Repository pandas-dev/pandas, pull requests merged in 2018-04, with the labels that each got.

#20569 BUG: Fix first_last_valid_index, now preserves the frequency.
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/series/test_timeseries.py
Labels: Bug, Frequency, Indexing

#20558 BUG: usecols kwarg accepts string when it should only allow list-like or callable.
  doc/source/io.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/parsers.pyx
  pandas/io/parsers.py
  pandas/tests/io/parser/usecols.py
Labels: Error Reporting, IO CSV

#20571 BUG: .unique() on MultiIndex: preserve names
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/indexes/multi.py
  pandas/tests/indexes/test_multi.py
Labels: Bug, MultiIndex

#18600 BUG: Fix initialization of DataFrame from dict with NaN as key
  asv_bench/benchmarks/frame_ctor.py
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals.py
  pandas/core/series.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/io/test_excel.py
Labels: Dtypes, Missing-data

#20577 TST: remove skip for values/index length mismatch in ExtensionArray tests
  pandas/tests/extension/base/constructors.py
Labels: ExtensionArray, Testing

#20506 Move GroupBy to Submodule and Add FutureWarning
  pandas/core/api.py
  pandas/core/generic.py
  pandas/core/groupby/__init__.py
  pandas/core/groupby/groupby.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/test_transform.py
  pandas/tests/test_resample.py
Labels: Groupby, Refactor

#20581 BUG: Series[EA].astype(str) works
  pandas/core/internals.py
  pandas/tests/extension/base/casting.py
  pandas/tests/extension/json/test_json.py
Labels: Dtypes, ExtensionArray

#20580 BUG: Fixed Series.align(frame) with ExtensionArray
  pandas/core/dtypes/cast.py
  pandas/tests/extension/base/reshaping.py
Labels: ExtensionArray, Missing-data, Reshaping

#20563 CLN: Use new-style classes instead of old-style classes
  ci/lint.sh
  pandas/_version.py
  pandas/io/common.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_constants.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/indexing/test_panel.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/test_errors.py
  pandas/tests/test_resample.py
  scripts/validate_docstrings.py
  versioneer.py
Labels: Style

#20152 DOC: update pandas.DataFrame.boxplot docstring. Fixes #8847
  pandas/plotting/_core.py
Labels: Docs

#20537 BUG: Presence of softlink in HDF5 file breaks HDFStore.keys() (GH20523)
  doc/source/whatsnew/v0.23.0.txt
  pandas/io/pytables.py
  pandas/tests/io/test_pytables.py
Labels: Data IO, IO HDF5

#20538 ERR: Better error message for missing matplotlib
  doc/source/whatsnew/v0.23.0.txt
  pandas/plotting/_core.py
  pandas/tests/plotting/test_misc.py
  pandas/util/_test_decorators.py
Labels: Visualization

#20564 ENH/DOC: update pandas-gbq signature and docstring
  doc/source/conf.py
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/io/gbq.py
Labels: Docs, IO Google

#20593 Safely raise errors when object contains unicode
  doc/source/whatsnew/v0.23.0.txt
  pandas/tests/util/test_testing.py
  pandas/util/testing.py
Labels: Testing, Unicode

#20645 MAINT: Remove console encode
  pandas/io/formats/printing.py
  pandas/tests/io/formats/test_printing.py
Labels: Clean

#20632 DOC: clean io.rst codeblocks for PEP8
  doc/source/io.rst
Labels: Docs, Style

#20510 API/BUG: Enforce "normalized" pytz timezones for DatetimeIndex
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pyx
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/test_resample.py
Labels: Bug, Resample, Timezones

#20651 BUG: Add uint64 support to IntervalTree
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: Bug, Dtypes, Interval

#20365 TST: fixtures for timezones
  pandas/conftest.py
  pandas/tests/dtypes/test_cast.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/test_base.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/scalar/timestamp/test_timezones.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/util/_test_decorators.py
Labels: Testing, Timezones

#20689 Updated URL for spam test
  pandas/tests/io/test_html.py
Labels: IO HTML, Testing

#20655 Np Any/All Transformation Bug
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/base.py
  pandas/tests/groupby/test_transform.py
Labels: Bug, Groupby, Missing-data

#19220 Adding (DEPRECATED) prefix to deprecated objects summary in the documentation
  doc/source/conf.py
Labels: Docs

#20540 DOC: Plans for 2.7
  doc/source/install.rst
  doc/source/whatsnew/v0.23.0.txt
Labels: Docs

#18902 DEPR: convert_datetime64 parameter in to_records()
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/tests/frame/test_convert_to.py
Labels: Deprecate, Dtypes

#20703 PERF: enhance MultiIndex.remove_unused_levels when no levels are unused
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/indexes/multi.py
Labels: MultiIndex, Performance

#20704 Revert DOC/CI: temp pin matplotlib for doc build #20045
  ci/requirements-3.6_DOC.run
Labels: Docs

#20691 BUG: Series.is_unique has extra output if contains objects with __ne__ defined
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/src/util.pxd
  pandas/tests/series/test_analytics.py
Labels: Compat, Indexing

#20702 DOC: Addition to pd.DataFrame.assign() docstring (#20085)
  pandas/core/frame.py
Labels: Docs, Indexing

#20705 HDFStore.select_column error reporting
  doc/source/whatsnew/v0.23.0.txt
  pandas/io/pytables.py
  pandas/tests/io/test_pytables.py
Labels: Error Reporting, IO HDF5

#19907 ENH: ExtensionArray.setitem
  pandas/core/frame.py
  pandas/core/indexing.py
  pandas/core/internals.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/test_json.py
Labels: ExtensionArray, Indexing

#20698 DEP: Add 'python_requires' to setup.py to drop 3.4 support
  ci/environment-dev.yaml
  ci/requirements_dev.txt
  doc/source/install.rst
  doc/source/whatsnew/v0.23.0.txt
  setup.py
Labels: Build

#20708 DOC: Correct documentation to GroupBy.rank
  pandas/core/groupby/groupby.py
Labels: Docs

#20584 API: rolling.apply will pass Series to function
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/window.pyx
  pandas/core/generic.py
  pandas/core/window.py
  pandas/tests/test_window.py
Labels: API Design, Reshaping

#20582 TST: add tests for take() on empty arrays
  pandas/core/arrays/base.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
Labels: Algos, ExtensionArray

#20461 CLN: Replacing %s with .format in pandas/core/frame.py
  pandas/core/frame.py
Labels: Clean

#20715 DOC: Change the indent for the pydoc of apply() function.
  pandas/core/series.py
Labels: Docs

#20718 PKG: remove pyproject.toml for now
  pyproject.toml
Labels: Build

#20741 DOC: use apply(raw=True) in docs to silence warning
  doc/source/computation.rst
  doc/source/cookbook.rst
Labels: Docs

#20738 Fix more tests expecting little-endian
  pandas/tests/dtypes/test_cast.py
  pandas/tests/frame/test_convert_to.py
  pandas/tests/indexes/period/test_formats.py
Labels: Compat, Testing

#20736 DOC: add coverage href to README.md
  README.md
Labels: Docs

#20730 DEPR: Deprecate DatetimeIndex.offset in favor of DatetimeIndex.freq
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/datetimes/test_setops.py
Labels: Deprecate, Frequency

#19021 ENH: DataFrame.append preserves columns dtype if possible
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/reshape/test_pivot.py
Labels: Dtypes, Reshaping

#20749 DOC: Clean up badges in README
  README.md
Labels: Docs

#20677 BUG: fixes indexing with monotonic decreasing DTI (#19362)
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
Labels: Bug, Indexing, Timeseries

#20707 DOC: Various EA docs
  doc/source/extending.rst
  doc/source/install.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/arrays/base.py
Labels: Docs, ExtensionArray

#20732 BUG: unexpected assign by a single-element list (GH19474)
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing

#20549 Fixed WOM offset when n=0
  doc/source/api.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Enhancement, Frequency

#20781 TST: split test_groupby.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/common.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_functional.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_nth.py
  pandas/tests/groupby/test_rank.py
  pandas/tests/groupby/test_transform.py
Labels: Groupby, Testing

#20745 Fix pd.merge to preserve ExtensionArrays dtypes
  pandas/core/dtypes/common.py
  pandas/core/internals.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/test_decimal.py
Labels: ExtensionArray

#20780 Accessor registry
  pandas/core/accessor.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/test_register_accessor.py
  scripts/validate_docstrings.py
Labels: Compat

#19657 DOC: removed vendored IPython.sphinxext - take 2
  ci/requirements-optional-conda.txt
  ci/requirements-optional-pip.txt
  doc/source/conf.py
  doc/sphinxext/ipython_sphinxext/__init__.py
  doc/sphinxext/ipython_sphinxext/ipython_console_highlighting.py
  doc/sphinxext/ipython_sphinxext/ipython_directive.py
Labels: Docs

#20746 TST: correct constructor in extension array tests
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
Labels: ExtensionArray

#20799 BUG: Coerce to object for mixed concat
  pandas/core/dtypes/concat.py
  pandas/tests/extension/base/reshaping.py
Labels: ExtensionArray, Reshaping

#20795 DOC/API: expose ExtensionArray in public api
  doc/source/api.rst
  doc/source/extending.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/api/extensions/__init__.py
  pandas/core/arrays/base.py
  pandas/core/common.py
Labels: Docs, ExtensionArray

#20782 DEPR: remove v018 resample compatibilitiy
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/resample.py
  pandas/tests/test_resample.py
Labels: Compat, Resample

#20790 DOC: add concatenation-section to text.rst
  doc/source/text.rst
  pandas/core/strings.py
Labels: Docs, Strings

#20786 BUG: Switch more size_t references to int64_t
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/src/parser/tokenizer.c
Labels: 32bit, Compat, IO CSV

#20624 TST: Parametrized index tests
  pandas/conftest.py
  pandas/tests/indexes/test_base.py
Labels: Dtypes, Indexing, Testing

#20544 Deprecated Index.get_duplicates()
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/reshape/concat.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_multi.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
Labels: Deprecate

#20794 TST: ExtensionArrays disallow .values attribute
  pandas/core/arrays/base.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
Labels: ExtensionArray

#20672 BUG: Fixed exception when Series.str.get is used with dict values and the index is not an existing key (#20671)
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/strings.py
  pandas/tests/test_strings.py
Labels: Bug, Strings

#20667 DOC: Updated the docstring of pandas.Series.str.get
  pandas/core/strings.py
Labels: Docs, Strings

#20497 Add interpolation options to rolling quantile
  asv_bench/benchmarks/rolling.py
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/window.pyx
  pandas/core/frame.py
  pandas/core/series.py
  pandas/core/window.py
  pandas/tests/test_window.py
Labels: Enhancement, Reshaping

#20811 Fixed typo
  doc/source/indexing.rst
Labels: Docs

#20797 BUG: fix to_latex() when using MultiIndex with NaN in (#14249) (v2)
  doc/source/whatsnew/v0.23.0.txt
  pandas/io/formats/latex.py
  pandas/tests/io/formats/test_to_latex.py
Labels: Bug, IO LaTeX

#20522 PERF: GH2003 Series.isin for categorical dtypes
  asv_bench/benchmarks/categoricals.py
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/categorical/test_algos.py
Labels: Categorical, Performance

#20721 DEPR: Series ndarray properties (strides, data, base, itemsize, flags)
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/algorithms.py
  pandas/core/base.py
  pandas/core/indexes/base.py
  pandas/core/internals.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_multi.py
  pandas/tests/indexes/test_range.py
  pandas/tests/internals/test_internals.py
  pandas/tests/test_base.py
Labels: Deprecate

#20823 DOC: Removed duplicate returns section
  pandas/core/window.py
Labels: Docs

#20827 TST: Fixed failures in JSON asserts
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
Labels: ExtensionArray

#20819 Change _can_hold_na to a class attribute and document that it shouldn't be changed
  pandas/core/arrays/base.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/conftest.py
Labels: ExtensionArray

#20813 CLN: Continued indexes/test_base.py cleanup
  pandas/tests/indexes/test_base.py
Labels: Indexing, Testing

#20814 ExtensionArray.take default implementation
  pandas/api/extensions/__init__.py
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/missing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals.py
  pandas/core/series.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/test_take.py
Labels: ExtensionArray, Indexing

#20847 DOC: small whatsnew fixes [ci skip]
  doc/source/whatsnew/v0.23.0.txt
Labels: Docs

#20840 BUG: concat of Series of EA and other dtype fails
  pandas/core/dtypes/concat.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/category/test_categorical.py
Labels: Bug, ExtensionArray

#20872 DOC: Link to new PyPI instead of legacy PyPI
  README.md
  doc/source/contributing.rst
  doc/source/index.rst.template
  doc/source/install.rst
  doc/source/release.rst
  pandas/core/frame.py
  pandas/io/clipboard/__init__.py
  versioneer.py
Labels: Docs

#20841 BUG/DEPR: deprecate Categorical take default behaviour + fix Series[categorical].take
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/arrays/categorical.py
  pandas/core/series.py
  pandas/tests/categorical/conftest.py
  pandas/tests/categorical/test_algos.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Categorical, Indexing

#20874 DOC: Fix read_hdf docstring
  pandas/io/pytables.py
Labels: Docs, IO HDF5

#20865 PERF: Fixed regression in Series(index=idx) constructor
  pandas/core/series.py
  pandas/tests/series/test_constructors.py
Labels: Performance
