Repository pandas-dev/pandas, pull requests merged in 2018-08, with the labels that each got.

#22142 Fix zillion deprecation warnings in core.dtypes.common
  pandas/core/dtypes/common.py
Labels: Compat, Deprecate

#22149 Catch IntervalIndex.itemsize deprecation warning in tests and remove IntervalArray.itemsize
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Interval

#22108 BUG: DataFrame.replace with out of bound datetime causing RecursionError
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/frame/test_replace.py
Labels: Bug, Reshaping

#22074 [Bug] Fix various DatetimeIndex comparison bugs
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/datetimes.py
  pandas/core/ops.py
  pandas/tests/frame/test_operators.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/series/test_operators.py
Labels: Bug, Timeseries

#22139 [TST] make xfails strict
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/integer/test_integer.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_duplicates.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/multi/test_missing.py
  pandas/tests/indexes/period/test_arithmetic.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_rank.py
  pandas/tests/sparse/frame/test_analytics.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/frame/test_indexing.py
  pandas/tests/sparse/series/test_indexing.py
  pandas/tests/test_algos.py
  pandas/tests/test_base.py
  pandas/tests/test_downstream.py
  pandas/tests/test_window.py
Labels: Testing

#22081 DOC: clarify default behavior for categories ordering
  pandas/core/arrays/categorical.py
Labels: Categorical, Docs, MultiIndex

#22155 Fix deprecation warning in SeriesGroupBy.count
  pandas/core/groupby/generic.py
Labels: Compat

#22147 use memoryviews instead of ndarrays
  pandas/_libs/hashing.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pyx
Labels: Compat

#22125 BUG: Better handling of invalid na_option argument for groupby.rank
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_rank.py
Labels: Error Reporting, Reshaping

#21775 Fix categorical from codes nan 21767
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_constructors.py
Labels: Categorical, Error Reporting

#22164 CLN: Use public method to capture UTC offsets
  pandas/_libs/tslib.pyx
Labels: Clean, Timezones

#22039 BUG: Matplotlib scatter datetime
  doc/source/whatsnew/v0.24.0.txt
  pandas/plotting/_converter.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Visualization

#19119 DEPR: Removing previously deprecated datetools module (#6581)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/api.py
  pandas/core/datetools.py
  pandas/tests/api/test_api.py
Labels: Deprecate, Timeseries

#21954 DEPR: pd.read_table
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/io/clipboards.py
  pandas/io/parsers.py
  pandas/tests/io/conftest.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parsers.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/test_common.py
  pandas/tests/test_multilevel.py
Labels: Data IO, Deprecate

#19973 fix: scalar timestamp assignment (#19843)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/tests/frame/test_indexing.py
Labels: Dtypes, Timeseries, Timezones

#22176 DOC: update the Series.str.contains docstring
  pandas/core/strings.py
Labels: Docs

#22175 DOC: updating the Series.str.cat docstring
  pandas/core/strings.py
Labels: Docs

#22179 Documentation: typo fixes in MultiIndex / Advanced Indexing
  doc/source/advanced.rst
Labels: Docs, Indexing

#22184 CI: Fix Travis failures due to lint.sh on pandas/core/strings.py
  pandas/core/strings.py
Labels: CI

#22165 TST: Check DatetimeIndex.drop on DST boundary
  pandas/tests/indexes/datetimes/test_timezones.py
Labels: Testing, Timeseries, Timezones

#22198 BUG: DataFrame.asof() : Timezone Awareness / Naivety comparison TypeError
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/tests/frame/test_asof.py
Labels: Dtypes, Indexing, Timeseries

#22214 DOC: Added 0.23.4 whatsnew [ci skip]
  doc/source/whatsnew.rst
Labels: Docs

#22196 Finish moving period_helper to cython
  ci/lint.sh
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/src/datetime/np_datetime.c
  pandas/_libs/tslibs/src/datetime/np_datetime.h
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.c
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.h
  pandas/_libs/tslibs/src/period_helper.c
  pandas/_libs/tslibs/src/period_helper.h
  pandas/_libs/tslibs/timedeltas.pyx
  setup.py
Labels: Clean, Period

#22223 Fix test_info_repr #21746
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting, Testing

#22083 BUG: maximum recursion error when replacing empty lists
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/tests/frame/test_replace.py
  pandas/tests/series/test_replace.py
Labels: Bug, Reshaping

#22146 Replace (private) _checknull with (public) is_nan
  pandas/_libs/hashing.pyx
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pyx
  pandas/_libs/ops.pyx
  pandas/_libs/parsers.pyx
  pandas/_libs/skiplist.pyx
  pandas/_libs/src/inference.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/util.pxd
  pandas/_libs/writers.pyx
Labels: Clean, Missing-data

#22153 ~Finish collecting m8[ns] tests, start collecting division by zero tests
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/test_arithmetic.py
Labels: Testing, Timedelta

#22237 Collect datetime64 and PeriodDtype arithmetic tests
  pandas/tests/arithmetic/__init__.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/period/test_arithmetic.py
  pandas/tests/series/test_arithmetic.py
Labels: Period, Testing, Timeseries

#22232 BUG: Fix DataFrame construction regression
  doc/source/whatsnew/v0.23.5.txt
  pandas/core/frame.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, Regression

#22219 [CLN] Merge inference into lib.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/src/inference.pyx
  pandas/_libs/src/parse_helper.h
  setup.py
Labels: Clean, Internals

#22217 Add missing period to pandas.Series.interpolate docstring
  pandas/core/generic.py
Labels: Docs

#22209 API/CLN: Have toplevel pd.pivot mirror pivot instead of pivot_simple
  pandas/core/frame.py
  pandas/core/reshape/api.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/test_panel.py
Labels: API Design, Clean

#22181 Standardize special case in tz_conversion functions
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/strptime.pyx
Labels: Clean, Timezones

#21906 Change ._data to ._parent for accessors
  pandas/core/arrays/categorical.py
  pandas/core/indexes/accessors.py
  pandas/core/strings.py
  pandas/plotting/_core.py
Labels: Clean

#22174 DOC: update the Series.str.join docstring
  pandas/core/strings.py
Labels: Docs, Strings

#22245 CLN: remove redundant call to ensure_index
  pandas/core/frame.py
Labels: Clean, Indexing

#22230 BUG: raise KeyError if MultiIndex.get_loc_level is asked unused label
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/multi.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/indexes/multi/test_indexing.py
Labels: Bug, MultiIndex

#22251 DOC: Add missing question mark in README
  README.md
Labels: Docs

#22254 Implement arithmetic.test_numeric and arithmetic.test_object
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_operators.py
  pandas/tests/test_arithmetic.py
Labels: Testing

#22253 Resampling with NaT in TimedeltaIndex raises MemoryError
  doc/source/whatsnew/v0.23.5.txt
  pandas/core/resample.py
  pandas/tests/test_resample.py
Labels: Bug, Resample, Timedelta

#22169 BUG: Fix using "inf"/"-inf" in na_values for csv with int index column
  doc/source/whatsnew/v0.23.5.txt
  pandas/core/algorithms.py
  pandas/tests/io/parser/na_values.py
Labels: IO CSV, Numeric

#22207 BUG: treat nan-objects the same way float64-nans are treated - all na…
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/src/klib/khash_python.h
  pandas/tests/indexes/test_base.py
  pandas/tests/test_algos.py
Labels: Algos, Missing-data

#21477 BUG: inconsistency between replace dict using integers and using strings (#20656)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/series/test_replace.py
Labels: Bug, Compat, Strings

#22187 DOC: Update the Series.str.len docstring
  pandas/core/strings.py
Labels: Docs, Strings

#22132 Add timetz attribute to DatetimeIndex
  doc/source/api.rst
  doc/source/timeseries.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslib.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/scalar/timestamp/test_timezones.py
  pandas/tests/series/test_datetime_values.py
Labels: Enhancement, Timezones

#22235 Assorted _libs cleanups
  pandas/_libs/algos_common_helper.pxi.in
  pandas/_libs/algos_take_helper.pxi.in
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/_libs/lib.pyx
  pandas/_libs/ops.pyx
  pandas/_libs/sparse.pyx
  pandas/_libs/sparse_op_helper.pxi.in
  pandas/_libs/src/compat_helper.h
  pandas/_libs/src/inline_helper.h
  pandas/_libs/src/klib/khash.h
  pandas/_libs/src/numpy_helper.h
  pandas/_libs/src/parse_helper.h
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
  pandas/_libs/src/skiplist.h
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/src/datetime/np_datetime.c
  pandas/_libs/tslibs/src/datetime/np_datetime.h
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/util.pxd
  pandas/_libs/util.pxd
  pandas/tests/tseries/offsets/test_fiscal.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Style

#22267 Continue Collecting Arithmetic Tests
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_operators.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_operators.py
  pandas/tests/test_arithmetic.py
Labels: Clean, Testing

#22182 implement masked_arith_op to de-duplicate ops code
  pandas/core/ops.py
Labels: Algos, Refactor

#22117 CLN: Remove special handling of nans in the float64-case of isin
  asv_bench/benchmarks/series_methods.py
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Indexing, Numeric

#21902 TST/CLN: correctly skip in indexes/common; add test for duplicated
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexes/test_range.py
Labels: Testing

#22161 BUG: ensuring that np.asarray() simple handles data as objects and doesn't…
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Bug, Compat, Indexing

#20170 DOC: update the pandas.DataFrame.plot.area docstring
  pandas/plotting/_core.py
Labels: Docs

#22072 fix for TypeError: unorderable types" in when using set_index with multiple column names
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/categorical.py
  pandas/tests/indexes/multi/test_constructor.py
Labels: Bug, IO LaTeX, MultiIndex

#22213 Fix Python2 test failures in certain locales
  pandas/tests/util/test_util.py
  pandas/util/testing.py
Labels: 2/3 Compat

#21896 DEPR: Deprecate Series.to_csv signature
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/io/test_compression.py
  pandas/tests/series/test_io.py
Labels: Compat, IO CSV

#22310 DOC/DEPR: clarify argmin/argmax deprecation message
  pandas/core/series.py
Labels: Docs

#22322 CLN: Remove variable assignment on CI script
  ci/print_skipped.py
Labels: Clean, Testing

#22307 DOC: fixes to DataFrame.plot.area docstring
  pandas/plotting/_core.py
Labels: Docs

#22327 CLN: Parameterize test case
  pandas/tests/scalar/timestamp/test_unary_ops.py
Labels: Testing, Timeseries

#22321 CLN: Remove unused method
  pandas/core/indexes/multi.py
Labels: Clean, Indexing, MultiIndex

#22163 dispatch scalar DataFrame ops to Series
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/ops.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_operators.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/internals/test_internals.py
  pandas/tests/test_arithmetic.py
  pandas/tests/test_expressions.py
Labels: Algos, Refactor

#22331 BUG: Interval scalar arithmetic operations reset closed
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/interval.pyx
  pandas/tests/scalar/interval/test_interval.py
Labels: Interval

#22064 TST: suppress deprecation warnings for compress
  pandas/core/series.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_api.py
Labels: Deprecate, Testing

#22368 DOC: edit docstring example to prevent segfault (#21824)
  pandas/core/frame.py
Labels: Docs

#22371 [CLN] remove last cython: nprofile comments
  pandas/_libs/algos.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/hashing.pyx
  pandas/_libs/hashtable.pyx
  pandas/_libs/index.pyx
  pandas/_libs/indexing.pyx
  pandas/_libs/join.pyx
  pandas/_libs/khash.pxd
  pandas/_libs/missing.pxd
  pandas/_libs/missing.pyx
  pandas/_libs/reduction.pyx
  pandas/_libs/reshape.pyx
  pandas/_libs/skiplist.pxd
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/ccalendar.pxd
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/frequencies.pxd
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
  pandas/_libs/window.pyx
Labels: Clean

#22354 Grab timezones appropriately in timetz test
  pandas/tests/series/test_datetime_values.py
Labels: Testing, Timezones

#22349 Drop redundant TestLocale
  pandas/tests/util/test_testing.py
  pandas/tests/util/test_util.py
Labels: Clean, Testing

#22344 [CLN] Make more of numpy_helper unnecessary
  pandas/_libs/index.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/src/numpy_helper.h
  pandas/_libs/util.pxd
Labels: Clean, Internals

#22320 Bump pytest
  ci/environment-dev.yaml
  ci/requirements_dev.txt
  doc/source/contributing.rst
  doc/source/install.rst
  doc/source/whatsnew/v0.23.5.txt
  setup.cfg
Labels: Dependencies, Testing

#22269 Replace tar_csv.tar.gz with gzipped tar
  pandas/tests/io/parser/data/tar_csv.tar.gz
Labels: Data IO, Testing

#20061 Add tests for docstring Validation Script + py27 compat
  pandas/tests/scripts/__init__.py
  pandas/tests/scripts/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs, Testing

#22378 Fix and test scalar extension dtype op corner case
  pandas/core/ops.py
  pandas/tests/arithmetic/test_object.py
Labels: Bug, ExtensionArray

#22298 Use a more helpful error message for invalid correlation methods in DataFrame.corr
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Error Reporting

#20270 DOC: update the pandas.Series/DataFrame.interpolate docstring
  pandas/core/generic.py
Labels: Docs

#22363 DOC: update doc-string in Index.rename
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_get_set.py
Labels: Docs

#22418 Remove weird comment in parse_dates.py
  pandas/tests/io/parser/parse_dates.py
Labels: Clean

#22424 CI: add missing tzlocal dependency (rpy2, doc build)
  ci/travis-36-doc.yaml
Labels: Docs

#22157 BUG: make conftest._cython_table deterministic for Python<3.6
  pandas/conftest.py
  pandas/core/base.py
Labels: Testing

#22417 DEPR: Rename reps to repeats in Series.repeat
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/series.py
  pandas/tests/series/test_analytics.py
Labels: Clean, Deprecate

#22406 CLN: dedent else part of Series._get_with
  pandas/core/series.py
Labels: Clean, Internals

#22070 Split fastpath IntegerArray constructor and general purpose constructor
  pandas/core/arrays/__init__.py
  pandas/core/arrays/integer.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/integer/test_integer.py
Labels: ExtensionArray, Needs Discussion

#22343 API: dispatch to EA.astype
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/integer.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/integer/test_integer.py
Labels: Dtypes, ExtensionArray

#22287 [CLN] More Misc Cleanups in _libs
  pandas/_libs/algos.pxd
  pandas/_libs/algos.pyx
  pandas/_libs/algos_common_helper.pxi.in
  pandas/_libs/groupby.pyx
  pandas/_libs/hashing.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/_libs/reduction.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
  pandas/_libs/window.pyx
Labels: Clean, Internals

#22345 API: ExtensionDtype._is_numeric
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/integer.py
  pandas/core/dtypes/base.py
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/integer/test_integer.py
  pandas/tests/frame/test_block_internals.py
Labels: Dtypes, ExtensionArray, Numeric

#22413 BLD: Install scripts tests only during inplace
  pandas/tests/scripts/test_validate_docstrings.py
Labels: Bug, Build

#22419 DOC: fix Dataframe.to_records examples
  ci/doctests.sh
  pandas/core/frame.py
Labels: Docs

#22456 MAINT: Reset sys.path if docstrings import fails
  pandas/tests/scripts/test_validate_docstrings.py
Labels: Testing

#22455 CLN: Lint for comprehension codes
  ci/lint.sh
Labels: Clean

#22441 BUG fix IntegerArray.astype int -> uint
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/integer.py
  pandas/tests/extension/integer/test_integer.py
Labels: Bug, ExtensionArray

#22380 BUG: fix read_csv to parse timezone correctly
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/parsers.py
  pandas/tests/io/parser/parse_dates.py
Labels: IO CSV, Timezones

#22357 Fix index locator cast bool key to float.
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/numeric.py
  pandas/tests/indexes/test_numeric.py
Labels: Error Reporting, Indexing, MultiIndex

#22365 Resampler.__iter__() not working
  doc/source/groupby.rst
  doc/source/timeseries.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/resample.py
  pandas/tests/test_resample.py
Labels: Compat, Groupby, Resample

#22329 CLN: de-duplicate index validation code
  pandas/_libs/index.pyx
  pandas/_libs/util.pxd
Labels: Clean, Indexing

#22304 ENH: add quantile method to resample
  doc/source/api.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/tests/test_resample.py
Labels: Enhancement, Resample

#22415 DEPR: Error with ambiguous groupby strings
  doc/source/groupby.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/reshape/merge.py
  pandas/tests/frame/test_sort_values_level_as_str.py
  pandas/tests/generic/test_label_or_level_utils.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_index_as_string.py
  pandas/tests/reshape/merge/test_merge_index_as_string.py
  pandas/tests/reshape/test_pivot.py
Labels: Deprecate, Groupby

#22464 DOC: confusing wording in Dataframe.quantile, term 'a la`
  pandas/core/frame.py
Labels: Docs

#22390 Fix arithmetic errors with timedelta64 dtypes
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/core/indexes/range.py
  pandas/core/ops.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/test_arithmetic.py
Labels: Bug, Timedelta

#22387 Support NDFrame.shift with EAs
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/base.py
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/methods.py
Labels: ExtensionArray

#22377 BUG: Fix DataFrame.apply for string arg with additional args (#22376)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/apply.py
  pandas/tests/frame/test_apply.py
Labels: Bug, Numeric, Reshaping

#22394 Bug in DataFrame.drop_duplicates for empty DataFrame throws error
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/tests/frame/test_duplicates.py
Labels: Bug, Reshaping

#22423 BUG: Ignore versionadded directive when checking for periods at docstring end
  pandas/tests/scripts/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#22457 BUG: Retain timezone information in to_datetime if box=False
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/test_algos.py
Labels: Bug, Timezones

#22474 DOC: Updating Series.agg docstring
  ci/doctests.sh
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs

#22499 CI: Bump to NumPy compat to 1.9.3
  ci/circle-27-compat.yaml
  ci/travis-27-locale.yaml
Labels: CI

#22280 Add initial property-based tests using Hypothesis
  .gitignore
  ci/appveyor-27.yaml
  ci/appveyor-36.yaml
  ci/check_imports.py
  ci/circle-27-compat.yaml
  ci/circle-35-ascii.yaml
  ci/circle-36-locale.yaml
  ci/circle-36-locale_slow.yaml
  ci/environment-dev.yaml
  ci/requirements_dev.txt
  ci/travis-27-locale.yaml
  ci/travis-27.yaml
  ci/travis-35-osx.yaml
  ci/travis-36-doc.yaml
  ci/travis-36-numpydev.yaml
  ci/travis-36-slow.yaml
  ci/travis-36.yaml
  ci/travis-37.yaml
  doc/source/contributing.rst
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/conftest.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/util/_tester.py
Labels: Testing

#22503 CLN: Remove versionadded in groupby.rst
  doc/source/groupby.rst
Labels: Clean, Docs

#22530 CLN: remove unused np version check
  pandas/_libs/reduction.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/timestamps.pxd
Labels: Clean

#22520 TST: Streaming of S3 files
  pandas/tests/io/test_s3.py
Labels: Data IO, Testing

#22494 CLN: Simplify read_csv tz offset parsing
  pandas/io/parsers.py
Labels: Clean, IO CSV

#22467 TEST: groupby(as_index=False, sort=False).aggregate formerly (?) gave unexpected results with a list-like function
  pandas/tests/groupby/aggregate/test_other.py
Labels: Groupby, Testing

#22469 remove numpy_helper and some unneeded util functions
  pandas/_libs/index.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/reduction.pyx
  pandas/_libs/src/numpy_helper.h
  pandas/_libs/util.pxd
  pandas/core/sparse/array.py
  setup.py
Labels: Clean

#22436 BUG #19860 Corrected use of mixed indexes with .at
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/core/indexing.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_scalar.py
Labels: Bug, Indexing

#21548 style.bar: add support for axis=None (tablewise application instead of rowwise or columnwise)
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/formats/style.py
  pandas/tests/io/formats/test_style.py
Labels: IO HTML, Output-Formatting

#22513 CLN: use self.dtype internally in Categorical
  pandas/core/arrays/categorical.py
Labels: Categorical, Clean

#22548 Typo: UCT -> UTC
  doc/source/timeseries.rst
Labels: Docs, Timezones

#22547 CLN: use 'codes' rather than 'values' internally in Categorical
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
Labels: Categorical, Clean

#22522 Updated condition to skip for pytables build issue on numpy 1.15 #22098
  pandas/compat/numpy/__init__.py
  pandas/tests/io/test_pytables.py
Labels: Testing

#22508 BUG: silent overflow in DateTimeArray subtraction
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/datetimes.py
  pandas/tests/arithmetic/test_datetime64.py
Labels: Bug, Timedelta

#22264 DEPR: list-likes of list-likes in str.cat
  doc/source/text.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/strings.py
  pandas/tests/test_strings.py
Labels: Deprecate, Strings
