Repository pandas-dev/pandas, pull requests merged in 2018-11, with the labels that each got.

#23388 style: fix import format at pandas/core/computation
  pandas/core/computation/align.py
  pandas/core/computation/check.py
  pandas/core/computation/common.py
  pandas/core/computation/engines.py
  pandas/core/computation/eval.py
  pandas/core/computation/expr.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
  setup.cfg
Labels: Style

#23402 BUG: Respect axis when doing DataFrame.expanding
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/window.py
  pandas/tests/test_window.py
Labels: Bug, Window

#19831 Fix to_csv of DataFrame with single level multiindex.
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/multi.py
  pandas/tests/io/formats/test_to_csv.py
Labels: IO CSV, MultiIndex, Output-Formatting

#22535 DEPR: deprecate integer add/sub with DTI/TDI/PI/Timestamp/Period
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/resample.py
  pandas/plotting/_converter.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/test_resample.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Deprecate, Numeric, Timeseries

#23405 DOC: Add DateOffsets to api.rst
  doc/source/api.rst
Labels: Docs, Timedelta

#23387 style: fix import format at pandas/core/reshape
  pandas/core/reshape/api.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/reshape/tile.py
  pandas/core/reshape/util.py
  setup.cfg
Labels: Style

#23112 Deprecate read_feather nthreads argument + update feather-format to pyarrow.feather
  ci/azure-windows-36.yaml
  ci/requirements-optional-conda.txt
  ci/requirements-optional-pip.txt
  ci/travis-27.yaml
  ci/travis-36-doc.yaml
  ci/travis-36.yaml
  ci/travis-37.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/feather_format.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_feather.py
Labels: Data IO, Deprecate

#23442 TST: Skip 32bit failing IntervalTree tests
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: 32bit, Interval, Testing

#23435 BUG: fix HDFStore.append with all empty strings error (GH12242)
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/pytables.py
  pandas/tests/io/test_pytables.py
Labels: Bug, IO HDF5

#23441 TST: tweak Hypothesis configuration and idioms
  pandas/conftest.py
  pandas/tests/frame/test_apply.py
Labels: CI, Testing

#23456 REF: cython cleanup, typing, optimizations
  pandas/_libs/algos_common_helper.pxi.in
  pandas/_libs/groupby_helper.pxi.in
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pxd
  pandas/_libs/reduction.pyx
  pandas/_libs/sparse.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pyx
  pandas/_libs/window.pyx
Labels: Clean, Internals, Refactor

#23431 REF: strictness/simplification in DatetimeArray/Index _simple_new
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
Labels: API Design, Refactor, Timeseries

#23430 REF: Remove DatetimelikeArrayMixin._shallow_copy
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
Labels: Clean, Refactor, Timeseries

#23404 PERF: speed up concat on Series by skipping unnecessary DataFrame creation
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/core/reshape/concat.py
  pandas/tests/generic/test_generic.py
Labels: Performance, Reshaping

#23406 BUG/ENH: Handle NonexistentTimeError in date rounding
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/indexes/datetimelike.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/test_datetime_values.py
Labels: Bug, Timeseries, Timezones

#22890 DOC: updated the docstring of Series.dot
  pandas/core/series.py
Labels: Docs, Numeric

#23472 Fixing flake8 problems new to flake8 3.6.0
  doc/source/conf.py
  scripts/find_commits_touching_func.py
  scripts/find_undoc_args.py
Labels: CI, Style

#23433 REF: strictness and checks for Timedelta _simple_new
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/timedeltas.py
Labels: Dtypes, Internals, Timedelta

#23394 ENH: Add FrozenList.union and .difference
  doc/source/groupby.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/frozen.py
  pandas/tests/indexes/test_frozen.py
Labels: API Design, Enhancement, Frozen

#23460 BUG: Allow freq conversion from dt64 to period
  pandas/core/arrays/period.py
  pandas/tests/arrays/test_period.py
  pandas/tests/indexes/period/test_construction.py
Labels: Period, Timeseries

#23150 DOC: Add number of errors/warnings
  scripts/validate_docstrings.py
Labels: CI, Docs

#23032 Add cookbook entry for triangular correlation matrix (closes #22840)
  doc/source/cookbook.rst
Labels: Docs

#23469 DOC: clean doc string for NDFrame.astype
  pandas/core/generic.py
Labels: Docs

#22980 DOC: Documentation for pandas.core.indexes.api
  pandas/core/indexes/api.py
Labels: Docs

#23408 DOC: Clarify documentation of 'ambiguous' parameter
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
Labels: Docs, Timeseries

#23161 DOC: Validate in docstrings that numpy and pandas are not imported
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#22504 DOC: Updated docstrings related to DateTimeIndex. GH22459
  pandas/core/indexes/datetimes.py
Labels: Docs, Timeseries

#21034 DOC: Rephrased doc for Series.asof. Added examples
  pandas/core/generic.py
Labels: Docs

#23479 TST: drop tz-aware timestamp from DatetimIndex with DST transition
  doc/source/whatsnew/v0.24.0.txt
  pandas/tests/test_multilevel.py
Labels: Indexing, Testing, Timeseries

#23364 Isort contributing guide
  doc/source/contributing.rst
  setup.cfg
Labels: Docs

#23422 API: fix corner case of lib.infer_dtype
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pxd
  pandas/_libs/missing.pyx
  pandas/tests/dtypes/test_inference.py
Labels: Dtypes, Internals

#23399 ENH: Use flake8 to check for PEP8 violations in doctests
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs, Style

#23480 TST: Empty Series.reindex with tz-aware dtype
  doc/source/whatsnew/v0.24.0.txt
  pandas/tests/series/indexing/test_alter_index.py
Labels: Reshaping, Timeseries, Timezones

#23129 DOC: Fix creation of [source] links in the doc creation
  doc/source/conf.py
Labels: Bug, CI, Docs

#23476 DOC: Remove dead link and update links to https
  doc/source/basics.rst
  doc/source/comparison_with_sas.rst
  doc/source/comparison_with_sql.rst
  doc/source/contributing_docstring.rst
  doc/source/cookbook.rst
  doc/source/dsintro.rst
  doc/source/ecosystem.rst
  doc/source/index.rst.template
  doc/source/io.rst
  doc/source/options.rst
  doc/source/overview.rst
  doc/source/release.rst
  doc/source/tutorials.rst
Labels: Docs

#23202 DOC: fix DataFrame.nlargest and DataFrame.nsmallest doctests
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#23498 DOC: Fix syntax error in groupby docs
  doc/source/groupby.rst
Labels: Bug, CI, Docs

#23501 STYLE: Run Isort on tests-> util, series, arrays
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/arrays/categorical/test_sorting.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/series/test_duplicates.py
  pandas/tests/util/test_hashing.py
  pandas/tests/util/test_testing.py
  pandas/tests/util/test_util.py
  setup.cfg
Labels: Style

#23487 TST: Add test of assignment chaining and dupe cols
  pandas/tests/indexing/test_chaining_and_caching.py
Labels: Error Reporting, Indexing, Testing

#23462 BUG: Avoid casting to double type unnecessarily when setting values i…
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_timedelta.py
Labels: Bug, Indexing, Numeric, Timedelta

#23482 Bumping up min version for pyarrow
  ci/requirements-optional-conda.txt
  ci/requirements-optional-pip.txt
  ci/travis-27.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Data IO, Dependencies

#23497 CI: Exclude asv benchmark envs from flake8 checks
  setup.cfg
Labels: CI, Refactor, Style

#23518 Extraneous parts broken off from other DTA/TDA PRs
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Clean, Timeseries

#23486 Fixing typo in cython casting lint, and making it azure friendly
  ci/code_checks.sh
  pandas/_libs/algos.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/hashing.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/parsers.pyx
  pandas/_libs/reduction.pyx
  pandas/_libs/sparse.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/window.pyx
Labels: Bug, CI, Style

#23485 TST: Add test for mangling of unnamed columns
  pandas/tests/io/parser/mangle_dupes.py
Labels: IO CSV, Missing-data, Testing

#23443 API: change default for sep in str.cat (in docstring)
  pandas/core/strings.py
  pandas/tests/test_strings.py
Labels: API Design, Strings

#21947 BUG: fix df.where(cond) when cond is empty
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_indexing.py
Labels: Algos, Bug, Error Reporting

#23484 BUG: Fix of handle missing CSV MI column names
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/parsers.pyx
  pandas/io/parsers.py
  pandas/tests/io/parser/index_col.py
Labels: Bug, IO CSV, MultiIndex

#23495 BUG GH23451 Allow setting date in string index for Series
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/series.py
  pandas/tests/series/test_datetime_values.py
Labels: Indexing, Timeseries

#23463 BUG: fix groupby.transform rename bug (#23461)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_transform.py
Labels: Bug, Groupby

#23318 BUG: GroupBy return EA dtype
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/groupby/groupby.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/sparse/test_groupby.py
  pandas/tests/test_resample.py
Labels: ExtensionArray, Groupby

#23499 BUG - pd.concat with all Series on axis=1 ignores the `names` argument (Issue: 23490)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/reshape/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Bug, Reshaping

#19849 BUG: names on union and intersection for Index were inconsistent (GH9943 GH9862)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/conftest.py
  pandas/tests/indexes/test_base.py
  pandas/tests/reshape/test_concat.py
Labels: Bug, Indexing, Reshaping

#23529 DOC/TST: Fix warning in concat docstring
  pandas/core/reshape/concat.py
Labels: Docs

#23526 CI: Moving CI dependencies to "ci/deps"
  .circleci/config.yml
  .travis.yml
  ci/azure/linux.yml
  ci/azure/macos.yml
  ci/azure/windows-py27.yml
  ci/azure/windows.yml
  ci/deps/azure-27-compat.yaml
  ci/deps/azure-36-locale_slow.yaml
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-macos-35.yaml
  ci/deps/azure-windows-27.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/circle-36-locale.yaml
  ci/deps/travis-27-locale.yaml
  ci/deps/travis-27.yaml
  ci/deps/travis-36-doc.yaml
  ci/deps/travis-36-slow.yaml
  ci/deps/travis-36.yaml
  ci/deps/travis-37-numpydev.yaml
  ci/deps/travis-37.yaml
  ci/incremental/setup_conda_environment.cmd
Labels: CI, Dependencies

#23425 Fix+test timedelta64(nat) ops
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/indexes/base.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Algos, Bug, Error Reporting, Timedelta

#23534 Isort io and compat dirs
  pandas/compat/numpy/function.py
  pandas/compat/pickle_compat.py
  pandas/io/clipboard/clipboards.py
  pandas/io/clipboard/windows.py
  pandas/io/formats/console.py
  pandas/io/formats/csvs.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/formats/latex.py
  pandas/io/formats/printing.py
  pandas/io/formats/style.py
  pandas/io/formats/terminal.py
  pandas/io/json/json.py
  pandas/io/json/normalize.py
  pandas/io/json/table_schema.py
  pandas/io/sas/sas7bdat.py
  setup.cfg
Labels: Clean, Style

#23454 Fail Azure CI for failing tests
  ci/azure/linux.yml
  ci/azure/macos.yml
  ci/azure/windows-py27.yml
  ci/azure/windows.yml
  ci/deps/azure-macos-35.yaml
Labels: CI

#23514 Make validate_docstrings.py ready for the CI
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#23543 CI/DOC: Fixing bug in validate_docstrings.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#23503 BUG: Timestamp retains frequency of input Timestamps
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Frequency, Timeseries

#22852 BUG: DatetimeIndex slicing with boolean Index raises TypeError
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/test_base.py
Labels: Bug, Indexing

#23540 BUG: Return KeyError for invalid string key
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_indexing.py
Labels: Indexing, Period

#22888 TST: coverage for skipped tests in io/formats/test_to_html.py
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML, Testing

#23471 DOC: Updating DataFrame.join docstring
  pandas/core/frame.py
Labels: Docs, Reshaping

#23284 ENH: Support EAs in Series.unstack
  asv_bench/benchmarks/reshape.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/reshape/reshape.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/sparse/test_pivot.py
Labels: ExtensionArray, Reshaping

#23550 BUG: Fix error message for invalid HTML flavor
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: Bug, Error Reporting, IO HTML

#23562 remove uses of (ts)?lib.(NaT|iNaT|Timestamp)
  pandas/core/generic.py
  pandas/core/indexes/period.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_internals.py
  pandas/tests/series/test_replace.py
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Internals, Refactor

#23546 BUG: raise if invalid freq is passed
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/plotting/test_converter.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Frequency, Timeseries

#23468 TST: Fix dtype mismatch on 32bit in IntervalTree get_indexer test
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: 32bit, Interval, Testing

#23285 Preserve EA dtype in DataFrame.stack
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/internals/blocks.py
  pandas/core/reshape/reshape.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/sparse/frame/test_frame.py
Labels: ExtensionArray, Reshaping

#23523 CI: Auto-cancel redundant builds
  .circleci/config.yml
Labels: CI, Clean

#22654 ENH: Support writing timestamps with timezones with to_sql
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Enhancement, IO SQL, Timezones

#18953 DOC: Added note about groupby excluding Decimal columns by default
  doc/source/groupby.rst
Labels: Docs, Dtypes, Groupby

#23552 DOC/CI: Fixes to make validate_docstrings.py to not generate warnings or unwanted output
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/panel.py
  pandas/core/strings.py
  pandas/errors/__init__.py
  pandas/plotting/_misc.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#23507 Update description of Index._values/values/ndarray_values
  pandas/core/indexes/base.py
Labels: Docs, Internals

#23591 PERF: define is_all_dates to shortcut inadvertent copy when slicing an IntervalIndex
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Interval, Performance

#23589 PERF: Speeds up creation of Period, PeriodArray, with Offset freq
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
Labels: Performance, Period, Timeseries

#23603 CLN: remove values attribute from datetimelike EAs
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimes.py
  pandas/tests/extension/test_period.py
Labels: ExtensionArray

#23321 Support for partition_cols in to_parquet
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
  pandas/tests/util/test_testing.py
  pandas/util/testing.py
Labels: IO Parquet

#23197 DOC: Fix pandas.Series.resample docstring
  ci/code_checks.sh
  pandas/core/generic.py
Labels: Docs

#23600 DOC: Remove incorrect periods at the end of parameter types (#23597)
  pandas/core/dtypes/inference.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/io/clipboards.py
Labels: Clean, Docs

#23611 DOC: Fix Order of parameters in docstrings
  pandas/core/reshape/pivot.py
  pandas/core/window.py
  pandas/io/json/normalize.py
  pandas/tseries/offsets.py
  pandas/util/testing.py
Labels: Docs

#23583 CLN: use float64_t consistently instead of double, double_t
  pandas/_libs/algos.pxd
  pandas/_libs/algos.pyx
  pandas/_libs/algos_common_helper.pxi.in
  pandas/_libs/algos_rank_helper.pxi.in
  pandas/_libs/algos_take_helper.pxi.in
  pandas/_libs/groupby.pyx
  pandas/_libs/groupby_helper.pxi.in
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/index.pyx
  pandas/_libs/index_class_helper.pxi.in
  pandas/_libs/interval.pyx
  pandas/_libs/intervaltree.pxi.in
  pandas/_libs/join.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pyx
  pandas/_libs/parsers.pyx
  pandas/_libs/sparse.pyx
  pandas/_libs/sparse_op_helper.pxi.in
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/window.pyx
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/frame/test_operators.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/series/test_operators.py
Labels: Clean, Internals

#23544 BUG: Delegate more of Excel parsing to CSV
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/excel.py
  pandas/tests/io/test_excel.py
Labels: API Design, Bug, Enhancement, IO Excel

#23524 BUG: Casting tz-aware DatetimeIndex to object-dtype ndarray/Index
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/indexes/test_base.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/tseries/offsets.py
Labels: Timeseries, Timezones

#23522 BUILD: Simplifying contributor dependencies
  ci/code_checks.sh
  ci/environment-dev.yaml
  ci/requirements-optional-conda.txt
  ci/requirements_dev.txt
  doc/source/contributing.rst
  environment.yml
  requirements-dev.txt
  scripts/convert_deps.py
  scripts/generate_pip_deps_from_conda.py
Labels: Build, CI, Dependencies

#23620 TST: Fix xfailing DataFrame arithmetic tests by transposing
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/util/testing.py
Labels: Numeric, Testing

#23249 CLN:Remove unused **kwargs from user facing methods
  pandas/io/pytables.py
Labels: Clean

#23627 CI: Check in the CI that assert_raises_regex is not being used
  ci/code_checks.sh
Labels: CI, Testing

#23587 CLN: datetimelike arrays: isort, small reorg
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_period.py
  pandas/tests/arrays/test_timedeltas.py
  setup.cfg
Labels: Output-Formatting, Refactor, Timeseries

#23629 More helpful Stata string length error.
  pandas/io/stata.py
Labels: Error Reporting, IO Stata

#23635 DEPR: Deprecate usecols as int in read_excel
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/excel.py
  pandas/tests/io/test_excel.py
Labels: Deprecate, IO Excel

#23527 BUG: Don't over-optimize memory with jagged CSV
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
  pandas/tests/io/parser/common.py
Labels: Bug, IO CSV

#23607 DOC: Adding validation of the section order in docstrings
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#23625 CLN: remove incorrect usages of com.AbstractMethodError
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/datetimelike.py
  pandas/io/common.py
  pandas/io/html.py
  pandas/io/json/json.py
  pandas/io/parquet.py
  pandas/io/parsers.py
  pandas/plotting/_core.py
  pandas/tests/io/parser/test_parsers.py
  pandas/tests/test_resample.py
  pandas/tseries/offsets.py
Labels: Clean, Error Reporting

#23637 DOC: avoid SparseArray.take error
  doc/source/whatsnew/v0.18.1.txt
Labels: Docs, Sparse

#23636 DOC: clean-up recent doc errors/warnings
  doc/source/advanced.rst
  doc/source/ecosystem.rst
  doc/source/timeseries.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/datetimelike.py
  pandas/core/tools/timedeltas.py
Labels: Docs

#23653 DOC: Fix docstring title sections
  pandas/_libs/tslibs/period.pyx
  pandas/core/accessor.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/range.py
  pandas/core/ops.py
  pandas/core/resample.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/util.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/numeric.py
  pandas/core/tools/timedeltas.py
  pandas/core/window.py
  pandas/io/json/table_schema.py
  pandas/io/sql.py
Labels: Clean, Docs

#23655 CI: Allow to compile docs with ipython 7.11 #22990
  ci/deps/travis-36-doc.yaml
  doc/source/conf.py
Labels: CI, Docs

#23660 TST: IntervalTree.get_loc_interval should return platform int
  pandas/_libs/intervaltree.pxi.in
Labels: 32bit, Interval, Testing

#23656 CLN: Move to_excel to generic.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
Labels: Clean, IO Excel, Refactor

#22866 Add to_flat_index method to MultiIndex
  doc/source/api.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_conversion.py
  pandas/tests/indexes/test_base.py
Labels: API Design, MultiIndex

#23661 BUG: Fix read_excel w/parse_cols & empty dataset
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/excel.py
  pandas/tests/io/data/test1.xls
  pandas/tests/io/data/test1.xlsm
  pandas/tests/io/data/test1.xlsx
  pandas/tests/io/test_excel.py
Labels: Bug, IO Excel

#19983 DOC: Update is_sparse docstring
  pandas/core/dtypes/common.py
Labels: Docs, Sparse

#23678 DOC: Surface / doc mangle_dupe_cols in read_excel
  pandas/io/excel.py
  pandas/tests/io/test_excel.py
Labels: Docs, IO Excel, Testing

#23674 Fix errorbar visualization
  doc/source/visualization.rst
Labels: Docs

#23639 DOC: Accessing files from a S3 bucket.
  doc/source/io.rst
Labels: Data IO, Docs

#23643 Implement _most_ of the EA interface for DTA/TDA
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/concat.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/tests/arrays/test_datetimelike.py
Labels: ExtensionArray, Timeseries

#23696 Remove unnecessary code
  pandas/core/accessor.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/dtypes/test_inference.py
Labels: Clean

#23692 ENH: Allow export of mixed columns to Stata strl
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Enhancement, IO Stata

#20374 DOC: update pandas.core.groupby.DataFrameGroupBy.resample docstring.
  pandas/core/groupby/groupby.py
Labels: Docs, Resample

#22987 BUG-22984 Fix truncation of DataFrame representations
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Bug, Output-Formatting

#23506 DOC: Validate space before colon docstring parameters #23483
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs, Style

#23714 DOC: Handle exceptions when computing contributors.
  doc/sphinxext/contributors.py
Labels: Docs

#23707 DOC: flake8-per-pr for windows users
  doc/source/contributing.rst
Labels: Docs, Windows

#23628 Ensure Index._data is an ndarray
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/test_operators.py
Labels: Dtypes, Reshaping

#20356 ENH: Allow for join between two multi-index dataframe instances
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/indexes/base.py
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_multi.py
Labels: Enhancement, Reshaping

#23657 API/DEPR: replace "raise_conflict" with "errors" for df.update
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/core/panel.py
  pandas/tests/frame/test_combine_concat.py
  pandas/tests/test_panel.py
Labels: Algos, Deprecate

#22786 BUG: to_html misses truncation indicators (...) when index=False
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/formats/html.py
  pandas/tests/io/formats/data/gh15019_expected_output.html
  pandas/tests/io/formats/data/gh22783_expected_output.html
  pandas/tests/io/formats/test_to_html.py
Labels: Bug, IO HTML, Output-Formatting

#23614 Fix order parameters and add decimal to to_string
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Clean, Docs, IO HTML

#23698 DOC: Delete more trailing blank lines in docstrings.
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/strings.py
  pandas/core/window.py
  pandas/plotting/_core.py
Labels: Docs, Style

#23687 BUG: 'Unnamed' != unnamed column in CSV
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/header.py
Labels: Bug, IO CSV

#23711 ERR: Fail-fast with incompatible skipfooter combos
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/common.py
Labels: Error Reporting, IO CSV

#23748 TST: implement tm.to_array, box_with_timedelta, box4
  pandas/tests/arithmetic/conftest.py
  pandas/util/testing.py
Labels: Testing

#21175 Fix nonzero of a SparseArray
  doc/source/whatsnew/v0.24.0.rst
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/sparse/frame/test_frame.py
Labels: Sparse

#23747 TST/CLN: refactor tests\io\formats\test_to_html.py
  pandas/tests/io/formats/data/datetime64_hourformatter.html
  pandas/tests/io/formats/data/datetime64_monthformatter.html
  pandas/tests/io/formats/data/escape_disabled.html
  pandas/tests/io/formats/data/escaped.html
  pandas/tests/io/formats/data/gh12031_expected_output.html
  pandas/tests/io/formats/data/gh14882_expected_output_1.html
  pandas/tests/io/formats/data/gh14882_expected_output_2.html
  pandas/tests/io/formats/data/gh14998_expected_output.html
  pandas/tests/io/formats/data/gh6131_expected_output.html
  pandas/tests/io/formats/data/gh8452_expected_output.html
  pandas/tests/io/formats/data/index_1.html
  pandas/tests/io/formats/data/index_2.html
  pandas/tests/io/formats/data/index_3.html
  pandas/tests/io/formats/data/index_4.html
  pandas/tests/io/formats/data/index_5.html
  pandas/tests/io/formats/data/index_formatter.html
  pandas/tests/io/formats/data/justify.html
  pandas/tests/io/formats/data/multiindex_1.html
  pandas/tests/io/formats/data/multiindex_2.html
  pandas/tests/io/formats/data/multiindex_sparsify_1.html
  pandas/tests/io/formats/data/multiindex_sparsify_2.html
  pandas/tests/io/formats/data/multiindex_sparsify_false_multi_sparse_1.html
  pandas/tests/io/formats/data/multiindex_sparsify_false_multi_sparse_2.html
  pandas/tests/io/formats/data/truncate.html
  pandas/tests/io/formats/data/truncate_multi_index.html
  pandas/tests/io/formats/data/truncate_multi_index_sparse_off.html
  pandas/tests/io/formats/data/unicode_1.html
  pandas/tests/io/formats/data/unicode_2.html
  pandas/tests/io/formats/data/with_classes.html
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML, Refactor, Testing

#23756 TST: groupby with daily frequency fails with NonExistentTimeError on clock change day in Brazil
  pandas/tests/test_resample.py
Labels: Resample, Timezones

#23712 MAINT: Add more pytest idiom to parser tests
  pandas/tests/io/parser/c_parser_only.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_parsers.py
Labels: IO CSV, Refactor, Testing

#23732 TST/CLN: Fix/clean pytables test
  pandas/tests/io/test_pytables.py
Labels: Data IO, Testing

#23749 DOC: Remove pandas. prefix from See Also section in Series #23659
  pandas/core/algorithms.py
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimelike.py
  pandas/core/series.py
  pandas/core/strings.py
Labels: Docs

#23725 BUG: concat warning bubbling up through str.cat
  pandas/core/strings.py
Labels: Reshaping, Strings

#23738 Add missing spacing before or after a param name in docstrings
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/compat/pickle_compat.py
  pandas/core/algorithms.py
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/concat.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/timedeltas.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/io/excel.py
  pandas/io/feather_format.py
  pandas/io/formats/style.py
  pandas/io/json/json.py
  pandas/io/packers.py
  pandas/io/parquet.py
  pandas/io/pytables.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/plotting/_tools.py
  pandas/tseries/offsets.py
Labels: Docs, Style

#23718 ENH: Improve error message for empty object array
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Error Reporting, IO Stata

#23652 DOC: Improve error message to show correct order
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs, Testing

#23662 ENH: update pandas-gbq to 0.8.0, adds credentials arg
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/io/gbq.py
  pandas/tests/io/test_gbq.py
Labels: IO Google

#23650 DOC: Add ignore-deprecate argument to validate_docstrings.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#23761 REF/TST: Add more pytest idiom to parsers tests
  pandas/tests/io/parser/comment.py
  pandas/tests/io/parser/compression.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/converters.py
  pandas/tests/io/parser/dialect.py
  pandas/tests/io/parser/test_comment.py
  pandas/tests/io/parser/test_compression.py
  pandas/tests/io/parser/test_converters.py
  pandas/tests/io/parser/test_dialect.py
  pandas/tests/io/parser/test_parsers.py
Labels: IO CSV, Refactor, Testing

#23757 TST: Use new arithmetic fixtures, parametrize many more tests
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/indexes/test_numeric.py
Labels: Testing

#23621 DEPR: tz_convert in the Timestamp constructor
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/io/formats/format.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Deprecate, Timeseries, Timezones

#23618 BUG: Index.str.partition not nan-safe (#23558)
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/test_strings.py
Labels: Bug, Indexing, Missing-data, Strings

#23703 BUG: Don't extract header names if none specified
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/excel.py
  pandas/tests/io/data/testmultiindex.xls
  pandas/tests/io/data/testmultiindex.xlsm
  pandas/tests/io/data/testmultiindex.xlsx
  pandas/tests/io/test_excel.py
Labels: Bug, IO Excel, MultiIndex

#23762 TST: Add test case for GH14080 for overflow exception
  pandas/tests/scalar/timestamp/test_arithmetic.py
Labels: Testing, Timedelta

#23466 API: Make Categorical.searchsorted returns a scalar when supplied a scalar
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_analytics.py
Labels: Categorical, Performance

#22726 CLN: io/formats/html.py: refactor
  pandas/io/formats/html.py
Labels: IO HTML, Refactor

#23772 PERF: Use is_utc check to improve performance of dateutil UTC in DatetimeIndex methods
  asv_bench/benchmarks/timeseries.py
  asv_bench/benchmarks/timestamp.py
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
Labels: Performance, Timezones

#23771 TST: Extend datetime64 arith tests to array classes, fix several broken cases
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/ops.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tseries/frequencies.py
Labels: ExtensionArray, Testing

#23072 Fixing memory leaks in read_csv
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/parsers.pyx
Labels: IO CSV, Performance

#23775 BUG: Don't warn if default conflicts with dialect
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_dialect.py
  pandas/util/testing.py
Labels: Bug, Error Reporting, IO CSV

#23774 DEPS: bump xlrd min version to 1.0.0
  ci/deps/azure-27-compat.yaml
  ci/deps/travis-27-locale.yaml
  ci/deps/travis-27.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/algos_rank_helper.pxi.in
  pandas/_libs/index.pyx
  pandas/_libs/index_class_helper.pxi.in
  pandas/core/indexes/period.py
  pandas/io/excel.py
  pandas/tests/io/test_excel.py
Labels: Compat, Dependencies
