Repository pandas-dev/pandas, pull requests merged in 2018-06, with the labels that each got.

#21277 Add missing period to get_dummies docs
  pandas/core/reshape/reshape.py
Labels: Docs, Needs Backport

#21217 CI: revert skip of geopandas downstream test
  pandas/tests/test_downstream.py
Labels: CI

#21254 BUG: Allow IntervalIndex to be constructed from categorical data with appropriate dtype
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_construction.py
Labels: Categorical, Interval, Needs Backport, Regression

#21107 PERF: Improve performance of CategoricalIndex.is_unique
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/indexes/category.py
  pandas/tests/indexes/test_category.py
Labels: Categorical, Performance

#21300 BUG: encoding error in to_csv compression
  doc/source/whatsnew/v0.23.1.txt
  pandas/io/formats/csvs.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/series/test_io.py
  pandas/tests/test_common.py
Labels: IO CSV, Needs Backport

#21316 DOC: whatsnew note for MultiIndex Sorting Fix
  doc/source/whatsnew/v0.23.1.txt
Labels: Docs

#21297 Add Featuretools to Pandas Ecosystem Page
  doc/source/ecosystem.rst
Labels: Docs, Needs Backport

#21274 PERF: improve performance of NDFrame.describe
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
Labels: Performance

#21293 DOC: Fixing 'a la' confusion in series.quantile documentation
  pandas/core/series.py
Labels: Docs

#21279 BUG: Fix encoding for Stata format 118 files
  doc/source/whatsnew/v0.23.1.txt
  pandas/io/stata.py
  pandas/tests/io/data/stata16_118.dta
  pandas/tests/io/test_stata.py
Labels: IO Stata, Unicode

#21330 DOC: fix mistake in Series.str.cat
  pandas/core/strings.py
Labels: Docs

#21281 BUG: Using DatetimeIndex.date with timezone returns incorrect date #2…
  doc/source/whatsnew/v0.23.1.txt
  pandas/_libs/tslib.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_timezones.py
Labels: Timeseries, Timezones

#21263 Color text based on background color when using `_background_gradient()`
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/formats/style.py
  pandas/tests/io/formats/test_style.py
Labels: Enhancement, Visualization

#21164 BUG: Fix nested_to_record with None values in nested levels
  doc/source/whatsnew/v0.23.1.txt
  pandas/io/json/normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON, Needs Backport

#21367 DOC: move whatsnew file for #21116 (index droplevel)
  doc/source/whatsnew/v0.23.1.txt
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21362 BUG: Fixed concat warning message
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/indexes/api.py
Labels: Reshaping

#21252 BUG: dropna incorrect with categoricals in pivot_table
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Bug, Categorical, Groupby, Needs Backport

#20968 Sharey keyword for boxplot
  doc/source/whatsnew/v0.23.1.txt
  pandas/plotting/_core.py
  pandas/tests/plotting/test_frame.py
Labels: Enhancement, Visualization

#21183 BUG: Series.combine() fails with ExtensionArray inside of Series
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/series.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/series/test_combine_concat.py
Labels: Bug, ExtensionArray

#21366 REGR: NA-values in ctors with string dtype
  doc/source/whatsnew/v0.23.1.txt
  pandas/conftest.py
  pandas/core/dtypes/cast.py
  pandas/core/series.py
  pandas/tests/dtypes/test_cast.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_constructors.py
Labels: Dtypes

#21387 DOC: update whatsnew 0.23.1
  doc/source/whatsnew/v0.23.1.txt
Labels: Docs

#21363 Fix #21356: JSON nested_to_record Silently Drops Top-Level None Values
  doc/source/whatsnew/v0.23.1.txt
  pandas/io/json/normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON

#21361 Revert change to comparison op with datetime.date objects
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/ops.py
  pandas/tests/series/test_arithmetic.py
Labels: Numeric, Timeseries

#21382 DOC: update multi-index term with MultiIndex
  doc/source/basics.rst
  doc/source/contributing_docstring.rst
  doc/source/dsintro.rst
  doc/source/ecosystem.rst
  doc/source/io.rst
  doc/source/merging.rst
  doc/source/release.rst
  doc/source/spelling_wordlist.txt
  doc/source/whatsnew/v0.10.0.txt
  doc/source/whatsnew/v0.10.1.txt
  doc/source/whatsnew/v0.12.0.txt
  doc/source/whatsnew/v0.14.0.txt
  doc/source/whatsnew/v0.14.1.txt
  doc/source/whatsnew/v0.15.0.txt
  doc/source/whatsnew/v0.15.1.txt
  doc/source/whatsnew/v0.15.2.txt
  doc/source/whatsnew/v0.16.0.txt
  doc/source/whatsnew/v0.16.1.txt
  doc/source/whatsnew/v0.17.0.txt
  doc/source/whatsnew/v0.17.1.txt
  doc/source/whatsnew/v0.18.0.txt
  doc/source/whatsnew/v0.20.0.txt
  doc/source/whatsnew/v0.21.0.txt
  doc/source/whatsnew/v0.21.1.txt
Labels: Docs, MultiIndex

#21310 REGR: allow merging on object boolean columns
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Regression, Reshaping

#21321 BLD: include dll in package_data on Windows
  doc/source/whatsnew/v0.23.1.txt
  setup.py
Labels: Build, Needs Backport

#21318 BUG: Fix empty Data frames to JSON round-trippable back to data frames
  doc/source/whatsnew/v0.23.1.txt
  pandas/io/json/table_schema.py
  pandas/tests/io/json/test_json_table_schema.py
Labels: Bug, IO JSON

#21414 Doc Fixes
  pandas/core/indexes/multi.py
Labels: Docs

#21421 DOC: fix grammar of deprecation message
  pandas/util/_decorators.py
Labels: Error Reporting

#21400 MAINT: Deprecate encoding from stata reader/writer
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Deprecate, IO Stata

#21433 DOC: Add 0.23.2 whatsnew template
  doc/source/whatsnew/v0.23.2.txt
Labels: Docs

#21377 MAINT: More friendly error msg on Index overflow
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: Dtypes, Error Reporting, Indexing

#21435 DOC: follow 0.23.1 template for 0.23.2 whatsnew
  doc/source/whatsnew/v0.23.2.txt
Labels: Docs

#21397 DOC: Loading sphinxcontrib.spelling to sphinx only if it's available (#21396)
  ci/environment-dev.yaml
  ci/requirements_dev.txt
  doc/source/conf.py
Labels: Bug, Build, Docs

#21438 Fix flake8 in conf.py
  doc/source/conf.py
Labels: Style

#21415 Doc Fixes
  pandas/core/indexing.py
Labels: Docs, Indexing, MultiIndex

#21413 add dropna=False to crosstab example
  pandas/core/reshape/pivot.py
Labels: Categorical, Docs

#21409 Two tests didn't properly assert an exception was raised. Fixed.
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/io/parser/c_parser_only.py
Labels: IO CSV, Testing

#21449 DOC: Fixed warning in doc build [ci skip]
  doc/source/ecosystem.rst
Labels: Docs

#21440 DOC: Add favicon to doc pages
  doc/source/_static/favicon.ico
  doc/source/conf.py
Labels: Docs

#21451 PERF: Use ccalendar.get_days_in_month over tslib.monthrange
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
  setup.py
Labels: Performance, Timeseries

#21407 BUG: Construct Timestamp with tz correctly near DST border
  doc/source/whatsnew/v0.23.2.txt
  pandas/_libs/tslibs/conversion.pyx
  pandas/tests/frame/test_timezones.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Bug, Indexing, Needs Backport, Timezones

#21405 parametrize tests, unify repeated tests
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Clean, Frequency, Testing

#21403 DOC: isin() docstring change DataFrame to pd.DataFrame
  pandas/core/frame.py
Labels: Docs

#21404 fix DateOffset eq to depend on normalize attr
  doc/source/whatsnew/v0.24.0.txt
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Bug, Timedelta

#21216 API/BUG: DatetimeIndex correctly localizes integer data
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_astype.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/test_base.py
Labels: API Design, Timezones

#21285 PERF: improve performance of groupby rank (#21237)
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/groupby_helper.pxi.in
Labels: Groupby, Performance

#21452 PERF: typing and cdefs for tslibs.resolution
  pandas/_libs/tslibs/resolution.pyx
Labels: Internals, Performance, Timeseries

#21427 disallow normalize=True with Tick classes
  doc/source/whatsnew/v0.24.0.txt
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Bug, Error Reporting, Timedelta

#21369 PERF: Add __contains__ to CategoricalIndex
  asv_bench/benchmarks/categoricals.py
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/indexes/category.py
Labels: Categorical, Indexing, Performance

#21490 CLN: Index imports and 0.23.1 whatsnew
  doc/source/whatsnew/v0.23.1.txt
  pandas/core/indexes/base.py
Labels: Clean

#21493 PERF: improve speed of nans in CategoricalIndex
  pandas/core/indexes/category.py
Labels: Categorical, Performance

#21447 perf improvements in tslibs.period
  pandas/_libs/src/util.pxd
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/period.pyx
Labels: Performance, Timeseries

#21432 BUG: Fix Series.nlargest for integer boundary values
  doc/source/whatsnew/v0.23.2.txt
  pandas/conftest.py
  pandas/core/algorithms.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Algos, Bug, Dtypes, Needs Backport

#21482 Removing SimpleMock test from pandas.util.testing
  pandas/util/testing.py
Labels: Clean, Testing

#21393 TST: adding test cases for verifying correct values shown by pivot_table() #21378
  pandas/tests/reshape/test_pivot.py
Labels: Categorical, Groupby, Testing

#21523 PERF: remove useless overrides
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/indexes/multi.py
Labels: MultiIndex, Needs Backport, Performance

#21491 TST: Add unit tests for older timezone issues
  doc/source/whatsnew/v0.23.2.txt
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/test_resample.py
Labels: Needs Backport, Testing, Timezones

#21485 BUG: Timedelta.__bool__
  doc/source/whatsnew/v0.23.2.txt
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Needs Backport, Timedelta

#21481 BUG: Fix Index construction when given empty generator (#21470).
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/arrays/categorical.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: Bug, Needs Backport, Regression

#21478 BUG/REG: file-handle object handled incorrectly in to_csv
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/frame.py
  pandas/core/series.py
  pandas/io/common.py
  pandas/io/formats/csvs.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/series/test_io.py
  pandas/tests/test_common.py
Labels: IO CSV, Needs Backport, Regression

#21251 Append Mode for ExcelWriter with openpyxl
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/excel.py
  pandas/tests/io/test_excel.py
Labels: IO Excel

#21511 DOC: Improve code example for Index.get_indexer
  pandas/core/indexes/base.py
Labels: Docs, Indexing

#21534 DOC: remove grammar duplication in groupby docs
  doc/source/groupby.rst
Labels: Clean, Docs

#21533 remove daytime attr, move getstate and setstate to base class
  pandas/_libs/tslibs/offsets.pyx
  pandas/tseries/offsets.py
Labels: Clean, Frequency

#21503 De-duplicate code for indexing with list-likes of keys
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexing.py
Labels: Clean, Indexing, Refactor

#21550 Update "See Also" section of pandas/core/generic.py
  pandas/core/generic.py
Labels: Docs

#21519 Fixing documentation lists indentation (#21518)
  doc/source/api.rst
  doc/source/basics.rst
  doc/source/categorical.rst
  doc/source/comparison_with_r.rst
  doc/source/computation.rst
  doc/source/contributing.rst
  doc/source/contributing_docstring.rst
  doc/source/developer.rst
  doc/source/dsintro.rst
  doc/source/ecosystem.rst
  doc/source/enhancingperf.rst
  doc/source/extending.rst
  doc/source/gotchas.rst
  doc/source/groupby.rst
  doc/source/indexing.rst
  doc/source/install.rst
  doc/source/internals.rst
  doc/source/io.rst
  doc/source/merging.rst
  doc/source/options.rst
  doc/source/overview.rst
  doc/source/reshaping.rst
  doc/source/sparse.rst
  doc/source/timeseries.rst
  doc/source/tutorials.rst
  doc/source/visualization.rst
Labels: Docs

#21508 PERF: add method Categorical.__contains__
  asv_bench/benchmarks/categoricals.py
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
  pandas/tests/categorical/test_operators.py
Labels: Categorical, Needs Backport, Performance

#21497 REGR: Fixes first_valid_index when DataFrame or Series has duplicate row index (GH21441)
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/generic.py
  pandas/tests/frame/test_timeseries.py
Labels: Indexing, Regression

#21456 API/BUG: Raise when int-dtype coercions fail
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/dtypes/cast.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/generic/test_generic.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/io/test_pytables.py
  pandas/tests/series/test_constructors.py
Labels: Dtypes, Error Reporting

#21566 DOC: Add documentation for freq='infer' option of DatetimeIndex and TimedeltaIndex constructors
  doc/source/timedeltas.rst
  doc/source/timeseries.rst
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Docs, Frequency, Timedelta, Timeseries

#21541 BUG: Fix group index calculation to prevent hitting maximum recursion depth (#21524)
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/sorting.py
  pandas/tests/frame/test_analytics.py
Labels: Bug, Reshaping

#21515 Fix passing empty label to df drop
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/series/indexing/test_alter_index.py
Labels: Indexing, MultiIndex

#21568 [DOC]: Updating merge.rst to resolve rendering issues
  doc/source/merging.rst
Labels: Docs

#21558 ERR: Raise a simpler backtrace for missing key
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexing.py
Labels: Error Reporting, Indexing

#21543 Fixed HDFSTore.groups() performance.
  doc/source/whatsnew/v0.23.2.txt
  pandas/io/pytables.py
Labels: IO HDF5, Needs Backport, Performance

#21570 DOC: Fixing spaces around backticks, and linting
  ci/lint.sh
  doc/source/merging.rst
  doc/source/release.rst
  doc/source/reshaping.rst
  doc/source/timeseries.rst
Labels: Docs

#21187 fix hashing string-casting error
  doc/source/whatsnew/v0.23.2.txt
  pandas/_libs/hashing.pyx
  pandas/tests/series/test_repr.py
  pandas/util/testing.py
Labels: Bug, Needs Backport, Output-Formatting

#21569 REF: multi_take is now able to tackle all list-like (non-bool) cases
  pandas/core/indexing.py
Labels: Indexing, Refactor

#21588 TST: Use int fixtures in test_construction.py
  pandas/tests/indexes/datetimes/test_construction.py
Labels: Clean, Dtypes, Testing

#21585 DOC: Adding clarification on return dtype of to_numeric
  pandas/core/tools/numeric.py
Labels: Docs, Dtypes, Numeric

#21586 [DOC]: To remove extra `` to match :class: rendering requirements
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21589 clarifying regex pipe behavior
  pandas/core/strings.py
Labels: Docs

#21580 DOC: Note assert_almost_equal impl. detail
  pandas/util/testing.py
Labels: Docs, Testing

#21579 DOC: update the Series.any / Dataframe.any docstring
  pandas/core/generic.py
Labels: Docs

#21591 TST: Clean up tests in test_take.py
  pandas/tests/test_take.py
Labels: Clean, Refactor, Testing

#21595 TST: Add interval closed fixture to top-level conftest
  pandas/conftest.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval_range.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/indexing/interval/test_interval.py
Labels: Clean, Interval, Testing

#21582 cache DateOffset attrs now that they are immutable
  asv_bench/benchmarks/period.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/offsets.pyx
  pandas/tseries/offsets.py
Labels: Frequency, Indexing, Performance

#21578 BUG: Series dot product __rmatmul__ doesn't allow matrix vector multiplication
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/series.py
  pandas/tests/series/test_analytics.py
Labels: Algos, Bug

#21573 BUG: first/last lose timezone in groupby with as_index=False
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_nth.py
Labels: Bug, Timezones

#21572 add test case when to_csv argument is sys.stdout
  pandas/tests/io/formats/test_to_csv.py
Labels: Data IO, Testing

#21540 BUG: Fix json_normalize throwing TypeError (#21536)
  doc/source/whatsnew/v0.23.2.txt
  pandas/io/json/normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: Bug, IO JSON

#21026 DOC: updated the Series.str.rsplit and Series.str.split docstrings
  pandas/core/strings.py
Labels: Docs

#21602 TST: Use multiple instances of parametrize instead of product in tests
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/frame/test_rank.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_whitelist.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/sparse/series/test_series.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_resample.py
  pandas/tests/test_window.py
Labels: Clean, Testing

#21008 MyPy cleanup and absolute imports in pandas.core.dtypes.common
  pandas/core/arrays/base.py
  pandas/core/base.py
  pandas/core/dtypes/common.py
Labels: Compat, Dtypes

#21619 remove unused cimport
  pandas/_libs/hashtable_class_helper.pxi.in
Labels: Clean

#21604 CI: Test against Python 3.7
  .travis.yml
  ci/travis-37.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.23.2.txt
  pandas/compat/__init__.py
  pandas/tests/tseries/offsets/test_offsets.py
  setup.py
Labels: CI

#21623 DOC: Do no use 'type' as first word when specifying a return type (#21622)
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/sparse/series.py
  pandas/core/window.py
  pandas/io/packers.py
  pandas/io/pickle.py
  pandas/io/pytables.py
Labels: Docs

#21594 PERF: do not check for label presence preventively
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexing.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexing/test_multiindex.py
Labels: Indexing, Performance, Refactor

#21600 TST: Refactor test_maybe_match_name and test_hash_pandas_object
  pandas/tests/test_common.py
  pandas/tests/util/test_hashing.py
Labels: Clean, Testing

#21486 API/COMPAT: support axis=None for logical reduction (reduce over all axes)
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/panel.py
  pandas/core/series.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/test_panel.py
  pandas/util/_test_decorators.py
Labels: Compat, Numeric

#21631 Move tz cleanup whatsnew entries to v0.24
  doc/source/whatsnew/v0.23.2.txt
  doc/source/whatsnew/v0.24.0.txt
Labels: Testing

#21634 DOC: fixup old whatsnew for dtype coercing change (#21456)
  doc/source/whatsnew/v0.11.0.txt
Labels: Docs

#21613 DEPR: MultiIndex.to_hierarchical
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/multi.py
  pandas/core/panel.py
  pandas/tests/indexes/test_multi.py
Labels: Deprecate, MultiIndex, Panel

#20729 [ENH] Add read support for Google Cloud Storage
  ci/appveyor-27.yaml
  ci/check_imports.py
  ci/circle-36-locale_slow.yaml
  ci/requirements-optional-conda.txt
  ci/requirements-optional-pip.txt
  ci/travis-27.yaml
  ci/travis-36.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/conftest.py
  pandas/io/common.py
  pandas/io/excel.py
  pandas/io/gcs.py
  pandas/io/json/json.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/io/parser/common.py
  pandas/tests/io/test_gcs.py
  pandas/util/_print_versions.py
Labels: Enhancement, IO Google

#19535 PKG: Exclude data test files.
  MANIFEST.in
  ci/script_single.sh
  doc/source/whatsnew/v0.23.2.txt
  pandas/conftest.py
  pandas/tests/indexes/test_multi.py
  pandas/tests/io/conftest.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/common.py
  pandas/tests/io/parser/compression.py
  pandas/tests/io/parser/dtypes.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parsers.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/sas/test_xport.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_packers.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_pytables.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_deprecated.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/test_tile.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/util/test_testing.py
  pandas/util/_test_decorators.py
  pandas/util/testing.py
  setup.cfg
  setup.py
Labels: Build, Needs Backport, Testing

#21163 Cleanup clipboard tests
  pandas/tests/io/test_clipboard.py
Labels: Clean, Needs Backport, Testing

#21549 use ccalendar instead of np_datetime
  pandas/_libs/tslibs/ccalendar.pxd
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  setup.py
Labels: Clean, Performance

#21649 DOC: Fix versionadded directive typos in IntervalIndex
  pandas/core/indexes/interval.py
Labels: Docs, Needs Backport

#21652 DOC: update DataFrame.dropna's axis argument docs
  pandas/core/frame.py
Labels: Docs

#21584 BUG: Let IntervalIndex constructor override inferred closed
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/interval.pyx
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_construction.py
Labels: API Design, Bug, Interval

#21661 TST: Use fixtures in dtypes/test_cast.py
  pandas/conftest.py
  pandas/tests/dtypes/test_cast.py
Labels: Clean, Refactor, Testing

#21612 TST: Clean old timezone issues PT2
  doc/source/whatsnew/v0.24.0.txt
  pandas/conftest.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_replace.py
  pandas/tests/series/test_timezones.py
Labels: Testing, Timezones

#21650 ENH: Allow keep='all' for nlargest/nsmallest
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/algorithms.py
  pandas/core/frame.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: API Design, Algos, Enhancement

#21659 PERF: avoid unneeded recoding of categoricals and reuse CategoricalDtypes for greater slicing speed
  asv_bench/benchmarks/categoricals.py
  asv_bench/benchmarks/indexing.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/category.py
Labels: Categorical, Performance

#21590 API/REGR: (re-)allow neg/pos unary operation on object dtype
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/generic.py
  pandas/tests/frame/test_operators.py
Labels: Dtypes, Regression

#21423 API: re-allow duplicate index level names
  doc/source/whatsnew/v0.23.2.txt
  pandas/core/indexes/multi.py
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexes/test_multi.py
  pandas/tests/io/test_pytables.py
  pandas/tests/reshape/test_pivot.py
Labels: API Design, MultiIndex

#21314 Make Period - Period return DateOffset instead of int
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/period.pyx
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/period.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/indexes/period/test_arithmetic.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/series/test_arithmetic.py
Labels: Frequency, Period

#20049 API: PeriodIndex subtraction to return object Index of DateOffsets
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/period/test_arithmetic.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
Labels: Frequency, Period

#21260 BUG: Series.get() with ExtensionArray and integer index
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Bug, ExtensionArray

#21261 ENH: Support ExtensionArray operators via a mixin
  doc/source/extending.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/api/extensions/__init__.py
  pandas/conftest.py
  pandas/core/arrays/__init__.py
  pandas/core/arrays/base.py
  pandas/core/ops.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
  pandas/util/testing.py
Labels: ExtensionArray

#21111 BUG: to_clipboard fails to format output for Excel
  doc/source/whatsnew/v0.23.2.txt
  pandas/io/clipboards.py
  pandas/tests/io/test_clipboard.py
Labels: IO Excel, Needs Backport
