Repository pandas-dev/pandas, pull requests merged in 2018-03, with the labels that each got.

#18099 ENH: Implement DataFrame.astype('category')
  doc/source/categorical.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_dtypes.py
Labels: Categorical, Enhancement

#19722 Cythonized GroupBy any
  asv_bench/benchmarks/groupby.py
  doc/source/api.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/groupby.pyx
  pandas/core/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Performance

#19889 ENH: Allow Timestamp to accept Nanosecond argument
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: API Design, Timeseries

#19840 DOC: script to build single docstring page
  doc/make.py
  doc/source/conf.py
  doc/source/contributing.rst
  doc/source/index.rst.template
Labels: Docs

#19947 CLN: remove redundant clean_fill_method calls
  pandas/core/generic.py
Labels: Clean

#19948 BUG: Preserve column metadata with DataFrame.astype
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_dtypes.py
Labels: Bug, Dtypes, Reshaping

#19949 DOC: suppress attributes for RangeIndex api docs
  doc/source/conf.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/range.py
Labels: Docs

#19773 BUG: DataFrame.diff(axis=0) with DatetimeTZ data
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/internals.py
  pandas/tests/frame/test_timeseries.py
Labels: Timeseries, Timezones

#19800 dispatch Series[datetime64] comparison ops to DatetimeIndex
  pandas/core/indexes/datetimes.py
  pandas/core/ops.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/test_base.py
Labels: Internals, Refactor, Timeseries

#19937 Making to_datetime('today') and Timestamp('today') consistent
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/tslib.pyx
  pandas/tests/indexes/datetimes/test_tools.py
Labels: API Design, Bug, Timeseries

#19914 BUG: Adding skipna as an option to groupby cumsum and cumprod
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/groupby.pyx
  pandas/core/groupby.py
  pandas/tests/groupby/test_transform.py
Labels: Groupby, Missing-data

#19898 DOC: Adding script to validate docstrings, and generate list of all functions/methods with state
  scripts/validate_docstrings.py
Labels: Docs

#19884 ENH: Let initialisation from dicts use insertion order for python >= 3.6 (part III)
  doc/source/dsintro.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/common.py
  pandas/core/frame.py
  pandas/core/panel.py
  pandas/core/series.py
  pandas/core/sparse/frame.py
  pandas/core/sparse/series.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_pytables.py
  pandas/tests/series/test_constructors.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/series/test_series.py
  pandas/tests/test_panel.py
Labels: Compat, Reshaping

#19908 DOC: update install.rst to include ActivePython distribution
  doc/source/install.rst
Labels: Docs

#19964 DOC: clarify version of ActivePython that includes pandas
  doc/source/install.rst
Labels: Docs

#19960 DOC: update docstring validation script
  scripts/validate_docstrings.py
Labels: Docs

#19913 API: Added ExtensionArray constructors
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
Labels: API Design, ExtensionArray

#19962 DOC: fix some sphinx syntax warnings
  doc/source/merging.rst
  doc/source/tutorials.rst
  doc/source/visualization.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/frame.py
  pandas/core/window.py
  pandas/io/json/json.py
Labels: Docs

#19951 DOC: small updates to make.py script
  doc/make.py
Labels: Docs

#19943 BUG: Compat for pre-0.20 TimedeltaIndex and Float64Index pickles #19939
  doc/source/whatsnew/v0.23.0.txt
  pandas/compat/pickle_compat.py
  pandas/tests/io/data/legacy_pickle/0.16.2/0.16.2_AMD64_windows_2.7.14.pickle
  pandas/tests/io/data/legacy_pickle/0.19.2/0.19.2_AMD64_windows_2.7.14.pickle
  pandas/tests/io/generate_legacy_storage_files.py
Labels: Compat, Data IO

#19918 transition period_helper to use pandas_datetimestruct
  pandas/_libs/src/period_helper.c
  pandas/_libs/src/period_helper.h
  pandas/_libs/tslibs/period.pyx
Labels: Clean, Period

#18164 ENH: Return locale based month_name and weekday_name values (#12805, #12806)
  doc/source/api.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/test_datetime_values.py
Labels: Compat, Enhancement, Timeseries

#19989 CLN: Python comprehensions and generators cleanup followup
  pandas/_libs/parsers.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/compat/pickle_compat.py
  pandas/core/generic.py
  pandas/core/indexing.py
Labels: Clean

#19987 fixed pytest deprecation warning
  pandas/tests/test_base.py
Labels: Testing

#19980 CLN: deprecate the pandas.tseries.plotting.tsplot function (GH18627)
  doc/source/whatsnew/v0.23.0.txt
  pandas/plotting/_timeseries.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Deprecate

#20005 DOC: fixed dynamic import mechanics of make.py
  doc/make.py
Labels: Docs

#20013 TST: clean deprecation warnings for xref #19980
  pandas/tests/plotting/test_datetimelike.py
Labels: Testing, Visualization

#20006 TST: split series/test_indexing.py (#18614)
  pandas/tests/series/indexing/__init__.py
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_iloc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_loc.py
  pandas/tests/series/indexing/test_numeric.py
  pandas/tests/series/test_indexing.py
Labels: Testing

#20010 month_name/day_name warnings followup
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Deprecate, Timeseries

#19912 Datetimelike add/sub catch cases more explicitly, tests
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/period/test_arithmetic.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
Labels: Period, Testing, Timedelta, Timeseries

#19936 DOC: add doc on ExtensionArray and extending pandas
  doc/source/developer.rst
  doc/source/ecosystem.rst
  doc/source/extending.rst
  doc/source/index.rst.template
  doc/source/internals.rst
  doc/source/whatsnew/v0.16.1.txt
  pandas/core/accessor.py
Labels: Docs, ExtensionArray

#19991 CLN/DOC: cache_readonly: remove allow_setting + preserve docstring
  pandas/_libs/properties.pyx
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
  pandas/tests/test_lib.py
Labels: Clean, Docs

#19986 DOC: is confusing for ddof parameter of sem, var and std functions
  pandas/core/generic.py
Labels: Docs

#20033 TST: xfail some tests for mpl 2.2 compat
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  pandas/util/_test_decorators.py
Labels: Testing, Visualization

#20035 TST: xfail numpy-dev clip failures
  pandas/tests/frame/test_analytics.py
Labels: Testing

#20019 TST: Fix wrong argument in TestDataFrameAlterAxes.test_set_index_dst
  pandas/tests/frame/test_alter_axes.py
Labels: Testing

#19999 DOC: Updated kurt docstring (for pandas sprint)
  pandas/core/window.py
Labels: Docs

#19996 DOC: updating docstring of Index.shift
  pandas/core/indexes/base.py
Labels: Docs

#20015 DOC: enable matplotlib plot_directive to include figures in docstrings
  doc/source/conf.py
  pandas/plotting/_core.py
Labels: Docs

#20026 Fix typos in test_interval_new.py
  pandas/tests/indexing/interval/test_interval_new.py
Labels: Interval, Testing

#20021 Added .pytest_cache to gitignore
  .gitignore
Labels: Testing

#19972 Small ops cleanups
  pandas/core/ops.py
Labels: Clean, Internals

#19894 EHN: Implement method argument for DataFrame.replace
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_replace.py
Labels: API Design, Missing-data, Reshaping

#20004 DOC: Add `Series` type to `to_sql` docstring
  pandas/io/sql.py
Labels: Docs, IO SQL

#19975 BUG: Fixes to msgpack support.
  pandas/io/packers.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/test_packers.py
Labels: IO Msgpack, Interval, Period, Timedelta

#20034 Moving tests in series/indexing to fixtures (#20014.1)
  pandas/tests/series/indexing/conftest.py
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_iloc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_loc.py
  pandas/tests/series/indexing/test_numeric.py
Labels: Indexing, Testing

#19664 enable multivalues insert
  doc/source/io.rst
  doc/source/whatsnew/v0.23.0.txt
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL, Performance

#20045 DOC/CI: temp pin matplotlib for doc build
  ci/requirements-3.6_DOC.run
Labels: Docs

#20025 Replace api coverage script
  doc/source/contributing.rst
  scripts/api_rst_coverage.py
  scripts/validate_docstrings.py
Labels: Docs

#20053 TST: xfail test_time on py2 & mpl 1.4.3
  pandas/tests/plotting/test_datetimelike.py
Labels: Testing, Visualization

#19994 DOC: require returns section in validation script
  scripts/validate_docstrings.py
Labels: Docs

#20063 Added flake8 to DEV requirements
  ci/environment-dev.yaml
  ci/requirements_dev.txt
Labels: CI, Dependencies

#15639 BUG: Dense ranking with percent now uses 100% basis
  doc/source/whatsnew/v0.23.0.txt
  pandas/_libs/algos_rank_helper.pxi.in
  pandas/tests/frame/test_rank.py
  pandas/tests/series/test_rank.py
Labels: Bug, Numeric

#19985 DOC: Improve docstring for pandas.Index.repeat
  pandas/core/indexes/base.py
Labels: Docs

#20055 Temporary github PR template for sprint
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Docs

#20044 DOC: Update Kurt Docstr
  pandas/core/window.py
Labels: Docs

#19890 BUG: Retain timezone dtype with cut and qcut
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/reshape/tile.py
  pandas/tests/reshape/test_tile.py
Labels: Bug, Reshaping, Timezones

#20058 Small typo in apply.py
  pandas/core/apply.py
Labels: Clean

#20047 Added 'displayed_only' option to 'read_html'
  doc/source/whatsnew/v0.23.0.txt
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: IO HTML, Output-Formatting

#20043 Refactored GroupBy ASVs
  asv_bench/benchmarks/groupby.py
Labels: Groupby, Performance, Timeseries

#19919 Cythonized GroupBy pct_change
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/groupby.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_transform.py
Labels: Groupby, Performance

#20036 DOC: Extend docstring pandas core index to_frame method
  pandas/core/indexes/base.py
Labels: Docs

#20017 BUG: Check for wrong arguments in index subclasses constructors
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/test_base.py
  pandas/util/testing.py
Labels: API Design, Compat

#19982 DOC: Improved the docstring of Series.str.findall
  pandas/core/strings.py
Labels: Docs

#20065 DOC: Improved the docstring of pandas.DataFrame.values
  pandas/core/generic.py
Labels: Docs

#20105 DOC: update the MultiIndex.swaplevel docstring
  pandas/core/indexes/multi.py
Labels: Docs, MultiIndex

#20114 DOC: update the pandas.Index.drop_duplicates and pandas.Series.drop_duplicates docstring
  pandas/core/base.py
  pandas/core/indexes/base.py
  pandas/core/series.py
Labels: Docs

#20176 DOC: update the pandas.Series.tail docstring
  pandas/core/generic.py
Labels: Docs

#20190 DOC: Edit doc contribution section. …
  doc/source/contributing.rst
Labels: Docs

#20086 DOC: update the Series.memory_usage() docstring
  pandas/core/series.py
Labels: Docs

#20192 DOC: update the Index.shift docstring
  pandas/core/indexes/base.py
Labels: Docs, Reshaping, Timeseries, Visualization

#20041 DOC: Improve pandas.Series.plot.kde docstring and kwargs rewording for whole file
  pandas/plotting/_core.py
Labels: Docs, Visualization

#20262 DOC: update pandas.DataFrame.head docstring
  pandas/core/generic.py
Labels: Docs

#20245 DOC: update the DataFrame.cov docstring
  pandas/core/frame.py
Labels: Docs, Numeric

#20225 DOC: Update pandas.DataFrame.tail docstring
  pandas/core/generic.py
Labels: Docs, Reshaping

#20169 DOC: Improved the docstring of pandas.plotting.radviz
  pandas/plotting/_misc.py
Labels: Docs, Visualization

#20191 DOC: update DataFrame.to_records
  pandas/core/frame.py
Labels: Data IO, Docs, Reshaping

#20064 Docstring for pd.core.window.Expanding.kurt
  pandas/core/window.py
Labels: Docs, Numeric, Reshaping

#20227 Docstring pandas.data frame.diff
  pandas/core/frame.py
Labels: Docs, Reshaping

#20219 DOC: update the DataFrame.iat[] docstring
  pandas/core/indexing.py
Labels: Docs, Indexing

#20246 DOC: update `pandas/core/ops.py` docstring template to accept examples
  pandas/core/ops.py
Labels: Docs

#20238 Docstring pandas.series.diff
  pandas/core/series.py
Labels: Docs, Numeric

#20223 DOC: add docstring for Index.get_duplicates
  pandas/core/indexes/base.py
Labels: Docs, Indexing

#20259 DOC: update the docstring of pandas.DataFrame.from_dict
  pandas/core/frame.py
Labels: Docs, Reshaping

#20220 DOC: update the Series.view docstring
  pandas/core/series.py
Labels: Docs, Reshaping

#20216 DOC: update the pandas.DataFrame.all docstring
  pandas/core/generic.py
Labels: Docs, Reshaping

#20231 DOC: update the Index.get_values docstring
  pandas/core/indexes/base.py
Labels: Docs, Indexing

#20166 Docstring bootstrap plot
  pandas/plotting/_misc.py
Labels: Docs, Visualization

#20187 DOC: Update the pandas.Series.dt.round/floor/ceil docstrings
  pandas/core/indexes/datetimelike.py
Labels: Docs

#20236 DOC: update the pandas.DataFrame.plot.density docstring
  pandas/plotting/_core.py
Labels: Docs, Visualization

#20129 DOC: update the parquet docstring
  pandas/core/frame.py
Labels: Docs, IO Parquet

#20163 DOC: update the DataFrame.plot.line docstring
  pandas/plotting/_core.py
Labels: Docs, Visualization

#20083 DOC: update the pandas.core.resample.Resampler.backfill docstring
  pandas/core/resample.py
Labels: Docs, Missing-data, Resample

#20288 CI: use dateutil-master in testing
  ci/requirements-3.6_NUMPY_DEV.build.sh
  pandas/conftest.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/tslibs/test_parsing.py
Labels: CI

#20221 DOC: update the DataFrame.count docstring
  pandas/core/frame.py
Labels: Docs

#20290 DOC: update the DataFrame.at[] docstring
  pandas/core/indexing.py
Labels: Docs

#20167 DOC: update the pandas.Index.is_categorical docstring
  pandas/core/indexes/base.py
Labels: Categorical, Docs

#20284 DOC/TST: Added NORMALIZE_WHITESPACE flag
  setup.cfg
Labels: Docs, Testing

#20247 DOC: update Series.sort_values docstring
  pandas/core/series.py
Labels: Docs, Reshaping

#20295 DOC: update the Period.daysinmonth docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Period

#20282 DOC: update the pandas.Series.str.split docstring
  pandas/core/strings.py
Labels: Docs

#20235 DOC: update Rolling.std docstring
  pandas/core/window.py
Labels: Docs, Reshaping

#20131 DOC: update pandas.DatetimeIndex.to_period docstring(Nairobi)
  pandas/core/indexes/datetimes.py
Labels: Docs, Period

#20297 DOC: update the Period.days_in_month docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Timeseries

#20202 DOC: update the pandas.DataFrame.apply docstring
  pandas/core/frame.py
Labels: Docs, Reshaping

#20217 DOC: update the pandas.DataFrame.any docstring
  .gitignore
  pandas/core/generic.py
  pandas/core/groupby.py
Labels: Docs, Reshaping

#20248 DOC: update the pandas.Series.sort_index docstring
  pandas/core/series.py
Labels: Docs, Reshaping

#20233 DOC: update the Rolling.var docstring
  pandas/core/window.py
Labels: Docs, Numeric, Reshaping

#20232 DOC: update the pd.Index.argsort docstring
  pandas/core/indexes/base.py
Labels: Docs, Reshaping

#19704 DOC: Adding guide for the pandas documentation sprint
  doc/source/contributing.rst
  doc/source/contributing_docstring.rst
Labels: Docs

#20311 COMPAT: Ascii example
  pandas/core/indexes/base.py
Labels: 2/3 Compat, Docs

#20310 DOC: update the pandas.DataFrame.pct_change docstring
  pandas/core/generic.py
Labels: Docs

#20299 DOC: update the Index.sort_values docstring
  pandas/core/indexes/base.py
Labels: Algos, Docs

#20250 DOC: update the DataFrame.pivot docstring
  pandas/core/frame.py
Labels: Docs, Reshaping

#20312 DOC : Update the pandas.Period.hour docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#20100 DOC: update the dtypes/ftypes docstring (Seoul)
  pandas/core/generic.py
Labels: Docs

#20314 Doc : update the pandas.Period.minute docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#20123 DOC: Update the pandas.Index.isna docstring
  pandas/core/indexes/base.py
Labels: Docs, Missing-data

#20180 DOC: update the pandas.Index.notna docstring
  pandas/core/indexes/base.py
Labels: Docs

#20277 DOC: update the Period.dayofyear docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#20322 DOC: update the Index.get duplicates docstring
  pandas/core/indexes/base.py
Labels: Docs

#20280 DOC: update the Period.dayofweek attribute docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Period

#19869 ENH: ExtensionArray.unique
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/json/array.py
Labels: Algos, Dtypes

#20292 BUG: Retain tz-aware dtypes with melt (#15785)
  doc/source/whatsnew/v0.23.0.txt
  pandas/core/reshape/melt.py
  pandas/tests/reshape/test_melt.py
Labels: Bug, Reshaping, Timezones

#20287 TST: adding join_types fixture
  pandas/conftest.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_multi.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_merge_index_as_string.py
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/test_period.py
Labels: Testing

#20158 DOC: update the pandas.DataFrame.plot.bar docsctring
  pandas/plotting/_core.py
Labels: Docs

#20198 Docstring changes to pandas.Series.dt.to_pydatetime
  pandas/core/indexes/accessors.py
Labels: Docs, Timeseries

#20319 DOC : Update the Period.second docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Period

#20307 DOC: update the pandas.Series.str.split docstring
  pandas/core/strings.py
Labels: Docs

#20079 COMPAT: Matplotlib 2.2 compatability
  pandas/plotting/_compat.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Dependencies, Visualization

#20096 DOC: update the DatetimeIndex.tz_convert(tz) docstring
  pandas/core/indexes/datetimes.py
Labels: Docs, Timezones

#20138 DOC: update the pandas.DataFrame.isna and pandas.Series.isna docstring
  pandas/core/generic.py
Labels: Docs

#20260 DOC: Improve the docstring of pandas.core.window.Rolling.median
  pandas/core/window.py
Labels: Docs

#20160 DOC: update the pandas.DataFrame.notna and pandas.Series.notna docstring
  pandas/core/generic.py
Labels: Docs

#20159 DOC: update the pandas.Series.dt.total_seconds docstring
  pandas/core/indexes/timedeltas.py
Labels: Docs, Timedelta, Timeseries

#20276 DOC: update the aggregate docstring
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/window.py
Labels: Docs, Reshaping

#20209 DOC: update the DataFrame.eval() docstring
  pandas/core/frame.py
Labels: Docs, Numeric, Reshaping

#20099 DOC: update the docstring for several functions and properties (Seoul).
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#20208 DOC: update the pandas.errors.DtypeWarning docstring
  pandas/errors/__init__.py
Labels: Docs, Error Reporting, IO CSV

#20101 DOC: update the axes, shape, dim and size property docstring (Seoul)
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#20329 DOC: Formatting for DtypeWarning Docstring [ci skip]
  pandas/errors/__init__.py
Labels: Data IO, Docs, IO CSV

#20330 CI: Fix linting on master [ci skip]
  pandas/_libs/tslibs/period.pyx
Labels: CI, Style

#20120 DOC: update and seperate the Series.drop and Dataframe.drop docstring
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs, Indexing, Reshaping

#20313 DOC: update docstring of pandas.Series.add_prefix docstring
  pandas/core/generic.py
Labels: Docs

#20315 DOC: update the pandas.Series.add_suffix docstring
  pandas/core/generic.py
Labels: Docs

#20162 DOC: update the docstring of pandas.DataFrame.to_dict
  pandas/core/frame.py
Labels: Docs

#20224 DOC: update the IntervalIndex.from_array docstring
  pandas/core/indexes/interval.py
Labels: Docs, Interval

#20126 DOC: update the pandas.DataFrame.to_sql docstring
  pandas/core/generic.py
Labels: Docs, IO SQL

#20113 DOC: update the pandas.DataFrame.hist docstring
  pandas/plotting/_core.py
Labels: Docs, Visualization

#20134 DOC: update the pandas.core.generic.NDFrame.to_clipboard docstring
  pandas/core/generic.py
Labels: Docs, Output-Formatting
