Repository pandas-dev/pandas, pull requests merged in 2018-12, with the labels that each got.

#23999 BUG: pandas.cut should disallow overlapping IntervalIndex bins
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/reshape/tile.py
  pandas/tests/reshape/test_tile.py
Labels: Bug, Interval, Reshaping

#24029 TST: Check error message in overlapping bins test
  pandas/tests/reshape/test_tile.py
Labels: Interval, Reshaping, Testing

#24015 DEPS: Pinning versions of some dependencies to speed up environment creation
  environment.yml
  requirements-dev.txt
Labels: Dependencies

#23385 DOC: Update DateOffset intro in timeseries.rst
  doc/source/timeseries.rst
Labels: Docs, Frequency, Timedelta

#24041 CLN: Adjust cdef types to fix MacPython 32 bit build
  pandas/_libs/tslibs/conversion.pyx
Labels: Clean

#24031 PERF: do NPY_NAT check inside get_datetime64_nanos
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
Labels: Performance, Timeseries

#24038 REF: Refactor Date/TimeLikeOps
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor, Timeseries

#24032 REF: Move non-raising parts of array_to_datetime outside of try/except
  pandas/_libs/tslib.pyx
Labels: Internals, Refactor, Timeseries

#23913 Fix the docstring of xs in pandas/core/generic.py #22892
  pandas/core/generic.py
Labels: Docs, Indexing

#23847 DOC: Upgrade flake8-rst version
  ci/deps/travis-36.yaml
  environment.yml
  requirements-dev.txt
  setup.cfg
Labels: Clean, Docs, Style

#23855 DOC: Fix flake8 problems in io.rst
  doc/source/io.rst
Labels: Docs, Style

#24045 BUG: all-na corner case for str.cat
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/strings.py
  pandas/tests/test_strings.py
Labels: Bug, Reshaping, Strings

#24049 REF: array_to_datetime catch overflows in one place
  pandas/_libs/tslib.pyx
Labels: Clean, Timeseries

#24003 Fix PEP-8 issues in contributing.rst
  doc/source/contributing.rst
  setup.cfg
Labels: Docs, Style

#24005 API: fix str-accessor on CategoricalIndex
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/strings.py
  pandas/tests/test_strings.py
Labels: Bug, Categorical, Indexing

#24008 PERF: optimize NaT lookups in cython modules
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Missing-data, Performance, Timeseries

#23963 BUG: CategoricalIndex allows reindexing with non-unique CategoricalIndex
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/indexes/category.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/indexes/test_category.py
Labels: Bug, Categorical, Indexing

#23991 BUG/TST: PeriodArray.__setitem__ with slice and list-like value
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/period.py
  pandas/tests/extension/base/setitem.py
Labels: Period, Testing

#22854 CI: Linting with azure instead of travis
  .travis.yml
  azure-pipelines.yml
  ci/code_checks.sh
  ci/deps/travis-36.yaml
  environment.yml
  pandas/core/frame.py
  pandas/core/panel.py
  pandas/core/tools/timedeltas.py
  pandas/core/window.py
  pandas/io/gbq.py
  pandas/io/json/json.py
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
Labels: CI, Style

#23864 ZeroDivisionError when groupby rank with method="dense" and pct=True
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/groupby_helper.pxi.in
  pandas/tests/groupby/test_rank.py
Labels: Error Reporting, Groupby

#24013 TST/CLN: parametrize tests\resample\test_time_grouper.py
  pandas/tests/resample/conftest.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_time_grouper.py
Labels: Resample, Testing

#23675 REF/DEPR: DatetimeIndex constructor
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
  pandas/core/tools/datetimes.py
Labels: Deprecate, Timeseries

#23721 TST: clean up to change setup.cfg to `xfail_strict = True` (GH23057)
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/frame/test_combine_concat.py
  pandas/tests/frame/test_duplicates.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/multi/test_missing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/parser/test_usecols.py
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_period.py
  pandas/tests/series/test_rank.py
  pandas/tests/sparse/frame/test_analytics.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/frame/test_indexing.py
  pandas/tests/sparse/series/test_indexing.py
  pandas/tests/test_downstream.py
  pandas/tests/test_window.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
  pandas/util/_test_decorators.py
  setup.cfg
Labels: Testing

#24039 REF: Refactor Datetimelike delegation
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/period.py
Labels: Refactor

#24065 DOC: Fix quotes position in Series docstrings
  pandas/core/accessor.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexing.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/core/tools/datetimes.py
  pandas/plotting/_converter.py
  pandas/plotting/_core.py
Labels: Clean, Docs, Style

#24062 CI: Fixing benchmark log
  azure-pipelines.yml
Labels: CI

#24054 TST: run setitem tests for IntegerArray
  pandas/core/arrays/integer.py
  pandas/tests/extension/test_integer.py
Labels: ExtensionArray, Testing

#23990 REF/API: DatetimeTZDtype
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
  pandas/core/internals/blocks.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/io/json/test_json_table_schema.py
Labels: Dtypes, Timeseries, Timezones

#24083 PERF: Define PeriodArray._values_for_argsort
  pandas/core/arrays/period.py
Labels: Performance, Period

#24073 TST: use s3_resource fixture consistently
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/test_excel.py
Labels: Data IO, Testing

#24080 remove calls to DataFrame.consolidate in benchmarks
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/join_merge.py
Labels: Deprecate, Performance

#24075 CI/TST: Making ci/run_tests.sh fail if one of the steps fail
  ci/run_tests.sh
Labels: CI, Testing

#23601 Add default repr for EAs
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse.py
  pandas/core/indexes/period.py
  pandas/core/internals/blocks.py
  pandas/io/formats/format.py
  pandas/io/formats/printing.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/arrays/test_period.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/base/printing.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/series/test_repr.py
Labels: ExtensionArray

#20475 Additional DOC and BUG fix related to merging with mix of columns and…
  doc/source/merging.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Bug, Docs, Reshaping

#24090 TST: Work around statsmodels bug
  pandas/tests/plotting/test_datetimelike.py
Labels: CI, Testing

#24092 CI: remove failing line
  asv_bench/benchmarks/algorithms.py
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/groupby.py
  pandas/core/sparse/scipy_sparse.py
  pandas/io/formats/html.py
  pandas/tests/io/conftest.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/sparse/frame/test_to_from_scipy.py
  setup.cfg
Labels: CI

#24102 Check import warning
  ci/code_checks.sh
  pandas/compat/__init__.py
  pandas/core/tools/datetimes.py
Labels: Compat

#24056 BUG/TST: Fix TimedeltaIndex comparisons with invalid types
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/generic.py
  pandas/core/ops.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/util/testing.py
Labels: Error Reporting, Timedelta

#24100 REF: Separate out DataFrame/Series Construction Helpers
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/core/series.py
  pandas/core/sparse/frame.py
Labels: Clean, Internals

#24096 BUG: fix mutation of DTI backing Series/DataFrame
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/core/series.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/series/test_block_internals.py
Labels: Timeseries

#23981 PERF: ascii c string functions
  LICENSES/MUSL_LICENSE
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/src/headers/portable.h
  pandas/_libs/src/parse_helper.h
  pandas/_libs/src/parser/tokenizer.c
Labels: Performance, Windows

#24116 CLN: Follow-up to #24100
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Clean

#24074 Implement DatetimeArray._from_sequence
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
Labels: ExtensionArray, Reshaping, Timeseries

#24027 BUG: Fix concat series loss of timezone
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/dtypes/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Bug, Reshaping, Timeseries

#24120 REF/TST: Add more pytest idiom to scalar/test_nat
  pandas/tests/scalar/test_nat.py
Labels: Refactor, Testing

#24107 REF/TST: Add pytest idiom to reshape/test_tile
  pandas/tests/reshape/test_cut.py
  pandas/tests/reshape/test_qcut.py
  pandas/tests/reshape/test_tile.py
Labels: Refactor, Testing

#24113 BUG: use internal linkage (static variables) in move.c
  doc/source/whatsnew/v0.24.0.rst
  pandas/util/move.c
Labels: Bug, Compat

#23673 DOC: Add missing docstring error to validate_docstrings.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#24126 Fix error GL07
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/interval.py
  pandas/core/base.py
  pandas/core/computation/eval.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/ops.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/numeric.py
  pandas/core/window.py
  pandas/io/excel.py
  pandas/io/formats/style.py
  pandas/io/html.py
  pandas/io/json/json.py
  pandas/io/json/table_schema.py
  pandas/io/sql.py
Labels: Clean, Docs

#23100 DOC: Improve the docstring of pd.Index.contains and closes PR #20211
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
Labels: Docs, Indexing

#24141 REF/TST: Add more pytest idiom to util/test_util
  pandas/tests/util/test_deprecate_kwarg.py
  pandas/tests/util/test_locale.py
  pandas/tests/util/test_move.py
  pandas/tests/util/test_safe_import.py
  pandas/tests/util/test_util.py
  pandas/tests/util/test_validate_args.py
  pandas/tests/util/test_validate_args_and_kwargs.py
  pandas/tests/util/test_validate_kwargs.py
Labels: Refactor, Testing

#24150 DOC: fix warnings in whatsnew about MI.labels -> codes rename
  doc/source/whatsnew/v0.10.1.rst
  doc/source/whatsnew/v0.20.0.rst
Labels: Docs

#24149 BUG: Fixed block placment from reindex(?)
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/internals.pyx
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/methods.py
  pandas/tests/internals/test_internals.py
Labels: Indexing, Internals

#18201 DOC: Update parquet metadata format description around index levels
  doc/source/developer.rst
Labels: Docs, IO Parquet

#24105 DOC: Corrects 'reindex_axis' docstring
  pandas/core/generic.py
Labels: Docs

#23947 Fixing shift() for ExtensionArray
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/sparse.py
  pandas/tests/extension/base/methods.py
Labels: ExtensionArray, Reshaping

#24163 API: Revert breaking `.values` changes
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/reshape/reshape.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/series/test_dtypes.py
  pandas/util/testing.py
Labels: API Design, Dtypes, ExtensionArray

#23915 BUG - remove scaling multiplier from `Period` diff result
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/conftest.py
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/tseries/offsets/conftest.py
Labels: Algos, Bug, Period

#23141 ENH: MultiIndex.from_frame
  doc/source/advanced.rst
  doc/source/api.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_constructor.py
  pandas/tests/indexes/multi/test_conversion.py
Labels: Enhancement, MultiIndex

#24154 DOC: update usage of randn in io.rst
  doc/source/io.rst
Labels: Clean, Docs

#23936 DOC: fix DataFrame.quantile docstring and doctests
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Clean, Docs

#24155 BUG: Throw ValueError when the format kwarg is passed to the HDFStore…
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/pytables.py
  pandas/tests/io/test_pytables.py
Labels: API Design, IO HDF5

#24140 Added log10 to the list of unary functions df.eval can handle
  doc/source/enhancingperf.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/computation/ops.py
Labels: Numeric

#24182 DOC: Fixes to the docs style
  doc/source/advanced.rst
  doc/source/categorical.rst
  doc/source/extending.rst
  doc/source/merging.rst
  setup.cfg
Labels: Clean, Docs, Style

#24189 DOC: Fix 10min.rst flake8 issues
  doc/source/10min.rst
  setup.cfg
Labels: Clean, Docs

#24186 DOC: Fix visualization.rst flake8 issues
  doc/source/visualization.rst
  setup.cfg
Labels: Clean, Docs

#24185 DOC: Repair doc/source/merging.rst flake8 issues
  doc/source/merging.rst
  setup.cfg
Labels: Clean, Docs

#24187 DOC: Fix dsintro.rst flake8 issues
  doc/source/dsintro.rst
  setup.cfg
Labels: Clean, Docs

#24183 DOC: Fix flake8 issues in doc/source/reshaping.rst
  doc/source/reshaping.rst
  setup.cfg
Labels: Docs

#24114 BUG/Perf: Support ExtensionArrays in where
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse.py
  pandas/core/indexes/category.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/test_period.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_sparse.py
Labels: ExtensionArray, Indexing

#24069 DOC: Correct/update skipna docstrings for `any` and `all` (#23109)
  pandas/core/generic.py
Labels: Docs

#24203 DEPR: Deprecating .clip_lower and .clip_upper
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Deprecate

#24191 DOC: Adding header to the rst files that don't have it
  doc/source/api.rst
  doc/source/contributing_docstring.rst
  doc/source/developer.rst
  doc/source/ecosystem.rst
  doc/source/extending.rst
  doc/source/options.rst
  doc/source/overview.rst
  doc/source/r_interface.rst
  doc/source/releases.rst
  doc/source/tutorials.rst
  scripts/validate_docstrings.py
Labels: Docs

#24204 BUG/PERF: Use EA in Index.get_value
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/indexes/base.py
  pandas/tests/arrays/categorical/test_indexing.py
Labels: ExtensionArray, Performance

#24217 Fix flake8 issues on v22, v23 and v24rst
  doc/source/whatsnew/v0.22.0.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.24.0.rst
  setup.cfg
Labels: Clean, Docs

#24053 REF/TST: Add more pytest idiom to indexing/multiindex/test_getitem.py
  pandas/tests/indexing/multiindex/test_getitem.py
Labels: Indexing, MultiIndex, Refactor, Testing

#23111 CI: Some Azure Pipelines cleanups
  azure-pipelines.yml
  ci/azure/linux.yml
  ci/azure/posix.yml
  ci/azure/windows-py27.yml
  ci/azure/windows.yml
Labels: CI, Testing

#24170 remove enum import for PY2 compat, xref #22802
  pandas/_libs/tslibs/timestamps.pyx
Labels: 2/3 Compat

#24199 DOC: Fixed implicit imports for whatsnew (v >= version 20.0)
  doc/source/whatsnew/v0.23.1.rst
  doc/source/whatsnew/v0.23.2.rst
  doc/source/whatsnew/v0.23.4.rst
  doc/source/whatsnew/v0.24.0.rst
Labels: Clean, Docs

#24232 DOC: add back currentmodule to api.rst
  doc/source/api.rst
Labels: Docs

#24190 DOC: Fix summaries not ending with a period
  pandas/core/accessor.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/generic.py
  pandas/core/indexes/accessors.py
  pandas/plotting/_core.py
Labels: Clean, Docs

#21235 pct change bug issue 21200
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_transform.py
Labels: Bug, Groupby

#24254 BLD: json deprecated unicode capi
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Build, IO JSON

#24134 Fix repr of DataFrame with IntervalIndex
  pandas/core/indexes/interval.py
  pandas/io/formats/format.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/period/test_formats.py
  pandas/tests/indexes/test_category.py
Labels: Blocker, Bug, Interval, Output-Formatting

#23398 ENH: to_list as alias for tolist
  doc/source/api.rst
  doc/source/timedeltas.rst
  doc/source/timeseries.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/base.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/test_base.py
Labels: API Design

#24236 Fix flake8 issues on v19, v20 and v21.0.rst
  doc/source/whatsnew/v0.19.0.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v0.21.0.rst
  setup.cfg
Labels: Docs

#24159 BUG - anchoring dates for resample with Day(n>1)
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/resample.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/resample/test_datetime_index.py
Labels: Bug, Frequency, Resample

#23715 Add option for DataFrame.to_html() to render URL data as links (#2679)
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/tests/io/formats/data/render_links_false.html
  pandas/tests/io/formats/data/render_links_true.html
  pandas/tests/io/formats/test_to_html.py
Labels: Enhancement, IO HTML

#24230 REF/TST: Add more pytest idiom to tests/resample
  pandas/tests/resample/conftest.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_timedelta.py
Labels: Resample, Testing

#24238 DOC: avoid warnings ipython 'Code input with no code'
  doc/source/advanced.rst
  doc/source/reshaping.rst
  doc/source/whatsnew/v0.17.0.rst
  doc/source/whatsnew/v0.24.0.rst
Labels: Docs

#24215 Fix docstring of functions created with the deprecate() function
  pandas/tests/util/test_deprecate.py
  pandas/util/_decorators.py
Labels: Docs

#24272 REF/TST: Add more pytest idiom to indexing/multiindex/test_iloc.py
  pandas/tests/indexing/multiindex/test_iloc.py
Labels: Indexing, Testing

#24276 implement independent parts of #24024
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimes.py
  pandas/io/formats/format.py
  pandas/tests/indexes/datetimes/test_astype.py
  pandas/tests/indexes/period/test_astype.py
  pandas/tests/indexes/timedeltas/test_astype.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/series/test_datetime_values.py
  pandas/tests/series/test_timeseries.py
  pandas/tests/test_base.py
  pandas/util/testing.py
  setup.cfg
Labels: Clean, Timeseries

#24253 Flake8 rst v0.14.x.rst
  doc/source/whatsnew/v0.14.0.rst
  doc/source/whatsnew/v0.14.1.rst
  setup.cfg
Labels: Docs

#24157 BUG: Assorted DatetimeIndex bugfixes
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Deprecate, Timeseries

#23941 BUG/ENH - base argument no longer ignored in period resample
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
Labels: Bug, Resample, Timeseries

#24277 DOC: Fix flake8 issues in whatsnew v10* and v11*
  doc/source/whatsnew/v0.10.0.rst
  doc/source/whatsnew/v0.10.1.rst
  doc/source/whatsnew/v0.11.0.rst
  setup.cfg
Labels: Docs

#24281 DOC: Removing tailing whitespaces in .rst files
  doc/source/advanced.rst
  doc/source/categorical.rst
  doc/source/comparison_with_sas.rst
  doc/source/computation.rst
  doc/source/enhancingperf.rst
  doc/source/gotchas.rst
  doc/source/overview.rst
  doc/source/timedeltas.rst
  doc/source/timeseries.rst
  doc/source/tutorials.rst
Labels: Clean, Docs

#24273 DOC: FIx flake8 errors for whatsnew v0.7.* -v0.9.* rst
  doc/source/whatsnew/v0.7.0.rst
  doc/source/whatsnew/v0.7.1.rst
  doc/source/whatsnew/v0.7.2.rst
  doc/source/whatsnew/v0.7.3.rst
  doc/source/whatsnew/v0.8.0.rst
  doc/source/whatsnew/v0.8.1.rst
  doc/source/whatsnew/v0.9.0.rst
  doc/source/whatsnew/v0.9.1.rst
  setup.cfg
Labels: Clean, Docs

#24285 REF: Period check compatabile with
  pandas/core/arrays/period.py
Labels: Refactor

#24286 CLN: Linting tailing whitespaces, and fixing remaining cases
  ci/code_checks.sh
  doc/source/_static/banklist.html
  doc/source/whatsnew/v0.20.3.rst
  doc/source/whatsnew/whatsnew_0171_html_table.html
  pandas/_libs/src/msgpack/unpack_template.h
  pandas/io/formats/templates/html.tpl
  pandas/tests/io/data/banklist.html
  pandas/tests/io/data/macau.html
  pandas/tests/io/data/nyse_wsj.html
  pandas/tests/io/data/spam.html
  pandas/tests/io/data/wikipedia_states.html
  pandas/tests/io/parser/data/salaries.csv
  pandas/tests/reshape/data/cut_data.csv
Labels: CI, Clean

#24287 DOC: Remove doc spellcheck
  doc/source/conf.py
  doc/source/names_wordlist.txt
  doc/source/spelling_wordlist.txt
Labels: Clean, Docs

#24291 DOC: Add new required sphinx setting latex_elements
  doc/source/conf.py
Labels: Docs

#24098 DOC: Use official numpydoc extension
  ci/deps/travis-36-doc.yaml
  doc/source/conf.py
  doc/sphinxext/numpydoc/LICENSE.txt
  doc/sphinxext/numpydoc/README.rst
  doc/sphinxext/numpydoc/__init__.py
  doc/sphinxext/numpydoc/docscrape.py
  doc/sphinxext/numpydoc/docscrape_sphinx.py
  doc/sphinxext/numpydoc/numpydoc.py
  doc/sphinxext/numpydoc/templates/numpydoc_docstring.rst
  doc/sphinxext/numpydoc/tests/test_docscrape.py
  environment.yml
  pandas/core/ops.py
  requirements-dev.txt
Labels: Docs

#23731 CI for boto: fix errors; add coverage; add skip for uncatchable ResourceWarning
  .travis.yml
  ci/deps/travis-36.yaml
  ci/deps/travis-37.yaml
  environment.yml
  pandas/tests/io/conftest.py
  pandas/util/testing.py
  requirements-dev.txt
Labels: CI, Data IO

#24289 Revert #21394
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Timedelta

#24284 API: Always return DataFrame from get_dummies
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/reshape/test_reshape.py
Labels: API Design, Reshaping, Sparse

#24292 DOC: Making the build fail if the doc build fails
  .travis.yml
  ci/build_docs.sh
  ci/run_build_docs.sh
  doc/make.py
Labels: CI, Docs

#24188 DOC: Deprecation directive in Docstrings should be placed before the extended summary
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/io/stata.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#24132 DOC: Fix order section in docstrings (part II)
  pandas/_libs/interval.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/accessor.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/core/window.py
Labels: Clean, Docs

#24299 DOC: Removing remaining spellcheck related stuff (deps, docs, code, whatsnew)
  doc/make.py
  doc/source/contributing.rst
  doc/source/whatsnew/v0.24.0.rst
  environment.yml
  requirements-dev.txt
Labels: Clean, Docs

#24283 CLN: standardize different freq message
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/indexes/period.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/indexes/period/test_indexing.py
Labels: Error Reporting, Frequency, Timeseries

#24307 TST: Fix flakey hypothesis apply test
  pandas/tests/frame/test_apply.py
Labels: Testing

#24309 DOC: flake8 fix for whatsnew v.0.12.*
  doc/source/whatsnew/v0.12.0.rst
  setup.cfg
Labels: Docs

#24297 STY: use pytest.raises context syntax
  pandas/tests/api/test_types.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/frame/test_apply.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_quantile.py
  pandas/tests/generic/test_frame.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexes/datetimes/test_astype.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_panel.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/indexing/test_numeric.py
  pandas/tests/series/test_apply.py
  pandas/tests/test_base.py
  pandas/tests/test_lib.py
Labels: Style

#24313 CLN: Add issue number
  pandas/tests/frame/test_apply.py
Labels: Testing

#24316 DOC: Not pushing the docs to github pages in PRs
  ci/build_docs.sh
Labels: CI, Docs

#24172 DOC: Link to dev version of contributing guide from README.md
  .github/CONTRIBUTING.md
  README.md
  doc/README.rst
Labels: Docs

#24308 PERF: Period plotting performance
  pandas/plotting/_converter.py
  setup.cfg
Labels: Performance, Visualization

#24298 DOC: whatsnew 0.24.0 corrections & edits & remove some warnings
  doc/source/api.rst
  doc/source/basics.rst
  doc/source/conf.py
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/indexes/accessors.py
Labels: Docs

#24117 DOC: Add pandas video series to tutorials.rst
  doc/source/tutorials.rst
Labels: Docs, Needs Discussion

#24303 DOC: Fix flake8 issues with whatsnew v0.18.*
  doc/source/whatsnew/v0.18.0.rst
  doc/source/whatsnew/v0.18.1.rst
  setup.cfg
Labels: Clean, Docs

#24334 DOC: Fix a few warnings
  doc/source/ecosystem.rst
  doc/source/timeseries.rst
Labels: Docs

#24327 ERR: Improve error message for cut with infinity in input and integer bins
  pandas/core/reshape/tile.py
  pandas/tests/reshape/test_cut.py
Labels: Error Reporting, Reshaping

#24335 BUG: Fixed msgpack roundtrip with PeriodIndex
  pandas/core/indexes/period.py
  pandas/io/packers.py
  pandas/tests/io/test_packers.py
Labels: IO Msgpack

#24337 BUG: Fix GSO values when writing latin-1 strLs
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Bug, IO Stata

#24338 DOC: Fix flake 8 errors for whatsnew v0.16*
  doc/source/whatsnew/v0.16.0.rst
  doc/source/whatsnew/v0.16.1.rst
  doc/source/whatsnew/v0.16.2.rst
  setup.cfg
Labels: Docs

#24322 DOC: Fixes flake8 issues in whatsnew v0.13.* #24256
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v0.13.1.rst
  setup.cfg
Labels: Clean, Docs

#24319 BUG: Ensure incomplete stata files are deleted
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata

#24330 API: Remove CalendarDay
  doc/source/timeseries.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/resample.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/timedeltas/test_timedelta_range.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/series/test_timezones.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/tseries/offsets.py
Labels: API Design, Frequency

#24342 DOC: Fixes additional flake8 issues in whatsnew v0.14.0 #24240
  doc/source/whatsnew/v0.14.0.rst
Labels: Clean, Docs

#24343 CLN: simplify CategoricalIndex internals
  pandas/core/indexes/category.py
Labels: Categorical, Internals

#23024 DOC: Upgraded Docstring pandas.DataFrame.dot
  pandas/core/frame.py
Labels: Docs, Numeric

#24288 DOC: Fix docstrings with the sections in the wrong order #24280
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/window.py
Labels: Docs

#24341 API: Standard signature for to_numpy
  doc/source/basics.rst
  pandas/core/base.py
  pandas/core/frame.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/multi/test_conversion.py
  pandas/tests/test_base.py
Labels: ExtensionArray

#24332 STY: Check pytest.raises is used context manager
  ci/code_checks.sh
Labels: CI, Style

#24361 REF/TST: Add more pytest idiom to test_read_fwf.py
  pandas/tests/io/parser/test_compression.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/util/testing.py
Labels: Refactor, Testing

#24331 DOC: Update compiler guidance for Windows
  doc/source/contributing.rst
Labels: Docs, Windows

#24349 ENH: ExtensionArray.repeat
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/base.py
  pandas/tests/extension/base/methods.py
Labels: ExtensionArray

#24379 implement _index_data parts of #24024
  pandas/_libs/reduction.pyx
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Internals

#24378 implement ensure_localized in datetimelikeArrayMixin
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/datetimelike.py
Labels: Clean, Timeseries

#24376 REF/TST: Collect Straggler Arithmetic Tests
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_range.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_operators.py
Labels: Numeric, Testing

#24370 REF/TST: Add more pytest idiom to indexing/multiindex/test_xs.py
  pandas/tests/indexing/multiindex/test_xs.py
Labels: Indexing, Testing

#24369 REF/TST: Add pytest idiom to test_testing
  ci/code_checks.sh
  pandas/tests/util/conftest.py
  pandas/tests/util/test_assert_almost_equal.py
  pandas/tests/util/test_assert_categorical_equal.py
  pandas/tests/util/test_assert_extension_array_equal.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/util/test_assert_index_equal.py
  pandas/tests/util/test_assert_interval_array_equal.py
  pandas/tests/util/test_assert_numpy_array_equal.py
  pandas/tests/util/test_assert_series_equal.py
  pandas/tests/util/test_testing.py
  pandas/tests/util/test_util.py
Labels: Refactor, Testing

#24356 COMPAT: Add keepdims and friends to validation
  doc/source/whatsnew/v0.24.0.rst
  pandas/compat/numpy/function.py
  pandas/core/generic.py
  pandas/tests/series/test_analytics.py
Labels: Compat

#24372 BUG/PERF: Sparse get_dummies uses concat
  asv_bench/benchmarks/join_merge.py
  asv_bench/benchmarks/panel_ctor.py
  asv_bench/benchmarks/reindex.py
  asv_bench/benchmarks/timedelta.py
  asv_bench/benchmarks/timestamp.py
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/dtypes/concat.py
  pandas/core/reshape/reshape.py
  pandas/tests/sparse/test_reshape.py
Labels: Performance, Sparse

#23801 API: Make Series.searchsorted return a scalar, when supplied a scalar
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/base.py
  pandas/core/series.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/indexes/multi/test_monotonic.py
  pandas/tests/series/test_analytics.py
Labels: Dtypes, Reshaping

#24393 TST: Add missing match parameter in test_move
  pandas/tests/util/test_move.py
Labels: Testing

#24365 CLN: post-post numpy bump
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/util/test_util.py
Labels: Clean, Dependencies

#24352 DEPR: Undeprecate period - integer addition
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
Labels: Deprecate
