Repository pandas-dev/pandas, pull requests merged in 2018-07, with the labels that each got.

#21693 use liboffsets to_offset function
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/offsets.pxd
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  setup.py
Labels: Clean, Frequency

#21690 Misc cleanups, test parametrization
  pandas/_libs/src/inference.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/tslibs/test_tslib.py
Labels: Testing, Timeseries

#21706 DOC: consistent sphinx title levels
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21655 BUG: Fix MI repr with long names
  doc/source/whatsnew/v0.23.2.txt
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Needs Backport, Output-Formatting

#21709 DOC: move whatsnew on performance from 0.23.2 to 0.24.0
  doc/source/whatsnew/v0.23.2.txt
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21696 add unit test for writing to already open file
  pandas/tests/io/formats/test_to_csv.py
Labels: IO CSV, Output-Formatting, Testing

#21692 move is_null_datetimelike to nattype for self-containment
  pandas/_libs/missing.pxd
  pandas/_libs/missing.pyx
  pandas/_libs/src/inference.pyx
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/period.pyx
  setup.py
Labels: Missing-data, Timeseries

#21691 move and de-privatize _localize_pydatetime, move shift_day to liboffsets
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/test_timezones.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_timezones.py
  pandas/tseries/offsets.py
Labels: Clean, Frequency, Timezones

#21674 TST/CLN: Old timezone issues PT3
  doc/source/whatsnew/v0.24.0.txt
  pandas/tests/frame/test_missing.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/reshape/test_concat.py
Labels: Testing, Timezones

#21660 BUG: Issues with DatetimeTZ values in where and combine_first (#21469 + #21546)
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/common.py
  pandas/core/internals.py
  pandas/core/series.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/test_combine_concat.py
Labels: Bug, Indexing, MultiIndex, Timezones

#19902 ENH: implement DatetimeLikeArray
  pandas/core/arrays/__init__.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Enhancement, ExtensionArray, Internals

#21710 remove unused cimport, parametrize test
  pandas/_libs/internals.pyx
  pandas/_libs/writers.pyx
  pandas/tests/sparse/test_libsparse.py
Labels: Testing

#21702 CLN: to_datetime internals
  pandas/core/tools/datetimes.py
Labels: Clean

#21694 move _add__ and __sub__ to liboffsets, implement _Tick
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/tseries/offsets.py
Labels: Clean, Frequency

#21185 ENH: add in extension dtype registry
  doc/source/extending.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/interval.py
  pandas/core/internals.py
  pandas/core/series.py
  pandas/io/formats/format.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
Labels: ExtensionArray

#21714 De-privatize tslibs functions
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/indexes/accessors.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/indexes/period/test_tools.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/tseries/offsets/test_fiscal.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/test_frequencies.py
  pandas/tests/tslibs/test_libfrequencies.py
  pandas/tseries/frequencies.py
Labels: Clean

#20956 ENH: Return DatetimeIndex or TimedeltaIndex bins for q/cut when input is datelike
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/reshape/tile.py
  pandas/tests/reshape/test_tile.py
Labels: Timedelta, Timeseries

#21711 ENH: Add set_closed method to IntervalIndex
  doc/source/api.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: API Design, Enhancement, Interval

#21514 split up pandas/tests/indexes/test_multi.py #18644
  pandas/tests/indexes/multi/__init__.py
  pandas/tests/indexes/multi/conftest.py
  pandas/tests/indexes/multi/data/mindex_073.pickle
  pandas/tests/indexes/multi/data/multiindex_v1.pickle
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/multi/test_compat.py
  pandas/tests/indexes/multi/test_constructor.py
  pandas/tests/indexes/multi/test_contains.py
  pandas/tests/indexes/multi/test_conversion.py
  pandas/tests/indexes/multi/test_copy.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexes/multi/test_equivalence.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/multi/test_get_set.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/multi/test_missing.py
  pandas/tests/indexes/multi/test_monotonic.py
  pandas/tests/indexes/multi/test_names.py
  pandas/tests/indexes/multi/test_operations.py
  pandas/tests/indexes/multi/test_partial_indexing.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/multi/test_set_ops.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexes/multi/test_unique_and_duplicates.py
  pandas/tests/indexes/test_multi.py
Labels: MultiIndex, Testing

#21717 TST: Parametrize tests in tools/test_numeric.py
  pandas/tests/tools/test_numeric.py
Labels: Clean, Numeric, Testing

#21719 docstring and whitespace cleanup
  pandas/_libs/groupby.pyx
  pandas/_libs/tslibs/conversion.pyx
Labels: Clean, Docs

#21712 Move Unchanged arith methods to EA mixins
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Internals, Refactor

#21724 CLN: Delay converting bins to datetimelike until necessary
  pandas/core/reshape/tile.py
Labels: Clean, Timeseries

#20446 scatter plot and hexbin plot lose x-axis when colorbar is included.
  doc/source/whatsnew/v0.24.0.txt
  pandas/plotting/_core.py
  pandas/tests/plotting/test_frame.py
Labels: Visualization

#21727 Implement _tz_convert_tzlocal_utc for de-duplication
  pandas/_libs/tslibs/conversion.pyx
Labels: Clean, Timezones

#21722 move ndarray-returning functions to EA mixin classes
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Timeseries

#21738 Implement tslibs.__init__, move easy bits of tslib
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/generic.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_tslib.py
Labels: Clean, Internals, Timedelta, Timeseries

#21744 TST: catch warnings for to_hierarchical deprecation
  pandas/tests/indexes/multi/test_conversion.py
Labels: Deprecate, Testing

#21735 DOC: Add nrows to DataFrame.from_records docstring
  pandas/core/frame.py
Labels: Docs

#21728 misplaced scatter/hexbin subplot colorbars
  doc/source/whatsnew/v0.24.0.txt
  pandas/plotting/_core.py
  pandas/tests/plotting/test_frame.py
Labels: Visualization

#21721 implement _local_timestamps in DatetimeArrayMixin
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
Labels: Clean, Timeseries

#21487 read_html: Handle colspan and rowspan
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: Enhancement, IO HTML

#21750 DOC: clean-up 0.23.2 whatsnew file
  doc/source/whatsnew/v0.23.2.txt
Labels: Docs

#21739 CLN/TST: Cleanup tests in test_ujson.py
  pandas/conftest.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/util/test_util.py
  pandas/util/testing.py
Labels: Clean, IO JSON, Testing

#21745 DOC: Update documentation with correct link
  doc/source/whatsnew/v0.20.0.txt
Labels: Docs

#21754 DOC: Correct docstring for check_dtype in assert_almost_equal
  pandas/util/testing.py
Labels: Docs, Testing

#21731 Fixes example code in docstring of pandas.DataFrame.query
  pandas/core/frame.py
Labels: Docs

#21614 DEPR: Series.ptp()
  doc/source/api.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/tests/series/test_analytics.py
Labels: Deprecate, Numeric

#21759 Fix whatsnew dates
  doc/source/whatsnew/v0.23.1.txt
  doc/source/whatsnew/v0.23.2.txt
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21753 CLN: clean up groupby / categorical
  pandas/core/arrays/categorical.py
  pandas/core/groupby/categorical.py
  pandas/core/groupby/groupby.py
Labels: Categorical, Groupby, Refactor

#21756 TST: Remove check_exact from assert_almost_equal
  pandas/util/testing.py
Labels: Testing

#21730 implement _tz_convert_dst for de-duplication
  pandas/_libs/tslibs/conversion.pyx
Labels: Clean, Timezones

#21764 Followup to #21738
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/tslibs/test_api.py
Labels: Clean, Docs

#21771 Whatsnew note for v0.23.3
  doc/source/whatsnew/v0.23.3.txt
Labels: Docs

#21663 DOC: Fixup docstring [ci skip]
  doc/source/merging.rst
  doc/source/text.rst
  doc/source/whatsnew/v0.10.0.txt
  doc/source/whatsnew/v0.13.1.txt
  doc/source/whatsnew/v0.14.1.txt
  doc/source/whatsnew/v0.15.0.txt
  doc/source/whatsnew/v0.17.1.txt
  doc/source/whatsnew/v0.24.0.txt
  doc/source/whatsnew/v0.8.0.txt
  pandas/core/series.py
Labels: Docs

#21776 Move methods and properties to EA Mixin classes
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Timeseries

#21332 Series.describe returns first and last for tz-aware datetimes
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Bug, Timezones

#21769 Removed Need for OHLC As First Element if Used in .agg
  doc/source/whatsnew/v0.23.3.txt
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby

#21780 Replaces Exceptions with ValueError in MultiIndex, closes #21770
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_reindex.py
Labels: Error Reporting, MultiIndex

#20864 DOC: Improve the docstring of String.str.zfill()
  pandas/core/strings.py
Labels: Docs, Strings

#21779 TST: Add more information for unexpected warnings
  pandas/util/testing.py
Labels: Error Reporting, Testing

#21782 REF: move more methods to EAMixins
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Refactor

#20145 DOC: Added examples to the IndexOpsmixin.value_counts() docstring
  pandas/core/base.py
Labels: Docs

#20269 DOC: update NDFrame.squeeze docstring
  pandas/core/generic.py
Labels: Docs

#18604 ENH: Raise error for 'sheet' arg in read_excel
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/excel.py
  pandas/tests/io/test_excel.py
Labels: Error Reporting, IO Excel

#21794 Removed Need for OHLC As First Element if Used in .agg (#21769)
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Numeric

#21774 Changed import statements in examples in DOCs
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/panel.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/core/sparse/series.py
  pandas/core/tools/numeric.py
  pandas/io/pytables.py
  pandas/io/sas/sas_xport.py
  pandas/io/stata.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/tseries/holiday.py
Labels: Docs

#21688 Accept constant memoryviews in HashTable.lookup
  ci/appveyor-27.yaml
  ci/appveyor-36.yaml
  ci/circle-27-compat.yaml
  ci/circle-35-ascii.yaml
  ci/circle-36-locale.yaml
  ci/circle-36-locale_slow.yaml
  ci/environment-dev.yaml
  ci/travis-27-locale.yaml
  ci/travis-27.yaml
  ci/travis-35-osx.yaml
  ci/travis-36-doc.yaml
  ci/travis-36-numpydev.yaml
  ci/travis-36-slow.yaml
  ci/travis-36.yaml
  ci/travis-37.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/conftest.py
  pandas/tests/test_algos.py
  setup.py
Labels: Algos, Dependencies

#20344 DOC: update the pd.Index.asof docstring
  pandas/core/indexes/base.py
Labels: Docs

#20148 DOC: Improved the docstring of pandas.Series.filter
  pandas/core/generic.py
Labels: Docs

#21798 move PeriodIndex comparisons, implement PeriodArray constructor
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Period

#20228 DOC:Improve the docstring of DataFrame.iloc()
  pandas/core/indexing.py
Labels: Docs, Indexing

#21795 TST: create pandas/tests/arrays to consolidate pandas-extension array testing
  pandas/tests/arrays/__init__.py
  pandas/tests/arrays/categorical/__init__.py
  pandas/tests/arrays/categorical/common.py
  pandas/tests/arrays/categorical/conftest.py
  pandas/tests/arrays/categorical/test_algos.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/arrays/categorical/test_sorting.py
  pandas/tests/arrays/categorical/test_subclass.py
  pandas/tests/arrays/categorical/test_warnings.py
Labels: ExtensionArray, Testing

#20863 DOC: update the pandas.Series.str.strip docstring
  pandas/core/strings.py
Labels: Docs, Strings

#20237 DOC: update the DataFrame.combine and DataFrame.combine_first docstrings
  pandas/core/frame.py
Labels: Docs, Missing-data

#20910 Doc: Added docstring to Groupby mean
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#21800 Use CB3 syntax for compiler
  conda.recipe/meta.yaml
Labels: Build

#21805 DOC: Bunch o warnings
  doc/source/extending.rst
  doc/source/text.rst
  doc/source/whatsnew/v0.23.0.txt
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/indexes/datetimes.py
Labels: Docs

#21803 implement constructors for TimedeltaArray, DatetimeArray
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Period, Timedelta, Timeseries

#21122 Resolution docstring
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs, Timedelta

#20222 DOC: Improve the docstring of DataFrame.describe()
  pandas/core/generic.py
Labels: Docs, Numeric

#21808 More doc warnings
  doc/source/merging.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/strings.py
Labels: Docs

#17900 ENH: Add 'infer' option to compression in _get_handle()
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/common.py
  pandas/io/pickle.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_compression.py
Labels: Enhancement, IO CSV

#21811 Add unit test for #12813
  doc/source/whatsnew/v0.24.0.txt
  pandas/tests/test_algos.py
Labels: Algos, Bug

#21678 API: referring to duplicate level name raises ValueError
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/multi.py
  pandas/core/reshape/reshape.py
  pandas/tests/indexes/multi/test_unique_and_duplicates.py
Labels: API Design, MultiIndex

#20268 DOC: add documentation to core.window.corr
  pandas/core/window.py
Labels: Docs

#20289 DOC: update the pandas.DataFrame.clip_lower docstring
  pandas/core/generic.py
Labels: Docs

#20135 DOC: improved the docstring of pandas.Series.clip_upper improved
  pandas/core/generic.py
Labels: Docs

#21812 DOC: consolidate clip_upper and clip_lower docstrings
  pandas/core/generic.py
Labels: Docs

#20210 DOC: update the Index.get_level_values docstring
  pandas/core/indexes/base.py
Labels: Docs, MultiIndex

#20345 DOC: ecosystem: Vaex, Pandas on Ray, alphabetization, pandas-datareader
  doc/source/ecosystem.rst
Labels: Docs

#20165 DOC: update the pandas.Series.where docstring
  pandas/core/generic.py
Labels: Docs

#21797 DOC: remove imports and use pd in docstrings
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/sparse/series.py
  pandas/core/strings.py
  pandas/core/window.py
  pandas/io/pytables.py
  pandas/plotting/_misc.py
Labels: Docs

#20333 DOC: update the Period.qyear docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#21496 Tseries fixtures docstrings
  pandas/conftest.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/tseries/conftest.py
  pandas/tests/tseries/offsets/conftest.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Docs, Testing, Timezones

#21816 update tslibs imports
  pandas/_libs/__init__.py
  pandas/_libs/index.pyx
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pyx
  pandas/_libs/reshape.pyx
  pandas/_libs/src/util.pxd
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/window.pyx
  pandas/core/arrays/timedelta.py
  pandas/core/common.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/missing.py
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals.py
  pandas/core/nanops.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/timedeltas.py
  pandas/core/util/hashing.py
  pandas/errors/__init__.py
  pandas/io/formats/format.py
  pandas/io/json/json.py
  pandas/io/stata.py
  pandas/plotting/_converter.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/tslibs/test_tslib.py
  pandas/tseries/frequencies.py
  pandas/tseries/offsets.py
  pandas/tslib.py
Labels: Clean, Timeseries

#21815 REF: Move most remaining arith helpers to datetimelike mixins
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Refactor, Timeseries

#20173 DOC: update the pandas.DataFrame.to_string docstring
  pandas/core/frame.py
  pandas/io/formats/format.py
Labels: Docs

#20912 BUG: DatetimeIndex._data should return an ndarray
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/io/pytables.py
  pandas/tests/indexes/test_base.py
Labels: Bug, Compat, Timeseries

#21821 DOC: Improve the docstring of Timedelta.asm8
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#20193 DOC: update the pandas.DataFrame.to_sparse docstring
  pandas/core/frame.py
Labels: Docs, Sparse

#21826 [CLN] cy cleanup, de-duplication
  pandas/_libs/index.pyx
  pandas/_libs/indexing.pyx
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/timezones.pyx
Labels: Clean, Timeseries

#21844 [CLN] cleanup import reverse-dependencies
  pandas/io/clipboards.py
  pandas/io/excel.py
  pandas/io/formats/csvs.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/formats/latex.py
  pandas/io/pytables.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_xport.py
  pandas/io/stata.py
  pandas/plotting/_converter.py
  pandas/plotting/_core.py
  pandas/plotting/_timeseries.py
  pandas/plotting/_tools.py
Labels: Clean

#21820 CLN: reorg groupby to multiple modules
  pandas/core/api.py
  pandas/core/base.py
  pandas/core/groupby/__init__.py
  pandas/core/groupby/base.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/window.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/test_whitelist.py
  pandas/tests/test_resample.py
Labels: Groupby, Refactor

#21861 CLN: miscellaneous cleanups / fixes
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/dtypes/inference.py
  pandas/core/frame.py
  pandas/core/indexes/datetimes.py
  pandas/core/series.py
  pandas/core/tools/timedeltas.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/test_internals.py
Labels: Bug, Clean

#21845 Move constructor helpers to EAMixins
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedelta.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Refactor, Timeseries

#21863 Replaced PANDAS_DATETIMEUNIT with NPY_DATETIMEUNIT
  pandas/_libs/src/datetime/np_datetime.c
  pandas/_libs/src/datetime/np_datetime.h
  pandas/_libs/src/datetime/np_datetime_strings.c
  pandas/_libs/src/datetime/np_datetime_strings.h
  pandas/_libs/src/period_helper.c
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/period.pyx
Labels: Clean, Timeseries

#21854 [CLN] resolve circular Period dependency, prepare setup.py
  pandas/_libs/__init__.py
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/resolution.pyx
  pandas/tests/tslibs/test_api.py
  setup.py
Labels: Build

#21259 ENH: Add support for tablewise application of style.background_gradient with axis=None
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/formats/style.py
  pandas/tests/io/formats/test_style.py
Labels: Enhancement, Output-Formatting

#21873 TST: Parameterize more tests
  pandas/conftest.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/series/indexing/test_boolean.py
Labels: Clean, Testing

#20611 REF: IntervalIndex[IntervalArray]
  doc/source/basics.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/interval.pyx
  pandas/core/arrays/__init__.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/util/hashing.py
  pandas/io/packers.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/interval/__init__.py
  pandas/tests/extension/interval/test_interval.py
  pandas/tests/extension/test_common.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/test_base.py
  pandas/tests/util/test_testing.py
  pandas/util/_doctools.py
  pandas/util/_exceptions.py
  pandas/util/testing.py
Labels: ExtensionArray, Interval

#21883 TST: Parametrize tests in tests/util/test_hashing.py
  pandas/tests/util/test_hashing.py
Labels: Clean, Testing

#21878 Cleanup cimports, implement bits of numpy_helper in util.pxd
  pandas/_libs/groupby.pyx
  pandas/_libs/index.pyx
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/src/numpy_helper.h
  pandas/_libs/src/util.pxd
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
Labels: Clean, Internals

#21872 [REF] Move comparison methods to EAMixins, share code
  pandas/_libs/src/numpy_helper.h
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/__init__.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/inference.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tseries/frequencies.py
Labels: Clean, Internals

#21867 BUG: np array indexer modifed in iloc
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
Labels: Bug, Indexing

#21886 use npy_datetimestruct instead of pandas_datetimestruct
  pandas/_libs/src/datetime/np_datetime.c
  pandas/_libs/src/datetime/np_datetime.h
  pandas/_libs/src/datetime/np_datetime_strings.c
  pandas/_libs/src/datetime/np_datetime_strings.h
  pandas/_libs/src/period_helper.c
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyx
Labels: Clean, Internals, Timeseries

#21897 DOC: move feature to correct whatsnew section; typos
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21912 Add statsmodels to optional dependencies
  ci/requirements-optional-conda.txt
  ci/requirements-optional-pip.txt
Labels: Build, Dependencies, Docs

#21898 TST: add test for duplicated frame/test_analytics
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_duplicates.py
Labels: Clean, Testing

#21899 TST/CLN: series.duplicated; parametrisation; fix warning
  pandas/conftest.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_duplicates.py
Labels: Testing

#21900 TST/CLN: clean up indexes/multi/test_unique_and_duplicates
  pandas/tests/indexes/multi/conftest.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/multi/test_names.py
Labels: MultiIndex, Testing

#21923 [BUG] change types to Py_ssize_t to fix #21905
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
Labels: 32bit, Bug

#21944 DOC add Python 2.7 warning to recent whatsnew; include 23.3
  doc/source/whatsnew.rst
  doc/source/whatsnew/v0.23.1.txt
  doc/source/whatsnew/v0.23.2.txt
  doc/source/whatsnew/v0.23.4.txt
  doc/source/whatsnew/v0.24.0.txt
Labels: Docs

#21914 Use the Agg backend for docs builds
  doc/make.py
Labels: Docs

#21870 [CLN] De-privatize commonly-used functions
  pandas/_libs/lib.pyx
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/timedeltas.py
  pandas/core/common.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/missing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/internals.py
  pandas/core/missing.py
  pandas/core/ops.py
  pandas/core/panel.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/reshape.py
  pandas/core/reshape/tile.py
  pandas/core/series.py
  pandas/core/sorting.py
  pandas/core/sparse/array.py
  pandas/core/sparse/frame.py
  pandas/core/sparse/series.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/numeric.py
  pandas/core/tools/timedeltas.py
  pandas/core/window.py
  pandas/io/formats/format.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_transform.py
  pandas/tests/indexes/test_base.py
Labels: Clean, Internals

#21934 BUG: Properly handle lists for .mask
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/series/indexing/test_boolean.py
Labels: Algos, Bug

#20413 DOC : update the pandas.Period.weekday docstring
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Period

#21921 BUG:Clip with a list-like threshold with a nan is broken (GH19992)
  doc/source/whatsnew/v0.23.4.txt
  pandas/core/generic.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Bug, Missing-data

#21966 Fix memory leak in roll_quantile
  doc/source/whatsnew/v0.23.4.txt
  pandas/_libs/window.pyx
Labels: Bug, Performance, Reshaping

#21960 standardize post-call treatment of get_dst_info, delay sorting calls
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/timezones.pyx
Labels: Internals, Refactor, Timeseries

#21962 Trim unncessary code in datetime/np_datetime.c
  pandas/_libs/src/datetime/np_datetime.c
  pandas/_libs/src/datetime/np_datetime.h
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/tslibs/np_datetime.pyx
Labels: Clean, Internals, Timeseries

#21933 ENH: add iso-format support to to_timedelta (#21877)
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/indexes/timedeltas/test_construction.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Enhancement, Timedelta

#21871 API: Add DataFrame.droplevel
  doc/source/api.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/generic.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/series/test_alter_axes.py
Labels: API Design, Indexing, MultiIndex

#19398 Fix invalid relativedelta_kwds
  doc/source/whatsnew/v0.23.0.txt
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Docs, Frequency

#21853 BUG: datetime rolling min/max segfaults when closed=left (#21704)
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/window.pyx
  pandas/tests/test_window.py
Labels: Bug, Numeric, Reshaping

#21982 REF: No need to delegate to index check of whether an int is an int
  pandas/core/indexing.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/indexing/test_iloc.py
Labels: Error Reporting, Indexing

#21985 CLN: Unreachable code, Boolean comparison, duplicate functions
  asv_bench/benchmarks/groupby.py
  pandas/_libs/internals.pyx
  pandas/core/indexes/period.py
Labels: Clean

#21926 Docstrings, de-duplicate EAMixin/DatetimeLikeIndex __new__ code
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/tseries/frequencies.py
Labels: Clean, ExtensionArray

#21160 ENH: Integer NA Extension Array
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/arrays/__init__.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/indexes/base.py
  pandas/core/internals.py
  pandas/core/missing.py
  pandas/core/ops.py
  pandas/core/series.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/category/test_categorical.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/integer/__init__.py
  pandas/tests/extension/integer/test_integer.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_common.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/series/test_constructors.py
Labels: Dtypes, Enhancement, ExtensionArray, Missing-data

#21997 Sparse get dummies perf
  asv_bench/benchmarks/reshape.py
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/reshape/reshape.py
Labels: Performance, Reshaping, Sparse

#20098 DOC: update the GroupBy.apply docstring
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
Labels: Docs, Groupby

#21903 [REF] implement internals as dir
  pandas/core/internals/__init__.py
  pandas/tests/internals/test_internals.py
Labels: Refactor

#22009 CLN: remove F821 flake8 error in test case
  pandas/tests/frame/test_dtypes.py
Labels: Style

#21981 ENH: Implement subtraction for object-dtype Index
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: API Design, Enhancement

#22014 [REF] separate blocks.py out of internals.__init__
  pandas/core/internals/__init__.py
  pandas/core/internals/blocks.py
  pandas/tests/extension/test_external_block.py
Labels: Refactor

#21223 ENH: Merge DataFrame and Series using `on` (GH21220)
  doc/source/merging.rst
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/frame.py
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Enhancement, Reshaping

#22028 Separate out internals.concat, internals.managers
  pandas/_libs/internals.pyx
  pandas/core/internals/__init__.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
Labels: Internals, Refactor

#22013 [CLN] [BLD] Fix many compiler warnings
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/src/datetime/np_datetime.c
  pandas/_libs/src/datetime/np_datetime.h
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/util.pxd
  pandas/io/msgpack/_unpacker.pyx
  pandas/io/sas/sas.pyx
  setup.py
Labels: Build, Clean

#22015 ENH: Number formatting support for excel styles
  doc/source/style.ipynb
  doc/source/whatsnew/v0.24.0.txt
  pandas/io/formats/excel.py
  pandas/tests/io/formats/test_to_excel.py
  pandas/tests/io/test_excel.py
Labels: Enhancement, IO Excel, Style

#20185 DOC: update the to_excel docstring
  pandas/core/generic.py
Labels: Docs

#21928 CLN: Address MulitIndex Test Follow Ups in Issue #21918
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/multi/test_astype.py
  pandas/tests/indexes/multi/test_constructor.py
  pandas/tests/indexes/multi/test_contains.py
  pandas/tests/indexes/multi/test_copy.py
  pandas/tests/indexes/multi/test_equivalence.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/multi/test_get_set.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/multi/test_missing.py
  pandas/tests/indexes/multi/test_operations.py
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexes/multi/test_set_ops.py
  pandas/tests/indexes/multi/test_sorting.py
Labels: MultiIndex, Testing

#22001 CLN: De-privatize core.common funcs, remove unused
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/common.py
  pandas/core/computation/expressions.py
  pandas/core/computation/pytables.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/nanops.py
  pandas/core/ops.py
  pandas/core/panel.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/util.py
  pandas/core/series.py
  pandas/core/sparse/frame.py
  pandas/core/sparse/series.py
  pandas/core/strings.py
  pandas/core/window.py
  pandas/io/formats/console.py
  pandas/io/pytables.py
  pandas/plotting/_converter.py
  pandas/plotting/_core.py
  pandas/plotting/_style.py
  pandas/tests/computation/test_eval.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/test_algos.py
  pandas/tests/test_common.py
  pandas/tests/test_sorting.py
Labels: Clean

#21992 Move FrequencyInferer out of libresolution
  pandas/_libs/algos.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/tseries/frequencies.py
Labels: Clean, Frequency

#21930 DEPR: Series.compress
  doc/source/whatsnew/v0.24.0.txt
  pandas/core/series.py
  pandas/tests/series/test_analytics.py
Labels: Deprecate

#21994 TST: tuple and namedtuple multiindex tests for read_csv
  pandas/tests/io/parser/header.py
Labels: Dtypes, MultiIndex, Testing

#22037 Raised value error on incorrect na_option
  pandas/core/generic.py
  pandas/tests/frame/test_rank.py
  pandas/tests/groupby/test_rank.py
  pandas/tests/series/test_rank.py
Labels: Error Reporting

#21904 BUG: issues with hash-function for Float64HashTable (GH21866)
  doc/source/whatsnew/v0.24.0.txt
  pandas/_libs/src/klib/khash_python.h
  pandas/tests/test_algos.py
Labels: Algos

#22002 CLN: Remove Unneeded BlockManager methods
  pandas/_libs/internals.pyx
  pandas/core/internals/managers.py
  pandas/tests/internals/test_internals.py
Labels: Clean, Internals

#22016 REF: move range-generation functions to EA mixin classes
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
Labels: ExtensionArray, Refactor

#22030 [BLD] [CLN] Close assorted issues - bare exceptions, unused func
  pandas/_libs/skiplist.pxd
  pandas/_libs/skiplist.pyx
  pandas/_libs/src/compat_helper.h
  pandas/core/tools/timedeltas.py
  pandas/io/s3.py
  pandas/tests/frame/test_missing.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_sql.py
  pandas/tests/series/test_missing.py
  pandas/util/_decorators.py
  pandas/util/_print_versions.py
  setup.py
Labels: Clean, Internals
