Repository pandas-dev/pandas, pull requests merged in 2019-09, with the labels that each got.

#28157 CLN: have Timestamp return NotImplemented
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/core/arrays/datetimelike.py
Labels: Timeseries

#28107 BUG: SparseDataFrame op incorrectly casting to float
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/sparse/frame.py
  pandas/tests/sparse/frame/test_frame.py
Labels: Bug, Numeric, Sparse

#28081 REF: separate bloated test
  pandas/core/ops/__init__.py
  pandas/tests/series/test_operators.py
Labels: Refactor, Testing

#28066 REF: do extract_array earlier in series arith/comparison ops
  pandas/core/ops/__init__.py
Labels: ExtensionArray, Reshaping

#28161 BUG: fix+test Timestamp with int array
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/tests/scalar/timestamp/test_arithmetic.py
Labels: Timeseries

#28205 CLN: avoid catching Exception in _choose_path
  pandas/core/groupby/generic.py
Labels: Clean, Groupby

#27959 REF: use dispatch_to_extension_op for bool ops
  pandas/core/ops/__init__.py
Labels: ExtensionArray

#27950 TST: parametrize and de-duplicate arith tests
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Clean, Testing

#28181 ENH: Enable read_csv interpret 'Infinity' as floating point value #10065
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parse_helper.h
  pandas/tests/io/parser/test_common.py
Labels: IO CSV

#28258 Revert #27959
  pandas/core/ops/__init__.py
Labels: CI, Reshaping

#28255 BENCH: Add peakmem benchmarks for rolling
  asv_bench/benchmarks/rolling.py
Labels: Benchmark, Window

#27909 CLN: Catch more specific exceptions in groupby
  pandas/_libs/index.pyx
  pandas/_libs/index_class_helper.pxi.in
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
Labels: Clean, Groupby

#28179 DOC: Add missing public plotting functions to the docs
  doc/source/reference/plotting.rst
  pandas/plotting/_misc.py
Labels: Docs, Visualization

#26872 Add docstring to the insertion method & add empty result note
  doc/source/user_guide/io.rst
Labels: Docs, IO SQL

#28260 re-implement #27959
  pandas/core/ops/__init__.py
Labels: ExtensionArray

#28164 Validate plot backend when setting.
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/config_init.py
  pandas/plotting/_core.py
  pandas/tests/plotting/test_backend.py
  pandas/tests/plotting/test_misc.py
Labels: Visualization

#25437 ENH: added optional caption and label arguments to DataFrame.to_latex()
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/generic.py
  pandas/io/formats/format.py
  pandas/io/formats/latex.py
  pandas/tests/io/formats/test_to_latex.py
Labels: Enhancement, IO LaTeX

#28276 CLN: catch Exception in fewer places, assorted cleanups
  ci/code_checks.sh
  pandas/_libs/lib.pyx
  pandas/core/common.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/ops/__init__.py
  pandas/tests/test_downstream.py
Labels: Clean

#28272 DEV: remove seed isort config
  .pre-commit-config.yaml
Labels: CI

#28259 Fix to_json Memory Tests
  asv_bench/benchmarks/io/json.py
Labels: Benchmark, IO JSON

#28281 DOC: Fix typo in min_rows / max_rows option example
  doc/source/user_guide/options.rst
Labels: Docs

#28267 BUG: Make sure correct values are passed to Rolling._on when axis=1
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_rolling.py
Labels: Bug, Timeseries, Window

#28239 PERF: asv for import
  asv_bench/benchmarks/package.py
  pandas/core/dtypes/dtypes.py
  pandas/util/_test_decorators.py
Labels: Benchmark

#28227 PERF: trim import time ~5%
  ci/code_checks.sh
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/test_html.py
  pandas/util/testing.py
Labels: Performance

#28230 Improved benchmark coverage for reading spreadsheets
  asv_bench/asv.conf.json
  asv_bench/benchmarks/io/excel.py
  environment.yml
  requirements-dev.txt
Labels: Benchmark, IO Excel

#28245 DOC: fix read_excel and ExcelFile engine parameter description (#28231)
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#28290 Fix inconsistent casting to bool
  pandas/core/ops/__init__.py
  pandas/tests/series/test_operators.py
Labels: Dtypes

#27951 BUG: Remove null values before sorting during groupby nunique calculation
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_function.py
Labels: Groupby, Missing-data, Timeseries

#28327 CLN: split_and_operate
  pandas/core/internals/blocks.py
Labels: Clean

#28328 CLN: eval_kwargs
  pandas/core/computation/expressions.py
  pandas/core/ops/__init__.py
Labels: Clean

#28324 Clean groupby error message
  pandas/core/groupby/ops.py
Labels: Docs

#28322 Removed PyString refs from extension modules
  pandas/_libs/src/parse_helper.h
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/tslibs/util.pxd
  pandas/_libs/writers.pyx
Labels: Clean

#28309 CLN: catch Exception less
  pandas/core/apply.py
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/concat.py
  pandas/core/indexes/accessors.py
  pandas/core/series.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_matplotlib/core.py
  setup.py
Labels: Clean

#28320 Added cpp files to build clean
  setup.py
Labels: Build

#28151 PERF: Speed up Spearman calculation
  asv_bench/benchmarks/stat_ops.py
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/algos.pyx
Labels: Performance

#28286 BUG: datetime64 - Timestamp incorrectly raising TypeError
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/tests/scalar/timestamp/test_arithmetic.py
Labels: Timeseries

#28310 CLN: catch specific Exceptions in _config
  pandas/_config/display.py
  pandas/_config/localization.py
  pandas/tests/io/formats/test_console.py
Labels: Clean

#28198 CLN: Catch more specific exception in groupby.ops
  pandas/core/groupby/ops.py
Labels: Clean, Groupby

#28340 Pandas.series.astype docstring PR02
  pandas/core/generic.py
Labels: Docs

#28268 BUG: Timestamp+int should raise NullFrequencyError, not ValueError
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/errors/__init__.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/tslibs/test_api.py
Labels: Bug, Frequency

#28346 CLN: handle bare exceptions im timedeltas, timestamps, reduction
  pandas/_libs/reduction.pyx
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Clean

#28342 PERF: lazify type-check import
  pandas/io/formats/format.py
Labels: Performance

#28344 CLN: avoid bare except in libfrequencies
  pandas/_libs/tslibs/frequencies.pyx
Labels: Clean, Frequency

#28345 CLN: avoid bare except in tslib and tslibs.parsing
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/parsing.pyx
Labels: Clean

#28349 CLN: Exception catching in io
  pandas/core/indexes/accessors.py
  pandas/core/indexes/frozen.py
  pandas/io/common.py
  pandas/io/parsers.py
  pandas/io/pickle.py
Labels: Clean

#28352 CLN: raise ValueError instead of Exception
  pandas/core/groupby/generic.py
Labels: Clean

#27992 BUG/TST: fix and test for timezone drop in GroupBy.shift/bfill/ffill
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby, Timezones

#26316 [ENH] Use default EA repr for IntervalArray
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/arrays/interval/test_interval.py
Labels: ExtensionArray, Interval

#28361 CLN: Exception catching
  pandas/_libs/testing.pyx
  pandas/core/construction.py
  pandas/core/indexing.py
Labels: Clean, Error Reporting

#28364 BUG: same behavior for Series/Index vs ndarray/list in Series logical ops
  pandas/core/ops/__init__.py
  pandas/tests/series/test_operators.py
Labels: Clean

#28343 CLN: fix bare excepts on close
  pandas/_libs/parsers.pyx
  pandas/io/common.py
  pandas/io/json/_json.py
  pandas/io/parquet.py
Labels: Clean, Error Reporting

#28336 GH28301 check for non-unique index in stack_multi_columns
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_reshape.py
Labels: Bug, Groupby, MultiIndex

#28354 GH28337: Period index doesn't handle reindexing with a non-period index
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/reshape/test_pivot.py
Labels: Indexing, Period

#28351 CLN: catch stricter in json
  pandas/io/json/_json.py
Labels: Clean, IO JSON

#25103 Fix #25099 set na_rep values before converting to string to prevent data truncation
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/writers.pyx
  pandas/core/internals/blocks.py
  pandas/tests/io/formats/test_to_csv.py
Labels: Bug, ExtensionArray, IO CSV, Missing-data, Output-Formatting

#28370 CLN: avoid catching Exception in generic
  pandas/core/generic.py
Labels: Clean

#28020 CLN: timeseries in plotting clean up
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/plotting/test_converter.py
Labels: Clean, Visualization

#27465 CLN: remove unused parts of skiplist (most of it)
  pandas/_libs/skiplist.pxd
  pandas/_libs/skiplist.pyx
Labels: Clean

#28316 DOC: Improve compiler installation instructions
  doc/source/development/contributing.rst
Labels: Docs

#28379 CLN: small ops cleanup
  pandas/core/ops/__init__.py
  pandas/core/ops/missing.py
Labels: Clean

#28338 DOC: Add pyjanitor to ecosystem.rst
  doc/source/ecosystem.rst
Labels: Docs

#28357 Change conda channel order for Windows builds
  ci/deps/azure-windows-36.yaml
  pandas/tests/io/test_parquet.py
Labels: CI, Windows

#28226 Don't fail when plotting Series/DataFrame with no row
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#27928 Assignment of column via .loc for numpy non-ns datetimes
  doc/source/whatsnew/v0.25.2.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/indexing/test_loc.py
Labels: Indexing

#28413 REF: prepare Series arith op to be refactored to array op
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
Labels: Clean

#28405 Revert "TMP: pin openssl for doc build"
  environment.yml
  scripts/generate_pip_deps_from_conda.py
Labels: CI

#28374 BLD: Add pyproject.toml
  .gitignore
  MANIFEST.in
  Makefile
  README.md
  ci/incremental/build.cmd
  ci/setup_env.sh
  doc/source/development/contributing.rst
  doc/source/whatsnew/v1.0.0.rst
  pyproject.toml
  setup.py
Labels: Build

#28387 CLN: Exception in core.dtypes
  pandas/core/arrays/sparse.py
  pandas/core/dtypes/common.py
  pandas/io/pytables.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/io/parser/test_dtypes.py
Labels: Clean

#28445 DOC: fix the editable install command
  doc/source/development/contributing.rst
Labels: Docs

#28449 DOC: fix docstring of core.comon.pipe (PR02)
  pandas/core/common.py
Labels: Docs, Style

#28450 TST: Fix sqlite3 transactions test
  pandas/tests/io/test_sql.py
Labels: Testing

#28052 Make DataFrame.to_string output full content by default
  doc/source/user_guide/options.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/config_init.py
  pandas/core/frame.py
  pandas/io/clipboards.py
  pandas/io/formats/html.py
  pandas/tests/config/test_config.py
  pandas/tests/io/formats/test_format.py
Labels: API Design, Output-Formatting

#28288 DOC: Fix PR06 errors in Series docstrings (#28253)
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/plotting/_core.py
Labels: Docs

#28217 DOC: Update index parameter in pandas to_parquet
  pandas/core/frame.py
  pandas/io/parquet.py
Labels: Clean, IO Parquet

#28442 CLN: remove merge-pr script, clean Exception in tm, doc
  doc/source/user_guide/io.rst
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/test_downstream.py
  pandas/util/testing.py
  scripts/merge-pr.py
Labels: Clean, Error Reporting

#28183 BUG: to_html() with formatters=<list> and max_cols fixed
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/data/html/truncate_formatter.html
  pandas/tests/io/formats/test_to_html.py
Labels: Bug, IO HTML

#28432 BLD: clean-up sdist creation
  MANIFEST.in
  doc/source/whatsnew/v1.0.0.rst
  setup.py
Labels: Build

#28433 CLN: Exception in nanops
  pandas/core/nanops.py
  pandas/tests/test_nanops.py
Labels: Clean

#28434 CLN: Exception in generic, series
  pandas/core/generic.py
  pandas/core/series.py
Labels: Clean

#28443 CLN: catch less in Block._astype
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#28027 REF: standardize usage in DataFrame vs SparseDataFrame ops
  pandas/core/frame.py
  pandas/core/ops/__init__.py
  pandas/core/sparse/frame.py
Labels: Sparse

#28444 TST: Fix makeObjectSeries data as object type
  pandas/tests/series/conftest.py
  pandas/util/testing.py
Labels: Testing

#28010 BUG: Avoid duplicating entire exploded column when joining back with origi…
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_explode.py
  pandas/tests/series/test_explode.py
Labels: API Design, Bug, Reshaping

#28484 REF: raise scalar_data_error to make mypy happy
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
Labels: Typing

#28478 TST: Parametrize and cleanup Exception
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexing/common.py
  pandas/tests/series/test_api.py
  pandas/tests/test_expressions.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Clean

#28119 BUG: Fixed PandasArray.__setitem__ with str
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/numpy_.py
  pandas/tests/arrays/test_numpy.py
Labels: Bug, ExtensionArray

#27838 Parametrize JSON tests
  pandas/tests/io/json/conftest.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Testing

#28347 CLN/BUG: array_equivalent on nested objects
  pandas/_libs/testing.pyx
  pandas/core/dtypes/missing.py
  pandas/tests/dtypes/test_missing.py
Labels: CI, Clean

#28475 BUG: Raise when casting infinity to int
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/numeric.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/test_numeric.py
Labels: Error Reporting

#28438 BUG: Don't cast categorical nan to int
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/indexes/base.py
  pandas/tests/extension/test_categorical.py
Labels: Bug, Categorical, Missing-data

#28014 WEB: Adding new pandas website
  ci/code_checks.sh
  environment.yml
  requirements-dev.txt
  web/README.md
  web/pandas/_templates/layout.html
  web/pandas/blog.html
  web/pandas/community/about.md
  web/pandas/community/citing.md
  web/pandas/community/coc.md
  web/pandas/community/ecosystem.md
  web/pandas/community/roadmap.md
  web/pandas/community/team.md
  web/pandas/config.yml
  web/pandas/donate.md
  web/pandas/index.html
  web/pandas/install.md
  web/pandas/static/css/pandas.css
  web/pandas/static/img/install/anaconda_prompt.png
  web/pandas/static/img/install/jupyterlab_home.png
  web/pandas/static/img/install/pandas_import_and_version.png
  web/pandas/static/img/pandas.svg
  web/pandas/static/img/partners/anaconda.svg
  web/pandas/static/img/partners/numfocus.svg
  web/pandas/static/img/partners/r_studio.svg
  web/pandas/static/img/partners/tidelift.svg
  web/pandas/static/img/partners/two_sigma.svg
  web/pandas/static/img/partners/ursa_labs.svg
  web/pandas/static/img/pydata_book.gif
  web/pandas/try.md
  web/pandas_web.py
Labels: Web

#28494 DOC: add example of pyarrow usage favored over the deprecated to_msgpack
  pandas/core/generic.py
  pandas/io/packers.py
Labels: Docs, IO Msgpack

#28130 Add Indent Support in to_json
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/src/ujson/lib/ultrajson.h
  pandas/_libs/src/ujson/lib/ultrajsonenc.c
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_typing.py
  pandas/core/generic.py
  pandas/io/json/_json.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON

#28502 Cleaned up JSON test with ambiguous DTA usage
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Testing

#28498 TST: added a test case for special character in file name
  pandas/tests/io/parser/test_common.py
Labels: Testing

#28497 WEB: Deployment of development website with the docs
  README.md
  azure-pipelines.yml
  doc/source/whatsnew/v0.25.0.rst
  web/pandas/config.yml
  web/pandas/donate.md
  web/pandas/index.html
  web/pandas/install.md
Labels: Web

#28482 CLN: Clean up of CI scripts
  ci/azure/posix.yml
  ci/print_skipped.py
  ci/run_tests.sh
Labels: CI, Clean

#28326 BUG: Fix FastParquetImpl.write for non-existent file
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_gcs.py
Labels: Data IO, IO Parquet

#28529 WEB: Fix deployment of the website
  azure-pipelines.yml
Labels: CI, Web

#27538 COMPAT: remove Categorical pickle compat with Pandas < 0.16
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/io/data/categorical.0.25.0.pickle
  pandas/tests/io/data/categorical_0_14_1.pickle
  pandas/tests/io/data/categorical_0_15_2.pickle
  pandas/tests/io/test_common.py
  pandas/tests/io/test_pickle.py
Labels: Categorical, Compat, Data IO

#28530 BUG: wrong exception raised by Week+Day
  doc/source/whatsnew/v1.0.0.rst
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/frequencies.py
  pandas/tseries/offsets.py
Labels: Error Reporting

#28543 WEB/CI: Fixing target path of the web build
  azure-pipelines.yml
Labels: CI, Web

#28213 BUG: Fix issue with apply on empty DataFrame
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/apply.py
  pandas/tests/frame/test_apply.py
Labels: Apply

#26456 BUG-26214 fix colors parameter in DataFrame.boxplot
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/boxplot.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Bug, Visualization

#28544 CLN: Exception and BaseException in test_nanops
  pandas/tests/test_nanops.py
Labels: Testing

#28415 Added version policy
  doc/source/development/index.rst
  doc/source/development/policies.rst
  doc/source/whatsnew/v1.0.0.rst
Labels: Admin

#28505 BUG/CLN: DatetimeTZDtype.construct_from_string Exception
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Error Reporting, Timezones

#28513 CLN: dont catch Exception when calling maybe_convert_numeric
  pandas/core/dtypes/cast.py
  pandas/core/tools/numeric.py
  pandas/io/parsers.py
  pandas/tests/dtypes/test_inference.py
Labels: Clean

#28508 BUG: fix array_equivalent with mismatched tzawareness
  pandas/_libs/lib.pyx
  pandas/core/dtypes/missing.py
  pandas/core/indexes/base.py
  pandas/tests/dtypes/test_missing.py
Labels: Timezones

#28542 ENH: Add dta 119 reading to StataReader
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/data/stata1_119.dta.gz
  pandas/tests/io/test_stata.py
Labels: IO Stata

#28447 [PERF] Vectorize select_dtypes
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
Labels: Dtypes, Performance

#28524 COMPAT: ensure no warnings on tab completion with Jedi 0.15
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/series.py
Labels: Output-Formatting

#28539 Pandas.io.formats.style.Styler docstring PR02
  pandas/io/formats/style.py
Labels: Docs

#28493 TST: parametrize test_expressions
  pandas/tests/io/excel/test_xlsxwriter.py
  pandas/tests/test_expressions.py
Labels: Testing

#28537 REF: Parametrize value_counts tests
  pandas/tests/groupby/test_value_counts.py
Labels: Testing

#28453 Annotate DataFrame Part 2 (Rendering Methods)
  pandas/core/frame.py
  pandas/io/formats/format.py
Labels: Typing

#28510 Re-implemented parametrization of test_frame_from_json_to_json
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Testing

#28550 Backport PR #28524: COMPAT: ensure no warnings on tab completion with Jedi 0.15
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/series.py
Labels: Output-Formatting

#28566 BENCH: Add rolling apply benchmarks
  asv_bench/benchmarks/rolling.py
Labels: Benchmark, Window

#28563 CLN: Assorted cleanups
  pandas/core/algorithms.py
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#28553 TST/CLN: parametrize and clean test_expressions, test_nanops
  pandas/tests/test_expressions.py
  pandas/tests/test_nanops.py
Labels: Testing

#28431 REF: implement arithmetic, comparison, logical ops on arrays
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
Labels: Clean, Internals

#28579 Fix typo
  pandas/core/frame.py
Labels: Docs

#28172 BUG: fix custom xticks in bar() plotting function
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_series.py
Labels: Bug, Visualization

#28586 Fix typo in class DataFrame
  pandas/core/frame.py
Labels: Docs

#28614 CI: troubleshoot s3fs failures
  ci/deps/travis-36-cov.yaml
  ci/deps/travis-36-slow.yaml
  ci/deps/travis-37.yaml
  pandas/tests/groupby/test_categorical.py
Labels: CI

#28241 Datetime mergeasof tolerance
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Timedelta

#28582 WEB: Restructuring pages and navigation, styling and new footer
  web/pandas/_templates/layout.html
  web/pandas/about/citing.md
  web/pandas/about/index.html
  web/pandas/about/roadmap.md
  web/pandas/about/sponsors.md
  web/pandas/about/team.md
  web/pandas/community/blog.html
  web/pandas/community/coc.md
  web/pandas/community/ecosystem.md
  web/pandas/config.yml
  web/pandas/contribute.md
  web/pandas/donate.md
  web/pandas/getting_started.md
  web/pandas/index.html
  web/pandas/static/css/pandas.css
Labels: Web

#28601 OPS: Remove mask_cmp_op fallback behavior
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/ops/__init__.py
  pandas/tests/frame/test_arithmetic.py
Labels: API Design

#28600 REF/TST: Corner cases for op(DataFrame, Series)
  pandas/core/ops/__init__.py
  pandas/tests/frame/test_arithmetic.py
Labels: Compat, Testing

#28590 CLN: unify __finalize__ treatment for Series ops
  pandas/core/ops/__init__.py
Labels: Clean

#28532 CLN+TST: Catch specific exception in equals
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/timedeltas/test_ops.py
Labels: Clean

#28624 REF: separate out dispatch-centric ops functions
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
  pandas/core/ops/dispatch.py
Labels: Clean

#28567 DOC: update fixing unknown parameters errors (error code PR02)
  pandas/plotting/_core.py
Labels: Docs, Style

#28648 CLN: Exception in nanops
  pandas/core/nanops.py
Labels: Clean

#28646 CLN: remove unused categories/ordered handling in astype
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/tests/series/test_dtypes.py
Labels: Clean, Dtypes

#28642 CLN: more Exceptions
  pandas/core/apply.py
  pandas/core/indexes/base.py
  pandas/io/sql.py
  pandas/io/stata.py
Labels: Clean

#28516 CLN: clean-up internal sparse imports + restructure sparse submodule
  doc/source/whatsnew/v1.0.0.rst
  pandas/__init__.py
  pandas/core/arrays/sparse/__init__.py
  pandas/core/arrays/sparse/accessor.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/sparse/test_combine_concat.py
  pandas/tests/arrays/sparse/test_dtype.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/sparse/__init__.py
Labels: Clean, Sparse

#28650 CLN: Exception catching in expressions
  pandas/core/computation/expressions.py
Labels: Clean

#28626 REF: Assert json roundtrip equal
  pandas/tests/io/json/test_pandas.py
Labels: Testing

#28053 DOC: fix punctuation in Timestamp/Timedelta docstrings
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#28075 DOC: redirect from_csv search
  doc/redirects.csv
Labels: Docs

#28655 DOC: Fixed PR08 docstring errors in pandas.DataFrame
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/plotting/_core.py
Labels: Docs, Style
