Repository pandas-dev/pandas, pull requests merged in 2019-05, with the labels that each got.

#26015 Improve dictionary map performance on category series, fixes #23785
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/base.py
Labels: Categorical, Performance

#26261 CLN: clean more uses of python2-style super()
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/io/msgpack/__init__.py
  pandas/tests/arrays/test_array.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/test_query_eval.py
  pandas/tseries/holiday.py
Labels: 2/3 Compat

#26255 DOC: Test doctests in pandas/core/groupby/groupby.py
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Testing

#26242 ENH: clearer error msg for unequal categoricals in merge_asof (GH#26136)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Categorical, Error Reporting, Reshaping

#26252 Fix type annotation in pandas.compat
  mypy.ini
  pandas/compat/__init__.py
Labels: Typing

#26266 Clean up Py2 Influence in move.c
  pandas/util/move.c
Labels: Clean

#26240 TST: Test pd.Grouper base floating point error (#25161)
  pandas/tests/resample/test_datetime_index.py
Labels: Groupby, Testing, Timeseries

#26260 CLN: Removing dead code in plotting and minor refactoring
  pandas/plotting/_core.py
Labels: Clean, Visualization

#26268 Canonicalize CRAN links
  doc/source/getting_started/comparison/comparison_with_r.rst
  doc/source/user_guide/visualization.rst
  doc/source/whatsnew/v0.16.0.rst
  pandas/io/sas/sas.pyx
  pandas/io/sas/sas7bdat.py
Labels: Docs

#26267 DOC: Add regex example in str.split docstring
  pandas/core/strings.py
Labels: Docs

#26270 Python2 String Handling Cleanup in parsers.pyx
  pandas/_libs/parsers.pyx
Labels: 2/3 Compat, Clean, IO CSV

#26273 DOC, CI: Correct wide_to_long docstring and add reshape/melt to CI
  ci/code_checks.sh
  pandas/core/reshape/melt.py
Labels: Docs, Style

#26279 CLN: Remove compat.re_type
  pandas/compat/__init__.py
  pandas/core/dtypes/inference.py
  pandas/tests/test_compat.py
Labels: 2/3 Compat, Clean

#26281 CLN: remove uses of compat.lrange, part I
  pandas/core/generic.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/internals/construction.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/pivot.py
  pandas/io/excel/_util.py
  pandas/io/html.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_nth.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/test_multilevel.py
  pandas/util/testing.py
Labels: 2/3 Compat, Clean

#26264 Remove usage of register keyword in Extension Modules
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
Labels: Clean

#26286 Update broken link to contributing.rst in contributing.md
  .github/CONTRIBUTING.md
  doc/source/development/contributing.rst
Labels: Docs

#25009 BUG-24212 fix when other_index has incompatible dtype
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Regression, Reshaping

#26152 Fix Bug with NA value in Grouping for Groupby.nth
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_nth.py
Labels: Groupby

#25328 DOC: Improvement docstring of DataFrame.rank()
  pandas/core/generic.py
Labels: Docs

#26297 Fix type annotations in pandas.core.base
  mypy.ini
  pandas/core/base.py
Labels: Typing

#26289 CLN: remove compat.lrange, part II
  pandas/io/parsers.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_pytables.py
  pandas/tests/io/test_sql.py
  pandas/tests/series/test_repr.py
  pandas/tests/test_algos.py
Labels: 2/3 Compat, Clean

#25462 Remove return values for asserts
  pandas/tests/arrays/test_integer.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tools/test_numeric.py
  pandas/util/testing.py
Labels: Clean, Testing

#25696 CLN: handle EAs and fast path (no bounds checking) in safe_sort
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/algorithms.py
  pandas/core/sorting.py
  pandas/tests/test_algos.py
  pandas/tests/test_sorting.py
Labels: Algos, ExtensionArray

#26220 PERF: added no exception versions of '_string_to_dts' and 'parse_iso_8601_datetime' functions
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.c
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.h
Labels: Performance, Timeseries

#25466 DOC: Fix encoding of docstring validation for Windows
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs, Windows

#26300 Add type annotation to config_init
  mypy.ini
  pandas/core/config_init.py
Labels: Typing

#26250 DOC removed unnecessary use of parameter in example rename function call
  pandas/core/frame.py
Labels: Docs

#26257 [BUG] Add is_coerce argument to func array_to_datetime_object (GH26122)
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslib.pyx
  pandas/tests/indexes/datetimes/test_tools.py
Labels: Bug, Timeseries

#26170 BUG: read_json converted date strings with Z to UTC
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslib.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Timezones

#26287 Remove Panel References
  pandas/compat/numpy/function.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/ops.py
  pandas/core/panel.py
  pandas/core/reshape/concat.py
  pandas/core/series.py
  pandas/io/pytables.py
  pandas/util/_validators.py
Labels: Clean, Panel

#25990 ENH: added new cache_dates parameter for read_csv func
  asv_bench/benchmarks/io/csv.py
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/parsers.py
Labels: Enhancement, IO CSV, Performance, Timeseries

#26243 ENH: Poisson exponential window
  doc/source/user_guide/computation.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/window.py
  pandas/tests/test_window.py
Labels: Enhancement, Window

#26308 Removed to_panel references
  doc/source/reference/frame.rst
  pandas/core/generic.py
  pandas/core/reshape/concat.py
Labels: Clean, Panel

#26295 Fix type annotations in pandas.core.computation
  mypy.ini
  pandas/core/computation/expr.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
Labels: Typing

#26234 DOC: Fix validation error type `RT01` and check in CI (#25356)
  ci/code_checks.sh
  pandas/core/accessor.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/interval.py
  pandas/core/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/inference.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/io/excel/_base.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/tseries/offsets.py
Labels: Docs, Style

#26311 CLN;: remove compat.lzip
  pandas/compat/__init__.py
  pandas/core/arrays/categorical.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/multi.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/merge.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/parsers.py
  pandas/io/stata.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/conftest.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_equivalence.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_sorted.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/series/test_api.py
  pandas/tests/test_compat.py
  pandas/tests/test_multilevel.py
  pandas/util/testing.py
Labels: 2/3 Compat, Clean

#26313 DOC: Replace .values with .to_numpy() in enhancingperf
  doc/source/user_guide/enhancingperf.rst
Labels: Docs

#26301 DOC Fix inconsistencies
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/sparse.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/nanops.py
  pandas/core/ops.py
  pandas/core/strings.py
  pandas/io/excel/_util.py
  pandas/io/formats/format.py
  pandas/io/json/table_schema.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/plotting/_misc.py
Labels: Docs

#26317 Change doc reference to `read_csv` to `read_excel`
  pandas/io/excel/_base.py
Labels: Docs

#26319 CLN: remove compat.lrange, part 3
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_combine_concat.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_missing.py
  pandas/tests/frame/test_mutate_columns.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_replace.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/frame/test_sorting.py
  pandas/tests/frame/test_timezones.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/series/test_apply.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_timeseries.py
  pandas/tests/series/test_timezones.py
Labels: 2/3 Compat, Clean

#26324 BUG: fix numpy min/max compat with index (#26125)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/base.py
  pandas/core/indexes/range.py
  pandas/tests/reductions/test_reductions.py
Labels: Compat

#26306 DOC: Improve links and fix issues on resample documentation page
  pandas/core/generic.py
Labels: Docs, Frequency

#26323 CLN: remove empty parenteses on class creation
  ci/code_checks.sh
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_apply.py
  pandas/tests/frame/test_asof.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_combine_concat.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_missing.py
  pandas/tests/frame/test_mutate_columns.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/test_gcs.py
  pandas/tests/series/test_apply.py
  pandas/tests/series/test_asof.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_datetime_values.py
  pandas/tests/series/test_io.py
  pandas/tests/series/test_missing.py
  pandas/util/_test_decorators.py
Labels: 2/3 Compat

#26322 CLN: remove compat.lmap
  pandas/compat/__init__.py
  pandas/core/computation/expr.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/core/sparse/frame.py
  pandas/core/sparse/scipy_sparse.py
  pandas/io/html.py
  pandas/io/stata.py
  pandas/plotting/_misc.py
  pandas/plotting/_style.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/indexes/period/test_construction.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/io/parser/test_converters.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/test_compat.py
  pandas/util/testing.py
Labels: 2/3 Compat

#26330 Update python_requires to 3.5+
  setup.py
Labels: Build

#26352 BLD: Work around Azure Windows 3.7 failure
  ci/deps/azure-windows-37.yaml
  ci/incremental/setup_conda_environment.cmd
Labels: Build, Windows

#26343 BUG: constructing a DataFrame using range doesn't work
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, DataFrame

#26337 CLN: Remove python2-style longs in regexes
  pandas/tests/indexing/multiindex/test_getitem.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_loc.py
  pandas/tests/series/test_analytics.py
Labels: 2/3 Compat, Clean

#26334 PERF: regression fixup for timestamp.TimestampConstruction.time_parse_iso8601_tz benchmark
  pandas/_libs/tslibs/conversion.pyx
Labels: Performance, Timeseries

#26331 Remove _DtypeOpsMixin
  pandas/core/dtypes/base.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/multi.py
  pandas/core/internals/blocks.py
Labels: Clean, Refactor

#26341 [WIP} Fix type annotation in pandas/core/api
  mypy.ini
  pandas/core/arrays/integer.py
Labels: Typing

#26339 Remove Python 2 in CLASSIFIERS
  setup.py
Labels: Build, Clean

#26357 CLN: Remove run_with_env.cmd
  ci/run_with_env.cmd
Labels: Build, Clean, Windows

#26358 BLD: Correct gcsfs install on Azure
  ci/incremental/setup_conda_environment.cmd
Labels: CI, Windows

#26332 Remove Panel References from Tests
  pandas/tests/groupby/test_groupby.py
  pandas/tests/io/test_excel.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/sparse/frame/test_frame.py
Labels: Clean, Panel

#26292 [BUG] Adding offset with nonzero month to DatetimeIndex (GH26258)
  doc/source/whatsnew/v0.25.0.rst
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tseries/offsets.py
Labels: Bug, Frequency, Timeseries

#25754 PERF: cythonizing _concat_date_cols; conversion to float without exceptions in _does_string_look_like_datetime
  asv_bench/benchmarks/io/csv.py
  asv_bench/benchmarks/io/parsers.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/io/parsers.py
  pandas/tests/io/parser/test_parse_dates.py
  setup.py
Labels: Missing-data, Performance, Timeseries

#26369 Fix broken link to contributing guide website
  .github/CONTRIBUTING.md
Labels: Docs

#26373 Compat with numpy dev argsort (radix sort added)
  pandas/compat/numpy/function.py
  pandas/tests/groupby/test_groupby.py
Labels: CI, Compat

#26371 Fix type annotation for pandas.core.indexes.base
  mypy.ini
  pandas/core/indexes/base.py
Labels: Typing

#26375 Remove extraneous brackets
  pandas/io/excel/_base.py
Labels: Docs

#25682 API: DataFrame.sparse accessor
  doc/source/reference/frame.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/sparse.py
  pandas/core/frame.py
  pandas/core/sparse/frame.py
  pandas/tests/arrays/sparse/test_accessor.py
  pandas/tests/arrays/sparse/test_array.py
Labels: Sparse

#25265 BUG: support casting from bool array to EA Integer dtype
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/integer.py
  pandas/core/series.py
  pandas/tests/arrays/test_integer.py
Labels: Bug, ExtensionArray, Missing-data

#26362 BUG: DataFrame.join on tz aware index and column
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
Labels: Bug, Timezones

#26386 CLN: Cleanup code in parsers.pyx
  pandas/_libs/parsers.pyx
Labels: Clean, IO CSV, Internals

#26360 New benchmarks for parsing dates with dayfirst=True and format='%d-%m-%Y'
  asv_bench/benchmarks/io/csv.py
Labels: IO CSV, Performance, Timeseries

#26162 BUG: groupby ffill adds labels as extra column (#21521)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_transform.py
Labels: Groupby, Missing-data

#26396 CLN: remove compat.lrange
  pandas/compat/__init__.py
  pandas/plotting/_converter.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/plotting/_style.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/frame/test_duplicates.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/multi/test_constructor.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexes/multi/test_equivalence.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/period/test_construction.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/period/test_tools.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexing/common.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_ix.py
  pandas/tests/indexing/multiindex/test_xs.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_ix.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_iloc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_loc.py
  pandas/tests/series/indexing/test_numeric.py
  pandas/tests/series/test_alter_axes.py
  pandas/tests/series/test_analytics.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/test_compat.py
  scripts/find_commits_touching_func.py
Labels: 2/3 Compat, Clean

#26384 Remove Deprecated Azure CI Step
  ci/azure/windows.yml
  ci/incremental/setup_conda_environment.cmd
Labels: CI, Windows

#26402 DOC: Test doctests in pandas/core/tools/datetimes.py
  ci/code_checks.sh
  pandas/core/tools/datetimes.py
Labels: Docs

#26228 Fix .transform crash when SeriesGroupBy is empty (#26208)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_grouping.py
Labels: Bug, Groupby

#26413 Added conda update step and re-added gcsfs
  ci/azure/windows.yml
  ci/deps/azure-windows-37.yaml
Labels: CI

#26415 CLN: remove __unicode__ from pandas.core.dtypes
  pandas/core/dtypes/dtypes.py
Labels: 2/3 Compat

#26416 CLN: remove __unicode__ from pyx, etc. files
  pandas/_libs/tslibs/period.pyx
Labels: 2/3 Compat

#26398 Fix type annotations in pandas.core.resample
  mypy.ini
  pandas/core/groupby/grouper.py
  pandas/core/resample.py
Labels: Resample, Typing

#26377 Fix type annotations in pandas.core.ops
  mypy.ini
  pandas/core/ops.py
Labels: Typing

#26355 BUG: Fix MultiIndex DataFrame to_csv() segfault
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/frame/test_to_csv.py
Labels: IO CSV, MultiIndex

#26405 DEPR: deprecate Series/DataFrame.compound
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/generic.py
  pandas/tests/series/test_analytics.py
Labels: Deprecate

#26423 DOC: remove usage of lrange in docs
  doc/source/whatsnew/v0.11.0.rst
  doc/source/whatsnew/v0.12.0.rst
Labels: Docs

#26103 CI/DOC: fix clipboard on travis
  .travis.yml
  ci/setup_env.sh
Labels: CI, Docs

#26434 CLN: Remove type from (class|type) in regexes
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/io/test_packers.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/indexing/test_numeric.py
  pandas/tests/series/test_analytics.py
  pandas/tests/tslibs/test_timedeltas.py
Labels: 2/3 Compat

#26435 CLN: remove unused code check for pytest.raises
  ci/code_checks.sh
Labels: Clean

#26433 CLN: Remove unicode u string prefix in regexes
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/msgpack/test_pack.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/util/test_assert_index_equal.py
  pandas/tests/util/test_assert_series_equal.py
Labels: 2/3 Compat

#26432 CLN: remove __unicode__ from code base
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse.py
  pandas/core/base.py
  pandas/core/computation/expr.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/frozen.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/sparse/series.py
  pandas/core/window.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/indexes/datetimes/test_formats.py
  pandas/tests/indexes/period/test_formats.py
  pandas/tests/indexes/timedeltas/test_formats.py
  pandas/tests/series/test_repr.py
Labels: 2/3 Compat

#26425 DOC: ecosystem.rst: Koalas
  doc/source/ecosystem.rst
Labels: Docs

#26381 BUG: error calculating BusinessHourMixin.apply for long business hour per day
  doc/source/whatsnew/v0.25.0.rst
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Bug, Timeseries

#26372 Misc Type Annotation fixes
  doc/source/whatsnew/v0.25.0.rst
  mypy.ini
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/reshape.py
  pandas/core/util/hashing.py
  pandas/core/window.py
  pandas/io/pytables.py
  pandas/util/testing.py
Labels: Typing

#26442 TST/CLN: remove try/except from test_column_contains_typeerror
  pandas/tests/frame/test_api.py
Labels: Testing

#26440 ERR: User-facing AssertionError in DataFrame Constructor
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/io/json/test_pandas.py
Labels: DataFrame, Testing

#26441 TST: Iterrows making incorrect assumptions about datetime
  pandas/tests/frame/test_api.py
Labels: Dtypes, Testing

#26422 Correction (and clarification) to EWMA doc
  doc/source/user_guide/computation.rst
Labels: Docs, Window

#26359 BUG: groupby.agg returns incorrect results for uint64 cols (#26310)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/dtypes/common.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Dtypes, Groupby

#26431 ERR: FutureWarning difficult to identify source
  pandas/core/indexes/datetimes.py
  pandas/tests/frame/test_alter_axes.py
Labels: Error Reporting

#26445 Clean Up src/parsers
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/io.h
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
Labels: Clean, Data IO

#26447 CLN: remove __bytes__
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/base.py
  pandas/core/dtypes/dtypes.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_frozen.py
  pandas/tests/series/test_repr.py
  pandas/tests/test_base.py
Labels: 2/3 Compat, Clean

#25964 BUG: Fix #25959 - Don't call .array in DatetimeLikeArrayMixin's map
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/series.py
  pandas/tests/series/test_apply.py
Labels: Bug, Timezones

#26438 DEPR: Change .ix DeprecationWarning -> FutureWarning
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexing/common.py
  pandas/tests/indexing/multiindex/test_ix.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_callable.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_ix.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/test_multilevel.py
Labels: Deprecate, Indexing

#26417 BUG: bugfix 26390 assigning PandasArray to DataFrame error
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/test_block_internals.py
Labels: Indexing, Internals

#26426 BUG: fix calling local references with keyword arguments in query
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/computation/expr.py
  pandas/tests/computation/test_eval.py
Labels: Algos

#26451 TST/DEPR: remove .ix from tests\indexing\multiindex\test_loc.py
  pandas/tests/indexing/multiindex/test_ix.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Deprecate, Index

#26374 BUG: ngroups and len(groups) do not equal when grouping with a list of Grouper and column label (GH26326)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby

#26298 BUG-20629 allow .at accessor with CategoricalIndex
  doc/source/whatsnew/v0.25.0.rst
  pandas/_typing.py
  pandas/core/frame.py
  pandas/core/indexes/category.py
  pandas/tests/indexing/test_categorical.py
Labels: Bug, Categorical, Indexing

#26356 BUG: Exception when frame constructed from dict of iterators
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/common.py
  pandas/core/internals/construction.py
  pandas/core/series.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, Series

#26466 Add defensive check for argument errors keyword in to_numeric
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/tools/numeric.py
  pandas/tests/tools/test_numeric.py
Labels: Error Reporting, Numeric

#26467 DOC: fix example with Timestamp/integer addition
  doc/source/user_guide/indexing.rst
Labels: Docs

#26465 DOC: #25723 passing kwargs to excel document engine
  doc/source/user_guide/io.rst
Labels: Docs, IO Excel

#26421 DEPR: deprecate SparseArray.values
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/reduction.pyx
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/core/arrays/sparse.py
  pandas/core/internals/managers.py
  pandas/core/ops.py
  pandas/core/sparse/frame.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/sparse/series/test_series.py
  pandas/util/testing.py
  setup.cfg
Labels: Deprecate

#23538 ENH - Index set operation modifications to address issue #23525
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/conftest.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/series/test_combine_concat.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_operators.py
Labels: API Design, Dtypes, Indexing, Period

#26484 DOC/CLN: wil -> will
  pandas/core/generic.py
Labels: Clean, Docs

#26489 Fixed typo mutiplication -> multiplication
  pandas/core/frame.py
Labels: Docs

#26499 DOC: fix SyntaxError in doc build on Windows
  doc/source/conf.py
Labels: Docs, Windows

#26496 DOC: Highlighted role of index alignment in DataFrame.dot(other) (#26…
  pandas/core/frame.py
Labels: Docs

#26486 DOC/CLN: Change API reference section title
  doc/source/reference/indexing.rst
Labels: Docs

#26505 CLN: Remove StringMixin from PandasObject
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/frozen.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/panel.py
  pandas/core/series.py
  pandas/core/sparse/series.py
  pandas/core/window.py
Labels: Clean, Internals

#26404 Fix type annotations in pandas.core.indexes.datetimes
  mypy.ini
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
Labels: Typing

#26483 Better error message for DataFrame.hist() without numerical columns (…
  pandas/plotting/_core.py
  pandas/tests/plotting/test_hist_method.py
Labels: Dtypes, Error Reporting, Visualization

#26473 Excel Test Cleanup - ReadWriteClass
  pandas/tests/io/test_excel.py
Labels: Clean, IO Excel, Testing

#26477 CLN: pd.TimeGrouper
  doc/source/whatsnew/v0.25.0.rst
  pandas/__init__.py
  pandas/core/api.py
  pandas/tests/api/test_api.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_time_grouper.py
Labels: Clean, Timeseries

#26464 CLN: Remove ExcelWriter.sheetname
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/test_excel.py
Labels: Clean, IO Excel

#26522 CLN: Remove deprecated parse_cols from read_excel
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/test_excel.py
Labels: Clean, IO Excel

#26392 [TEST] Add two more parameters to the test_dti_add_sub_nonzero_mth_offset
  pandas/tests/arithmetic/test_datetime64.py
Labels: Frequency, Testing, Timeseries

#26458 Remove py.path special handling from io.common
  pandas/io/common.py
Labels: Clean

#26523 CLN: remove StringMixin from code base, except in core.computation
  pandas/io/pytables.py
  pandas/io/stata.py
Labels: Clean, Internals

#26516 MAINT: port numpy#13188 for np_datetime simplification
  pandas/_libs/tslibs/src/datetime/np_datetime.c
Labels: Dependencies, Internals

#26533 DOC: fix broken link for .iloc
  pandas/core/indexing.py
Labels: Docs

#26540 CLN: pd.options.html.border
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/config_init.py
  pandas/core/frame.py
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_to_html.py
Labels: Clean, Output-Formatting

#26391 [PERF] Get rid of MultiIndex conversion in IntervalIndex.is_unique
  asv_bench/benchmarks/index_object.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/interval.py
Labels: Interval, Performance

#26548 xfail constructor test for numpydev
  pandas/compat/numpy/__init__.py
  pandas/tests/frame/test_constructors.py
Labels: CI

#26241 BUG: Enable plotting with PeriodIndex with arbitrary frequencies, resolves #14763
  doc/source/whatsnew/v0.25.0.rst
  pandas/plotting/_timeseries.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Visualization

#26137 Deprecate SparseDataFrame and SparseSeries
  doc/source/user_guide/sparse.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/sparse.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/core/sparse/frame.py
  pandas/core/sparse/scipy_sparse.py
  pandas/core/sparse/series.py
  pandas/tests/arrays/sparse/test_accessor.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_packers.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_pytables.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_combine_concat.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_subclass.py
  pandas/tests/sparse/frame/test_analytics.py
  pandas/tests/sparse/frame/test_apply.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/frame/test_to_csv.py
  pandas/tests/sparse/frame/test_to_from_scipy.py
  pandas/tests/sparse/series/test_series.py
  pandas/tests/sparse/test_combine_concat.py
  pandas/tests/sparse/test_format.py
  pandas/tests/sparse/test_groupby.py
  pandas/tests/sparse/test_indexing.py
  pandas/tests/sparse/test_pivot.py
  pandas/tests/sparse/test_reshape.py
  setup.cfg
Labels: Deprecate, Sparse

#26547 CI: unary operator expected error in log files
  ci/setup_env.sh
Labels: CI

#26518 Fix type annotations in pandas.core.indexes.period
  mypy.ini
  pandas/core/indexes/period.py
Labels: Indexing, Typing

#26543 Fixturize Test Excel
  pandas/tests/io/test_excel.py
Labels: Clean, IO Excel, Testing

#26519 Issue/26506 Provides correct desciption in docstring that get_indexer methods are not yet supported
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
Labels: Docs, Indexing, Interval

#26399 ENH: Support nested renaming / selection
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/__init__.py
  pandas/core/api.py
  pandas/core/base.py
  pandas/core/groupby/__init__.py
  pandas/core/groupby/generic.py
  pandas/tests/api/test_api.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_other.py
Labels: API Design, Deprecate, Groupby

#26463 Fix 'observed' kwarg not doing anything on SeriesGroupBy
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_categorical.py
Labels: Groupby

#26553 Remove Unnecessary Subclasses from test_excel
  pandas/io/excel/_base.py
  pandas/tests/io/test_excel.py
Labels: Clean, IO Excel, Testing

#25567 DEPR: remove Panel-specific parts of core.indexing
  pandas/_libs/indexing.pyx
  pandas/core/indexing.py
  pandas/tests/indexing/test_indexing.py
Labels: Indexing, Panel

#26575 PERF/CI: fix benchmark import error + run asv check on all builds
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/groupby.py
  asv_bench/benchmarks/io/parsers.py
  azure-pipelines.yml
Labels: Benchmark

#26577 TST: update tests\plotting\test_frame.py message check for mpl 3.1.0
  pandas/plotting/_compat.py
  pandas/tests/plotting/test_frame.py
Labels: CI, Testing, Visualization

#26586 Revert test_constructors xfail
  pandas/tests/frame/test_constructors.py
Labels: CI

#26497 DOC: Fixed redirects in various parts of the documentation
  pandas/core/arrays/categorical.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/concat.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/reshape/concat.py
  pandas/core/tools/datetimes.py
  pandas/core/window.py
  pandas/io/json/json.py
  pandas/io/parsers.py
  pandas/io/pytables.py
Labels: Docs
