Repository pandas-dev/pandas, pull requests merged in 2019-10, with the labels that each got.

#28604 CLN: Assorted typings
  pandas/core/algorithms.py
  pandas/core/util/hashing.py
Labels: Typing

#28571 DOC: Fixed PR08 docstring errors in pandas.tseries
  pandas/tseries/offsets.py
Labels: Docs

#28577 DOC: Add scaling to large datasets section
  doc/.gitignore
  doc/source/index.rst.template
  doc/source/user_guide/index.rst
  doc/source/user_guide/scale.rst
  doc/source/whatsnew/v1.0.0.rst
  environment.yml
  pandas/util/testing.py
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
Labels: Docs

#28671 BUG: restore limit in RangeIndex.get_indexer
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/indexes/range.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexes/test_range.py
Labels: Bug, Indexing

#28707 DOC: Fixed PR09 docstring errors in pandas.tseries (#27977)
  pandas/tseries/offsets.py
Labels: Docs

#28710 CI Failing: TestReadHtml.test_spam_url #28708
  pandas/tests/io/test_html.py
Labels: CI, IO HTML

#28564 TST: un-xfail incorrectly xfailed tests for maybe_promote
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes, Testing

#28651 CLN: Define and pin GroupBy properties without exec
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Clean, Groupby

#28716 Backport PR #28710 on branch 0.25.x (CI Failing: TestReadHtml.test_spam_url #28708)
  pandas/tests/io/test_html.py
Labels: CI, IO HTML

#28709 DOC: Fixed PR08, PR09 doctring issues in pandas.core.groupby
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Docs

#28718 DOC: Fixed PR06 docstring errors in pandas.DataFrame
  pandas/core/frame.py
Labels: Docs

#28721 DOC: Fixed PR06 docstrings errors in pandas.arrays.IntervalArray
  pandas/core/arrays/interval.py
Labels: Docs

#28723 DOC: Fixed PR06 docstrings errors in pandas.ExcelWriter
  pandas/io/excel/_base.py
Labels: Docs

#28251 BUG: Fix numpy boolean subtraction error in Series.diff
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/algorithms.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_timeseries.py
Labels: Bug, Dtypes, Reshaping

#28720 CLN: Exception in io/plotting
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/io/test_sql.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Clean, Visualization

#28637 CLN: streamline Series _construct_result calls
  pandas/core/ops/__init__.py
  pandas/core/series.py
Labels: Clean

#28717 DOC: Series.between() can take arguments that are not just scalars
  pandas/core/series.py
Labels: Docs

#28725 Change maybe_promote fill_value to dt64/td64 NaT instead of iNaT
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Compat, Missing-data

#28728 DOC: fix pr09,pr08 errors in frame.py
  pandas/core/frame.py
Labels: Docs

#28712 Backport PR #28671 on branch 0.25.x (BUG: restore limit in RangeIndex.get_indexer)
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/indexes/range.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexes/test_range.py
Labels: Indexing, Regression

#28737 Backport PR #28400 on branch 0.25.x (Fix a typo in "computation.rst" in document.)
  doc/source/user_guide/computation.rst
Labels: Docs

#21686 API: remove ordered requirement in Categorical.searchsorted
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/base.py
  pandas/tests/arrays/categorical/test_analytics.py
Labels: API Design, Categorical

#28667 DOC: Updating See Also section in IndexOpsMixin
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/indexes/multi.py
Labels: Docs

#28743 DOC: Styler errors PR08 and PR09
  pandas/io/formats/style.py
Labels: Docs

#28736 TST: add test to confirm adding 'm' to a Series of strings does not error
  pandas/tests/series/test_arithmetic.py
Labels: Strings, Testing

#28680 BUG: Fix RangeIndex.get_indexer for decreasing RangeIndex
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/indexes/range.py
  pandas/tests/indexes/test_range.py
Labels: Bug, Indexing, Regression

#28731 TST: return pytest MarkDecorator from td.skip_if_no #26735
  pandas/tests/io/test_gcs.py
Labels: Clean, Testing

#28719 DOC: Fixed PR06 docstrings errors in pandas.timedelta_range
  pandas/core/indexes/timedeltas.py
Labels: Docs

#28745 Backport PR #28680 on branch 0.25.x (BUG: Fix RangeIndex.get_indexer for decreasing RangeIndex)
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/indexes/range.py
  pandas/tests/indexes/test_range.py
Labels: Bug, Indexing, Regression

#28727 Added doctstring to fixture
  pandas/tests/io/excel/conftest.py
Labels: Testing

#28734 BUG: fix renaming in requirements generation script
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
Labels: Dependencies

#28638 REF: Consolidate alignment calls in DataFrame ops
  pandas/core/frame.py
  pandas/core/ops/__init__.py
Labels: Reshaping

#28729 TST: Fix broken test cases where Timedelta/Timestamp raise
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Testing

#28748 DOC: Fixed doctring errors PR08, PR09 in pandas.io
  pandas/io/formats/style.py
  pandas/io/json/_table_schema.py
Labels: Docs

#28742 DOC: Pandas.Series.drop docstring PR02 (#27976)
  pandas/core/series.py
Labels: Docs

#28643 BUG: Fix TypeError raised in libreduction
  pandas/_libs/reduction.pyx
  pandas/core/apply.py
  pandas/tests/groupby/test_groupby.py
Labels: Error Reporting

#28756 Fixed docstring errors in pandas.period range and pandas.PeriodIndex
  pandas/core/indexes/period.py
Labels: Docs

#28761 CLN: Fix typo in contributing.rst
  doc/source/development/contributing.rst
Labels: Docs

#28621 DEPR: Deprecate Index.set_value
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: Deprecate, Index

#27584 CLN: Centralised _check_percentile
  pandas/core/algorithms.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/util/_validators.py
Labels: Refactor

#28750 reenable codecov
  ci/run_tests.sh
Labels: CI

#28569 Bugfix/groupby datetime issue
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_apply.py
Labels: Bug, Groupby

#28764 TST: port maybe_promote tests from #23982
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes, Testing

#28752 DOC: Minor fixes in pandas/testing.py docstring.
  pandas/util/testing.py
Labels: Docs

#28630 WEB: Add diversity note to team.md
  web/pandas/about/team.md
Labels: Web

#28739 DOC: fix PR09,PR08 errors for pandas.Timestamp
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#28018 DOC/TST: Update the parquet (pyarrow >= 0.15) docs and tests regarding Categorical support
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/tests/io/test_parquet.py
Labels: Docs, IO Parquet, Testing

#28794 DOC: Fix PR06 docstring errors in pandas.merge_asof
  pandas/core/reshape/merge.py
Labels: Docs

#28623 DOC: start using new bootstrap-based sphinx theme
  doc/redirects.csv
  doc/source/conf.py
  doc/source/ecosystem.rst
  doc/source/getting_started/index.rst
  doc/source/getting_started/install.rst
  doc/source/index.rst.template
  environment.yml
  requirements-dev.txt
  web/pandas/getting_started.md
Labels: Docs

#28801 TST: Move datetime specific test from common tests
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_datetime.py
Labels: Clean, Testing, Timeseries

#28775 TST: Remove maybe_promote tests for iNaT as an NA value
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes, Missing-data, Testing

#28776 TST: fix maybe_promote float dtype xfails
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes

#28777 TST: port more maybe_promote tests, adds 260 xfails
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes, Testing

#28746 Test pytables refactor
  pandas/tests/io/pytables/common.py
  pandas/tests/io/pytables/conftest.py
  pandas/tests/io/pytables/test_compat.py
  pandas/tests/io/pytables/test_complex.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/pytables/test_timezones.py
  pandas/util/_test_decorators.py
Labels: Clean, IO HDF5, Testing

#28670 Fix incorrect doc for to_datetime
  pandas/core/tools/datetimes.py
Labels: Docs

#28772 hide Index.get_values in docs and IPython tab completion
  pandas/core/indexes/base.py
Labels: Deprecate, Docs

#28741 BUG: Fix DataFrame logical ops Series inconsistency
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/core/ops/__init__.py
  pandas/core/ops/dispatch.py
  pandas/tests/frame/test_operators.py
  pandas/tests/series/test_operators.py
Labels: Reshaping

#28735 Issue 28518 multiindex interesection
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/test_multilevel.py
Labels: Bug, MultiIndex, Reshaping

#27949 API: Add string extension type
  ci/code_checks.sh
  doc/source/getting_started/basics.rst
  doc/source/reference/arrays.rst
  doc/source/user_guide/text.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/__init__.py
  pandas/arrays/__init__.py
  pandas/core/api.py
  pandas/core/arrays/__init__.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/string_.py
  pandas/core/dtypes/missing.py
  pandas/core/strings.py
  pandas/tests/api/test_api.py
  pandas/tests/arrays/string_/__init__.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/extension/test_string.py
  pandas/tests/test_strings.py
  pandas/util/testing.py
Labels: Dtypes, ExtensionArray, Strings

#28754 TST: Fix maybe_promote xfails
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Clean, Testing

#28795 PERF: improve perf. of Categorical.searchsorted
  asv_bench/benchmarks/categoricals.py
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
  pandas/tests/arrays/categorical/test_analytics.py
Labels: Categorical, Performance

#28789 TST: Added SA01, SA02, and SA03 error checks to the Travis CI Build
  ci/code_checks.sh
Labels: Docs

#28666 BUG: fix broken error message in ujson.encode() (GH18878)
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/tests/io/json/test_ujson.py
Labels: Error Reporting, IO JSON

#28760 DOC: Fixed PR06 docstring errors in pandas.interval_range & pandas.util.hash_array
  pandas/core/indexes/interval.py
  pandas/core/util/hashing.py
Labels: Docs

#27874 COMPAT: unique() should preserve the dtype of the input
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/algorithms.py
  pandas/tests/test_base.py
Labels: Algos, Dtypes, Reshaping

#28804 DOC/BLD: remove old sphinx pin
  environment.yml
  requirements-dev.txt
Labels: Docs

#28798 BUG: Keep categorical name in groupby
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_categorical.py
Labels: Bug, Categorical, Groupby

#28632 BUG: DataFrame.to_html validates formatters has the correct length
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML

#28830 troubleshoot CI failing Linux py36_32bit
  ci/deps/azure-36-32bit.yaml
Labels: CI, Dependencies

#28824 TST: Update test in #28798 to use a Categorical
  pandas/tests/groupby/test_categorical.py
Labels: Categorical, Groupby, Testing

#28832 TST: port tests from #23982
  pandas/tests/dtypes/cast/test_promote.py
Labels: Testing

#28802 BUG: Coercing bool types to int in qcut
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/reshape/tile.py
  pandas/tests/reshape/test_cut.py
  pandas/tests/reshape/test_qcut.py
Labels: Bug, Dtypes, Reshaping

#28835 Remove NDFrameGroupBy Class
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Groupby, Refactor

#28762 BUG: Allow cast from cat to extension dtype
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Bug, Categorical, ExtensionArray

#28165 ENH: implement TimedeltaArray/TimedeltaIIndex sum, median, std
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Algos, Timeseries

#28828 CLN: core.generic.NDFrame.astype
  pandas/core/generic.py
Labels: Clean, Dtypes

#28809 TST: Dataframe KeyError when getting nonexistent category (#28799)
  pandas/tests/groupby/test_categorical.py
Labels: Error Reporting, Groupby

#28771 CLN: Exception*2 in groupby wrapper
  pandas/core/groupby/groupby.py
Labels: Clean

#28850 TST: un-xfail 1 passing maybe_promote test
  pandas/tests/dtypes/cast/test_promote.py
Labels: Clean, Testing

#28854 remove doc note about apply applying a function to the first element …
  pandas/core/frame.py
Labels: Docs

#28856 TST: un-xfail 22 maybe_promote tests
  pandas/tests/dtypes/cast/test_promote.py
Labels: Clean, Dtypes

#28844 TST: Improve compatibility with pypy error messages
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Error Reporting, Testing

#28852 TST: Fix not-boxed maybe_promote test
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes

#28833 TST: fix 24 xfails in maybe_promote
  pandas/core/dtypes/cast.py
  pandas/core/internals/concat.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes, Testing

#28848 CLN: Assorted cleanups
  ci/code_checks.sh
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_merge_ordered.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_combine_concat.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_rank.py
  pandas/tests/test_algos.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_sorting.py
  pandas/tests/test_strings.py
Labels: Clean

#28847 Clean up Abstract and Naming Definitions for GroupBy
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Groupby, Refactor

#28858 DOC: Fix missing periods and non capitalized summary beginnings (#27977)
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/interval.py
  pandas/io/formats/style.py
  pandas/plotting/_misc.py
Labels: Docs

#28606 fix unnecessary sort in pd.read_json and orient="index"
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/json/_json.py
  pandas/tests/io/json/test_pandas.py
Labels: Compat, IO JSON

#28883 CLN: dont catch Exception in groupby var
  pandas/core/groupby/groupby.py
Labels: Clean, Error Reporting, Groupby

#28878 CLN: dont catch on groupby.mean
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Groupby

#28879 CLN: assorted cleanups, remove unicode checks in cython
  pandas/_libs/hashing.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/parsers.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/ops/array_ops.py
  pandas/tests/frame/test_operators.py
  pandas/tests/frame/test_query_eval.py
Labels: Clean

#28873 CLN: No catching needed for groupby median
  pandas/core/groupby/groupby.py
Labels: Groupby

#28700 read_hdf closes HDF5 stores that it didn't open.
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_store.py
Labels: IO HDF5

#28880 TST: Fix maybe_promote floating non-boxed tests
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes

#28864 TST: Fix xfails for non-box maybe_promote on integer dtypes
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes

#28887 DOC: Fixed PR06 error in pandas.io.formats.style.Styler.set_table_attributes
  pandas/io/formats/style.py
Labels: Docs

#28885 DOC: Fixed PR06 errors in pandas.api.extensions.ExtensionArray
  pandas/core/arrays/base.py
Labels: Docs

#28899 REF: simplify maybe_promote integer cases
  pandas/core/dtypes/cast.py
Labels: Clean, Dtypes

#28915 DOC: Fix typos in docstrings
  pandas/core/indexes/multi.py
  pandas/core/indexes/timedeltas.py
Labels: Docs

#28914 TYPING: lockdown test modules passing mypy
  setup.cfg
Labels: Typing

#28913 CLN: simplify maybe_promote in float and complex cases
  pandas/core/dtypes/cast.py
Labels: Clean, Dtypes

#28910 TYPING: errors reported by mypy 0.730
  pandas/compat/pickle_compat.py
Labels: Typing

#28886 REF: use fused types for groupby_helper
  pandas/_libs/groupby_helper.pxi.in
Labels: Dtypes, Groupby

#28875 BUG: Allow all int types for merge (GH28870)
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Bug, Reshaping

#28861 TST: Fix 36 maybe_promote xfails wanting np.bytes_ instead of np.object_
  pandas/tests/dtypes/cast/test_promote.py
Labels: Clean, Dtypes

#28908 TYPING: fix type annotation for pandas.io.formats.format._binify
  pandas/io/formats/format.py
Labels: Typing

#23982 TST: add test coverage for maybe_promote
  pandas/tests/dtypes/cast/test_promote.py
Labels: Dtypes, Testing

#28865 TST: Use fixtures instead of setup_method for index tests
  pandas/tests/indexes/common.py
  pandas/tests/indexes/conftest.py
  pandas/tests/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_datetimelike.py
  pandas/tests/indexes/interval/test_base.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/test_range.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
Labels: Index, Refactor, Testing

#28853 CLN: dont catch Exception on reindex_multi
  pandas/core/generic.py
Labels: Clean, MultiIndex

#28857 CLN: assorted cleanups, mostly post-black fixups
  asv_bench/benchmarks/ctors.py
  asv_bench/benchmarks/eval.py
  asv_bench/benchmarks/io/hdf.py
  doc/source/conf.py
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/reduction.pyx
  pandas/_version.py
  pandas/core/apply.py
  pandas/io/sas/sas7bdat.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/style.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/io/test_html.py
  pandas/tests/window/test_window.py
  pandas/tseries/offsets.py
  pandas/util/_decorators.py
  pandas/util/_exceptions.py
  pandas/util/_print_versions.py
  pandas/util/_test_decorators.py
  pandas/util/_validators.py
  pandas/util/testing.py
  scripts/find_commits_touching_func.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
  setup.py
Labels: Clean

#28807 DOC: PR06 docstring fixes
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/period.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
Labels: Docs

#28811 TST: Allow for multiple variables on the same line in docstring validation
  pandas/core/series.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#28939 CLN: try/except cleanups
  pandas/core/apply.py
  pandas/core/base.py
  pandas/core/groupby/generic.py
Labels: Clean

#28918 BUG: Avoid undefined behaviour when converting from float to timedelta
  pandas/core/nanops.py
Labels: Timedelta

#28907 Added note to 'contributing.rst file', telling users to append GH Issue…
  doc/source/development/contributing.rst
Labels: Docs

#28897 REF: maybe_promote refactor/cleanup
  pandas/core/dtypes/cast.py
Labels: Clean, Dtypes

#28805 API: Add various deprecated attributes to ._deprecated
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/tests/series/test_api.py
Labels: Deprecate

#28803 TST: Test pivot_table() with categorical data
  pandas/tests/reshape/test_pivot.py
Labels: Categorical, Reshaping

#27368 BUG: Need 'windows-1252' encoding for locale names.
  doc/source/whatsnew/v1.0.0.rst
  pandas/_config/localization.py
Labels: Linux, Unicode

#28940 DOC: disable nbsphinx including requirejs
  doc/source/conf.py
Labels: Docs

#28947 CLN: fix mypy errors in pandas/tests/extension/test_numpy.py #28926
  pandas/tests/extension/base/ops.py
  setup.cfg
Labels: Typing

#28942 TST: add test_series_any_timedelta for GH17667
  pandas/tests/test_multilevel.py
Labels: Testing

#28946 PR06 doc string fixes
  pandas/core/computation/eval.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/reshape/tile.py
  pandas/core/tools/numeric.py
  pandas/io/json/_json.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/tseries/frequencies.py
Labels: Docs

#28935 fix #28926 pandas\api\test_api.py mypy errors
  pandas/tests/api/test_api.py
  setup.cfg
Labels: Typing

#28753 Eliminated _WriterBase class, removed unused fixtures from methods in pandas/io/excel/test_writers.py
  pandas/tests/io/excel/test_writers.py
Labels: Clean, IO Excel, Testing

#28960 Fix mypy errors for pandas\tests\* #28926 (test_algos.py)
  pandas/tests/test_algos.py
  setup.cfg
Labels: Typing

#28845 DOC: Fixed PR08 and PR09 docstring errors in pandas.Series
  pandas/core/accessor.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/plotting/_core.py
  pandas/tseries/offsets.py
Labels: Docs

#28765 BUG: Partial fix for docstring validation for parameters
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#28686 DOC: fix formatting in the ExtensionArray docstrings
  pandas/core/arrays/base.py
Labels: Docs

#28841 BUG: use EA.astype in ExtensionBlock.to_native_types
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/extension/list/__init__.py
  pandas/tests/extension/list/array.py
  pandas/tests/extension/list/test_list.py
Labels: Bug, ExtensionArray

#28982 Document 3.8 compatibility
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v0.25.2.rst
  setup.py
Labels: Docs, Python 3.8

#28730 CI: 3.8 build
  .travis.yml
  ci/build38.sh
  ci/setup_env.sh
Labels: CI, Python 3.8

#28977 CLN: remove unnecessary get_value_at calls
  pandas/_libs/index.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/reduction.pyx
  pandas/core/sorting.py
Labels: Clean, Internals

#28978 CLN: declare types in rank_1d_, rank_2d
  pandas/_libs/algos_rank_helper.pxi.in
Labels: Clean, Internals

#28967 CLN: Exception in _libs
  pandas/_libs/intervaltree.pxi.in
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/timezones.pyx
Labels: Clean

#28972 CLN: pandas-dev#28926 Fix pandas/tests/tseries/offsets/test_offsets_properties
  pandas/tests/tseries/offsets/test_offsets_properties.py
  setup.cfg
Labels: Typing

#28973 CLN: pandas-dev#28926 Fix mypy errors in pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/conftest.py
  setup.cfg
Labels: Typing

#28985 Backport PR #28841: BUG: use EA.astype in ExtensionBlock.to_native_types (#28841)
  doc/source/whatsnew/v0.25.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/extension/list/__init__.py
  pandas/tests/extension/list/array.py
  pandas/tests/extension/list/test_list.py
Labels: ExtensionArray

#28999 Backport PR #28982 on branch 0.25.x (Document 3.8 compatibility)
  ci/deps/azure-36-32bit.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.25.2.rst
  setup.py
Labels: Docs

#29000 DOC: 0.25.2 whatsnew cleanup
  doc/source/whatsnew/v0.25.2.rst
Labels: Docs

#29002 Backport PR #28730 on branch 0.25.x (CI: 3.8 build)
  .travis.yml
  ci/build38.sh
  ci/setup_env.sh
Labels: CI

#29004 fix is_scalar documentation (#28998)
  pandas/_libs/lib.pyx
Labels: Docs

#29010 Setuptools CI fixup
  ci/setup_env.sh
Labels: CI

#29006 CLN: Fix mypy errors in pandas/tests/io/test_sql.py Reverted and added type changes
  pandas/tests/io/test_sql.py
  setup.cfg
Labels: Typing

#28793 DOC: Reference level name as Term of HDFStore.select query (#28791)
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.0.0.rst
Labels: Docs, IO HDF5

#28962 CLN: move small bits outside of try/excepts
  pandas/_libs/algos_take_helper.pxi.in
  pandas/core/base.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Clean

#28958 CLN: Consistent and Annotated Return Type of _iterate_slices
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Groupby, Typing

#29013 TST: restore xfail for test_apply
  pandas/tests/groupby/test_categorical.py
Labels: Testing

#28692 To html encoding add
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML

#29015 Backport PR #29010 on branch 0.25.x (Setuptools CI fixup)
  ci/setup_env.sh
Labels: CI
