Repository pandas-dev/pandas, pull requests merged in 2019-12, with the labels that each got.

#29942 A closing parenthesis has been added to resolve a typo.
  doc/source/getting_started/basics.rst
Labels: Docs

#29937 CI: added unwanted pattern test case for "foo.__class__" instead of type(foo)
  ci/code_checks.sh
Labels: CI, Style

#29923 CLN: OrderedDict -> Dict
  pandas/core/frame.py
  pandas/io/excel/_base.py
  pandas/io/stata.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/multi/test_constructor.py
  pandas/tests/indexes/multi/test_conversion.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/test_stata.py
Labels: Clean

#29900 DEPR: Categorical.ravel, get_dtype_counts, dtype_str, to_dense
  asv_bench/benchmarks/frame_methods.py
  doc/redirects.csv
  doc/source/reference/frame.rst
  doc/source/reference/indexing.rst
  doc/source/reference/series.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/common.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/generic/test_generic.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/test_common.py
Labels: Deprecate

#29940 BUG: merge_asof with tz_aware left index and right column
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Bug, Reshaping, Timezones

#29938 STY: F-strings and repr
  pandas/tests/tseries/offsets/test_fiscal.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
  pandas/util/_decorators.py
  pandas/util/testing.py
Labels: Style

#29929 DEPR: tz_convert in the Timestamp constructor raises
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Deprecate, Timezones

#29936 CLN: make kwargs explicit in pytables constructors
  pandas/io/pytables.py
Labels: Clean

#29875 DEPR: dropna multiple axes, fillna int for td64, from_codes with floats, Series.nonzero
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/frame.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/frame/test_missing.py
  pandas/tests/series/test_missing.py
Labels: Clean, Deprecate

#29903 Convert core/indexes/base.py to f-strings
  pandas/core/indexes/base.py
Labels: Style

#29935 CLN: make kwargs explicit for pytables read_ methods
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#29939 CLN: explicit signature for to_hdf
  pandas/core/generic.py
  pandas/io/pytables.py
Labels: IO HDF5, Typing

#29932 TST: add test for rolling max/min/mean with DatetimeIndex over different frequencies
  pandas/tests/window/test_timeseries_window.py
Labels: Testing

#29825 CLN: BlockManager.apply
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Clean, Internals

#29597 ENH: add NA scalar for missing value indicator, use in StringArray.
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/__init__.py
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pxd
  pandas/_libs/missing.pyx
  pandas/_libs/testing.pyx
  pandas/core/api.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/string_.py
  pandas/core/dtypes/missing.py
  pandas/io/formats/format.py
  pandas/tests/api/test_api.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_string.py
  pandas/tests/scalar/test_na_scalar.py
Labels: Enhancement, Missing-data

#29949 STY: Added space at the end of the sentence
  pandas/core/dtypes/dtypes.py
Labels: Style

#29950 STY: "foo!r" -> "repr(foo)" #batch-2
  pandas/core/computation/pytables.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
Labels: Style

#29948 STY: "foo!r" -> "repr(foo)" #batch-1
  pandas/_libs/interval.pyx
  pandas/conftest.py
  pandas/core/accessor.py
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/numpy_.py
  pandas/core/computation/align.py
  pandas/core/computation/eval.py
  pandas/core/computation/expr.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
Labels: Style

#29947 TYP: Annotated __eq__
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/sparse/dtype.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/frozen.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/tseries/offsets.py
Labels: Typing

#29951 CLN: fix pytables passing too many kwargs
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#29930 DEPR: DTI/TDI/PI constructor arguments
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/period/test_construction.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/timedeltas/test_construction.py
Labels: Constructors, Deprecate, Index, Period, Timedelta, Timeseries

#27929 API/DEPR: Change default skipna behaviour + deprecate numeric_only in Categorical.min and max
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/series.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/reductions/test_reductions.py
Labels: API Design, Categorical, Deprecate

#29958 CLN: small things in pytables
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#29956 DOC : Typo fix in userguide/Styling
  doc/source/user_guide/style.ipynb
Labels: Docs

#29959 STY: "{foo!r}" -> "{repr(foo)}" #batch-4
  pandas/io/html.py
  pandas/io/parsers.py
  pandas/plotting/_core.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/test_html.py
  pandas/tests/test_strings.py
Labels: Style

#29968 TYP: some types for pandas/core/arrays/base.py
  pandas/core/arrays/base.py
Labels: Typing

#29799 API: Infer extension types in array
  doc/source/user_guide/integer_na.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/lib.pyx
  pandas/core/construction.py
  pandas/tests/arrays/test_array.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/internals/test_internals.py
  pandas/tests/series/test_ufunc.py
Labels: Dtypes, ExtensionArray

#29972 TYP: add some types to pandas/io/parquet.py
  pandas/io/parquet.py
Labels: Typing

#29971 CLN: explicit kwargs and docstring for create_index
  pandas/io/pytables.py
Labels: IO HDF5

#29977 CLN: explicit kwargs for select
  pandas/io/pytables.py
Labels: IO HDF5

#29952 CLN: f-string in pandas/core/window/*
  pandas/core/window/common.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Style

#29984 CI: add jinja to deps
  ci/deps/azure-windows-36.yaml
Labels: CI, Dependencies

#29993 CI: re-enable downstream test for geopandas
  pandas/tests/test_downstream.py
Labels: CI

#29871 REF: io.pytables operate on DataFrames instead of Blocks
  pandas/io/pytables.py
Labels: IO HDF5, Internals, Refactor

#29999 TYP: some (mainly primative) types for tseries.frequencies
  pandas/tseries/frequencies.py
Labels: Typing

#29998 TST: update test_nanops setup_method
  pandas/tests/test_nanops.py
Labels: Testing

#29996 TST: use index_or_series fixture
  pandas/tests/arithmetic/test_datetime64.py
Labels: Testing, Typing

#29995 CLN: some imports in pandas/tests/frame/test_dtypes.py
  pandas/tests/frame/test_dtypes.py
Labels: Typing

#30004 DEPR: get_duplicates
  doc/redirects.csv
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
Labels: Deprecate

#30006 DOC: whatsnew notes that slipped through the cracks
  doc/source/whatsnew/v1.0.0.rst
Labels: Deprecate, Docs

#30007 CLN: test code no longer shared with sparse
  pandas/tests/frame/test_api.py
  pandas/tests/series/test_api.py
Labels: Clean, Testing

#29994 TST: add some message checks in test_query_eval
  pandas/tests/frame/test_query_eval.py
Labels: Testing

#29982 CLN: assorted pytables cleanups, remove unwanted assertion
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#29969 TYP: add some types to pandas/core/arrays/numpy_.py
  pandas/core/arrays/numpy_.py
Labels: Typing

#29943 BUG: fix Series.interpolate(method='index') with unsorted index
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/missing.py
  pandas/tests/series/test_missing.py
Labels: Missing-data

#30009 CI: troubleshoot openpyxl failures
  ci/deps/travis-36-cov.yaml
  pandas/tests/io/excel/test_openpyxl.py
Labels: CI

#30039 CI: ensure proper coverage of different pyarrow versions
  ci/deps/azure-36-locale.yaml
  ci/deps/azure-37-locale.yaml
  ci/deps/travis-36-cov.yaml
  pandas/tests/io/test_parquet.py
Labels: CI, Dependencies

#30044 CI: Fix print skipped tests
  ci/print_skipped.py
Labels: CI

#30033 revert openpyxl test changes
  pandas/tests/io/excel/test_openpyxl.py
Labels: CI

#30032 changed "fun !r" -> "repr(fun)"
  pandas/core/series.py
  pandas/core/sorting.py
  pandas/core/strings.py
Labels: Style

#30023 f-string update for core.base.
  pandas/core/base.py
Labels: Clean, Style

#30036 Removed CParserError
  pandas/_libs/parsers.pyx
  pandas/io/common.py
  pandas/tests/test_errors.py
Labels: Clean, IO CSV, Internals

#30019 CLN: no need to broadcast axes for ndim<=2 (pytables)
  pandas/io/pytables.py
Labels: Clean

#30016 REF: make indexables cache_readonly (pytables)
  pandas/io/pytables.py
Labels: IO HDF5

#30012 CLN: annotate and de-nest write_array
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#30014 DOC: Added "Raises `KeyError`"
  pandas/compat/chainmap.py
Labels: Docs

#29991 TYP: some (mainly primative) types for core.generic
  pandas/core/generic.py
Labels: Typing

#29988 STY: F-strings
  ci/print_skipped.py
  doc/sphinxext/announce.py
  doc/sphinxext/contributors.py
Labels: Strings, Style

#29986 DEPR: remove real, imag, put, and str.partition kwarg
  doc/redirects.csv
  doc/source/reference/series.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/series.py
  pandas/core/strings.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_internals.py
  pandas/tests/test_strings.py
Labels: Clean, Deprecate

#29983 CI: Using more appropriate GitHub Actions syntax to set path
  .github/workflows/ci.yml
Labels: CI, Clean

#29979 REF: move attribute setting towards the constructor
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#29957 Make kwargs explicit in put, append
  pandas/core/generic.py
  pandas/io/pytables.py
Labels: IO HDF5

#29926 BUG: Index.get_value implementation for ExtensionArray
  pandas/core/indexes/base.py
  pandas/tests/extension/decimal/test_decimal.py
Labels: ExtensionArray, Indexing

#29892 String formatting > fstring
  pandas/errors/__init__.py
  pandas/tests/arrays/interval/test_ops.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/sparse/test_libsparse.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/base/printing.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/tseries/offsets/common.py
  pandas/tseries/frequencies.py
Labels: Style

#30049 CI: disable numpydev job
  ci/azure/posix.yml
  pandas/core/generic.py
Labels: CI

#30029 REF: collect attribute-setting at the end of create_axes
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30018 CLN: pytables _set_tz/_get_tz
  pandas/io/pytables.py
Labels: Clean, IO HDF5

#30055 STY: "{foo!r}" -> "{repr(foo)}"
  ci/print_skipped.py
Labels: Style

#29961 Use new NA scalar in BooleanArray
  pandas/_libs/missing.pyx
  pandas/core/arrays/boolean.py
  pandas/tests/arrays/test_boolean.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/scalar/test_na_scalar.py
Labels: ExtensionArray, Missing-data

#30010 DOC: Fix to lzma.LZMAFile
  pandas/compat/__init__.py
Labels: Docs, Typing

#30069 CI: temp skip BooleanArray pyarrow test
  pandas/tests/arrays/test_boolean.py
Labels: CI

#29989 DEPR: remove get_values, SparseArray.values
  doc/redirects.csv
  doc/source/reference/frame.rst
  doc/source/reference/indexing.rst
  doc/source/reference/series.rst
  pandas/_libs/reduction.pyx
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse/array.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/series/test_api.py
Labels: Clean, Deprecate, Sparse

#30028 f strings in core/sorting
  pandas/core/sorting.py
Labels: Clean, Style

#30072 Remove legacy scipy compat
  pandas/core/nanops.py
Labels: Clean

#30025 f strings in core/series
  pandas/core/series.py
Labels: Clean, Style

#30075 Fix PR06 docstring errors in sql.py and gbq.py
  pandas/io/gbq.py
  pandas/io/sql.py
Labels: Docs, Style

#29878 ENH: Allow users to definite their own window bound calculations in rolling
  doc/source/reference/window.rst
  doc/source/user_guide/computation.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/_libs/window/indexers.pyx
  pandas/api/__init__.py
  pandas/api/indexers/__init__.py
  pandas/core/window/indexers.py
  pandas/core/window/rolling.py
  pandas/tests/api/test_api.py
  pandas/tests/window/test_base_indexer.py
Labels: Enhancement, Window

#30034 BUG: unclosed file warning when passing invalid encoding
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Compat

#30071 STY: fstrings doc/source/conf.py
  doc/source/conf.py
Labels: Style

#30066 STY: Style fix pandas/errors/__init__.py
  pandas/errors/__init__.py
Labels: Style

#30080 STY: fstrings doc/source/conf.py #2
  doc/source/conf.py
Labels: Style

#30064 CLN: NDFrame.setup_axes
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/indexing/test_indexing.py
Labels: Clean

#30060 STY: fstrings doc/make.py
  doc/make.py
Labels: Style

#30068 CLN: simplify pytables create_axes
  pandas/io/pytables.py
Labels: IO HDF5

#30058 REF: pytables do string conversion early to set attributes in fewer places
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30003 DEPR: plotting deprecations
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/__init__.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tseries/converter.py
Labels: Deprecate, Visualization

#30000 TYP: some types for pandas/io/formats/csvs.py
  pandas/io/formats/csvs.py
Labels: Typing

#29401 removing kendall tests
  asv_bench/benchmarks/stat_ops.py
Labels: Benchmark

#30027 Updated .format() to f-strings
  pandas/io/html.py
Labels: Clean, Style

#30065 CI: correct azure-36-locale slow name + move pyarrow
  ci/azure/posix.yml
  ci/deps/azure-36-locale.yaml
  ci/deps/azure-36-locale_slow.yaml
Labels: CI

#30082 REF: make pytables.IndexCol.itemsize a property
  pandas/io/pytables.py
Labels: IO HDF5

#30084 REF: Standardize coercion in set_data
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30067 REF: set non_index_axes at the end of create_axes
  pandas/io/pytables.py
Labels: IO HDF5

#29134 Improve performance of equality comparison between a simple Index and a MultiIndex
  asv_bench/benchmarks/index_object.py
  asv_bench/benchmarks/multiindex_object.py
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
Labels: MultiIndex, Performance

#30088 DEPR: remove compound
  doc/redirects.csv
  doc/source/getting_started/10min.rst
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/generic.py
  pandas/tests/series/test_analytics.py
Labels: Deprecate

#30090 DEPR: join_axes kwarg to pd.concat
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Deprecate

#30085 REF: do string itemsize casting earlier
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30074 REF: make pytables get_atom_data non-stateful
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#29654 CI: Format isort output for azure
  ci/code_checks.sh
Labels: CI, Error Reporting

#30096 BUG: file leak in read_excel
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
  pandas/util/_test_decorators.py
Labels: IO Excel

#30102 REF: implement io.pytables.DataCol._get_atom
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30104 DEPR: ufunc.outer for Series
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/series.py
  pandas/tests/series/test_ufunc.py
Labels: Deprecate

#30101 REF: collect pytables DataCol.set_data calls in one place
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30089 DEPR: enforce deprecation of old set_axis signature
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/series/test_alter_axes.py
Labels: Deprecate

#30061 Replace custom macro with stdlib
  pandas/_libs/src/parser/tokenizer.c
Labels: Clean

#30111 DEPR: box arg in to_datetime
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
Labels: Deprecate

#30110 CLN: Refactor test_base - part1
  pandas/tests/indexes/test_frozen.py
  pandas/tests/test_base.py
Labels: Testing

#30079 TYP: Annotations in pandas/core/{accessor, sorting}.py
  pandas/core/accessor.py
  pandas/core/sorting.py
Labels: Typing

#30021 added f strings and typing to frame.py
  pandas/core/frame.py
  pandas/core/reshape/merge.py
Labels: Clean, Style, Typing

#30117 DEPR: integer add/sub for Timestamp, DatetimeIndex, TimedeltaIndex
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
Labels: Deprecate

#30113 DEPR: Series.argmin, argmax
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/series.py
  pandas/tests/reductions/test_reductions.py
Labels: Deprecate

#30116 STY: change .format() to fstring
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
Labels: Style

#30115 DEPR: DTI int64 values and tz interpreted as UTC
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/test_base.py
Labels: Timeseries

#30100 REF: implement io.pytables._maybe_adjust_name
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30118 DEPR: YyM units for Timedelta and friends
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/indexes/timedeltas.py
  pandas/core/tools/timedeltas.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Deprecate

#30120 CLN: f-string in pandas/core/accessor.py and pandas/core/algorithms.py
  pandas/core/accessor.py
  pandas/core/algorithms.py
Labels: Style

#30121 CLN: f-string in pandas/core/arrays/sparse/*
  pandas/core/arrays/sparse/accessor.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/arrays/sparse/scipy_sparse.py
Labels: Clean, Style

#30124 CLN: f-string in pandas/core/arrays/*
  pandas/core/arrays/_ranges.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/period.py
Labels: Clean, Style

#30119 DOC: Style format
  pandas/core/accessor.py
  pandas/core/sorting.py
Labels: Docs

#29954 Reduce Loosely Typed Functions in objToJSON
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: IO JSON, Refactor

#30135 CLN: change str.format() to f-string
  pandas/core/arrays/string_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/common.py
  pandas/core/computation/engines.py
  pandas/core/computation/expr.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
Labels: Style

#30136 Removed is_sparse_array from objToJSON
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Clean, IO JSON

#30132 REF: simplify pytables set_kind
  pandas/io/pytables.py
Labels: IO HDF5

#30130 CLN: Split test_base
  pandas/core/base.py
  pandas/tests/base/__init__.py
  pandas/tests/base/test_construction.py
  pandas/tests/base/test_conversion.py
  pandas/tests/base/test_ops.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/indexes/timedeltas/test_ops.py
  pandas/tests/series/test_analytics.py
Labels: Clean, Testing

#30127 CLN: pytables create_axes cleanup
  pandas/io/pytables.py
Labels: IO HDF5

#30125 CLN: clean pytables convert methods
  pandas/io/pytables.py
Labels: IO HDF5

#30109 Fixing 'names' doc for 'read_csv'
  pandas/io/parsers.py
Labels: Docs

#30103 DEPR: Index.contains, DatetimeIndex.offset
  doc/redirects.csv
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_range.py
Labels: Deprecate

#30097 API: Handle pow & rpow special cases
  doc/source/user_guide/missing_data.rst
  pandas/_libs/missing.pyx
  pandas/tests/scalar/test_na_scalar.py
Labels: Missing-data, Numeric

#30093 STY: fstrings, repr pandas/io/html.py
  pandas/io/html.py
Labels: Clean, Style

#30048 27820 clarify that read parquet accepts a directory path
  pandas/io/parquet.py
Labels: Docs, IO Parquet

#29909 Added FutureWarning to Series.str.__iter__
  doc/source/whatsnew/v0.12.0.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/strings.py
  pandas/tests/test_strings.py
Labels: Deprecate

#29858 ENH: Add progress_bar_type argument in read_gbq
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/gbq.py
  pandas/tests/io/test_gbq.py
Labels: IO Google

#28428 BUG: Remove error raise to allow same input function on the same column in named aggregation
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Groupby

#30142 REF: pytables remove IndexCol.infer, move attr setting to constructors
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30143 REF: pytables remove need for set_atom
  pandas/io/pytables.py
Labels: IO HDF5, Refactor

#30133 DOC: added docs
  pandas/core/indexing.py
Labels: Docs

#29842 ENH: Implement Kleene logic for BooleanArray
  asv_bench/benchmarks/boolean.py
  doc/source/index.rst.template
  doc/source/user_guide/boolean.rst
  doc/source/user_guide/index.rst
  pandas/core/arrays/boolean.py
  pandas/core/ops/__init__.py
  pandas/core/ops/dispatch.py
  pandas/core/ops/mask_ops.py
  pandas/tests/arrays/test_boolean.py
Labels: ExtensionArray, Missing-data

#30139 DEPR: Remove how, fill_method, and limit from resample
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resample_api.py
Labels: Deprecate, Resample

#29955 DEPR: Change default value for CategoricalDtype.ordered from None to False
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/construction.py
  pandas/core/dtypes/dtypes.py
  pandas/core/series.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/test_category.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_io.py
Labels: Categorical, Clean, Deprecate

#30095 PERF: improve conversion to BooleanArray from int/float array
  asv_bench/benchmarks/array.py
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/boolean.py
  pandas/tests/arrays/test_boolean.py
Labels: ExtensionArray, Performance

#30156 STY: some files in pandas/_libs/
  pandas/_libs/groupby.pyx
  pandas/_libs/hashing.pyx
  pandas/_libs/hashtable.pyx
  pandas/_libs/index.pyx
  pandas/_libs/indexing.pyx
Labels: Style

#30149 Consolidated Nanosecond Conversions
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Clean, IO JSON

#30137 CLN/TYPE: window aggregation cleanups and typing
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/rolling.py
Labels: Clean, Window

#29953 STY: "{foo!r}" -> "{repr(foo)}" #batch-3
  pandas/core/missing.py
  pandas/core/nanops.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/tile.py
  pandas/core/strings.py
  pandas/io/formats/css.py
  pandas/io/formats/excel.py
  pandas/io/formats/style.py
Labels: Style

#30155 DOC: Cleaned pandas/_libs/algos.pyx docstrings
  pandas/_libs/algos.pyx
Labels: Docs

#30174 Remove Dead JSON Code
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Clean, IO JSON

#30179 Simplified JSON string handling
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: IO JSON

#30157 DOC/STY: Cleaned pandas/_libs/{internals,interval}.pyx
  pandas/_libs/internals.pyx
  pandas/_libs/interval.pyx
Labels: Style, Typing

#30169 STY: Underscores for long numbers
  pandas/core/arrays/datetimes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/core/window/ewm.py
Labels: Style
