Repository pandas-dev/pandas, pull requests merged in 2019-08, with the labels that each got.

#27580 DOC:Update python version support info
  doc/source/install.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.23.1.rst
  doc/source/whatsnew/v0.23.2.rst
  doc/source/whatsnew/v0.23.4.rst
  doc/source/whatsnew/v0.24.0.rst
  doc/source/whatsnew/v0.24.1.rst
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v1.0.0.rst
Labels: Docs

#27685 CLN: Prune unnecessary internals
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/io/clipboards.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/formats/csvs.py
  pandas/io/formats/format.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/io/sas/sas_xport.py
  pandas/io/sql.py
  pandas/io/stata.py
Labels: Clean

#27653 BUG: Fix dir(interval_index)
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/lib.pyx
  pandas/core/strings.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Regression

#27691 Backport PR #27580 on branch 0.25.x
  doc/source/install.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.23.1.rst
  doc/source/whatsnew/v0.23.2.rst
  doc/source/whatsnew/v0.23.4.rst
  doc/source/whatsnew/v0.24.0.rst
  doc/source/whatsnew/v0.24.1.rst
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.0.rst
Labels: Docs

#27693 Backport PR #27653 on branch 0.25.x (BUG: Fix dir(interval_index))
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/lib.pyx
  pandas/core/strings.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Docs

#27689 DOC: 0.25 fixups
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v0.25.1.rst
Labels: Docs

#27478 Add a Roadmap
  doc/source/development/index.rst
  doc/source/development/roadmap.rst
Labels: Admin, Community

#27694 Backport PR #27689 on branch 0.25.x (DOC: 0.25 fixups)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v0.25.1.rst
Labels: Docs

#27662 DOC: add anonymizeIp for Google analytics in docs
  doc/source/themes/nature_with_gtoc/layout.html
Labels: Docs

#27701 CI: Fixed CI
  ci/deps/travis-36-locale.yaml
Labels: CI

#27674 Handle construction of string ExtensionArray from lists
  pandas/core/construction.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/arrow/test_string.py
Labels: ExtensionArray

#27703 Backport PR #27701 on branch 0.25.x (CI: Fixed CI)
  ci/deps/travis-36-locale.yaml
Labels: CI

#27698 Backport PR #27478 on branch 0.25.x (Add a Roadmap)
  doc/source/development/index.rst
  doc/source/development/roadmap.rst
Labels: Docs

#27520 DOC:Remove DataFrame.append from the 10min intro
  doc/source/getting_started/10min.rst
Labels: Docs

#27710 DOC: Fixed a typo in the roadmap.rst (the word "uses" appeared twice)
  doc/source/development/roadmap.rst
Labels: Docs

#27711 Backport PR #27710 on branch 0.25.x (DOC: Fixed a typo in the roadmap.rst (the word "uses" appeared twice))
  doc/source/development/roadmap.rst
Labels: Docs

#27700 BUG: grouby(axis=1) cannot select column names
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby

#27699 BUG: DTA/TDA incorrectly accepting iNaT for setitem
  pandas/core/arrays/datetimelike.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/test_base.py
Labels: Indexing, Missing-data, Timeseries

#27598 TYPING: some type hints for pandas\io\common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/common.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting, Typing

#27716 pandas.PeriodIndex and pandas.DateTimeIndex docstring quotes fix
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
Labels: Docs

#27708 Linebreak is bleeding into the documentation page
  pandas/core/base.py
Labels: Docs

#27734 TYPING: type hints for io.formats.latex
  pandas/io/formats/latex.py
Labels: Typing

#27741 CLN: deprivatize names in pd.core.common
  pandas/core/common.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/merge.py
  pandas/core/series.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/style.py
  pandas/io/json/_table_schema.py
  pandas/io/pytables.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/scalar/interval/test_interval.py
  pandas/tests/test_common.py
Labels: Clean

#27738 DOC: update docstrings following refactor of buffer handling
  pandas/core/generic.py
  pandas/io/formats/format.py
Labels: Docs, Output-Formatting

#27725 STYLE: Add flake8-comprehensions to pre-commit configuration
  .pre-commit-config.yaml
Labels: Style

#27739 BUG: fix+test PA+all-NaT TDA
  pandas/core/arrays/period.py
  pandas/core/ops/__init__.py
  pandas/tests/arithmetic/test_period.py
Labels: Missing-data, Timedelta

#27714 REF/CLN: maybe_downcast_to_dtype
  pandas/core/dtypes/cast.py
Labels: Dtypes

#27712 BUG: partial string indexing with scalar
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexing.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
Labels: Indexing, Timeseries

#27702 BUG: Concatenation warning still appears with sort=False
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/frame.py
  pandas/tests/frame/test_join.py
Labels: Reshaping

#27740 BUG: Fix NaT +/- DTA/TDA
  pandas/_libs/tslibs/nattype.pyx
  pandas/tests/scalar/test_nat.py
Labels: Missing-data, Timedelta

#27706 CLN: rename reduce-->do_reduce
  pandas/_libs/reduction.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/apply.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/ops/__init__.py
  pandas/tests/groupby/test_bin_groupby.py
Labels: Internals

#27743 Backport PR #27702 on branch 0.25.x (BUG: Concatenation warning still appears with sort=False)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/frame.py
  pandas/tests/frame/test_join.py
Labels: Reshaping

#27742 Backport PR #27712 on branch 0.25.x (BUG: partial string indexing with scalar)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexing.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
Labels: Indexing

#27746 CLN: Move base.StringMixin to computations.common
  pandas/core/base.py
  pandas/core/computation/common.py
  pandas/core/computation/expr.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
  pandas/tests/series/test_repr.py
Labels: Clean

#27747 REF: combine dispatch_to_index_op into dispatch_to_extension_op
  pandas/core/ops/__init__.py
Labels: Clean, Internals

#27726 BUG: fix+test DTA/TDA/PA add/sub Index
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Compat, ExtensionArray, Index

#27727 REF: define concat classmethods in the appropriate places
  pandas/core/dtypes/concat.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/test_category.py
Labels: Reshaping

#27715 TST: troubleshoot inconsistent xfails
  pandas/compat/__init__.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/computation/test_eval.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/series/test_analytics.py
  pandas/tests/sparse/test_combine_concat.py
  pandas/tests/sparse/test_pivot.py
Labels: Testing

#27683 CLN: remove _try_coerce_result altogether
  pandas/core/groupby/ops.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Clean, Internals

#27720 BUG: fix replace_list
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/generic.py
  pandas/core/internals/managers.py
  pandas/tests/indexing/test_coercion.py
Labels: Timezones

#27752 Backport PR #27715 on branch 0.25.x (TST: troubleshoot inconsistent xfails)
  pandas/compat/__init__.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/computation/test_eval.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/series/test_analytics.py
  pandas/tests/sparse/test_combine_concat.py
  pandas/tests/sparse/test_pivot.py
Labels: CI

#27753 Backport PR #27720 on branch 0.25.x (BUG: fix replace_list)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/generic.py
  pandas/core/internals/managers.py
  pandas/tests/indexing/test_coercion.py
Labels: Bug, Dtypes, Reshaping

#27754 Slightly rephrase SPSS doc
  doc/source/user_guide/io.rst
Labels: Docs

#27717 remove confusing instructions and link.
  doc/source/development/contributing.rst
Labels: Docs

#27382 ENH: Validation to only allow positive integers for options
  doc/source/whatsnew/v1.0.0.rst
  pandas/_config/config.py
  pandas/core/config_init.py
  pandas/tests/config/test_config.py
Labels: Output-Formatting

#27735 REF: separate out invalid ops
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/base.py
  pandas/core/ops/__init__.py
  pandas/core/ops/invalid.py
Labels: Clean

#27723 CLN: collected cleanups from other branches
  pandas/_libs/index.pyx
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/resample.py
  pandas/core/window.py
  pandas/tests/groupby/test_categorical.py
Labels: Clean

#27733 BUG: fix to_datetime(dti, utc=True)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
Labels: Timeseries, Timezones

#27767 BUG: Fix windowing over read-only arrays
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/window.py
  pandas/tests/window/test_rolling.py
Labels: Window

#27764 CLN/REF: Remove _try_cast_result, _try_coerce_and_cast_result
  pandas/core/groupby/generic.py
  pandas/core/groupby/ops.py
  pandas/core/internals/blocks.py
Labels: Clean

#27663 BUG: pd.crosstab not working when margin and normalize are set together
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping

#27782 Backport PR #27767 on branch 0.25.x (BUG: Fix windowing over read-only arrays)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/window.py
  pandas/tests/window/test_rolling.py
Labels: Window

#27630 DOC: Validate docstring directives
  ci/code_checks.sh
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#27783 Backport PR #27663 on branch 0.25.x (BUG: pd.crosstab not working when margin and normalize are set together)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping

#27774 DEPR: Removed the previously deprecated ExtensionArray._formatting_values
  doc/source/reference/extensions.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/io/formats/format.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_external_block.py
Labels: Deprecate, ExtensionArray

#27787 Fix miniconda path issue #26962
  azure-pipelines.yml
  ci/azure/posix.yml
  ci/azure/windows.yml
Labels: CI, Clean

#27793 DEPR: Remove previously deprecated IntervalIndex.from_intervals
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_construction.py
Labels: Deprecate, Interval

#27786 BUG: fix construction of NonConsolidatableBlock with inconsistent ndim
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/getitem.py
Labels: Bug, ExtensionArray

#27770 [BLD] Add script that fails build if git tags do not exist
  .travis.yml
  ci/check_git_tags.sh
  pandas/tests/test_common.py
Labels: Build

#27736 REF: pandas/core/window.py into multiple files
  doc/source/reference/window.rst
  pandas/core/generic.py
  pandas/core/window/__init__.py
  pandas/core/window/common.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_moments.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_window.py
Labels: Refactor, Window

#27788 TST: Add tests for groupby categorical values with axis=1
  pandas/tests/groupby/test_categorical.py
Labels: Categorical, Groupby, Testing

#27792 CLN: remove nested error handling
  pandas/core/internals/blocks.py
Labels: Clean

#27645 BUG: Add mapping for pyqt for successful package installation
  doc/source/whatsnew/v1.0.0.rst
  environment.yml
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
Labels: Dependencies

#27809 CI: remove pytest pins
  ci/deps/azure-36-locale.yaml
  ci/deps/travis-36-slow.yaml
Labels: CI

#27798 DOC: add print statement in to_latex example
  pandas/core/generic.py
Labels: Docs, IO LaTeX

#27819 Backport PR #27809 on branch 0.25.x (CI: remove pytest pins)
  ci/deps/azure-36-locale.yaml
  ci/deps/travis-36-slow.yaml
Labels: CI

#27811 REF: separate method-pinning functions
  pandas/core/ops/__init__.py
  pandas/core/ops/methods.py
Labels: Clean

#27803 REF: Simplify _comp_method_SERIES
  pandas/core/ops/__init__.py
Labels: Clean

#27791 CLN: Assorted Cleanups
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/sparse.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/io/pytables.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/series/test_period.py
Labels: Clean, Internals

#25709 DOC: Add expanded index descriptors for specifying for RangeIndex-as-metadata in Parquet file schema
  doc/source/development/developer.rst
Labels: IO Parquet

#27607 BUG: break reference cycle in Index._engine
  asv_bench/benchmarks/index_object.py
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: Performance

#27818 COMPAT: restore shape for 'invalid' Index with nd array
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/test_base.py
Labels: Compat

#27633 EA: implement+test EA.view
  doc/source/reference/extensions.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/sparse.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_sparse.py
Labels: API Design, ExtensionArray

#27833 Update sample() documentation
  pandas/core/generic.py
Labels: Docs

#27822 Add security policy
  .github/SECURITY.md
Labels: Docs

#27845 CI: pytest, xdist versions
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-37-numpydev.yaml
  ci/deps/azure-macos-35.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/azure-windows-37.yaml
  ci/deps/travis-36-cov.yaml
  ci/deps/travis-37.yaml
Labels: Dependencies

#27826 BUG: Fix groupby quantile segfault
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/test_function.py
Labels: Groupby, Segfault

#27849 CLN: op-->opname in Categorical _cat_compare_op
  pandas/core/arrays/categorical.py
Labels: Clean

#27768 CLN: short-circuit case in Block.replace
  pandas/core/internals/blocks.py
Labels: Clean

#27665 BUG: Allow plotting boolean values
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#27777 Avoid calling S3File.s3
  doc/source/whatsnew/v0.25.1.rst
  pandas/io/parquet.py
  pandas/io/s3.py
Labels: Data IO, IO Parquet

#27855 BUG: add back check for MultiIndex case and take_split_path
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Regression

#27893 DOC: clarify see also for DataFrame.iterrows()
  pandas/core/frame.py
Labels: Docs

#27852 DOC:add append example in to_excel documentation
  pandas/core/generic.py
Labels: Docs

#27871 DOC:Standardize use of "Iterate" and "Iterator"
  pandas/core/frame.py
Labels: Docs

#27769 REF: Make CategoricalIndex comparison defer to Categorical comparison
  pandas/core/arrays/categorical.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/ops/__init__.py
  pandas/tests/indexes/test_category.py
Labels: API Design, Categorical, Numeric

#27810 TST: skip test if running non-installed
  pandas/tests/plotting/test_backend.py
Labels: Testing, Visualization

#27830 CLN: match standardized dispatch logic in IntegerArray
  pandas/core/arrays/integer.py
  pandas/tests/arrays/test_integer.py
Labels: Clean

#27873 requested edit to comparison method
  pandas/core/ops/__init__.py
Labels: Reshaping

#27879 CLN: use invalid_comparison for incorrect case in Index comparison
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_numpy_compat.py
Labels: Reshaping

#27883 CLN: Index.__new__
  pandas/core/frame.py
  pandas/core/indexes/base.py
Labels: Reshaping

#27886 CLN: remove unnecessary validate_for_numeric_binop
  pandas/core/indexes/base.py
  pandas/core/indexes/range.py
Labels: Dtypes

#27889 CLN: remove unnecessary dtype checks
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/tests/arithmetic/test_datetime64.py
Labels: Dtypes

#27846 BUG: boxplot does not work when data has datetime column
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Regression, Visualization

#27851 DOC: Add CoC to the README
  README.md
Labels: Docs

#27890 BUG: fix Sparse reduction
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/arrays/sparse.py
  pandas/tests/series/test_ufunc.py
Labels: Sparse

#27876 DOC:Use of "Yields" for documentation of DataFrame.iteritems()
  pandas/core/frame.py
Labels: Docs

#27840 PERF: Break reference cycle for all Index types
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_base.py
Labels: Index, Performance

#27908 CLN: remove never-True checks in algorithms.py
  pandas/core/algorithms.py
Labels: Clean

#27815 REF: implement should_extension_dispatch
  pandas/core/ops/__init__.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/extension/test_categorical.py
Labels: Internals, Refactor

#27891 CLN: remove unnecessary validate_for_numeric_unary
  pandas/core/indexes/base.py
Labels: Dtypes

#27917 Backport PR #27907 on branch 0.25.x (Revert 37 pins)
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-37-numpydev.yaml
  ci/deps/travis-37.yaml
  environment.yml
  requirements-dev.txt
Labels: CI

#27918 Backport PR #27840 on branch 0.25.x (PERF: Break reference cycle for all Index types)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_base.py
Labels: Performance

#27919 DOC: Fix section reference placement in whatsnew
  doc/source/whatsnew/v1.0.0.rst
Labels: Docs

#27847 TST: parametrize arithmetic tests
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Testing

#27807 BUG: fix+test op(NaT, ndarray), also simplify
  pandas/_libs/tslibs/nattype.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/test_nat.py
Labels: Missing-data

#27896 CLN: remove _maybe_update_attributes
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
Labels: Clean

#27923 CLN: simplify comparison method, docstring cleanups
  pandas/core/computation/common.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/ops/__init__.py
Labels: Clean

#27878 TST: Raise ValueError and suggestion to use header=None if header=-1 is pa…
  doc/source/whatsnew/v0.25.1.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_header.py
Labels: IO CSV

#27932 BUG: Ensure that fill_na in Categorical only replaces null values
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/arrays/categorical.py
  pandas/tests/series/test_missing.py
Labels: Bug, Categorical, Missing-data

#27940 Fix typos in HDFStore docs
  doc/source/user_guide/io.rst
Labels: Docs

#27808 VIS: Fix DataFrame.plot() produces incorrect legend markers when plotting multiple series on the same axis
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_frame.py
Labels: Visualization

#27947 Backport PR #27932 on branch 0.25.x (BUG: Ensure that fill_na in Categorical only replaces null values)
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/arrays/categorical.py
  pandas/tests/series/test_missing.py
Labels: Categorical

#27946 BUG: Merge with readonly arrays
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/hashtable.pyx
  pandas/tests/reshape/merge/test_merge.py
Labels: Reshaping

#27939 CLN: docstrings, circularity in core.computation
  pandas/compat/chainmap.py
  pandas/core/computation/align.py
  pandas/core/computation/common.py
  pandas/core/computation/engines.py
  pandas/core/computation/expr.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/computation/scope.py
Labels: Clean

#27936 REF: implement array_ops
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
Labels: Reshaping

#27933 TST: Asserts all types are caterogical in function fillna with correct error message
  doc/source/whatsnew/v0.25.1.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/tests/arrays/categorical/test_missing.py
Labels: Categorical, Testing

#27948 Backport PR #27946 on branch 0.25.x (BUG: Merge with readonly arrays)
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/hashtable.pyx
  pandas/tests/reshape/merge/test_merge.py
Labels: Compat

#27956 TST: xfail on 37, win
  pandas/tests/groupby/test_categorical.py
Labels: Unreliable Test

#27957 Backport PR #27956 on branch 0.25.x (TST: xfail on 37, win)
  pandas/tests/groupby/test_categorical.py
Labels: CI

#27990 DOC: remove savefig references from the docs v0.7.3
  doc/source/whatsnew/v0.7.3.rst
Labels: Docs

#27920 Updated table with read_fwf()
  doc/source/user_guide/io.rst
Labels: Docs, IO CSV

#27882 BUG: lzma is a required part of python, make it optional
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/parsers.pyx
  pandas/compat/__init__.py
  pandas/io/common.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_pickle.py
  pandas/util/testing.py
Labels: Data IO

#27925 BUG: Help python csv engine read binary buffers
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/common.py
  pandas/tests/io/parser/test_common.py
Labels: IO CSV

#27910 CLN: missing boilerplate in Sparse op
  pandas/core/arrays/sparse.py
  pandas/tests/arrays/sparse/test_arithmetics.py
Labels: Sparse

#27773 BUG: _can_use_numexpr fails when passed large Series
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/computation/expressions.py
  pandas/tests/test_expressions.py
Labels: Numeric, Regression

#28016 TST: fix flaky xfail
  pandas/tests/series/test_analytics.py
Labels: Unreliable Test

#27926 Fix regression in .ix fallback with IntervalIndex
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_ix.py
Labels: Indexing

#27912 REF: use should_extension_dispatch for comparison method
  pandas/core/ops/__init__.py
Labels: ExtensionArray

#27922 CLN: Remove incorrect check, comment, rename
  pandas/core/ops/__init__.py
Labels: Clean

#27916 BUG: fix to_timestamp out_of_bounds
  doc/source/whatsnew/v0.25.1.rst
  pandas/_libs/tslibs/period.pyx
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/scalar/period/test_asfreq.py
Labels: Compat, Period

#27664 issue#27482 - added a check for if obj is instance of type in _isna-new
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/dtypes/missing.py
  pandas/tests/dtypes/test_missing.py
Labels: Missing-data

#27993 PLT: plot('line') or plot('area') produces wrong xlim in xaxis in 0.25.0
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#27481 Correctly re-instate Matplotlib converters
  doc/source/whatsnew/v0.25.1.rst
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/plotting/test_converter.py
Labels: Visualization

#28009 DOC: Corrected file description in read_fwf()
  doc/source/user_guide/io.rst
Labels: Docs, IO CSV

#26419 Fix GroupBy nth Handling with Observed=False
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_categorical.py
Labels: Categorical, Groupby, Missing-data

#27991 DataFrame html repr: also follow min_rows setting
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/frame.py
  pandas/tests/io/formats/test_format.py
Labels: IO HTML, Output-Formatting

#28029 DOC: Change document code prun in a row
  doc/source/user_guide/enhancingperf.rst
Labels: Docs

#28008 [CI] Add pip dependence explicitly
  ci/deps/azure-macos-35.yaml
Labels: CI, Dependencies

#28067 Set SHA for codecov upload
  ci/run_tests.sh
Labels: CI

#28073 DOC: Update whatsnew
  doc/source/whatsnew/v0.25.1.rst
Labels: Docs

#27827 BUG: Fixed groupby quantile for listlike q
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_function.py
Labels: Groupby

#26471 Fix bug where list like object not returning empty Index.
  pandas/core/frame.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/indexing/test_partial.py
Labels: Dtypes, Indexing

#27814 BUG: Series.rename raises error on values accepted by Series construc…
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/series.py
  pandas/tests/series/test_alter_axes.py
Labels: Bug, Indexing, Series

#27650 issue #27642 - timedelta merge asof with tolerance
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Timedelta

#27844 DOC: GroupBy.head()/tail() documentation
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#28082 DOC: Remove alias for numpy.random.randn from the docs
  doc/source/conf.py
  doc/source/whatsnew/v0.10.0.rst
Labels: Docs

#28031 DOC: Fix docstrings lack of punctuation
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
Labels: Docs

#28111 DOC: Start 0.25.2
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v0.25.2.rst
Labels: Docs

#27765 TYPING: more type hints for io.formats.printing
  pandas/io/formats/printing.py
Labels: 2/3 Compat, Typing
