Repository pandas-dev/pandas, pull requests merged in 2019-01, with the labels that each got.

#24517 Make _freq/freq/tz/_tz/dtype/_dtype/offset/_offset all inherit reliably
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: ExtensionArray, Timeseries

#24510 Fix ValueError when reading a Dataframe with HDFStore in Python 3 fro…
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/pytables.py
  pandas/tests/io/data/legacy_hdf/legacy_table_fixed_py2.h5
  pandas/tests/io/test_pytables.py
Labels: 2/3 Compat, IO HDF5

#24527 Implement unique+array parts of 24024
  doc/source/whatsnew/v0.24.0.rst
  pandas/arrays/__init__.py
  pandas/core/algorithms.py
  pandas/core/base.py
  pandas/core/series.py
  pandas/tests/test_algos.py
  pandas/tests/test_base.py
Labels: Refactor, Timeseries

#24520 MAINT: Port _timelex in codebase
  LICENSES/DATEUTIL_LICENSE
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/tslibs/test_parsing.py
Labels: Dependencies, Deprecate, Testing

#24531 Run isort on tests/indexes
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval_new.py
  pandas/tests/indexes/interval/test_interval_range.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/multi/test_astype.py
  pandas/tests/indexes/multi/test_conversion.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/multi/test_missing.py
  pandas/tests/indexes/multi/test_names.py
  pandas/tests/indexes/multi/test_partial_indexing.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexes/multi/test_set_ops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexes/test_frozen.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/indexes/timedeltas/test_astype.py
  pandas/tests/indexes/timedeltas/test_construction.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexes/timedeltas/test_ops.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/indexes/timedeltas/test_setops.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/indexes/timedeltas/test_timedelta_range.py
  pandas/tests/indexes/timedeltas/test_tools.py
  setup.cfg
Labels: Style

#24529 CI: fix db usage in CI
  .travis.yml
  pandas/conftest.py
  pandas/util/_tester.py
  test_fast.bat
  test_fast.sh
Labels: CI

#24530 Run isort
  pandas/tests/frame/common.py
  pandas/tests/frame/conftest.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_apply.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_asof.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_combine_concat.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_convert_to.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/frame/test_duplicates.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_join.py
  pandas/tests/frame/test_missing.py
  pandas/tests/frame/test_mutate_columns.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_operators.py
  pandas/tests/frame/test_period.py
  pandas/tests/frame/test_quantile.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_rank.py
  pandas/tests/frame/test_replace.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/frame/test_sort_values_level_as_str.py
  pandas/tests/frame/test_sorting.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/frame/test_timezones.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/frame/test_validate.py
  setup.cfg
Labels: Style

#24533 CLN: Refactor some sorting code in Index set operations
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/test_operators.py
Labels: Compat, Reshaping

#24534 Make DTI[tz]._values and Series[tz]._values return DTA
  pandas/core/dtypes/concat.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/test_base.py
Labels: Timeseries

#24536 implement fillna from 24024, with fixes and tests
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/missing.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
Labels: Missing-data, Refactor

#19881 Include MultiIndex slice in non-reducing slices
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/io/formats/test_style.py
Labels: IO HTML, Indexing, MultiIndex, Output-Formatting

#24532 Run isort at pandas/tests/io
  pandas/io/formats/style.py
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_eng_formatting.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_printing.py
  pandas/tests/io/formats/test_style.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/formats/test_to_excel.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/formats/test_to_latex.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_normalize.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_readlines.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/io/msgpack/common.py
  pandas/tests/io/msgpack/test_buffer.py
  pandas/tests/io/msgpack/test_except.py
  pandas/tests/io/msgpack/test_extension.py
  pandas/tests/io/msgpack/test_limits.py
  pandas/tests/io/msgpack/test_newspec.py
  pandas/tests/io/msgpack/test_pack.py
  pandas/tests/io/msgpack/test_read_size.py
  pandas/tests/io/msgpack/test_seq.py
  pandas/tests/io/msgpack/test_sequnpack.py
  pandas/tests/io/msgpack/test_subtype.py
  pandas/tests/io/msgpack/test_unpack.py
  pandas/tests/io/msgpack/test_unpack_raw.py
  pandas/tests/io/sas/test_sas.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/sas/test_xport.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_gbq.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_pytables.py
  pandas/tests/io/test_s3.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/test_stata.py
  setup.cfg
Labels: Style

#23255 ENH:Add EA types to read CSV
  doc/source/io.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/parsers.pyx
  pandas/core/arrays/base.py
  pandas/core/arrays/integer.py
  pandas/io/parsers.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/io.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/io/parser/common.py
Labels: ExtensionArray, IO CSV

#24545 TST: move test_non_reducing_slice_on_multiindex
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_indexing.py
Labels: MultiIndex, Testing

#24504 BUG: Ensuring that _get_standard_colors returns num_colors (GH #20585)
  doc/source/whatsnew/v0.24.0.rst
  pandas/plotting/_core.py
  pandas/plotting/_style.py
  pandas/tests/plotting/test_misc.py
Labels: Bug, Visualization

#24543 diff reduction for 24024
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
  pandas/core/ops.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/test_indexing.py
Labels: Clean, Docs, Testing

#24547 BUG: (row) Index Name with to_html(header=False) is not displayed
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/formats/html.py
  pandas/tests/io/formats/data/html/index_named_multi_columns_none.html
  pandas/tests/io/formats/data/html/index_named_standard_columns_none.html
  pandas/tests/io/formats/data/html/index_unnamed_multi_columns_none.html
  pandas/tests/io/formats/data/html/index_unnamed_standard_columns_none.html
  pandas/tests/io/formats/data/html/trunc_df_index_named_multi_columns_none.html
  pandas/tests/io/formats/data/html/trunc_df_index_named_standard_columns_none.html
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML

#24550 TST: isort tests/reshape
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/merge/test_merge_ordered.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/reshape/test_union_categoricals.py
  pandas/tests/reshape/test_util.py
  setup.cfg
Labels: Style

#24551 TST: isort tests/test_*
  pandas/tests/test_algos.py
  pandas/tests/test_base.py
  pandas/tests/test_common.py
  pandas/tests/test_compat.py
  pandas/tests/test_config.py
  pandas/tests/test_downstream.py
  pandas/tests/test_errors.py
  pandas/tests/test_expressions.py
  pandas/tests/test_join.py
  pandas/tests/test_lib.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_nanops.py
  pandas/tests/test_panel.py
  pandas/tests/test_sorting.py
  pandas/tests/test_strings.py
  pandas/tests/test_take.py
  pandas/tests/test_window.py
  setup.cfg
Labels: Style

#24552 DOC: fix some doc build warnings/errors
  doc/source/cookbook.rst
  doc/source/integer_na.rst
  doc/source/io.rst
  doc/source/missing_data.rst
  doc/source/timeseries.rst
  doc/source/tutorials.rst
  doc/source/whatsnew/v0.20.0.rst
Labels: Docs

#24553 TST: isort tests/groupby
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_index_as_string.py
  pandas/tests/groupby/test_nth.py
  pandas/tests/groupby/test_rank.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/test_transform.py
  pandas/tests/groupby/test_value_counts.py
  pandas/tests/groupby/test_whitelist.py
  setup.cfg
Labels: Style

#24024 REF: DatetimeLikeArray
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/generic.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/construction.py
  pandas/core/internals/managers.py
  pandas/io/pytables.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/extension/arrow/bool.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/test_common.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_timezones.py
  pandas/tests/indexes/timedeltas/test_construction.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/test_parquet.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/series/test_block_internals.py
  pandas/tests/test_base.py
  pandas/tests/test_panel.py
  pandas/util/testing.py
Labels: Refactor, Timeseries

#24573 CLN: Follow-ups to #24024
  pandas/core/algorithms.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/io/packers.py
Labels: Clean

#24572 BUG: TypeError with to_html(sparsify=False) and max_cols < len(columns)
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/formats/html.py
  pandas/tests/io/formats/data/html/truncate_multi_index_sparse_off.html
  pandas/tests/io/formats/test_to_html.py
Labels: Bug, IO HTML

#24571 Added Datetime & Timedelta inference to array
  pandas/core/arrays/array_.py
  pandas/tests/arrays/test_array.py
Labels: API Design

#24554 read_sas catches own error #24548
  doc/source/whatsnew/v0.24.0.rst
  pandas/io/sas/sasreader.py
  pandas/tests/io/sas/test_sas.py
Labels: Bug, IO SAS

#21681 Allow merging on object / non-object column
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Dtypes, Reshaping

#24563 TST: isort tests/sparse
  pandas/tests/sparse/frame/conftest.py
  pandas/tests/sparse/frame/test_analytics.py
  pandas/tests/sparse/frame/test_apply.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/frame/test_indexing.py
  pandas/tests/sparse/frame/test_to_csv.py
  pandas/tests/sparse/frame/test_to_from_scipy.py
  pandas/tests/sparse/series/test_indexing.py
  pandas/tests/sparse/series/test_series.py
  pandas/tests/sparse/test_combine_concat.py
  pandas/tests/sparse/test_format.py
  pandas/tests/sparse/test_indexing.py
  pandas/tests/sparse/test_pivot.py
  pandas/tests/sparse/test_reshape.py
  setup.cfg
Labels: Style

#24560 REF: shift ravel in infer_dtype
  pandas/_libs/lib.pyx
  pandas/core/algorithms.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/missing.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/internals/construction.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/tile.py
  pandas/core/series.py
  pandas/core/sorting.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/plotting/_converter.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/series/test_constructors.py
  pandas/tests/test_strings.py
Labels: Dtypes

#24578 Fix import format at pandas/tests/io/dtypes directory
  pandas/tests/dtypes/test_cast.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_concat.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/dtypes/test_missing.py
  setup.cfg
Labels: Style

#24582 REF: put DatetimeBlock adjacent to DatetimeLikeBlockMixin
  pandas/core/internals/blocks.py
Labels: Internals

#24493 ENH: Add additional options to nonexistent in tz_localize
  doc/source/timeseries.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/timestamp/test_timezones.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/test_datetime_values.py
  pandas/tests/series/test_timezones.py
Labels: Enhancement, Timezones

#24585 DOC: Correct description of day_opt in shift_month
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs, Internals, Timeseries

#24584 Fix docstring templates not being filled (#24535)
  pandas/core/indexes/base.py
Labels: Bug, Docs

#24591 DOC: hide warning from arrow about deprecated MultiIndex labels
  doc/source/io.rst
Labels: Docs

#24594 Remove unhittable methods in internals
  pandas/core/internals/blocks.py
  pandas/tests/frame/test_indexing.py
Labels: Clean

#24601 Rename DatetimeArray and TimedeltaArray
  pandas/arrays/__init__.py
  pandas/core/arrays/__init__.py
  pandas/core/arrays/array_.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/indexes/datetimes/test_astype.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/indexes/timedeltas/test_astype.py
  pandas/tests/indexes/timedeltas/test_construction.py
  pandas/tests/internals/test_internals.py
  pandas/tests/test_algos.py
  pandas/tests/test_base.py
  pandas/tests/test_nanops.py
  pandas/util/testing.py
Labels: API Design

#24595 DOC: fix to_numpy explanation for tz aware data
  doc/source/basics.rst
  doc/source/timeseries.rst
  pandas/core/base.py
Labels: Docs

#24587 TST/REF: Add more pytest idiom to tests/tslib
  pandas/tests/tslibs/test_array_to_datetime.py
  pandas/tests/tslibs/test_ccalendar.py
  pandas/tests/tslibs/test_conversion.py
  pandas/tests/tslibs/test_libfrequencies.py
  pandas/tests/tslibs/test_liboffsets.py
  pandas/tests/tslibs/test_normalize_date.py
  pandas/tests/tslibs/test_parse_iso8601.py
  pandas/tests/tslibs/test_parsing.py
  pandas/tests/tslibs/test_period_asfreq.py
  pandas/tests/tslibs/test_timedeltas.py
  pandas/tests/tslibs/test_timezones.py
  pandas/tests/tslibs/test_tslib.py
Labels: Refactor, Testing, Timeseries, Timezones

#24602 DOC: Update doc description for day_opt in offsets
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs, Internals, Timeseries

#24599 Fixed construction / factorization of empty PA and IA
  pandas/core/arrays/interval.py
  pandas/core/arrays/period.py
  pandas/tests/arrays/test_period.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/json/array.py
Labels: Interval, Period

#24597 REF: Simplify quantile, remove reduction from BlockManager
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/nanops.py
Labels: Clean, Numeric

#24579 Fix import format at pandas/tests/io/arithmetic directory
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  setup.cfg
Labels: Style

#24561 See also description formatting
  pandas/_libs/interval.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/strings.py
Labels: Docs

#24606 REF: dispatch Series.quantile to DataFrame, remove ScalarBlock
  pandas/core/internals/__init__.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/resample/test_base.py
Labels: Clean, Numeric

#24605 24024 follow-up: fix incorrectly accepting iNaT in validate_fill_value
  pandas/_libs/algos_common_helper.pxi.in
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/datetimelike.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Clean, Missing-data, Timeseries

#24580 Fix import format at pandas/tests/io/plotting directory
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_groupby.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  setup.cfg
Labels: Style

#24419 REF: clearer Categorical/CategoricalIndex construction
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/category.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/test_category.py
Labels: Categorical, Refactor

#24050 DEPR: deprecate default of skipna=False in infer_dtype
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/lib.pyx
  pandas/core/arrays/array_.py
  pandas/core/reshape/merge.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/series/test_constructors.py
Labels: Dtypes

#24598 DOC: Remove flake8 errors for basics.rst and contributing_docstring.rst
  doc/source/contributing_docstring.rst
Labels: Docs

#23723 DOC: update str.cat example
  doc/source/text.rst
Labels: Docs, Strings

#24609 REF/TST: Add more pytest idiom to test_to_html.py
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML, Testing

#24541 CLN: use idiomatic pandas_dtypes in pandas/dtypes/common.py
  asv_bench/benchmarks/dtypes.py
  asv_bench/benchmarks/pandas_vb_common.py
  doc/source/whatsnew/v0.24.0.rst
  pandas/conftest.py
  pandas/core/arrays/integer.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/frame.py
  pandas/core/indexes/numeric.py
  pandas/core/internals/concat.py
  pandas/core/internals/construction.py
  pandas/tests/dtypes/test_common.py
Labels: Clean, Dtypes

#24604 Fixed PeriodIndex._shallow_copy for i8
  pandas/core/indexes/period.py
  pandas/core/resample.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/resample/test_base.py
Labels: Period

#24621 Fix 32-bit builds by correctly using intp_t instead of int64_t for numpy.searchsorted result
  pandas/_libs/tslibs/conversion.pyx
Labels: Compat

#24640 Fix 32-bit builds by correctly using intp_t instead of int64_t for nmpy.searchsorted result, part 2 (#24621)
  pandas/_libs/tslibs/conversion.pyx
Labels: 32bit

#24557 REF/TST: mixed use of mock/monkeypatch
  pandas/tests/io/test_gbq.py
Labels: Clean, Testing

#24590 DOC: Bump fastparquet version
  ci/deps/azure-macos-35.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/travis-27.yaml
  ci/deps/travis-36-doc.yaml
  ci/deps/travis-36.yaml
  doc/source/install.rst
  doc/source/whatsnew/v0.24.0.rst
  environment.yml
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
  requirements-dev.txt
Labels: Docs, IO Parquet

#24596 DEPR: __array__ for tz-aware Series/Index
  doc/source/api/series.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/dtypes.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/core/nanops.py
  pandas/core/reshape/tile.py
  pandas/core/series.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/series/test_timeseries.py
Labels: Deprecate, Timeseries, Timezones

#24619 CLN: _try_coerce_result, redundant dtypes.missing method
  pandas/_libs/missing.pyx
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/nattype.pyx
  pandas/core/dtypes/missing.py
  pandas/core/internals/blocks.py
  pandas/core/sparse/series.py
  pandas/tests/tslibs/test_api.py
Labels: Clean, Missing-data, Timeseries

#24622 ensure DatetimeTZBlock always gets a DatetimeArray
  pandas/core/internals/blocks.py
  pandas/io/packers.py
Labels: IO Msgpack, Internals, Timezones

#24624 REF/TST: use pytest builtin monkeypatch fixture and remove mock fixture
  pandas/conftest.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/test_gcs.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
Labels: Clean, Testing

#24626 Array api docs
  doc/source/10min.rst
  doc/source/api/arrays.rst
  doc/source/api/index.rst
  doc/source/api/scalars.rst
  doc/source/api/series.rst
  doc/source/basics.rst
  doc/source/categorical.rst
  doc/source/comparison_with_r.rst
  doc/source/groupby.rst
  doc/source/whatsnew/v0.15.0.rst
  pandas/core/arrays/array_.py
  pandas/core/arrays/sparse.py
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#24629 CLN: replace lambdas with named functions so they are labeled in asv
  asv_bench/benchmarks/ctors.py
Labels: Benchmark

#24630 Have Categorical ops defer to DataFrame; broken off of #24282
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_operators.py
Labels: Bug, Categorical

#24631 DOC: Improve DataFrame.align docstring
  pandas/core/generic.py
Labels: Docs

#24633 DOC: update applymap docstring in pandas/core/frame.py
  pandas/core/frame.py
Labels: Docs

#24635 DOC: Fix flake8 errors on whatsnew v0.15*
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v0.15.1.rst
  doc/source/whatsnew/v0.15.2.rst
  setup.cfg
Labels: Docs

#24637 REF: io/formats/html.py (and io/formats/format.py)
  pandas/io/formats/format.py
  pandas/io/formats/html.py
Labels: IO HTML, Output-Formatting

#24638 DOC: parallel safe
  doc/sphinxext/contributors.py
Labels: Docs

#24639 CLN: Parameterize test cases
  pandas/tests/plotting/test_converter.py
Labels: Testing

#24642 DOC: fix warnings in docstrings examples for deprecated functions
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
Labels: Deprecate, Docs

#24636 Fix DeprecationWarning: invalid escape sequence in versioneer.py
  versioneer.py
Labels: Compat

#24628 catch complex nan in util.is_nan, de-dup+optimize libmissing, tests
  pandas/_libs/missing.pyx
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/util.pxd
  pandas/tests/dtypes/test_missing.py
Labels: Complex, Missing-data

#24644 CLN: remove redundant mac wheel-build code
  setup.py
Labels: Build

#24646 Repr for Integer and Pandas Dtypes
  pandas/core/arrays/integer.py
  pandas/core/arrays/numpy_.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/arrays/test_numpy.py
Labels: Output-Formatting

#23593 API: consistent __array__ for datetime-like ExtensionArrays
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/extension/base/interface.py
Labels: ExtensionArray

#24643 Make DTA/TDA/PA return NotImplemented on comparisons
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/tests/arithmetic/test_period.py
Labels: Internals

#24266 EHN: Add filename to FileNotFoundError
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/test_common.py
Labels: Data IO, Enhancement, Error Reporting

#24494 BUG-19214 int categoricals are formatted as ints
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/reshape/test_concat.py
Labels: Categorical, Output-Formatting

#24648 CI/TST: Check that unittest.mock is not being used in testing
  ci/code_checks.sh
Labels: CI

#24048 Deprecate series.nonzero (GH18262)
  doc/source/api/series.rst
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/io/stata.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/series/test_missing.py
Labels: Deprecate

#24647 PERF: 10x speedup in Series/DataFrame construction for lists of ints
  asv_bench/benchmarks/ctors.py
  pandas/_libs/lib.pyx
Labels: Performance

#24649 DOC: whatsnew & linked edits
  doc/source/advanced.rst
  doc/source/api/arrays.rst
  doc/source/basics.rst
  doc/source/whatsnew/v0.24.0.rst
Labels: Docs

#24634 TST: Fixed timezone issues post DatetimeArray refactor
  doc/source/whatsnew/v0.24.0.rst
  pandas/tests/frame/test_reshape.py
  pandas/tests/indexes/datetimes/test_astype.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Timezones

#24650 DOC: Fixing more doc warings and wrong .. code-block :: directive (space before colon)
  ci/code_checks.sh
  doc/source/api/arrays.rst
  doc/source/dsintro.rst
  doc/source/indexing.rst
  doc/source/io.rst
  doc/source/whatsnew/v0.12.0.rst
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v0.16.0.rst
  doc/source/whatsnew/v0.16.1.rst
  doc/source/whatsnew/v0.17.0.rst
  doc/source/whatsnew/v0.17.1.rst
  doc/source/whatsnew/v0.18.0.rst
  doc/source/whatsnew/v0.19.0.rst
Labels: Clean, Docs

#24654 TST/CI: disable hypothesis deadline for test_tick_add_sub
  pandas/tests/tseries/offsets/test_ticks.py
Labels: CI

#24184 DOC: Fix docstring of window.Expanding/Rolling.apply and document *args and **kwargs
  pandas/core/window.py
Labels: Docs

#24652 REF: clear out a bunch of algos, de-duplicate a bunch of core.missing
  pandas/_libs/algos.pyx
  pandas/_libs/algos_common_helper.pxi.in
  pandas/_libs/index.pyx
  pandas/_libs/index_class_helper.pxi.in
  pandas/core/missing.py
  pandas/tests/indexing/test_indexing_engines.py
  pandas/tests/test_algos.py
Labels: Clean, Missing-data

#24664 BLD: Include tslibs src
  setup.py
Labels: Build

#24665 Have DTA._simple_new take dtype instead of tz
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals/blocks.py
  pandas/tseries/offsets.py
Labels: Internals, Timeseries

#24655 STY: use pytest.raises context syntax
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/json/test_normalize.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/io/msgpack/test_except.py
  pandas/tests/io/msgpack/test_limits.py
  pandas/tests/io/msgpack/test_obj.py
  pandas/tests/io/msgpack/test_pack.py
Labels: Refactor, Testing

#24651 REF: io/formats/html.py (and io/formats/format.py)
  pandas/io/formats/format.py
  pandas/io/formats/html.py
Labels: IO HTML, Refactor

#24660 API: Datetime/TimedeltaArray from to_datetime
  pandas/core/arrays/array_.py
  pandas/tests/arrays/test_array.py
  pandas/tests/series/test_internals.py
Labels: Dtypes, ExtensionArray, Timeseries

#24398 API: Add dtype parameter to Categorical.from_codes
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/indexes/test_category.py
Labels: API Design, Categorical

#24669 REF: move templated index.pyx code to non-template
  pandas/_libs/index.pyx
  pandas/_libs/index_class_helper.pxi.in
Labels: Clean

#24680 BUG: Fix segfault in Categorical.set_categories
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_api.py
Labels: Bug, Categorical, Segfault

#24663 BUG: fix to_datetime failing to raise on mixed tznaive/tzaware datetimes
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/indexes/datetimes/test_construction.py
Labels: Timeseries, Timezones

#24676 STY: use pytest.raises context syntax
  pandas/tests/io/msgpack/test_sequnpack.py
  pandas/tests/io/msgpack/test_unpack.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_packers.py
  pandas/tests/io/test_stata.py
Labels: Data IO, Refactor, Testing

#24679 DOC: Fixes to the whatsnew structure
  doc/source/index.rst.template
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v0.4.x.rst
Labels: Docs

#24214 PERF: expand asv benchmark coverage
  asv_bench/benchmarks/algorithms.py
  asv_bench/benchmarks/categoricals.py
  asv_bench/benchmarks/join_merge.py
  asv_bench/benchmarks/pandas_vb_common.py
  asv_bench/benchmarks/plotting.py
  asv_bench/benchmarks/reindex.py
  asv_bench/benchmarks/reshape.py
  asv_bench/benchmarks/series_methods.py
  asv_bench/benchmarks/timeseries.py
  asv_bench/benchmarks/timestamp.py
Labels: Benchmark

#24666 Ensure TDA.__init__ validates freq
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Clean, Timedelta

#24692 DOC: Updated sample CI image in contributing docs
  doc/source/_static/ci.png
Labels: Docs

#24693 CLN: Removing find_undoc_args.py, validate_docstrings.py implements the same
  scripts/find_undoc_args.py
Labels: Clean

#24701 Update test_ticks.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: CI

#24695 remove unused kwarg
  pandas/core/internals/blocks.py
Labels: Internals

#24694 fix interpreting int as second--> nano
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/series/test_missing.py
Labels: Deprecate, Missing-data, Timedelta

#24717 BUG: Fix DataFrame.astype(ExtensionDtype) with duplicate column names
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_dtypes.py
Labels: Bug, Dtypes, ExtensionArray

#24719 CLN: replace %s syntax with .format in pandas.io
  pandas/io/packers.py
  pandas/io/pytables.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sql.py
  pandas/io/stata.py
Labels: Style

#24708 Revert handling of i8values to DatetimeIndex
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/reshape/tile.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/indexes/datetimes/test_astype.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/test_base.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/test_base.py
Labels: Timeseries, Timezones

#24723 TimedeltaArray freq validation without _from_sequence
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Timedelta

#24738 DOC: Small whatsnew fixes
  doc/source/whatsnew/v0.24.0.rst
Labels: Docs

#24710 implement Tick division, fix Timedelta.__cmp__ tick
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/tseries/offsets.py
Labels: Frequency, Timedelta

#24743 PERF: 3x speedup in Series of dicts with datetime keys by not having error message scale with input
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Dtypes, Performance, Timeseries

#24744 DOC: Use backticks instead of quotes
  doc/source/whatsnew/v0.24.0.rst
Labels: Docs

#24745 CLN: More isort
  pandas/tests/computation/test_compat.py
  pandas/tests/computation/test_eval.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/internals/test_internals.py
  pandas/tests/tools/test_numeric.py
  setup.cfg
Labels: Clean, Style

#24731 Change MultiIndex repr (labels -> codes)
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/strings.py
  pandas/tests/util/test_assert_index_equal.py
Labels: MultiIndex, Output-Formatting

#24714 ModuleNotFoundError in in_interactive_session
  pandas/io/formats/console.py
Labels: Compat

#24741 CLN/TST: indexing/multiindex/test_getitem.py
  pandas/tests/indexing/multiindex/test_getitem.py
  pandas/tests/indexing/multiindex/test_iloc.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/multiindex/test_setitem.py
Labels: Clean, Testing

#24756 CI: Pinning flake8-rst, last version raises incorrect errors
  environment.yml
  requirements-dev.txt
Labels: CI, Docs

#24747 PERF: speed up .ix by moving deprecation string out of __init__
  pandas/core/indexing.py
Labels: Indexing, Performance

#24750 STY: use pytest.raises context syntax (series/indexing/*)
  pandas/tests/series/indexing/test_alter_index.py
  pandas/tests/series/indexing/test_boolean.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_loc.py
  pandas/tests/series/indexing/test_numeric.py
Labels: Style

#24746 CI: isort ci
  ci/code_checks.sh
  setup.cfg
Labels: CI, Clean, Style

#24758 COMPAT: Properly encode filenames in read_csv
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/test_common.py
Labels: 2/3 Compat, Bug, Compat, IO CSV, Python 3.6, Unicode, Windows

#24771 API: Added is_extension_array_dtype
  doc/source/api/general_utility_functions.rst
  pandas/core/dtypes/api.py
  pandas/core/dtypes/common.py
  pandas/tests/api/test_types.py
Labels: ExtensionArray

#24780 DOC: IntervalArray and IntervalIndex minor doc fixes
  doc/source/api/indexing.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
Labels: Docs, Interval

#22805 BUG: Hashtable size hint cap
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/tests/test_algos.py
Labels: Bug, Groupby, Internals

#24774 Update DataFrame.eq docstring
  pandas/core/ops.py
Labels: Docs

#24772 Fix flake8 issues in doc/source/enhancingperf.rst
  doc/source/enhancingperf.rst
  setup.cfg
Labels: Style

#24754 CategoricalAccessor.categorical removed in 0.24.0rc1 #24751
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_warnings.py
  pandas/tests/series/test_api.py
  pandas/tests/test_config.py
Labels: Categorical, Deprecate

#24792 PERF: avoid object-dtype comparisons
  pandas/core/internals/blocks.py
  pandas/util/testing.py
Labels: Dtypes, Performance

#24759 BUG: DataFrame.min/max with axis=1 and uniform datetime64[ns, tz] types does not return NaNs
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/tests/reductions/test_reductions.py
Labels: Bug, Timezones

#24776 TST/REF: Collect Reduction, Arithmetic Tests
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexes/test_range.py
  pandas/tests/indexes/timedeltas/test_ops.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/test_nanops.py
Labels: Testing

#24707 Updated with match
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_pytables.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/test_datetime_values.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/test_config.py
Labels: Data IO, Testing

#24802 Revert unnecessary changes from 22019
  doc/source/whatsnew/v0.24.0.rst
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/reshape/test_pivot.py
Labels: Docs

#24799 Whatsnew reorganization
  doc/source/whatsnew/v0.24.0.rst
Labels: Docs

#24812 STY: use pytest.raises context syntax (series)
  pandas/tests/series/test_alter_axes.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_combine_concat.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_internals.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_rank.py
  pandas/tests/series/test_replace.py
  pandas/tests/series/test_sorting.py
  pandas/tests/series/test_timeseries.py
Labels: Style, Testing

#24810 TST/CLN: follow-up to #24750
  pandas/tests/series/indexing/test_boolean.py
Labels: Clean, Testing

#24793 Avoid unnecessary use of _coerce_scalar_to_timedelta_type
  pandas/core/computation/pytables.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/frame/test_analytics.py
Labels: Clean, Internals

#24811 BUG: Offset-based rolling window, with only one raw in dataframe and closed='left', max and min functions make python crash
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/window.pyx
  pandas/tests/test_window.py
Labels: Bug, Window

#24826 TST: remove patches to pandas.util.testing.N
  pandas/tests/indexing/multiindex/conftest.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/series/test_alter_axes.py
  pandas/tests/test_multilevel.py
Labels: Testing

#24821 use Timedelta instead of convert_to_timedelta64
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/tools/timedeltas.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Timedelta

#24830 Question regarding Series.argsort documentation #24816
  pandas/core/series.py
Labels: Docs

#24521 ENH: Add sort parameter to set operations for some Indexes and adjust…
  doc/source/whatsnew/v0.24.0.rst
  pandas/_libs/lib.pyx
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/io/pytables.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_set_ops.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_range.py
Labels: API Design, Reshaping

#24762 DOC: update DF.set_index
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_alter_axes.py
Labels: Docs

#24834 REF remove unused imports from tseries.frequencies; update imports elsewhere
  pandas/core/arrays/period.py
  pandas/core/indexes/period.py
  pandas/core/resample.py
  pandas/plotting/_converter.py
  pandas/plotting/_timeseries.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/tseries/test_frequencies.py
  pandas/tseries/frequencies.py
Labels: Clean, Frequency

#24733 BUG-24212 fix usage of Index.take in pd.merge
  doc/source/whatsnew/v0.24.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Bug, Reshaping

#24735 PERF: fix some of .clip() performance regression by using numpy arrays where possible
  asv_bench/benchmarks/series_methods.py
  pandas/core/generic.py
Labels: Dtypes, Performance

#24828 STY: use pytest.raises context syntax (groupby)
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_transform.py
Labels: Clean, Style, Testing

#24847 ERR/TST: Add pytest idiom to dtypes/test_cast.py
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/__init__.py
  pandas/tests/dtypes/cast/test_construct_from_scalar.py
  pandas/tests/dtypes/cast/test_construct_ndarray.py
  pandas/tests/dtypes/cast/test_construct_object_arr.py
  pandas/tests/dtypes/cast/test_convert_objects.py
  pandas/tests/dtypes/cast/test_downcast.py
  pandas/tests/dtypes/cast/test_find_common_type.py
  pandas/tests/dtypes/cast/test_infer_datetimelike.py
  pandas/tests/dtypes/cast/test_infer_dtype.py
  pandas/tests/dtypes/test_cast.py
Labels: Clean, Error Reporting, Refactor, Testing
