Repository pandas-dev/pandas, pull requests merged in 2019-07, with the labels that each got.

#27144 ERR/TST: Raise NotImplementedError in to_hdf for extension dtypes in MultiIndex
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/pytables.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/io/pytables/test_pytables.py
  pandas/tests/reshape/test_pivot.py
Labels: Error Reporting, IO HDF5, Testing, Timezones

#27163 CI: Install moto from conda-forge
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-windows-37.yaml
  ci/deps/travis-36-cov.yaml
  ci/deps/travis-36-locale.yaml
  pandas/core/indexes/base.py
Labels: CI

#26409 DEPR: deprecate get_values
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/lib.pyx
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse.py
  pandas/core/dtypes/concat.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/multi.py
  pandas/core/internals/blocks.py
  pandas/core/ops.py
  pandas/core/series.py
  pandas/core/sparse/frame.py
  pandas/core/sparse/series.py
  pandas/io/formats/format.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/series/test_api.py
  pandas/util/testing.py
Labels: Deprecate

#27044 ENH: Exclude nuisance columns from result of window functions
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/window.py
  pandas/tests/test_window.py
Labels: Dtypes, Enhancement, Window

#27127 Slicing an index with DateTime throws AttributeError: 'int' object has no attribute 'stop'
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_indexing.py
Labels: Bug, Timeseries

#27156 DOC: mention that float_format can be a function, not just a string
  pandas/core/generic.py
Labels: Docs, IO LaTeX

#23293 Add __array_ufunc__ to Series / Array
  doc/source/development/extending.rst
  doc/source/getting_started/dsintro.rst
  doc/source/user_guide/computation.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/sparse.py
  pandas/core/ops.py
  pandas/core/series.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_ufunc.py
Labels: API Design, Numeric

#27110 BUG: Fix indexing on DatetimeBlock
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/indexing/test_datetime.py
Labels: Bug, Indexing, Timezones

#27168 CLN: True option in Series.groupby.nth(dropna=)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_nth.py
Labels: Clean

#27140 BUG: Fix empty closed window issue with rolling min and max
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/window.pyx
  pandas/tests/test_window.py
Labels: Window

#17753 API: change IntervalIndex.contains to work elementwise
  doc/source/reference/arrays.rst
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexing.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_range.py
Labels: Deprecate, Indexing, Interval

#27157 Fix build warnings
  pandas/_libs/groupby.pyx
  pandas/_libs/hashtable.pxd
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/_libs/index.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/src/parser/tokenizer.c
Labels: Build

#27171 CLN: convert argument in .take method
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/sparse/series/test_series.py
Labels: Clean

#27175 ERR: Raise on duplicates names in read_csv
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.19.0.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_dtypes.py
  pandas/tests/io/parser/test_mangle_dupes.py
Labels: Clean, Error Reporting, IO CSV

#27173 BUG: Fix Index constructor with mixed closed Intervals
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/indexes/test_base.py
Labels: Bug, Index, Interval

#27151 CLN: separate raising from non-raising parts of method
  pandas/core/internals/blocks.py
  pandas/tests/internals/test_internals.py
Labels: Clean, Internals

#27100 API: Implement new indexing behavior for intervals
  ci/code_checks.sh
  doc/source/user_guide/advanced.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexing.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/frame/test_missing.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval_new.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/interval/test_interval_new.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/reshape/test_concat.py
Labels: API Design, Indexing, Interval

#27196 TST: handle inconsistent ordering in resample_api compat test
  ci/deps/azure-36-locale.yaml
  ci/deps/travis-36-slow.yaml
  pandas/tests/resample/test_resample_api.py
Labels: Testing

#26403 DEPR: Deprecate ordered=None for CategoricalDtype
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/dtypes.py
  pandas/core/internals/construction.py
  pandas/core/series.py
  pandas/io/packers.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/test_category.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_dtypes.py
Labels: Categorical, Deprecate, Dtypes

#26876 Enhancement Add max_level param to json_normalize
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/json/normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON

#27193 CLN: fix cython build warning
  pandas/_libs/tslib.pyx
Labels: Build

#27145 DEPR: DataFrame.get_dtype_counts
  doc/source/getting_started/basics.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v0.10.1.rst
  doc/source/whatsnew/v0.11.0.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/computation/expressions.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_combine_concat.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_missing.py
  pandas/tests/frame/test_mutate_columns.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/frame/test_timezones.py
  pandas/tests/generic/test_generic.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/io/pytables/test_pytables.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/sparse/frame/test_frame.py
Labels: Deprecate

#27191 DOC: Started 0.25.1 whatsnew
  doc/source/whatsnew/v0.24.1.rst
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.1.rst
Labels: Docs

#27184 Object dtype for empty describe
  pandas/core/generic.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Dtypes

#27188 DOC: whatsnew for array_ufunc
  doc/source/whatsnew/v0.25.0.rst
Labels: Docs

#22318 DEPR: join_axes-kwarg in pd.concat
  doc/source/user_guide/merging.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/reshape/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Deprecate, Reshaping

#27200 CLN: more blocks code out from try/excepts
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Clean, Internals

#27194 REGR: Group empty Series
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_grouping.py
Labels: Groupby, Regression

#27192 improve test for timestamp addition/subtraction
  pandas/tests/scalar/timestamp/test_arithmetic.py
Labels: Frequency, Testing

#26097 BUG: _convert_and_box_cache raise ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/index.py
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
Labels: Timeseries

#27198 DEPR: Deprecate outer ufunc in Series.__array_ufunc__
  doc/source/getting_started/dsintro.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/series.py
  pandas/tests/series/test_ufunc.py
Labels: Deprecate

#27207 BUG: Fixup bench for deprecation
  asv_bench/benchmarks/categoricals.py
Labels: Performance

#27101 CLN/DEPR: Final panel removal
  doc/source/getting_started/basics.rst
  doc/source/whatsnew/v0.11.0.rst
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v0.15.2.rst
  pandas/__init__.py
  pandas/core/api.py
  pandas/core/dtypes/generic.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/panel.py
  pandas/io/packers.py
  pandas/tests/api/test_api.py
Labels: Panel

#27009 PLT: Cleaner plotting backend API, and unify Series and DataFrame accessors
  doc/source/development/extending.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/plotting/__init__.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/__init__.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
Labels: Blocker, Clean, Visualization

#27137 API: ExtensionArray.argsort places the missing value at the end
  asv_bench/benchmarks/algorithms.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/sorting.py
  pandas/tests/extension/base/methods.py
  pandas/tests/frame/test_sorting.py
Labels: ExtensionArray, Missing-data

#27199 DEPR: make Categorical.ravel() return Categorical
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/tests/extension/base/base.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_sparse.py
Labels: Categorical, Deprecate

#25427 Class to read OpenDocument Tables
  ci/deps/travis-36-cov.yaml
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/compat/_optional.py
  pandas/core/config_init.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odfreader.py
  pandas/tests/io/data/blank.ods
  pandas/tests/io/data/blank_with_header.ods
  pandas/tests/io/data/invalid_value_type.ods
  pandas/tests/io/data/test1.ods
  pandas/tests/io/data/test2.ods
  pandas/tests/io/data/test3.ods
  pandas/tests/io/data/test4.ods
  pandas/tests/io/data/test5.ods
  pandas/tests/io/data/test_converters.ods
  pandas/tests/io/data/test_index_name_pre17.ods
  pandas/tests/io/data/test_multisheet.ods
  pandas/tests/io/data/test_squeeze.ods
  pandas/tests/io/data/test_types.ods
  pandas/tests/io/data/testdateoverflow.ods
  pandas/tests/io/data/testdtype.ods
  pandas/tests/io/data/testmultiindex.ods
  pandas/tests/io/data/testskiprows.ods
  pandas/tests/io/data/times_1900.ods
  pandas/tests/io/data/times_1904.ods
  pandas/tests/io/data/writertable.odt
  pandas/tests/io/excel/conftest.py
  pandas/tests/io/excel/test_odf.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_xlrd.py
Labels: Data IO, Enhancement

#27095 Shorter truncated Series/DataFrame repr: introduce min_rows
  doc/source/user_guide/options.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/config_init.py
  pandas/core/frame.py
  pandas/core/series.py
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting

#27221 ENH: Implement is_empty property for Interval structures
  doc/source/reference/arrays.rst
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/interval.pyx
  pandas/core/arrays/interval.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/scalar/interval/test_interval.py
Labels: Enhancement, Interval

#27216 DOC: Add 0.25.0 to whatsnew index
  doc/source/whatsnew/index.rst
Labels: Docs

#26043 PERF: changed default value of cache parameter to True in to_datetime function
  asv_bench/benchmarks/io/csv.py
  asv_bench/benchmarks/timeseries.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: API Design, Performance, Timeseries

#27187 CLN: simplify MultiIndex._shallow_copy
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_equivalence.py
Labels: Clean, MultiIndex

#27231 STYLE: add black makefile & skip some dirs
  Makefile
  ci/code_checks.sh
Labels: Style

#27238 REF: make ops a directory
  pandas/core/ops/__init__.py
  pandas/core/ops/roperator.py
Labels: Clean, Internals

#27243 BUG: merge_asof with multiple by columns with tz
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Timezones

#27236 CLN: remove never-used branch from Series ops
  pandas/core/ops/__init__.py
Labels: Clean, Internals

#27223 CLN: Move code outside of try/except blocks
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#27257 REF: ops.missing
  pandas/core/indexes/base.py
  pandas/core/missing.py
  pandas/core/ops/__init__.py
  pandas/core/ops/missing.py
  pandas/tests/indexing/test_coercion.py
Labels: Algos, Refactor

#27201 Misleading error for pd.read_msgpack
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/generic.py
  pandas/io/packers.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_packers.py
Labels: Error Reporting, IO Msgpack

#27260 CLN: remove unnecessary fastpath, transpose kwargs in internals
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_internals.py
Labels: Clean, Internals

#27239 BUG: Fix divmod fill value, closes #26987
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/ops/__init__.py
  pandas/core/ops/missing.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/sparse/series/test_series.py
Labels: Bug, Missing-data

#27136 PERF, BENCH: Fix performance issue when indexing into non-unique DatetimeIndex/PeriodIndex.
  asv_bench/benchmarks/categoricals.py
  asv_bench/benchmarks/indexing.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/period.py
  pandas/tests/series/indexing/test_datetime.py
Labels: Performance, Period, Timeseries

#27269 CLN: Remove unused SparseArray code
  pandas/core/arrays/sparse.py
  pandas/core/ops/__init__.py
Labels: Clean, Sparse

#27276 TST/CLN: remove try block from test_indexing_over_size_cutoff_period_index
  pandas/tests/series/indexing/test_datetime.py
Labels: Clean, Testing

#27277 TST/CLN: remove try block from tests/test_strings.py::TestStringMetho…
  pandas/tests/test_strings.py
Labels: Clean, Testing

#27268 REF: Avoid dispatching Series ops to pd.Index
  pandas/core/ops/__init__.py
Labels: Clean, Missing-data, Timedelta

#27259 COMPAT: catch InvalidIndexError in base Indexer getitem
  pandas/core/indexing.py
Labels: Dependencies, Indexing

#26875 BUG: from_dict ignored order of OrderedDict (#8425)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: DataFrame, Reshaping

#27070 Typing: Support New Mypy Semantic Analyzer
  pandas/core/arrays/interval.py
  pandas/core/indexes/timedeltas.py
  pandas/io/json/__init__.py
  pandas/io/json/_json.py
  pandas/io/json/_normalize.py
  pandas/io/json/_table_schema.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_normalize.py
  pandas/tests/io/json/test_readlines.py
Labels: Typing

#27233 DOC: update contributing guidelines for black
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  doc/source/development/contributing.rst
Labels: Docs

#27278 BUG: Fix+test division by negative zero
  pandas/core/arrays/integer.py
  pandas/core/ops/missing.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/io/pytables/test_pytables.py
  setup.cfg
Labels: Missing-data

#27154 BUG: fix KeyError with list of a single, missing, element
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/multiindex/test_slice.py
Labels: Indexing, MultiIndex

#27265 DOC: Clarify column type for 'on' parameter of rolling
  pandas/core/window.py
Labels: Docs, Reshaping

#27287 Add comment and test for geopandas compat fix (GH27259)
  pandas/core/indexing.py
  pandas/tests/test_downstream.py
Labels: Indexing, Testing

#27300 ENH: maybe_convert_objects seen NaT speed-up
  asv_bench/benchmarks/algorithms.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/lib.pyx
Labels: Performance, Timedelta

#27301 CLN: assorted cleanups
  pandas/core/computation/expressions.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/ops/__init__.py
  pandas/tests/computation/test_eval.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/series/test_arithmetic.py
Labels: Clean

#27296 CLN: checks instead of try/except
  pandas/core/internals/blocks.py
Labels: Clean

#27294 CLN: Remove unused vars in roll_window
  pandas/_libs/window.pyx
Labels: Clean, Window

#27307 STYLE: fix line length check of flake8
  pandas/core/groupby/grouper.py
  pandas/core/indexing.py
  pandas/io/parsers.py
  pandas/tests/io/json/test_normalize.py
  pandas/tests/util/test_hashing.py
  setup.cfg
Labels: Style

#27291 BUG: Incorrect Message in KeyError with MultiIndex
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_getitem.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Bug, Error Reporting, Indexing, MultiIndex

#27304 PERF: Suppress ix warnings benchmarks
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/indexing.py
  asv_bench/benchmarks/io/msgpack.py
  pandas/core/generic.py
Labels: Deprecate, Performance

#27284 BUG: Fix CategoricalIndex.__contains__ with non-hashable, closes #21729
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/frame.py
  pandas/core/indexes/category.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/indexes/test_category.py
Labels: Bug, Categorical, Indexing

#27245 TST: add tests to validate margin results for pivot (#25815)
  pandas/tests/reshape/test_pivot.py
Labels: Categorical, Reshaping, Testing

#27271 TST: parametrize sparse array arithmetic tests
  pandas/conftest.py
  pandas/tests/arrays/sparse/test_arithmetics.py
Labels: Sparse, Testing

#27289 DOC: Small whatsnew fixes
  doc/source/whatsnew/v0.25.0.rst
Labels: Docs

#27298 REF: check can_hold_element instead of try/except
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#27229 REF: separate indexer utilities from indexing.py
  pandas/core/algorithms.py
  pandas/core/indexers.py
  pandas/core/indexes/base.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/indexing/test_indexing.py
Labels: Clean, Indexing, Internals

#27317 BUG: Preserve CategoricalDtype._ordered_from_sentinel with pickle
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/series/test_io.py
Labels: Bug, Categorical

#27302 check early for non-scalar default_fill_value
  pandas/core/sparse/frame.py
  pandas/tests/sparse/frame/test_frame.py
Labels: Error Reporting, Sparse

#27305 CLN: Split test_window.py
  pandas/tests/window/__init__.py
  pandas/tests/window/conftest.py
  pandas/tests/window/test_dtypes.py
  pandas/tests/window/test_pairwise.py
  pandas/tests/window/test_timeseries_window.py
  pandas/tests/window/test_window.py
Labels: Clean, Testing, Window

#27303 BUG: appending a Timedelta to Series incorrectly casts to integer
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Timedelta

#26114 CLN: replace usage internally of .iteritems with .items
  asv_bench/benchmarks/frame_methods.py
  doc/source/development/contributing_docstring.rst
  doc/source/getting_started/basics.rst
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/multi.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/core/sparse/frame.py
  pandas/core/strings.py
  pandas/core/util/hashing.py
  pandas/io/formats/style.py
  pandas/io/json/_json.py
  pandas/io/json/_table_schema.py
  pandas/io/msgpack/_packer.pyx
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_operators.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/io/test_html.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_io.py
  pandas/tests/test_base.py
Labels: Clean

#27330 TST: suppress rolling warnings correctly for raw=
  pandas/tests/window/test_window.py
Labels: CI, Testing

#27321 BUG: Consistent division by zero behavior for Index/Series
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/ops/__init__.py
  pandas/core/ops/missing.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/series/test_series.py
Labels: Compat, Missing-data

#27322 BUG: fix inserting tz-aware datetime to Series, closes #12862
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/series.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Bug, Indexing, Timezones

#27275 ENH: Raise ValueError for unsupported Window functions
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/base.py
  pandas/tests/window/test_window.py
Labels: Window

#27341 Accept empty dataframes in DataFrame.to_parquet
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Compat, IO Parquet

#27331 BUG: fix+test assigning invalid NAT-like to DTA/TDA/PA
  pandas/core/arrays/datetimelike.py
  pandas/core/dtypes/missing.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Missing-data, Period, Timedelta, Timeseries

#27336 CLN: remove Hypothesis warning during test
  pandas/conftest.py
Labels: CI, Testing

#27355 add type annotations to io\formats\html.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
Labels: Typing

#27354 TST/CLN: Add message checks to raises KeyError tests
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_duplicates.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_mutate_columns.py
  pandas/tests/generic/test_generic.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval_new.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/indexes/multi/test_partial_indexing.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_range.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/interval/test_interval_new.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/pytables/test_pytables.py
Labels: Testing

#27349 CLN: Collapse private ._take implementation into the public take method
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/indexing.py
  pandas/core/series.py
Labels: Clean

#27348 CLN: Split test_window.py further
  pandas/tests/window/common.py
  pandas/tests/window/test_api.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_grouper.py
  pandas/tests/window/test_moments.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_window.py
Labels: Clean, Testing

#27346 CLN: revisit build warnings in cython templates
  pandas/_libs/groupby_helper.pxi.in
  pandas/_libs/hashtable_class_helper.pxi.in
Labels: Clean

#27359 TST: add test for multiindex partial indexing both axis
  pandas/tests/indexing/multiindex/test_partial.py
Labels: Indexing, MultiIndex, Testing

#27352 Dispatch Index ops to Series
  pandas/core/indexes/base.py
  pandas/core/ops/__init__.py
  pandas/core/ops/missing.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/indexes/test_common.py
Labels: Algos, Refactor

#27351 CLN/REF: indexing typing, prune unreachable branches
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/series.py
Labels: Clean, Typing

#27362 TST: add test for series list indexing with missing values
  pandas/tests/indexing/test_loc.py
Labels: Indexing, Testing

#27361 REF: separate out docstrings.py
  pandas/core/ops/__init__.py
  pandas/core/ops/docstrings.py
Labels: Docs

#27360 adds non regression test for GH27358
  pandas/tests/frame/test_constructors.py
Labels: Testing

#27366 Add small docs about xlsxwriter in user guide
  doc/source/user_guide/io.rst
Labels: Docs, IO Excel

#27393 Added annotations to util._decorators
  pandas/util/_decorators.py
Labels: Typing

#27371 Fix compilation warnings
  pandas/_libs/internals.pyx
  pandas/_libs/tslibs/c_timestamp.pyx
  pandas/_libs/window.pyx
Labels: Clean

#27375 BUG: Fix take with read-only indexer, closes #17192
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/algos_take_helper.pxi.in
  pandas/tests/indexing/test_indexing.py
Labels: Bug, Indexing

#25164 DOC: update file path descriptions in IO docstrings
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/packers.py
  pandas/io/parquet.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/io/sas/sasreader.py
  pandas/io/stata.py
Labels: Docs, IO Parquet

#27279 DOC: Explicitly include "private" ExtensionArray methods in API docs
  doc/source/reference/extensions.rst
  pandas/core/arrays/base.py
  pandas/core/indexes/category.py
Labels: Docs, ExtensionArray

#27401 disallow np.timedelta64 in is_integer
  pandas/_libs/tslibs/util.pxd
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
  pandas/tests/dtypes/test_inference.py
Labels: Dtypes

#27402 Easy warning fixups for mypy
  pandas/core/computation/pytables.py
  pandas/io/json/_normalize.py
Labels: Clean, Typing

#27274 Added 32-bit build
  ci/azure/posix.yml
  ci/deps/azure-36-32bit.yaml
  ci/setup_env.sh
  pandas/tests/groupby/test_grouping.py
Labels: Build

#27347 Fix _can_hold_element for datetimelike blocks
  pandas/core/dtypes/missing.py
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#27376 Assorted cleanups
  pandas/_libs/src/klib/khash_python.h
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/core/internals/managers.py
Labels: Clean, Internals

#27378 TST: add NaN tests for all data types (#12535)
  pandas/tests/window/test_dtypes.py
Labels: Testing, Window

#27410 CLN: docstring
  pandas/core/groupby/grouper.py
Labels: Docs

#27416 CI: limit pytest version on 3.6
  ci/deps/azure-37-numpydev.yaml
  ci/deps/azure-macos-35.yaml
Labels: CI

#27412 CLN: fix compiler warnings in tzconversion.pyx
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Build, Clean

#27427 Merged mypy.ini into setup.cfg
  mypy.ini
  setup.cfg
Labels: Typing

#27309 ENH: Preserve key order when passing list of dicts to DataFrame on py 3.6+
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/io/json/test_normalize.py
Labels: Reshaping

#27367 BUG: Fix timezone-related indexing and plotting bugs
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/series.py
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/series/indexing/test_datetime.py
Labels: Bug, Indexing, Timezones, Visualization

#26773 PERF: 5x speedup for read_json() with orient='index' by avoiding transpose
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/json/_json.py
Labels: IO JSON, Performance

#27380 arrays/period: allow parsing of PeriodDtype columns from read_csv
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/arrays/period.py
  pandas/tests/extension/test_period.py
Labels: IO CSV, Period

#27426 Reallow usecols to reference OOB indices - reverts 25623
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_usecols.py
Labels: Data IO

#27425 BUG: fix+test fillna with non-nano datetime64; closes #27419
  pandas/core/internals/blocks.py
  pandas/tests/series/test_missing.py
Labels: Missing-data

#27280 DOC: cleanup docstring for read_json and fix error in contribution guide
  doc/source/development/contributing.rst
  pandas/io/json/_json.py
Labels: Docs

#27323 BUG: Fix insertion of wrong-dtypes NaT into Series[m8ns]
  pandas/_libs/index.pyx
  pandas/core/series.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Missing-data

#27391 TYPING: pandas/core/window.py
  pandas/_typing.py
  pandas/core/window.py
Labels: Typing, Window

#27267 ENH: Add Series method to explode a list-like column
  Makefile
  asv_bench/benchmarks/io/parsers.py
  asv_bench/benchmarks/reshape.py
  asv_bench/benchmarks/series_methods.py
  asv_bench/benchmarks/timeseries.py
  ci/code_checks.sh
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/user_guide/reshaping.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/lib.pxd
  pandas/_libs/lib.pyx
  pandas/_libs/reshape.pyx
  pandas/core/dtypes/inference.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/tests/frame/test_explode.py
  pandas/tests/series/test_explode.py
Labels: Enhancement, Reshaping

#27448 PERF: restore performance for unsorted CategoricalDtype comparison
  pandas/core/dtypes/dtypes.py
Labels: Categorical, Performance

#27440 CLN: Trim unused/unnecessary code
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
  pandas/util/testing.py
Labels: Clean, Internals

#27432 PLT: Delegating to plotting backend only plots of Series and DataFrame methods
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
Labels: Visualization

#27384 PERF: significantly improve performance of MultiIndex.shape
  asv_bench/benchmarks/index_cached_properties.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
Labels: MultiIndex, Performance

#27455 Pinned date and fixed contributors directive
  doc/source/whatsnew/v0.25.0.rst
Labels: Docs

#27474 DOC: Fix typos in docstrings for functions referring.
  pandas/plotting/_misc.py
Labels: Docs

#27489 PERF: speed up IntervalIndex._intersection_non_unique by ~50x
  pandas/core/indexes/interval.py
Labels: Performance

#27463 Remove .. versionadded:: 0.18
  doc/source/getting_started/basics.rst
  doc/source/getting_started/dsintro.rst
  doc/source/user_guide/enhancingperf.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/reshaping.rst
  doc/source/user_guide/text.rst
  doc/source/user_guide/timeseries.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/core/tools/datetimes.py
  pandas/core/window.py
  pandas/io/formats/format.py
  pandas/io/formats/style.py
  pandas/io/parsers.py
  pandas/tseries/offsets.py
Labels: Docs

#27466 CLN: remove unused row_bool_subset
  pandas/_libs/lib.pyx
  pandas/core/groupby/ops.py
Labels: Clean, Groupby

#27413 CLN/REF: Unify Arithmetic Methods
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/timedeltas.py
  pandas/core/ops/__init__.py
Labels: Compat

#27491 DOC: setup 1.0.0 docs
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.0.0.rst
Labels: Docs

#27423 CLN: fix build warning in c_timestamp.pyx
  pandas/_libs/tslibs/c_timestamp.pyx
Labels: Clean, Internals

#27444 CLN: simplify maybe_convert_objects, soft_convert_objects
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/dtypes/cast/test_convert_objects.py
  pandas/tests/internals/test_internals.py
Labels: Clean, Internals

#27418 add some type annotations io/formats/format.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
Labels: Output-Formatting, Typing

#27507 remove last references to v0.18 in docs and code
  doc/source/user_guide/advanced.rst
  doc/source/user_guide/computation.rst
  doc/source/user_guide/enhancingperf.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/reshaping.rst
  doc/source/user_guide/style.ipynb
  doc/source/user_guide/text.rst
  doc/source/user_guide/timeseries.rst
  doc/source/user_guide/visualization.rst
  doc/source/whatsnew/v0.16.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/core/window.py
  pandas/io/parsers.py
Labels: Docs

#27508 remove references to v0.19 in docs and code
  doc/source/getting_started/basics.rst
  doc/source/user_guide/categorical.rst
  doc/source/user_guide/computation.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/merging.rst
  doc/source/user_guide/text.rst
  doc/source/user_guide/timeseries.rst
  doc/source/user_guide/visualization.rst
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/base.py
  pandas/core/computation/ops.py
  pandas/core/dtypes/concat.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/reshape/merge.py
  pandas/core/series.py
  pandas/core/sorting.py
  pandas/core/tools/numeric.py
  pandas/core/util/hashing.py
  pandas/core/window.py
  pandas/io/excel/_base.py
  pandas/io/formats/format.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/tseries/offsets.py
Labels: Docs

#27510 BUG: Retain tz transformation in groupby.transform
  doc/source/whatsnew/v0.25.1.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_transform.py
Labels: Bug, Groupby, Timezones

#27311 BUG: Fix inserting of wrong-dtyped NaT, closes #27297
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/index.pyx
  pandas/core/internals/blocks.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Missing-data, Timeseries

#27411 REF: stop allowing iNaT in TimedeltaBlock methods
  pandas/core/internals/blocks.py
  pandas/core/nanops.py
  pandas/tests/series/test_missing.py
Labels: Compat, Timedelta

#27499 REF: de-privatize dtypes.concat functions
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/concat.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/melt.py
Labels: Clean, Internals

#27536 xfail to fix CI
  pandas/tests/series/indexing/test_indexing.py
Labels: CI, Testing

#27530 CLN: remove arrmap, closes #27251
  pandas/_libs/algos.pyx
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Clean

#27537 TST: label-based indexing fails with certain list indexers in case of…
  pandas/tests/indexing/test_loc.py
Labels: Indexing, Testing

#27533 DEPR: remove .ix tests from tests/indexing/test_floats.py
  pandas/tests/indexing/test_floats.py
Labels: Deprecate, Indexing
