Repository pandas-dev/pandas, pull requests merged in 2019-03, with the labels that each got.

#25132 Fix PR10 error and Clean up docstrings from functions related to RT05 errors
  ci/code_checks.sh
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/io/excel/_base.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/tseries/frequencies.py
Labels: Docs

#25496 TST: Fix test_stringified_slice_with_tz failure
  pandas/tests/indexes/datetimes/test_datetime.py
Labels: Unreliable Test

#25482 Correct documentation on make.py --single parameter
  doc/make.py
  doc/source/development/contributing.rst
Labels: Build, Docs

#25505 fix MacPython / pandas-wheels ci failures
  pandas/tests/test_algos.py
  pandas/tests/test_sorting.py
Labels: Testing

#25491 DOC: Reword Series.interpolate docstring for clarity
  pandas/core/generic.py
Labels: Docs

#25486 DOC: Use correct pandas when building documentation
  doc/make.py
Labels: CI, Docs

#25517 TST: xfail non-writeable pytables tests with numpy 1.16x
  pandas/compat/numpy/__init__.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/io/test_pytables.py
Labels: IO HDF5, Testing

#25504 STY: use pytest.raises context manager (arithmetic, arrays, computati…
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/sparse/test_libsparse.py
  pandas/tests/computation/test_eval.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_dtypes.py
Labels: CI, Style

#25498 BUG: Fix RecursionError during IntervalTree construction
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: Bug, Interval, Numeric

#25483 STY: use pytest.raises context manager (plotting, reductions, scalar...)
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/sparse/frame/test_frame.py
  pandas/tests/sparse/series/test_series.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_yqm_offsets.py
Labels: CI, Style

#25518 Backport PR #25517: TST: xfail non-writeable pytables tests with numpy 1.16x
  pandas/compat/numpy/__init__.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/io/test_pytables.py
Labels: Testing

#25368 BUG: Fix potential segfault after pd.Categorical(pd.Series(...), categories=...)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_constructors.py
Labels: Categorical, Regression

#25519 Backport PR #25498 on branch 0.24.x (BUG: Fix RecursionError during IntervalTree construction)
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: Bug, Interval

#24841 Make DataFrame.to_html output full content
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/formats/html.py
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML, Output-Formatting

#25520 Backport PR #25368 on branch 0.24.x (BUG: Fix potential segfault after pd.Categorical(pd.Series(...), categories=...))
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_constructors.py
Labels: Bug, Categorical

#24842 BUG-16807-1 SparseFrame fills with default_fill_value if data is None
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/sparse/frame.py
  pandas/tests/sparse/frame/test_frame.py
Labels: Bug, Missing-data, Sparse

#25490 DOC: Add conda uninstall pandas to contributing guide
  doc/source/development/contributing.rst
Labels: Docs

#25529 fix segfault when running with cython coverage enabled, xref cython#2879
  pandas/_libs/tslibs/period.pyx
Labels: Clean

#24886 TST: inline empty_frame = DataFrame({}) fixture
  pandas/tests/frame/common.py
  pandas/tests/frame/conftest.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_apply.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/series/conftest.py
  pandas/tests/series/test_constructors.py
Labels: Refactor, Testing

#25528 DOC: Polishing typos out of doc/source/user_guide/indexing.rst
  doc/source/user_guide/indexing.rst
Labels: Docs

#25516 STY: use pytest.raises context manager (frame)
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_convert_to.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/frame/test_missing.py
  pandas/tests/frame/test_mutate_columns.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_quantile.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_replace.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/frame/test_sorting.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/frame/test_to_csv.py
Labels: Style

#25358 DOC: Fix #24268 by updating description for keep in Series.nlargest
  pandas/core/series.py
Labels: Algos, Docs

#25537 fix MacPython / pandas-wheels ci failures
  pandas/tests/test_sorting.py
Labels: Style

#25533 BUG: caught typeError in series.at (#25506)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/series.py
  pandas/tests/indexing/test_scalar.py
Labels: Indexing, Timezones

#25535 ENH: Add errors parameter to DataFrame.rename
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/frame/test_alter_axes.py
Labels: API Design, DataFrame, Error Reporting

#25558 TST: Skip IntervalTree construction overflow test on 32bit
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: 32bit, Interval, Testing

#25559 DOC: Small fixes to 0.24.2 whatsnew
  doc/source/whatsnew/v0.24.2.rst
Labels: Docs

#25561 Backport PR #25558 on branch 0.24.x (TST: Skip IntervalTree construction overflow test on 32bit)
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: 32bit, Interval, Testing

#25574 minor typo error
  doc/source/getting_started/10min.rst
Labels: Docs

#25553 BUG: in error message raised when invalid axis parameter
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_missing.py
  pandas/tests/frame/test_quantile.py
  pandas/tests/frame/test_sorting.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_rank.py
  pandas/tests/series/test_sorting.py
  pandas/tests/series/test_timeseries.py
Labels: Error Reporting

#25568 BLD: Fixed pip install with no numpy
  doc/source/whatsnew/v0.24.2.rst
  setup.py
Labels: Build

#25551 Document the behavior of `axis=None` with `style.background_gradient`
  pandas/io/formats/style.py
Labels: Docs

#25579 fix minor typos in dsintro.rst
  doc/source/getting_started/dsintro.rst
Labels: Docs

#25556 BUG: Handle readonly arrays in period_array
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/tslibs/period.pyx
  pandas/tests/arrays/test_period.py
Labels: Period

#25578 Backport PR #25568 on branch 0.24.x (BLD: Fixed pip install with no numpy)
  doc/source/whatsnew/v0.24.2.rst
  setup.py
Labels: Build

#25598 DOC: Fix typo in tz_localize
  pandas/core/generic.py
Labels: Docs

#25586 BUG: secondary y axis could not be set to log scale (#25545)
  doc/source/whatsnew/v0.24.2.rst
  pandas/plotting/_core.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#25589 TST: add test for groupby on list of empty list
  pandas/tests/groupby/test_groupby.py
Labels: Error Reporting, Groupby, Testing

#25599 Backport PR #25586 on branch 0.24.x (BUG: secondary y axis could not be set to log scale (#25545))
  doc/source/whatsnew/v0.24.2.rst
  pandas/plotting/_core.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#25576 CLN: typing/mypy cleanup: Small fixes to make stubgen happy
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse.py
  pandas/core/groupby/groupby.py
  pandas/core/internals/blocks.py
Labels: Clean

#25355 CLN: Parmeterize test cases
  pandas/tests/io/test_sql.py
Labels: IO SQL, Refactor, Testing

#25603 STY: use pytest.raises context manager (generic)
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_series.py
Labels: Style, Testing

#25615 Fix HTML syntax errors in README.md
  README.md
Labels: Docs

#25597 STY: use pytest.raises context manager (io.sql)
  pandas/tests/io/test_sql.py
Labels: IO SQL, Refactor, Testing

#25618 DOC: Cleanup docstring pandas.core.filter
  pandas/core/generic.py
Labels: Docs

#25612 DOC: Remove makePanel from docs (#25609)
  doc/source/getting_started/dsintro.rst
  doc/source/whatsnew/v0.13.1.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v0.23.0.rst
Labels: Docs, Panel

#25631 TST: failing wheel building on PY2 and old numpy
  pandas/tests/frame/test_constructors.py
Labels: 2/3 Compat, Compat, Testing

#25525 DOC: resolve all GL03 docstring validation errors
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/sparse.py
  pandas/core/base.py
  pandas/core/config.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/base.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/io/feather_format.py
  pandas/plotting/_misc.py
Labels: Docs

#25620 BUG: Fix user-facing AssertionError with to_html (#25608)
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/formats/html.py
  pandas/tests/io/formats/test_to_html.py
Labels: Error Reporting, IO HTML

#25628 Fixturize tests/frame/test_asof.py
  pandas/tests/frame/test_asof.py
Labels: Testing

#25634 Fixturize tests/frame/test_combine_concat.py
  pandas/tests/frame/test_combine_concat.py
Labels: Testing

#25639 Fixturize tests/frame/test_join.py
  pandas/tests/frame/test_join.py
Labels: Clean, Testing

#25642 Fixturize tests/frame/test_mutate_columns.py
  pandas/tests/frame/test_mutate_columns.py
Labels: Clean, Testing

#25540 BUG: Fix #25481 by fixing the error message in TypeError
  doc/source/whatsnew/v0.25.0.rst
  pandas/plotting/_core.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
Labels: Error Reporting

#25643 TST: xref #25630
  pandas/tests/frame/test_constructors.py
Labels: 2/3 Compat

#25645 backport of 25643, 25638 on 0.24.x
  pandas/tests/frame/test_constructors.py
Labels: 2/3 Compat, Testing

#25524 DOC:Remove hard-coded examples from _flex_doc_SERIES (#24589)
  pandas/core/ops.py
Labels: Docs

#25008 require Return section only if return is not None nor commentary
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: CI, Docs

#25647 Removed debugging code
  pandas/tests/computation/test_eval.py
  pandas/tests/internals/test_internals.py
  pandas/util/testing.py
Labels: Clean

#25653 TST: fix incorrect sparse test (now failing on scipy master)
  pandas/tests/arrays/sparse/test_array.py
Labels: CI

#25629 Suppress incorrect warning in nargsort for timezone-aware DatetimeIndex
  pandas/core/sorting.py
  pandas/tests/test_sorting.py
Labels: Compat

#25657 Backport PR #25629: Suppress incorrect warning in nargsort for timezo…
  pandas/core/sorting.py
  pandas/tests/test_sorting.py
Labels: Timezones

#25624 DOC: file obj for to_csv must be newline=''
  doc/source/user_guide/io.rst
  pandas/core/generic.py
Labels: IO CSV, Windows

#25625 BUG: to_csv line endings with compression
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/common.py
  pandas/tests/frame/test_to_csv.py
Labels: IO CSV

#25584 BUG: Redefine IndexOpsMixin.size, fix #25580.
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/series/test_api.py
Labels: Bug, ExtensionArray

#25663 Backport PR #25625 on branch 0.24.x (BUG: to_csv line endings with compression)
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/common.py
  pandas/tests/frame/test_to_csv.py
Labels: IO CSV

#25134 DOC: restore toctree maxdepth
  doc/source/development/index.rst
  doc/source/getting_started/index.rst
  doc/source/index.rst.template
  doc/source/reference/index.rst
  doc/source/themes/nature_with_gtoc/layout.html
  doc/source/user_guide/index.rst
Labels: Docs

#25662 DOC: hardcode contributors for 0.24.x releases
  doc/source/whatsnew/v0.24.1.rst
  doc/source/whatsnew/v0.24.2.rst
Labels: Docs

#25669 Add 0.24.1 and 0.24.2 to whatsnew index
  doc/source/whatsnew/index.rst
Labels: Docs

#25668 DOC: update link to whatsnew in sidebar to 0.24.2
  doc/source/index.rst.template
Labels: Docs

#25660 DOC: clean-up of 0.24.2 whatsnew file
  doc/source/whatsnew/v0.24.2.rst
Labels: Docs

#25651 REGR: to_timedelta precision issues with floating data
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/timedeltas.py
  pandas/tests/indexes/timedeltas/test_tools.py
Labels: Regression, Timedelta

#25676 CLN: remove Panel from concat error message
  pandas/core/reshape/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Panel

#25670 CLN: Remove unused test code
  pandas/tests/computation/test_eval.py
Labels: Clean, Testing

#25687 Backport PR #25651 on branch 0.24.x (REGR: to_timedelta precision issues with floating data)
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/timedeltas.py
  pandas/tests/indexes/timedeltas/test_tools.py
Labels: Timedelta

#25602 BUG: Fix to_string output when using header keyword arg (#16718)
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_to_latex.py
Labels: IO LaTeX, Output-Formatting

#25592 BUG: fix usage of na_sentinel with sort=True in factorize()
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Algos, Regression

#25644 BUG: Fix error in replace with strings that are large numbers (#25616)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/series/test_replace.py
Labels: Numeric

#25699 DOC: update date of 0.24.2 release notes
  doc/source/whatsnew/v0.24.2.rst
Labels: Docs

#25701 Pinned pycodestyle
  environment.yml
  requirements-dev.txt
Labels: Build

#25675 TST/CLN: Remove more Panel tests
  pandas/tests/api/test_api.py
  pandas/tests/computation/test_eval.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_label_or_level_utils.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/test_base.py
Labels: Panel

#25655 CLN: remove pandas.core.categorical
  pandas/core/categorical.py
  pandas/tests/api/test_api.py
Labels: Clean

#25224 Fix concat not respecting order of OrderedDict
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/generic.py
  pandas/core/reshape/concat.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/reshape/test_concat.py
Labels: Bug, Reshaping

#25585 BUG: Preserve name in DatetimeIndex.snap
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/series/indexing/test_datetime.py
Labels: Bug, Timeseries

#24486 DEPR: Deprecate box kwarg for to_timedelta and to_datetime
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/dtypes/cast.py
  pandas/core/indexes/datetimelike.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/timedeltas.py
  pandas/io/parsers.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/indexes/timedeltas/test_tools.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Deprecate, Timedelta, Timeseries

#24868 TST: resolve issues with test_constructor_dtype_datetime64
  pandas/tests/frame/test_dtypes.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_dtypes.py
Labels: Testing, Timeseries

#25619 Json normalize nan support
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/json/normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON, Missing-data

#25714 #25707 - Fixed flakiness in stata write test
  pandas/tests/io/test_common.py
Labels: IO Stata, Unreliable Test

#25712 Make Rolling.apply documentation clearer
  pandas/core/window.py
Labels: Docs

#25720 ENH: Add public start, stop, and step attributes to RangeIndex
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/range.py
  pandas/tests/indexes/test_range.py
Labels: API Design, Index

#25728 DOC: fix some grammar and inconsistency issues in the User Guide
  doc/source/user_guide/text.rst
Labels: Docs

#25729 Update ValueError message in corr
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Error Reporting

#25641 Fixturize tests/frame/test_operators.py
  pandas/tests/frame/test_operators.py
Labels: Clean, Testing

#25646 CLN: Remove Panel benchmarks
  asv_bench/benchmarks/indexing.py
  asv_bench/benchmarks/join_merge.py
  asv_bench/benchmarks/panel_ctor.py
  asv_bench/benchmarks/panel_methods.py
Labels: Benchmark, Clean, Panel

#25590 BUG: Cast ExtensionArray to numpy ndarray before plot
  doc/source/whatsnew/v0.25.0.rst
  pandas/plotting/_core.py
  pandas/tests/plotting/test_frame.py
Labels: ExtensionArray, Visualization

#25665 PERF: speed up MPLPlot._apply_axis_properties by skipping expensive tick enumeration where feasible
  pandas/plotting/_core.py
Labels: Performance, Visualization

#25502 Update documentation of read_csv to explain that index_col can be a string containg a column name
  doc/source/user_guide/io.rst
  pandas/io/parsers.py
Labels: Docs, IO CSV

#24942 Remove py27 CI jobs
  .travis.yml
  README.md
  azure-pipelines.yml
  ci/azure/posix.yml
  ci/azure/windows.yml
  ci/deps/azure-27-compat.yaml
  ci/deps/azure-27-locale.yaml
  ci/deps/azure-windows-27.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/travis-27.yaml
  ci/deps/travis-36-doc.yaml
  ci/run_with_env.cmd
  doc/source/install.rst
  doc/source/whatsnew/v0.25.0.rst
  setup.py
  tox.ini
Labels: 2/3 Compat, Build

#25761 Fix typo in docstring of DataFrame.memory_usage
  pandas/core/frame.py
Labels: Docs

#25755 remove unnecessary check_output copy/pasted code
  pandas/util/testing.py
Labels: Clean

#25732 DOC: clarify corr behaviour when using a callable
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs

#25541 ENH: to_datetime support iso week year (16607)
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/strptime.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
Labels: Compat, Timeseries

#25713 Auto backport of pr 25701 on 0.24.x
  environment.yml
  requirements-dev.txt
Labels: CI

#25751 DOC: Fix function name.
  pandas/core/generic.py
Labels: Docs

#24879 DOC: Improve the docsting of Series.iteritems
  pandas/core/series.py
Labels: Docs

#25640 TST: Fixturize tests/frame/test_missing.py
  pandas/tests/frame/test_missing.py
Labels: Clean, Testing

#25693 Replace dicts with OrderedDicts in groupby aggregation functions
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Groupby

#25770 DOC: Fix typo in docstring of DataFrame.memory_usage
  pandas/core/frame.py
Labels: Docs

#25773 TST: Check pytables<3.5.1 when skipping
  pandas/tests/io/test_pytables.py
  pandas/tests/test_downstream.py
Labels: CI, Dependencies, Testing

#24721 CLN: replace %s syntax with .format in pandas.io.parsers
  pandas/io/parsers.py
Labels: Clean, Strings

#25613 make core.config self-contained
  pandas/core/config.py
Labels: Clean

#25721 TST: assert_produces_warning works with filterwarnings
  pandas/tests/util/test_assert_produces_warning.py
  pandas/util/testing.py
Labels: Testing

#25719 API: concat on sparse values
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/dtypes/concat.py
  pandas/core/groupby/generic.py
  pandas/tests/reshape/test_reshape.py
Labels: API Design, Reshaping, Sparse

#24538 Cython language level 3
  pandas/_libs/groupby.pyx
  pandas/_libs/parsers.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/writers.pyx
  pandas/io/sas/sas.pyx
  setup.py
Labels: 2/3 Compat, Build

#25065 ENH: Support datetime.timezone objects
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/timezones.pyx
  pandas/conftest.py
  pandas/tests/indexes/datetimes/test_construction.py
  pandas/tests/indexes/test_base.py
Labels: Enhancement, Timezones

#24047 Add test for rdivmod on EA array (GH23287)
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
Labels: ExtensionArray

#25789 Unpin pycodestyle
  environment.yml
  pandas/_libs/__init__.py
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/nattype.pyx
  pandas/core/arrays/array_.py
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse.py
  pandas/core/base.py
  pandas/core/common.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/io/formats/format.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/io/test_pytables.py
  pandas/tests/series/test_rank.py
  pandas/tests/tslibs/test_api.py
  requirements-dev.txt
Labels: CI, Dependencies, Style

#25757 Move locale code out of tm, into _config
  pandas/_config/__init__.py
  pandas/_config/localization.py
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/tests/config/__init__.py
  pandas/tests/config/test_localization.py
  pandas/util/testing.py
  setup.cfg
Labels: Clean

#25526 DOC: Fixed PeriodArray api ref
  doc/source/reference/arrays.rst
  pandas/core/arrays/period.py
Labels: Docs

#25792 DOC: clean bug fix section in whatsnew
  doc/source/whatsnew/v0.25.0.rst
Labels: Docs

#25769 BUG: reading windows utf8 filenames in py3.6
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/io.c
  pandas/tests/io/parser/test_common.py
Labels: Bug, Windows

#24955 ENH: Quoting column names containing spaces with backticks to use them in query and eval.
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/computation/common.py
  pandas/core/computation/expr.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/frame/test_query_eval.py
Labels: API Design

#25649 CLN: Panel reference from documentation
  doc/source/conf.py
  doc/source/development/extending.rst
  doc/source/ecosystem.rst
  doc/source/getting_started/10min.rst
  doc/source/getting_started/basics.rst
  doc/source/getting_started/dsintro.rst
  doc/source/install.rst
  doc/source/reference/index.rst
  doc/source/reference/panel.rst
  doc/source/user_guide/computation.rst
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/merging.rst
  doc/source/user_guide/sparse.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v0.6.0.rst
  doc/source/whatsnew/v0.7.0.rst
  pandas/core/frame.py
Labels: Clean, Docs, Panel

#25521 BUG-24971 copying blocks also considers ndim
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/series/test_replace.py
Labels: Categorical, Reshaping

#25588 BUG: Fix _binop for operators for serials which has more than one returns (divmod/rdivmod).
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/ops.py
  pandas/core/series.py
  pandas/tests/series/test_operators.py
Labels: Bug, Numeric

#25784 Speed up tokenizing of a row in csv and xstrtod parsing
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
Labels: IO CSV, Performance

#25780 PERF: Improve performance of StataReader's processing of missing values
  asv_bench/benchmarks/io/stata.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata, Performance

#25801 Fix ReST formatting of pandas.read_excel usecols
  pandas/io/excel/_base.py
Labels: Docs

#25808 DOC: Improved README formatting.
  doc/cheatsheet/README.txt
Labels: Docs

#25811 BUG: DatetimeIndex.to_frame does not drop timezone information
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/common.py
Labels: Index, Timeseries

#25810 BUG: DataFrame.update with tz-aware date doesn't return naive data
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_combine_concat.py
Labels: DataFrame, Timeseries

#25822 Implement --with-debugging-symbols switch in setup.py
  setup.py
Labels: Build

#25827 CI: exclude asv env directory from isort and tailing whitespace checks
  ci/code_checks.sh
  setup.cfg
Labels: Style

#25431 [BUG] maybe_upcast_putmast also handle ndarray
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_upcast.py
Labels: Algos, Bug, Dtypes

#25836 Safe version of ascii macros, add missing tolower_ascii
  pandas/_libs/src/headers/portable.h
Labels: Clean

#25804 PERF: Improve performance of hash sets in read_csv
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/khash.pxd
  pandas/_libs/parsers.pyx
  pandas/_libs/src/klib/khash_python.h
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
Labels: IO CSV, Performance

#25826 WIP, MAINT: upstream timedelta64 changes
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/arithmetic/test_datetime64.py
Labels: Compat, Timedelta

#25768 [BUG] Construction of Interval restricted to numeric/ Timestamp/ Timedelta (#23013)
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/interval.pyx
  pandas/tests/indexes/interval/test_construction.py
  pandas/tests/scalar/interval/test_interval.py
Labels: Dtypes, Interval

#25840 Remove chainmap_impl compat code
  pandas/compat/chainmap.py
  pandas/compat/chainmap_impl.py
  pandas/compat/numpy/function.py
Labels: Clean

#25852 CLN: Remove u and u_safe from pandas.compat
  pandas/compat/__init__.py
  pandas/compat/pickle_compat.py
  pandas/conftest.py
  pandas/core/arrays/categorical.py
  pandas/core/computation/pytables.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/panel.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/io/excel/_base.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/formats/latex.py
  pandas/io/formats/printing.py
  pandas/io/html.py
  pandas/io/json/json.py
  pandas/io/packers.py
  pandas/io/parsers.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/test_axis_select_reindex.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/frame/test_to_csv.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_frozen.py
  pandas/tests/indexes/test_range.py
  pandas/tests/indexing/multiindex/test_getitem.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/formats/test_eng_formatting.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/formats/test_to_latex.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/io/msgpack/test_pack.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_quoting.py
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_packers.py
  pandas/tests/io/test_pytables.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_io.py
  pandas/tests/series/test_repr.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_strings.py
  pandas/util/testing.py
Labels: 2/3 Compat, Clean, Unicode

#25793 Move core.config to _config.config
  pandas/__init__.py
  pandas/_config/__init__.py
  pandas/_config/config.py
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/api.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/interval.py
  pandas/core/base.py
  pandas/core/computation/expressions.py
  pandas/core/config_init.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/category.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/nanops.py
  pandas/core/series.py
  pandas/io/excel/_base.py
  pandas/io/formats/console.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/formats/printing.py
  pandas/io/formats/style.py
  pandas/io/pytables.py
  pandas/plotting/_core.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/config/test_config.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/groupby/test_transform.py
  pandas/tests/indexes/multi/test_format.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_category.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_printing.py
  pandas/tests/io/test_excel.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/sparse/test_format.py
Labels: Clean

#25859 [CLN] Remove TypeError in Interval.length
  pandas/_libs/interval.pyx
Labels: Clean, Interval

#25862 CLN: Remove long and integer_types from pandas.compat
  pandas/compat/__init__.py
  pandas/core/internals/blocks.py
  pandas/core/sorting.py
  pandas/io/json/json.py
  pandas/io/stata.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_integer.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_convert_to.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexes/conftest.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/multi/test_compat.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_comparisons.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/test_base.py
  pandas/tests/test_take.py
  pandas/tests/tools/test_numeric.py
Labels: 2/3 Compat, Clean, Numeric

#25394 BUG: pd.Series.interpolate non-numeric index column (21662)
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/generic.py
  pandas/tests/series/test_missing.py
Labels: Error Reporting, Numeric

#25865 CLN: Remove vestigial references to PY2 in tests
  pandas/tests/arithmetic/test_period.py
  pandas/tests/frame/test_indexing.py
  pandas/tests/series/test_repr.py
Labels: 2/3 Compat, Clean, Testing

#25861 [REF] Move remaining locale functions to _config.localization
  pandas/_config/__init__.py
  pandas/_config/dates.py
  pandas/_config/display.py
  pandas/_config/localization.py
  pandas/core/config_init.py
  pandas/io/formats/console.py
  pandas/tests/config/test_localization.py
  pandas/tests/io/formats/test_console.py
  pandas/util/testing.py
Labels: 2/3 Compat, Clean, Internals, Refactor

#25718 Backport PR #25262 on branch 0.24.x (REF/TST: resample/test_base.py)
  pandas/tests/resample/test_base.py
Labels: Testing

#25796 BUG: pd.concat does not drop DatetimeIndex.freq when result is monotonic with even spacing
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/datetimelike.py
  pandas/tests/reshape/test_concat.py
Labels: Reshaping

#25759 BUG: Cleaner exception when `.iloc` called with non-integer list
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
Labels: Error Reporting

#24748 ENH: Only apply first group once in fast GroupBy.apply
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/reduction.pyx
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Performance
