Repository pandas-dev/pandas, pull requests merged in 2019-02, with the labels that each got.

#25062 Clarification in docstring of Series.value_counts
  pandas/core/base.py
Labels: Docs

#25046 ENH: Support fold argument in Timestamp.replace
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_unary_ops.py
Labels: Enhancement, Timezones

#25044 CLN: to_pickle internals
  pandas/compat/pickle_compat.py
  pandas/io/pickle.py
Labels: 2/3 Compat, Clean

#25079 Backport PR #25069 on branch 0.24.x (REGR: rename_axis with None should remove axis name)
  doc/source/whatsnew/v0.24.1.rst
  pandas/core/generic.py
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/series/test_alter_axes.py
Labels: Regression, Reshaping

#24832 Implement+Test Tick.__rtruediv__
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Frequency

#25063 API: change Index set ops sort=True -> sort=None
  doc/source/whatsnew/v0.24.1.rst
  pandas/_libs/lib.pyx
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_set_ops.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_range.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
Labels: API Design, Deprecate

#25027 DOC: 0.24.1 whatsnew
  doc/source/index.rst.template
Labels: Docs

#25040 BUG: to_clipboard text truncated for Python 3 on Windows for UTF-16 text
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/clipboard/windows.py
  pandas/tests/io/test_clipboard.py
Labels: Data IO, Windows

#25045 PERF: use new to_records() argument in to_stata()
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/stata.py
Labels: IO Stata, Performance

#25084 DOC: Cleanup 0.24.1 whatsnew
  doc/source/whatsnew/v0.24.1.rst
Labels: Docs

#25086 Backport PR #25084 on branch 0.24.x (DOC: Cleanup 0.24.1 whatsnew)
  doc/source/whatsnew/v0.24.1.rst
Labels: Docs

#25073 Backport PR #25026 on branch 0.24.x (DOC: Start 0.24.2.rst)
  doc/source/whatsnew/v0.24.2.rst
Labels: Docs

#25074 CLN: Remove sentinel_factory() in favor of object()
  pandas/core/common.py
  pandas/io/formats/html.py
  pandas/io/formats/style.py
Labels: Clean

#24736 TST: avoid DST transitions when testing DateTimeIndex roundtrip
  pandas/tests/indexes/datetimes/test_timezones.py
Labels: Testing, Timezones

#25111 BLD: remove spellcheck from Makefile
  Makefile
Labels: Docs

#25095 TST: tests for categorical apply
  pandas/tests/series/test_apply.py
Labels: Categorical, Testing

#25098 CLN: use dtype in categorical constructors
  pandas/core/arrays/categorical.py
Labels: Categorical, Clean

#25097 DOC: frame.py doctest fixing
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/core/window.py
Labels: Docs

#25125 DOC: 0.24.1 release
  doc/source/whatsnew/v0.24.1.rst
Labels: Docs

#25085 Revert set_index inspection/error handling for 0.24.1
  doc/source/whatsnew/v0.24.1.rst
  pandas/core/frame.py
  pandas/tests/frame/test_alter_axes.py
Labels: Docs, Error Reporting, Indexing

#24825 DOC/CLN: Timezone section in timeseries.rst
  doc/source/user_guide/timeseries.rst
Labels: Clean, Docs, Timezones

#25129 DOC: Fix validation type error RT04 (#25107)
  ci/code_checks.sh
  pandas/core/algorithms.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/panel.py
  pandas/core/series.py
  pandas/io/formats/style.py
Labels: Docs

#25058 Reading a HDF5 created in py2
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/pytables.py
  pandas/tests/io/data/legacy_hdf/legacy_table_py2.h5
  pandas/tests/io/test_pytables.py
Labels: 2/3 Compat, IO HDF5

#25102 BUG: Fixing regression in DataFrame.all and DataFrame.any with bool_only=True
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/frame.py
  pandas/tests/frame/test_analytics.py
Labels: Bug, Reshaping

#25123 DOC: Removal of return variable names [WIP]
  pandas/core/generic.py
Labels: Docs

#24914 TST/REF: collect DataFrame reduction tests
  pandas/tests/frame/test_analytics.py
Labels: Refactor, Testing

#25139 Backport PR #25058 on branch 0.24.x (Reading a HDF5 created in py2)
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/pytables.py
  pandas/tests/io/data/legacy_hdf/legacy_table_py2.h5
  pandas/tests/io/test_pytables.py
Labels: IO HDF5

#25140 Backport PR #25102 on branch 0.24.x (BUG: Fixing regression in DataFrame.all and DataFrame.any with bool_only=True)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/frame.py
  pandas/tests/frame/test_analytics.py
Labels: Reshaping

#25133 Fix validation error type `SS05` and check in CI
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/ops.py
  pandas/core/panel.py
  pandas/core/series.py
  pandas/core/strings.py
  pandas/core/window.py
  pandas/io/stata.py
  pandas/plotting/_misc.py
  pandas/util/_decorators.py
Labels: Clean, Docs

#25089 Fixed tuple to List Conversion in Dataframe class
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/lib.pyx
  pandas/tests/frame/test_constructors.py
Labels: Bug, Reshaping

#25163 DOC: Updates to Timestamp document
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#25145 BLD: pin cython language level to '2'
  setup.py
Labels: Build

#25128 CLN: Use ABCs in set_index
  pandas/core/frame.py
Labels: Clean

#25179 Backport PR #25089 on branch 0.24.x (Fixed tuple to List Conversion in Dataframe class)
  doc/source/whatsnew/v0.24.2.rst
  pandas/_libs/lib.pyx
  pandas/tests/frame/test_constructors.py
Labels: Reshaping

#25116 DOC: update docstring for series.nunique
  pandas/core/base.py
Labels: Docs

#25181 Backport PR #25145 on branch 0.24.x (BLD: pin cython language level to '2')
  setup.py
Labels: 2/3 Compat

#25047 DEPR: remove PanelGroupBy, disable DataFrame.to_panel
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/groupby/__init__.py
  pandas/core/groupby/generic.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/io/pytables.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/io/test_pytables.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/test_panel.py
Labels: Deprecate, Panel

#24819 BUG: DataFrame.merge(suffixes=) does not respect None
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/internals/managers.py
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Bug, Reshaping

#25186 fix MacPython pandas-wheels failure
  pandas/tests/indexes/multi/test_analytics.py
Labels: Testing

#25192 modernize compat imports
  pandas/compat/__init__.py
  pandas/compat/numpy/function.py
  pandas/core/base.py
  pandas/core/common.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/sparse/scipy_sparse.py
  pandas/io/excel.py
  pandas/io/formats/html.py
  pandas/io/packers.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/msgpack/test_pack.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/test_panel.py
  pandas/util/_decorators.py
  pandas/util/testing.py
Labels: Clean

#25155 TST: follow-up to Test nested pandas array #24993
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/numpy_/__init__.py
  pandas/tests/extension/numpy_/conftest.py
  pandas/tests/extension/numpy_/test_numpy.py
  pandas/tests/extension/numpy_/test_numpy_nested.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_sparse.py
Labels: Testing

#24945 DOC/CLN: Fix errors in Series docstrings
  pandas/core/series.py
Labels: Docs

#25204 REF: Add more pytest idiom to test_holiday.py
  pandas/tests/tseries/holiday/__init__.py
  pandas/tests/tseries/holiday/test_calendar.py
  pandas/tests/tseries/holiday/test_federal.py
  pandas/tests/tseries/holiday/test_holiday.py
  pandas/tests/tseries/holiday/test_observance.py
  pandas/tests/tseries/test_holiday.py
Labels: Refactor, Testing

#25208 DOC: Fix validation type error SA05
  ci/code_checks.sh
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/computation/eval.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/inference.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/resample.py
  pandas/core/reshape/tile.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/numeric.py
  pandas/core/window.py
  pandas/errors/__init__.py
  pandas/io/formats/style.py
  pandas/io/gbq.py
  pandas/io/html.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/tseries/frequencies.py
Labels: Docs

#25182 BUG: Fix Series.is_unique with single occurrence of NaN
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/base.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/test_category.py
  pandas/tests/series/test_duplicates.py
Labels: Bug, Missing-data

#25191 REF: Remove many Panel tests
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/io/pytables.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/io/test_excel.py
  pandas/tests/io/test_pytables.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/test_panel.py
  pandas/tests/util/test_hashing.py
  pandas/util/testing.py
Labels: Clean

#25109 DOC: Fixes to docstrings and add PR10 (space before colon) to validation
  ci/code_checks.sh
  pandas/core/config.py
  pandas/io/excel.py
  pandas/plotting/_core.py
Labels: Docs

#24549 DOC: exclude autogenerated c/cpp/html files from 'trailing whitespace' checks
  ci/code_checks.sh
  pandas/util/move.c
Labels: CI

#25199 STY: use pytest.raises context manager (indexes/period)
  pandas/tests/indexes/period/test_asfreq.py
  pandas/tests/indexes/period/test_construction.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/period/test_period.py
Labels: Style, Testing

#25223 Backport PR #25182 on branch 0.24.x (BUG: Fix Series.is_unique with single occurrence of NaN)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/base.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/test_category.py
  pandas/tests/series/test_duplicates.py
Labels: Missing-data

#25231 DEPR: remove tm.makePanel and all usages
  pandas/tests/frame/test_reshape.py
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_panel.py
  pandas/tests/indexing/test_panel.py
  pandas/tests/io/test_sql.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/test_panel.py
  pandas/util/testing.py
Labels: Clean, Deprecate, Panel

#25233 DEPR: Remove Panel-specific parts of io.pytables
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/internals/__init__.py
  pandas/core/internals/blocks.py
  pandas/io/pytables.py
  pandas/tests/io/data/legacy_hdf/legacy_table.h5
  pandas/tests/io/test_pytables.py
Labels: Clean, Panel

#23264 DEPR: Add Deprecated warning for timedelta with passed units M and Y
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/indexes/timedeltas.py
  pandas/core/tools/timedeltas.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Deprecate, Timedelta

#25202 BUG-25061 fix printing indices with NaNs
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/formats/format.py
  pandas/tests/series/test_repr.py
Labels: Categorical, Output-Formatting

#25230 BUG: Fix regression in DataFrame.apply causing RecursionError
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/dtypes/inference.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_apply.py
Labels: DataFrame, Regression

#25171 BUG: Fix read_json orient='table' without index (#25170)
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/json/table_schema.py
  pandas/tests/io/json/test_pandas.py
Labels: Bug, IO JSON

#25237 BLD: prevent asv from calling sys.stdin.close() by using different launch method
  azure-pipelines.yml
Labels: Performance

#25032 (Closes #25029) Removed extra bracket from cheatsheet code example.
  doc/cheatsheet/Pandas_Cheat_Sheet.pdf
  doc/cheatsheet/Pandas_Cheat_Sheet.pptx
  doc/cheatsheet/Pandas_Cheat_Sheet_JA.pdf
  doc/cheatsheet/Pandas_Cheat_Sheet_JA.pptx
Labels: Docs

#25244 Backport PR #25202 on branch 0.24.x (BUG-25061 fix printing indices with NaNs)
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/formats/format.py
  pandas/tests/series/test_repr.py
Labels: Missing-data

#25206 CLN: For loops, boolean conditions, misc.
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/computation/pytables.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/category.py
  pandas/core/indexing.py
  pandas/core/internals/construction.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/tile.py
  pandas/core/strings.py
  pandas/core/tools/numeric.py
  pandas/core/window.py
  pandas/tests/arrays/test_integer.py
Labels: Clean

#25245 Backport PR #25230 on branch 0.24.x (BUG: Fix regression in DataFrame.apply causing RecursionError)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/dtypes/inference.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_apply.py
Labels: Reshaping

#24954 Refactor groupby helper from tempita to fused types
  pandas/_libs/groupby.pyx
  pandas/_libs/groupby_helper.pxi.in
  pandas/core/groupby/ops.py
Labels: Clean

#25150 CLN: Remove ipython 2.x compat
  asv_bench/benchmarks/__init__.py
  pandas/core/frame.py
  pandas/io/formats/console.py
Labels: CI, Clean, Dependencies

#25248 Backport PR #25171 on branch 0.24.x
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/json/table_schema.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON

#25234 BUG: Duplicated returns boolean dataframe
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_duplicates.py
Labels: Reshaping

#25262 REF/TST: resample/test_base.py
  pandas/tests/resample/test_base.py
Labels: Resample, Testing

#25253 Revert "BLD: prevent asv from calling sys.stdin.close() by using different launch method"
  azure-pipelines.yml
Labels: Performance

#25247 BUG: pandas Timestamp tz_localize and tz_convert do not preserve `freq` attribute
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Bug, Frequency, Timezones

#25238 DEPR: remove assert_panel_equal
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_panel.py
  pandas/tests/indexing/common.py
  pandas/tests/indexing/multiindex/test_panel.py
  pandas/tests/indexing/test_panel.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/test_packers.py
  pandas/tests/io/test_pickle.py
  pandas/tests/test_expressions.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_panel.py
  pandas/util/testing.py
Labels: Deprecate, Panel

#25157 PR04 errors fix
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/algorithms.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/panel.py
  pandas/core/resample.py
  pandas/io/formats/style.py
  pandas/io/parquet.py
Labels: Docs

#25153 Split Excel IO Into Sub-Directory
  pandas/io/excel.py
  pandas/io/excel/__init__.py
  pandas/io/excel/_base.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_util.py
  pandas/io/excel/_xlrd.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
Labels: IO Excel, Refactor

#25267 Backport PR #25234 on branch 0.24.x (BUG: Duplicated returns boolean dataframe)
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_duplicates.py
Labels: Reshaping

#25254 API: Ensure DatetimeTZDtype standardizes pytz timezones
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Timezones

#25246 BUG: Fix exceptions when Series.interpolate's `order` parameter is missing or invalid
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/tests/series/test_missing.py
Labels: Error Reporting, Missing-data

#25260 BUG: DataFrame.join on tz-aware DatetimeIndex
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
Labels: Reshaping, Timezones

#25272 REF: use _constructor and ABCFoo to avoid runtime imports
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/timedeltas.py
Labels: Clean

#25249 Refactor groupby group_prod, group_var, group_mean, group_ohlc
  pandas/_libs/groupby.pyx
  pandas/_libs/groupby_helper.pxi.in
  pandas/tests/test_algos.py
Labels: Groupby, Internals, Refactor

#25215 [DOC] Fix typo in Cheat sheet with regex
  doc/cheatsheet/Pandas_Cheat_Sheet.pdf
  doc/cheatsheet/Pandas_Cheat_Sheet.pptx
  doc/cheatsheet/Pandas_Cheat_Sheet_JA.pdf
  doc/cheatsheet/Pandas_Cheat_Sheet_JA.pptx
Labels: Docs

#25198 Edit parameter type in pandas.core.frame.py DataFrame.count
  pandas/core/frame.py
Labels: Docs

#25279 "Backport PR #25260 on branch 0.24.x"
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
Labels: Reshaping, Still Needs Manual Backport, Timezones

#25277 TST/CLN: remove test_slice_ints_with_floats_raises
  pandas/tests/indexes/test_base.py
Labels: Clean, Testing

#25281 Removed Panel class from HDF ASVs
  asv_bench/benchmarks/io/hdf.py
Labels: Benchmark, Deprecate, Panel

#25285 DOC: Fix minor typo in docstring
  pandas/core/frame.py
Labels: Docs

#24952 DOC/CLN: Fix errors in DataFrame docstrings
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#25323 Skipped broken Py2 / Windows test
  pandas/tests/test_downstream.py
Labels: 2/3 Compat, Build, Windows

#25309 Rt05 documentation error fix issue 25108
  ci/code_checks.sh
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/panel.py
  pandas/core/reshape/melt.py
  pandas/core/series.py
  pandas/core/tools/numeric.py
  pandas/core/window.py
  pandas/io/formats/style.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  pandas/tseries/frequencies.py
Labels: Docs

#25305 DOC: fix misspellings
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.10.0.rst
  doc/source/whatsnew/v0.16.1.rst
Labels: Docs

#25325 Backport PR #25323 on branch 0.24.x (Skipped broken Py2 / Windows test)
  pandas/tests/test_downstream.py
Labels: 2/3 Compat, Build, Windows

#25333 Doc: corrects spelling in generic.py
  pandas/core/generic.py
Labels: Docs

#25264 BUG: groupby.transform retains timezone information
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_transform.py
Labels: Bug, Groupby, Timezones

#25088 Fixes Formatting Exception
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/formats/terminal.py
  pandas/tests/io/formats/test_console.py
Labels: Output-Formatting

#25297 BUG: OverflowError in resample.agg with tz data
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/resample/test_resample_api.py
Labels: Bug, Resample, Timezones

#25295 DOC/CLN: Fix various docstring errors
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/reshape/tile.py
  pandas/core/strings.py
Labels: Docs

#25342 Backport PR #25264 on branch 0.24.x (BUG: groupby.transform retains timezone information)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_transform.py
Labels: Groupby, Timezones

#25142 COMPAT: alias .to_numpy() for scalars
  doc/source/reference/arrays.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Compat, Timedelta, Timeseries

#25280 ENH: Support times with timezones in at_time
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/frame/test_timeseries.py
Labels: Enhancement, Indexing, Timezones

#25343 Backport PR #25088 on branch 0.24.x (Fixes Formatting Exception)
  doc/source/whatsnew/v0.24.2.rst
  pandas/io/formats/terminal.py
  pandas/tests/io/formats/test_console.py
Labels: Output-Formatting

#25304 BUG: Fix passing of numeric_only argument for categorical reduce
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/arrays/categorical.py
  pandas/core/series.py
  pandas/tests/reductions/test_reductions.py
Labels: Categorical, Regression

#25344 Backport PR #25304 on branch 0.24.x (BUG: Fix passing of numeric_only argument for categorical reduce)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/arrays/categorical.py
  pandas/core/series.py
  pandas/tests/reductions/test_reductions.py
Labels: Categorical

#25346 TST: use a fixed seed to have the same uniques across python versions
  ci/deps/azure-27-compat.yaml
  ci/deps/azure-27-locale.yaml
  ci/deps/azure-36-locale_slow.yaml
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-37-numpydev.yaml
  ci/deps/azure-macos-35.yaml
  ci/deps/azure-windows-27.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/travis-27.yaml
  ci/deps/travis-36-locale.yaml
  ci/deps/travis-36-slow.yaml
  ci/deps/travis-36.yaml
  ci/deps/travis-37.yaml
  pandas/tests/io/formats/test_console.py
  pandas/tests/resample/test_datetime_index.py
Labels: Resample, Testing, Unreliable Test

#25352 TST: xfail excel styler tests, xref GH25351
  pandas/_libs/src/compat_helper.h
  pandas/_libs/src/inline_helper.h
  pandas/_libs/src/parse_helper.h
  pandas/_libs/src/parser/io.c
  pandas/_libs/src/parser/io.h
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
  pandas/_libs/tslibs/src/datetime/np_datetime.c
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.c
  pandas/tests/io/test_excel.py
  pandas/util/move.c
Labels: IO Excel, Style, Testing

#25360 DOC: Correct doc mistake in combiner func
  doc/source/getting_started/basics.rst
Labels: Bug, Docs

#25209 DOC/BLD: fix --no-api option
  doc/source/conf.py
Labels: Docs

#25363 Backport PR #25352: TST: xfail excel styler tests, xref GH25351
  pandas/tests/io/test_excel.py
Labels: IO Excel, Testing

#25365 DOC: modify typos in Contributing section
  doc/source/development/contributing.rst
Labels: Docs

#25371 Remove spurious MultiIndex creation in `_set_axis_name`
  pandas/core/generic.py
Labels: Clean

#25366 #23049: test for Fatal Stack Overflow stemming From Misuse of astype(…
  pandas/tests/frame/test_combine_concat.py
Labels: Categorical, Testing

#25310 #9236: test for the DataFrame.groupby with MultiIndex having pd.NaT
  pandas/tests/groupby/test_groupby.py
Labels: Testing

#25268 [BUG] exception handling of MultiIndex.__contains__ too narrow
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_multiindex.py
Labels: Bug, MultiIndex

#25372 Backport PR #25371 on branch 0.24.x (Remove spurious MultiIndex creation in `_set_axis_name`)
  pandas/core/generic.py
Labels: Clean

#25327 #14873: test for groupby.agg coercing booleans
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Dtypes, Testing

#25124 BUG/ENH: Timestamp.strptime
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Timeseries

#25338 Interval dtype fix
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/series/test_operators.py
Labels: Dtypes, Interval

#25275 [CLN] Excel Module Cleanups
  pandas/io/excel/_base.py
  pandas/io/excel/_util.py
  pandas/tests/io/test_excel.py
Labels: Clean

#25380 Backport PR #25338 on branch 0.24.x (Interval dtype fix)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/series/test_operators.py
Labels: Dtypes, Interval

#24924 ENH: indexing and __getitem__ of dataframe and series accept zerodim integer np.array as int
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/frame.py
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_scalar.py
Labels: Bug, Indexing

#25329 REGR: fix TimedeltaIndex sum and datetime subtraction with NaT (#25282, #25317)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/base.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Regression, Timeseries

#25381 DOC: edited whatsnew typo
  doc/source/whatsnew/v0.25.0.rst
Labels: Docs

#25388 DOC: Fix typo of see also in DataFrame stat funcs
  pandas/core/generic.py
Labels: Docs

#25189 API: more consistent error message for MultiIndex.from_arrays
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_constructor.py
Labels: Error Reporting

#25382 CLN: (re-)enable infer_dtype to catch complex
  pandas/_libs/lib.pyx
  pandas/tests/dtypes/test_inference.py
Labels: API Design, Dtypes

#25410 DOC: Edited docstring of Interval
  pandas/_libs/interval.pyx
Labels: Docs

#25400 Mark test_pct_max_many_rows as high memory
  pandas/tests/frame/test_rank.py
  pandas/tests/series/test_rank.py
  pandas/tests/test_algos.py
Labels: Testing

#25418 Correct a typo of version number for interpolate()
  doc/source/user_guide/missing_data.rst
  pandas/core/generic.py
Labels: Docs

#25417 DEP: add pytest-mock to environment.yml
  environment.yml
  requirements-dev.txt
Labels: Dependencies

#25219 BUG: Fix type coercion in read_json orient='table' (#21345)
  doc/source/whatsnew/v0.25.0.rst
  pandas/io/json/json.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_pandas.py
Labels: Dtypes, IO JSON

#25414 ERR: doc update for ParsingError
  pandas/errors/__init__.py
Labels: Docs, Error Reporting

#25110 ENH: Add in sort keyword to DatetimeIndex.union
  doc/source/styled.xlsx
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_setops.py
Labels: Reshaping

#25421 DOC: Rewriting of ParserError doc + minor spacing
  pandas/errors/__init__.py
Labels: Data IO, Docs

#24984 API/ERR: allow iterators in df.set_index & improve errors
  doc/source/whatsnew/v0.25.0.rst
  pandas/compat/__init__.py
  pandas/core/frame.py
  pandas/tests/frame/test_alter_axes.py
Labels: Reshaping

#25263 BUG: Indexing with UTC offset string no longer ignored
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
Labels: Indexing, Timezones

#22034 PERF/REF: improve performance of Series.searchsorted, PandasArray.searchsorted, collect functionality
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/arrays/numpy_.py
  pandas/core/base.py
  pandas/core/series.py
  pandas/tests/arrays/test_array.py
Labels: Algos, Performance

#24885 TST: remove never-used singleton fixtures
  pandas/tests/frame/conftest.py
Labels: Clean, Testing

#25289 BUG: fixed merging with empty frame containing an Int64 column (#25183)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Dtypes, ExtensionArray, Reshaping

#25426 Backport PR #25289 on branch 0.24.x (BUG: fixed merging with empty frame containing an Int64 column (#25183))
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/merge/test_merge.py
Labels: ExtensionArray, Reshaping

#25420 fixed geo accessor example in extending.rst
  doc/source/development/extending.rst
Labels: Docs

#25432 TST: numpy RuntimeWarning with Series.round()
  pandas/tests/frame/test_analytics.py
  pandas/tests/series/test_analytics.py
Labels: Bug, Missing-data

#25455 CI: add __init__.py to isort skip list
  ci/deps/azure-27-compat.yaml
  ci/deps/azure-27-locale.yaml
  ci/deps/azure-36-locale_slow.yaml
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-37-numpydev.yaml
  ci/deps/azure-macos-35.yaml
  ci/deps/azure-windows-27.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/travis-27.yaml
  ci/deps/travis-36-doc.yaml
  ci/deps/travis-36-locale.yaml
  ci/deps/travis-36-slow.yaml
  ci/deps/travis-36.yaml
  ci/deps/travis-37.yaml
  setup.cfg
Labels: CI, Style

#24852 DOC: CategoricalIndex doc string
  pandas/core/indexes/category.py
Labels: Categorical, Docs

#25474 DataFrame.drop Raises KeyError definition
  pandas/core/frame.py
Labels: Docs

#25469 BUG: Keep column level name in resample nunique
  doc/source/reference/groupby.rst
  doc/source/whatsnew/v0.25.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_function.py
  pandas/tests/resample/test_datetime_index.py
Labels: Algos, Bug, MultiIndex

#25467 ERR: Correct error message in to_datetime
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/tslib.pyx
  pandas/tests/indexes/datetimes/test_tools.py
Labels: Dtypes, Error Reporting, Timeseries

#25458 Fix minor typo
  pandas/core/generic.py
Labels: Docs

#25402 CI: Set pytest minversion to 4.0.2
  ci/deps/azure-27-compat.yaml
  ci/deps/azure-27-locale.yaml
  ci/deps/azure-36-locale_slow.yaml
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-37-numpydev.yaml
  ci/deps/azure-macos-35.yaml
  ci/deps/azure-windows-27.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/travis-27.yaml
  ci/deps/travis-36-doc.yaml
  ci/deps/travis-36-locale.yaml
  ci/deps/travis-36-slow.yaml
  ci/deps/travis-36.yaml
  ci/deps/travis-37.yaml
  doc/source/development/contributing.rst
  doc/source/install.rst
  doc/source/whatsnew/v0.25.0.rst
  environment.yml
  pandas/util/_tester.py
  requirements-dev.txt
  setup.cfg
Labels: Testing

#25447 STY: use pytest.raises context manager (indexes)
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_category.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/timedeltas/test_arithmetic.py
  pandas/tests/indexes/timedeltas/test_construction.py
  pandas/tests/indexes/timedeltas/test_ops.py
  pandas/tests/indexes/timedeltas/test_partial_slicing.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/indexes/timedeltas/test_tools.py
Labels: CI, Style

#25452 STY: use pytest.raises context manager (tests/test_*)
  pandas/tests/test_algos.py
  pandas/tests/test_config.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_nanops.py
  pandas/tests/test_sorting.py
  pandas/tests/test_strings.py
  pandas/tests/test_window.py
Labels: CI, Style

#25256 Fix minor error in dynamic load function
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Error Reporting, Style

#20405 Cythonized GroupBy Quantile
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v0.25.0.rst
  pandas/_libs/groupby.pxd
  pandas/_libs/groupby.pyx
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Performance

#25266 BUG: Fix regression on DataFrame.replace for regex
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/internals/managers.py
  pandas/tests/frame/test_replace.py
Labels: Bug, Strings

#25477 Backport PR #25266 on branch 0.24.x (BUG: Fix regression on DataFrame.replace for regex)
  doc/source/whatsnew/v0.24.2.rst
  pandas/core/internals/managers.py
  pandas/tests/frame/test_replace.py
Labels: Missing-data, Reshaping
