Repository pandas-dev/pandas, pull requests merged in 2020-10, with the labels that each got.

#36734 DOC: Format more code blocks
  doc/source/user_guide/io.rst
  doc/source/user_guide/text.rst
Labels: Docs

#36653 CLN: de-duplicate IntervalArray validators
  pandas/core/arrays/interval.py
Labels: Clean

#36747 [DOC]: Add explanation about DataFrame methods use all Categories
  doc/source/user_guide/categorical.rst
Labels: Categorical, Docs

#36645 REF: privatize in core.missing, remove unused kwarg
  pandas/core/arrays/base.py
  pandas/core/missing.py
Labels: Clean

#36685 DEPR: Deprecate params levels & codes in MultiIndex.copy
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_copy.py
Labels: Deprecate, MultiIndex

#36742 TYP: some more static definitions of methods for DatetimeIndex
  pandas/core/indexes/datetimes.py
Labels: Typing

#36696 TYP: mostly datetimelike
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/series.py
  pandas/tests/extension/arrow/arrays.py
Labels: Typing

#36762 TST: insert 'match' to bare pytest raises in pandas/tests/indexing/te…
  pandas/tests/indexing/test_chaining_and_caching.py
Labels: Testing

#36751 Backport PR #36706 on branch 1.1.x (CI: npdev new exception message)
  pandas/tests/arithmetic/common.py
  pandas/tests/frame/test_arithmetic.py
Labels: CI

#36750 Backport PR #36552 on branch 1.1.x (REGR: Series.__mod__ behaves different with numexpr)
  doc/source/whatsnew/v1.1.3.rst
  pandas/core/computation/expressions.py
  pandas/core/ops/methods.py
  pandas/tests/test_expressions.py
Labels: Numeric

#36580 BUG: use cmath to test complex number equality in pandas._testing
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/testing.pyx
  pandas/tests/util/test_assert_almost_equal.py
Labels: Complex, Testing

#36770 CI: troubleshoot travis ci on 1.1.x
  ci/deps/travis-36-cov.yaml
  ci/deps/travis-36-locale.yaml
Labels: CI, IO Google

#36763 DOC: Fix PR09 errors in several files
  pandas/core/computation/eval.py
  pandas/core/flags.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/series.py
  pandas/io/json/_json.py
  pandas/io/pickle.py
  pandas/io/pytables.py
Labels: Docs

#36789 TST: Add test for 32724
  pandas/tests/window/test_rolling.py
Labels: Testing, Window

#36811 DOC: use blacken to fix code style in documentation #36777
  doc/source/user_guide/cookbook.rst
Labels: Docs

#36801 CLN: Use more pytest idioms in test_momemts_ewm.py
  pandas/tests/window/moments/test_moments_ewm.py
Labels: Clean, Testing, Window

#36649 DEPR: min_periods=None behavior for Rolling.count
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/rolling.py
  pandas/tests/window/moments/test_moments_consistency_rolling.py
  pandas/tests/window/moments/test_moments_rolling_functions.py
  pandas/tests/window/test_base_indexer.py
  pandas/tests/window/test_dtypes.py
  pandas/tests/window/test_grouper.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_timeseries_window.py
Labels: Deprecate, Window

#36784 CLN: test_moments_rolling.py for quantile/kurt/skew
  pandas/tests/window/moments/test_moments_rolling.py
  pandas/tests/window/moments/test_moments_rolling_quantile.py
  pandas/tests/window/moments/test_moments_rolling_skew_kurt.py
Labels: Clean, Testing, Window

#36813 DOC: use black to fix code style in doc pandas-dev#36777
  doc/source/getting_started/comparison/comparison_with_r.rst
  doc/source/getting_started/comparison/comparison_with_sas.rst
  doc/source/getting_started/comparison/comparison_with_sql.rst
  doc/source/getting_started/comparison/comparison_with_stata.rst
Labels: Docs

#36792 ERR: error handling in DataFrame.__rmatmul__
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_analytics.py
Labels: Bug, Error Reporting, Numeric

#36786 CLN: Remove param _set_identity from MultiIndex
  pandas/core/indexes/multi.py
Labels: Clean, MultiIndex

#36744 BUG: DTI/TDI.equals with i8
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/datetimelike.py
  pandas/core/ops/__init__.py
  pandas/tests/computation/test_eval.py
  pandas/tests/indexes/datetimelike.py
Labels: Bug, Timeseries

#36810 CLN: test_moments_consistency_*.py
  pandas/tests/window/common.py
  pandas/tests/window/moments/test_moments_consistency_ewm.py
  pandas/tests/window/moments/test_moments_consistency_rolling.py
Labels: Clean, Testing, Window

#36793 API: make DataFrame.__boolop__ default_axis match DataFrame.__arithop__ default_axis
  pandas/core/ops/__init__.py
  pandas/tests/series/test_api.py
Labels: API - Consistency, Reshaping

#36761 ENH: Implement IntegerArray reductions
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/integer.py
  pandas/tests/arrays/integer/test_function.py
Labels: Enhancement, NA - MaskedArrays

#36484 ENH: PandasArray ops use core.ops functions
  pandas/core/arrays/numpy_.py
  pandas/tests/arithmetic/common.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: ExtensionArray, Numeric

#36815 DOC: uses black to fix formatting #36777
  doc/source/user_guide/merging.rst
Labels: Docs

#36674 CLN: cleanups in DataFrame._reduce
  pandas/core/frame.py
Labels: Clean

#36797 DOC: remove outdated doc closes #31487
  doc/source/user_guide/dsintro.rst
Labels: Docs

#36623 BUG: Categorical setitem, comparison with tuple category
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_operators.py
Labels: Categorical, Indexing

#36677 CLN/TYP: aggregation methods in core.base
  pandas/core/base.py
Labels: Typing

#36675 REGR: Series.loc with a MultiIndex containing Timestamp raises InvalidIndexError
  doc/source/whatsnew/v1.1.3.rst
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Indexing, MultiIndex, Regression, Timeseries

#36707 CI, CLN remove unnecessary noqa statements, add CI check
  .pre-commit-config.yaml
  asv_bench/benchmarks/pandas_vb_common.py
  asv_bench/benchmarks/tslibs/offsets.py
  doc/source/conf.py
  pandas/_typing.py
  pandas/api/types/__init__.py
  pandas/conftest.py
  pandas/core/arrays/floating.py
  pandas/io/common.py
  pandas/io/formats/console.py
  pandas/io/formats/info.py
  pandas/io/json/_table_schema.py
  pandas/io/pytables.py
  pandas/io/sas/sasreader.py
  pandas/plotting/_matplotlib/__init__.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/arrays/sparse/test_libsparse.py
  pandas/tests/computation/test_eval.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/categorical/test_formats.py
  pandas/tests/indexes/multi/test_formats.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexing/test_callable.py
  pandas/tests/io/formats/test_style.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/test_index_col.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/series/test_repr.py
  pandas/tests/test_common.py
  pandas/tests/test_downstream.py
  pandas/tests/test_errors.py
  scripts/validate_docstrings.py
  setup.py
Labels: CI, Clean

#36656 ASV: used integer ndarray as indexer for Series.take indexing benchmark
  asv_bench/benchmarks/indexing.py
Labels: Benchmark, ExtensionArray

#36731 EA: tighten TimedeltaArray._from_sequence signature
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/timedeltas.py
Labels: API - Consistency, ExtensionArray

#36718 EA: Tighten signature on DatetimeArray._from_sequence
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
  pandas/core/nanops.py
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/scalar/test_nat.py
Labels: API - Consistency, ExtensionArray

#36310 REF: Back IntervalArray by array instead of Index
  doc/source/whatsnew/v1.2.0.rst
  pandas/_testing.py
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/extension/test_interval.py
  pandas/tests/indexes/interval/test_constructors.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/util/test_assert_interval_array_equal.py
Labels: Interval

#36795 DEPR: automatic alignment on frame.__cmp__(series)
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/ops/__init__.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/frame/test_arithmetic.py
Labels: Deprecate, Reshaping

#36778 ENH: Implement FloatingArray reductions
  pandas/core/arrays/floating.py
  pandas/tests/arrays/floating/test_function.py
Labels: Enhancement, NA - MaskedArrays

#36730 [BUG]: Rolling selected too large windows with PeriodIndex
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_rolling.py
Labels: Bug, Window

#36818 Backport PR #36675 on branch 1.1.x (REGR: Series.loc with a MultiIndex containing Timestamp raises InvalidIndexError)
  doc/source/whatsnew/v1.1.3.rst
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Indexing, Regression

#36821 DOC: update code style for development doc and user guide #36777
  doc/source/development/extending.rst
  doc/source/user_guide/computation.rst
  doc/source/user_guide/dsintro.rst
  doc/source/user_guide/visualization.rst
Labels: Docs

#36823 DOC: update code style for user guide for #36777
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/missing_data.rst
  doc/source/user_guide/scale.rst
  doc/source/user_guide/timeseries.rst
Labels: Docs

#36600 CI: silence codecov for unrelated lines
  codecov.yml
Labels: CI

#36648 TST: GH23452 test reorder_categories() on categorical index
  pandas/tests/indexing/test_categorical.py
Labels: Testing

#36844 DOC: Typo fix
  doc/source/user_guide/style.ipynb
Labels: Docs

#36726 CLN: private funcs in concat.py
  pandas/core/internals/concat.py
Labels: Refactor

#36647 ENH: match stdlib behavior for datetimelike comparisons
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/scalar/timestamp/test_comparisons.py
  pandas/tests/series/indexing/test_datetime.py
Labels: Error Reporting, Timezones

#36845 DOC: normalize usage of word "pandas"
  doc/source/development/code_style.rst
  doc/source/development/contributing.rst
  doc/source/development/maintaining.rst
  doc/source/ecosystem.rst
  doc/source/getting_started/comparison/comparison_with_r.rst
  doc/source/getting_started/comparison/comparison_with_stata.rst
  doc/source/getting_started/install.rst
  doc/source/getting_started/overview.rst
  doc/source/reference/arrays.rst
  doc/source/reference/series.rst
  doc/source/user_guide/basics.rst
  doc/source/user_guide/boolean.rst
  doc/source/user_guide/categorical.rst
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/dsintro.rst
  doc/source/user_guide/duplicates.rst
  doc/source/user_guide/enhancingperf.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/integer_na.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/missing_data.rst
  doc/source/user_guide/scale.rst
  doc/source/user_guide/sparse.rst
  doc/source/user_guide/timedeltas.rst
  doc/source/user_guide/timeseries.rst
  doc/source/user_guide/visualization.rst
  doc/source/whatsnew/v0.11.0.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v0.17.0.rst
  doc/source/whatsnew/v0.19.0.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v0.21.0.rst
  doc/source/whatsnew/v0.21.1.rst
  doc/source/whatsnew/v0.22.0.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.23.2.rst
  doc/source/whatsnew/v0.24.0.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v0.25.1.rst
  doc/source/whatsnew/v0.25.2.rst
  doc/source/whatsnew/v1.0.0.rst
  doc/source/whatsnew/v1.1.3.rst
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#36864 CI: Update error message for np_dev
  pandas/tests/series/indexing/test_indexing.py
Labels: CI

#36802 DOC: ran blacken docs tool and checked output to improve formatting #36777
  doc/source/user_guide/10min.rst
  doc/source/user_guide/advanced.rst
  doc/source/user_guide/basics.rst
  setup.cfg
Labels: Docs, Style

#36877 CLN: Remove the duplicate configuration of flake8-rst in setup.cfg
  setup.cfg
Labels: Style

#36886 Backport PR #36864 on branch 1.1.x (CI: Update error message for np_dev)
  pandas/tests/series/indexing/test_indexing.py
Labels: CI

#36883 DOC: sync release notes on 1.1.x with master
  doc/source/whatsnew/v1.1.3.rst
Labels: Docs

#36885 TYP: check_untyped_defs core.arrays.base
  pandas/core/arrays/base.py
  setup.cfg
Labels: Typing

#36884 TYP: check_untyped_defs compat.pickle_compat
  pandas/compat/pickle_compat.py
  setup.cfg
Labels: Typing

#36872 PERF: Improve RollingGroupby.count
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/window/common.py
Labels: Performance, Window

#36887 DOC: 1.1.3 release date
  doc/source/whatsnew/v1.1.3.rst
Labels: Docs

#36891 Backport PR #36887 on branch 1.1.x (DOC: 1.1.3 release date)
  doc/source/whatsnew/v1.1.3.rst
Labels: Docs

#36839 PERF: Add asv benchmarks for select_dtypes (14588)
  asv_bench/benchmarks/dtypes.py
Labels: Benchmark, Dtypes

#36689 DOC: Start v1.1.4 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.1.3.rst
  doc/source/whatsnew/v1.1.4.rst
Labels: Docs

#34755 TST: Period with Timestamp overflow
  pandas/tests/scalar/period/test_period.py
Labels: Period, Stale, Testing

#36863 CI: Show ipython directive errors
  .github/workflows/ci.yml
Labels: CI, Docs

#36746 Standardize cast_str behavior in all datetimelike fill_value validators
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/indexes/datetimelike.py
Labels: Error Reporting, Missing-data

#36905 CLN: value -> key
  pandas/core/arrays/interval.py
Labels: Clean, Interval

#36902 CLN: standardize fixture usage in datetimelike array tests
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Testing

#36900 DEPR: Index.ravel returning an ndarray
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/io/formats/format.py
  pandas/tests/indexes/test_common.py
Labels: Deprecate, Index, Reshaping

#36901 REF: collect reduction tests
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_reductions.py
  pandas/tests/test_lib.py
  pandas/tests/test_sorting.py
Labels: Testing

#36899 Backport PR #36689 on branch 1.1.x (DOC: Start v1.1.4 release notes)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.1.3.rst
  doc/source/whatsnew/v1.1.4.rst
Labels: Docs

#36840 PERF: Index._shallow_copy shares _cache with copies of self
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/tests/base/test_misc.py
  pandas/tests/indexes/common.py
Labels: Index, Performance

#36917 TYP: check_untyped_defs core.computation.expressions
  pandas/core/computation/expressions.py
  setup.cfg
Labels: Typing

#36753 BUG: Segfault with string Index when using Rolling after Groupby
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Regression, Window

#36920 TYP: check_untyped_defs core.computation.pytables
  pandas/core/computation/pytables.py
  setup.cfg
Labels: Typing

#36870 TST: xfailed arithmetic tests
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/integer.py
  pandas/core/arrays/numpy_.py
  pandas/tests/arithmetic/common.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
Labels: Timedelta

#36625 CLN: de-duplicate numeric type check in _libs/testing
  pandas/_libs/testing.pyx
  pandas/_libs/tslibs/util.pxd
Labels: Clean, Testing

#36783 Test that nan value counts are included when dropna=False. GH#31944
  pandas/tests/base/test_value_counts.py
Labels: Missing-data, Testing

#36859 REF/CLN: pandas/io/pytables.py
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_store.py
Labels: IO HDF5, Refactor

#36478 CLN: aggregation.transform
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/aggregation.py
  pandas/core/frame.py
  pandas/core/shared_docs.py
  pandas/tests/frame/apply/test_frame_transform.py
  pandas/tests/series/apply/test_series_transform.py
Labels: Apply, Clean

#36871 REF: IntervalIndex.equals defer to IntervalArray.equals
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
Labels: Interval, Refactor

#36826 CI add end-of-file-fixer
  .github/CODE_OF_CONDUCT.md
  .pre-commit-config.yaml
  AUTHORS.md
  ci/travis_process_gbq_encryption.sh
  doc/data/iris.data
  doc/source/development/contributing.rst
  doc/source/development/developer.rst
  doc/source/getting_started/intro_tutorials/index.rst
  doc/source/getting_started/overview.rst
  doc/source/reference/general_utility_functions.rst
  doc/source/whatsnew/v0.14.0.rst
  flake8/cython-template.cfg
  pandas/_libs/src/klib/khash_python.h
  pandas/_libs/util.pxd
  pandas/tests/io/json/data/tsframe_iso_v012.json
  pandas/tests/io/json/data/tsframe_v012.json
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
  setup.cfg
  web/pandas/community/coc.md
Labels: CI, Style

#36923 DOC: add newline to fix code block format in `pandas.DataFrame.to_sql`
  pandas/core/generic.py
Labels: Docs, IO SQL

#36004 BUG: Can't restore index from parquet with offset-specified timezone #35997
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/tslibs/timezones.pyx
  pandas/conftest.py
  pandas/tests/io/test_parquet.py
  pandas/tests/tslibs/test_timezones.py
Labels: Bug, IO Parquet, Timezones

#36626 CI: add py38 slow build #35160
  .travis.yml
  ci/azure/posix.yml
  ci/deps/azure-37-32bit.yaml
  ci/deps/azure-37.yaml
  ci/deps/azure-38.yaml
  ci/deps/travis-37-locale.yaml
  ci/deps/travis-38-slow.yaml
  ci/deps/travis-38.yaml
Labels: CI

#36773 DOC: Fix code block line length
  doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
  doc/source/user_guide/advanced.rst
  doc/source/user_guide/basics.rst
  doc/source/user_guide/categorical.rst
  doc/source/user_guide/computation.rst
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/merging.rst
  doc/source/user_guide/missing_data.rst
  doc/source/user_guide/reshaping.rst
  doc/source/user_guide/text.rst
  doc/source/user_guide/timedeltas.rst
  doc/source/user_guide/timeseries.rst
  doc/source/user_guide/visualization.rst
  doc/source/whatsnew/v0.10.1.rst
  doc/source/whatsnew/v0.13.1.rst
  doc/source/whatsnew/v0.14.1.rst
  doc/source/whatsnew/v0.17.0.rst
  doc/source/whatsnew/v0.19.0.rst
  doc/source/whatsnew/v0.8.0.rst
  setup.cfg
Labels: Docs

#36501 Modify doc/source/whatsnew7
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v0.25.1.rst
  doc/source/whatsnew/v0.25.2.rst
  doc/source/whatsnew/v0.25.3.rst
  doc/source/whatsnew/v1.0.0.rst
  doc/source/whatsnew/v1.0.2.rst
  doc/source/whatsnew/v1.1.0.rst
  scripts/validate_rst_title_capitalization.py
Labels: Clean, Docs

#36563 Closes #36541 (BUG: ValueError: cannot convert float NaN to integer when resetting MultiIndex with NaT values)
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/series/indexing/test_multiindex.py
Labels: Bug, Missing-data, MultiIndex

#35987 TST: Verify operators with IntegerArray and list-likes (22606)
  pandas/tests/arithmetic/conftest.py
  pandas/tests/arithmetic/test_numeric.py
Labels: ExtensionArray, Testing

#36713 CLN: pandas/core/indexing.py
  pandas/core/indexing.py
Labels: Indexing, Refactor

#36564 ENH: return RangeIndex from difference, symmetric_difference
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/range.py
  pandas/tests/indexes/ranges/test_setops.py
Labels: Index

#36694 ENH: DatetimeArray/PeriodArray median
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/reductions/test_stat_reductions.py
Labels: Numeric, Period, Timeseries

#36710 BUG: df.diff axis=1 mixed dtypes
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/managers.py
  pandas/core/reshape/melt.py
  pandas/tests/frame/methods/test_diff.py
Labels: Dtypes, Reshaping

#36643 TYP: selection and groups type-hinting in groupby
  pandas/core/base.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Groupby, Typing

#36413 fix inconsistent index naming with union/intersect #35847
  doc/source/user_guide/merging.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/reshape/concat.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_common.py
  pandas/tests/reshape/test_concat.py
Labels: Index

#36921 TYP: check_untyped_defs core.groupby.ops
  pandas/core/groupby/ops.py
  setup.cfg
Labels: Typing

#36760 BUG: inconsistent name-retention in Series ops
  doc/source/whatsnew/v1.2.0.rst
  pandas/conftest.py
  pandas/core/ops/__init__.py
  pandas/tests/series/test_arithmetic.py
Labels: API - Consistency

#36766 BUG: fix inconsistent col spacing in info
  pandas/io/formats/info.py
  pandas/tests/io/formats/test_info.py
Labels: IO Data

#36930 TYP/REF: define comparison methods non-dynamically
  pandas/core/arraylike.py
  pandas/core/arrays/datetimelike.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/ops/__init__.py
  pandas/core/ops/methods.py
  pandas/core/series.py
Labels: Refactor, Typing

#36148 DEPR: disallow tznaive datetimes when indexing tzaware datetimeindex
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/methods/test_truncate.py
Labels: Deprecate, Indexing, Timezones

#36954 TYP/REF: use _cmp_method in EAs
  pandas/core/arrays/boolean.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/string_.py
Labels: Refactor, Typing

#36709 Fix delim_whitespace behavior in read_table, read_csv
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_common.py
Labels: API Design, Bug, IO CSV

#36836 DOC: Update docs on estimated time of running full asv suite (36344)
  doc/source/development/contributing.rst
Labels: Docs

#36873 REF: dont consolidate in is_mixed_type
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals/managers.py
  pandas/tests/frame/test_dtypes.py
  pandas/tests/internals/test_internals.py
Labels: Internals

#36869 DOC: Distinguish between different types of boolean indexing #10492
  doc/source/user_guide/indexing.rst
Labels: Docs, Index, hacktoberfest-accepted

#36959 TYP: core.missing, ops.docstrings, internals.ops, internals.managers, io.html
  pandas/core/internals/managers.py
  pandas/core/missing.py
  pandas/core/ops/docstrings.py
  pandas/io/html.py
  setup.cfg
Labels: Typing

#36964 REF/TYP: use OpsMixin for logical methods
  pandas/core/arraylike.py
  pandas/core/ops/__init__.py
  pandas/core/ops/methods.py
  pandas/core/series.py
  pandas/tests/extension/arrow/arrays.py
Labels: Refactor

#36929 TYP: define Index.any, Index.all non-dynamically
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
Labels: Numeric

#36931 TYP: define RangeIndex methods non-dynamically
  pandas/core/indexes/range.py
  setup.cfg
Labels: Typing

#36518 Fix grammatical errors
  doc/source/getting_started/intro_tutorials/03_subset_data.rst
  doc/source/getting_started/intro_tutorials/04_plotting.rst
Labels: Docs

#36848 REF: IndexOpsMixin wrapping
  pandas/core/base.py
  pandas/core/indexes/base.py
  pandas/core/series.py
Labels: Refactor

#36946 REGR: Make DateOffset immutable
  doc/source/whatsnew/v1.1.4.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Frequency, Regression, Timeseries

#36967 TYP: consistent return types blocks
  pandas/core/internals/blocks.py
Labels: Refactor, Typing

#36966 CLN: remove unnecessary BoolBlock.replace
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#36952 CLN: dont special-case should_store, CategoricalBlock
  pandas/core/internals/blocks.py
Labels: Categorical, Internals

#36962 BUG/API: tighter checks on DTI/TDI.equals
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/tests/indexes/datetimelike.py
  pandas/tests/indexes/timedeltas/test_constructors.py
Labels: Numeric

#36987 Fix test_unstack
  pandas/tests/extension/base/reshaping.py
Labels: ExtensionArray, Testing

#36969 DOC: make rename docs consistent
  pandas/core/frame.py
Labels: Docs

#36993 CI: xfail intermittently-failing tests
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_groupby.py
Labels: CI

#36911 BUG: RollingGroupby not respecting sort=False
  doc/source/whatsnew/v1.1.4.rst
  pandas/core/groupby/grouper.py
  pandas/tests/window/test_grouper.py
Labels: Bug, Window

#36284 DOC: Fixed type hints for GroupBy.{any, all}
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#36945 use-python-language-in-pip-to-conda
  .pre-commit-config.yaml
Labels: CI

#36992 Backport PR #36946 on branch 1.1.x (REGR: Make DateOffset immutable)
  doc/source/whatsnew/v1.1.4.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Frequency

#37002 Backport PR #36911: BUG: RollingGroupby not respecting sort=False
  doc/source/whatsnew/v1.1.4.rst
  pandas/core/groupby/grouper.py
  pandas/tests/window/test_grouper.py
Labels: Window

#37003 Backport PR #36753 on branch 1.1.x: BUG: Segfault with string Index when using Rolling after Groupby
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Window

#36950 REGR: Allow positional arguments in DataFrame.agg
  doc/source/whatsnew/v1.1.4.rst
  pandas/core/frame.py
  pandas/tests/frame/apply/test_frame_apply.py
Labels: Apply, Regression

#37005 Backport PR #36950 on branch 1.1.x (REGR: Allow positional arguments in DataFrame.agg)
  doc/source/whatsnew/v1.1.4.rst
  pandas/core/frame.py
  pandas/tests/frame/apply/test_frame_apply.py
Labels: Apply

#37004 CI: isort fixup on 1.1.x
  pandas/_libs/hashtable.pxd
  pandas/_libs/khash.pxd
  pandas/_libs/missing.pxd
  pandas/_libs/tslibs/ccalendar.pxd
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/offsets.pxd
  pandas/_libs/tslibs/period.pxd
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/util.pxd
  pandas/_libs/util.pxd
  pandas/tests/tseries/offsets/test_offsets.py
Labels: CI

#36999 CLN: Move _aggregate and _aggregate_multiple_funcs to core.aggregation
  pandas/core/aggregation.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/window/rolling.py
Labels: Apply, Clean

#36934 TST: RollingGroupby.count with closed specified
  doc/source/whatsnew/v1.2.0.rst
  pandas/tests/window/test_grouper.py
Labels: Testing, Window

#37009 CLN: standardize values coercion in Blocks
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#36567 REF: Remove rolling window fixed algorithms
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/common.py
  pandas/core/window/indexers.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_rolling.py
Labels: Refactor, Window

#37013 DOC: pandas.Index.astype says it raises ValueError instead of TypeError
  pandas/core/indexes/base.py
Labels: Docs

#36903 TYP: io.json._json, util._decorators
  pandas/io/json/_json.py
  pandas/plotting/_matplotlib/converter.py
  pandas/util/_decorators.py
  setup.cfg
Labels: Typing

#36924 TYP: check_untyped_defs core.indexes.base
  pandas/core/indexes/base.py
  pandas/io/formats/printing.py
  setup.cfg
Labels: Typing

#37027 TST: insert 'match' to bare pytest raises in pandas/tests/tools/test_…
  pandas/tests/tools/test_to_datetime.py
Labels: Error Reporting, Testing, hacktoberfest-accepted

#37026 TST: insert 'match' to bare pytest raises in pandas/tests/test_flags.py
  pandas/tests/test_flags.py
Labels: Error Reporting, Testing, hacktoberfest-accepted

#36989 TYP: generic, series, frame
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/series/methods/test_count.py
  setup.cfg
Labels: Typing

#36847 CI: pin pymysql #36465
  ci/deps/travis-37-cov.yaml
Labels: CI, Dependencies, IO SQL

#37019 CLN/REF: de-duplicate DatetimeTZBlock.setitem
  pandas/core/internals/blocks.py
Labels: Indexing, Internals

#37017 REF/TYP: define NDFrame numeric methods non-dynamically
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Typing

#37018 CLN: require td64 in TimeDeltaBlock
  pandas/core/internals/blocks.py
  pandas/core/missing.py
Labels: Missing-data, Timedelta

#35769 BUG: Raise ValueError instead of bare Exception in sanitize_array
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/construction.py
  pandas/tests/series/test_constructors.py
Labels: Constructors, Error Reporting, Series

#37021 CLN: collected cleanups, warning suppression in tests
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/io/pytables.py
  pandas/tests/extension/test_external_block.py
  pandas/tests/frame/apply/test_frame_transform.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/common.py
  pandas/tests/io/__init__.py
  pandas/tests/io/excel/__init__.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/test_common.py
Labels: Testing

#37032 DOC: Group relevant df.mask/df.where examples together
  pandas/core/generic.py
Labels: Docs

#36043 DOC: add semicolons to suppress text repr of matplotlib objects in visualization.rst
  doc/source/user_guide/visualization.rst
Labels: Docs, Stale, Visualization

#36961 TYP: use OpsMixin for DecimalArray
  pandas/tests/extension/decimal/array.py
Labels: Refactor, Typing

#36965 CLN: share to_native_types
  pandas/core/internals/blocks.py
Labels: Clean

#36979 CLN: re-wrap docstrings in pandas\compat\numpy\function.py
  pandas/compat/numpy/function.py
Labels: Clean

#36982 FIX: fix cleanup warnings for errorbar timeseries
  pandas/tests/plotting/test_frame.py
Labels: Clean, Testing, Visualization

#36943 REF/TYP: define methods non-dynamically for SparseArray
  pandas/core/arrays/sparse/array.py
  setup.cfg
Labels: Refactor, Typing

#36998 BUG: DataFrame.diff with dt64 and NaTs
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_diff.py
Labels: Bug, Timeseries
