Repository pandas-dev/pandas, pull requests merged in 2020-09, with the labels that each got.

#35999 BUG: None in Float64Index raising TypeError, should return False
  doc/source/whatsnew/v1.1.2.rst
  pandas/_libs/index.pyx
  pandas/tests/indexes/numeric/test_indexing.py
Labels: Bug, Indexing

#35066 DOC: Remove mypy from pre commit
  .pre-commit-config.yaml
Labels: Style, Typing

#36023 Comma cleanup for #35925
  pandas/tests/frame/test_analytics.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_reshape.py
Labels: Clean, Style

#36013 Backport PR #36011 on branch 1.1.x (CI: suppress another setuptools warning)
  pandas/tests/util/test_show_versions.py
Labels: CI

#36009 Backport PR #35936: (REGR: Fix inplace updates on column to set correct values)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/internals/managers.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/frame/test_block_internals.py
Labels: Categorical, Missing-data

#36035 CI: pin s3fs for Windows py37_np18 on 1.1.x
  ci/deps/azure-windows-37.yaml
Labels: CI

#36025 TYP: add type annotation to `_xlwt.py` #36024
  pandas/io/excel/_xlwt.py
  setup.cfg
Labels: Typing

#36026 DOC: Update documentation for pd.Interval if string endpoints are not allowed anymore
  pandas/_libs/interval.pyx
Labels: Docs

#36007 TYP: misc typing cleanup in core/indexes/multi.py
  pandas/core/indexes/multi.py
Labels: Typing

#36029 remove trailing commas for #35925
  pandas/io/parquet.py
  pandas/io/parsers.py
  pandas/io/pytables.py
Labels: Clean, Style

#36017 TYP: annotate plotting._matplotlib.misc
  pandas/plotting/_matplotlib/misc.py
  pandas/plotting/_matplotlib/style.py
Labels: Typing

#36041 Backport PR #35999 on branch 1.1.x (BUG: None in Float64Index raising TypeError, should return False)
  doc/source/whatsnew/v1.1.2.rst
  pandas/_libs/index.pyx
  pandas/tests/indexes/numeric/test_indexing.py
Labels: Indexing

#36016 TYP: Annotate plotting stacker
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Typing

#36039 Backport PR #35938 on branch 1.1.x (REGR: Fix comparison broadcasting over array of Intervals)
  doc/source/whatsnew/v1.1.2.rst
  pandas/_libs/interval.pyx
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/scalar/interval/test_arithmetic.py
  pandas/tests/scalar/interval/test_interval.py
Labels: Interval

#36022 TYP/CLN: cleanup `_openpyxl.py`, add type annotation #36021
  ci/deps/azure-37-locale_slow.yaml
  ci/deps/azure-37-minimum_versions.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/excel/_openpyxl.py
  setup.cfg
Labels: Clean, Typing

#36053 CLN: _wrap_applied_output
  pandas/core/groupby/generic.py
Labels: Apply, Clean, Groupby

#36048 CI: pin setuptools on 1.1.x
  ci/setup_env.sh
Labels: CI

#36020 REF: implement Block._replace_list
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Internals, Refactor

#36015 BUG: PeriodIndex.get_loc incorrectly raising ValueError instead of KeyError
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/grouper.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_indexing.py
Labels: Indexing, Period

#36012 CI: Unpin MyPy
  environment.yml
  pandas/_config/config.py
  pandas/core/common.py
  pandas/core/computation/expr.py
  pandas/core/indexes/frozen.py
  pandas/core/resample.py
  requirements-dev.txt
  setup.cfg
Labels: CI, Typing

#36000 ENH: vendor typing_extensions
  pandas/_vendored/__init__.py
  pandas/_vendored/typing_extensions.py
  setup.cfg
Labels: Typing

#35778 Added numba as an argument
  doc/source/user_guide/computation.rst
  doc/source/user_guide/enhancingperf.rst
Labels: Docs, Window

#35937 BUG: BlockSlider not clearing index._cache
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/reduction.pyx
  pandas/tests/groupby/test_allowlist.py
Labels: Internals

#36045 BUG: NDFrame.replace wrong exception type, wrong return when size==0
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/generic.py
  pandas/tests/series/methods/test_replace.py
Labels: Error Reporting

#35852 API: replace dropna=False option with na_sentinel=None in factorize
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/algorithms.py
  pandas/core/base.py
  pandas/core/groupby/grouper.py
  pandas/tests/base/test_factorize.py
  pandas/tests/test_algos.py
Labels: API Design, Docs, Testing

#36067 TYP: update setup.cfg
  setup.cfg
Labels: Typing

#36068 TYP: statically define attributes in plotting._matplotlib.core
  pandas/plotting/_matplotlib/core.py
Labels: Typing

#36051 BUG: frame._item_cache not cleared when Series is altered
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/generic.py
  pandas/tests/frame/test_missing.py
  pandas/tests/indexing/test_chaining_and_caching.py
Labels: Bug, Indexing

#36057 CLN remove unnecessary trailing commas
  pandas/tests/arithmetic/test_interval.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arrays/boolean/test_logical.py
Labels: Clean

#36071 Backport PR #35852 on branch 1.1.x (API: replace dropna=False option with na_sentinel=None in factorize)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/algorithms.py
  pandas/core/base.py
  pandas/core/groupby/grouper.py
  pandas/tests/base/test_factorize.py
  pandas/tests/test_algos.py
Labels: API Design

#36072 Backport PR #36051 on branch 1.1.x (BUG: frame._item_cache not cleared when Series is altered)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/generic.py
  pandas/tests/frame/test_missing.py
  pandas/tests/indexing/test_chaining_and_caching.py
Labels: Indexing

#36049 CLN: rename private functions used across modules
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/misc.py
  pandas/plotting/_matplotlib/style.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
Labels: Clean, Style

#35991 TYP: misc typing in core\indexes\base.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
Labels: Typing

#36077 DOC: Fix typo of `=!` to `!=` in docstring
  pandas/core/ops/docstrings.py
Labels: Docs

#36073 CLN clearing unnecessary trailing commas
  pandas/tests/scalar/test_na_scalar.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/series/methods/test_argsort.py
  pandas/tests/series/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/series/methods/test_unstack.py
  pandas/tests/series/test_cumulative.py
  pandas/tests/test_algos.py
Labels: Clean, Style

#36034 TYP: Postponed Evaluation of Annotations (PEP 563)
  pandas/core/algorithms.py
  pandas/core/construction.py
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Typing

#35848 BUG: Index.get_slice_bounds does not accept datetime.date or tz naive datetime.datetimes
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/base_class/test_indexing.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/test_numeric.py
Labels: Bug, Timeseries

#35900 REF: use BlockManager.apply for cython_agg_blocks, apply_blockwise
  pandas/core/groupby/generic.py
  pandas/core/internals/managers.py
  pandas/core/window/rolling.py
Labels: Internals, Refactor

#28394 Optionally disallow duplicate labels
  doc/source/reference/frame.rst
  doc/source/reference/general_utility_functions.rst
  doc/source/reference/series.rst
  doc/source/user_guide/duplicates.rst
  doc/source/user_guide/index.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/__init__.py
  pandas/_testing.py
  pandas/core/api.py
  pandas/core/flags.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/tests/api/test_api.py
  pandas/tests/base/test_misc.py
  pandas/tests/frame/test_api.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/generic/test_generic.py
  pandas/tests/series/test_api.py
  pandas/tests/test_flags.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/util/test_assert_series_equal.py
Labels: API Design, metadata

#35681 BUG/ENH: compression for google cloud storage in to_csv
  doc/source/whatsnew/v1.2.0.rst
  pandas/_typing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/formats/csvs.py
  pandas/io/json/_json.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers.py
  pandas/io/pickle.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_xport.py
  pandas/io/sas/sasreader.py
  pandas/io/stata.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_gcs.py
Labels: Compat, IO Google

#36087 DOC: Add trailing dot
  doc/source/development/contributing_docstring.rst
Labels: Docs

#36086 DOC: minor fixes to whatsnew\v1.1.2.rst
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36052 CLN remove unnecessary trailing commas in pandas/io
  pandas/io/sas/sas_xport.py
  pandas/io/stata.py
Labels: Clean, Style

#36090 DOC: add mypy version to whatsnew\v1.2.0.rst
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#35986 DOC: Add Notes about difference to numpy behaviour for ddof in std() GH35985
  pandas/core/generic.py
Labels: Docs

#36095 Backport PR #36086 on branch 1.1.x (DOC: minor fixes to whatsnew\v1.1.2.rst)
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36112 DOC: sync doc/source/whatsnew/v1.1.2.rst on 1.1.x
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36061 BUG: groupby and agg on read-only array gives ValueError: buffer source array is read-only
  doc/source/whatsnew/v1.1.2.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/aggregate/test_cython.py
Labels: Compat, Groupby

#36109 CLN: use IS64 instead of is_platform_32bit #36108
  pandas/_libs/missing.pyx
  pandas/compat/__init__.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/test_algos.py
  pandas/util/_test_decorators.py
Labels: 32bit, Clean

#36118 REGR: ensure closed attribute of IntervalIndex is preserved in pickle roundtrip
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: IO Pickle, Interval, Regression

#36099 TYP: misc fixes for numpy types 2
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/reshape/merge.py
Labels: Typing

#36120 TYP: io
  pandas/io/excel/_util.py
  pandas/io/formats/css.py
  setup.cfg
Labels: Typing

#36119 Backport PR #36118 on branch 1.1.x (REGR: ensure closed attribute of IntervalIndex is preserved in pickle roundtrip)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: IO Pickle, Interval

#36050 BUG: incorrect year returned in isocalendar for certain dates
  doc/source/whatsnew/v1.1.2.rst
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/tests/series/test_datetime_values.py
  pandas/tests/tslibs/test_ccalendar.py
Labels: Bug, Timeseries

#35924 REF: use BlockManager.apply for DataFrameGroupBy.count
  pandas/core/groupby/generic.py
Labels: Internals

#36114 REGR: fix consolidation/cache issue with take operation
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/generic.py
  pandas/tests/frame/test_block_internals.py
Labels: Indexing, Regression

#36107 STY: de-privatize funcs imported cross-module
  pandas/_libs/indexing.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/common.py
  pandas/core/computation/common.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/inference.py
  pandas/core/dtypes/missing.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/nanops.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/util.py
  pandas/core/tools/datetimes.py
  pandas/io/formats/format.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/tslibs/test_parsing.py
Labels: Clean

#36104 STY: De-privatize functions in io.excel imported elsewhere
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_util.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
Labels: Style

#36088 TYP: activate Check for missing error codes
  ci/code_checks.sh
  pandas/core/arrays/datetimelike.py
  pandas/core/groupby/categorical.py
  pandas/io/common.py
  pandas/plotting/_matplotlib/core.py
Labels: Typing

#36128 CLN: remove xfails/skips for no-longer-supported numpys
  pandas/plotting/_matplotlib/style.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/frame/test_analytics.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/series/test_analytics.py
Labels: Compat, Testing

#36127 Backport PR #36050 on branch 1.1.x (BUG: incorrect year returned in isocalendar for certain dates)
  doc/source/whatsnew/v1.1.2.rst
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/tests/series/test_datetime_values.py
  pandas/tests/tslibs/test_ccalendar.py
Labels: Timeseries

#36130 CLN: De-privatize
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexing.py
  pandas/core/util/hashing.py
  pandas/io/formats/format.py
  pandas/io/formats/style.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_indexing.py
Labels: Style

#36098 TYP: misc fixes for numpy types
  pandas/_typing.py
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
Labels: Typing

#36082 Comma cleanup
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/multi/test_isin.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/indexes/timedeltas/test_searchsorted.py
  pandas/tests/indexing/common.py
  pandas/tests/indexing/test_callable.py
  pandas/tests/indexing/test_check_indexer.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/indexing/test_floats.py
Labels: Clean

#36129 CLN: remove unused args/kwargs
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Clean, Groupby

#35951 BUG: Fix DataFrame.groupby().apply() for NaN groups with dropna=False
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/groupby/test_groupby_dropna.py
Labels: Apply, Bug, Groupby

#36121 Bug 29764 groupby loses index name sometimes
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby

#36089 STY: add code check for use of builtin filter function
  ci/code_checks.sh
Labels: Style

#36093 BUG: df.replace with numeric values and str to_replace
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/array_algos/replace.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Algos

#35946 CLN: resolve UserWarning in `pandas/plotting/_matplotlib/core.py` #35945
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_frame.py
Labels: Clean, Visualization

#36125 DOC: add missing data handling info to pd.Categorical docstring
  pandas/core/arrays/categorical.py
Labels: Categorical, Docs

#36101 CLN removing trailing commas
  pandas/tests/io/test_sql.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/reshape/merge/test_merge_index_as_string.py
  pandas/tests/reshape/test_crosstab.py
  pandas/tests/reshape/test_get_dummies.py
Labels: Clean, Style

#36139 Updated series documentation to close #35406
  pandas/core/series.py
Labels: Constructors, Docs, Series

#33821 BUG: repair 'style' kwd handling in DataFrame.plot (#21003)
  doc/source/whatsnew/v1.2.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#35736 BUG/ENH: to_pickle/read_pickle support compression for file ojects
  doc/source/whatsnew/v1.2.0.rst
  pandas/_typing.py
  pandas/core/frame.py
  pandas/io/common.py
  pandas/io/formats/csvs.py
  pandas/io/json/_json.py
  pandas/io/parsers.py
  pandas/io/pickle.py
  pandas/io/stata.py
  pandas/tests/io/test_pickle.py
Labels: IO Data, IO Pickle

#36137 TYP: Check for use of Union[Series, DataFrame] instead of FrameOrSeriesUnion alias
  ci/code_checks.sh
  pandas/core/apply.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/io/pytables.py
Labels: Style, Typing

#36140 TYP: remove string literals for type annotations in pandas\core\frame.py
  pandas/core/frame.py
Labels: Typing

#36144 STY+CI: check for private function access across modules
  Makefile
  ci/code_checks.sh
  pandas/_libs/algos.pyx
  pandas/core/algorithms.py
  pandas/core/arrays/sparse/array.py
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/plotting/_matplotlib/compat.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_misc.py
  scripts/validate_unwanted_patterns.py
Labels: Style

#36143 CLN: unused case in compare_or_regex_search
  pandas/core/array_algos/replace.py
Labels: Clean

#35918 REF: window/test_dtypes.py with pytest idioms
  pandas/tests/window/conftest.py
  pandas/tests/window/test_dtypes.py
Labels: Refactor, Testing

#36145 DOC: add userwarning doc about mpl #35684
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs, Visualization

#35882 BUG: item_cache invalidation in get_numeric_data
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_cov_corr.py
Labels: Bug, Internals

#35914 Make MultiIndex.get_loc raise for unhashable type
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/indexes/multi.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/series/indexing/test_setitem.py
Labels: MultiIndex, Regression

#35637 ENH: Make explode work for sets
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/reshape.pyx
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_explode.py
  pandas/tests/series/methods/test_explode.py
Labels: Enhancement, Reshaping

#36054 BUG: Don't raise when constructing Series from ordered set
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/construction.py
  pandas/tests/series/test_constructors.py
Labels: Bug, Constructors

#36163 Backport PR #35914 on branch 1.1.x (Make MultiIndex.get_loc raise for unhashable type)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/indexes/multi.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/series/indexing/test_setitem.py
Labels: MultiIndex

#36162 Backport PR #36054 on branch 1.1.x (BUG: Don't raise when constructing Series from ordered set)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/construction.py
  pandas/tests/series/test_constructors.py
Labels: Constructors

#36115 REGR: append tz-aware DataFrame with tz-naive values
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/dtypes/concat.py
  pandas/core/internals/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Regression, Reshaping

#35979 BUG: Respect errors="ignore" during extension astype
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/series/methods/test_astype.py
Labels: Bug, Dtypes, ExtensionArray

#36156 STY: De-privatize imported names
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/_libs/parsers.pyx
  pandas/_testing.py
  pandas/compat/__init__.py
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/arrays/masked.py
  pandas/core/computation/check.py
  pandas/core/computation/eval.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/frame.py
  pandas/core/indexes/multi.py
  pandas/core/internals/__init__.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/sorting.py
  pandas/core/window/common.py
  pandas/core/window/ewm.py
  pandas/core/window/rolling.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odfreader.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_pyxlsb.py
  pandas/io/excel/_xlrd.py
  pandas/io/formats/format.py
  pandas/io/formats/printing.py
  pandas/tests/computation/test_compat.py
  pandas/tests/computation/test_eval.py
  pandas/tests/extension/json/array.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/test_pickle.py
  pandas/tests/test_algos.py
  pandas/tests/window/moments/test_moments_consistency_rolling.py
  pandas/tests/window/test_pairwise.py
  pandas/util/_test_decorators.py
Labels: Style

#36154 REF: share more EA methods
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/numpy_.py
Labels: API - Consistency, ExtensionArray

#36146 CLN: Separate transform tests
  pandas/tests/frame/apply/test_frame_apply.py
  pandas/tests/frame/apply/test_frame_transform.py
  pandas/tests/frame/common.py
  pandas/tests/series/apply/test_series_apply.py
  pandas/tests/series/apply/test_series_transform.py
Labels: Apply, Testing

#36155 CLN: backport mpl warning fix to 1.1.2
  doc/source/whatsnew/v1.1.2.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_frame.py
Labels: Visualization

#36160 CLN: _wrap_applied_output
  pandas/core/groupby/generic.py
Labels: Apply, Clean, Groupby

#35604 BUG: allow missing values in Index when calling Index.sort_values
  doc/source/whatsnew/v1.2.0.rst
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/indexes/test_common.py
Labels: Bug, Index, Missing-data

#36094 BUG: extra leading space in to_string when index=False
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_to_latex.py
Labels: Bug, Output-Formatting, Regression

#36167 Backport PR #35979 on branch 1.1.x (BUG: Respect errors="ignore" during extension astype)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/series/methods/test_astype.py
Labels: Dtypes, ExtensionArray

#36166 Backport PR #36115 on branch 1.1.x (REGR: append tz-aware DataFrame with tz-naive values)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/dtypes/concat.py
  pandas/core/internals/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Reshaping, Timezones

#36134 BUG: shows correct package name when import_optional_dependency is ca…
  doc/source/whatsnew/v1.1.2.rst
  pandas/compat/_optional.py
Labels: Build, Error Reporting, IO Excel

#35872 REF: simplify latex formatting
  pandas/io/formats/format.py
  pandas/io/formats/latex.py
  pandas/tests/io/formats/test_to_latex.py
Labels: IO LaTeX, Refactor

#36168 Comma cleanup
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_info.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_usecols.py
Labels: Style

#36192 TST: test_datetime64_factorize on 32bit
  pandas/tests/test_algos.py
Labels: 32bit, Testing

#36188 Backport PR #35882 on branch 1.1.x (BUG: item_cache invalidation in get_numeric_data)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_cov_corr.py
Labels: Internals

#36191 TST: update test_series_factorize_na_sentinel_none for 32bit
  pandas/tests/base/test_factorize.py
Labels: 32bit, Testing

#36187 DOC: move release note for #36155
  doc/source/whatsnew/v1.1.2.rst
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#36181 REF: use _validate_foo pattern in Categorical
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
Labels: Categorical, Indexing, Refactor

#36200 Backport PR #36191 on branch 1.1.x (TST: update test_series_factorize_na_sentinel_none for 32bit)
  pandas/tests/base/test_factorize.py
Labels: 32bit, Testing

#36199 Backport PR #36134: BUG: shows correct package name when import_optional_dependency is ca…
  doc/source/whatsnew/v1.1.2.rst
  pandas/compat/_optional.py
Labels: Build, Error Reporting, IO Excel

#36171 DTA/TDA/PA use self._data instead of self.asi8 for self._ndarray
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/frame/indexing/test_datetime.py
Labels: Compat, Performance

#36164 TST verify groupby doesn't alter unit64s to floats #30859
  pandas/tests/groupby/test_groupby.py
Labels: Dtypes, Groupby, Testing

#36152 Fix compressed multiindex for output of groupby.rolling
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Bug, Groupby, Window

#36202 TST: DataFrame.replace: TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'unicode'
  pandas/tests/frame/methods/test_replace.py
Labels: Numeric, Strings, Testing

#36173 REF: collect methods by topic
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor

#36203 Backport PR #36152 on branch 1.1.x (Fix compressed multiindex for output of groupby.rolling)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Groupby, Window

#36180 REF: implement Categorical._validate_setitem_value
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
Labels: Indexing, Refactor

#36176 COMPAT: match numpy behavior for searchsorted on dt64/td64
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Numeric, Timeseries

#36194 pandas docs json_normalize example
  pandas/io/json/_normalize.py
Labels: Docs, IO JSON

#36208 BUG: GroupbyRolling with an empty frame
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Windows

#36205 DOC: doc fix
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36213 Backport PR #36208 on branch 1.1.x (BUG: GroupbyRolling with an empty frame)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Groupby, Window

#36215 Backport PR #36205 on branch 1.1.x (DOC: doc fix)
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36182 DOC: release date for 1.1.2
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36217 Backport PR #36182 on branch 1.1.x (DOC: release date for 1.1.2)
  doc/source/whatsnew/v1.1.2.rst
Labels: Docs

#36207 Fixed pandas.json_normalize doctests errors
  pandas/io/json/_normalize.py
Labels: Docs, IO JSON

#36141 BUG: copying series into empty dataframe does not preserve dataframe index name
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/frame.py
  pandas/tests/indexing/test_partial.py
Labels: Index, Indexing

#36220 TST: skip test_groupby_rolling_index_changed on 32bit
  pandas/tests/window/test_grouper.py
Labels: 32bit, Testing

#36221 Backport PR #36141 on branch 1.1.x (BUG: copying series into empty dataframe does not preserve dataframe index name)
  doc/source/whatsnew/v1.1.2.rst
  pandas/core/frame.py
  pandas/tests/indexing/test_partial.py
Labels: Index, Indexing

#36222 CLN remove trailing commas
  pandas/tests/io/pytables/test_timezones.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_s3.py
Labels: Style

#36196 CLN: remove unused return value in _create_blocks
  pandas/core/window/rolling.py
Labels: Internals, Window

#36149 Make to_numeric default to correct precision
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/src/parse_helper.h
  pandas/tests/tools/test_to_numeric.py
Labels: Compat, IO CSV

#36206 REF: implement Categorical._box_func, make _box_func a method
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
Labels: ExtensionArray, Refactor

#36178 STY: de-privatize names imported across modules
  pandas/__init__.py
  pandas/_testing.py
  pandas/compat/numpy/__init__.py
  pandas/core/array_algos/masked_reductions.py
  pandas/core/arrays/sparse/accessor.py
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/core/common.py
  pandas/core/computation/engines.py
  pandas/core/computation/expr.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/computation/scope.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/generic.py
  pandas/core/index.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/nanops.py
  pandas/core/ops/__init__.py
  pandas/core/reshape/merge.py
  pandas/io/formats/format.py
  pandas/io/json/_json.py
  pandas/io/parsers.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/generic/test_generic.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/test_common.py
  pandas/tests/test_expressions.py
  pandas/util/_test_decorators.py
Labels: Style

#36183 DOC: Start 1.1.3
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.1.2.rst
  doc/source/whatsnew/v1.1.3.rst
Labels: Docs

#36229 CLN: re-use invalid_comparison in Categorical comparisons
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/series/test_arithmetic.py
Labels: Categorical, Clean

#36223 CLN: w3 formatting
  pandas/io/formats/style.py
  pandas/tests/io/formats/test_style.py
Labels: Styler

#36234 REF: pass setitem to unbox_scalar to de-duplicate validation
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Indexing, Refactor

#36242 Backport PR #36183 on branch 1.1.x (DOC: Start 1.1.3)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.1.2.rst
  doc/source/whatsnew/v1.1.3.rst
Labels: Docs

#36046 REF: simplify CSVFormatter
  pandas/_typing.py
  pandas/core/generic.py
  pandas/io/common.py
  pandas/io/formats/csvs.py
Labels: IO CSV, Refactor

#36193 CLN: remove unnecessary trailing commas on issues #35925
  pandas/tests/arrays/categorical/test_replace.py
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/base/test_conversion.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Style

#36246 DOC: Fixed a broken JSON Table Schema link
  doc/source/user_guide/io.rst
Labels: Docs

#36239 DOC: Improve Index docstrings
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
Labels: Docs

#35317 DOC: Rst Formatting, make sure continuation prompt are used.
  pandas/core/indexing.py
  pandas/io/excel/_base.py
Labels: Docs

#36106 BUG: DataFrame.any with axis=1 and bool_only=True
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/frame.py
  pandas/tests/reductions/test_reductions.py
Labels: Algos, Bug

#35966 BUG: instantiation using a dict with a period scalar
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/interval.py
  pandas/tests/dtypes/cast/test_infer_dtype.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/series/test_constructors.py
Labels: Bug, Constructors, Dtypes, ExtensionArray, Period

#36209 REF: share more EA methods
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/numpy_.py
Labels: ExtensionArray, Refactor

#36237 CLN: simplify Categorical comparisons
  pandas/core/arrays/categorical.py
Labels: Categorical, Clean

#36238 DOC: Update groupby.rst
  doc/source/user_guide/groupby.rst
Labels: Docs

#35704 ENH add na_action to DataFrame.applymap
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/lib.pyx
  pandas/core/frame.py
  pandas/tests/frame/apply/test_frame_apply.py
Labels: Missing-data

#36272 CI: xfail failing parquet test
  pandas/tests/io/test_parquet.py
Labels: CI

#36259 de-privatize imported names
  pandas/compat/numpy/function.py
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/ops/__init__.py
  pandas/core/ops/methods.py
  pandas/io/excel/__init__.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odfreader.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_pyxlsb.py
  pandas/io/excel/_xlrd.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
  pandas/util/_test_decorators.py
Labels: Style
