Repository pandas-dev/pandas, pull requests merged in 2020-11, with the labels that each got.

#37541 REF: make EA reductions, nanops funcs keyword-only
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/boolean.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/nanops.py
Labels: API - Consistency, ExtensionArray

#37457 BUG: BusinessDay.apply_index with offset
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Frequency

#37063 TST: Verify functioning of histtype argument (GH23992)
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_hist_method.py
Labels: Testing, Visualization

#37527 TYP: use typing.final in indexes.base
  pandas/_typing.py
  pandas/core/indexes/base.py
Labels: Typing

#37562 TST: fix xfailing indexing test
  pandas/core/indexing.py
  pandas/tests/indexing/test_indexing.py
Labels: Indexing, Testing

#37563 CLN: remove redundant variable in setitem_with_indexer
  pandas/core/indexing.py
Labels: Clean, Indexing

#37549 TST/REF: collect base tests by method
  pandas/tests/base/test_drop_duplicates.py
  pandas/tests/base/test_misc.py
  pandas/tests/frame/methods/test_drop_duplicates.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/internals/test_internals.py
  pandas/tests/series/test_arithmetic.py
Labels: Testing

#37548 CLN: de-duplicate recode_for_categories
  pandas/core/arrays/categorical.py
Labels: Categorical, Clean

#37551 REF: simplify Index.take, MultiIndex.take
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
Labels: Index, Indexing

#37570 TST: avoid/suppress DeprecationWarnings
  pandas/core/arrays/boolean.py
  pandas/tests/indexes/test_index_new.py
Labels: Testing

#37569 PERF: faster numeric indexes comparisons when self is identical to other
  pandas/core/indexes/numeric.py
  pandas/core/indexes/range.py
Labels: Index, Performance

#37561 REF: move IntervalIndex.equals up to ExtensionIndex.equals
  pandas/core/indexes/extension.py
  pandas/core/indexes/interval.py
Labels: Interval

#37560 REF: move _wrap_joined_index up to NDarrayBackedExtensionIndex
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/extension.py
Labels: ExtensionArray, Index

#37568 BUG: Fix bug in combine_first with string dtype and only NA
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/frame/methods/test_combine_first.py
Labels: NA - MaskedArrays, Reshaping

#37374 DEPR: Index.__and__, __or__, __xor__ behaving as set ops
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/io/formats/excel.py
  pandas/io/json/_json.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexes/timedeltas/test_setops.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/test_strings.py
Labels: Deprecate

#37567 CLN: de-duplicate asof_locs
  pandas/core/indexes/base.py
  pandas/core/indexes/period.py
Labels: Indexing

#37573 TST/REF: collect tests by method
  pandas/tests/frame/methods/test_swapaxes.py
  pandas/tests/frame/test_add_prefix_suffix.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_iteration.py
  pandas/tests/io/test_pickle.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_iteration.py
Labels: Testing

#37479 ENH: Fix output of assert_frame_equal if indexes differ and check_like=True
  doc/source/whatsnew/v1.2.0.rst
  pandas/_testing.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/util/test_assert_index_equal.py
Labels: Testing

#37587 TST: catch FutureWarnings from Index.__and__ deprecation
  pandas/tests/series/test_arithmetic.py
Labels: Deprecate, Testing

#37590 TST/REF: collect indexing tests by method
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_set_value.py
  pandas/tests/indexing/test_callable.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing_slow.py
  pandas/tests/indexing/test_loc.py
Labels: Indexing, Testing

#37588 REF: prelims for single-path setitem_with_indexer
  pandas/core/indexing.py
  pandas/tests/indexing/test_indexing.py
Labels: Indexing, Refactor

#37164 ENH: __repr__ for 2D DTA/TDA
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Output-Formatting

#37595 CLN: de-duplicate _validate_where_value with _validate_setitem_value
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/extension.py
Labels: Indexing, Refactor

#37589 TST/REF: collect tests by method
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_add_prefix_suffix.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_transpose.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_timeseries.py
  pandas/tests/frame/test_timezones.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/methods/test_is_monotonic.py
  pandas/tests/series/methods/test_view.py
  pandas/tests/series/test_analytics.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_period.py
  pandas/tests/series/test_timeseries.py
Labels: Testing

#37545 REF: Categorical.is_dtype_equal -> categories_match_up_to_permutation
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/concat.py
  pandas/core/indexes/category.py
  pandas/core/reshape/merge.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/reshape/merge/test_merge.py
Labels: API - Consistency, Categorical

#37580 CLN refactor non-core
  pandas/_config/config.py
  pandas/_config/localization.py
  pandas/_testing.py
  pandas/_version.py
  pandas/compat/__init__.py
  pandas/conftest.py
Labels: Style

#37585 CLN refactor core/computation
  pandas/core/computation/align.py
  pandas/core/computation/eval.py
  pandas/core/computation/expr.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
Labels: Style

#37596 TST/REF: share method tests between DataFrame and Series
  pandas/conftest.py
  pandas/core/frame.py
  pandas/tests/frame/methods/test_at_time.py
  pandas/tests/frame/methods/test_between_time.py
  pandas/tests/frame/methods/test_to_period.py
  pandas/tests/frame/methods/test_to_timestamp.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/methods/test_at_time.py
  pandas/tests/series/methods/test_between_time.py
  pandas/tests/series/methods/test_to_period.py
  pandas/tests/series/methods/test_to_timestamp.py
Labels: Testing

#37591 BUG: Index.where casting ints to str
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/numeric.py
  pandas/tests/indexes/base_class/test_where.py
  pandas/tests/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexing/test_coercion.py
Labels: Bug, Indexing

#37124 REF: IntervalArray comparisons
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/extension/base/methods.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Interval, Refactor

#36897 regression fix for merging DF with datetime index with empty DF
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_multi.py
Labels: Regression, Reshaping

#37602 ERR: fix error message in Period for invalid frequency
  pandas/_libs/tslibs/period.pyx
  pandas/tests/scalar/period/test_period.py
Labels: Error Reporting, Period

#37608 CLN: remove rebox_native
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Dtypes

#37618 TST/REF: tests.generic
  pandas/tests/frame/methods/test_equals.py
  pandas/tests/frame/methods/test_head_tail.py
  pandas/tests/generic/methods/test_first_valid_index.py
  pandas/tests/generic/methods/test_pipe.py
  pandas/tests/generic/methods/test_reorder_levels.py
  pandas/tests/generic/methods/test_sample.py
  pandas/tests/generic/test_generic.py
Labels: Testing

#37617 TST: collect tests by method
  pandas/tests/frame/methods/test_asfreq.py
  pandas/tests/frame/methods/test_values.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/series/apply/test_series_apply.py
  pandas/tests/series/methods/test_values.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_dtypes.py
  pandas/tests/series/test_period.py
  pandas/tests/series/test_timeseries.py
Labels: Testing

#37616 TST/REF: share tests across Series/DataFrame
  pandas/tests/frame/methods/test_asof.py
  pandas/tests/frame/methods/test_droplevel.py
  pandas/tests/frame/methods/test_first_and_last.py
  pandas/tests/frame/methods/test_head_tail.py
  pandas/tests/frame/methods/test_truncate.py
  pandas/tests/frame/methods/test_tz_convert.py
  pandas/tests/frame/methods/test_tz_localize.py
  pandas/tests/series/methods/test_asof.py
  pandas/tests/series/methods/test_droplevel.py
  pandas/tests/series/methods/test_first_and_last.py
  pandas/tests/series/methods/test_pop.py
  pandas/tests/series/methods/test_truncate.py
Labels: Testing

#37096 Gh 36562 typeerror comparison not supported between float and str
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/algorithms.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/test_sorting.py
Labels: Dtypes, MultiIndex, Numeric

#37612 DOC: Fix punctuation
  pandas/core/generic.py
Labels: Docs

#37564 REGR: pd.to_hdf(..., dropna=True) not dropping missing rows
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_store.py
Labels: IO HDF5, Regression

#37619 TST/REF: parametrize set_axis tests
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/generic/methods/test_set_axis.py
  pandas/tests/series/methods/test_set_name.py
  pandas/tests/series/test_alter_axes.py
Labels: Testing

#37203 CLN: clean color selection in _matplotlib/style
  pandas/plotting/_matplotlib/style.py
  pandas/tests/plotting/test_style.py
Labels: Refactor, Visualization

#37601 DEPR: DataFrame/Series.slice_shift
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/generic.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/generic/test_generic.py
Labels: Deprecate

#37597 REF: re-use _validate_setitem_value in Categorical.fillna
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/indexes/categorical/test_fillna.py
  pandas/tests/series/methods/test_fillna.py
Labels: Categorical, Indexing, Refactor

#37389 PERF: release gil for ewma_time
  pandas/_libs/window/aggregations.pyx
Labels: Window

#36842 BUG: Groupy dropped nan groups from result when grouping over single column
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/lib.pyx
  pandas/core/groupby/ops.py
  pandas/core/sorting.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/window/test_rolling.py
Labels: Groupby, Missing-data

#35973 ENH: implement timeszones support for read_json(orient='table') and astype() from 'object'
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/datetimes.py
  pandas/io/json/_json.py
  pandas/io/json/_table_schema.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/io/json/test_json_table_schema.py
Labels: IO JSON, Timezones

#36997 REF/BUG/TYP: read_csv shouldn't close user-provided file handles
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/parsers.pyx
  pandas/_typing.py
  pandas/core/frame.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/formats/csvs.py
  pandas/io/formats/format.py
  pandas/io/json/_json.py
  pandas/io/orc.py
  pandas/io/parsers.py
  pandas/io/pickle.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_xport.py
  pandas/io/sas/sasreader.py
  pandas/io/stata.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/io/json/test_readlines.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/io/test_compression.py
  pandas/tests/series/methods/test_to_csv.py
Labels: IO CSV

#37539 CI Move unwanted typing checks to pre-commit
  .pre-commit-config.yaml
  ci/code_checks.sh
  scripts/validate_unwanted_patterns.py
Labels: CI, Style

#37623 TST: 32bit dtype compat test_groupby_dropna
  pandas/tests/groupby/test_groupby_dropna.py
Labels: 32bit, Testing

#37461 BUG: Metadata propagation for groupby iterator
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_groupby_subclass.py
Labels: metadata

#37613 BUG: read-only values in cython funcs
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/join.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/libs/test_join.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_timedelta.py
Labels: Bug, Compat, Timeseries

#37581 CLN refactor core/arrays
  pandas/core/arrays/base.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/timedeltas.py
Labels: Style

#37628 Backport PR #37461 on branch 1.1.x: BUG: Metadata propagation for groupby iterator
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_groupby_subclass.py
Labels: metadata

#37381 Fixed Metadata Propogation in DataFrame
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/frame.py
  pandas/core/reshape/merge.py
  pandas/tests/generic/test_finalize.py
Labels: metadata

#37128 TYP: add Shape alias to pandas._typing
  pandas/_typing.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/dtypes/cast.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/ops/array_ops.py
  pandas/io/pytables.py
Labels: Typing

#37630 DOC: Fix typo
  pandas/core/shared_docs.py
Labels: Docs

#37195 CLN: parametrize test_nat_comparisons
  pandas/tests/arithmetic/test_datetime64.py
Labels: Missing-data, Testing

#37632 Added dataclass into dataframe API reference
  pandas/core/frame.py
Labels: Docs

#37583 CLN refactor core/groupby
  pandas/core/groupby/base.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
Labels: Groupby, Style

#37606 BUG: set index of DataFrame.apply(f) when f returns dict (#37544)
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/apply.py
  pandas/tests/frame/apply/test_frame_apply.py
Labels: Apply, Bug

#37571 BUG: to_dict should return a native datetime object for NumPy backed dataframes
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/core/common.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/indexes/interval.py
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/tests/dtypes/cast/test_dict_compat.py
  pandas/tests/frame/methods/test_to_dict.py
  pandas/tests/test_common.py
Labels: Dtypes

#37621 ENH: memory_map for compressed files
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/common.py
  pandas/io/parsers.py
  pandas/tests/io/parser/test_common.py
Labels: IO CSV

#36814 DOC: add example & prose of slicing with labels when index has duplicate labels
  doc/source/user_guide/indexing.rst
Labels: Docs, Indexing, hacktoberfest-accepted

#37636 DOC: Fix typo
  pandas/core/frame.py
Labels: Docs

#37652 BUG: don't suppress OSError in tzlocal
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Timezones, Windows

#37638 TST/REF: collect indexing tests by method
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_sparse.py
  pandas/tests/indexing/test_at.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/indexing/test_timedelta.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_numeric.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Indexing, Testing

#37634 TST/REF: collect tests for get_numeric_data
  pandas/tests/frame/methods/test_get_numeric_data.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_series.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/internals/test_internals.py
  pandas/tests/series/methods/test_get_numeric_data.py
Labels: Testing

#37640 REF: de-duplicate _validate_insert_value with _validate_scalar
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/timedeltas.py
Labels: Clean, Indexing

#37659 CI: catch windows py38 OSError
  pandas/_libs/tslibs/tzconversion.pxd
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/tests/frame/test_reductions.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: CI, Windows

#37679 REF/TST: share some api tests
  pandas/tests/frame/test_api.py
  pandas/tests/series/test_api.py
Labels: Testing

#37666 TST: match matplotlib warning message
  pandas/tests/plotting/test_frame.py
Labels: Testing

#37687 pd.Series.loc.__getitem__ promotes to float64 instead of raising KeyError
  pandas/tests/indexing/test_loc.py
Labels: Indexing, Needs Tests

#37678 TST/REF: misplaced Categorical tests
  pandas/tests/arrays/categorical/test_algos.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/categorical/test_replace.py
  pandas/tests/arrays/categorical/test_take.py
Labels: Categorical, Testing

#37677 REF/TST: collect indexing tests by method
  pandas/tests/frame/indexing/test_categorical.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/test_at.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_numeric.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_item.py
  pandas/tests/series/methods/test_reset_index.py
  pandas/tests/series/methods/test_values.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_dtypes.py
Labels: Indexing, Testing

#37673 CLN: only call _wrap_results one place in nanmedian
  pandas/core/nanops.py
Labels: Algos, Dtypes

#37671 TYP: Index._concat
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
Labels: Typing

#37667 BUG: CategoricalIndex.equals casting non-categories to np.nan
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/category.py
  pandas/tests/indexes/categorical/test_category.py
Labels: Bug, Categorical

#37683 CLN: _replace_single
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Clean, Reshaping

#37688 TYP: make some internal funcs keyword-only
  pandas/core/array_algos/masked_reductions.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/decimal/array.py
Labels: Typing

#37691 REF: make Series._replace_single a regular method
  pandas/core/generic.py
  pandas/core/series.py
Labels: Clean, Reshaping

#37664 REF: simplify cycling through colors
  pandas/plotting/_matplotlib/style.py
Labels: Clean, Testing, Visualization

#37660 REF: implement _wrap_reduction_result
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/nanops.py
Labels: Refactor

#37644 BUG: preserve fold in Timestamp.replace
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_unary_ops.py
Labels: Bug, Timeseries, Timezones

#37689 CLN: Clean indexing tests
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_partial.py
Labels: Clean, Indexing, Testing

#37669 TST: fix warning for pie chart
  pandas/tests/plotting/test_frame.py
Labels: Testing, Visualization

#37426 PERF: reverted change from commit 7d257c69 to solve issue #37081
  pandas/core/frame.py
Labels: Performance

#28102 DataFrameGroupby.boxplot fails when subplots=False
  doc/source/whatsnew/v1.2.0.rst
  pandas/plotting/_matplotlib/boxplot.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Groupby, Visualization

#37547 ENH: Improve error reporting for wrong merge cols
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Error Reporting, Reshaping

#37662 Move inconsistent namespace check to pre-commit, fixup more files
  .pre-commit-config.yaml
  ci/code_checks.sh
  pandas/tests/dtypes/test_inference.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_missing.py
  pandas/tests/groupby/test_quantile.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/datetimes/test_shift.py
  pandas/tests/indexes/period/test_formats.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/timedeltas/test_formats.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_compression.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/test_repr.py
  pandas/tests/window/test_expanding.py
  scripts/check_for_inconsistent_pandas_namespace.py
  scripts/tests/test_inconsistent_namespace_check.py
Labels: Style

#37704 REF: simplify NDFrame.replace, ObjectBlock.replace
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/categorical/test_replace.py
Labels: Clean

#37650 REF: implement Categorical.encode_with_my_categories
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/concat.py
Labels: Categorical, Refactor

#37657 BUG: unpickling modifies Block.ndim
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/internals/managers.py
  pandas/tests/io/test_pickle.py
Labels: Compat, ExtensionArray

#37658 REF: dont support dt64tz in nanmean
  pandas/core/nanops.py
  pandas/tests/test_nanops.py
Labels: Timeseries, Timezones

#37702 CLN: Simplify groupby head/tail tests
  pandas/tests/groupby/test_nth.py
Labels: Clean, Groupby, Testing

#37675 Bug in loc raised for numeric label even when label is in Index
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing

#37696 REF: implement replace_regex, remove unreachable branch in ObjectBlock.replace
  pandas/core/array_algos/replace.py
  pandas/core/internals/blocks.py
Labels: Categorical, Clean

#37713 Backport PR #37657 on branch 1.1.x: BUG: unpickling modifies Block.ndim
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/internals/managers.py
  pandas/tests/io/test_pickle.py
Labels: Compat, ExtensionArray

#37556 TYP: Check untyped defs (except vendored)
  pandas/_testing.py
  pandas/core/apply.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/string_.py
  pandas/core/base.py
  pandas/core/computation/expr.py
  pandas/core/computation/ops.py
  pandas/core/computation/scope.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/base.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/reshape/merge.py
  pandas/io/excel/_base.py
  pandas/io/formats/console.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/parsers.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_misc.py
  setup.cfg
Labels: Typing

#37710 REF: remove ObjectBlock._replace_single
  pandas/core/internals/blocks.py
Labels: Refactor

#37274 TST: fix warnings on multiple subplots
  pandas/tests/plotting/common.py
  pandas/tests/plotting/test_hist_method.py
Labels: Testing

#37717 TST: move and reformat latex_na_rep test
  pandas/tests/io/formats/test_to_latex.py
Labels: IO LaTeX, Testing

#37661 BUG: RollingGroupby when groupby key is in the index
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Bug, Groupby, Window

#37718 TST: improve readability using dedent in test_to_string.py
  pandas/tests/io/formats/test_to_string.py
Labels: Clean, Testing

#37714 CLN: cleanup, deduplicate plotting/test_frame
  pandas/tests/plotting/test_frame.py
Labels: Clean, Testing, Visualization

#37706 BUG: Fix return of missing values when applying loc to single level of MultiIndex
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Indexing, MultiIndex

#37697 DOC: capitalize Gregorian and fix word order
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#37557 ENH: Improve numerical stability for window functions skew and kurt
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_rolling.py
Labels: Window

#37720 TST: Add test for missing fillvalue in categorical dtype
  pandas/tests/indexes/categorical/test_reindex.py
Labels: Categorical, Needs Tests

#37721 CLN: clean categorical indexes tests
  pandas/tests/indexing/test_categorical.py
Labels: Clean

#37729 TST/REF: collect indexing tests by method
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_sparse.py
  pandas/tests/indexing/test_at.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/indexing/test_timedelta.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Indexing, Testing

#37719 TST: Add test for KeyError with MultiIndex
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Indexing, MultiIndex, Needs Tests

#37723 REF: collect boilerplate in _datetimelike_compat
  pandas/core/nanops.py
Labels: Clean, Numeric, Timeseries

#37724 REF: remove Categorical._validate_listlike, unbox_listlike
  pandas/core/arrays/categorical.py
  pandas/core/groupby/categorical.py
  pandas/core/indexes/category.py
  pandas/core/reshape/merge.py
Labels: Categorical, Refactor

#37559 Add ss02
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#37700 DOC: Add caveat to to_stata with version=119
  pandas/core/frame.py
Labels: Docs, IO Stata

#37701 DOC: Highlight pre-commit section
  doc/source/development/code_style.rst
  doc/source/development/contributing.rst
Labels: Docs

#37738 TYP: fix mypy ignored error in pandas/io/formats/latex.py
  pandas/io/formats/latex.py
Labels: Typing

#37741 Backport PR #37661 on branch 1.1.x: BUG: RollingGroupby when groupby key is in the index
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Groupby, Window

#37739 TYP: fix mypy ignored err in pandas/io/formats/format.py
  pandas/io/formats/format.py
Labels: Typing

#37734 TST: use default_axes=True where multiple plots
  pandas/tests/plotting/test_frame.py
Labels: Clean, Testing, Visualization

#37694 TYP: @final for NDFrame methods
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/io/formats/excel.py
Labels: Typing

#37735 TST: parametrize in tests/plotting/test_frame.py
  pandas/tests/plotting/test_frame.py
Labels: Testing, Visualization

#37607 BUG: nunique not ignoring both None and np.nan
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/base.py
  pandas/tests/base/test_unique.py
Labels: Bug, Missing-data

#37637 DOC: test organization
  doc/source/development/index.rst
  doc/source/development/test_writing.rst
  pandas/tests/series/methods/test_item.py
Labels: Docs, Testing

#37731 REF: use extract_array in DataFrame.combine_first
  pandas/core/frame.py
Labels: Refactor

#37384 replace Appender decorator with doc
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/core/shared_docs.py
Labels: Docs

#37736 BUG: read_html - file path cannot be pathlib.Path type
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: IO HTML

#37727 ENH: Raise when subsetting columns on groupby with axis=1
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_groupby.py
Labels: Enhancement, Error Reporting, Groupby

#37745 TYP: follow-up to #37723
  pandas/core/nanops.py
Labels: Typing

#37703 remove unnecessary use of Appender
  pandas/core/generic.py
Labels: Docs

#37767 CI: remove unused import
  pandas/core/generic.py
Labels: CI

#37762 BUG: clean the figure windows created by tests
  pandas/tests/plotting/test_converter.py
Labels: Testing, Unreliable Test

#37655 TST: split up tests/plotting/test_frame.py into subdir & modules #34769
  pandas/tests/plotting/frame/__init__.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/frame/test_frame_groupby.py
  pandas/tests/plotting/frame/test_frame_subplots.py
Labels: Testing, Visualization

#37791 CLN: remove unreachable in interpolate_with_fill
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#37789 CLN: remove no-longer-reachable Block.replace code
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#37788 REF: implement Block._putmask_simple for non-casting putmask
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Internals, Refactor

#37797 TYP: fix mypy ignored error in pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_fsspec.py
Labels: Typing

#37780 BUG: adding Timedelta to DatetimeIndex raising incorrectly
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/indexes/datetimes/test_misc.py
Labels: Regression, Timedelta, Timeseries

#37778 BUG: Groupby head/tail with axis=1 fails
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_nth.py
Labels: Bug, Groupby

#37775 CLN: _get_daily_rule
  pandas/core/arrays/datetimelike.py
  pandas/tseries/frequencies.py
Labels: Clean, Frequency

#37773 TST/REF: collect Index setop, indexing tests
  pandas/tests/indexes/common.py
  pandas/tests/indexes/numeric/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_indexing.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/test_setops.py
Labels: Testing

#37747 CLN: remove unused min_count argument in libgroupby.group_nth
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
Labels: Clean, Groupby

#37733 API: consistently raise TypeError for invalid-typed fill_value
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/indexes/multi.py
  pandas/tests/arrays/categorical/test_take.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_period.py
  pandas/tests/extension/test_interval.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/categorical/test_reindex.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/series/methods/test_shift.py
Labels: Error Reporting, Indexing

#37730 TST/REF: collect/parametrize tests from tests.generic
  pandas/tests/frame/test_alter_axes.py
  pandas/tests/frame/test_logical_ops.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_logical_ops.py
  pandas/tests/generic/test_to_xarray.py
  pandas/tests/series/test_dtypes.py
Labels: Refactor, Testing

#37726 TST: Add test for filling new rows through reindexing MultiIndex
  pandas/tests/frame/methods/test_reindex.py
Labels: Indexing, MultiIndex, Needs Tests

#37722 BUG: loc.__getitem__[[na_value]] with CategoricalIndex containing NAs
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/common.py
  pandas/core/indexes/category.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/test_common.py
Labels: Bug, Categorical, Indexing

#37363 REGR: Notebook (html) repr of DataFrame no longer follows min_rows/max_rows settings
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: IO HTML, Output-Formatting, Regression

#37806 Backport PR #37780 on branch 1.1.x (BUG: adding Timedelta to DatetimeIndex raising incorrectly)
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/indexes/datetimes/test_misc.py
Labels: Timedelta, Timeseries

#37611 Add tests for categorical with null ea as input
  pandas/tests/arrays/categorical/test_constructors.py
Labels: Categorical, ExtensionArray, Testing

#37776 BUG: Bug in xs ignored droplevel
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/generic.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/series/indexing/test_xs.py
Labels: Indexing, MultiIndex
