Repository pandas-dev/pandas, pull requests merged in 2020-12, with the labels that each got.

#38099 BUG: fix wrong error message in deprecated 2D indexing of Series with datetime values
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/series/indexing/test_getitem.py
Labels: Deprecate, Regression

#38168 BUG/CLN: Minimize number of ResourceWarnings
  pandas/io/excel/_base.py
  pandas/io/excel/_xlwt.py
  pandas/io/parsers.py
  pandas/io/sas/sasreader.py
  pandas/tests/io/excel/test_openpyxl.py
  pandas/tests/io/excel/test_style.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/excel/test_xlsxwriter.py
  pandas/tests/io/parser/test_multi_thread.py
Labels: IO Data

#38057 PERF: fix regression in creation of resulting index in RollingGroupby
  asv_bench/benchmarks/rolling.py
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_rolling.py
Labels: Groupby, Performance, Window

#38178 BUG: preserve nullable dtype for float result in IntegerArray/BooleanArray arithmetic ops
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/arrays/boolean.py
  pandas/core/arrays/integer.py
  pandas/tests/arrays/boolean/test_arithmetic.py
  pandas/tests/arrays/boolean/test_function.py
  pandas/tests/arrays/floating/test_function.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/arrays/masked/test_arithmetic.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_floating.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_string.py
  pandas/tests/series/test_arithmetic.py
Labels: NA - MaskedArrays

#38208 Revert "ENH: Improve performance for df.__setitem__ with list-like indexers"
  asv_bench/benchmarks/indexing.py
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/indexing.py
Labels: Indexing, Performance

#38211 Backport PR #38057: PERF: fix regression in creation of resulting index in RollingGroupby
  asv_bench/benchmarks/rolling.py
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_grouper.py
Labels: Groupby, Performance, Window

#38209 CI/TST: fix CI with numpy dev for changed error message / dev version
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/util/test_show_versions.py
Labels: Error Reporting

#38212 CI: xfail test_area_lim
  pandas/tests/plotting/frame/test_frame.py
Labels: CI, Visualization

#38106 BUG in Series.interpolate: limit_area/limit_direction kwargs with method="pad"/"bfill" have no effect
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Bug, Missing-data

#35029 DEPR: Deprecate using `xlrd` engine for read_excel
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/excel/test_xlrd.py
Labels: Blocker, Deprecate, IO Excel

#38189 DOC: fix redirects to user guide in README
  README.md
Labels: Docs

#38190 REF: IntervalIndex.intersection match pattern in other intersection methods
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
Labels: Interval, Refactor

#38111 BUG: name retention in Index.intersection
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/test_setops.py
Labels: Bug, Constructors, Index, MultiIndex

#38154 CLN: improve is_unique check in Index.intersection
  pandas/core/indexes/base.py
Labels: Clean, MultiIndex

#38105 REF: implement _should_compare
  pandas/core/indexes/base.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_indexing.py
Labels: Index

#38194 DOC: Clarify development environment creation for documentation changes
  doc/source/development/contributing.rst
Labels: Docs

#38018 Using os.PathLike instead of pathlib.Path (#37979)
  pandas/_typing.py
  pandas/io/common.py
Labels: Typing

#38162 REF: implement _ea_wrap_cython_operation
  pandas/core/groupby/ops.py
Labels: Groupby, Refactor

#38170 BUG: unexpected merge_ordered results caused by wrongly groupby
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_ordered.py
Labels: Bug, Reshaping

#38171 TST: add comment that plotting tests are slow
  pandas/tests/plotting/common.py
Labels: Docs, Testing

#38192 DOC: Fixed to_pickle compression argument list 'gzip' > 'gz'
  pandas/core/generic.py
Labels: Docs

#38199 Remove duplicate entry on series.rst
  doc/source/reference/series.rst
Labels: Docs

#38206 TST: Added dataframe constructor tests confirming order is preserved with standard Python dicts
  pandas/tests/frame/test_constructors.py
Labels: Constructors, Testing

#38207 Rewrite dict literal for files in pandas/tests/frame
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/frame/methods/test_to_records.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_reductions.py
Labels: Style

#38205 Rewrite dict literal for files in tests/groupby & ./pandas/tests/dtypes
  pandas/tests/dtypes/test_inference.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Style

#38203 Rewrite dict literal for files in ./pandas/tests/tools/ and ./pandas/tests/resample/
  pandas/tests/io/test_parquet.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/tools/test_to_numeric.py
  pandas/tests/util/test_assert_extension_array_equal.py
  pandas/tests/util/test_assert_index_equal.py
  pandas/tests/util/test_assert_interval_array_equal.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Style

#38228 CI: pin pip to 20.2 on numpy-dev build
  ci/deps/azure-38-numpydev.yaml
Labels: CI

#38197 BUG: name attr in RangeIndex.intersection
  doc/source/whatsnew/v1.2.0.rst
  pandas/conftest.py
  pandas/core/indexes/range.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/indexes/ranges/test_setops.py
Labels: Refactor

#38223 TST: tighten testing assertions
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/pytables/test_store.py
Labels: Testing

#38219 Update Dockerfile to use conda-forge compilers
  Dockerfile
Labels: Build

#38215 TST: add cases for nearest_workday and before_nearest_workday
  pandas/tests/tseries/holiday/test_observance.py
Labels: Frequency, Testing

#38204 Retain views with listlike indexers setitem
  asv_bench/benchmarks/indexing.py
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexing.py
  pandas/core/internals/managers.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Indexing, Performance

#38195 BUG: DataFrame.idxmin/idxmax with mixed dtypes
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_reductions.py
Labels: Bug, Reductions

#38187 BUG: groupby.rank for dt64tz, period dtypes
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_rank.py
Labels: Groupby

#38175 ENH: support nanoseconds in Period constructor
  doc/source/whatsnew/v1.2.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/tests/scalar/period/test_period.py
Labels: Period

#38164 REF: avoid try/except in wrapping in cython_agg_blocks
  pandas/core/groupby/generic.py
Labels: Groupby, Refactor

#38173 BUG: array-like quantile fails on column groupby
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_quantile.py
Labels: Bug, Groupby

#38071 BUG: DataFrame.loc returning empty result with negative stepsize for MultiIndex
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_slice.py
Labels: Indexing, MultiIndex

#38070 BUG: Index.drop raising Error when Index has duplicates
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexes/test_base.py
Labels: Index, MultiIndex

#38244 REGR: unstack on 'int' dtype prevent fillna to work
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Regression, Reshaping

#38157 BUG: assert_frame_equal exception for datetime #37609
  doc/source/whatsnew/v1.2.0.rst
  pandas/_testing.py
  pandas/tests/util/test_assert_frame_equal.py
Labels: Dtypes, ExtensionArray, Testing

#38235 REF: casting in _python_agg_general
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Groupby, Refactor

#38237 REF: consolidate result-casting in _cython_operation
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Groupby, Refactor

#38238 TST: revert too-ambitious part of #38223
  pandas/tests/io/pytables/test_store.py
Labels: Frequency, Testing

#38241 TST: setitem in presence of duplicate cols
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, Testing

#38252 CI: delete unused import in groupby/groupby.py
  pandas/core/groupby/groupby.py
Labels: CI

#38259 Backport PR #38244: REGR: unstack on 'int' dtype prevent fillna to work
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/test_reshape.py
Labels: Reshaping

#38248 PERF: timeseries comparison ops
  pandas/core/arrays/datetimelike.py
Labels: Performance, Timeseries

#38242 TST: string representation of IntervalIndex
  pandas/tests/indexes/interval/test_formats.py
Labels: Interval, Output-Formatting

#38253 REF: simplify _cython_operation return
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Groupby, Refactor

#38255 TST: split unfocused groupby test
  pandas/tests/groupby/test_function.py
Labels: Groupby, Testing

#38245 BUG: CategoricalDtype.__repr__ with RangeIndex categories
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Categorical, Output-Formatting, Regression

#38265 Rewrite dict call to literals
  pandas/core/indexes/numeric.py
Labels: Style

#38263 C408 rewrite dict call to dict literals
  pandas/core/arrays/interval.py
  pandas/tests/io/pytables/test_store.py
Labels: Style

#38275 CLN: assorted cleanups
  pandas/_libs/reduction.pyx
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/base.py
  pandas/tests/series/indexing/test_xs.py
Labels: Clean

#38176 The error message for unsupported index on shift() could be more explicit
  pandas/core/indexes/base.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/multi/test_analytics.py
Labels: Error Reporting

#38268 BUG: name retention in Index.difference corner cases
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/test_setops.py
Labels: Bug

#38284 TST: fixturize unfocused test
  pandas/tests/groupby/test_function.py
Labels: Groupby, Testing

#38283 REF: de-duplicate intersection methods
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/range.py
Labels: Index, Refactor

#38251 ENH: implement _should_compare/_is_comparable_dtype for all Index subclasses
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/tests/indexes/test_base.py
Labels: Index, Refactor

#38280 pandas/core/strings/accesory.py Unnecessary dict call - rewrite as a literal #38138
  pandas/core/strings/accessor.py
Labels: Style

#38276 Removing dict calls
  pandas/core/arrays/floating.py
  pandas/core/arrays/numpy_.py
Labels: Style

#38260 C408 fix
  pandas/tests/io/json/test_normalize.py
  pandas/tests/io/json/test_ujson.py
Labels: Style

#38277 BUG: Validate drop_duplicates ignore_index argument for bool
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_drop_duplicates.py
Labels: Error Reporting

#38279 BUG: isin numeric vs string
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Dtypes, Performance

#38272 BUG: DataFrame.apply with axis=1 and EA dtype
  pandas/core/apply.py
  pandas/tests/frame/apply/test_frame_apply.py
Labels: Apply, ExtensionArray, Regression

#38225 ENH: context-manager for chunksize/iterator-reader
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/parsers.py
  pandas/io/sas/sasreader.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_readlines.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/parser/test_dtypes.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/sas/test_xport.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_stata.py
  pandas/tests/reshape/concat/test_invalid.py
Labels: IO CSV

#38298 New dict call fixings #38138
  pandas/core/arrays/base.py
  pandas/core/computation/pytables.py
  pandas/core/indexes/base.py
  pandas/core/ops/methods.py
  pandas/io/pytables.py
Labels: Style

#38290 REF: move common arithmetic ops from Integer/FloatingArray to NumericArray
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numeric.py
Labels: NA - MaskedArrays, Refactor

#38264 REF: implement Groupby idxmin, idxmax without fallback
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_function.py
Labels: Groupby, Refactor

#38257 BUG: groupby.apply on the NaN group drops values with original axes return
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_apply.py
Labels: Apply, Bug, Groupby

#38200 TYP: @final in groupby
  pandas/core/groupby/base.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
Labels: Groupby, Typing

#38266 BUG: Inserting array of same size with Series.loc raises ValueError
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexers.py
  pandas/tests/indexing/test_indexers.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing

#38282 BUG: IntervalIndex.union with mismatched dtypes both empty
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/interval/test_setops.py
Labels: Bug, Index

#38309 TST: tighten xfails
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/base/test_conversion.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/series/test_arithmetic.py
Labels: Testing

#38330 REGR: Groupby first/last/nth treats None as an observation
  doc/source/whatsnew/v1.1.5.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/test_nth.py
Labels: Groupby, Missing-data, Regression

#38333 Backport PR #38330: REGR: Groupby first/last/nth treats None as an observation
  doc/source/whatsnew/v1.1.5.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/test_nth.py
Labels: Groupby, Missing-data

#38332 REGR: Fix Index construction from Sparse["datetime64[ns]"]
  doc/source/whatsnew/v1.1.5.rst
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_constructors.py
Labels: Index, Sparse, Timeseries

#38318 DOC: 1.1.5 release date
  doc/source/whatsnew/v1.1.5.rst
Labels: Docs

#38327 CLN: dtypes.cast
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
Labels: Clean, Typing

#38320 CLN: fix C408 #38138
  pandas/core/arrays/base.py
  pandas/core/computation/expressions.py
  pandas/core/dtypes/dtypes.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/methods/test_to_records.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/pytables/test_timezones.py
Labels: Style

#38319 Removed unnecessary dict calls
  pandas/tests/io/parser/test_quoting.py
  pandas/tests/io/parser/test_usecols.py
Labels: Style

#38310 TST: avoid skipping in frame arith test
  pandas/tests/frame/test_arithmetic.py
Labels: Testing

#38304 TST: share transform tests
  pandas/tests/frame/apply/test_frame_transform.py
  pandas/tests/series/apply/test_series_transform.py
  pandas/tests/series/conftest.py
Labels: Apply, Testing

#38014 BUG: Fixes plotting with nullable integers (#32073)
  doc/source/whatsnew/v1.2.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame.py
Labels: NA - MaskedArrays, Visualization

#38321 CLN: remove now-unnecesary coerce_to_dtypes
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
Labels: Clean, Dtypes

#38306 TYP/BUG: fix passing incorrect type to interpolate_1d
  pandas/core/generic.py
  pandas/core/missing.py
Labels: Missing-data, Typing

#38302 BUG: Clean intersection and fix resulting names when MultiIndex are equal
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/period/test_setops.py
Labels: Clean, MultiIndex

#38313 REF: simplify casting of scalars to array
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/tests/dtypes/cast/test_infer_dtype.py
Labels: Clean, Dtypes

#38337 REF: avoid accessing private iloc methods
  pandas/core/frame.py
Labels: Indexing, Refactor

#38345 TST: revert too-ambitious
  pandas/tests/io/pytables/test_store.py
Labels: Testing

#38307 TYP: datetimelike
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
Labels: Timeseries, Typing

#38146 ENH: add "schema" kwarg to io.sql.get_schema method
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL

#38346 PERF: isin casting integers to object
  pandas/core/algorithms.py
Labels: Algos, Performance

#38317 DEPR: xlwt for writing excel files
  doc/source/user_guide/io.rst
  doc/source/user_guide/options.rst
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/config_init.py
  pandas/core/generic.py
  pandas/io/excel/_base.py
  pandas/io/formats/excel.py
  pandas/tests/io/excel/__init__.py
  pandas/tests/io/excel/test_xlwt.py
Labels: Deprecate, IO Excel

#38291 ENH: use correct dtype in groupby cython ops when it is known (without try/except)
  pandas/core/dtypes/cast.py
  pandas/core/groupby/ops.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/test_function.py
  pandas/tests/resample/test_datetime_index.py
Labels: Groupby, Refactor

#38361 DOC: minor fixes to 1.2 release notes
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#38360 CI: activate azure pipelines/github actions on 1.2.x
  .github/workflows/ci.yml
  azure-pipelines.yml
Labels: CI

#38354 TST: a weird bug with numpy + DataFrame with duplicate columns
  pandas/tests/frame/test_nonunique_indexes.py
Labels: Indexing, Testing

#38349 REF: call _ensure_valid_index inside _sanitize_column
  pandas/core/frame.py
Labels: Clean, Indexing

#38359 DOC: Start v1.3.0 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.3.0.rst
Labels: Docs

#38363 Backport PR #38361 on branch 1.2.x (DOC: minor fixes to 1.2 release notes)
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#38366 Backport PR #38360 on branch 1.2.x (CI: activate azure pipelines/github actions on 1.2.x)
  .github/workflows/ci.yml
  azure-pipelines.yml
Labels: CI

#38322 REF: use lighter-weight casting function
  pandas/core/dtypes/cast.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/interval.py
  pandas/core/tools/numeric.py
Labels: Dtypes, Refactor

#37690 DOC: add examples to insert and update generally
  pandas/core/frame.py
Labels: Docs

#38351 BUG: item_cache invalidation
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_sort_values.py
Labels: Bug, Refactor

#38348 Removed unused strict struct member in tokenizer
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
Labels: Clean, IO CSV

#38326 CLN: use with instead of try finally in `io/stata.py`
  pandas/io/stata.py
Labels: IO Stata, Style

#38369 DOC: sync xarray version
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#38308 REF: implement Index._get_indexer
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
Labels: Index, Indexing

#38350 TST: add message matches to pytest.raises in various tests GH30999
  pandas/tests/io/pytables/test_complex.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/plotting/frame/test_frame_subplots.py
Labels: Testing

#38383 CLN: C408 Unnecessary dict call - rewrite as a literal #38138
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/parser/test_comment.py
  pandas/tests/io/parser/test_dialect.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_index_col.py
  pandas/tests/io/parser/test_na_values.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_skiprows.py
Labels: Style

#38371 Backport PR #38369 on branch 1.2.x (DOC: sync xarray version)
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#38374 CLN: typo fixup in 1.2.0 whatsnew
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#38384 Backport PR #38374 on branch 1.2.x (CLN: typo fixup in 1.2.0 whatsnew)
  doc/source/whatsnew/v1.2.0.rst
Labels: Docs

#38385 CLN: fix C408 #38138
  pandas/tests/io/parser/test_common.py
  setup.cfg
Labels: Clean, Style

#38216 Corrected the grammar in Exception
  pandas/core/apply.py
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Error Reporting

#38389 REF: consolidate NDFrame._iset_item, _set_item with DataFrame methods
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Indexing, Internals

#35100 Document Tips for Debugging C Extensions
  doc/source/development/debugging_extensions.rst
  doc/source/development/index.rst
  setup.py
Labels: Docs

#38395 Backport PR #35100 on branch 1.2.x (Document Tips for Debugging C Extensions)
  doc/source/development/debugging_extensions.rst
  doc/source/development/index.rst
  setup.py
Labels: Docs

#38396 BUG: algos.rank with readonly values
  pandas/_libs/algos.pyx
  pandas/tests/util/test_show_versions.py
Labels: Compat

#38409 Backport PR #38396 on branch 1.2.x (BUG: algos.rank with readonly values)
  pandas/_libs/algos.pyx
  pandas/tests/util/test_show_versions.py
Labels: Compat

#38404 REF: simplify casting
  pandas/core/arrays/sparse/array.py
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
Labels: Dtypes, Refactor

#38289 CLN: remove internal usage of integer_array()
  pandas/core/arrays/__init__.py
  pandas/core/arrays/integer.py
  pandas/tests/arrays/integer/conftest.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/integer/test_construction.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/arrays/integer/test_repr.py
  pandas/tests/arrays/test_array.py
  pandas/tests/base/test_conversion.py
  pandas/tests/extension/test_integer.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_get_numeric_data.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Clean, NA - MaskedArrays

#38372 REF: de-duplicate get_indexer methods
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/categorical/test_indexing.py
  pandas/tests/indexes/common.py
Labels: Index, Indexing, Refactor

#38398 REF: implement sanitize_masked_array
  pandas/core/construction.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Constructors, Refactor

#37073 ENH: Add MultiIndex.dtypes
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_get_set.py
Labels: Enhancement, MultiIndex

#38400 REF: simplify internals.construction
  pandas/core/internals/construction.py
Labels: Internals

#38323 CLN: Implement multiindex handling for get_op_result_name
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/ops/common.py
  pandas/tests/indexes/multi/test_setops.py
Labels: Clean, MultiIndex

#38411 REF: move __from_arrow__ to common base class for numeric masked arrays
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numeric.py
Labels: NA - MaskedArrays, Refactor

#38335 BUG: iloc.__setitem__ with dict value and mixed dtypes
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
Labels: Bug, Indexing

#38232 TST: Assert msg with pytest raises in pandas/tests/extension/base
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/reduce.py
Labels: Testing

#38431 BUG: read_csv raising TypeError for engine=c with names and parse_dates
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: IO CSV

#38329 REF/TYP: Rename ABCIndexClass->ABCIndex and use cast
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/core/common.py
  pandas/core/construction.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/generic.py
  pandas/core/dtypes/missing.py
  pandas/core/indexers.py
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/core/ops/array_ops.py
  pandas/core/ops/common.py
  pandas/core/strings/accessor.py
  pandas/core/tools/numeric.py
  pandas/core/tools/timedeltas.py
  pandas/core/tools/times.py
  pandas/core/util/hashing.py
  pandas/io/formats/csvs.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/dtypes/test_generic.py
Labels: Refactor, Typing

#38331 BUG: first("1M") returning two months when first day is last day of month
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_first_and_last.py
Labels: Bug, Frequency

#38428 REF: simplify maybe_upcast
  pandas/core/dtypes/cast.py
Labels: Dtypes, Refactor

#38421 REF: simplify maybe_casted_values
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
Labels: Dtypes, Refactor

#38407 CLN: remove coerce_float keyword from construction.internals
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Constructors, Refactor

#38373 REF: share IntervalIndex.intersection with Index.intersection
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/interval.py
  pandas/tests/dtypes/cast/test_find_common_type.py
  pandas/tests/indexes/interval/test_setops.py
Labels: Index, Refactor

#38405 BUG: Series/DataFrame construction from scalars
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/tests/dtypes/cast/test_construct_from_scalar.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, Constructors, Timedelta

#38406 BUG: DataFrame.to_markdown with an empty frame
  ci/deps/azure-38.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v1.3.0.rst
  pandas/compat/_optional.py
  pandas/tests/io/formats/test_to_markdown.py
Labels: Dependencies, Output-Formatting

#38247 BUG: Limited available colors
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/formats/_color_data.py
  pandas/io/formats/excel.py
  pandas/tests/io/formats/test_to_excel.py
Labels: Visualization

#38448 Revert "BUG: first("1M") returning two months when first day is last day of month"
  doc/source/whatsnew/v1.2.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_first_and_last.py
Labels: Bug, Frequency

#38445 BUG: read_csv usecols and names parameters inconsistent between c and python
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/parsers.py
  pandas/tests/io/parser/test_usecols.py
Labels: Bug, IO CSV

#38435 Backport PR #38247 on branch 1.2.x (BUG: Limited available colors)
  doc/source/whatsnew/v1.2.0.rst
  pandas/io/formats/_color_data.py
  pandas/io/formats/excel.py
  pandas/tests/io/formats/test_to_excel.py
Labels: Visualization

#38440 TYP: pandas/core/frame.py (easy: bool/str)
  pandas/core/frame.py
Labels: Typing

#38452 ENH: Improve error message when names and usecols do not match for read_csv with engine=c
  doc/source/whatsnew/v1.3.0.rst
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/test_usecols.py
Labels: Error Reporting, IO CSV

#38102 REF: use _validate_fill_value in Index.insert
  pandas/core/dtypes/cast.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/tests/dtypes/cast/test_promote.py
Labels: Index, Missing-data, Refactor

#38430 Fixed #38419 - BUG: set_index screws up the dtypes on empty DataFrames
  pandas/tests/frame/methods/test_set_index.py
Labels: Index, Reshaping

#38423 CLN: MultiIndex.union align with Index.union()
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_setops.py
Labels: MultiIndex
