Repository pandas-dev/pandas, pull requests merged in 2020-07, with the labels that each got.

#35071 CLN: remove unnecessary get_timezone calls
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Clean, Timezones

#35073 REF: de-duplicate month_offset in tslibs.fields
  pandas/_libs/tslibs/ccalendar.pxd
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/fields.pyx
Labels: Clean, Timeseries

#35068 PERF: Timestamp.normalize
  asv_bench/benchmarks/tslibs/timestamp.py
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Performance, Timezones

#33522 BUG: Fixed concat with reindex and extension types
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/internals/concat.py
  pandas/core/reshape/concat.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/test_categorical.py
Labels: ExtensionArray, Reshaping

#35064 Assorted ujson Cleanups
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Clean, IO JSON

#35079 TYP: stronger typing in libtimezones
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
Labels: Clean, Timezones

#35072 Add test apply dtype
  pandas/tests/frame/test_apply.py
Labels: Groupby, Testing

#35082 CLN: stronger typing in libtimezones
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
Labels: Clean

#35074 TST: Test for groupby transform on categorical column
  pandas/tests/groupby/test_categorical.py
Labels: Testing

#34493 Test for pd.to_sql column error if data contains -np.inf
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Dtypes, IO SQL

#35093 TYP: types for tz_compare
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
  pandas/core/arrays/datetimes.py
Labels: Timezones, Typing

#35091 BENCH: implement asvs for ints_to_pydatetime
  asv_bench/benchmarks/tslibs/tslib.py
Labels: Benchmark

#35088 CLN: tighter typing in libconversion
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: Clean, Timezones, Typing

#35086 CLN: Removed unreached else block GH33478
  pandas/core/groupby/generic.py
Labels: Clean, Groupby

#35075 BENCH: implement asvs for get_resolution
  asv_bench/benchmarks/tslibs/resolution.py
Labels: Benchmark

#35061 Fixed #34859: Added support for '0' and '1' in BooleanArray._from_sequence_of_strings method
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/arrays/boolean.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/io/parser/test_dtypes.py
Labels: IO CSV, NA - MaskedArrays

#35003 BUG: DataFrame.melt gives unexpected result when column "value" already exists
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/reshape/melt.py
  pandas/tests/reshape/test_melt.py
Labels: Deprecate, Reshaping

#35087 PERF: tz_convert/tz_convert_single
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/tests/tslibs/test_conversion.py
Labels: Performance, Timezones

#35096 TYP: type for get_timezone
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
Labels: Clean, Timezones

#35110 DOC: Fix code formatting and typos in Series.tz_localize
  pandas/core/generic.py
Labels: Docs

#35101 PERF: Fix quantile perf regression
  pandas/util/_validators.py
Labels: Performance, Regression

#35117 CLN: convert lambda to function
  pandas/io/formats/printing.py
Labels: Clean, Output-Formatting

#34962 REF: dont consolidate in BlockManager.equals
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_internals.py
Labels: Internals, Reshaping

#35139 CI: pin sphinx <= 3.1.1 for autodoc failure
  environment.yml
  requirements-dev.txt
Labels: CI, Docs

#35085 Fix numpy warning
  pandas/conftest.py
Labels: Missing-data, Testing

#35099 TYP: type unit as str
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Clean

#35111 BUG: reset_index is passing a bad dtype to NumPy
  pandas/core/frame.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/series/methods/test_reset_index.py
Labels: Dtypes, ExtensionArray, Indexing, Regression, Reshaping

#35125 TST: Add test for category equalness on applies (#21239)
  pandas/tests/frame/test_apply.py
Labels: Testing

#34839 ENH: Add support for calculating EWMA with a time component
  asv_bench/benchmarks/rolling.py
  doc/source/user_guide/computation.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/generic.py
  pandas/core/window/ewm.py
  pandas/tests/window/conftest.py
  pandas/tests/window/test_ewm.py
Labels: Enhancement, Window

#35107 TYP: get_utcoffset
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
  pandas/core/arrays/datetimes.py
  pandas/tseries/frequencies.py
Labels: Timezones, Typing

#35113 PERF: ints_to_pydatetime
  pandas/_libs/tslib.pyx
Labels: Performance, Timeseries

#35133 CLN: unused imports in tslibs
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Clean

#35141 DEPR: Deprecate n-dim indexing for Series
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexers.py
  pandas/core/series.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/interval/test_base.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/indexing/test_getitem.py
Labels: Deprecate, Indexing

#34880 TST: Add test to verify align behaviour on CategoricalIndex
  pandas/tests/frame/methods/test_align.py
Labels: Categorical, Indexing, Testing

#35146 Move mark registration
  pandas/conftest.py
  setup.cfg
Labels: CI

#35102 REF: standardize tz_convert_single usage
  pandas/_libs/tslibs/timestamps.pyx
Labels: Refactor, Timeseries

#35104 CLN: tz_convert is always from UTC
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/tests/tslibs/test_conversion.py
Labels: Clean, Timeseries

#35106 PERF: tz_localize(None) from dst, asvs
  asv_bench/benchmarks/tslibs/tz_convert.py
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Benchmark, Performance, Timeseries

#35108 REF: implement tz_localize_to_utc_single
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/tzconversion.pxd
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Refactor, Timeseries

#35128 CLN: remove the circular import in NDFrame.dtypes
  pandas/core/generic.py
Labels: Clean

#35119 REF: make ccalendar self-contained
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/fields.pyx
Labels: Refactor, Timeseries

#34343 Added missing import in boxplot_frame_groupby example
  pandas/plotting/_core.py
Labels: Docs, Visualization

#35151 CI: move py36 slow to azure (#34776)
  .travis.yml
  ci/azure/posix.yml
  ci/deps/azure-36-slow.yaml
  ci/setup_env.sh
Labels: CI

#35114 BUG: get_loc with time object matching NaT micros
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/fields.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_indexing.py
Labels: Bug, Indexing, Timeseries

#35118 CLN: Index._format_with_header (remove kwargs etc.)
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/range.py
  pandas/io/formats/style.py
Labels: Clean, Index

#35120 TYP, DOC, CLN:SeriesGroupBy._wrap_applied_output
  pandas/core/groupby/generic.py
Labels: Groupby, Typing

#35021 CI: add validate_unwanted_patterns to known_third_parties
  scripts/tests/test_validate_unwanted_patterns.py
  setup.cfg
Labels: Style

#34908 BUG: incorrect type when indexing sparse dataframe with iterable
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_sparse.py
Labels: Indexing, Sparse, Testing

#35166 Fixed Series.apply performance regression
  pandas/core/apply.py
Labels: Apply, Performance

#35140 Fix regression on datetime in MultiIndex
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_datetime.py
Labels: Indexing, MultiIndex

#35121 TST add test case for drop_duplicates
  pandas/tests/frame/methods/test_drop_duplicates.py
Labels: Missing-data, Testing

#27801 ENH: Add argmax and argmin to ExtensionArray
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/arrays/base.py
  pandas/core/sorting.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_sparse.py
Labels: ExtensionArray

#35022 TST: add test to ensure that df.groupby() returns the missing categories when grouping on 2 pd.Categoricals
  pandas/tests/groupby/test_categorical.py
Labels: Categorical, Groupby, Testing

#34366 DOC - Moving Tips and Trick from wiki to Style Guide - added Reading …
  doc/source/development/code_style.rst
Labels: Docs

#34985 ENH: concat of nullable int + bool preserves int dtype
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/arrays/integer.py
  pandas/tests/arrays/integer/test_concat.py
Labels: ExtensionArray, NA - MaskedArrays, Reshaping

#35168 REF: collect get_dst_info-using functions in tslibs.vectorized
  asv_bench/benchmarks/tslibs/resolution.py
  asv_bench/benchmarks/tslibs/tslib.py
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pxd
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/_libs/tslibs/vectorized.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/datetimes.py
  pandas/tests/tslibs/test_api.py
  setup.py
Labels: Refactor, Timeseries

#35149 ASV: tslibs.fields
  asv_bench/benchmarks/tslibs/fields.py
Labels: Benchmark

#35103 TYP: maybe_get_tz
  pandas/_libs/tslibs/timezones.pxd
  pandas/_libs/tslibs/timezones.pyx
  pandas/tests/tslibs/test_timezones.py
Labels: Timezones, Typing

#34954 Fix Issue 34748 - read in datetime as MultiIndex for column headers
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/parsers.py
  pandas/tests/io/data/excel/test_datetime_mi.ods
  pandas/tests/io/data/excel/test_datetime_mi.xls
  pandas/tests/io/data/excel/test_datetime_mi.xlsb
  pandas/tests/io/data/excel/test_datetime_mi.xlsm
  pandas/tests/io/data/excel/test_datetime_mi.xlsx
  pandas/tests/io/excel/test_readers.py
Labels: Bug, IO Excel

#35098 BUG: fix union_indexes not supporting sort=False for Index subclasses
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexes/api.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/test_common.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/test_strings.py
Labels: Bug, Reshaping

#35183 Json Visual Clutter cleanup
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Clean

#35154 REF: remove always-UTC arg from tz_convert, tz_convert_single
  asv_bench/benchmarks/tslibs/tz_convert.py
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/tzconversion.pxd
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/scalar/timestamp/test_timezones.py
  pandas/tests/tslibs/test_api.py
  pandas/tests/tslibs/test_conversion.py
  pandas/tseries/frequencies.py
Labels: Clean, Timezones

#35181 TST Verifiy that dropna returns none when called inplace (#35179)
  pandas/tests/frame/test_missing.py
Labels: Reshaping, Testing

#35175 DOC: fix code snippets for generic indexing
  doc/source/user_guide/cookbook.rst
Labels: Docs, Indexing

#35171 PERF: periodarr_to_dt64arr
  asv_bench/benchmarks/tslibs/period.py
  pandas/_libs/tslibs/period.pyx
Labels: Performance, Period

#34863 PERF: to speed up rendering of styler
  asv_bench/asv.conf.json
  asv_bench/benchmarks/io/style.py
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/test_style.py
Labels: IO HTML, Performance, Styler

#35199 REF: re-use get_firstbday, get_lastbday in fields.pyx
  pandas/_libs/tslibs/ccalendar.pxd
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tslibs/test_liboffsets.py
Labels: Frequency

#35090 TST: update gbq service account key
  ci/travis_encrypt_gbq.sh
  ci/travis_gbq.json.enc
  ci/travis_gbq_config.txt
  ci/travis_process_gbq_encryption.sh
  pandas/tests/io/test_gbq.py
Labels: IO Google

#34996 TST: df.loc[:, 'col'] returning a view, but df.loc[df.index, 'col'] returning a copy
  pandas/tests/indexing/test_loc.py
Labels: Indexing, Testing

#35083 No fastcall attribute in POWER platform
  pandas/_libs/src/ujson/lib/ultrajson.h
  pandas/_libs/src/ujson/lib/ultrajsondec.c
  pandas/_libs/src/ujson/lib/ultrajsonenc.c
Labels: Build

#34363 TST: category isin on frame
  pandas/tests/frame/methods/test_isin.py
Labels: Algos, Categorical

#35195 PERF: MonthOffset.apply_index
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Frequency, Performance

#34931 BUG: fix IntegerArray astype with copy=True/False
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/arrays/integer.py
  pandas/core/arrays/masked.py
  pandas/tests/arrays/integer/test_dtypes.py
Labels: NA - MaskedArrays

#35205 CLN: tighten types to get_rule_month
  pandas/_libs/tslibs/parsing.pxd
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
  pandas/tests/tslibs/test_libfrequencies.py
Labels: Frequency

#35198 REF: remove libresolution
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tslibs/test_api.py
  pandas/tseries/frequencies.py
  setup.py
Labels: Clean

#35035 BUG: fix read_excel error for header=None and index_col as list #31783
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_readers.py
Labels: Bug, IO Excel

#35213 Add xarray copyright notice to comply with reuse under Apache License
  LICENSES/XARRAY_LICENSE
Labels: Docs

#29116 ENH: Implement Keyword Aggregation for DataFrame.agg and Series.agg
  pandas/core/aggregation.py
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/series.py
  pandas/tests/frame/apply/__init__.py
  pandas/tests/frame/apply/test_apply_relabeling.py
  pandas/tests/frame/apply/test_frame_apply.py
  pandas/tests/series/apply/__init__.py
  pandas/tests/series/apply/test_apply_relabeling.py
  pandas/tests/series/apply/test_series_apply.py
Labels: Enhancement, Groupby

#35210 Tst return none inplace series
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/series/methods/test_replace.py
  pandas/tests/series/methods/test_reset_index.py
  pandas/tests/series/methods/test_sort_values.py
  pandas/tests/series/methods/test_truncate.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_datetime_values.py
  pandas/tests/series/test_missing.py
Labels: Missing-data, Testing

#35212 Fix strange behavior when precision display option is zero (#20359)
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Bug, Output-Formatting

#35170 DOC: Add pint pandas ecosystem docs
  doc/source/ecosystem.rst
  web/pandas/community/ecosystem.md
Labels: Docs, Web

#34448 BUG: ensure_timedelta64ns overflows
  doc/source/reference/general_utility_functions.rst
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/conversion.pyx
  pandas/core/internals/blocks.py
  pandas/errors/__init__.py
  pandas/tests/tslibs/test_api.py
  pandas/tests/tslibs/test_conversion.py
Labels: Bug, Timedelta

#35221 ASV: asvs for normalize functions
  asv_bench/benchmarks/tslibs/normalize.py
Labels: Benchmark

#35167 CLN: remove unused freq kwarg in libparsing
  pandas/_libs/tslibs/parsing.pyx
Labels: Clean, Internals

#35222 Fixing a confused method name in 02_read_write.rst
  doc/source/getting_started/intro_tutorials/02_read_write.rst
Labels: Docs, IO Excel

#35152 BUG: transform with nunique should have dtype int64
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/common.py
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_nunique.py
Labels: Bug, Dtypes, Groupby, Timeseries

#34830 REF: move registry, Registry to dtypes.base
  pandas/api/extensions/__init__.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/arrays/string_.py
  pandas/core/construction.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_period.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Dtypes, Refactor

#34875 DF.__setitem__ creates extension column when given extension scalar
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/frame.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, ExtensionArray, Indexing

#35220 TYPING/DOC: Move custom type to _typing and add whatsnew
  doc/source/whatsnew/v1.1.0.rst
  pandas/_typing.py
  pandas/core/aggregation.py
Labels: Docs, Typing

#35216 TST add corner cases in test_constructors
  pandas/tests/frame/test_constructors.py
Labels: Testing

#35232 Tst verify return none in tests/frame
  pandas/tests/frame/indexing/test_categorical.py
  pandas/tests/frame/indexing/test_mask.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_clip.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/methods/test_rename_axis.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_reshape.py
  pandas/tests/frame/test_to_csv.py
Labels: Testing

#35242 CLN: annotate
  pandas/_libs/hashing.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/strptime.pyx
Labels: Clean, Typing

#33458 TST: concat(..., copy=False) with datetime tz-aware data raises ValueError: cannot create a DatetimeTZBlock without a tz
  pandas/tests/dtypes/test_concat.py
Labels: Reshaping, Testing, Timezones

#35260 CI: Ignore setuptools distutils warning
  ci/deps/azure-36-32bit.yaml
  ci/deps/azure-36-locale.yaml
  ci/deps/azure-36-locale_slow.yaml
  ci/deps/azure-36-minimum_versions.yaml
  ci/deps/azure-36-slow.yaml
  ci/deps/azure-37-locale.yaml
  ci/deps/azure-37-numpydev.yaml
  ci/deps/azure-macos-36.yaml
  ci/deps/azure-windows-36.yaml
  ci/deps/azure-windows-37.yaml
  ci/deps/travis-36-cov.yaml
  ci/deps/travis-36-locale.yaml
  ci/deps/travis-37-arm64.yaml
  ci/deps/travis-37.yaml
  ci/deps/travis-38.yaml
  environment.yml
  pandas/tests/util/test_show_versions.py
  requirements-dev.txt
Labels: CI

#35237 TST: GH20676 Verify equals operator for list of Numpy arrays
  pandas/tests/generic/test_generic.py
  pandas/tests/series/methods/test_equals.py
Labels: Algos, Testing

#35255 REF: make tz_convert match pattern elsewhere
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Refactor, Timezones

#35230 TST verify return none inplace in tests/indexing
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexing/multiindex/test_indexing_slow.py
  pandas/tests/indexing/multiindex/test_ix.py
  pandas/tests/indexing/multiindex/test_sorted.py
  pandas/tests/indexing/multiindex/test_xs.py
Labels: Testing

#35253 BUG: ValueError on groupby with categoricals
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_categorical.py
Labels: Bug, Categorical, Groupby

#35274 CI: pin pytest in minimum versions
  ci/deps/azure-36-minimum_versions.yaml
Labels: CI

#35190 Be specific about more indexes or values
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/internals/construction.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Error Reporting

#34887 Deprecate `center` on `df.expanding`
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/core/window/expanding.py
  pandas/tests/window/moments/test_moments_consistency_expanding.py
  pandas/tests/window/test_api.py
  pandas/tests/window/test_expanding.py
Labels: Bug, Deprecate, Window

#35273 Move API changes to appropriate sections
  doc/source/whatsnew/v1.1.0.rst
Labels: Docs

#34291 TYP: Add type hints to pd.read_html
  pandas/io/html.py
Labels: IO HTML, Typing

#35244 ASV: dt64arr_to_periodarr
  asv_bench/benchmarks/tslibs/period.py
Labels: Benchmark, Period

#34798 API: Make describe changes backwards compatible
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_describe.py
  pandas/tests/series/methods/test_describe.py
Labels: API Design, Deprecate

#30858 BUG: aggregations were getting overwritten if they had the same name
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Groupby, Reshaping

#35122 CLN: remove kwargs in Index.format
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
Labels: Clean, Typing

#35277 Revert "BUG: fix union_indexes not supporting sort=False for Index subclasses"
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexes/api.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/test_common.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/test_strings.py
Labels: Regression

#35165 Fixed apply_index
  doc/source/reference/offset_frequency.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Deprecate, Frequency

#35229 Place the calculation of mask prior to the calls of comp in replace_list to improve performance
  pandas/core/internals/managers.py
Labels: Performance, Strings

#35182 ENH: Add compute.use_numba configuration for automatically using numba
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/config_init.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/util/numba_.py
  pandas/core/window/rolling.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
  pandas/tests/util/test_numba.py
  pandas/tests/window/test_numba.py
Labels: numba

#33091 ENH: Add index option to_markdown()
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/io/formats/test_to_markdown.py
Labels: Enhancement, IO Data

#35184 WIP CI: MacPython failing TestPandasContainer.test_to_json_large_numbers
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Testing

#35289 xfail failing 32-bit tests
  pandas/compat/__init__.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: 32bit

#34877 BUG/TST: Read from Public s3 Bucket Without Creds
  pandas/io/common.py
  pandas/tests/io/test_s3.py
Labels: IO CSV, Testing

#35295 CI: xfail failing 32-bit tests
  pandas/tests/window/test_api.py
  pandas/tests/window/test_apply.py
  pandas/tests/window/test_grouper.py
  pandas/tests/window/test_timeseries_window.py
Labels: 32bit, CI

#35254 BUG: Use correct ExtensionArray reductions in DataFrame reductions
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/frame.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/frame/test_analytics.py
Labels: ExtensionArray, Numeric

#33247 BUG: Fix droped result column in groupby with as_index False
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Groupby, Reshaping

#35233 TST: Verify filtering operations on DataFrames with categorical Series
  pandas/tests/frame/indexing/test_categorical.py
Labels: Categorical, Indexing

#34402 BUG/API: other object type check in Series/DataFrame.equals
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/series/test_subclass.py
Labels: API Design

#35236 TST: added tests for sparse and date range quantiles
  pandas/tests/frame/methods/test_quantile.py
Labels: Algos, Sparse, Testing

#35187 Add date overflow message to tz_localize (#32967)
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/tests/scalar/timestamp/test_timezones.py
Labels: Error Reporting, Timeseries

#35231 BUG: Inconsistent behavior in Index.difference
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexes/numeric.py
  pandas/tests/indexes/test_numeric.py
Labels: Bug, Index, Numeric

#35287 Fix indexing, reindex on all-sparse SparseArray.
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/indexing/test_sparse.py
Labels: Regression, Sparse

#35304 TST: xfail more 32-bits
  pandas/tests/window/test_rolling.py
Labels: 32bit, Testing

#35306 Revert BUG: Ensure same index is returned for slow and fast path in …
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/reduction.pyx
  pandas/tests/groupby/test_apply.py
Labels: Regression

#34906 BUG: Groupby with as_index=True causes incorrect summarization
  pandas/tests/groupby/test_function.py
Labels: Groupby, Testing

#35298 TST: Remove deprecated use of apply_index
  pandas/tests/tseries/offsets/test_offsets_properties.py
Labels: Frequency

#35312 pin numpy<1.19 in doc build
  environment.yml
  requirements-dev.txt
Labels: Build, Docs

#35308 CLN: consistent EA._reduce signatures
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/string_.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/decimal/array.py
Labels: Clean, ExtensionArray, Typing

#35234 TST add test for dtype consistency with pd replace #23305
  pandas/tests/frame/methods/test_replace.py
Labels: Categorical, Testing

#34756 BUG: DataFrameGroupBy.quantile raises for non-numeric dtypes rather than dropping columns
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_quantile.py
Labels: Bug, Groupby, Regression

#35303 Fixed reindexing arith with duplicates
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/ops/__init__.py
  pandas/tests/frame/test_arithmetic.py
Labels: Indexing, Numeric

#35038 BUG: DataFrame.append with empty DataFrame and Series with tz-aware datetime value allocated object column
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/dtypes/concat.py
  pandas/core/internals/concat.py
  pandas/tests/reshape/test_concat.py
Labels: Bug, Reshaping, Timezones

#35316 DOC: extra closing parens make example invalid.
  pandas/_libs/lib.pyx
Labels: Style

#35055 TST: Adds CategoricalIndex DataFrame from_records test (GH32805)
  pandas/tests/frame/test_constructors.py
Labels: Categorical, Constructors, Testing

#35164 Infer compression if file extension is uppercase
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/common.py
  pandas/tests/io/test_common.py
Labels: Enhancement, IO Data, Needs Discussion

#35235 CLN/DOC: DataFrame.to_parquet supports file-like objects
  pandas/core/frame.py
  pandas/io/parquet.py
Labels: Docs, IO Parquet, Typing

#35323 Remove deprecated warn kwarg for matplotlib use
  pandas/util/_test_decorators.py
Labels: Visualization

#34514 BUG: asymmetric error bars for series (GH9536)
  doc/source/user_guide/visualization.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_series.py
Labels: Visualization

#35327 Doc fixups
  doc/source/reference/groupby.rst
  doc/source/reference/window.rst
  doc/source/whatsnew/v1.1.0.rst
Labels: Docs

#35329 More whatsnew cleanup.
  doc/source/whatsnew/v1.1.0.rst
Labels: Docs

#35328 Optimize array_equivalent for NDFrame.equals
  pandas/core/dtypes/missing.py
  pandas/core/internals/managers.py
  pandas/tests/dtypes/test_missing.py
Labels: Performance

#35324 Fix AttributeError when groupby as_index=False on empty DataFrame
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Regression

#35358 CI: pin matplotlib for doc build
  ci/deps/azure-37-locale.yaml
  environment.yml
  requirements-dev.txt
Labels: CI

#35353 REGR: MultiIndex Indexing
  pandas/core/indexes/base.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Bug, Indexing, MultiIndex, Regression

#35374 Change defaults for rolling/expanding.apply engine kwargs to None
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Enhancement, Window

#35396 PKG: Set max pin for Cython
  pyproject.toml
Labels: Dependencies

#35393 Matplotlib 3.3 compatibility fixups
  ci/deps/azure-37-locale.yaml
  doc/source/whatsnew/v1.1.0.rst
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/compat.py
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_frame.py
  pandas/tests/plotting/test_series.py
Labels: Compat, Visualization

#35397 CLN: Remove leftover partial-result code from apply
  pandas/core/apply.py
Labels: Clean
