Repository pandas-dev/pandas, pull requests merged in 2020-06, with the labels that each got.

#33749 BUG: Fix mixed datetime dtype inference
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/lib.pyx
  pandas/core/indexes/base.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/indexes/datetimes/test_indexing.py
Labels: Compat, Timeseries

#34261 DOC: Clarify ExcelFile's available engine compatibility with file types in...
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#34199 PERF: Fixes performance regression in DataFrame[bool_indexer] (#33924)
  asv_bench/benchmarks/indexing.py
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexing.py
Labels: Indexing, Performance

#34158 REGR: use dtype.fill_value in ExtensionBlock.fill_value where available
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/test_sparse.py
Labels: Missing-data, Sparse

#34110 CLN: Don't use astype_nansafe after to_numpy
  pandas/core/arrays/boolean.py
  pandas/core/arrays/integer.py
  pandas/tests/arrays/boolean/test_astype.py
  pandas/tests/arrays/integer/test_dtypes.py
Labels: Clean, Missing-data

#34507 REF: use standard pattern in normalize_i8_timestamps
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
Labels: Clean, Timeseries

#34486 ENH: mul(Tick, float); simplify to_offset
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Frequency

#34509 BUG: fix BooleanArray.astype('string') (GH34110)
  pandas/core/arrays/boolean.py
Labels: Bug

#32699 DOC: Clarify output of diff (returned type and possible overflow)
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs, Numeric

#34464 CLN: drop **kwds from pd.read_excel
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
Labels: API Design, IO Excel

#34449 BUG: Period.to_timestamp not matching PeriodArray.to_timestamp
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
  pandas/tests/indexes/period/test_scalar_compat.py
  pandas/tests/scalar/period/test_period.py
Labels: Period, Timeseries

#34516 CI: Linux py37_np_dev failing on 1.0.x
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
Labels: CI, Compat

#34515 CLN: remove Resolution.get_stride_from_decimal
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/tseries/frequencies/test_freq_code.py
Labels: Clean, Frequency

#34474 BUG: fix origin epoch when freq is Day and harmonize epoch between timezones
  pandas/core/resample.py
  pandas/tests/resample/test_datetime_index.py
Labels: API - Consistency, Resample

#34518 REF: add Resolution to tslibs.__init__
  pandas/_libs/tslibs/__init__.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/tests/tslibs/test_api.py
Labels: Frequency, Internals

#34524 CLN: remove Resolution.get_attrname_from_abbrev
  pandas/_libs/tslibs/resolution.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/tseries/frequencies/test_freq_code.py
Labels: Period

#34523 CLN: stronger typing for Period.freq
  pandas/_libs/tslibs/offsets.pxd
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Period

#34183 BUG/ENH: Fix apply to only call `func` once on the first column/row
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/reduction.pyx
  pandas/core/apply.py
  pandas/core/frame.py
  pandas/tests/frame/test_apply.py
  pandas/tests/groupby/test_bin_groupby.py
Labels: Reshaping

#34517 TST #22663: Operation between DataFrame with non-numeric types and incomplete series
  pandas/tests/frame/test_arithmetic.py
Labels: Numeric, Reshaping, Testing

#33959 fix bfill, ffill and pad when calling with df.interpolate with column…
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Bug, Missing-data

#34461 mask based multi-index assignment of column values described
  doc/source/user_guide/indexing.rst
Labels: Clean, Docs, Indexing

#34192 PERF: Remove unnecessary copies in sorting functions (#33917)
  pandas/core/sorting.py
Labels: Performance, Reshaping

#34522 DEPR: tz kwarg in Period.to_timestamp
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/scalar/period/test_period.py
Labels: Deprecate, Period, Timezones

#34450 Fix MultiIndex .loc "Too Many Indexers" with None as return value
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_multiindex.py
Labels: Indexing, MultiIndex

#34443 TST #28981 comparison operation for interval dtypes
  pandas/tests/arithmetic/test_interval.py
Labels: Interval, Testing

#34377 BUG: pd.DataFrame.transform recursively loops in some cases #34224
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/frame.py
  pandas/tests/series/test_apply.py
Labels: Reshaping

#34554 CLN: Update imports
  pandas/core/arrays/datetimes.py
Labels: Clean, Timezones

#34559 CLN: remove ABCTimedelta
  pandas/_libs/index.pyx
  pandas/_libs/interval.pyx
  pandas/_libs/tslibs/base.pxd
  pandas/_libs/tslibs/base.pyx
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Clean, Timedelta

#34555 REF: simplify wrapping in apply_index
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_yqm_offsets.py
Labels: Clean, Frequency

#34435 BUG: Fix to GH34422 SeriesGroupBy works only with 'func' now
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/aggregation.py
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Error Reporting, Groupby

#34560 BUG: fix resolution_string docstring
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs, Frequency

#34538 REF: add to_offset to tslibs namespace
  pandas/_libs/tslibs/__init__.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/dtypes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/timedeltas.py
  pandas/core/resample.py
  pandas/core/window/rolling.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/tseries/frequencies/test_freq_code.py
  pandas/tests/tseries/frequencies/test_to_offset.py
  pandas/tests/tslibs/test_api.py
Labels: API - Consistency, Frequency

#34453 [ENH] Allow pad, backfill and cumcount in groupby.transform
  doc/source/reference/frame.rst
  doc/source/reference/groupby.rst
  doc/source/reference/series.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Missing-data

#34499 REF/PERF: PeriodDtype decouple from DateOffset
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/tests/tslibs/test_api.py
  setup.py
Labels: Frequency, Period

#34561 DOC: Fixed PR06 (wrong parameter type) in pandas.Timestamp
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#34128 BUG/ENH: Improve categorical construction when using the iterator in StataReader
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/stata.py
  pandas/tests/io/data/stata/stata-dta-partially-labeled.dta
  pandas/tests/io/test_stata.py
Labels: Bug, Categorical, IO Stata

#33477 Send None parameter to pandas-gbq to set no progress bar
  ci/deps/travis-36-locale.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/compat/_optional.py
  pandas/io/gbq.py
  pandas/tests/io/test_gbq.py
Labels: IO Google

#34563 CLN: circular/runtime imports in tslibs
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Clean

#34579 solves ci issues with #34575
  asv_bench/benchmarks/arithmetic.py
Labels: CI, Frequency

#34574 DOC: fixed PR06 in pandas.Timedeltas
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs, Timedelta

#34566 CLN: address FIXMEs in liboffsets
  pandas/_libs/tslibs/offsets.pxd
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34572 TST: Added test to check that the freqstr attribute of the index is p…
  pandas/tests/series/methods/test_shift.py
Labels: Frequency, Testing, Timeseries

#34487 TST, TYP: _use_dynamic_x
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Typing, Visualization

#33962 Add nrows to read json.
  asv_bench/benchmarks/io/json.py
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/json/_json.py
  pandas/tests/io/json/test_readlines.py
Labels: IO JSON, Performance

#33982 BUG: Handling columns from index_col in _is_potential_multi_index
  pandas/io/parsers.py
  pandas/tests/io/data/excel/df_empty.xlsx
  pandas/tests/io/data/excel/df_equals.xlsx
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/test_index_col.py
Labels: IO Excel, MultiIndex

#34458 CLN: Clean csv files in test data GH34427
  doc/source/getting_started/comparison/comparison_with_sas.rst
  doc/source/getting_started/comparison/comparison_with_sql.rst
  doc/source/getting_started/comparison/comparison_with_stata.rst
  doc/source/user_guide/visualization.rst
  pandas/conftest.py
  pandas/plotting/_misc.py
  pandas/tests/data/iris.csv
  pandas/tests/data/tips.csv
  pandas/tests/io/parser/data/iris.csv
  pandas/tests/io/test_common.py
  pandas/tests/io/test_sql.py
  pandas/tests/util/test_util.py
Labels: Clean, Testing

#34454 TST/REF: refactor the arithmetic tests for IntegerArray
  pandas/tests/arrays/integer/test_arithmetic.py
Labels: NA - MaskedArrays, Refactor, Testing

#34624 DOC: updated core/arrays/base.py for PR08 errors
  pandas/core/arrays/base.py
Labels: Docs

#34600 DOC: Fixed docstring in Series .isin() method
  pandas/core/series.py
Labels: Docs

#34627 TST #24444 added tests
  pandas/tests/scalar/period/test_period.py
Labels: Testing

#34631 TYP: some type annotations for interpolate
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/missing.py
Labels: Typing

#34490 DOC: Added documentation for building using pyenv
  doc/source/development/contributing.rst
Labels: Docs

#34619 DOC: docstring, closes #23475
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#34485 DOC: updating the `indicator` wording in `merge` doc
  pandas/core/frame.py
Labels: Docs

#34594 Improve document for **kwargs argument of pandas.DataFrame.to_markdown
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#34394 DOC: "Setting layouts" plots' label size GH34305
  doc/source/user_guide/visualization.rst
Labels: Docs

#34591 DOC: updated base.py and datetimes.py in core/indexes for PR08
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
Labels: Docs

#34208 Restrict Pandas merge suffixes param type to list/tuple to avoid interchange in right and left suffix order
  doc/source/user_guide/merging.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
Labels: API Design, Error Reporting, Reshaping

#34477 CLN: Removed duplicated test data
  pandas/tests/io/conftest.py
  pandas/tests/io/data/csv/test1.csv.bz2
  pandas/tests/io/data/csv/test1.csv.gz
  pandas/tests/io/data/csv/tips.csv.bz2
  pandas/tests/io/data/csv/tips.csv.gz
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/data/test1.csv
  pandas/tests/io/parser/data/tips.csv
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_textreader.py
Labels: Clean, Testing

#34604 DOC: updated io/pytables.py to fix PR08
  pandas/io/pytables.py
Labels: Docs, IO HDF5

#34612 REF: make DateOffset apply_index methods operate on ndarrays where feasible
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34610 TST: mark tzlocal tests as slow, closes #34413
  pandas/tests/resample/test_datetime_index.py
Labels: Testing

#34595 BUG: fix Series.where(cond) when cond is empty
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/tests/series/indexing/test_where.py
Labels: Algos, Bug

#34585 REF: ensure we have offset objects in plotting functions
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Visualization

#34614 CLN: update tslibs/tseries test locations/imports
  pandas/tests/tseries/frequencies/test_freq_code.py
  pandas/tests/tseries/frequencies/test_frequencies.py
  pandas/tests/tslibs/test_libfrequencies.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Clean

#34616 Improve document for **kwargs argument of pandas.Series.to_markdown
  pandas/core/series.py
Labels: Docs

#34636 CLN: EWMA cython code and function dispatch
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/ewm.py
Labels: Clean, Window

#34625 REF: re-use existing conversion functions
  pandas/_libs/tslibs/period.pyx
Labels: Refactor

#34613 REF: RelativeDeltaOffset.apply_index operate on ndarray
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34590 REF: mix PeriodPseudoDtype into PeriodDtype
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
  pandas/core/dtypes/dtypes.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Period

#34634 BUG/API: Disallow unit if input to Timedelta and to_timedelta is/contains str
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/timedeltas.py
  pandas/core/computation/pytables.py
  pandas/core/tools/timedeltas.py
  pandas/tests/scalar/timedelta/test_constructors.py
Labels: Error Reporting, Timedelta

#34649 REF: simplify libperiod.get_yq
  pandas/_libs/tslibs/period.pyx
Labels: Frequency

#34653 DOC: updated _testing.py for PR08 errors
  pandas/_testing.py
Labels: Docs

#34646 DOC: updated io/sql.py for PR08 errors
  pandas/io/sql.py
Labels: Docs

#34588 REF: implement c_FreqGroup, FreqGroup in tslibs.dtypes
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/period.pyx
Labels: Clean, Frequency

#34267 Fix .isin Considers "1" and 1 equal
  pandas/tests/test_algos.py
Labels: Dtypes, Testing

#32702 BUG: Add errors argument to to_csv() call to enable error handling for encoders
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/io/common.py
  pandas/io/formats/csvs.py
  pandas/tests/io/formats/test_to_csv.py
Labels: Error Reporting, IO CSV

#34648 REF: de-duplicate month/year rolling in libperiod
  pandas/_libs/tslibs/period.pyx
Labels: Frequency

#34658 CLN: disallow passing tuples for Period freq
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
Labels: Period

#34632 Revert backport of #33632: Parquet & s3 I/O changes
  pandas/io/common.py
  pandas/io/gcs.py
  pandas/io/parquet.py
  pandas/io/s3.py
  pandas/tests/io/test_parquet.py
Labels: IO Parquet

#34638 CLN: deduplicate in core.internals.blocks.interpolate
  pandas/core/internals/blocks.py
Labels: Clean, Internals

#34661 BUG: Allow plain bools in ExtensionArray.equals
  pandas/core/arrays/base.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/arrow/test_bool.py
Labels: Bug, ExtensionArray

#34659 REF: avoid get_freq_code
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
Labels: Frequency

#34652 DOC: updated plotting/_misc.py for PR08 errors
  pandas/plotting/_misc.py
Labels: Docs

#34672 PERF: normalize_i8_timestamps
  pandas/_libs/tslibs/conversion.pyx
Labels: Performance, Timeseries

#34641 ENH: Add max_results kwarg to read_gbq
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/gbq.py
  pandas/tests/io/test_gbq.py
Labels: Enhancement, IO Google

#34680 CLN: dont consolidate in groupby
  pandas/core/groupby/groupby.py
Labels: Clean, Groupby, Performance

#34599 BUG: Pandas changes dtypes of columns when no float (or other) assignments are done to this column #34573
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Bug, Dtypes, Indexing

#34587 ENH: Resolutions for month/qtr/year
  pandas/_libs/tslibs/resolution.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/tseries/frequencies/test_freq_code.py
Labels: Frequency

#34674 CLN: remove get_freq_code
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/frequencies.pxd
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/period.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/indexes/datetimes/test_to_period.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/tseries/frequencies/test_freq_code.py
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tests/tseries/offsets/test_fiscal.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_libfrequencies.py
  pandas/tests/tslibs/test_period_asfreq.py
Labels: Frequency

#34630 TYP: some type annotations in core\tools\datetimes.py
  pandas/_typing.py
  pandas/core/indexes/datetimes.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/io/excel/_odfreader.py
Labels: Typing

#34711 BLD: Pin cython for 37-locale build
  ci/deps/azure-37-locale.yaml
  environment.yml
  requirements-dev.txt
Labels: Build

#34667 BLD: pyproject.toml for Py38
  doc/source/whatsnew/v1.0.5.rst
  pyproject.toml
Labels: Build

#34500 REG: Fix read_parquet from file-like objects
  pandas/io/parquet.py
  pandas/tests/io/data/parquet/simple.parquet
  pandas/tests/io/test_parquet.py
Labels: IO Parquet, Regression

#34721 Debug CI Issue
  pandas/compat/numpy/__init__.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/plotting/test_misc.py
Labels: CI

#34729 Changed the way a few sentences were written
  README.md
  setup.py
Labels: Docs

#34716 DOC: updated pandas/core/series.py for SS06 errors
  pandas/core/series.py
Labels: Docs

#34715 DOC: updated core/groupby/generic.py for SS06 errors
  pandas/core/groupby/generic.py
Labels: Docs

#34713 DOC: updated core/indexes/base.py for SS06 errors
  pandas/core/indexes/base.py
Labels: Docs

#34745 DOC: updated strings.py for SS06 errors
  pandas/core/strings.py
Labels: Docs

#34742 CLN: remove the old 'nature_with_gtoc' sphinx doc theme
  doc/source/themes/nature_with_gtoc/layout.html
  doc/source/themes/nature_with_gtoc/static/nature.css_t
  doc/source/themes/nature_with_gtoc/theme.conf
Labels: Clean

#34688 TYP: update setup.cfg
  setup.cfg
Labels: Typing

#34697 TYP: type annotations for read_sas
  pandas/io/sas/sasreader.py
Labels: Typing

#34692 TYP: check_untyped_defs pandas.core.resample
  pandas/core/indexes/period.py
  pandas/core/resample.py
  setup.cfg
Labels: Typing

#34622 TST: boolean indexing using .iloc #20627
  pandas/tests/indexing/test_iloc.py
Labels: Indexing, Testing

#34744 CLN: clean and deduplicate in core.missing.interpolate_1d
  pandas/core/missing.py
Labels: Clean

#34758 typo: pivot_table -> pivot
  doc/source/getting_started/intro_tutorials/07_reshape_table_layout.rst
Labels: Docs

#34757 typo: rows -> columns
  doc/source/getting_started/intro_tutorials/01_table_oriented.rst
Labels: Docs

#34695 TYP: check_untyped_defs pandas.io.json._table_schema
  pandas/io/json/_table_schema.py
  setup.cfg
Labels: Typing

#34709 BUG: DataFrame.unstack with non-consolidated
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_reshape.py
Labels: Bug, Reshaping

#34707 PERF: is_date_array_normalized
  pandas/_libs/tslibs/conversion.pyx
Labels: Performance, Timeseries

#34700 CLN: remove usages of base_and_stride
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/plotting/_matplotlib/timeseries.py
Labels: Frequency

#34701 CLN: remove libfrequencies.get_freq_group
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/frequencies.pxd
  pandas/_libs/tslibs/frequencies.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/resolution.pyx
  pandas/core/indexes/period.py
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/tseries/frequencies/test_freq_code.py
Labels: Clean, Frequency

#34762 CLN: day->day_opt, remove unused case in liboffsets.get_day_of_month
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34750 Bump up minimum numpy version in windows37 job
  ci/azure/windows.yml
  ci/deps/azure-windows-37.yaml
Labels: CI

#34752 REF: refactor NDFrame.interpolate to avoid dispatching to fillna
  pandas/core/generic.py
Labels: Missing-data, Refactor

#34737 PERF: avoid copy in replace
  pandas/core/internals/blocks.py
Labels: Performance

#34344 BUG: don't plot colorbar if c is column containing colors
  doc/source/whatsnew/v1.1.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_frame.py
Labels: Visualization

#34689 TYP: check_untyped_defs pandas.core.nanops
  pandas/core/nanops.py
  setup.cfg
Labels: Typing

#32546 BUG: Dataframe.groupby aggregations with categorical columns lead to incorrect results.
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Categorical, Groupby

#34623 TST/REF: arithmetic tests for BooleanArray + consolidate with integer masked tests
  pandas/_testing.py
  pandas/core/arrays/boolean.py
  pandas/tests/arrays/boolean/test_arithmetic.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/masked/test_arithmetic.py
  pandas/tests/extension/base/ops.py
Labels: Bug, NA - MaskedArrays, Testing

#34069 ENH: Implement groupby.sample
  doc/source/reference/groupby.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/core/groupby/base.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_sample.py
  pandas/tests/groupby/test_whitelist.py
Labels: Enhancement, Groupby

#34558 DOC: Add bcpandas to Ecosystem in docs
  doc/source/ecosystem.rst
Labels: Docs, IO SQL

#34718 Removed __div__ impls from Cython
  ci/deps/azure-37-locale.yaml
  environment.yml
  pandas/_libs/interval.pyx
  pandas/_libs/tslibs/nattype.pyx
  requirements-dev.txt
Labels: Build

#34764 REF: make get_day_of_month nogil
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
Labels: Internals, Refactor, Timeseries

#34736 BUG: Fixed regression in PeriodIndex loc
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_indexing.py
Labels: Indexing, Period

#34763 REF: remove roll_check, use roll_convention
  pandas/_libs/tslibs/offsets.pyx
Labels: Internals, Refactor, Timeseries

#33086 BUG: Groupby lost index, when one of the agg keys had no function all…
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/base.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Groupby, Reshaping

#34746 API: validate `limit_direction` parameter of NDFrame.interpolate
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/tests/series/methods/test_interpolate.py
Labels: API Design

#34770 CLN/TYPE: EWM
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/ewm.py
Labels: Clean, Typing, Window

#34772 REF: inline get_day_of_month
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34570 Export InvalidIndexError
  doc/source/reference/general_utility_functions.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/index.py
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/indexing.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/resample/test_period_index.py
Labels: Error Reporting

#34537 CI/TST #34131 fixed test_floordiv_axis0_numexpr_path
  pandas/tests/frame/test_arithmetic.py
Labels: Testing

#34760 REF: De-duplicate roll_yearday/roll_qtrday
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tslibs/test_liboffsets.py
Labels: Frequency

#32723 BUG: Fix HDFStore empty keys on native HDF5 file by adding keyword include
  doc/source/whatsnew/v1.1.0.rst
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_store.py
Labels: API - Consistency, IO HDF5

#34647 TST: groupby apply with indexing and column aggregation returns the column #7002
  pandas/tests/groupby/test_apply.py
Labels: Groupby, Testing

#34775 DOC: updated multi.py docstring for SS06 errors
  pandas/core/indexes/multi.py
Labels: Docs

#34761 REF: implement shift_bday
  pandas/_libs/tslibs/offsets.pyx
Labels: Internals, Refactor, Timeseries

#34778 REF: de-duplicate code in liboffsets
  pandas/_libs/tslibs/offsets.pyx
Labels: Clean, Frequency

#34703 CLN: disallow tuple in to_offset
  doc/source/whatsnew/v1.1.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Frequency

#34780 TST: remove super slow cases on upsample_nearest_limit
  .pre-commit-config.yaml
  pandas/tests/io/parser/test_multi_thread.py
  pandas/tests/resample/test_datetime_index.py
Labels: Testing

#34781 REF: reuse roll_qtrday in liboffsets
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34782 REF: avoid using DTA/PA methods in Week.apply_index
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34783 REF: avoid DTA/PA methods in SemiMonthOffset.apply_index
  pandas/_libs/tslibs/offsets.pyx
Labels: Frequency

#34767 BUG: Groupby with as_index=False raises error when type is Category
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_size.py
Labels: Categorical, Groupby

#34705 TST: Add test for rolling window, see GH 34605
  pandas/tests/window/test_rolling.py
Labels: Testing, Window

#34545 DEPR: Deprecate tshift and integrate it to shift
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v1.1.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_shift.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_whitelist.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/series/methods/test_shift.py
Labels: Deprecate, Timeseries

#34785 DOC: add release note about revert for 1.0.5
  doc/source/whatsnew/v1.0.5.rst
Labels: Docs

#34797 Backport PR #34785 on branch 1.0.x (DOC: add release note about revert for 1.0.5)
  doc/source/whatsnew/v1.0.5.rst
Labels: Docs

#34796 API: Removed PeriodDtype.dtype_code from public API
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/period.pyx
Labels: API Design, Period
