Repository pandas-dev/pandas, pull requests merged in 2020-01, with the labels that each got.

#30585 BUG: Disable parallel cythonize on Windows (GH 30214)
  ci/azure/windows.yml
  doc/source/whatsnew/v1.0.0.rst
  setup.py
Labels: Build, Windows

#30591 CLN: datetimelike EA and Index cleanups
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/blocks.py
Labels: Clean, ExtensionArray

#30587 REF: share code between DatetimeIndex and TimedeltaIndex
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor, Timedelta, Timeseries

#30577 CLN: Clean _test_moments_consistency in common.py
  pandas/tests/window/common.py
  pandas/tests/window/moments/test_moments_ewm.py
  pandas/tests/window/moments/test_moments_expanding.py
  pandas/tests/window/moments/test_moments_rolling.py
Labels: Clean, Testing

#30586 REF: separate casting out of Index.__new__
  pandas/core/indexes/base.py
Labels: Dtypes, Refactor

#30592 CLN: remove no-longer-reachable addsub_int_array
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
Labels: Clean, Period

#30566 CLN: Clean test moments for expanding
  pandas/tests/window/moments/test_moments_expanding.py
Labels: Testing, Window

#30560 BLD: Fix IntervalTree build warnings
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: Build, Interval

#30499 DOC: Make pyplot import explicit in the 10 minutes to pandas page
  doc/source/getting_started/10min.rst
Labels: Docs

#30314 DOC/CLN: move NDFrame.groupby to (DataFrame|Series).groupby
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/reshape/merge.py
  pandas/core/series.py
Labels: Clean, Groupby

#30434 ENH: Allow scatter plot to plot objects and datetime type data
  doc/source/whatsnew/v1.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_frame.py
Labels: Visualization

#30594 BUG: DTA/TDA/PA add/sub object-dtype
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/common.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/dtypes/test_common.py
Labels: Period, Timedelta, Timeseries

#30595 REF: share join methods for DTI/TDI
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor, Reshaping

#30596 REF: move inference/casting out of Index.__new__
  pandas/core/indexes/base.py
Labels: Constructors, Index, Refactor

#30145 Fix NoneType error when pulling non existent field
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/json/_normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON

#30599 REF: share _wrap_joined_index
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor

#30601 CLN: Use fstring instead of .format in io/excel and test/generic
  pandas/io/excel/_base.py
  pandas/io/excel/_odfreader.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_util.py
  pandas/io/excel/_xlwt.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_series.py
Labels: Style

#28662 BUG: Fix groupby.apply
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/reduction.pyx
  pandas/tests/groupby/test_apply.py
Labels: Bug, Groupby, Indexing

#29883 CLN: Clean up of locale testing
  ci/azure/posix.yml
  ci/run_tests.sh
  ci/setup_env.sh
  pandas/tests/config/test_localization.py
  pandas/tests/io/test_common.py
Labels: Clean

#30602 TST: Add test for TypeError when using datetime.time in scatter plot
  pandas/tests/plotting/test_frame.py
Labels: Error Reporting, Visualization

#30507 BUG: pass 2D ndarray and EA-dtype to DataFrame, closes #12513
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, Constructors, ExtensionArray

#28492 BUG: Raise when casting NaT to int
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/test_common.py
Labels: Dtypes

#29847 PERF: perform reductions block-wise
  pandas/core/frame.py
  pandas/core/internals/managers.py
  pandas/core/nanops.py
  pandas/tests/groupby/test_groupby.py
Labels: Performance, Reshaping

#30257 DOC: .get_slice_bound in MultiIndex needs documentation.
  pandas/core/indexes/multi.py
Labels: Docs, Typing

#30146 BUG: Fix pd.NA `na_rep` truncated in to_csv
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/io/formats/test_to_csv.py
Labels: Missing-data, Output-Formatting

#30598 CLN: Remove int32 and float32 dtypes from IntervalTree
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: Build, Clean, Interval

#29260 Multiindex recurse error fix
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/reshape/merge/test_multi.py
Labels: Bug, MultiIndex

#30604 CLN: Replace old format strings to f-strings in pandas/tests/base
  pandas/tests/base/test_conversion.py
  pandas/tests/base/test_ops.py
Labels: Style

#30497 CLN: OrderedDict -> Dict
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/core/groupby/generic.py
  pandas/core/indexes/multi.py
  pandas/io/formats/html.py
  pandas/tests/io/parser/test_common.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/util/test_validate_args.py
  pandas/tests/util/test_validate_args_and_kwargs.py
  pandas/tests/util/test_validate_kwargs.py
  pandas/util/_validators.py
  scripts/validate_docstrings.py
Labels: Clean

#30295 JSON Support for parsing NaN, Infinity and -Infinity
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/src/ujson/lib/ultrajson.h
  pandas/_libs/src/ujson/lib/ultrajsondec.c
  pandas/_libs/src/ujson/python/JSONtoObj.c
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON

#30600 BUG: Ensure df.itertuples() uses plain tuples correctly
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_api.py
Labels: Reshaping

#30606 CLN: remove CategoricalIndex.itemsize, should have gone in #29918
  pandas/core/arrays/categorical.py
  pandas/core/indexes/category.py
Labels: Categorical, Deprecate

#30369 Clean Up nogil Warning From Parsers
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
Labels: Clean

#30496 Improve ISO Date Performance for JSON
  asv_bench/benchmarks/io/json.py
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Timeseries

#30467 CI: Add test case for unwanted patterns
  ci/code_checks.sh
  scripts/validate_string_concatenation.py
Labels: CI

#29788 ENH: Allow map with abc mapping
  doc/source/whatsnew/v1.0.0.rst
  pandas/conftest.py
  pandas/core/base.py
  pandas/core/series.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_apply.py
  pandas/tests/series/test_constructors.py
  pandas/util/testing.py
Labels: Algos, Enhancement, Series

#30400 TYP: Type hints in pandas/io/formats/excel.py
  pandas/io/formats/excel.py
Labels: Typing

#30608 CLN: remove warnings clearing
  pandas/tests/arithmetic/test_datetime64.py
Labels: Clean

#30607 REF: Delegate more methods for DTI/TDI/PI
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor

#30489 DEPR: Deprecate pandas.datetime
  doc/source/whatsnew/v1.0.0.rst
  pandas/__init__.py
  pandas/tests/api/test_api.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/sas/test_sas7bdat.py
Labels: Deprecate

#30605 REF: delegate attrs for CategoricalIndex, IntervalIndex
  pandas/core/indexes/category.py
  pandas/core/indexes/interval.py
Labels: Categorical, Interval, Refactor

#30580 BUG: Series __setitem__ gives wrong result with bool indexer
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_indexing.py
Labels: Bug, Indexing

#30611 Improve ASV Environment Creation Performance
  asv_bench/asv.conf.json
Labels: Performance

#30526 BUG: pct_change wrong result when there are duplicated indices
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_pct_change.py
  pandas/tests/series/methods/test_pct_change.py
Labels: Bug, Missing-data

#30241 BUG: to_datetime with unit with Int64
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslib.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/datetimes/test_tools.py
Labels: ExtensionArray, Timeseries

#30624 whatsnew fixups
  doc/source/whatsnew/v1.0.0.rst
Labels: Docs

#30612 CLN: replacing str.format with f-strings in several files. #29547
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_style.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/formats/test_to_excel.py
Labels: Style

#30627 REF: remove IntervalIndex.copy
  pandas/core/indexes/interval.py
Labels: Clean

#30623 REF: standardize usage with _make_wrapped_arith_op
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Clean

#30622 DOC: Fixing PR09 formatting errors
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/period.py
  pandas/core/window/ewm.py
  pandas/io/excel/_base.py
Labels: Docs

#30613 TYP: Add TypeVars to NDFrame
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/reshape/pivot.py
Labels: Typing

#30633 CI: Remove pin google-cloud-bigquery
  ci/deps/travis-36-cov.yaml
Labels: CI

#30516 DEPR: tz-aware Series/DatetimIndex.__array__ returns an object array of Timestamps
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/datetimes.py
  pandas/core/series.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/generic/test_frame.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/series/test_timeseries.py
Labels: Deprecate, Timezones

#28876 ENH: show numbers on .info() with verbose flag
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_repr_info.py
Labels: DataFrame

#30629 REF: implement indexes.extension to share delegation
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Index

#30546 DEPR: DataFrame GroupBy indexing with single items DeprecationWarning
  doc/source/getting_started/comparison/comparison_with_sas.rst
  doc/source/getting_started/comparison/comparison_with_stata.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_transform.py
Labels: Deprecate, Groupby

#30574 API: Raise when setting name via level
  doc/source/user_guide/advanced.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_names.py
Labels: MultiIndex

#30308 DOC/TST: Indexing with NA raises
  .pre-commit-config.yaml
  asv_bench/benchmarks/indexing.py
  doc/source/reference/extensions.rst
  doc/source/user_guide/boolean.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/api/indexers/__init__.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/sparse/array.py
  pandas/core/common.py
  pandas/core/indexers.py
  pandas/core/indexing.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_na_indexing.py
  pandas/tests/series/indexing/test_boolean.py
Labels: ExtensionArray, Indexing

#29551 Add pandarallel to ecosystem documentation
  doc/source/ecosystem.rst
Labels: Docs

#30630 CI: Fix Flakey GBQ Tests
  pandas/tests/io/test_gbq.py
Labels: IO Google, Unreliable Test

#30635 BUG: Index.__new__ with Interval/Period data and object dtype
  pandas/core/indexes/base.py
  pandas/tests/indexes/period/test_constructors.py
Labels: Constructors, Index

#30626 REF: delegate more IntervalIndex methods
  pandas/core/indexes/interval.py
Labels: Interval, Refactor

#30519 ENH: add support for reading binary Excel files (#15914)
  doc/source/whatsnew/v1.0.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_readers.py
Labels: Enhancement, IO Excel

#30637 REF/BUG: DTA/TDA/PA comparison ops inconsistencies
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/test_period.py
Labels: Period, Timedelta, Timeseries

#30570 CLN: refactor tests in test_moments_ewm.py
  pandas/tests/window/common.py
  pandas/tests/window/moments/conftest.py
  pandas/tests/window/moments/test_moments_ewm.py
Labels: Testing, Window

#30578 ENH: Add ignore_index to sort_index
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/series/methods/test_sort_index.py
Labels: API Design, Enhancement, Reshaping

#29143 DOC: Edit MultiIndex.set_levels() docstring to clarify that set_levels() interprets passed values as new components of the .levels attribute (#28294)
  pandas/core/indexes/multi.py
Labels: Docs, MultiIndex

#30628 DOC: Add strings for dtypes in basic.rst
  doc/source/getting_started/basics.rst
  doc/source/reference/arrays.rst
Labels: Docs, Dtypes

#30129 DOC: Code style documentation
  doc/source/development/code_style.rst
  doc/source/development/contributing.rst
  doc/source/development/index.rst
  doc/source/index.rst.template
Labels: Docs, Style

#30653 TST: Test for merge_asof groupby=multiple with categorical column
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Testing

#30631 CLN: Update old string formatting to f-string
  pandas/core/ops/array_ops.py
  pandas/core/ops/dispatch.py
  pandas/core/ops/invalid.py
  pandas/core/ops/methods.py
  pandas/core/ops/roperator.py
Labels: Style

#30662 TYP: check_untyped_defs plotting._matplotlib.timeseries
  pandas/plotting/_matplotlib/__init__.py
  setup.cfg
Labels: Typing

#30663 MAINT: Change all SO links to use HTTPS
  doc/source/user_guide/cookbook.rst
  pandas/core/dtypes/missing.py
  pandas/io/sql.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/io/parser/test_common.py
Labels: Clean, Docs

#30664 DOC: Update info regarding pydatastream
  doc/source/ecosystem.rst
Labels: Docs

#30646 TST: Regression testing for fixed issues
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_missing.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/parser/test_index_col.py
  pandas/tests/reshape/test_concat.py
  pandas/tests/reshape/test_pivot.py
Labels: Testing

#30660 Fix flakey base setitem test
  pandas/tests/extension/base/setitem.py
Labels: Unreliable Test

#30658 TYP: --disallow-any-generics pandas\core\reshape\concat.py
  pandas/core/reshape/concat.py
Labels: Typing

#30661 TYP: check_untyped_defs pandas/io/sql.py
  pandas/io/sql.py
  setup.cfg
Labels: Typing

#30669 MAINT: Change all pandas links to use HTTPS
  RELEASE.md
  asv_bench/asv.conf.json
  conda.recipe/meta.yaml
  doc/source/development/contributing.rst
  doc/source/getting_started/tutorials.rst
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/style.ipynb
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v0.15.2.rst
  doc/source/whatsnew/v0.16.0.rst
  doc/source/whatsnew/v0.21.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/concat.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/reshape/concat.py
  pandas/core/tools/datetimes.py
  pandas/core/window/ewm.py
  pandas/core/window/rolling.py
  pandas/io/json/_json.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/io/formats/data/html/render_links_false.html
  pandas/tests/io/formats/data/html/render_links_true.html
  pandas/tests/io/formats/test_to_html.py
Labels: Clean, Docs

#30674 TST: Add more tests for fixed issues
  pandas/tests/groupby/test_nth.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/test_multilevel.py
Labels: Testing

#30671 JSON Code Cleanup
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: Clean, IO JSON

#30666 ENH: Implement PeriodIndex.intersection without object-dtype cast
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/period.py
Labels: Index, Period, Reshaping

#30665 CI: unpin IPython
  environment.yml
  requirements-dev.txt
Labels: CI

#30682 TYP: Add mypy as a pre-commit
  .pre-commit-config.yaml
Labels: Typing

#30684 DOC: Mention TYP as a type annotation PR prefix
  doc/source/development/contributing.rst
Labels: Docs

#30686 Fix PeriodIndex.get_indexer with non-PI
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_indexing.py
Labels: Index, Period

#30651 CLN: Clean tests for *.sort_index, *.sort_values and df.drop_duplicates
  pandas/tests/frame/methods/test_drop_duplicates.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/series/methods/test_sort_index.py
  pandas/tests/series/methods/test_sort_values.py
Labels: Testing

#30650 REF: use _data.take for CI/DTI/TDI/PI.take
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
Labels: ExtensionArray, Refactor

#30648 REF: move EA wrapping/unwrapping to indexes.extensions
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: ExtensionArray, Index

#30625 TST: Adding test to concat where copy=False for ExtensionArrays
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/test_sparse.py
Labels: ExtensionArray, Testing

#30619 TYP: enable strict_equality to prohibit comparisons of non-overlappin…
  pandas/core/arrays/boolean.py
  pandas/core/arrays/period.py
  pandas/core/arrays/string_.py
  pandas/core/dtypes/base.py
  pandas/io/excel/_odfreader.py
  pandas/io/formats/format.py
  setup.cfg
Labels: Typing

#28215 Add function to clean up column names with special characters
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/computation/common.py
  pandas/core/computation/eval.py
  pandas/core/computation/expr.py
  pandas/core/computation/parsing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/frame/test_query_eval.py
Labels: DataFrame

#30655 REF: change TDI.delete behavior to match DTI.delete
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
Labels: Index, Timedelta

#30687 PLT: Add tests for missing markers
  pandas/tests/plotting/test_frame.py
Labels: Testing, Visualization

#30698 Fix integer check; also add column with integer name in test case.
  pandas/core/generic.py
  pandas/tests/frame/test_query_eval.py
Labels: Typing

#30693 CI: Fix pytest junit_family warnings
  setup.cfg
Labels: CI

#30694 CLN: unreachable code in indexes
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Clean, Index

#30695 REF: share `delete` between DTI/TDI/PI
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Index, Refactor

#30689 CI: Fix IPython Tab Completion test async warning
  ci/deps/azure-36-locale.yaml
  ci/deps/azure-37-locale.yaml
  environment.yml
  pandas/tests/arrays/categorical/test_warnings.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/test_base.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/series/test_api.py
  pandas/util/_test_decorators.py
  requirements-dev.txt
Labels: Output-Formatting, Testing

#30701 BUG: TimedeltaIndex.union with sort=False
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/timedeltas/test_setops.py
Labels: Timedelta

#30688 CLN: share compatibility-check code
  pandas/core/arrays/period.py
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/period/test_tools.py
  pandas/tests/series/test_arithmetic.py
Labels: Clean, Period

#30690 TYP: NDFrame.(loc|iloc|at|iat)
  pandas/core/generic.py
  pandas/core/indexing.py
Labels: Indexing, Typing

#30700 CLN: Replace fstring in tests/groupby/*.py files
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_transform.py
  pandas/tests/groupby/test_value_counts.py
  pandas/tests/groupby/test_whitelist.py
Labels: Clean, Style

#30654 REF/TST: PeriodArray comparisons with listlike
  pandas/core/arrays/period.py
  pandas/core/indexes/base.py
  pandas/tests/arithmetic/test_period.py
Labels: Period, Reshaping

#30632 TPY: Add Types to gbq.py
  pandas/io/gbq.py
Labels: Typing

#30710 CI: Fix numpydev build
  pandas/_libs/src/ujson/python/objToJSON.c
Labels: CI, Dependencies

#30656 CLN: Deprecate pandas.SparseArray for pandas.arrays.SparseArray
  doc/source/development/contributing_docstring.rst
  doc/source/getting_started/basics.rst
  doc/source/getting_started/dsintro.rst
  doc/source/reference/arrays.rst
  doc/source/user_guide/sparse.rst
  doc/source/whatsnew/v0.19.0.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v1.0.0.rst
  pandas/__init__.py
  pandas/_testing.py
  pandas/core/arrays/sparse/accessor.py
  pandas/core/arrays/sparse/array.py
  pandas/core/dtypes/common.py
  pandas/tests/api/test_api.py
  pandas/tests/arrays/sparse/test_accessor.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/sparse/test_combine_concat.py
  pandas/tests/arrays/test_array.py
  pandas/tests/base/test_conversion.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/internals/test_internals.py
  pandas/tests/reshape/test_reshape.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_ufunc.py
Labels: Deprecate, Sparse

#30705 BUG: listlike comparisons for DTA and TDA
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/common.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: ExtensionArray

#30582 TYP: Add types to top-level funcs, step 2
  pandas/_typing.py
  pandas/core/algorithms.py
  pandas/core/frame.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/io/formats/format.py
Labels: Typing

#30680 TYP: Fix chainmap typing for mypy 0.740+
  pandas/compat/chainmap.py
  pandas/core/computation/pytables.py
Labels: Typing

#30697 Implement PeriodIndex.difference without object-dtype cast
  pandas/_testing.py
  pandas/core/indexes/period.py
Labels: Period, Reshaping

#30704 REF: Share _fast_union between DTI/TDI
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Index

#30696 Make DTI/TDI _union behavior match
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/timedeltas/test_setops.py
Labels: Timedelta, Timeseries

#30702 DEPR: CategoricalIndex.take_nd
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/indexes/category.py
  pandas/tests/arrays/categorical/test_algos.py
Labels: Categorical, Deprecate

#30245 Implement NA.__array_ufunc__
  doc/source/getting_started/dsintro.rst
  doc/source/user_guide/missing_data.rst
  pandas/_libs/missing.pyx
  pandas/_libs/ops_dispatch.pyx
  pandas/core/ops/__init__.py
  pandas/core/ops/dispatch.py
  pandas/tests/scalar/test_na_scalar.py
  setup.py
Labels: ExtensionArray, Missing-data, Numeric

#30712 CLN: remove Index/Series._is_homogeneous_type
  pandas/core/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/series/test_dtypes.py
Labels: Clean

#30672 CLN: Simplify rolling.py helper functions
  pandas/core/window/common.py
  pandas/core/window/ewm.py
  pandas/core/window/rolling.py
Labels: Clean, Window

#30703 Implement ExtensionIndex
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/interval.py
Labels: Constructors, ExtensionArray

#30640 BUG: Fix IntervalArray equality comparisions
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/series/test_arithmetic.py
Labels: Bug, Interval

#30675 BUG: bug in date_range with custom business hours and given periods
  doc/source/whatsnew/v1.0.0.rst
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tseries/offsets.py
Labels: Bug, Timedelta

#30715 IntervalArray equality follow-ups
  pandas/core/indexes/interval.py
  pandas/tests/arithmetic/test_interval.py
  pandas/tests/arrays/interval/test_interval.py
Labels: Interval

#30639 BLD: address build warnings
  pandas/_libs/algos_take_helper.pxi.in
  pandas/_libs/hashtable.pyx
  pandas/_libs/tslibs/conversion.pxd
Labels: Clean

#30725 DOC: fix see also in docstring of check_bool_array_indexer
  pandas/core/indexers.py
Labels: Docs

#30713 Fix PeriodIndex._shallow_copy allowing object-dtype
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/period.py
Labels: Constructors, Index, Period

#30615 DEPR: is_copy arg of take
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/tests/frame/methods/test_asof.py
  pandas/tests/generic/test_generic.py
Labels: Deprecate

#30645 TST: Adding test to concat Sparse arrays
  pandas/tests/reshape/test_concat.py
Labels: Reshaping, Sparse, Testing

#30723 REF: Create test_encoding file for CSV
  pandas/tests/io/parser/test_common.py
  pandas/tests/io/parser/test_encoding.py
Labels: IO CSV, Refactor, Testing

#30720 REF: cosmetic differences between DTA/TDA/PA comparison methods
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
Labels: Algos, Refactor, Timeseries

#30714 REF: share _union between DTI/TDI
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
Labels: Clean, Index, Timedelta, Timeseries

#28399 BUG: Fix Series(List[Interval]) to infer interval dtype
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/construction.py
  pandas/tests/series/test_constructors.py
Labels: Bug, Constructors, Dtypes, Interval

#30395 TST: Added fromisocalendar test cases
  doc/source/whatsnew/v1.0.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Compat, Timeseries

#30724 annotations
  pandas/_libs/interval.pyx
  pandas/core/arrays/categorical.py
  pandas/core/indexes/datetimelike.py
  pandas/core/internals/managers.py
  pandas/plotting/_misc.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/methods/test_to_records.py
Labels: Typing

#30707 STY: Spaces over concat strings - batch 1
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/computation/eval.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/core/strings.py
  pandas/io/clipboards.py
  pandas/io/excel/_util.py
  pandas/io/formats/format.py
  pandas/io/formats/style.py
  pandas/io/parsers.py
  pandas/io/pytables.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/computation/test_eval.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/window/moments/test_moments_rolling.py
Labels: Style

#30721 Make DTA _check_compatible_with less strict by default
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimes.py
Labels: Algos, Timeseries

#30706 CLN: replacing '.format' with f-strings in various files
  pandas/tests/util/test_validate_args.py
  pandas/tests/util/test_validate_kwargs.py
  pandas/tests/window/test_window.py
  pandas/tseries/holiday.py
  scripts/download_wheels.py
  scripts/generate_pip_deps_from_conda.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Style

#30722 BUG: PeriodArray comparisons inconsistent with Period comparisons
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/arrays/period.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/indexes/period/test_period.py
Labels: Algos, Bug, Period

#30718 TYP: type up parts of frame.py
  pandas/core/frame.py
  pandas/core/reshape/concat.py
Labels: Typing

#30749 Fix PR08 errors
  pandas/core/indexes/multi.py
  pandas/tseries/frequencies.py
Labels: Docs

#30747 PERF: Categorical getitem perf
  pandas/core/arrays/categorical.py
Labels: Categorical, Indexing, Performance

#30752 REF: share _validate_fill_value
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
Labels: Clean

#30756 TST: Use datapath fixture
  pandas/tests/io/test_pickle.py
Labels: Testing

#30760 DOC: new EAs
  pandas/core/base.py
Labels: Docs, ExtensionArray

#30762 DOC: Fix the string example.
  doc/source/user_guide/text.rst
Labels: Docs, Strings

#30759 BUG: Fixed getattr for frame with column sparse
  doc/source/whatsnew/v1.0.0.rst
  pandas/core/frame.py
  pandas/tests/arrays/sparse/test_accessor.py
Labels: Sparse

#30751 REF: share comparison methods for DTA/TDA/PA
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
Labels: Clean

#30754 BUG: DTI/TDI .insert accepting incorrectly-dtyped NaT
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/timedeltas/test_indexing.py
Labels: Bug, Missing-data, Timedelta

#30745 DEPR/REGR: Fix pandas.util.testing deprecation
  pandas/tests/api/test_api.py
  pandas/util/__init__.py
  pandas/util/testing.py
  pandas/util/testing/__init__.py
Labels: Deprecate, Testing

#30764 BUG: TDI/DTI _shallow_copy creating invalid arrays
  pandas/core/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_constructors.py
Labels: ExtensionArray, Index, Timedelta, Timeseries

#30767 STY: spaces in wrong place
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_tools.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_numeric.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/indexes/timedeltas/test_tools.py
Labels: Style

#29218 ENH: Show column name in assert_frame_equal
  pandas/_testing.py
  pandas/tests/util/test_assert_frame_equal.py
Labels: Compat
