Repository pandas-dev/pandas, pull requests merged in 2021-11, with the labels that each got.

#44260 CLN: tighten flake8/cython.cfg
  flake8/cython.cfg
  pandas/_libs/algos.pyx
  pandas/_libs/hashing.pyx
  pandas/_libs/internals.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/writers.pyx
Labels: Code Style

#44245 TST: Old issues
  pandas/tests/apply/test_series_apply.py
  pandas/tests/arithmetic/test_categorical.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_rank.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/io/parser/test_read_fwf.py
Labels: Testing

#44264 Fix formatting typo in user_guide/style.ipynb
  doc/source/user_guide/style.ipynb
Labels: Styler

#44248 BUG: styler render when using `hide`, `MultiIndex` and `max_rows` in combination
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: MultiIndex, Styler

#44236 BUG: setitem into td64/dt64 series/frame with Categorical[strings]
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/core/dtypes/common.py
  pandas/tests/indexing/test_indexing.py
Labels: Dtype Conversions

#44258 CLN: address TODOs, FIXMEs
  pandas/_libs/join.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/core/array_algos/putmask.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexers/utils.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Clean

#43406 BUG: DataFrame.__setitem__ sometimes operating inplace
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/internals/test_internals.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Indexing, ArrayManager

#44271 CLN: DataFrame.__repr__
  pandas/core/frame.py
Labels: Clean

#44278 CLN: missing f for f-string
  pandas/core/dtypes/cast.py
Labels: Docs

#44263 ENH/PERF: RangeIndex.argsort accept kind; pd.isna(rangeindex) fastpath
  pandas/core/dtypes/missing.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/common.py
Labels: Performance, Index

#44254 TYP: check typings with pyright
  pyproject.toml
  typings/numba.pyi
Labels: Typing

#44261 BUG: Series[int8][:3] = range(3) unnecessary upcasting to int64
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_can_hold_element.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Dtype Conversions

#44296 BUG: partially-inferring pydatetime objects
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
Labels: Timeseries

#44185 ENH: added regex argument to Series.str.split
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/strings/accessor.py
  pandas/core/strings/object_array.py
  pandas/tests/strings/test_split_partition.py
Labels: Enhancement, Strings

#44285 BUG: Period.__eq__ numpy scalar (#44182 (comment))
  pandas/_libs/tslibs/period.pyx
  pandas/tests/arithmetic/test_period.py
  pandas/tests/scalar/period/test_period.py
Labels: Bug, Period

#44315 Pin aiobotocore to lower than 2.0
  ci/deps/actions-38-db.yaml
  environment.yml
  requirements-dev.txt
Labels: CI, Dependencies

#44294 DEPR: unused 'errors' keyword in where, mask
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/series/methods/test_fillna.py
Labels: Indexing, Deprecate

#44123 BUG: DataFrame index name no longer resets after appending a list of series
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_append.py
Labels: Bug, Reshaping

#43731 ENH: Add engine="numba" to groupby mean
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_numba.py
Labels: Groupby

#44281 DOC: Fix rolling apply raw default arg
  pandas/core/window/doc.py
Labels: Docs, Window

#44283 BENCH: Add more numba rolling benchmarks
  asv_bench/benchmarks/rolling.py
Labels: Benchmark

#44308 CLN/TYP: address TODOs, ignores
  pandas/_libs/tslibs/dtypes.pyi
  pandas/core/arrays/base.py
  pandas/core/arrays/masked.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/period.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/core/internals/construction.py
  pandas/core/ops/array_ops.py
  pandas/core/reshape/reshape.py
  pandas/core/strings/accessor.py
  pandas/core/strings/object_array.py
  pandas/core/tools/datetimes.py
  pandas/io/stata.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/indexes/multi/test_setops.py
Labels: Clean, Typing

#44307 CLN: libparsers
  pandas/_libs/parsers.pyi
  pandas/_libs/parsers.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/io/parsers/base_parser.py
Labels: IO CSV, Clean

#44321 DOC: remove note about groupby.apply side-effect
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#44317 ENH: Add decimal parameter to read_excel
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/data/excel/test_decimal.ods
  pandas/tests/io/data/excel/test_decimal.xls
  pandas/tests/io/data/excel/test_decimal.xlsb
  pandas/tests/io/data/excel/test_decimal.xlsm
  pandas/tests/io/data/excel/test_decimal.xlsx
  pandas/tests/io/excel/test_readers.py
Labels: Enhancement, IO Excel

#44305 CLN: address TODOs
  pandas/_libs/hashtable.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/writers.pyi
  pandas/_libs/writers.pyx
  pandas/core/array_algos/putmask.py
  pandas/core/indexes/category.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/categorical/test_replace.py
  pandas/tests/arrays/timedeltas/test_reductions.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/indexes/categorical/test_indexing.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/conftest.py
  pandas/tests/indexes/interval/test_base.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/numeric/test_indexing.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/io/formats/style/test_to_latex.py
Labels: Clean

#44272 BUG: Styler `hide` compatible with `max_columns`
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_style.py
Labels: Bug, Styler

#44275 BUG: broadcasting listlike values in Series.__setitem__ GH#44265
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/series.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/indexing/test_where.py
Labels: Bug, Indexing, Nested Data

#44270 BUG: Series.replace(method='pad') with EA dtypes
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/generic.py
  pandas/core/missing.py
  pandas/core/series.py
  pandas/tests/series/methods/test_replace.py
Labels: Bug, Missing-data, ExtensionArray

#44316 BUG: failure to cast all-int floating dtypes when setting into int dtypes
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/dtypes/cast.py
  pandas/core/indexes/numeric.py
  pandas/core/internals/blocks.py
  pandas/tests/dtypes/cast/test_can_hold_element.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Indexing, Dtype Conversions

#43738 DOC: Added sentence to show that unmatched values return -1.
  pandas/core/indexes/base.py
Labels: Docs, Index, Stale

#44330 CLN: remove _AXIS_REVERSED
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/internals/test_internals.py
Labels: Internals, Clean

#44300 Detect CPORT header in SAS files
  pandas/io/sas/sas_xport.py
  pandas/tests/io/sas/data/DEMO_PUF.cpt
  pandas/tests/io/sas/test_xport.py
Labels: Error Reporting, IO SAS

#44328 REF: remove putmask_preserve, putmask_without_repeat
  pandas/core/array_algos/putmask.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/extension/test_numpy.py
Labels: Refactor, Indexing

#44314 BUG: PeriodIndex in pytables
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_put.py
Labels: Bug, IO HDF5, Period

#44274 DOC: added examples to DataFrame.var #44162
  pandas/core/generic.py
Labels: Docs

#44280 CI: Revert splitting 3.10 tests
  .github/workflows/python-dev.yml
Labels: CI, Python 3.10

#44338 Revert "REF: remove putmask_preserve, putmask_without_repeat"
  pandas/core/array_algos/putmask.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/extension/test_numpy.py
Labels: Indexing

#44237 BUG: all-NaT TDI division with object dtype preserve td64
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Missing-data, Timedelta

#44348 CLN: address TODOs/FIXMEs
  pandas/core/frame.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/base_class/test_setops.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/numeric/test_setops.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/ranges/test_range.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/io/formats/test_console.py
  pandas/tests/plotting/test_backend.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/series/methods/test_asof.py
  pandas/tests/series/test_logical_ops.py
Labels: Clean

#44362 CI: xfail tests failing on numpy dev
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/window/test_rolling.py
Labels: CI

#44319 Backport PR #44315 on branch 1.3.x (Pin aiobotocore to lower than 2.0 )
  ci/deps/actions-37-db.yaml
  ci/deps/actions-39.yaml
  ci/deps/azure-windows-38.yaml
  environment.yml
  requirements-dev.txt
Labels: CI, Dependencies

#44360 TYP: changed variable hashed to combined_hashed in dtype.py
  pandas/core/dtypes/dtypes.py
Labels: Typing

#44370 Backport PR #44362 on branch 1.3.x (CI: xfail tests failing on numpy dev)
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/window/moments/test_moments_rolling.py
Labels: CI

#44359 Update cython version for asv conf
  asv_bench/asv.conf.json
  environment.yml
  requirements-dev.txt
Labels: Benchmark

#44355 CLN: split giant dt accessor tests
  pandas/tests/series/accessors/test_dt_accessor.py
Labels: Testing

#44346 REF: re-remove _putmask_preserve
  pandas/core/array_algos/putmask.py
Labels: Refactor, Indexing

#44206 TST: enable 2D tests for Categorical
  pandas/core/arrays/categorical.py
  pandas/tests/extension/test_categorical.py
Labels: Testing, Categorical

#44381 TST/COMPAT: update csv test to infer time with pyarrow>=6.0
  pandas/compat/pyarrow.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: IO CSV, Arrow

#44374 TST: Make tests for groupby median/mean more strict on dtype
  pandas/tests/groupby/test_function.py
  pandas/tests/resample/test_datetime_index.py
Labels: Testing

#44385 TST: make get_upcast_box more flexible
  pandas/_testing/__init__.py
  pandas/tests/arithmetic/common.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Testing

#44388 CI: Use conda-forge to create Python 3.10 env
  .github/workflows/sdist.yml
Labels: CI, Python 3.10

#44389 Backport PR #44388 on branch 1.3.x (CI: Use conda-forge to create Python 3.10 env)
  .github/workflows/sdist.yml
Labels: CI, Python 3.10

#44375 CLN: misplaced indexing tests
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/timedeltas/test_ops.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_constructors.py
Labels: Testing, Clean, Index

#44105 BUG: PeriodIndex[B].to_timestamp inferring "D" instead of "B".
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/period.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Timeseries, Period

#44391 fix documentation on options in read_csv
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#44387 ENH: implement EA._putmask
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/interval.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
Labels: ExtensionArray

#44372 TST: split/collect partial tests
  pandas/tests/indexing/test_partial.py
Labels: Testing, Indexing

#44367 CLN: split/fixturize to_datetime tests
  pandas/tests/tools/test_to_datetime.py
Labels: Testing

#44395 TST: parametrize arithmetic tests
  pandas/tests/arithmetic/common.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Testing

#44377 REF/TST: collect index tests
  pandas/tests/indexes/datetimelike_/test_is_monotonic.py
  pandas/tests/indexes/datetimes/methods/test_isocalendar.py
  pandas/tests/indexes/datetimes/test_asof.py
  pandas/tests/indexes/datetimes/test_freq_attr.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/period/test_freq_attr.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/period/test_pickle.py
  pandas/tests/indexes/period/test_resolution.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/timedeltas/test_freq_attr.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexes/timedeltas/test_ops.py
  pandas/tests/series/test_api.py
Labels: Testing

#44356 Fixed regression in Series.duplicated for categorical dtype with bool categories
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/tests/series/methods/test_duplicated.py
Labels: Missing-data, Regression, Categorical

#44399 CLN: Refactor extract multiindex header call
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
Labels: IO CSV, Clean

#44401 BUG: DataFrame.stack with EA columns
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping, ExtensionArray

#44358 ENH: Use find_stack_level in pandas.core
  pandas/core/accessor.py
  pandas/core/arraylike.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/common.py
  pandas/core/computation/align.py
  pandas/core/computation/eval.py
  pandas/core/config_init.py
  pandas/core/construction.py
  pandas/core/describe.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/index.py
  pandas/core/indexers/utils.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexing.py
  pandas/core/internals/__init__.py
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/core/internals/managers.py
  pandas/core/ops/__init__.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/core/tools/datetimes.py
  pandas/core/window/ewm.py
  pandas/core/window/rolling.py
Labels: Enhancement

#44402 Backport PR #44356 on branch 1.3.x (Fixed regression in Series.duplicated for categorical dtype with bool categories)
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/tests/series/methods/test_duplicated.py
Labels: Missing-data, Regression, Categorical

#44407 TST: Add nulls fixture to duplicates categorical na test
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/tests/series/methods/test_duplicated.py
Labels: Testing, Missing-data, Categorical

#42743 [BUG] don't mangle null-objects in value_counts
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/tests/base/test_value_counts.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/libs/test_hashtable.py
Labels: Missing-data

#44345 BUG: frame.loc[2:, 'z'] not setting inplace when multi-block
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexing.py
  pandas/io/stata.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/test_reductions.py
Labels: Indexing

#44249 DataFrame.convert_dtypes doesn't preserve subclasses
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/generic/test_finalize.py
Labels: Compat, Constructors, Subclassing

#44416 ENH: Use find_stack_level
  pandas/_testing/asserters.py
  pandas/io/common.py
  pandas/io/date_converters.py
  pandas/io/excel/_base.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tseries/frequencies.py
  pandas/util/_validators.py
  pandas/util/testing.py
Labels: Compat

#44415 TST: de-duplicate assert_slics_equivalent
  pandas/_testing/__init__.py
  pandas/_testing/asserters.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Testing, Indexing

#44418 DOC: Add how=cross description to join
  pandas/core/frame.py
Labels: Docs, Reshaping

#44419 DOC: whatsnew for the improvement to warning messages
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#44390 BUG: handle NaNs in FloatingArray.equals
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/masked.py
  pandas/tests/arrays/floating/test_comparison.py
Labels: ExtensionArray

#44432 Fix FloatingArray.equals on older numpy
  pandas/core/arrays/masked.py
  pandas/core/dtypes/missing.py
Labels: ExtensionArray

#44428 BUG: DataFrame with mismatched NA value and dtype
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Indexing

#44413 TST: collect/share Index tests
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/indexes/base_class/test_formats.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_formats.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_pickle.py
  pandas/tests/indexes/multi/test_compat.py
  pandas/tests/indexes/multi/test_pickle.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/series/indexing/test_getitem.py
Labels: Testing, Indexing

#44436 TST: remove pyarrow bz2 xfail
  pandas/tests/io/parser/test_compression.py
Labels: Testing, Dependencies

#44435 REF: simplify putmask_smart
  pandas/core/array_algos/putmask.py
  pandas/core/internals/blocks.py
Labels: Refactor, Indexing, Internals

#44439 ENH: Use stacklevel in warnings
  pandas/core/algorithms.py
  pandas/core/arraylike.py
  pandas/core/arrays/datetimelike.py
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/io/excel/_base.py
  pandas/io/formats/style.py
Labels: Enhancement, Warnings

#44437 TST: FIXMES in DataFrame.quantile tests
  pandas/tests/frame/methods/test_quantile.py
Labels: Testing, Algos

#44441 BLD: Exclude CPT data files
  MANIFEST.in
Labels: Build

#44440 DOC: Some minor doc cleanups
  doc/source/user_guide/io.rst
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/io/parsers/readers.py
Labels: Docs

#44408 BUG: read_csv raising if parse_dates is used with MultiIndex columns
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/base_parser.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: Bug, IO CSV

#44430 Doc: Clean obj.empty docs to describe Series/DataFrame
  pandas/core/generic.py
Labels: Docs

#44404 BUG: .get_indexer_non_unique() must return an array of ints (#44084)
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_indexing.py
Labels: Indexing, MultiIndex, Interval

#44325 BUG: closes #44312: fixes unwanted TypeError with nullable nested metadata in json_normalize
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/json/_normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON

#44331 DOC: df.to_html documentation incorrectly contains min_rows optional param
  pandas/core/frame.py
  pandas/io/formats/format.py
Labels: Docs

#44003 [BUG] Fix DataFrameGroupBy.boxplot with subplots=False fails for object columns
  doc/source/whatsnew/v1.4.0.rst
  pandas/plotting/_matplotlib/boxplot.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Visualization

#44397 ENH: Support timespec argument in Timestamp.isoformat()
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timestamp/test_formats.py
Labels: Enhancement, Timeseries

#44398 DEPR: PeriodIndex.astype(dt64)
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/methods/test_astype.py
  pandas/tests/indexes/test_common.py
Labels: Period, Deprecate

#44443 COMPAT: Python 3.9.8
  pandas/tests/io/parser/test_quoting.py
Labels: Testing, Compat

#44444 Backport PR #44443 on branch 1.3.x (COMPAT: Python 3.9.8)
  pandas/tests/io/parser/test_quoting.py
Labels: Testing, Compat

#44447 DOC: Remove use of as_type for PeriodIndex to DatetimeIndex conversion
  doc/source/user_guide/timeseries.rst
Labels: Docs, Period

#44449 TST: check_stacklevel=True in various tests
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/dtypes/cast/test_promote.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_join.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/resample/test_deprecated.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/series/accessors/test_cat_accessor.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/test_expressions.py
  pandas/tests/window/test_rolling.py
Labels: Testing, Warnings

#43855 TYP: make IOHandles generic
  pandas/_typing.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/json/_json.py
  pandas/io/parquet.py
  pandas/io/parsers/base_parser.py
  pandas/io/stata.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Typing

#44361 CLN: Removed _SAFE_NAMES_WARNING in io.sql
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL, Clean

#44452 Revert "CI: xfail tests failing on numpy dev"
  pandas/tests/window/test_rolling.py
Labels: CI

#44469 Backport PR #44452: Revert "CI: xfail tests failing on numpy dev"
  pandas/tests/window/moments/test_moments_rolling.py
Labels: CI, Compat

#44468 TYP/CLN: remove defaults from overloads
  pandas/core/base.py
  pandas/core/reshape/concat.py
  pandas/io/common.py
  pandas/io/sql.py
Labels: Clean, Typing

#44462 DataFrame.rename renames wrong elements
  pandas/tests/frame/methods/test_rename.py
Labels: Testing

#44460 ENH: don't silently ignore dtype in NaT/Timestamp/Timedelta to_numpy
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Missing-data

#44139 CLN: remove pyarrow<1 compat
  ci/deps/actions-38-locale.yaml
  pandas/compat/__init__.py
  pandas/compat/_optional.py
  pandas/compat/pyarrow.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/masked/test_arrow_compat.py
  pandas/tests/arrays/period/test_arrow_compat.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/arrow/test_timestamp.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_parquet.py
Labels: Clean

#44446 Added "." on to check_dtype and obj parameter
  pandas/_testing/asserters.py
Labels: Docs

#44466 BUG: fix timedelta floordiv with scalar float
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Bug, Numeric Operations, Timedelta

#44425 BUG: Using boolean keys to select a column (GH44322)
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing

#44475 REF: rolling benchmarks to reduce redundant benchmarks
  asv_bench/benchmarks/rolling.py
Labels: Benchmark, Window

#44448 CI/TST Removed Timestamp.now() from tests. #44341
  pandas/tests/arrays/test_datetimelike.py
Labels: Testing, Timezones

#44455 CLN: TODOs and FIXMEs
  pandas/core/array_algos/quantile.py
  pandas/core/dtypes/cast.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/ops/missing.py
  pandas/tests/base/test_value_counts.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/reshape/concat/test_invalid.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/util/_test_decorators.py
Labels: Clean

#44474 BUG: Tick + np.timedelta64
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_business_day.py
  pandas/tests/tseries/offsets/test_custom_business_day.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Frequency

#44434 BUG: read_csv and read_fwf not skipping all defined rows when nrows is given
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_skiprows.py
Labels: Bug, IO CSV

#44352 changed shape argument for ndarray from int to tuple in ./core/strings/object_array.py
  pandas/core/strings/object_array.py
Labels: Typing

#44491 DOCS: use non-deprecated method in doc examples
  doc/source/user_guide/style.ipynb
Labels: Docs, Styler

#44493 TST: share a bunch of test_custom_business_day
  pandas/tests/tseries/offsets/test_business_day.py
  pandas/tests/tseries/offsets/test_custom_business_day.py
Labels: Testing, Frequency

#42222 ENH: add if_sheet_exists='overlay' to ExcelWriter
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/excel/_base.py
  pandas/io/excel/_openpyxl.py
  pandas/tests/io/excel/test_openpyxl.py
Labels: Enhancement, IO Excel

#44492 BUG: NumericArray.__pos__ should make a copy
  pandas/core/arrays/numeric.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/floating/test_arithmetic.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Bug, Algos

#44479 CLN: TODOs and FIXMEs
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/masked.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/internals/managers.py
  pandas/core/nanops.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sql.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/arrays/floating/test_arithmetic.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/indexes/datetimes/methods/test_insert.py
  pandas/tests/indexes/multi/test_formats.py
  pandas/tests/series/methods/test_convert.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/tools/test_to_datetime.py
Labels: Clean

#44445 ENH: Infer inner file name of zip archive (GH39465)
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/common.py
  pandas/tests/io/formats/test_to_csv.py
Labels: IO Data

#43951 TYP: Use Protocols for file-like objects in read/to_*
  pandas/_testing/_io.py
  pandas/_typing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odfreader.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_pyxlsb.py
  pandas/io/feather_format.py
  pandas/io/formats/csvs.py
  pandas/io/formats/format.py
  pandas/io/formats/info.py
  pandas/io/formats/style.py
  pandas/io/formats/xml.py
  pandas/io/html.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/io/pickle.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_xport.py
  pandas/io/sas/sasreader.py
  pandas/io/stata.py
  pandas/io/xml.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Typing

#44357 DOC: Clarify DST rounding behavior in Timestamp/DatetimeIndex
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
Labels: Docs, Timeseries

#44495 PERF: lib.Validator iteration
  pandas/_libs/lib.pyx
  pandas/core/arrays/string_.py
  pandas/core/dtypes/inference.py
  pandas/tests/dtypes/test_inference.py
Labels: Performance

#44426 TYP: improve typing for DataFrame.to_string
  pandas/core/frame.py
Labels: Typing

#44510 TYP/CI: fix to_string overload
  pandas/core/frame.py
Labels: CI, Typing

#44471 BUG: fix timedelta floordiv with scalar float (correction of #44466)
  pandas/core/arrays/timedeltas.py
Labels: Bug, Numeric Operations, Timedelta

#44506 DOC: df.to_html documentation incorrectly contains min_rows optional param (release note)
  doc/source/whatsnew/v1.4.0.rst
Labels: IO HTML

#44525 Comment deleted as build on Mac failed. Suggested by @marcogorelli.
  doc/source/development/contributing_environment.rst
Labels: Docs

#44523 COMPAT: Matplotlib 3.5.0
  pandas/plotting/_matplotlib/compat.py
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_hist_box_by.py
  pandas/tests/plotting/test_common.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_series.py
Labels: Visualization, Compat

#44529 CLN: tighten noqas
  doc/source/user_guide/io.rst
  pandas/api/__init__.py
  pandas/core/algorithms.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/dtypes/missing.py
  pandas/core/internals/blocks.py
  pandas/core/reshape/tile.py
  pandas/io/sas/__init__.py
  pandas/tests/arrays/boolean/test_function.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/arrays/floating/test_function.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/computation/test_compat.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/categorical/test_formats.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/io/conftest.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/test_series.py
  pandas/tests/resample/test_base.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/test_repr.py
  pandas/tests/test_downstream.py
  pandas/tseries/api.py
  pandas/tseries/frequencies.py
  pandas/util/__init__.py
  pandas/util/_decorators.py
  pandas/util/_tester.py
  pandas/util/testing.py
Labels: Clean

#44489 TST: fix deprecation warning in test
  pandas/tests/io/formats/style/test_style.py
Labels: Testing, Deprecate, Styler

#44459 BUG: Series/Index arithmetic result names with NAs
  doc/source/whatsnew/v1.4.0.rst
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/core/ops/common.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/test_common.py
Labels: Bug, Reshaping, Numeric Operations, NA - MaskedArrays

#44535 TST: Address numba warnings in test suite
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
Labels: Testing

#44537 DOC: update styler user guide for out of date material
  doc/source/user_guide/style.ipynb
Labels: Docs, Styler

#44442 BUG: AttributeError: 'BooleanArray' object has no attribute 'sum' while infer types #44079
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/base_parser.py
  pandas/tests/io/parser/test_index_col.py
Labels: IO CSV, NA - MaskedArrays

#44520 REF: implement _maybe_squeeze_arg
  pandas/core/internals/blocks.py
Labels: Refactor, Internals

#44519 REF: remove unused allow_object kwarg from sequence_to_dt64ns
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/cast.py
  pandas/tests/arrays/datetimes/test_constructors.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Refactor

#44497 ERR: Raise ValueError when BaseIndexer start & end bounds are unequal length
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/window/ewm.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_base_indexer.py
Labels: Window, Segfault

#44505 REF: combine isnaobj+isnaobj_old
  pandas/_libs/missing.pxd
  pandas/_libs/missing.pyx
  pandas/_libs/tslibs/nattype.pxd
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/nattype.pyx
  pandas/core/dtypes/missing.py
Labels: Refactor, Missing-data

#44533 BUG: BooleanArray raising on comparison to string
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/boolean.py
  pandas/tests/arrays/boolean/test_logical.py
  pandas/tests/frame/methods/test_replace.py
Labels: Bug, Numeric Operations, replace, NA - MaskedArrays

#44530 Fix regression ignoring arrays in dtype check for merge_asof
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Regression

#44507 BUG: Period incorrectly allowing np.timedelta64('NaT')
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/tests/arrays/period/test_constructors.py
  pandas/tests/scalar/period/test_period.py
Labels: Timedelta, Period

#44501 (TST) Replacing Timestamp.now () in tests.
  pandas/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/arrays/timedeltas/test_reductions.py
  pandas/tests/dtypes/cast/test_construct_from_scalar.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_comparisons.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/methods/test_replace.py
  pandas/tests/tools/test_to_timedelta.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_timezones.py
Labels: Testing, Timeseries

#44538 Backport PR #44530 on branch 1.3.x (Fix regression ignoring arrays in dtype check for merge_asof)
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Regression

#44532 BUG: td64+offset
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_business_day.py
Labels: Timedelta

#44522 DEPR: DateOffset.apply
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tseries/offsets/common.py
  pandas/tests/tseries/offsets/test_business_day.py
  pandas/tests/tseries/offsets/test_business_hour.py
  pandas/tests/tseries/offsets/test_custom_business_hour.py
  pandas/tests/tseries/offsets/test_fiscal.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Frequency, Deprecate

#44531 Add json normalize back into doc and move read_json to pd namespace
  doc/source/reference/io.rst
Labels: Docs, IO JSON

#44518 BUG: DataFrame with scalar tzaware Timestamp
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/datetimes.py
  pandas/tests/frame/test_constructors.py
Labels: Regression, Timezones, Constructors

#44487 update astype keyerror msg
  pandas/core/generic.py
  pandas/tests/frame/methods/test_astype.py
Labels: Error Reporting

#44457 REF: dont dispatch Block.putmask to Block.where
  pandas/core/internals/blocks.py
Labels: Refactor, Internals

#44454 DOC: substitute multiple entries for `subset` in `style.py`
  pandas/io/formats/style.py
Labels: Docs, Styler
