Repository pandas-dev/pandas, pull requests merged in 2021-03, with the labels that each got.

#40132 TST: share value_counts tests
  pandas/tests/indexes/datetimelike_/test_value_counts.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/period/test_ops.py
  pandas/tests/indexes/timedeltas/test_ops.py
Labels: Testing

#40133 TST: collect tests by method, split large tests
  pandas/core/frame.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/categorical/test_append.py
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/categorical/test_formats.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexes/timedeltas/test_partial_slicing.py
  pandas/tests/series/indexing/test_getitem.py
Labels: Testing

#40085 [ArrayManager] TST: resample tests
  .github/workflows/ci.yml
  pandas/tests/resample/test_base.py
Labels: Internals, Testing

#40138 to_offset was not using the compiled regex
  pandas/_libs/tslibs/offsets.pyx
Labels: Clean, Frequency

#40128 CLN: remove conda recipe
  conda.recipe/bld.bat
  conda.recipe/build.sh
  conda.recipe/meta.yaml
Labels: Build, Clean

#39917 BENCH: collect low-dependency asvs
  asv_bench/benchmarks/algorithms.py
  asv_bench/benchmarks/attrs_caching.py
  asv_bench/benchmarks/dtypes.py
  asv_bench/benchmarks/gil.py
  asv_bench/benchmarks/indexing_engines.py
  asv_bench/benchmarks/inference.py
  asv_bench/benchmarks/libs.py
  asv_bench/benchmarks/reindex.py
  asv_bench/benchmarks/timedelta.py
  asv_bench/benchmarks/timeseries.py
Labels: Benchmark

#40119 CLN: Window aggregation typing
  pandas/_libs/window/aggregations.pyx
Labels: Clean, Window

#40125 STYLE update pre-commit-config
  .pre-commit-config.yaml
Labels: Style

#40120 REF: re-use objects_to_datetime64ns in maybe_infer_to_datetimelike
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/cast.py
Labels: Refactor, Timeseries

#40116 PERF: DTA/TDA _simple_new disallow i8 values
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/cast.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/nanops.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/indexes/test_common.py
Labels: Internals, Performance, Timeseries

#40129 REF: share recarray constructor code
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Constructors, Refactor

#40121 TYP: to_arrays, BUG: from_records empty dtypes
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/test_constructors.py
Labels: Dtypes, Reshaping

#40142 CI, TST enable branch coverage
  setup.cfg
Labels: CI

#40150 PERF: extract_array -> _values
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/construction.py
  pandas/core/dtypes/concat.py
  pandas/core/series.py
Labels: Performance

#40155 REF: avoid circular (runtime) import in dtypes.cast
  pandas/core/dtypes/cast.py
Labels: Timedelta

#40137 DOC: 1.2.3 release date
  doc/source/whatsnew/v1.2.3.rst
Labels: Docs

#40159 STYLE: incondintent namaspace(series)
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_where.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/series/methods/test_shift.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_repr.py
Labels: Style

#40161 STYLE: Inconsistent namespace - dtypes (pandas-dev#39992)
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/dtypes/test_missing.py
Labels: Style

#40165 Backport PR #40137 on branch 1.2.x (DOC: 1.2.3 release date)
  doc/source/whatsnew/v1.2.3.rst
Labels: Docs

#40170 DOC: Start v1.2.4 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.2.3.rst
  doc/source/whatsnew/v1.2.4.rst
Labels: Docs

#40172 Backport PR #40170 on branch 1.2.x (DOC: Start v1.2.4 release notes)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.2.3.rst
  doc/source/whatsnew/v1.2.4.rst
Labels: Docs

#38007 ENH: Arrow backed string array - implement factorize() method without casting to objects
  asv_bench/benchmarks/algorithms.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_string.py
Labels: ExtensionArray, Strings

#40166 REF: remove internal Block usage from FrameColumnApply
  pandas/core/apply.py
  pandas/core/internals/managers.py
Labels: Apply, Internals, Refactor

#40141 REF: move Block.astype implementation to dtypes/cast.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_astype.py
  pandas/util/_exceptions.py
Labels: Dtypes, Internals, Refactor

#40122 Use tempfile for creating a file in home directory for a IO test
  pandas/tests/io/test_common.py
Labels: Testing

#40156 REF: refactor array_strptime_with_fallback from to_datetime
  pandas/core/tools/datetimes.py
Labels: Refactor, Timeseries

#40147 [ArrayManager] Ensure to store datetimelike data as DatetimeArray/TimedeltaArray (and not ndarray)
  pandas/core/internals/array_manager.py
  pandas/tests/frame/methods/test_rename.py
Labels: Internals, Refactor

#40096 BUG: df.loc setitem-with-expansion with duplicate index
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/multi.py
  pandas/core/indexing.py
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_loc.py
Labels: Indexing

#40176 PERF: don't sort data twice in groupby apply when not using libreduction fast_apply
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_apply.py
Labels: Groupby, Performance

#39022 Deprecate DataFrame indexer for iloc setitem and getitem
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
Labels: Error Reporting, Indexing

#40163 BUG: DataFrame(frozenset) should raise
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/construction.py
  pandas/core/series.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/series/test_constructors.py
Labels: Bug

#40187 REF: move mixed-int handling from maybe_cast_to_datetime
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/cast.py
Labels: Refactor, Timeseries

#40113 CLN/TST: normalize test_frame_apply
  pandas/tests/apply/test_frame_apply.py
Labels: Apply, Clean, Testing

#40092 TST/REF: Consolidate tests in apply.test_invalid_arg
  pandas/tests/apply/conftest.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_frame_apply_relabeling.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/apply/test_series_transform.py
Labels: Apply, Refactor, Testing

#40162 BUG: Add decl when xml_declaration=True and pretty_print=False for et…
  pandas/io/formats/xml.py
  pandas/tests/io/xml/test_to_xml.py
Labels: XML

#40188 CI: xfail npdev test_groupby_apply_identity
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/test_boolean.py
Labels: Groupby, Testing

#39991 [ArrayManager] DataFrame constructors
  .github/workflows/ci.yml
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/construction.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_groupby.py
Labels: Constructors, Internals, Refactor

#40178 PERF: cache _get_cython_function in groupby ops
  pandas/core/groupby/ops.py
Labels: Groupby, Performance

#40194 PERF: avoid zeros_like in groupby.pyx
  pandas/_libs/groupby.pyx
Labels: Groupby, Performance

#40164 BUG: EWM.__getitem__ raised error with times
  doc/source/whatsnew/v1.3.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/ewm.py
  pandas/tests/window/test_ewm.py
Labels: Bug, Window

#40185 REF: split out to_datetime_with_unit, _to_datetime_with_format
  pandas/core/tools/datetimes.py
Labels: Refactor, Timeseries

#40190 REF: move dtype-validation out of maybe_cast_to_datetime
  pandas/core/dtypes/cast.py
Labels: Refactor, Timeseries

#40191 REF: re-use sequence_to_datetimes in try_datetime
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/cast.py
Labels: Refactor, Timeseries

#40154 TYP: internals.construction
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Constructors, Typing

#40203 REF: get reshape kludge out of dtypes.cast
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
Labels: Refactor, Reshaping

#40207 DOC: Add Notes and Examples back to GroupBy.apply docs template
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#40206 DOC: Update read_hdf's acceptable path types
  pandas/io/pytables.py
Labels: Docs, IO HDF5

#36299 BUG: Index.union() inconsistent with non-unique Indexes
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/algorithms.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/test_algos.py
Labels: Bug, Index

#40212 CI: remove xfail in grouopby #40144
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/test_boolean.py
Labels: Groupby, Testing

#40221 STYLE: Inconsistent namespace - arrays #39992
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/arrays/datetimes/test_reductions.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/test_datetimelike.py
Labels: Style

#40220 STYLE: Inconsistent namespace - resample #39992
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_deprecated.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/resample/test_timedelta.py
Labels: Style

#40216 TST: remove some no longer necessary ArrayManager skips for groupby
  pandas/tests/frame/methods/test_count.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/frame/methods/test_reorder_levels.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/reshape/merge/test_join.py
Labels: Internals, Testing

#40218 STYLE: Inconsistent namespace - scalar #39992
  pandas/tests/scalar/test_na_scalar.py
Labels: Style

#40213 TST/CLN: Move raising apply tests to test_invalid_arg
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/apply/test_series_apply.py
Labels: Apply, Clean, Testing

#40222 TST: use env variable instead of pytest option for testing ArrayManager
  .github/workflows/ci.yml
  pandas/conftest.py
  pandas/core/config_init.py
  pandas/util/_test_decorators.py
Labels: Testing

#40223 STYLE: Inconsistent namespace - api
  pandas/tests/api/test_api.py
Labels: Style

#40199 REF: remove block access in groupby libreduction Series(Bin)Grouper
  pandas/_libs/reduction.pyx
  pandas/core/internals/managers.py
Labels: Groupby, Internals

#40181 CLN: Refactor tests and delete duplicates
  pandas/conftest.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_at.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/indexing/test_na_indexing.py
Labels: Clean, Testing

#40224 STYLE: Inconsistent namespace - arithmetic (#39992)
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Style

#39163 API/BUG: always try to operate inplace when setting with loc/iloc[foo, bar]
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
Labels: Indexing

#40035 PERF: json_normalize, for basic use case
  asv_bench/benchmarks/io/json.py
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/json/_normalize.py
Labels: IO JSON, Performance

#40225 CLN: Minor cleanup of caching
  pandas/core/base.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/ranges/test_range.py
Labels: Clean

#39975 BUG: Incomplete Styler copy methods fix (#39708)
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Copy / view semantics, Styler

#40152 [ArrayManager] Add SingleArrayManager to back a Series
  .github/workflows/ci.yml
  pandas/_typing.py
  pandas/core/construction.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/indexing.py
  pandas/core/internals/__init__.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/core/internals/managers.py
  pandas/core/nanops.py
  pandas/core/series.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/series/test_constructors.py
Labels: Internals, Refactor

#40143 REGR: reduction operations failing if `min_count` is larger
  doc/source/whatsnew/v1.2.4.rst
  pandas/core/frame.py
  pandas/core/nanops.py
  pandas/tests/frame/test_reductions.py
Labels: Reductions

#40180 Make Index.all compatible with numpy.all
  doc/source/whatsnew/v1.3.0.rst
  pandas/compat/numpy/function.py
  pandas/core/indexes/base.py
  pandas/tests/reductions/test_reductions.py
Labels: Bug, Compat, Index

#40209 REF: tighten signature on maybe_convert_platform
  pandas/core/arrays/interval.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
Labels: Refactor

#40196 [ArrayManager] ENH: ArrayManager.convert without block fallback
  pandas/core/internals/array_manager.py
Labels: Internals, Refactor

#39700 [ArrayManager] TST: get tests running for /tests/frame
  .github/workflows/ci.yml
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Internals, Testing

#40208 DOC: Fix Examples section for some window methods
  pandas/core/window/doc.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Docs, Window

#39692 PERF: optimize algos.take for repeated calls
  pandas/core/array_algos/take.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/array_manager.py
  pandas/tests/test_take.py
Labels: Algos, Performance

#40189 ENH: ArrayManager.quantile
  pandas/core/array_algos/quantile.py
  pandas/core/frame.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_describe.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_quantile.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/resample/test_base.py
  pandas/tests/series/methods/test_describe.py
  pandas/tests/series/methods/test_quantile.py
Labels: Enhancement, Numeric

#40217 [ArrayManager] TST: activate a bunch of (passing) tests
  .github/workflows/ci.yml
  pandas/tests/generic/test_generic.py
Labels: Internals, Testing

#40248 PERF: avoid validating indices repeatedly in ArrayManager.reindex_indexer
  pandas/core/internals/array_manager.py
Labels: Performance

#40247 BENCH: add DataFrame.reindex(columns=..) benchmark that selects existing columns
  asv_bench/benchmarks/frame_methods.py
Labels: Benchmark

#40238 DEPR: Partial failure in Series.transform and DataFrame.transform
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/apply.py
  pandas/tests/apply/common.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/apply/test_series_apply.py
Labels: Apply, Deprecate

#40251 [ArrayManager] Fix window operations with axis=1
  .github/workflows/ci.yml
  pandas/conftest.py
  pandas/core/internals/array_manager.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_rolling.py
Labels: Internals, Window

#40182 API: pseudo-public internals API for downstream libraries
  pandas/core/internals/__init__.py
  pandas/core/internals/api.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/construction.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_api.py
  pandas/tests/internals/test_internals.py
Labels: API - Consistency, API Design, Internals

#40233 DEPS: skip html tests if html5lib is not installed #40198
  pandas/tests/io/test_html.py
Labels: CI, Dependencies, IO HTML

#40240 CLN: Remove to_xml from format.py to run directly in frame.py
  pandas/core/frame.py
  pandas/io/formats/format.py
  pandas/io/formats/xml.py
Labels: Clean, XML

#40236 PERF: non-cython groupby.apply
  pandas/core/generic.py
  pandas/core/groupby/ops.py
Labels: Groupby, Performance

#40253 Backport PR #40233 on branch 1.2.x (DEPS: skip html tests if html5lib is not installed #40198)
  pandas/tests/io/test_html.py
Labels: Dependencies

#40075 REF: move logic of 'block manager axis' into the BlockManager
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
Labels: Internals, Refactor

#40254 PERF/CLN: restrict _isna_ndarraylike to actual ndarray/EA
  pandas/core/dtypes/missing.py
Labels: Clean, Missing-data, Performance

#40237 Backport PR #40143 on branch 1.2.x (REGR: reduction operations failing if `min_count` is larger)
  doc/source/whatsnew/v1.2.4.rst
  pandas/core/frame.py
  pandas/core/nanops.py
  pandas/tests/frame/test_reductions.py
Labels: Reductions

#39953 PERF: avoid object conversion in fillna(method=pad|backfill) for masked arrays
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v1.3.0.rst
  pandas/_libs/algos.pyx
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/string_arrow.py
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/core/series.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_sparse.py
Labels: Missing-data, NA - MaskedArrays, Performance

#40246 PERF: specialized 1D take version
  pandas/core/array_algos/take.py
  pandas/core/internals/array_manager.py
Labels: Algos, Performance

#40242 ENH: consistent `Styler.highlight_X` arg signature with `props`
  doc/source/reference/style.rst
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_highlight.py
Labels: Styler

#40134 DEPR: `Styler.set_na_rep` and `.set_precision` in favour of `.format(na_rep='x', precision=3)`
  doc/source/reference/style.rst
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Deprecate, Styler

#40227 PERF: BlockPlacement construction
  pandas/_libs/internals.pyx
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Internals, Performance

#40264 CI: numpy-dev PerformanceWarning
  pandas/tests/extension/test_sparse.py
Labels: CI

#40270 TYP: remove ignore from makeCustomIndex
  pandas/_testing/__init__.py
Labels: Typing

#40276 STYLE: Inconsistent namespace - plotting
  pandas/tests/plotting/frame/test_frame.py
Labels: Style

#40277 Reorder pre-commit-config and normalize id names
  .pre-commit-config.yaml
Labels: Style

#40266 DOC: GH39672 Pandas dataframe pct_change function arguments
  pandas/core/generic.py
Labels: Docs

#40268 TYP: add mypy messages as comments to ignores
  pandas/conftest.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/floating.py
  pandas/core/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/nanops.py
  pandas/core/series.py
  pandas/io/common.py
  pandas/io/pickle.py
  pandas/io/pytables.py
  pandas/io/stata.py
Labels: Typing

#40283 STYLE: Inconsistent namespace - tools (pandas-dev#39992)
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_numeric.py
  pandas/tests/tools/test_to_timedelta.py
Labels: Style

#40267 Remove pd_array from tests
  pandas/tests/arithmetic/common.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/series/methods/test_view.py
  scripts/check_for_inconsistent_pandas_namespace.py
Labels: Style

#40280 STYLE: Pandas codespell fix for documentation
  .pre-commit-config.yaml
  doc/source/development/contributing.rst
  doc/source/development/debugging_extensions.rst
  doc/source/getting_started/comparison/comparison_with_spreadsheets.rst
  doc/source/getting_started/comparison/comparison_with_sql.rst
  doc/source/user_guide/dsintro.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/window.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v1.2.1.rst
  doc/source/whatsnew/v1.3.0.rst
  setup.cfg
Labels: Style

#40278 Move cpplint check to pre-commit
  .pre-commit-config.yaml
  ci/code_checks.sh
Labels: Style

#40292 CLN: Window code
  pandas/core/window/ewm.py
  pandas/core/window/rolling.py
Labels: Clean, Window

#40290 DOC: fix grammar issues and incorrect link in "Getting Started" guide…
  doc/source/getting_started/index.rst
Labels: Docs

#40279 DOC: Clarify DataFrame.combine_first and Series.combine_first
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs

#40301 [ArrayManager] Fix DataFrame.from_records with emtpy size
  pandas/core/internals/construction.py
  pandas/tests/frame/constructors/test_from_records.py
Labels: Internals

#40284 API: remove `.set_tooltips_class` incorpate to `.set_tooltips`
  doc/source/reference/style.rst
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_tooltip.py
Labels: Clean, Styler

#40282 CI: avoid port-already-in-use errors
  pandas/tests/io/test_user_agent.py
Labels: CI

#40281 REF: Block.putmask dont use split_and_operate
  pandas/core/array_algos/putmask.py
  pandas/core/internals/blocks.py
Labels: Internals

#40265 TYP: remove ignores for "Cannot assign to a method"
  pandas/core/generic.py
Labels: Typing

#40271 TYP: remove ignore from PandasObject.__sizeof__
  pandas/core/base.py
Labels: Typing

#40272 TYP: remove ignore from MPLPlot._plot
  pandas/plotting/_matplotlib/core.py
Labels: Typing

#40261 CLN: Remove _axis from apply
  pandas/core/apply.py
  pandas/core/groupby/generic.py
Labels: Apply, Clean

#39751 ENH: Implement rounding for floating dtype array #38844
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/arrays/numeric.py
  pandas/tests/arrays/masked/test_function.py
  pandas/tests/series/methods/test_round.py
Labels: Enhancement, ExtensionArray

#40295 PERF: declare contiguity in libgroubpy
  pandas/_libs/algos_common_helper.pxi.in
  pandas/_libs/groupby.pyx
  pandas/_libs/missing.pyx
  pandas/core/groupby/ops.py
Labels: Groupby, Performance

#40310 GH39992 update inconsistent namespace usage for reductions
  pandas/tests/reductions/test_reductions.py
Labels: Style

#39949 TYP: hashing
  pandas/_libs/hashing.pyx
  pandas/_libs/lib.pyx
  pandas/core/frame.py
  pandas/core/util/hashing.py
  pandas/tests/util/test_hashing.py
Labels: Typing

#40294 ENH: NDArrayBackedExtensionArray.fillna(method) with 2d
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/period.py
  pandas/core/missing.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/extension/base/dim2.py
Labels: Internals, Missing-data

#40314 ERR: Raise NotImplimentedError for EWMA with times and adjust=False
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/window/ewm.py
  pandas/tests/window/test_ewm.py
Labels: Error Reporting, Window

#40241 ENH: allow start=range_object in RangeIndex constructor
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/ranges/test_constructors.py
Labels: Constructors, Index

#40330 REF/TYP: indexes
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/range.py
  pandas/tests/groupby/test_function.py
Labels: Index, Typing

#39777 ENH: 'encoding_errors' argument for read_csv/json
  doc/source/whatsnew/v1.3.0.rst
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/io.c
  pandas/_libs/src/parser/io.h
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/parser/tokenizer.h
  pandas/io/common.py
  pandas/io/json/_json.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/test_common.py
Labels: IO CSV, IO JSON, Unicode

#40324 BUG: Fix sort_values for empty by argument
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_sort_values.py
Labels: Algos, Bug

#38134 REF: de-duplicate Block.__init__
  pandas/core/internals/api.py
  pandas/core/internals/blocks.py
Labels: Deprecate, Internals, Mothballed, Refactor

#40331 REF: prelims for 2D DTA/TDA
  asv_bench/benchmarks/reshape.py
  pandas/core/groupby/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/internals/ops.py
  pandas/core/nanops.py
  pandas/core/reshape/reshape.py
Labels: Internals, Reshaping

#40214 BUG: read_excel skips single-column empty rows
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/data/excel/one_col_blank_line.ods
  pandas/tests/io/data/excel/one_col_blank_line.xls
  pandas/tests/io/data/excel/one_col_blank_line.xlsb
  pandas/tests/io/data/excel/one_col_blank_line.xlsm
  pandas/tests/io/data/excel/one_col_blank_line.xlsx
  pandas/tests/io/excel/test_readers.py
Labels: IO Excel, Regression

#40332 STYLE: Extending codespell to pandas/tests Part 2
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/frame/methods/test_values.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_libgroupby.py
  pandas/tests/indexes/categorical/test_formats.py
  pandas/tests/indexes/datetimelike_/test_sort_values.py
  pandas/tests/indexes/datetimes/methods/test_insert.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/timedeltas/methods/test_insert.py
  pandas/tests/indexes/timedeltas/test_setops.py
  pandas/tests/indexing/common.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/indexing/test_iloc.py
Labels: Style

#40347 [ArrayManager] TST: enable arrays tests
  .github/workflows/ci.yml
  pandas/core/internals/array_manager.py
Labels: Internals

#40200 TYP fixup overloads for reset_index
  pandas/core/frame.py
Labels: Typing

#40339 PERF: Categorical._from_backing_data
  pandas/_libs/algos_take_helper.pxi.in
  pandas/_libs/internals.pyx
  pandas/core/arrays/categorical.py
  pandas/core/indexes/extension.py
Labels: Categorical, Performance

#40262 CLN: BlockManager.get_slice require only slice arg
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/internals/test_internals.py
Labels: Internals, Refactor

#40342 CLN: remove unused c_encoding
  pandas/_libs/parsers.pyx
Labels: Clean, IO CSV, Unicode

#40127 BUG: Set dtypes of new columns when stacking (#36991)
  doc/source/whatsnew/v1.3.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Dtypes, Reshaping

#40334 BUG: fix regression in Styler.export/use
  doc/source/whatsnew/v1.3.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Style

#40337 PERF: do ndim validation before Block.__init__
  pandas/core/internals/api.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/internals/test_internals.py
Labels: Internals

#40354 Fix formatting in extractall example outputs
  pandas/core/strings/accessor.py
Labels: Docs

#40338 REF: share code ArrayManager/BlockManager
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Internals, Refactor

#40365 BUG: Post-merge fixup, raise on dimension-expanding
  pandas/core/internals/managers.py
Labels: CI, Internals

#40320 STYLE: Extending codespell to pandas/tests
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/computation/test_eval.py
  pandas/tests/config/test_config.py
  pandas/tests/dtypes/cast/test_promote.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/test_parquet.py
Labels: Style

#40370 CI: mypy fixup
  pandas/core/internals/api.py
  pandas/core/internals/blocks.py
Labels: CI, Typing

#40286 STYLE: Resolved Inconsistent namespace
  .pre-commit-config.yaml
  pandas/tests/arithmetic/test_interval.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/base/test_conversion.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/indexes/period/test_setops.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_check_indexer.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/series/test_ufunc.py
  pandas/tests/strings/test_cat.py
  pandas/tests/test_algos.py
Labels: Style

#40372 STYLE: Extending codespell to pandas/tests/ part3 38802
  .pre-commit-config.yaml
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_timezones.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/libs/test_hashtable.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_subplots.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_series.py
  pandas/tests/reshape/concat/test_datetimes.py
  pandas/tests/reshape/merge/test_merge_ordered.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/series/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_nlargest.py
  pandas/tests/series/methods/test_to_csv.py
  pandas/tests/strings/test_cat.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_fields.py
Labels: Style

#40381 Docs - Grammar fix #40377
  pandas/core/groupby/groupby.py
Labels: Docs

#40293 TYP: Window code
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Typing, Window

#40379 TYP: change ArrayLike/AnyArrayLike alias to Union
  pandas/_typing.py
  pandas/core/algorithms.py
  pandas/core/array_algos/putmask.py
  pandas/core/array_algos/quantile.py
  pandas/core/array_algos/replace.py
  pandas/core/array_algos/take.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/arrays/string_arrow.py
  pandas/core/base.py
  pandas/core/common.py
  pandas/core/computation/pytables.py
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/missing.py
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/period.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/construction.py
  pandas/core/internals/managers.py
  pandas/core/internals/ops.py
  pandas/core/nanops.py
  pandas/core/reshape/merge.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/core/util/hashing.py
  pandas/core/window/rolling.py
  pandas/io/formats/format.py
  pandas/io/parsers/base_parser.py
  pandas/io/pytables.py
  pandas/tests/extension/decimal/array.py
Labels: Typing

#40369 INT: Use Index._getitem_slice in ArrayManager
  pandas/core/internals/array_manager.py
Labels: Internals

#40392 CI/TYP: Window typing followup
  pandas/core/generic.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Typing, Window

#40269 Add examples to documentation for DataFrame.swaplevel
  pandas/core/frame.py
Labels: Docs

#40298 [ArrayManager] TST: enable IO tests
  .github/workflows/ci.yml
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/pytables/test_compat.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_keys.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_pytables_missing.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_retain_attributes.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/pytables/test_subclass.py
  pandas/tests/io/pytables/test_time_series.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_stata.py
  pandas/tests/io/test_user_agent.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Internals, Testing

#40391 PERF: avoid double-verify of take indices
  pandas/core/indexers.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
Labels: Clean, Internals, Performance

#40323 [ArrayManager] TST: run (+fix/skip) pandas/tests/frame/indexing tests
  .github/workflows/ci.yml
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_insert.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_xs.py
Labels: Indexing, Internals

#40326 [ArrayManager] TST: run (+fix/skip) pandas/tests/series/indexing tests
  .github/workflows/ci.yml
  pandas/core/internals/array_manager.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/indexing/test_where.py
Labels: Indexing, Internals
