Repository pandas-dev/pandas, pull requests merged in 2021-08, with the labels that each got.

#42832 CI: Unpin jedi
  ci/deps/actions-38-locale.yaml
Labels: CI, Dependencies

#42850 Backport PR #42787: BUG: 1D slices over extension types turn into N-dimensional slices over ExtensionArrays
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/getitem.py
Labels: ExtensionArray, Indexing

#42842 CI: Upgrade codecov-action to v2
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
Labels: CI

#42860 Backport PR #42842 on branch 1.3.x (CI: Upgrade codecov-action to v2)
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
Labels: CI

#41203 TYP: Fix typing in ExtensionDtype registry
  pandas/core/dtypes/base.py
  pandas/core/dtypes/common.py
Labels: ExtensionArray, Typing

#42839 BUG: `styler.hide_columns` now hides the index name header row
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#42867 Backport PR #42839 on branch 1.3.x (BUG: `styler.hide_columns` now hides the index name header row)
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#42304 DEPS: update setuptools min version
  .pre-commit-config.yaml
  doc/source/development/contributing_environment.rst
  pyproject.toml
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
Labels: Dependencies

#42861 REGR: `styler.highlight_min/max` did not ignore `pd.NA` and caused error
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_highlight.py
Labels: Missing-data, Styler

#42873 TST: Replace deprecated pyarrow.parquet.ParquetDataset
  pandas/compat/pyarrow.py
  pandas/tests/io/test_parquet.py
Labels: Clean, Testing

#42650 BUG: EWM silently failed float32
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_select_dtypes.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_rolling.py
Labels: Bug, Dtypes, Window

#42877 TST: update message in skip_array_manager mark
  pandas/util/_test_decorators.py
Labels: Clean, Testing

#42882 TST: remove chained assignment outside indexing tests
  pandas/tests/frame/methods/test_dropna.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_isin.py
Labels: Clean, Testing

#42508 read_excel() modifies provided types dict when accessing file with duplicate column
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: Bug, IO Excel

#42647 BUG: ArrayManager reindex with copy=True not copying
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/tests/frame/methods/test_reindex.py
Labels: ArrayManager, Bug

#42843 REGR: sample modifying `weights` inplace
  pandas/core/sample.py
  pandas/tests/frame/methods/test_sample.py
Labels: Algos, Regression

#42885 PERF: Groupby.shift dont re-call libgroupby.group_shift_indexer
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Performance

#42669 ENH: Add BytesIOWrapper
  pandas/io/common.py
  pandas/tests/io/test_common.py
Labels: Enhancement, IO Data, Refactor

#42826 BUG: column names with degree sign make query fail
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/computation/parsing.py
  pandas/tests/computation/test_eval.py
Labels: Bug, expressions

#42874 DOC: add cookbook link about hidden sheets
  doc/source/user_guide/cookbook.rst
Labels: Docs, IO Excel

#42857 DEPR: unused kind arg in Index methods
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/tests/indexes/base_class/test_indexing.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/numeric/test_indexing.py
Labels: Deprecate, Index

#42855 REF: date arg not reachable in DTI._maybe_cast_slice_bound
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_indexing.py
Labels: Refactor

#42893 Backport PR #42508 on branch 1.3.x (read_excel() modifies provided types dict when accessing file with duplicate column)
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: Bug, IO Excel

#42831 TST: raising ValueError when inserting one dataframe in another
  pandas/tests/frame/indexing/test_insert.py
Labels: Indexing, Testing

#42903 Backport PR #42720 on branch 1.3.x (CLN: clean the conda-to-pip script)
  scripts/generate_pip_deps_from_conda.py
Labels: Clean

#42871 BUG: GH42866 DatetimeIndex de-serializing fails in PYTHONOPTIMIZE mode
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/test_downstream.py
Labels: Bug, Timeseries

#35498 BUG: Index.get_indexer_non_unique misbehaves with multiple nan
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/index.pyx
  pandas/core/indexes/base.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/test_indexing.py
Labels: Indexing, Missing-data

#42780 BUG: enable test_numpy tests with ArrayManager
  pandas/core/indexing.py
  pandas/core/internals/array_manager.py
  pandas/tests/extension/test_numpy.py
Labels: ArrayManager, Bug

#42775 fixes docstring in `to_hdf()`
  pandas/core/generic.py
Labels: Docs, IO HDF5

#42636 ENH: add kw `levels` to `Styler.hide_index` to hide only specific levels
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: Enhancement, Styler

#42884 BUG: dataframe.rolling along rows drops float16
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_rolling.py
Labels: Dtypes, Window

#42894 TST: add read_json test with date values GH33787
  pandas/tests/io/json/test_readlines.py
Labels: IO JSON, Testing

#42830 REF: remove unnecessary return value from ensure_data
  pandas/core/algorithms.py
Labels: Refactor

#42904 Backport PR #42871 on branch 1.3.x (BUG: GH42866 DatetimeIndex de-serializing fails in PYTHONOPTIMIZE mode)
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/test_downstream.py
Labels: Bug, Timeseries

#42901 Backport PR #42304: DEPS: update setuptools min version
  .pre-commit-config.yaml
  doc/source/development/contributing_environment.rst
  pyproject.toml
  requirements-dev.txt
  scripts/generate_pip_deps_from_conda.py
Labels: Dependencies

#42897 REF: share maybe_cast_slice_bound DTI/TDI/PI
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
Labels: Refactor

#41153 ENH: NumericIndex for any numpy int/uint/float dtype
  pandas/_libs/join.pyx
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/core/api.py
  pandas/core/dtypes/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/range.py
  pandas/tests/base/test_unique.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numpy_compat.py
Labels: Enhancement, Dtypes, Index, Constructors

#42596 BUG: SeriesGroupBy.nlargest/smallest inconsistent shape
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_function.py
Labels: Bug, Groupby

#42910 cln: remove printing statements
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#42909 TST: reorganize misplaced month / business month tests (#27085)
  pandas/tests/tseries/offsets/test_business_month.py
  pandas/tests/tseries/offsets/test_month.py
  pandas/tests/tseries/offsets/test_yqm_offsets.py
Labels: Testing, Frequency

#42764 DOC: fix a few URLs
  doc/source/getting_started/overview.rst
Labels: Docs

#42809 DOC: Fixed GL02 errors in documentation
  pandas/core/groupby/generic.py
Labels: Docs

#42619 DOC: update redirecting URLs
  doc/source/getting_started/install.rst
Labels: Docs

#41879 REF: avoid mutating Series._values directly in setitem but defer to Manager method
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/core/internals/managers.py
  pandas/core/series.py
Labels: Refactor, Indexing

#42923 STYLE: moving unwanted pattern check to precommit
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  ci/code_checks.sh
Labels: Code Style

#42799 BUG: `Styler.set_sticky` fix the names rows 2/2
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_html.py
Labels: Styler

#42776 BUG: Incorrect variable window bounds for first row when offset cover all rows
  doc/source/whatsnew/v1.3.2.rst
  pandas/_libs/window/indexers.pyx
  pandas/tests/window/test_rolling.py
Labels: Window

#42929 Backport PR #42776 on branch 1.3.x (BUG: Incorrect variable window bounds for first row when offset cover all rows)
  doc/source/whatsnew/v1.3.2.rst
  pandas/_libs/window/indexers.pyx
  pandas/tests/window/test_rolling.py
Labels: Window

#42928 Backport PR #42799 on branch 1.3.x (BUG: `Styler.set_sticky` fix the names rows 2/2)
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_html.py
Labels: Styler

#42797 BUG: concat with ArrayManager not making copy
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_dataframe.py
Labels: Bug, ArrayManager

#42930 TST: reorganize misplaced year / business year tests (#27085)
  pandas/tests/tseries/offsets/test_business_year.py
  pandas/tests/tseries/offsets/test_year.py
  pandas/tests/tseries/offsets/test_yqm_offsets.py
Labels: Testing, Frequency

#42835 TST: clean old sql tests
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#42919 COMPAT: Support fastparquet 0.7.1
  ci/deps/actions-38-db.yaml
  ci/deps/azure-windows-38.yaml
  doc/source/whatsnew/v1.3.2.rst
  environment.yml
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
  requirements-dev.txt
Labels: Compat, IO Parquet

#42568 DEPR: Index.reindex with duplicate index
  doc/source/user_guide/duplicates.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/indexes/categorical/test_reindex.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/resample/test_datetime_index.py
Labels: Deprecate, Index

#42932 TST: reorganize misplaced quarter / business quarter tests (#27085)
  pandas/tests/tseries/offsets/test_business_quarter.py
  pandas/tests/tseries/offsets/test_quarter.py
  pandas/tests/tseries/offsets/test_yqm_offsets.py
Labels: Testing, Frequency

#42329 BUG: .loc with MultiIndex with tuple in level GH#27591
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing, MultiIndex

#42142 STYLE fixup cython linting
  .pre-commit-config.yaml
  flake8/cython.cfg
  pandas/_libs/algos.pyx
  pandas/_libs/khash.pxd
  pandas/_libs/lib.pyx
  pandas/_libs/parsers.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Code Style

#42870 DEPR: Index inferring numeric dtype from ndarray[object]
  pandas/_testing/__init__.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/dtypes.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/strings/accessor.py
  pandas/core/tools/datetimes.py
  pandas/core/util/hashing.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_function.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/ranges/test_constructors.py
  pandas/tests/io/test_stata.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/series/methods/test_equals.py
  pandas/tests/series/test_logical_ops.py
Labels: Deprecate, Index

#42914 ENH: add kw `level` to `Styler.hide_columns`
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: Enhancement, Styler

#42942 ERR: clarify PerformanceWarning for fragmented frame
  pandas/core/internals/managers.py
Labels: Indexing, DataFrame, Warnings

#42958 Backport PR #42942 on branch 1.3.x (ERR: clarify PerformanceWarning for fragmented frame)
  pandas/core/internals/managers.py
Labels: Indexing, DataFrame, Warnings

#42186 STYLE: moving spacing conventions in cython casting to pre-commit
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  ci/code_checks.sh
  doc/source/development/contributing_codebase.rst
Labels: Code Style, Stale

#42969 Backport PR #42962 on branch 1.3.x (CI: Pin dateutil)
  ci/deps/actions-38-numpydev.yaml
Labels: CI

#42959 TST: use fixtures for sql test data
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#42834 DEPR: dropping nuisance columns in rolling aggregations
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_api.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_numba.py
Labels: Window, Nuisance Columns

#42952 TST: move index tests to correct files (#27045)
  pandas/tests/tseries/offsets/test_business_month.py
  pandas/tests/tseries/offsets/test_index.py
Labels: Testing, Frequency

#42949 Fix cross-references in docs
  doc/source/development/extending.rst
  doc/source/user_guide/sparse.rst
Labels: Docs

#42936 BUG:Can't calculate quantiles from Int64Dtype Series when results are floats
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/array_algos/quantile.py
  pandas/tests/series/methods/test_quantile.py
Labels: Algos, ExtensionArray

#42954 Revert fastparquet nullable dtype support
  doc/source/whatsnew/v1.3.2.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: IO Parquet

#42938 BUG: df.drop not separating missing labels with commas
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/tests/frame/methods/test_drop.py
Labels: Indexing, Error Reporting

#42974 Backport PR #42936 on branch 1.3.x (BUG:Can't calculate quantiles from Int64Dtype Series when results are floats)
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/array_algos/quantile.py
  pandas/tests/series/methods/test_quantile.py
Labels: Algos, ExtensionArray

#42838 REGR: Series.nlargest with masked arrays
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_nlargest.py
Labels: Regression, NA - MaskedArrays

#42963 PERF: avoid repeating checks in interpolation
  pandas/core/missing.py
Labels: Performance

#42953 REF: format_object_attrs -> Index._format_attrs
  pandas/core/indexes/base.py
  pandas/io/formats/printing.py
Labels: Refactor, Output-Formatting, Index

#42955 CLN: remove unused Series._index attribute
  pandas/core/generic.py
  pandas/core/series.py
Labels: Clean

#42975 Backport PR #42838 on branch 1.3.x (REGR: Series.nlargest with masked arrays)
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_nlargest.py
Labels: Regression, NA - MaskedArrays

#42823 BUG: Pass copy argument to expanddim constructor in concat.
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/reshape/concat.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/frame/methods/test_astype.py
Labels: ExtensionArray, Copy / view semantics

#42956 BENCH: Fix misleading Interpolate asv
  asv_bench/benchmarks/frame_methods.py
Labels: Benchmark

#42984 Backport PR #42823 on branch 1.3.x (BUG: Pass copy argument to expanddim constructor in concat.)
  doc/source/whatsnew/v1.3.2.rst
  pandas/core/reshape/concat.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/frame/methods/test_astype.py
Labels: ExtensionArray, Copy / view semantics

#42983 DOC/CLN: 1.3.2 release notes
  doc/source/whatsnew/v1.3.2.rst
Labels: Docs, Clean

#42985 Backport PR #42983: DOC/CLN: 1.3.2 release notes
  doc/source/whatsnew/v1.3.2.rst
Labels: Docs, Clean

#41893 ENH: `Styler.apply_index` and `Styler.applymap_index` for conditional formatting of column/index headers
  doc/source/_static/style/appmaphead1.png
  doc/source/_static/style/appmaphead2.png
  doc/source/reference/style.rst
  doc/source/user_guide/style.ipynb
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/formats/templates/html_style.tpl
  pandas/io/formats/templates/html_table.tpl
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_style.py
Labels: Enhancement, Styler

#42991 TST: test_offsets files to better homes & parameterize (#27085)
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_week.py
Labels: Testing, Frequency

#42989 TST: move orphaned business hour tests biz hour file (#27085)
  pandas/tests/tseries/offsets/test_business_hour.py
  pandas/tests/tseries/offsets/test_opening_times.py
Labels: Testing, Frequency

#42990 TST: move easter to own file and parameterize (#27085)
  pandas/tests/tseries/offsets/test_easter.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Testing, Frequency

#42987 Backport fastparquet 0.7 compat (PR #42954 and #42919)
  ci/deps/actions-37-db.yaml
  ci/deps/azure-windows-38.yaml
  environment.yml
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
  requirements-dev.txt
Labels: Compat, IO Parquet

#42992 REF: remove libreduction.apply_frame_axis0
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/reduction.pyx
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_apply.py
Labels: Groupby, Clean

#43005 CI: Run python dev with numpy python 3.10 wheels
  .github/workflows/python-dev.yml
Labels: CI, Python 3.10

#43007 Backport PR #43005 on branch 1.3.x (CI: Run python dev with numpy python 3.10 wheels)
  .github/workflows/python-dev.yml
Labels: CI, Python 3.10

#42988 TST: refactor iris table creation in SQL test
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#43010 PERF: Series.mad
  pandas/core/internals/managers.py
Labels: Performance

#43009 POC: use github issue form for usage questions
  .github/ISSUE_TEMPLATE/submit_question.md
  .github/ISSUE_TEMPLATE/submit_question.yml
Labels: Enhancement

#42706 DOC: NumericIndex
  doc/source/reference/indexing.rst
  doc/source/user_guide/advanced.rst
  doc/source/user_guide/categorical.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v0.16.1.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/__init__.py
  pandas/_testing/__init__.py
  pandas/core/indexes/category.py
  pandas/tests/api/test_api.py
  pandas/tests/base/test_unique.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numpy_compat.py
Labels: Docs, Index, Constructors

#43024 TST: refactor iris_view table creation in SQL test
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#43021 PERF: internals.concat
  pandas/_libs/internals.pyi
  pandas/_libs/internals.pyx
  pandas/core/internals/concat.py
Labels: Performance, Reshaping

#42999 TST: Fix test related to reverting fastparquet nullable support
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Testing, IO Parquet

#43027 Backport PR #42999 on branch 1.3.x (TST: Fix test related to reverting fastparquet nullable support)
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Testing, IO Parquet

#42828 BUG: Exactly same check multiple times in if statement
  pandas/core/indexes/multi.py
Labels: Indexing, Clean

#43030 DOC: Clarify dtype of returned object from window ops
  pandas/core/window/doc.py
Labels: Docs, Window

#43049 Backport PR #43045 on branch 1.3.x (1.3.2 release date)
  doc/source/whatsnew/v1.3.2.rst
Labels: Docs

#43046 DOC: Start v1.3.3 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.3.2.rst
  doc/source/whatsnew/v1.3.3.rst
Labels: Docs

#43051 DOC: Typo fix in "Extending Pandas"
  doc/source/development/extending.rst
Labels: Docs

#43055 Backport PR #43046 on branch 1.3.x (DOC: Start v1.3.3 release notes)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.3.2.rst
  doc/source/whatsnew/v1.3.3.rst
Labels: Docs

#43052 REGR: window ewm slowdown
  doc/source/whatsnew/v1.3.3.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/ewm.py
Labels: Performance, Regression, Window

#43033 DOC: arguments options correction
  pandas/io/formats/style.py
Labels: Styler

#43043 BUG: JoinUnit._is_valid_na_for
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_append.py
Labels: Bug, Reshaping

#42940 TST: GH34037 add test for type error when using parameter 'min_period'
  pandas/tests/groupby/test_groupby.py
Labels: Testing, Window

#43041 Fix len one list dataframe constructor bug for datetime
  doc/source/whatsnew/v1.3.3.rst
  pandas/core/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Regression, DataFrame, Constructors

#43070 Backport PR #43033 on branch 1.3.x (DOC: arguments options correction)
  pandas/io/formats/style.py
Labels: Styler

#43069 Backport PR #43052 on branch 1.3.x (REGR: window ewm slowdown)
  doc/source/whatsnew/v1.3.3.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/ewm.py
Labels: Performance, Regression, Window

#43077 Backport PR #43041 on branch 1.3.x (Fix len one list dataframe constructor bug for datetime)
  doc/source/whatsnew/v1.3.3.rst
  pandas/core/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Regression, DataFrame, Constructors

#43078 REF: `axis in [...]` becomes `_get_axis_number(axis)` in Styler
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_style.py
Labels: Clean, Styler

#43073 PERF: is_string_dtype checks
  pandas/core/dtypes/common.py
  pandas/core/dtypes/missing.py
Labels: Performance, Dtype Conversions

#42140 DEPR: `Styler.render` in favour of `Styler.to_html`
  asv_bench/benchmarks/io/style.py
  doc/source/reference/style.rst
  doc/source/user_guide/style.ipynb
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_deprecated.py
  pandas/tests/io/formats/style/test_format.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_non_unique.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/io/formats/style/test_tooltip.py
Labels: IO HTML, Deprecate, Styler

#43063 BENCH: fix misleading json asvs
  asv_bench/benchmarks/io/json.py
Labels: Benchmark

#43066 TST: df.combine_first duplicates rows for nan index values (#39881)
  pandas/tests/frame/methods/test_combine_first.py
Labels: Testing, Indexing, Missing-data, MultiIndex

#43071 BENCH: Add pyarrow to env
  asv_bench/asv.conf.json
Labels: Benchmark

#43040 TST: refactor types table in SQL test
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#42979 DOC: updates documentations Closes #21749
  pandas/_testing/_io.py
  pandas/_testing/asserters.py
  pandas/core/dtypes/base.py
  pandas/io/formats/latex.py
  pandas/tseries/holiday.py
Labels: Docs

#43037 REF: address the floating "_" in `styler.uuid`
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style_render.py
  pandas/io/formats/templates/html_style.tpl
  pandas/io/formats/templates/html_table.tpl
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/io/formats/style/test_tooltip.py
Labels: Styler

#43054 REGR: SeriesGrouper using Timestamp index
  doc/source/whatsnew/v1.3.3.rst
  pandas/core/indexes/datetimelike.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Timeseries, Groupby, Regression

#43064 BUG: Allow named aggregation with Resampler.agg
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_resample_api.py
Labels: Bug, Groupby, Apply

#43004 DOC: Update param doc of to_parquet about compression
  pandas/io/parquet.py
Labels: Docs, IO Parquet

#43061 DOC: Updating grammar for clarity and consistency
  doc/source/user_guide/10min.rst
Labels: Docs

#43081 Backport PR #43054 on branch 1.3.x (REGR: SeriesGrouper using Timestamp index)
  doc/source/whatsnew/v1.3.3.rst
  pandas/core/indexes/datetimelike.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Timeseries, Groupby, Regression

#43059 PERF: read_stata
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/stata.py
Labels: Performance, IO Stata

#43029 DOC: Ensure pandas warnings & exceptions are always documented in API docs
  .pre-commit-config.yaml
  doc/source/reference/general_utility_functions.rst
  pandas/errors/__init__.py
  scripts/pandas_errors_documented.py
Labels: Docs

#43047 TST: cleanup of any_* test fixtures GH38017
  asv_bench/benchmarks/dtypes.py
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/integer/test_comparison.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/arrays/masked/test_arithmetic.py
  pandas/tests/arrays/masked/test_arrow_compat.py
  pandas/tests/arrays/masked/test_function.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/test_array.py
  pandas/tests/dtypes/cast/test_downcast.py
  pandas/tests/dtypes/cast/test_infer_dtype.py
  pandas/tests/dtypes/cast/test_promote.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_groupby_shift_diff.py
  pandas/tests/groupby/test_libgroupby.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/formats/test_to_string.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/test_qcut.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/indexing/test_where.py
  pandas/tests/series/methods/test_clip.py
  pandas/tests/series/methods/test_nlargest.py
  pandas/tests/series/methods/test_replace.py
  pandas/tests/series/methods/test_round.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_unary.py
  pandas/tests/test_algos.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_rolling.py
Labels: Testing

#43097 DOC: `styler.format` does not, in fact, raise a KeyError
  pandas/io/formats/style_render.py
Labels: Docs, Styler

#43100 Backport PR #43097 on branch 1.3.x (DOC: `styler.format` does not, in fact, raise a KeyError)
  pandas/io/formats/style_render.py
Labels: Docs, Styler

#43013 Replace str::replace hack for getting module name from ImportError in __init__.py
  pandas/__init__.py
Labels: Refactor, Build

#43025 PERF: unstack
  pandas/_libs/internals.pyi
  pandas/_libs/internals.pyx
  pandas/core/internals/managers.py
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Performance, Reshaping

#43044 BUG: also copy `uuid` in `Styler.copy`
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#43083 TST: refactor count rows in sql test
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#43065 REF: Move BaseIndexers and indexer.py functions into their own directory
  pandas/api/indexers/__init__.py
  pandas/core/generic.py
  pandas/core/indexers/__init__.py
  pandas/core/indexers/objects.py
  pandas/core/indexers/utils.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_base_indexer.py
Labels: Refactor

#43103 PERF: stronger typing in libgroupby
  pandas/_libs/groupby.pyx
  pandas/core/groupby/groupby.py
Labels: Groupby, Typing

#43099 REF: ensure to_arrays returns matched-length arrays/columns
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Performance

#43104 REF: reorder_arrays handle missing
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Refactor, Internals

#43098 TST: resolve most of future warnnings in SQL test, clean import
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#43003 DOC: Fixed all remaining GL02 documentation errors and added appropriate check in CI
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#43026 Bug in Series constructor returning wrong missing values
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/test_constructors.py
Labels: Missing-data, Series, Constructors

#43107 TYP: Replace namedtuple with dataclass #40531
  pandas/core/groupby/base.py
Labels: Clean

#42865 Add warning about NA merges
  doc/source/getting_started/comparison/comparison_with_sql.rst
  pandas/core/frame.py
Labels: Docs, Reshaping

#42841 PERF: GroupBy.any/all operate blockwise instead of column-wise
  asv_bench/benchmarks/groupby.py
  pandas/_libs/groupby.pyx
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Groupby, Performance, Algos

#43034 BUG: don't manipulate `styler` object due to args in `to_html`
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#42937 CLN: clean warning assertions in sql tests
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#43111 DOC: `Styler` whats new section refactor 1.4.0
  doc/source/whatsnew/v1.4.0.rst
Labels: Styler

#43110 REF: arrays_to_manager dont need names
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Refactor, Internals

#42998 PERF: DataFrame.insert
  asv_bench/benchmarks/indexing.py
  pandas/_libs/internals.pyi
  pandas/_libs/internals.pyx
  pandas/core/internals/managers.py
Labels: Performance, Reshaping

#42014 BUG: `Styler.apply` consistently manages Series return objects aligning labels.
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Bug, Apply, Styler
