Repository pandas-dev/pandas, pull requests merged in 2021-07, with the labels that each got.

#42334 PERF/REGR: restore IntervalIndex._intersection_non_unique
  pandas/core/indexes/interval.py
Labels: Index, Interval, Performance, setops

#42313 DOC: v1.3.0 release date
  doc/source/whatsnew/v1.3.0.rst
Labels: Docs

#42336 Backport PR #42334 on branch 1.3.x (PERF/REGR: restore IntervalIndex._intersection_non_unique)
  pandas/core/indexes/interval.py
Labels: Index, Interval, Performance, setops

#42337 Backport PR #42313 on branch 1.3.x (DOC: v1.3.0 release date)
  doc/source/whatsnew/v1.3.0.rst
Labels: Docs

#42231 PERF: tighten _should_compare for MultiIndex
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_indexing.py
Labels: MultiIndex, Performance

#42310 BUG: don't silently ignore kwargs in get_indexer_for
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
Labels: Bug, Indexing

#42315 REF: remove drop_level kwarg from MultiIndex._get_loc_level
  pandas/core/generic.py
  pandas/core/indexes/multi.py
Labels: Indexing, MultiIndex, Refactor

#42308 REF: move casting from Index._get_indexer to Index.get_indexer
  pandas/core/indexes/base.py
  pandas/core/indexes/range.py
Labels: Indexing, Refactor

#42227 REF: implement Index._should_partial_index
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
Labels: Index, Indexing, Interval

#42258 REF: simplify __can_partial_date_slice, _parsed_string_to_bounds
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
Labels: Indexing, Refactor

#42269 DEPR: Index.get_loc with method
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/numeric/test_indexing.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/test_downstream.py
Labels: Deprecate, Indexing

#42265 BUG: Series.loc[dtstr] type depends on monotonicity
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
Labels: Bug, Indexing

#42263 CLN: simplify take2d_axis0 generated code
  pandas/_libs/algos_take_helper.pxi.in
Labels: Algos, Clean

#42260 CLN: allow label memviews to be None
  pandas/_libs/algos.pyi
  pandas/_libs/algos.pyx
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Algos, Clean

#42278 TST: Added test for upcasting to object when concatinating on categorical indexes with non-identical categories
  pandas/tests/reshape/concat/test_categorical.py
Labels: Categorical, Reshaping, Testing

#42267 TST IntegerArray bounds error closing GH21796
  pandas/tests/arrays/test_array.py
Labels: Constructors, Dtypes, Testing

#42271 CLN: simplify Styler clear mechanics and tests
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Clean, Refactor, Styler

#42233 PERF/REF: groupby sample
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/sample.py
  pandas/tests/frame/methods/test_sample.py
  pandas/tests/groupby/test_sample.py
Labels: Groupby, Performance, Refactor

#42330 BENCH: update imports to allow testing against 1.2.5
  asv_bench/benchmarks/algos/isin.py
Labels: Benchmark

#41698 BUG: Ignore chartsheets
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/excel/_base.py
  pandas/io/excel/_openpyxl.py
  pandas/tests/io/data/excel/chartsheet.xls
  pandas/tests/io/data/excel/chartsheet.xlsb
  pandas/tests/io/data/excel/chartsheet.xlsm
  pandas/tests/io/data/excel/chartsheet.xlsx
  pandas/tests/io/excel/test_readers.py
Labels: Bug, IO Excel

#42312 DOC: Start v1.3.1 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.3.0.rst
  doc/source/whatsnew/v1.3.1.rst
Labels: Docs

#42348 Backport PR #42312 on branch 1.3.x (DOC: Start v1.3.1 release notes)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.3.0.rst
  doc/source/whatsnew/v1.3.1.rst
Labels: Docs

#42342 DOC: fix docs after deprecation of args
  pandas/core/series.py
Labels: Deprecate, Docs

#41955 CLN: Replace FrameOrSeriesUnion annotation by DataFrame | Series
  pandas/_typing.py
  pandas/core/algorithms.py
  pandas/core/apply.py
  pandas/core/describe.py
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/pivot.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/core/util/hashing.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/io/formats/info.py
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/json/_json.py
  pandas/io/pytables.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/plotting/_matplotlib/tools.py
Labels: Clean, Typing

#42363 Backport PR #42342 on branch 1.3.x (DOC: fix docs after deprecation of args)
  pandas/core/series.py
Labels: Deprecate, Docs

#42368 TYP: remove some ignores
  pandas/_testing/asserters.py
  pandas/core/algorithms.py
  pandas/core/apply.py
  pandas/core/base.py
  pandas/core/frame.py
Labels: Typing

#42350 BUG: Don't cache args during rolling/expanding.apply with numba engine
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/window/numba_.py
  pandas/core/window/rolling.py
  pandas/tests/window/conftest.py
  pandas/tests/window/test_numba.py
Labels: Bug, Window, numba

#42361 CLN: make some private Index methods keyword-only
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
Labels: Clean, Index

#42362 REF: handle length-0 setops cases higher up
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/range.py
Labels: Index, Refactor

#42261 BUG: Fix to_datetime() cache behaviour to not omit duplicated output values
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Bug, Timeseries

#42360 BUG: fixes PyPy build (do not use _PyHASH_Imag)
  doc/source/whatsnew/v1.3.1.rst
  pandas/_libs/src/klib/khash_python.h
Labels: Build

#42353 PERF: DatetimeIndex.union
  pandas/core/indexes/datetimelike.py
Labels: Index, Performance

#42326 REF: avoid try/except in maybe_mi_droplevel
  pandas/core/generic.py
  pandas/core/indexes/multi.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
Labels: Indexing, MultiIndex

#42319 BUG: not dropping scalar-indexes MultiIndex levels
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_getitem.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Bug, Indexing, MultiIndex

#42245 CLN: simplify MultiIndex.get_locs
  pandas/core/indexes/multi.py
  pandas/core/indexing.py
Labels: Clean, Indexing, MultiIndex

#42243 PERF/ENH: allow Generator in sampling methods
  doc/source/whatsnew/v1.4.0.rst
  pandas/_typing.py
  pandas/core/common.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/sample.py
  pandas/tests/frame/methods/test_sample.py
  pandas/tests/test_common.py
Labels: Enhancement, Performance

#42215 DEPR: Series.__setitem__ with Float64Index falling back to positional
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/series.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/test_arithmetic.py
Labels: Deprecate, Indexing

#41989 DEPS: drop Python 3.7 and NumPy 1.17 from tests (#41678)
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/sdist.yml
  azure-pipelines.yml
  ci/azure/posix.yml
  ci/azure/windows.yml
  ci/deps/actions-37-locale_slow.yaml
  ci/deps/actions-37-minimum_versions.yaml
  ci/deps/actions-37.yaml
  ci/deps/actions-38-db-min.yaml
  ci/deps/actions-38-db.yaml
  ci/deps/actions-38-locale.yaml
  ci/deps/actions-38-locale_slow.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38-slow.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39-numpydev.yaml
  ci/deps/actions-39-slow.yaml
  ci/deps/actions-39.yaml
  ci/deps/azure-macos-38.yaml
  ci/deps/azure-windows-38.yaml
  ci/deps/azure-windows-39.yaml
  ci/deps/circle-38-arm64.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v1.4.0.rst
  environment.yml
  pandas/compat/_optional.py
  pandas/compat/numpy/__init__.py
  pyproject.toml
  requirements-dev.txt
  setup.cfg
Labels: Compat, Dependencies, Deprecate

#42373 Backport PR #42360 on branch 1.3.x (BUG: fixes PyPy build (do not use _PyHASH_Imag))
  doc/source/whatsnew/v1.3.1.rst
  pandas/_libs/src/klib/khash_python.h
Labels: Build

#42377 CI: Prefer conda-forge over defaults
  ci/deps/azure-windows-39.yaml
Labels: CI

#42375 CLN: remove np17 compat
  pandas/__init__.py
  pandas/compat/__init__.py
  pandas/compat/numpy/__init__.py
  pandas/core/common.py
  pandas/tests/api/test_api.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/frame/methods/test_sample.py
  pandas/tests/indexes/period/test_searchsorted.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/test_common.py
Labels: Clean

#42374 CLN: remove Python 3.8 compat
  pandas/compat/__init__.py
  pandas/tests/computation/test_eval.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: Clean

#42385 TYP: clean for PY3.8 (Literal)
  pandas/_typing.py
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/base.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/resample.py
  pandas/core/series.py
Labels: Clean, Typing

#42392 STYLE: update pyupgrade for py38 syntax
  .pre-commit-config.yaml
Labels: Code Style

#42411 CI: Don't test on 1.2.x
  .github/workflows/ci.yml
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  azure-pipelines.yml
Labels: CI

#42339 ENH: Add `method='table'` for EWM.mean
  asv_bench/benchmarks/rolling.py
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/core/window/ewm.py
  pandas/core/window/numba_.py
  pandas/tests/window/test_numba.py
Labels: Enhancement, Window

#42412 Backport PR #42411 on branch 1.3.x (CI: Don't test on 1.2.x)
  .github/workflows/ci.yml
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  azure-pipelines.yml
Labels: CI

#42410 DEPS: use importlib for backend discovery #41815
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/plotting/_core.py
Labels: Build

#42404 REF: Skip all empty groups in _transform_general
  pandas/core/groupby/generic.py
Labels: Groupby, Refactor

#42413 CI: runtime warning in npdev build
  pandas/tests/scalar/timedelta/test_arithmetic.py
Labels: CI, Testing

#42394 REGR: unpickling in 1.3.0 DataFrame created in 1.2.x #42345
  doc/source/whatsnew/v1.3.1.rst
  pandas/_libs/internals.pyx
  pandas/tests/io/data/legacy_pickle/1.2.4/empty_frame_v1_2_4-GH#42345.pkl
  pandas/tests/io/test_pickle.py
Labels: IO Data, Regression

#42407 CLN: random state updates after dropping numpy 1.17
  pandas/_typing.py
  pandas/core/common.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
Labels: Clean, Typing

#42415 Backport PR #42413 on branch 1.3.x (CI: runtime warning in npdev build)
  pandas/tests/scalar/timedelta/test_arithmetic.py
Labels: CI, Testing

#42416 Backport PR #42394 on branch 1.3.x (REGR: unpickling in 1.3.0 DataFrame created in 1.2.x #42345)
  doc/source/whatsnew/v1.3.1.rst
  pandas/_libs/internals.pyx
  pandas/tests/io/data/legacy_pickle/1.2.4/empty_frame_v1_2_4-GH#42345.pkl
  pandas/tests/io/test_pickle.py
Labels: IO Data, Regression

#41651 GH41457 Upgrade Bootstrap to v5.0
  web/pandas/_templates/layout.html
  web/pandas/contribute.md
  web/pandas/index.html
  web/pandas/static/css/pandas.css
Labels: Web

#42417 DOC: GH42409 Fix mistake in code example of Styler.to_latex documentation
  pandas/io/formats/style.py
Labels: Docs, IO LaTeX, Styler

#42418 Backport PR #42417 on branch 1.3.x (DOC: GH42409 Fix mistake in code example of Styler.to_latex documentation)
  pandas/io/formats/style.py
Labels: Docs, IO LaTeX, Styler

#42398 TYP: remove ignores from BlockManager.__cinit__
  pandas/_libs/internals.pyx
Labels: Typing

#42389 TYP: remove ignores in refine_percentiles
  pandas/core/describe.py
Labels: Typing

#42400 TYP: remove some ignores - nansum, _get_counts_nanvar
  pandas/core/frame.py
  pandas/core/nanops.py
Labels: Typing

#42378 REF: disambiguate get_loc_level k variable
  pandas/core/generic.py
  pandas/core/indexes/multi.py
Labels: MultiIndex, Refactor

#42419 CI: update vm image version for Azure
  azure-pipelines.yml
Labels: CI

#42432 Backport PR #42419 on branch 1.3.x (CI: update vm image version for Azure)
  azure-pipelines.yml
Labels: CI

#42288 DEPR: treating dt64 as UTC in Timestamp constructor
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: Deprecate, Timeseries

#42338 PERF/REGR: revert #41785
  doc/source/whatsnew/v1.3.1.rst
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
  pandas/tests/dtypes/cast/test_dict_compat.py
Labels: Constructors, Performance

#42435 BUG: .loc failing to drop first level
  pandas/core/indexes/multi.py
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/test_arithmetic.py
Labels: Indexing, MultiIndex

#42366 BUG: truncate has incorrect behavior when index has only one unique v…
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_truncate.py
  pandas/tests/series/methods/test_truncate.py
Labels: Bug, Indexing

#42436 CLN: clean doc validation script
  scripts/validate_docstrings.py
Labels: Clean

#42438 Fix Formatting Issue
  pandas/core/series.py
Labels: Docs

#42427 DOC: Add more instructions for updating the whatsnew
  doc/source/development/contributing_codebase.rst
Labels: Docs, Enhancement

#42386 DOC fix the incorrect doc style in 1.2.1
  doc/source/whatsnew/v1.0.0.rst
  doc/source/whatsnew/v1.2.1.rst
Labels: Docs

#42444 Backport PR #42338 on branch 1.3.x (PERF/REGR: revert #41785)
  doc/source/whatsnew/v1.3.1.rst
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
  pandas/tests/dtypes/cast/test_dict_compat.py
Labels: Constructors, Performance

#42445 Backport PR #42386 on branch 1.3.x (DOC fix the incorrect doc style in 1.2.1)
  doc/source/whatsnew/v1.0.0.rst
  doc/source/whatsnew/v1.2.1.rst
Labels: Docs

#42195 PERF: Try fast/slow paths only once in DataFrameGroupby.transform
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/groupby/generic.py
Labels: Apply, Groupby, Performance

#42449 REGR: DataFrame.agg with axis=1, EA dtype, and duplicate index
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/frame.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/base/test_transpose.py
Labels: Apply, Regression, Reshaping

#42301 ENH: `Styler.bar` extended to allow centering about the mean, value or callable
  doc/source/user_guide/style.ipynb
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_align.py
Labels: Enhancement, Styler

#42264 CLN: Group tests for apply/agg/transform with a string argument
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/apply/test_series_transform.py
  pandas/tests/apply/test_str.py
Labels: Clean, Groupby, Testing

#42325 WEB: Added theme dependent favicon
  web/pandas/_templates/layout.html
  web/pandas/static/img/favicon_white.ico
Labels: Web

#42451 CI: Sync all 3.9 builds
  ci/deps/actions-39-slow.yaml
  ci/deps/actions-39.yaml
Labels: CI

#42144 DOC: Substitute example in DataFrame.to_markdown docstring (#42126)
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs

#42181 TST: Add unmatched warning messages to assert_produces_warning() error
  pandas/_testing/_warnings.py
  pandas/tests/util/test_assert_produces_warning.py
Labels: Error Reporting, Testing

#42470 DOC: GH42420 Fix typo in windows C compiler install guide
  doc/source/development/contributing_environment.rst
Labels: Build, Docs

#42251 DOC: Clarify relation between DateOffset and relativedelta
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs, Frequency

#42244 Updated the return type section of to_datetime
  pandas/core/tools/datetimes.py
Labels: Docs, Timeseries

#42242 DOC: Add pandas-workshop community tutorial.
  doc/source/getting_started/tutorials.rst
Labels: Docs

#42173 PERF: Use list comprehension to join strings (#41753)
  asv_bench/benchmarks/io/csv.py
  doc/source/user_guide/io.rst
  pandas/_config/config.py
  pandas/core/computation/engines.py
  pandas/core/computation/parsing.py
  pandas/core/computation/pytables.py
  pandas/core/computation/scope.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/io/formats/excel.py
  pandas/io/formats/latex.py
  pandas/io/formats/style.py
  pandas/io/formats/xml.py
  pandas/io/html.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/python_parser.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_series.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/io/formats/style/test_align.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_multi_thread.py
  pandas/tests/io/parser/test_na_values.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/io/test_sql.py
  pandas/util/_decorators.py
  pandas/util/_print_versions.py
  pandas/util/version/__init__.py
  scripts/tests/test_validate_docstrings.py
Labels: Performance

#42285 to_timedelta docs warning on default behaviour
  doc/source/user_guide/timedeltas.rst
Labels: Docs

#42469 REGR: indexing with list subclass
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/common.py
  pandas/tests/test_common.py
Labels: Indexing, Regression

#42439 DOC: Refactor Numba enhancing performance and add parallelism caveat
  doc/source/user_guide/enhancingperf.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/window.rst
  pandas/core/window/doc.py
Labels: numba

#42489 Backport PR #42469 on branch 1.3.x (REGR: indexing with list subclass)
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/common.py
  pandas/tests/test_common.py
Labels: Indexing, Regression

#42490 Backport PR #42439 on branch 1.3.x (DOC: Refactor Numba enhancing performance and add parallelism caveat)
  doc/source/user_guide/enhancingperf.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/window.rst
  pandas/core/window/doc.py
Labels: numba

#42487 CI: add back xfail for flaky chunksize test
  pandas/tests/io/parser/common/test_chunksize.py
Labels: CI, IO CSV, Testing

#42472 CLN TST: Refactor `Styler.bar` tests through parametrisation
  pandas/tests/io/formats/style/test_align.py
Labels: Styler, Testing

#42063 BUG: avoid unnecessary casting in CategoricalIndex.reindex
  pandas/core/indexes/category.py
Labels: Categorical

#42486 REGR: to_dict(orient={"records", "split", "dict"}) slowdown
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/dtypes/cast.py
Labels: Dtypes, Performance, Regression

#42491 Backport PR #42487 on branch 1.3.x (CI: add back xfail for flaky chunksize test)
  pandas/tests/io/parser/common/test_chunksize.py
Labels: CI, IO CSV, Testing

#42500 TYP/CLN: update setup.cfg
  pandas/io/formats/string.py
  setup.cfg
Labels: Clean, Typing

#42496 CLN: renamed a test file
  pandas/tests/io/formats/style/test_bar.py
Labels: Styler, Testing

#42467 CI: Don't auto-cancel on master
  .github/workflows/ci.yml
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/pre-commit.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
Labels: CI

#42480 REF: implement MultiIndex._get_indexer_level_0
  pandas/core/indexes/multi.py
Labels: Indexing, MultiIndex, Refactor

#28373 ENH: Fix `by` in DataFrame.plot.hist and DataFrame.plot.box
  doc/source/whatsnew/v1.4.0.rst
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/groupby.py
  pandas/plotting/_matplotlib/hist.py
  pandas/tests/plotting/frame/test_hist_box_by.py
Labels: Visualization

#42498 TYP/CLN: implicit re-export
  pandas/core/describe.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/indexers.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/array_manager.py
  pandas/core/series.py
Labels: Clean, Typing

#42502 Backport PR #42486 on branch 1.3.x (REGR: to_dict(orient={"records", "split", "dict"}) slowdown)
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/dtypes/cast.py
Labels: Dtypes, Performance, Regression

#42504 TST CLN: Styler bar tests cleanup 2/3
  pandas/tests/io/formats/style/test_bar.py
Labels: Styler, Testing

#42402 DOC: Adding examples to DataFrameGroupBy.rank #38972
  pandas/core/groupby/groupby.py
Labels: Algos, Docs, Groupby

#42510 TST CLN: test_bar.py cleanup 3/3: NaN cases
  pandas/tests/io/formats/style/test_bar.py
Labels: Styler

#42464 BUG: `to_xml` with `index=False` and offset input index
  doc/source/whatsnew/v1.3.1.rst
  pandas/io/formats/xml.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Bug, IO XML

#42513 Backport PR #42464 on branch 1.3.x (BUG: `to_xml` with `index=False` and offset input index)
  doc/source/whatsnew/v1.3.1.rst
  pandas/io/formats/xml.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Bug, IO XML

#42515 Backport PR #42451: CI: Sync all 3.9 builds (part)
  ci/deps/actions-39.yaml
Labels: CI, Python 3.9

#42483 ENH: Styler.bar height control
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_bar.py
Labels: Styler

#42507 CLN: remove deprecated sqlite cursor
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Clean, IO SQL

#42516 DOC: fixes for 1.3.1 release notes
  doc/source/whatsnew/v1.3.1.rst
Labels: Docs

#42517 Backport PR #42516 on branch 1.3.x (DOC: fixes for 1.3.1 release notes)
  doc/source/whatsnew/v1.3.1.rst
Labels: Docs

#42290 DOC: Only include numpy.std note for std, not all ddof methods
  pandas/core/generic.py
Labels: Docs

#42235 BUG: OutOfBoundsTimedelta not raised for out-of-bounds Timedelta
  pandas/tests/scalar/timedelta/test_constructors.py
Labels: Testing, Timedelta

#42475 PERF/REGR: astype changing order of some 2d data
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_astype.py
Labels: Dtypes, Performance, Reduction Operations, Regression

#42524 CI: Xfail less on Python 3.10
  pandas/tests/indexes/test_base.py
  pandas/tests/reshape/test_get_dummies.py
  pandas/tests/test_algos.py
Labels: CI, Python 3.10, Testing

#42521 REF: de-duplicate WrappedCythonOp._ea_wrap_cython_operation
  pandas/core/groupby/ops.py
Labels: Groupby, Refactor

#42511 ENH: validate the argument `width` on `Styler.bar`
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_bar.py
Labels: Styler

#42527 CI: Test Python dev on 1.3.x PRs
  .github/workflows/python-dev.yml
Labels: CI, Python 3.10

#42488 TYP: npt.NDarray
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/range.py
  pandas/core/resample.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/reshape.py
  pandas/core/sorting.py
Labels: Typing

#42526 Backport PR #42475: PERF/REGR: astype changing order of some 2d data
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_astype.py
Labels: Dtypes, Performance, Reduction Operations, Regression

#42531 Backport PR #42527 on branch 1.3.x (CI: Test Python dev on 1.3.x PRs)
  .github/workflows/python-dev.yml
Labels: CI, Python 3.10

#42525 Backport PR #42524 on branch 1.3.x (CI: Xfail less on Python 3.10)
  pandas/tests/indexes/test_base.py
  pandas/tests/reshape/test_get_dummies.py
  pandas/tests/test_algos.py
Labels: CI, Python 3.10, Testing

#42473 REGR: isin with nullable types with missing values raising
  asv_bench/benchmarks/algos/isin.py
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/arrays/masked.py
  pandas/tests/series/methods/test_isin.py
Labels: NA - MaskedArrays, Regression, isin

#42529 DOC: add height param added to user_guide
  doc/source/user_guide/style.ipynb
Labels: Docs, Styler

#42539 Revert "CI: runtime warning in npdev build"
  pandas/tests/scalar/timedelta/test_arithmetic.py
Labels: CI

#42538 CI: Run some checks on push on 1.3.x
  .github/workflows/posix.yml
  .github/workflows/pre-commit.yml
  .github/workflows/sdist.yml
Labels: CI

#42351 DEPR: ignoring missing labels when indexing on MultiIndex level
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/io/formats/style/test_style.py
Labels: Deprecate, MultiIndex

#42528 TST: Test reindex w/ multiindex df (GH21247)
  pandas/tests/indexes/multi/test_reindex.py
Labels: Testing

#42422 TYP: clean for PY3.8 (final)
  pandas/_libs/internals.pyi
  pandas/_libs/internals.pyx
  pandas/_typing.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/internals/base.py
  pandas/core/internals/blocks.py
  pandas/core/resample.py
  pandas/io/parsers/base_parser.py
Labels: Typing

#41985 DOC: update array-like parameters if scalars accepted
  pandas/core/algorithms.py
  pandas/core/arrays/base.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/core/dtypes/common.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
Labels: Docs

#42543 Backport PR #42473: REGR: isin with nullable types with missing values raising
  asv_bench/benchmarks/algos/isin.py
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/arrays/masked.py
  pandas/tests/series/methods/test_isin.py
Labels: NA - MaskedArrays, Regression, isin

#42541 REGR: concat(ints, bools) casting to object #42092
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_dataframe.py
Labels: Dtypes, Regression, Reshaping

#42476 BUG: string slicing on MultiIndex DatetimeIndex level
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/indexing.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/multi/test_partial_indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Bug, Indexing, MultiIndex

#42519 BUG: Fix multi-index colname references in read_csv c engine.
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/parser/test_converters.py
  pandas/tests/io/parser/test_na_values.py
Labels: Bug, IO CSV, MultiIndex

#42179 BUG: json_normalize not consistently ignoring errors (#41876)
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/json/_normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: Bug, IO JSON

#39272 BUG: 2D ndarray of dtype 'object' is always copied upon construction
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Internals, Reshaping

#42335 BUG: Series.loc with MultiIndex whose first level is all-NaN
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing, MultiIndex

#42548 Backport PR #42541 on branch 1.3.x (REGR: concat(ints, bools) casting to object #42092)
  doc/source/whatsnew/v1.3.1.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_dataframe.py
Labels: Dtypes, Regression, Reshaping

#42340 DOC: Unsuppress relevant dataframe in split-apply-combine guide
  doc/source/user_guide/groupby.rst
Labels: Docs, Groupby

#42551 Backport PR #42538: CI: Run some checks on push on 1.3.x
  .github/workflows/posix.yml
  .github/workflows/pre-commit.yml
  .github/workflows/sdist.yml
Labels: CI

#42485 REF: implement Index._get_indexer_strict
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/indexing.py
Labels: Indexing, MultiIndex

#41919 REF: de-duplicate Categorical _validate_foo_value
  doc/source/user_guide/categorical.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/arrays/categorical/test_take.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/indexes/categorical/test_fillna.py
  pandas/tests/indexes/categorical/test_indexing.py
  pandas/tests/indexes/categorical/test_reindex.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/series/methods/test_shift.py
Labels: Categorical, Error Reporting, Refactor

#42465 BUG: MultiIndex.get_loc with string key on DatetimeIndex level
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_partial_indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Bug, Indexing, MultiIndex

#42556 CI: Run all GHA checks on backport branch
  .github/workflows/ci.yml
Labels: CI

#42561 Backport PR #42556: CI: Run all GHA checks on backport branch
  .github/workflows/ci.yml
Labels: CI

#42558 CI: Remove xfail for xpassing test
  pandas/tests/scalar/timedelta/test_arithmetic.py
Labels: CI

#42554 Modified ecosystem.rst to include ibis
  doc/source/ecosystem.rst
Labels: Docs

#42564 Backport PR #42554 on branch 1.3.x (Modified ecosystem.rst to include ibis)
  doc/source/ecosystem.rst
Labels: Docs
