Repository pandas-dev/pandas, pull requests merged in 2021-12, with the labels that each got.

#44674 BUG: Series.__rfloordiv__ with list/tuple
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/ops/array_ops.py
  pandas/core/ops/missing.py
  pandas/tests/series/test_arithmetic.py
Labels: Bug, Algos

#44695 PERF: assert_frame_equal
  pandas/_testing/asserters.py
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Performance

#44369 TST: check compatibility with pyarrow types_mapper parameter
  pandas/tests/arrays/masked/test_arrow_compat.py
Labels: Testing, Arrow

#37320 ENH: enable Series.info()
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/io/formats/info.py
  pandas/tests/io/formats/test_series_info.py
  pandas/tests/series/test_api.py
Labels: Output-Formatting

#44653 BUG: using .replace() on a Series containing np.nan raising ValueError when using regex=True.
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/array_algos/replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Bug, Strings

#44678 Type read_fwf
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
Labels: Typing, IO Fixed Width

#44682 CI: Try to not auto-cancel on master
  .github/workflows/ci.yml
  .github/workflows/database.yml
  .github/workflows/posix.yml
  .github/workflows/pre-commit.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
Labels: CI

#44685 TST: fix Nullable xfails
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/boolean.py
  pandas/core/arrays/numeric.py
  pandas/tests/arrays/masked/test_arithmetic.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_floating.py
  pandas/tests/extension/test_integer.py
Labels: Testing, Dtype Conversions

#44691 REF: simplify Block.where (and subtle alignment bug)
  pandas/core/internals/blocks.py
Labels: Refactor, Internals

#44514 BUG: IntegerArray/FloatingArray constructors mismatched NAs
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/missing.pyx
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/floating/test_construction.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/series/methods/test_clip.py
  pandas/tests/series/test_constructors.py
Labels: Missing-data, ExtensionArray, NA - MaskedArrays

#44699 TST: de-duplicate fixtures
  pandas/conftest.py
  pandas/tests/arithmetic/conftest.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_allowlist.py
  pandas/tests/indexes/multi/test_monotonic.py
  pandas/tests/indexes/test_common.py
  pandas/tests/io/formats/test_series_info.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/reshape/concat/test_index.py
  pandas/tests/reshape/concat/test_series.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/test_repr.py
Labels: Testing

#44706 TST: fix xfails/skips
  pandas/core/computation/expressions.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/test_expressions.py
  pandas/tests/test_nanops.py
Labels: Testing

#44708 DOC: Removed link to Engarde project. It doesn't develop anymore. #44543
  doc/source/ecosystem.rst
Labels: Docs

#44710 Deprecate positional arguments for read_fwf
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/test_read_fwf.py
Labels: Deprecate, IO Fixed Width

#44612 CI/TST: Use CI moto service instead of subprocess
  .github/workflows/ci.yml
  .github/workflows/database.yml
  .github/workflows/posix.yml
  ci/deps/actions-38-db-min.yaml
  ci/deps/actions-38-db.yaml
  ci/deps/actions-38-locale.yaml
  ci/deps/actions-38-slow.yaml
  ci/deps/actions-39-slow.yaml
  ci/deps/actions-39.yaml
  ci/deps/azure-windows-38.yaml
  ci/deps/azure-windows-39.yaml
  pandas/tests/io/conftest.py
Labels: CI

#44255 TST: Add test for where inplace
  pandas/_testing/_hypothesis.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/tests/tslibs/test_ccalendar.py
Labels: Testing, Indexing

#44721 Backport PR #44658 on branch 1.3.x (BUG: groupby.sum with timedelta64 and NaT)
  doc/source/whatsnew/v1.3.5.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_function.py
Labels: Groupby, Timedelta

#44716 CLN: contextmanagers should yield in a try-finally block
  pandas/_config/config.py
  pandas/_testing/contexts.py
  pandas/util/_test_decorators.py
Labels: Clean

#44725 TST: Fix local run on s3 tests
  pandas/tests/io/conftest.py
Labels: Testing

#44724 PERF: DataFrame.T
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Performance, Reshaping, ExtensionArray

#44717 CLN: TODOs/FIXMEs
  asv_bench/benchmarks/frame_ctor.py
  doc/source/whatsnew/v0.5.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/_typing.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/indexes/interval.py
  pandas/tests/base/test_value_counts.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/methods/test_clip.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/plotting/test_series.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_ufunc.py
Labels: Clean

#44697 BUG: Series.where with incompatible NA value
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/arrays/integer/test_construction.py
  pandas/tests/frame/indexing/test_where.py
Labels: Bug, Indexing, Missing-data

#44711 DOC: validate_docstrings cleans up leftover files; doctest +SKIP file examples
  pandas/core/generic.py
  pandas/errors/__init__.py
  pandas/io/excel/_base.py
  pandas/io/pickle.py
  pandas/io/pytables.py
  pandas/io/stata.py
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#44664 TYP: changed variable cat_array to cat_array_list in dtypes.py and arr_list in categorical.py
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/dtypes.py
Labels: Typing

#44666 PERF: passthrough mask to take_1d if already known
  pandas/core/array_algos/take.py
  pandas/core/internals/array_manager.py
Labels: Performance, ArrayManager

#44624 PERF/TYP: typing cast in __getitem__ gives quite some overhead
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
Labels: Performance, Typing

#44702 DOC: fix examples in Timestamp functions
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs, Timeseries

#44713 Deprecate prefix argument in read_csv and read_table
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: IO CSV, Deprecate

#44733 CLN: TODOs
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/arrays/masked/test_arithmetic.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/test_arithmetic.py
Labels: Clean

#44730 TST: dont skip dt64tz rolling tests
  pandas/tests/window/conftest.py
  pandas/tests/window/test_dtypes.py
Labels: Testing, Window

#44728 TST: remove non-strict xfails
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_parquet.py
Labels: Testing

#44694 TST: read_csv raisin error with string dtype and parse dates
  pandas/tests/io/parser/test_parse_dates.py
Labels: Testing, IO CSV

#44756 CI/DOC: warning in docbuild
  doc/source/whatsnew/v0.10.0.rst
Labels: Docs

#44735 DOC: Improve code example for DataFrame.join
  pandas/core/frame.py
Labels: Docs, Reshaping

#44760 TST: Parameterize test_algos.py
  pandas/tests/test_algos.py
Labels: Testing

#44759 Fix compression misspelling in ExcelWriter
  pandas/io/excel/_base.py
Labels: IO Excel

#44753 REGR: find_stack_level reverts
  pandas/core/arrays/categorical.py
  pandas/core/indexes/base.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/series/accessors/test_cat_accessor.py
Labels: Performance, Regression, Warnings

#44750 CLN: Todo test reductions in test_style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Testing, Clean

#44688 ENH: Add indexing syntax to GroupBy.nth()
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/groupby/groupby.py
  pandas/core/groupby/indexing.py
  pandas/tests/groupby/test_nth.py
Labels: Groupby, API - Consistency

#44715 BUG: FloatingArray(float16data)
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/floating.py
  pandas/core/arrays/masked.py
  pandas/core/construction.py
  pandas/tests/arrays/boolean/test_function.py
  pandas/tests/arrays/floating/test_construction.py
  pandas/tests/arrays/test_array.py
Labels: Bug, Dtype Conversions

#44737 REF: share _reduce method
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reductions/test_stat_reductions.py
Labels: Refactor

#44747 ENH: implement tm.shares_memory
  pandas/_testing/__init__.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/floating/test_arithmetic.py
  pandas/tests/arrays/floating/test_astype.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/arrays/masked_shared.py
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_numpy.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Testing

#44749 BUG: series.interpolate(inplace=True) *actually* inplace
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Missing-data

#44609 ENH: improved dtype inference for Index.map
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
Labels: Dtype Conversions, ExtensionArray

#44672 Deprecate mapper argument in rename
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/series/methods/test_rename.py
Labels: Reshaping

#42252 ENH: allow attrs to be propagated via pd.concat
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Reshaping, metadata, Needs Review

#44744 CLN/TST: skips -> xfails
  pandas/_testing/__init__.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_floating.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/generic/test_to_xarray.py
  pandas/tests/indexes/interval/test_constructors.py
  pandas/tests/indexes/multi/test_analytics.py
  pandas/tests/io/excel/test_xlrd.py
  pandas/tests/io/parser/common/test_float.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_comment.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/test_parquet.py
Labels: Testing, Clean

#44680 44414 data frame attributes not propagating with astype
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/series/methods/test_astype.py
Labels: metadata

#43511 Updated code_checks.sh with PR06
  ci/code_checks.sh
  pandas/core/arrays/sparse/array.py
  pandas/core/tools/numeric.py
Labels: Docs

#44757 DOC: Uniform block directive syntax.
  .pre-commit-config.yaml
  doc/source/user_guide/io.rst
  pandas/core/algorithms.py
Labels: Docs, Code Style

#44773 fix PR06 failing CI
  pandas/core/frame.py
Labels: Docs

#44746 ENH: IntervalArray.min/max
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/interval.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/extension/test_interval.py
  pandas/tests/series/test_ufunc.py
Labels: Enhancement, Interval

#44771 CLN: FIXMEs
  pandas/_config/config.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/io/clipboard/__init__.py
  pandas/tests/arrays/floating/test_construction.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/series/methods/test_convert.py
  pandas/tests/series/test_missing.py
  pandas/tests/series/test_ufunc.py
Labels: Testing, Clean

#44559 PERF: avoid copy in concatenate_array_managers if reindex already copies
  pandas/core/internals/array_manager.py
  pandas/core/internals/concat.py
Labels: Performance, ArrayManager

#44776 TST: pytest.mark.parameterize some tests
  pandas/tests/test_multilevel.py
  pandas/tests/test_nanops.py
Labels: Testing

#44774 TST: Add regression test for groupby rolling
  pandas/tests/window/test_groupby.py
Labels: Testing

#44758 PERF: unstack
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Performance, Reshaping

#44775 CI: Filter any SSLSocket ResouceWarnings from dependencies
  pandas/_testing/_warnings.py
Labels: CI

#44777 CLN: memory_map do not silently fail
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/common.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_common.py
Labels: IO CSV, Clean

#44778 TST: Refactor test_expressions.py
  pandas/tests/test_expressions.py
Labels: Testing

#44790 REF: share MaskedArray reduction methods
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numeric.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/reductions/test_reductions.py
Labels: Refactor, ExtensionArray

#44797 TST: Avoid hanging behavior in test_user_agent.py
  pandas/tests/io/test_user_agent.py
Labels: Testing

#44795 BUG/TST: ArrowStringArray skips/xfails
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/test_string.py
  pandas/tests/strings/test_string_array.py
Labels: Strings, ExtensionArray

#44804 CLN: xfails, FIXMEs
  pandas/_testing/_warnings.py
  pandas/core/arraylike.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/numpy_.py
  pandas/core/indexes/period.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/indexes/datetimelike_/test_equals.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/test_base.py
  pandas/tests/io/parser/common/test_chunksize.py
  pandas/tests/io/test_html.py
  pandas/tests/plotting/test_series.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Clean

#44805 TST: split/parametrize
  pandas/_testing/asserters.py
  pandas/tests/frame/methods/test_convert.py
  pandas/tests/series/accessors/test_cat_accessor.py
  pandas/tests/series/methods/test_convert.py
Labels: Testing

#44741 TST: stricten xfails
  pandas/tests/io/parser/common/test_chunksize.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_groupby.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
Labels: Testing

#44765 REF: use idiomatic checks in __array_ufunc__
  pandas/core/arraylike.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/test_numpy.py
  pandas/tests/extension/decimal/array.py
Labels: Refactor

#44807 CLN: frequencies/test_inference.py
  pandas/tests/tseries/frequencies/test_inference.py
Labels: Testing

#44808 CLN: test_holiday
  pandas/tests/tseries/holiday/test_holiday.py
Labels: Testing

#44815 CLN: test_hashing
  pandas/tests/util/test_hashing.py
Labels: Testing

#44814 CI: use pytest-timeout to avoid windows timeouts
  .github/workflows/python-dev.yml
  azure-pipelines.yml
  ci/deps/actions-38-db-min.yaml
  ci/deps/actions-38-db.yaml
  ci/deps/actions-38-locale.yaml
  ci/deps/actions-38-locale_slow.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38-slow.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39-numpydev.yaml
  ci/deps/actions-39-slow.yaml
  ci/deps/actions-39.yaml
  ci/deps/azure-macos-38.yaml
  ci/deps/azure-windows-38.yaml
  ci/deps/azure-windows-39.yaml
  ci/deps/circle-38-arm64.yaml
  environment.yml
  pandas/tests/io/__init__.py
  pandas/tests/io/test_user_agent.py
  requirements-dev.txt
Labels: Testing, CI

#44812 Clarify regex interpretation in str.contains
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_find_replace.py
Labels: Docs, Indexing

#44810 TST: fix 217 incorrect skips
  pandas/core/indexes/datetimelike.py
  pandas/tests/arrays/floating/test_construction.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/scalar/test_nat.py
Labels: Testing

#44816 CLN: Split test_fields.py
  pandas/tests/tslibs/test_fields.py
Labels: Testing

#44740 DOC: Fix swaplevel docstring
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs

#44827 PERF: faster dataframe construction from recarray
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/internals/construction.py
Labels: Performance, Reshaping

#44828 REGR: resampling DataFrame with DateTimeIndex with empty groups and uint8, uint16 or uint32 columns incorrectly raising RuntimeError
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/groupby/ops.py
  pandas/tests/resample/test_datetime_index.py
Labels: Timeseries, Regression, Resample

#44834 CI: Pin numpydev wheels
  .github/workflows/python-dev.yml
  ci/deps/actions-39-numpydev.yaml
Labels: CI

#44838 Backport PR #44834 on branch 1.3.x (CI: Pin numpydev wheels)
  .github/workflows/python-dev.yml
  ci/deps/actions-38-numpydev.yaml
Labels: CI

#44831 Backport PR #44828 on branch 1.3.x (REGR: resampling DataFrame with DateTimeIndex with empty groups and uint8, uint16 or uint32 columns incorrectly raising RuntimeError)
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/groupby/ops.py
  pandas/tests/resample/test_datetime_index.py
Labels: Timeseries, Regression, Resample

#44762 BUG: MultiIndex union setting wrong sortorder parameter
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Indexing, MultiIndex

#44840 Tests added for dtype comparison with fixture
  pandas/tests/dtypes/test_common.py
Labels: Testing, Dtype Conversions

#44770 ENH: Enabling parsing ulonglong from json
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/src/ujson/lib/ultrajson.h
  pandas/_libs/src/ujson/lib/ultrajsondec.c
  pandas/_libs/src/ujson/python/JSONtoObj.c
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
Labels: Dtype Conversions, IO JSON

#44763 BUG: Raise TypeError for scalar indexer in take
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_indexing.py
Labels: Error Reporting

#44806 TST: group by - apply Key Error
  pandas/tests/groupby/test_apply.py
Labels: Testing, Groupby

#44843 CLN: Split and parameterize test_to_timedelta.py
  pandas/tests/tools/test_to_timedelta.py
Labels: Testing

#44824 BUG: Fix regression in groupby.rolling.corr/cov when other is same size as each group
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_groupby.py
Labels: Regression, Window

#44822 CI: Troubleshoot CI
  .github/workflows/python-dev.yml
  ci/deps/actions-39-numpydev.yaml
  pandas/_libs/ops_dispatch.pyx
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/plotting/test_datetimelike.py
Labels: CI

#44830 BUG: IntervalArray.__cmp__(pd.NA)
  pandas/_testing/__init__.py
  pandas/core/arrays/interval.py
  pandas/tests/arithmetic/test_interval.py
Labels: Bug, Interval

#44761 ENH: support SpooledTemporaryFile
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/common.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/test_common.py
Labels: IO Data

#44832 PERF: array_equivalent_object
  pandas/core/dtypes/missing.py
Labels: Performance

#44829 BUG: SparseArray.min/max skipna
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_array.py
Labels: Sparse

#44796 PERF: DataFrame.__setitem__
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Indexing, Performance

#44848 Backport PR #44824 on branch 1.3.x (BUG: Fix regression in groupby.rolling.corr/cov when other is same size as each group)
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_groupby.py
Labels: Regression, Window

#44849 Backport PR #44822 on branch 1.3.x (CI: Troubleshoot CI)
  .github/workflows/python-dev.yml
  ci/deps/actions-38-numpydev.yaml
  pandas/_libs/ops_dispatch.pyx
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/plotting/test_datetimelike.py
Labels: CI

#44851 DOC: 1.3.5 release date
  doc/source/whatsnew/v1.3.5.rst
Labels: Docs

#44853 Backport PR #44851 on branch 1.3.x (DOC: 1.3.5 release date)
  doc/source/whatsnew/v1.3.5.rst
Labels: Docs

#44850 CLN: Split/parameterize test_to_time
  pandas/tests/tools/test_to_time.py
Labels: Testing

#44858 Revert "CI: use pytest-timeout to avoid windows timeouts"
  .github/workflows/python-dev.yml
  azure-pipelines.yml
  ci/deps/actions-38-db-min.yaml
  ci/deps/actions-38-db.yaml
  ci/deps/actions-38-locale.yaml
  ci/deps/actions-38-locale_slow.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38-slow.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39-numpydev.yaml
  ci/deps/actions-39-slow.yaml
  ci/deps/actions-39.yaml
  ci/deps/azure-macos-38.yaml
  ci/deps/azure-windows-38.yaml
  ci/deps/azure-windows-39.yaml
  ci/deps/circle-38-arm64.yaml
  environment.yml
  pandas/tests/io/__init__.py
  pandas/tests/io/test_user_agent.py
  requirements-dev.txt
Labels: Clean

#37672 BUG: Fix bug in loc setitem changing the dtype when condition is False
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Bug, Indexing

#44863 CI/TST: Run http server in process instead of thread for test_user_agent.py
  pandas/tests/io/test_user_agent.py
Labels: Testing, CI

#44859 CLN: Split/parameterize test_to_datetime
  pandas/tests/tools/test_to_datetime.py
Labels: Testing

#44862 ENH: Add numba engine to groupby.var/std
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_numba.py
Labels: Enhancement, Groupby

#44669 BUG: Fix setitem with 1d matrix
  doc/source/whatsnew/v1.3.5.rst
  pandas/core/construction.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Constructors

#44251 TYP: Subset of "Improved the type stubs in the _libs directory to help with type checking"
  pandas/_libs/interval.pyx
  pandas/_libs/missing.pyi
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timestamps.pyi
  pandas/core/arrays/string_.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
  pandas/core/ops/mask_ops.py
  pandas/core/resample.py
  pandas/core/strings/object_array.py
  pandas/tests/arrays/boolean/test_logical.py
Labels: Typing

#44681 REF: hold PeriodArray in NDArrayBackedExtensionBlock
  pandas/core/dtypes/common.py
  pandas/core/internals/api.py
  pandas/core/internals/blocks.py
  pandas/core/internals/construction.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arrays/period/test_arrow_compat.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_parquet.py
Labels: Period

#44349 TYP: misc typing in _libs
  pandas/_libs/join.pyi
  pandas/_libs/ops.pyi
  pandas/_libs/tslibs/fields.pyi
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/timedeltas.pyi
Labels: Typing

#44854 TYP: stricter type for compression
  pandas/_typing.py
  pandas/io/parsers/readers.py
  pandas/io/xml.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/io/xml/test_xml.py
Labels: Typing

#44820 REF: use dispatch_reduction_ufunc in PandasArray.__array_ufunc__
  pandas/core/arrays/numpy_.py
Labels: Refactor

#44875 TST: Parameterize test_strings.py
  pandas/tests/strings/test_strings.py
Labels: Testing

#44873 BUG: Index.fillna silently ignoring 'downcast' kwarg
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/tests/indexes/categorical/test_fillna.py
  pandas/tests/indexes/common.py
Labels: Bug, Missing-data

#44809 CI: PyPy3 testing
  .github/workflows/posix.yml
  ci/deps/actions-pypy-38.yaml
Labels: CI, PyPy

#44327 BUG: is_dtype_equal(dtype, "string[pyarrow]") raises if pyarrow not installed
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
Labels: Dtype Conversions

#44890 CLN/TST: remove used-once fixtures
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/tests/base/test_misc.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/io/json/test_pandas.py
Labels: Testing

#44876 TST: Split/parameterize test_split_partition.py
  pandas/tests/strings/test_split_partition.py
Labels: Testing

#44907 CI: echo PYTHONHASHSEED for (hopeful) run reproducibility
  ci/run_tests.sh
Labels: CI

#44884 TST: fix tm.to_array nullable handling
  pandas/_testing/__init__.py
  pandas/tests/arithmetic/test_numeric.py
Labels: Testing

#44910 DOC: follow up #44327, change issue number
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#44857 PERF: any/all with axis=1
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Performance, Reshaping

#44918 TST: skip fewer tests
  ci/deps/actions-38-db.yaml
  environment.yml
  pandas/conftest.py
  pandas/core/arrays/categorical.py
  pandas/tests/base/test_fillna.py
  pandas/tests/base/test_unique.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/test_algos.py
Labels: Testing

#44906 BUG: np.divmod with Sparse
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/series/test_ufunc.py
Labels: Bug, Sparse

#44895 Remove numpy compat functions
  pandas/compat/__init__.py
  pandas/compat/numpy/__init__.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/base/test_value_counts.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/methods/test_asof.py
  pandas/tests/test_algos.py
  pandas/tests/tseries/offsets/test_business_day.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Compat

#44892 TST/REF: collect mask tests
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_mask.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Testing

#44888 CLN/TST: parametrize
  asv_bench/benchmarks/arithmetic.py
  pandas/compat/pickle_compat.py
  pandas/core/api.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/computation/api.py
  pandas/core/dtypes/api.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/reshape/api.py
  pandas/errors/__init__.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/test_common.py
  pandas/tests/tools/test_to_time.py
  pandas/tseries/holiday.py
Labels: Testing, Clean

#44879 BUG: doing a class method lookup in __dealloc__ is dangerous
  pandas/_libs/parsers.pyx
Labels: IO CSV

#44878 BUG: Inconsistent conversion of missing column names
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/common.py
  pandas/core/frame.py
  pandas/core/indexes/multi.py
  pandas/io/json/_table_schema.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/tests/frame/methods/test_to_records.py
Labels: Reshaping

#44899 BUG: read_csv not raising when \n as sep
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
Labels: Error Reporting, IO CSV

#44908 PERF: Improve performance in to_csv with date format for index
  asv_bench/benchmarks/io/csv.py
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/csvs.py
Labels: Performance, IO CSV

#44929 DEPR: Categorical.replace
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/arrays/categorical/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Categorical, Deprecate

#44902 Bug in concat casting all na levels to float
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_missing.py
  pandas/tests/reshape/concat/test_datetimes.py
Labels: Missing-data, Reshaping, Dtype Conversions

#44916 DEPR: ‘names’ param in Index.copy
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: Deprecate, Index

#44943 PERF: Performance improvement in to_csv with unused levels in multiindex
  asv_bench/benchmarks/io/csv.py
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/csvs.py
Labels: Performance, IO CSV

#44942 ASV: Add additional to_csv benchmark
  asv_bench/benchmarks/io/csv.py
Labels: IO CSV, Benchmark

#44901 BUG: read_csv converting nans to 1 when casting bools to float
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/parsers.pyx
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/test_na_values.py
Labels: Dtype Conversions, Error Reporting, IO CSV

#44941 TST/REF: share shift tests
  pandas/_testing/__init__.py
  pandas/_testing/compat.py
  pandas/tests/frame/methods/test_shift.py
  pandas/tests/series/methods/test_shift.py
Labels: Testing

#44852 CI: Creating separate job for benchmarks
  .github/workflows/ci.yml
Labels: CI, Benchmark

#44932 REF: get regex logic out of Block.replace
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Refactor, Internals

#44887 CI: Fix PyPy CI
  .github/workflows/posix.yml
  ci/deps/actions-pypy-38.yaml
  ci/run_tests.sh
Labels: CI, PyPy

#44938 TST: Add any_string_dtype parameterization to test
  pandas/tests/strings/test_split_partition.py
Labels: Testing

#44935 BUG: PeriodArray.to_timestamp when non-contiguous
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/tests/indexes/period/methods/test_to_timestamp.py
Labels: Bug, Dtype Conversions, Period

#44228 DOC: local py.typed for users
  .gitignore
  doc/source/development/contributing_codebase.rst
Labels: Docs, Typing

#44944 BUG: groupby agg raising when column was selected twice
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/base.py
  pandas/tests/groupby/test_indexing.py
Labels: Groupby, Indexing, Error Reporting

#43968 FIX BUG: Timestamp __add__/__sub__ DateOffset with nanoseconds lost.
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Bug, Frequency

#44931 Bug: names of multiindex columns not set correctly when index col is not first column
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/base_parser.py
  pandas/tests/io/parser/test_index_col.py
Labels: Bug, IO CSV

#44951 Add tests for usecols and index col combinations
  pandas/tests/io/parser/usecols/test_usecols_basic.py
Labels: Testing, IO CSV

#44954 DOC: Fix mistake in code example
  doc/source/user_guide/timeseries.rst
Labels: Docs

#44961 CLN: tests/window/moments
  pandas/tests/window/moments/conftest.py
  pandas/tests/window/moments/test_moments_consistency_ewm.py
  pandas/tests/window/moments/test_moments_consistency_expanding.py
  pandas/tests/window/moments/test_moments_consistency_rolling.py
Labels: Testing, Window

#44928 BUG: SparseArray.__floordiv__ not matching non-Sparse Series behavior
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/sparse_op_helper.pxi.in
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_arithmetics.py
Labels: Numeric Operations, Sparse

#44939 ENH: Add numba engine to groupby.sum
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_numba.py
Labels: Enhancement, Groupby

#44948 DOC: update documentation of type annotation (PEP 585)
  doc/source/development/contributing_codebase.rst
Labels: Docs, Typing
