Repository pandas-dev/pandas, pull requests merged in 2022-10, with the labels that each got.

#48897 STYLE: fix pylint style checks for inherit-non-class.
  pandas/core/arrays/base.py
  pyproject.toml
Labels: Code Style

#48912 solved the pylint issue of "no self argument"
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/io/test_sql.py
  pandas/tests/scalar/period/test_period.py
  pyproject.toml
Labels: Code Style

#48906 Fix: Reanme duplicate function names in unittests
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/window/test_groupby.py
  pyproject.toml
Labels: Code Style

#48917 fix warning no-value-for-parameter in pandas/io
  pandas/io/excel/_base.py
Labels: Warnings

#48907 TYP: Axis-related annotations
  pandas/core/apply.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/reshape/concat.py
  pandas/core/series.py
  pandas/io/pytables.py
Labels: Typing

#48862 REF: helpers to de-duplicate datetimelike arithmetic
  pandas/core/arrays/datetimelike.py
Labels: Refactor, Timeseries, Numeric Operations

#48889 BUG: preserve EA in pd.array
  pandas/core/construction.py
  pandas/tests/arrays/test_array.py
Labels: ExtensionArray, Constructors

#47672 Bug fix using GroupBy.resample produces inconsistent behavior when calling it over empty df #47705
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Groupby

#47405 SAS7BDAT parser: Speed up RLE/RDC decompression
  asv_bench/benchmarks/io/sas.py
  pandas/io/sas/sas.pyx
  pandas/tests/io/sas/test_sas7bdat.py
Labels: Performance, IO SAS

#48927 TST: Use more index_or_series
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/concat/test_append_common.py
  pandas/tests/tools/test_to_datetime.py
Labels: Testing, Clean

#48879 WEB: Add Luke to maintainers list
  web/pandas/config.yml
Labels: Web

#48929 Backport PR #48879 on branch 1.5.x (WEB: Add Luke to maintainers list)
  web/pandas/config.yml
Labels: Web

#48932 DOC: Small docstring clarifications
  pandas/core/indexes/datetimes.py
  pandas/core/tools/datetimes.py
Labels: Docs

#47656 SAS7BDAT parser: Improve subheader lookup performance
  pandas/io/sas/_sas.pyi
  pandas/io/sas/sas.pyx
  pandas/io/sas/sas7bdat.py
Labels: Performance, IO SAS

#48898 BUG: Timedelta.__new__
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/scalar/timedelta/test_constructors.py
Labels: Timedelta

#48928 API: .astype to non-nano return the specified dtype
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/dtypes/astype.py
  pandas/tests/frame/methods/test_astype.py
Labels: Dtype Conversions, Non-Nano

#48894 BUG: DatetimeArray-datetimelike mixed resos
  pandas/_libs/tslibs/timestamps.pyi
  pandas/core/arrays/datetimelike.py
  pandas/tests/arrays/test_datetimes.py
Labels: Timeseries, Numeric Operations, Non-Nano

#48824 REGR: groupby fails with nullable dtypes and dropna=False
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/groupby/test_groupby_dropna.py
Labels: Bug, Groupby, Regression, NA - MaskedArrays

#48764 SAS7BDAT parser: Drop unused instance variables
  pandas/io/sas/sas7bdat.py
Labels: Clean, IO SAS

#48926 TST/CLN: Use more frame_or_series fixture
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/test_period.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/frame/methods/test_pct_change.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/methods/test_sample.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/resample/conftest.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/window/test_base_indexer.py
Labels: Testing, Clean

#48938 Backport PR #48824 on branch 1.5.x (REGR: groupby fails with nullable dtypes and dropna=False)
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/groupby/test_groupby_dropna.py
Labels: Bug, Groupby, Regression, NA - MaskedArrays

#47403 SAS7BDAT parser: Fast byteswap
  doc/source/whatsnew/v1.6.0.rst
  pandas/io/sas/_byteswap.pyi
  pandas/io/sas/byteswap.pyx
  pandas/io/sas/sas7bdat.py
  pandas/tests/io/sas/test_byteswap.py
  setup.py
Labels: Performance, IO SAS

#48676 BUG: to_datetime raising on invalid offsets with errors=coerce and infer_datetime_format
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tslibs/test_parsing.py
Labels: Bug, Timeseries

#48943 REGR: ExcelWriter.book not settable
  doc/source/whatsnew/v1.5.1.rst
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
  pandas/tests/io/excel/test_writers.py
Labels: Bug, Regression, IO Excel, Deprecate

#48935 DOC: reverted directive for SAS logo white
  doc/source/getting_started/index.rst
Labels: Bug, Docs

#48960 Backport PR #48935 on branch 1.5.x (DOC: reverted directive for SAS logo white)
  doc/source/getting_started/index.rst
Labels: Bug, Docs

#48924 TST: Fail if parameterize set is empty
  pandas/tests/computation/test_eval.py
  pyproject.toml
Labels: Testing

#48899 CLN/TST: Remove ensure_clean_dir for tmp_dir fixture
  pandas/_testing/__init__.py
  pandas/_testing/contexts.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_parquet.py
  pandas/tests/util/test_util.py
Labels: Testing, Clean

#48958 CLN: Replace test_fast scripts with documenting xdist n flag
  Makefile
  doc/source/development/contributing_codebase.rst
  test_fast.bat
  test_fast.sh
Labels: Clean

#48953 REF: de-duplicate reso-casting code
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/tslibs/test_api.py
Labels: Refactor, Non-Nano

#48956 Implement get_supported_reso
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/dtypes.pyx
Labels: Non-Nano

#48954 BUG: guess_datetime_format doesn't guess format correctly for UTC+1
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/tslibs/test_parsing.py
Labels: Bug, Timeseries

#48959 Backport PR #48943 on branch 1.5.x (REGR: ExcelWriter.book not settable)
  doc/source/whatsnew/v1.5.1.rst
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
  pandas/tests/io/excel/test_writers.py
Labels: Bug, Regression, IO Excel, Deprecate

#48900 BUG/PERF: algos.union_with_duplicates losing EA dtypes
  asv_bench/benchmarks/index_object.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/algorithms.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_setops.py
Labels: Performance, MultiIndex, Index

#48970 BUG: to_datetime(..., infer_datetime_format=True) fails with np.str_input
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Bug, Timeseries

#48896 fix pylint bad-super-call
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/generic/test_frame.py
  pyproject.toml
Labels: Code Style

#48961 ENH: support Timedelta division with mismatched resos
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Timedelta, Non-Nano

#48962 REF: tighter typing in datetimelike arith methods
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_period.py
Labels: Refactor, Timeseries, Numeric Operations, Typing

#48965 DOC: Fixed documentation for pivot_table margins (#48916)
  pandas/core/frame.py
Labels: Docs, Reshaping

#48495 BUG/PERF: use lexsort_indexer in MultiIndex.argsort
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexing/multiindex/test_sorted.py
Labels: Bug, Performance, MultiIndex, NA - MaskedArrays

#48948 STYLE: Add code check to avoid returning Exceptions instead of raising
  .pre-commit-config.yaml
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/managers.py
  pandas/io/pytables.py
Labels: Code Style

#48925 TST/CLN: Remove ensure_clean_path for tmp_dir fixture
  pandas/tests/io/pytables/common.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/pytables/test_compat.py
  pandas/tests/io/pytables/test_complex.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_keys.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_retain_attributes.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/pytables/test_subclass.py
  pandas/tests/io/pytables/test_timezones.py
Labels: Testing, IO HDF5, Clean

#48989 CI: Pin pydata sphinx theme
  environment.yml
  requirements-dev.txt
Labels: Docs, CI, Dependencies

#48776 ENH: Add option to use nullable dtypes in read_csv
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/parsers.pyx
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: IO CSV, NA - MaskedArrays

#48987 REG: Fix regression in assert_frame_equal for categorical and check_like
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/indexes/api.py
  pandas/tests/util/test_assert_frame_equal.py
Labels: Testing, Regression

#48980 DOC: Updated Resampler.mean docstring to have its own docstring
  pandas/core/resample.py
Labels: Docs, Resample, Reduction Operations

#48945 REF: Refactor cibuildwheel logic into pyproject.toml
  .github/workflows/wheels.yml
  pyproject.toml
Labels: Build

#48910 API: preserve reso in Timelta(td64_obj)
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/window/ewm.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/dtypes/cast/test_promote.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/scalar/timedelta/test_constructors.py
Labels: Timedelta, Non-Nano

#48993 Backport PR #48989 on branch 1.5.x (CI: Pin pydata sphinx theme)
  environment.yml
  requirements-dev.txt
Labels: Docs, CI, Dependencies

#48976 PERF: df.groupby(categorical, sort=False)
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/groupby/categorical.py
Labels: Groupby, Performance, Categorical

#48918 API: Timedelta constructor pytimedelta, Tick preserve reso
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/masked.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/dtypes/cast/test_promote.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Timedelta, Frequency

#48963 API: .astype td64->td64 give requested dtype
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/astype.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/indexing/test_loc.py
Labels: Timeseries, Dtype Conversions

#49002 Backport PR #48412 on branch 1.5.x (BUG: safe_sort losing MultiIndex dtypes)
  pandas/core/algorithms.py
  pandas/tests/test_sorting.py
Labels: Dtype Conversions, MultiIndex

#48973 CI: Bump timeouts Python dev builds
  .github/workflows/python-dev.yml
Labels: CI

#49030 DOC: Remove mention of make
  README.md
Labels: Docs

#49015 BUG: resolution in datetimelike add/sub timedeltalike scalar
  pandas/core/arrays/datetimelike.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Timeseries, Numeric Operations, Timedelta, Non-Nano

#49009 REF: avoid sanitize_to_nanoseconds
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/groupby/grouper.py
Labels: Refactor, Timeseries

#49004 CLN/TST: Use fixture instead of setup_method
  pandas/tests/frame/test_query_eval.py
  pandas/tests/io/json/test_json_table_schema_ext_dtype.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/window/test_groupby.py
Labels: Testing, Clean

#48999 CLN: test_nanops/take.py
  pandas/tests/test_nanops.py
  pandas/tests/test_take.py
Labels: Testing, Clean

#49018 pylint: fix misplaced-bare-raise
  pandas/core/internals/blocks.py
  pyproject.toml
Labels: Code Style

#48022 ENH: change get_dummies default dtype to bool
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/reshape/encoding.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/reshape/test_get_dummies.py
Labels: Reshaping

#48580 CLN: Simplify factorize
  pandas/core/algorithms.py
  pandas/tests/test_sorting.py
Labels: Algos, Clean

#48923 BUG: preserve DTA/TDA+timedeltalike scalar with mismatched resos
  pandas/tests/arrays/test_datetimes.py
Labels: Timeseries, Numeric Operations, Timedelta, Non-Nano

#49038 STYLE check for ability to remove 'c-extension-no-member' from pylint exclusions
  pyproject.toml
Labels: Code Style

#49040 REF: sequence_to_dt64ns
  pandas/core/arrays/datetimes.py
  pandas/tests/arrays/datetimes/test_constructors.py
Labels: Refactor, Timeseries

#49017 CLN: tseries/offsets base tests
  pandas/tests/tseries/offsets/common.py
  pandas/tests/tseries/offsets/test_common.py
  pandas/tests/tseries/offsets/test_custom_business_hour.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Testing, Frequency, Clean

#49005 DOC: Fix typos and standardize spelling of "GitHub" and "macOS"
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/macos-windows.yml
  .github/workflows/python-dev.yml
  .github/workflows/wheels.yml
  .pre-commit-config.yaml
  doc/source/development/contributing_codebase.rst
  doc/source/development/maintaining.rst
  doc/source/ecosystem.rst
  doc/source/getting_started/overview.rst
  doc/source/whatsnew/v1.5.0.rst
  doc/sphinxext/announce.py
  pandas/_version.py
  pandas/core/internals/api.py
  pandas/core/missing.py
  pandas/io/clipboard/__init__.py
  pandas/tests/extension/json/array.py
  pandas/tests/io/conftest.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
  pandas/tests/window/test_win_type.py
  versioneer.py
  web/pandas/community/ecosystem.md
  web/pandas/getting_started.md
  web/pandas_web.py
Labels: Docs

#48280 BUG: array ufuncs with more than 2 inputs fails with 2 or more pd.Series and scalar arguments
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/arraylike.py
  pandas/tests/frame/test_ufunc.py
  pandas/tests/series/test_ufunc.py
Labels: ufuncs

#49047 BUG: guess_datetime_format doesn't guess 2018-01-01T00:00:00.000
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/tslibs/test_parsing.py
Labels: Bug, Timeseries

#49036 STYLE: Fix or suppress non-iterator-returned errors from pylint
  pandas/tests/io/test_html.py
  pyproject.toml
Labels: Code Style

#49010 BUG/PERF: MultiIndex setops with sort=None
  asv_bench/benchmarks/multiindex_object.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/algorithms.py
  pandas/tests/indexes/multi/test_setops.py
Labels: Bug, Performance, MultiIndex, setops

#49051 CLN: parametrize tests, comments, docstrings
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimelike.py
  pandas/core/reshape/merge.py
  pandas/tests/base/test_constructors.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/test_constructors.py
Labels: Testing, Docs, Clean

#49008 ENH: retain reso in Timestamp(dt64_obj)
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/frame/test_constructors.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/tools/test_to_datetime.py
Labels: Non-Nano, Timestamp

#49050 BUG: DTA.isin with mismatched resos
  pandas/core/arrays/datetimelike.py
  pandas/tests/series/methods/test_isin.py
Labels: Timeseries, Non-Nano

#48995 REGR: to_parquet raising with bytes filename
  doc/source/whatsnew/v1.5.1.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Regression, IO Parquet

#48990 DOC: replace developer meeting with contributor community page
  doc/redirects.csv
  doc/source/development/community.rst
  doc/source/development/index.rst
  doc/source/development/meeting.rst
Labels: Docs

#49067 Backport PR #48990 on branch 1.5.x (DOC: replace developer meeting with contributor community page)
  doc/redirects.csv
  doc/source/development/community.rst
  doc/source/development/index.rst
  doc/source/development/meeting.rst
Labels: Docs

#49061 Backport PR #48995 on branch 1.5.x (REGR: to_parquet raising with bytes filename)
  doc/source/whatsnew/v1.5.1.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Regression, IO Parquet

#49070 CI: Fix DeprecationWarning of numpy dev
  pandas/tests/series/test_constructors.py
Labels: Dependencies

#49074 Backport PR #49070 on branch 1.5.x (CI: Fix DeprecationWarning of numpy dev)
  pandas/tests/series/test_constructors.py
Labels: Dependencies

#49072 BUG: redirect from meeting to community was incorrect
  doc/redirects.csv
Labels: Docs

#49000 CLN/TST: Remove testing ArrowExtensionArray in favor of `extensions/test_arrow.py`
  pandas/tests/extension/arrow/__init__.py
  pandas/tests/extension/arrow/arrays.py
  pandas/tests/extension/arrow/test_bool.py
  pandas/tests/extension/arrow/test_string.py
  pandas/tests/extension/arrow/test_timestamp.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
Labels: Testing, Clean, Arrow

#49033 TST/CLN: Avoid subprocess shell=True
  pandas/_config/localization.py
  pandas/tests/config/test_localization.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/accessors/test_dt_accessor.py
Labels: Testing, Clean

#49077 Backport PR #49072 on branch 1.5.x (BUG: redirect from meeting to community was incorrect)
  doc/redirects.csv
Labels: Docs

#48984 DOC: Update xdist to provide more speed-up options and context (#48958) (#48535)
  doc/source/development/contributing_codebase.rst
Labels: Docs

#48752 PERF: MultiIndex.union
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/indexes/multi.py
Labels: Performance, MultiIndex

#49011 differences in Series.map with defaultdict with different dtypes
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/base.py
  pandas/tests/apply/test_series_apply.py
Labels: Missing-data, Series

#48457 TST: Fix unsigned pyarrow types in SIGNED_INT_PYARROW_DTYPES
  pandas/_testing/__init__.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48321 dataframe.astype() exception message to include column name
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_astype.py
Labels: Dtype Conversions, Error Reporting

#49088 Remove out-of-date external compatibility section from hdf_store docs
  doc/source/getting_started/comparison/comparison_with_r.rst
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.16.0.rst
Labels: Docs, IO HDF5

#49080 REGR: midx.values resetting freq of underyling index
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_get_level_values.py
Labels: Regression, MultiIndex

#49093 Backport PR #48457 on branch 1.5.x (TST: Fix unsigned pyarrow types in SIGNED_INT_PYARROW_DTYPES)
  pandas/_testing/__init__.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48966 BUG: pd.compare does not recognize differences when comparing values with null Int64 data type
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_compare.py
Labels: NA - MaskedArrays

#49094 Backport PR #49080 on branch 1.5.x (REGR: midx.values resetting freq of underyling index)
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_get_level_values.py
Labels: Regression, MultiIndex

#49100 DOC: Update documentation for window parameter of rolling() to account for all possible data types
  pandas/core/generic.py
  pandas/core/window/rolling.py
Labels: Docs, Window

#49097 REF: reso->creso in TSObject
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Refactor, Non-Nano

#49098 REF: _as_reso->_as_creso
  pandas/_libs/index.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timedeltas.pxd
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyx
Labels: Refactor, Non-Nano

#49099 CLN: simplify maybe_normalize_endpoints
  pandas/core/arrays/datetimes.py
Labels: Clean

#49092 BUG: unstack accessing wrong index level when midx has mixed names
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/series/methods/test_unstack.py
Labels: Reshaping, MultiIndex

#49014 API: retain non-nano timedelta64 dtype in DataFrame/Series/Index constructors
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/__init__.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/timedeltas.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arrays/test_array.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tools/test_to_timedelta.py
  pandas/tests/tslibs/test_api.py
Labels: Timedelta, Constructors, Non-Nano

#48770 added sytle in stylesheet for <blockquote>
  web/pandas/static/css/pandas.css
Labels: Web

#49102 Backport PR #48770 on branch 1.5.x (added sytle in stylesheet for <blockquote>)
  web/pandas/static/css/pandas.css
Labels: Web

#49122 DOC: Fixed Issue: Typo of DataFrame.iat() in 10 minutes to panda
  doc/source/user_guide/10min.rst
Labels: Docs

#49123 REF: reso->creso
  pandas/_libs/index.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/tzconversion.pxd
  pandas/_libs/tslibs/tzconversion.pyi
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/_libs/tslibs/vectorized.pyx
  pandas/core/arrays/datetimes.py
Labels: Clean, Timestamp

#49125 DOC: fix versionchanged blank line usage (#49117)
  pandas/plotting/_core.py
Labels: Docs

#49120 BUG: _guess_datetime_format_for_array doesn't guess if first element is '' or 'NaT'
  pandas/_libs/tslib.pyi
  pandas/_libs/tslib.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Bug, Timeseries

#49127 BUG: guess_datetime_format doesn't guess just year
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/tslibs/test_parsing.py
Labels: Timeseries

#49137 WEB/DOC: Fix typo in OVH name
  doc/_templates/pandas_footer.html
  web/pandas/_templates/layout.html
Labels: Docs, Web

#49138 Backport PR #49137 on branch 1.5.x (WEB/DOC: Fix typo in OVH name)
  doc/_templates/pandas_footer.html
  web/pandas/_templates/layout.html
Labels: Docs, Web

#49136 CLN: Replace _obj_with_exclusions with _select_obj for Series
  pandas/core/groupby/generic.py
Labels: Groupby, Clean

#49064 STYLE: fix pylint no-method-argument warning
  pandas/tests/io/test_gcs.py
  pyproject.toml
Labels: Code Style

#49145 BUG: guess_datetime_format fails to read 13/2019 in dateutil==2.8.1
  ci/deps/actions-38-minimum_versions.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/tests/tslibs/test_parsing.py
  setup.cfg
Labels: Bug, Timeseries, Dependencies

#49140 Revert "PERF: faster corrwith method for pearson and spearman correlation when other is a Series and axis = 0 (column-wise) (#46174)"
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_cov_corr.py
Labels: Algos

#49147 REGR: read_csv and nullable dtypes fails if dtype is specified
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: Regression, IO CSV

#49124 BUG: setitem raising for rhs with midx columns and tuple indexer
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Indexing, MultiIndex

#49114 BLD: Add meson build scripts
  scripts/generate_pxi.py
  scripts/generate_version.py
Labels: Build

#49105 CLN/TST: Remove pandas_testing_mode
  .github/workflows/ubuntu.yml
  pandas/_testing/__init__.py
  pandas/tests/io/pytables/conftest.py
Labels: Testing, Clean

#49149 DOC Replace gitter badge with one for slack
  README.md
Labels: Docs

#49151 Backport PR #49140 on branch 1.5.x (Revert "PERF: faster corrwith method for pearson and spearman correlation when other is a Series and axis = 0 (column-wise) (#46174)")
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_cov_corr.py
Labels: Algos

#49134 DOC/BUG: Enforce that freq is required in Period.now
  pandas/_libs/tslibs/period.pyx
  pandas/tests/scalar/period/test_period.py
Labels: Docs, Period

#49096 DEPS: Bump PyArrow to 6.0
  .github/workflows/ubuntu.yml
  ci/deps/actions-38-minimum_versions.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/_testing/__init__.py
  pandas/compat/__init__.py
  pandas/compat/_optional.py
  pandas/compat/pyarrow.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/arrow/dtype.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/base/test_unique.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/test_parquet.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_strings.py
Labels: Dependencies, Arrow

#49155 BUG: NA with binary operation with bytes
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/missing.pyx
  pandas/tests/scalar/test_na_scalar.py
Labels: Missing-data, Numeric Operations

#49152 TST/CLN: Use monkeypatch fixture instead of setup_method
  pandas/tests/config/test_config.py
Labels: Testing, Clean

#49154 TST/CLN: Ensure sqlite memory connections are closed
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL, Clean

#49128 PERF: pd.concat with EA-backed indexes
  asv_bench/benchmarks/array.py
  asv_bench/benchmarks/join_merge.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/masked.py
  pandas/core/arrays/string_.py
  pandas/tests/arrays/masked/test_function.py
  pandas/tests/arrays/string_/test_string.py
Labels: Performance, Reshaping, ExtensionArray

#49165 Backport PR #49162 on branch 1.5.x (PERF: Fix performance regression for isin with mismatching dtypes)
  doc/source/whatsnew/v1.5.1.rst
  pandas/core/algorithms.py
Labels: Performance, Regression, Algos

#49156 API: Change Series/DataFrame.other default to no_default instead of np.nan
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
  pandas/tests/extension/test_arrow.py
Labels: Missing-data, API - Consistency

#49148 CLN use pd.Timestamp for single element in converter
  doc/source/whatsnew/v2.0.0.rst
  pandas/plotting/_matplotlib/converter.py
Labels: Clean

#49109 PERF: StringArray from np.str_ array
  asv_bench/benchmarks/array.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/arrays/string_/test_string.py
Labels: Performance, Strings

#49058 API: retain non-nano dtype in DatetimeArray constructor
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/cast.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/test_array.py
  pandas/tests/base/test_constructors.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/window/test_online.py
Labels: Timeseries, Constructors, Non-Nano

#49104 BUG: Timestamp.__richcmp__(dt64_unsupported_reso)
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_comparisons.py
Labels: Numeric Operations, Non-Nano, Timestamp

#49169 API: stop silent conversion of object-Index to DatetimeIndex
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/generic.py
  pandas/core/series.py
  pandas/io/pytables.py
  pandas/tests/series/test_constructors.py
Labels: Timeseries, Index, Constructors

#49177 PERF: ArrowExtensionArray.factorize
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/arrow/array.py
Labels: Performance, Arrow

#49160 Replace pylint message types with explicit message names
  pyproject.toml
Labels: Code Style

#49179 DOC: Adding whatsnew for 1.5.2 and clean up of whatsnew for 1.5.0 and 1.5.1
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.5.0.rst
  doc/source/whatsnew/v1.5.1.rst
  doc/source/whatsnew/v1.5.2.rst
Labels: Docs, Release, Clean

#49081 DEP: Enforce deprecation of pad/backfill for groupby and resample
  doc/source/reference/groupby.rst
  doc/source/reference/resampling.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/base.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/tests/groupby/test_allowlist.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/resample/test_deprecated.py
Labels: Groupby, Deprecate

#49161 BUG: loc casting to object for multi block case when setting with list indexer
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_coercion.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
Labels: Indexing

#49184 Backport PR #49179 on branch 1.5.x (DOC: Adding whatsnew for 1.5.2 and clean up of whatsnew for 1.5.0 and 1.5.1)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.5.0.rst
  doc/source/whatsnew/v1.5.1.rst
  doc/source/whatsnew/v1.5.2.rst
Labels: Docs, Release, Clean

#49182 BUG: CSV C engine raises an error on single line CSV with no header w…
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/common/test_common_basic.py
Labels: IO CSV

#49172 TST: ArrowExtensionArray with string and binary types
  doc/source/whatsnew/v2.0.0.rst
  pandas/_testing/__init__.py
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Strings, Arrow

#48822 DEPR: Enforce is_extension_type removal
  doc/source/reference/arrays.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/conftest.py
  pandas/core/arrays/sparse/array.py
  pandas/core/dtypes/api.py
  pandas/core/dtypes/common.py
  pandas/tests/api/test_types.py
  pandas/tests/dtypes/test_common.py
Labels: Deprecate

#48839 DEPR: Enforce rolling.count min_periods deprecation
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_base_indexer.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_rolling_functions.py
  pandas/tests/window/test_timeseries_window.py
Labels: Deprecate, Window

#49087 DEP: Enforce deprecation of names and dtype in index copy and codes and levels in midx.copy
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/multi/test_copy.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
Labels: Deprecate, Index

#49192 PERF: Avoid call to list in isin
  pandas/core/algorithms.py
Labels: Performance, Algos

#48821 DEPR: Enforce deprecation of Categorical.min/max(numeric_only)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_analytics.py
Labels: Deprecate

#48823 DEPR: Enforce DTI.to_series(keep_tz) removal
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/indexes/datetimes/methods/test_to_series.py
Labels: Deprecate

#48840 DEPR: Enforce expanding(center) deprecation
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/generic.py
  pandas/core/window/expanding.py
  pandas/tests/window/test_expanding.py
Labels: Deprecate, Window

#49193 DEPR: enforce try_cast argument deprecation in mask/where
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/indexing/test_mask.py
  pandas/tests/frame/indexing/test_where.py
Labels: Deprecate

#49082 DEP: Enforce deprecation of squeeze argument in groupby
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/shared_docs.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_timegrouper.py
Labels: Groupby, Deprecate

#49204 Removed gitter from contributing.rst
  doc/source/development/contributing.rst
Labels: Docs
