Repository pandas-dev/pandas, pull requests merged in 2022-09, with the labels that each got.

#48336 DOC: Add whatsnew note for #45404
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#48337 Switch to mambaforge for circleci
  .circleci/setup_env.sh
Labels: CI

#48324 BUG: Add note in whatsnew for DataFrame.at behavior change
  doc/source/whatsnew/v1.5.0.rst
  pandas/tests/indexing/test_at.py
Labels: Bug, Indexing

#48345 Backport PR #48324 on branch 1.5.x (BUG: Add note in whatsnew for DataFrame.at behavior change)
  doc/source/whatsnew/v1.5.0.rst
  pandas/tests/indexing/test_at.py
Labels: Bug, Indexing

#48341 Backport PR #48336 on branch 1.5.x (DOC: Add whatsnew note for #45404)
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#48334 BUG: read_html(extract_links=all) with no header
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: IO HTML

#48113 DOC: update contributing to pandas documentation
  doc/source/development/contributing.rst
Labels: Docs

#48329 WEB: Update to `jupyterlite==0.1.0b12`
  environment.yml
  requirements-dev.txt
Labels: Web

#48254 REF: avoid FutureWarning about using deprecates loc.__setitem__ non-inplace usage
  pandas/core/generic.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Indexing, Warnings

#48353 Backport PR #48254 on branch 1.5.x (REF: avoid FutureWarning about using deprecates loc.__setitem__ non-inplace usage)
  pandas/core/generic.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Indexing, Warnings

#48350 Backport PR #48334 on branch 1.5.x (BUG: read_html(extract_links=all) with no header)
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: IO HTML

#48359 pytest: Use colored output
  pyproject.toml
Labels: CI

#48357 DOC: add pd.Grouper type to groupby by argument types
  pandas/core/shared_docs.py
Labels: Docs, Groupby

#48265 CI: Setting up ssh key to upload prod docs
  .github/workflows/docbuild-and-upload.yml
Labels: Docs, CI

#48190 BUG: Reindex casting to object in certain situation
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_reindex.py
Labels: Indexing, ExtensionArray

#48078 ENH: Support mask for groupby var and mean
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
Labels: Groupby, NA - MaskedArrays, Reduction Operations

#48370 Backport PR #48265 on branch 1.5.x (CI: Setting up ssh key to upload prod docs)
  .github/workflows/docbuild-and-upload.yml
Labels: Docs, CI

#48372 TST: to_numeric(large_float, downcast=float) isn't lossy
  pandas/tests/tools/test_to_numeric.py
Labels: Testing, Dtype Conversions

#48351 Added test for `assert_index_equal` to check that function raises an exception if two different types
  pandas/tests/util/test_assert_index_equal.py
Labels: Testing, Missing-data

#48376 DOC: how to_datetime %S differs from strptime
  pandas/core/tools/datetimes.py
Labels: Docs

#48239 TYP: Remove use of deprecated mypy option
  pyproject.toml
Labels: Typing

#48281 DOC: Add none as a default argument for orient
  pandas/io/json/_json.py
Labels: Docs, IO JSON

#48381 CI: Pin mambaforge image
  Dockerfile
Labels: CI

#48401 Backport PR #48381 on branch 1.5.x (CI: Pin mambaforge image)
  Dockerfile
Labels: CI

#48229 TST: Test Nullable int floordiv by 0
  doc/source/whatsnew/v1.5.0.rst
  pandas/tests/arrays/integer/test_arithmetic.py
Labels: Testing, Numeric Operations, NA - MaskedArrays

#48298 The indexes of DataFrame.describe(percentiles=[0.29, 0.57, 0.58]) are incorrect
  doc/source/whatsnew/v1.6.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Algos

#48389 TST: add tests for parser functions being pickle-able.
  pandas/tests/io/test_common.py
Labels: Testing, IO Data

#48414 DOC: Add deprecation to is_categorical
  pandas/core/dtypes/common.py
Labels: Docs, Deprecate

#48412 BUG: safe_sort losing MultiIndex dtypes
  pandas/core/algorithms.py
  pandas/tests/test_sorting.py
Labels: Dtype Conversions, MultiIndex

#48387 ENH: Suppport masks in median groupby algo
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
Labels: Groupby, NA - MaskedArrays

#48386 CLN/DOC: Adjust xpath validation and error messaging in read_xml with IO tools doc note and example
  doc/source/user_guide/io.rst
  pandas/io/xml.py
  pandas/tests/io/xml/test_xml.py
Labels: Docs, Clean, IO XML

#48383 TYP: contextmanager expects a Generator
  pandas/_config/config.py
  pandas/_config/localization.py
  pandas/_testing/_warnings.py
  pandas/_testing/contexts.py
  pandas/compat/pickle_compat.py
  pandas/core/common.py
  pandas/core/groupby/groupby.py
  pandas/io/formats/format.py
  pandas/io/formats/style.py
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_misc.py
  pandas/tests/io/pytables/common.py
  pandas/tests/libs/test_hashtable.py
  pandas/tests/test_register_accessor.py
  pandas/util/_exceptions.py
  pandas/util/_test_decorators.py
Labels: Typing

#48377 DOC: More types for groupby's by argument
  pandas/core/shared_docs.py
Labels: Docs, Groupby

#48364 Upgrade codespell version and fix misspelled words
  .pre-commit-config.yaml
  pandas/core/resample.py
  pandas/io/formats/style.py
  pandas/io/parsers/python_parser.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/config/test_config.py
  setup.cfg
Labels: Code Style

#48264 BUG: ArrowExtensionArray._from_* accepts pyarrow arrays
  pandas/core/arrays/arrow/array.py
  pandas/core/tools/times.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/tools/test_to_time.py
Labels: Testing, Constructors, Arrow

#48413 Backport PR #48229 on branch 1.5.x (TST: Test Nullable int floordiv by 0)
  doc/source/whatsnew/v1.5.0.rst
  pandas/tests/arrays/integer/test_arithmetic.py
Labels: Testing, Numeric Operations, NA - MaskedArrays

#48418 Backport PR #48414 on branch 1.5.x (DOC: Add deprecation to is_categorical)
  pandas/core/dtypes/common.py
Labels: Docs, Deprecate

#48411 REGR: get_loc for ExtensionEngine not returning bool indexer for na
  pandas/_libs/index.pyx
  pandas/tests/indexes/test_indexing.py
Labels: Indexing

#48422 Backport PR #48264 on branch 1.5.x (BUG: ArrowExtensionArray._from_* accepts pyarrow arrays)
  pandas/core/arrays/arrow/array.py
  pandas/core/tools/times.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/tools/test_to_time.py
Labels: Testing, Constructors, Arrow

#48430 Backport PR #48411 on branch 1.5.x (REGR: get_loc for ExtensionEngine not returning bool indexer for na)
  pandas/_libs/index.pyx
  pandas/tests/indexes/test_indexing.py
Labels: Indexing

#48419 BUG: ensure to return writable buffer in __dataframe__ interchange for categorical column
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#48378 BUG: masked mean unnecessarily overflowing
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/array_algos/masked_reductions.py
  pandas/core/arrays/masked.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/reductions/test_reductions.py
Labels: NA - MaskedArrays, Reduction Operations

#48290 CLN, STYLE: remove unused variables and imports in Cython files
  .pre-commit-config.yaml
  pandas/_libs/algos.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/hashing.pyx
  pandas/_libs/hashtable.pyx
  pandas/_libs/index.pyx
  pandas/_libs/internals.pyx
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/sparse.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/_libs/tslibs/vectorized.pyx
Labels: Code Style, Clean

#48380 DOC: Clarify that objects dtype takes precedence in where
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
Labels: Docs

#48444 CI: Pin ipython version
  doc/source/user_guide/timeseries.rst
Labels: Docs, CI

#48427 BLD: Refactor Dockerfile to not install dev enviornment on base
  .github/workflows/code-checks.yml
  Dockerfile
  doc/source/development/contributing_environment.rst
  doc/source/whatsnew/v1.5.0.rst
Labels: Build

#48441 Backport PR #48419 on branch 1.5.x (BUG: ensure to return writable buffer in __dataframe__ interchange for categorical column)
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#48354 CI: Bump timeout to 180 minutes
  .github/workflows/macos-windows.yml
  .github/workflows/ubuntu.yml
Labels: CI

#48449 Backport PR #48444 on branch 1.5.x (CI: Pin ipython version)
  doc/source/user_guide/timeseries.rst
Labels: Docs, CI

#48445 Backport PR #48380 on branch 1.5.x (DOC: Clarify that objects dtype takes precedence in where)
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
Labels: Docs

#48452 DOC: Fix typo
  pandas/core/generic.py
Labels: Docs

#48426 BUG: Column.size should be a method
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
  pandas/tests/interchange/test_spec_conformance.py
Labels: Interchange

#46405 BUG: Fixed Unicode decoding error in `Period.strftime` when a locale-specific directive is used
  .github/workflows/ubuntu.yml
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/util.pxd
  pandas/tests/io/formats/test_format.py
Labels: Unicode, Period

#48465 Backport PR #48426 on branch 1.5.x (BUG: Column.size should be a method)
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
  pandas/tests/interchange/test_spec_conformance.py
Labels: Interchange

#48416 REF: ensure to apply suffixes before concat step in merge code
  pandas/core/reshape/merge.py
Labels: Reshaping

#48468 Revert FutureWarning check
  pandas/tests/frame/methods/test_update.py
Labels: Testing, Warnings

#48467 DOC: complete documentation for pd.get_dummies (#48466)
  pandas/core/reshape/encoding.py
Labels: Docs

#48420 Backport PR #48398 on branch 1.5.x (WARN: Avoid FutureWarnings in tests)
  pandas/tests/frame/methods/test_fillna.py
Labels: Warnings

#48470 Backport PR #48416 on branch 1.5.x (REF: ensure to apply suffixes before concat step in merge code)
  pandas/core/reshape/merge.py
Labels: Reshaping

#48474 Backport PR #48354 on branch 1.5.x (CI: Bump timeout to 180 minutes)
  .github/workflows/macos-windows.yml
  .github/workflows/ubuntu.yml
Labels: CI

#48464 BUG: merge with CategoricalIndex for left_on/right_on
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Reshaping, Categorical

#48485 DOC: A blank line is needed at the beginning of list.
  pandas/core/frame.py
Labels: Docs

#48472 PERF: keep using ObjectEngine for ExtensionArrays for 1.5
  pandas/core/indexes/base.py
Labels: Index, NA - MaskedArrays

#48456 TYP: remove mypy ignores from io/formats/printing.py
  pandas/io/formats/printing.py
Labels: Typing

#48437 DOC: Improve docs for plotting
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_misc.py
Labels: Docs, Visualization

#48338 PERF: Performance improvement value_counts for masked arrays
  asv_bench/benchmarks/array.py
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/arrays/masked.py
  pandas/core/arrays/numeric.py
Labels: Performance, Algos, Series, Constructors, NA - MaskedArrays

#48486 Backport PR #48472 on branch 1.5.x (PERF: keep using ObjectEngine for ExtensionArrays for 1.5)
  pandas/core/indexes/base.py
Labels: Index, NA - MaskedArrays

#48443 BUG: Fix pyarrow groupby tests
  pandas/core/series.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Groupby, Arrow

#48493 CI: Fix failing tests
  pandas/tests/extension/test_arrow.py
Labels: Testing, Groupby, CI, ExtensionArray

#48473 REGR: .describe on unsigned dtypes results in object
  pandas/conftest.py
  pandas/core/describe.py
  pandas/tests/series/methods/test_describe.py
Labels: Bug, Dtype Conversions, Regression

#48501 Backport PR #48473 on branch 1.5.x (REGR: .describe on unsigned dtypes results in object)
  pandas/conftest.py
  pandas/core/describe.py
  pandas/tests/series/methods/test_describe.py
Labels: Bug, Dtype Conversions, Regression

#48390 ENH: raise_assert_detail shows the difference between the columns
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/testing.pyx
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_frame_equal.py
Labels: Testing

#48484 BUG: fix valueError for groupby with empty inputs when sample method is called
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_sample.py
Labels: Bug, Groupby

#48490 CI: Use -j1 for python-dev build to avoid flaky build error
  .github/workflows/python-dev.yml
Labels: CI

#48496 ENH: Support mask properly in GroupBy.quantile
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_quantile.py
Labels: Groupby, NA - MaskedArrays

#48498 BUG: MultiIndex.union losing extension array dtype
  doc/source/whatsnew/v1.6.0.rst
  pandas/conftest.py
  pandas/core/algorithms.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_setops.py
Labels: MultiIndex, NA - MaskedArrays

#48491 WEB: Update Python for Data Analysis book
  web/pandas/getting_started.md
  web/pandas/index.html
  web/pandas/static/img/pydata_book.gif
Labels: Web

#48385 CLN: assorted
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals/concat.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/plotting/test_series.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Clean

#48333 BUG: make Series handle dtype='int64' for string array
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/series/test_constructors.py
Labels: Dtype Conversions, Strings

#48293 BUG: DataFrame.pivot not respecting None as column name
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/frame.py
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_pivot_multilevel.py
Labels: Reshaping

#48517 Backport PR #48490 on branch 1.5.x (CI: Use -j1 for python-dev build to avoid flaky build error)
  .github/workflows/python-dev.yml
Labels: CI

#48428 BUG/TST: fix a bunch of arraymanager+pyarrow tests
  pandas/core/internals/array_manager.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48502 SAS7BDAT parser: Speed up blank_missing
  doc/source/whatsnew/v1.6.0.rst
  pandas/io/sas/sas.pyx
  pandas/io/sas/sas7bdat.py
Labels: Performance, IO SAS

#48150 ENH: Support mask in duplicated algorithm
  asv_bench/benchmarks/algorithms.py
  pandas/_libs/hashtable.pyi
  pandas/_libs/hashtable_func_helper.pxi.in
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_duplicated.py
Labels: Algos, duplicated, NA - MaskedArrays

#48497 Bug: raise TypeError when doing infer_freq using RangeIndex
  doc/source/whatsnew/v1.6.0.rst
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tseries/frequencies.py
Labels: Frequency

#48525 CI: Fix py311 builds different exception message
  pandas/tests/dtypes/test_concat.py
Labels: CI, Dependencies

#48520 change test such that it passes in headless mode (instead of xpass)
  pandas/tests/io/test_clipboard.py
Labels: Testing, IO Data

#48379 PERF: Add var to masked arrays
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/array_algos/masked_reductions.py
  pandas/core/arrays/masked.py
  pandas/tests/reductions/test_reductions.py
Labels: NA - MaskedArrays, Reduction Operations

#48429 ENH: Add index param to df.to_dict
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_to_dict.py
Labels: DataFrame

#48518 Manual Backport PR #48428 on branch 1.5.x (BUG/TST: fix a bunch of arraymanager+pyarrow tests)
  pandas/core/internals/array_manager.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48505 ENH: Keep dtypes in MultiIndex.union without NAs
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_setops.py
Labels: Performance, MultiIndex, NA - MaskedArrays

#48529 Backport PR #48525 on branch 1.5.x (CI: Fix py311 builds different exception message)
  pandas/tests/dtypes/test_concat.py
Labels: CI, Dependencies

#48489 BUG: fix test_arrow.py tests
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/internals/concat.py
  pandas/core/reshape/merge.py
  pandas/io/formats/format.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48532 Backport PR #48489 on branch 1.5.x (BUG: fix test_arrow.py tests)
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/internals/concat.py
  pandas/core/reshape/merge.py
  pandas/io/formats/format.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48455 DOC: Add missing API item to reference docs
  doc/source/reference/arrays.rst
  doc/source/reference/general_functions.rst
  doc/source/reference/groupby.rst
  doc/source/reference/options.rst
  pandas/core/groupby/generic.py
  pandas/io/formats/format.py
Labels: Docs

#48511 BUG: Fix bug in pd.eval when UnaryOp in function
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/computation/expr.py
  pandas/tests/computation/test_eval.py
Labels: expressions

#48531 CI/TST: Remove --color=yes for more consistent log output
  pyproject.toml
Labels: Testing, CI

#48446 BUG: Index.equals raising with index of tuples that contain NA
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/lib.pyx
  pandas/_libs/missing.pxd
  pandas/_libs/missing.pyx
  pandas/tests/dtypes/test_missing.py
Labels: Missing-data, NA - MaskedArrays

#48548 Backport PR #48543 on branch 1.5.x (DOC: Update footer and include OVH)
  doc/source/conf.py
Labels: Docs

#48384 PERF: avoid unnecessary reordering in MultiIndex._reorder_indexer
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_indexing.py
Labels: Performance, MultiIndex

#48417 Revert set_index inplace and copy keyword changes
  doc/source/user_guide/indexing.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/frame.py
  pandas/core/reshape/merge.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_function.py
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexing/multiindex/test_indexing_slow.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/test_sql.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/window/test_rolling.py
Labels: Deprecate, Copy / view semantics

#48550 TST: remove 2D tests irrelevant for pyarrow
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48552 Manual Backport PR #48417 on branch 1.5.x (Revert set_index inplace and copy keyword changes)
  doc/source/user_guide/indexing.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/frame.py
  pandas/core/reshape/merge.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/pytables.py
  pandas/io/sql.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_function.py
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexing/multiindex/test_indexing_slow.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/test_sql.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/window/test_rolling.py
Labels: Copy / view semantics

#48554 Backport PR #48550 on branch 1.5.x (TST: remove 2D tests irrelevant for pyarrow)
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#48556 DOC: Fix docs footer
  doc/_templates/pandas_footer.html
  doc/source/conf.py
Labels: Docs

#48339 REF: de-duplicate take_nd
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
Labels: Refactor, Internals

#48558 Backport PR #48556 on branch 1.5.x (DOC: Fix docs footer)
  doc/_templates/pandas_footer.html
  doc/source/conf.py
Labels: Docs

#48563 DOC: Fix read_sas 1.5 release notes
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#48565 Backport PR #48563 on branch 1.5.x (DOC: Fix read_sas 1.5 release notes)
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#48541 Added test case to lock in behaviour
  doc/source/whatsnew/v1.6.0.rst
  pandas/tests/reshape/concat/test_empty.py
Labels: Testing, Reshaping, NA - MaskedArrays

#48539 REGR: groupby doesn't identify null values when sort=False
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/algorithms.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/test_algos.py
Labels: Bug, Groupby, Missing-data, Regression, Algos

#48555 DEPR: Series.astype(np.datetime64)
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/tests/series/methods/test_astype.py
Labels: Timeseries, Dtype Conversions, Deprecate

#48557 WEB: Add new footer to web
  web/pandas/_templates/layout.html
  web/pandas/config.yml
  web/pandas_web.py
Labels: Web

#48568 Backport PR #48539 on branch 1.5.x (REGR: groupby doesn't identify null values when sort=False)
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/algorithms.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/test_algos.py
Labels: Bug, Groupby, Missing-data, Regression, Algos

#48569 Backport PR #48555 on branch 1.5.x (DEPR: Series.astype(np.datetime64))
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/tests/series/methods/test_astype.py
Labels: Timeseries, Dtype Conversions, Deprecate

#48571 Backport PR #48557 on branch 1.5.x (WEB: Add new footer to web)
  web/pandas/_templates/layout.html
  web/pandas/config.yml
  web/pandas_web.py
Labels: Web

#48500 DOC: Add SeriesGroupBy and DataFrameGroupBy reference pages
  doc/source/reference/groupby.rst
  doc/source/user_guide/10min.rst
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v1.0.0.rst
  doc/source/whatsnew/v1.0.1.rst
  doc/source/whatsnew/v1.0.2.rst
  doc/source/whatsnew/v1.0.4.rst
  doc/source/whatsnew/v1.1.0.rst
  doc/source/whatsnew/v1.1.4.rst
  doc/source/whatsnew/v1.1.5.rst
  doc/source/whatsnew/v1.2.0.rst
  doc/source/whatsnew/v1.2.1.rst
  doc/source/whatsnew/v1.3.0.rst
  doc/source/whatsnew/v1.3.3.rst
  doc/source/whatsnew/v1.3.4.rst
  doc/source/whatsnew/v1.3.5.rst
  doc/source/whatsnew/v1.4.0.rst
  doc/source/whatsnew/v1.5.0.rst
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  scripts/validate_rst_title_capitalization.py
Labels: Enhancement, Docs, Groupby

#48397 WARN: Remove false positive warning for iloc inplaceness
  pandas/_testing/__init__.py
  pandas/core/dtypes/cast.py
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/test_nonunique_indexes.py
Labels: Warnings, Copy / view semantics

#48572 DOC: Fixing styles for the dark theme
  doc/source/_static/css/getting_started.css
  doc/source/_static/css/pandas.css
Labels: Docs

#48285 WEB: Unpin pydata sphinx theme
  doc/_templates/sidebar-nav-bs.html
  doc/source/conf.py
  environment.yml
  requirements-dev.txt
  web/pandas/versions.json
Labels: Dependencies, Web

#48585 Backport PR #48285 on branch 1.5.x (WEB: Unpin pydata sphinx theme)
  doc/_templates/sidebar-nav-bs.html
  doc/source/conf.py
  environment.yml
  requirements-dev.txt
  web/pandas/versions.json
Labels: Dependencies, Web

#48584 Backport PR #48572 on branch 1.5.x (DOC: Fixing styles for the dark theme)
  doc/source/_static/css/getting_started.css
  doc/source/_static/css/pandas.css
Labels: Docs

#48583 Backport PR #48397 on branch 1.5.x (WARN: Remove false positive warning for iloc inplaceness)
  pandas/_testing/__init__.py
  pandas/core/dtypes/cast.py
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/test_nonunique_indexes.py
Labels: Warnings, Copy / view semantics

#48587 Fix `series.str.startswith(tuple)`
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_strings.py
Labels: Strings

#48593 Backport PR #48587 on branch 1.5.x (Fix `series.str.startswith(tuple)`)
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_strings.py
Labels: Strings

#48601 CI: Fix matplolib release issues
  doc/source/user_guide/visualization.rst
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/compat.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/style.py
  pandas/plotting/_misc.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_series.py
Labels: Visualization, CI

#48617 Backport PR #48601 on branch 1.5.x (CI: Fix matplolib release issues)
  doc/source/user_guide/visualization.rst
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/compat.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/style.py
  pandas/plotting/_misc.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_series.py
Labels: Visualization, CI

#48623 REGR/DOC: Docs left navbar broke
  doc/_templates/sidebar-nav-bs.html
Labels: Bug, Docs, Regression

#48625 Backport PR #48623 on branch 1.5.x (REGR/DOC: Docs left navbar broke)
  doc/_templates/sidebar-nav-bs.html
Labels: Bug, Docs, Regression

#48619 REGR: Loc.setitem with enlargement raises for nested data
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Indexing, Regression, Nested Data

#48627 DOC: Last changes to release notes for 1.5.0 release
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#48629 Backport PR #48619 on branch 1.5.x (REGR: Loc.setitem with enlargement raises for nested data)
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Indexing, Regression, Nested Data

#48630 Backport PR #48627 on branch 1.5.x (DOC: Last changes to release notes for 1.5.0 release)
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#48600 DOC: Fix version switcher in old docs
  web/pandas/versions.json
Labels: Docs

#48642 DOC: Add release notes for 1.5.1
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.5.1.rst
Labels: Docs

#48639 CI: Fix directory name for published prod docs
  .github/workflows/docbuild-and-upload.yml
Labels: Docs, CI

#48640 BUG: is_datetime64tz_dtype shortcut only for DatetimeTZDtype
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
Labels: Dtype Conversions, Timezones, ExtensionArray

#48628 CI: Get rid of some warnings
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_combine_first.py
Labels: Warnings

#48643 BUG: MultiIndex.set_levels raising when setting empty level
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_get_set.py
Labels: MultiIndex

#48622 PERF: Improve performance for MultiIndex.isin
  asv_bench/benchmarks/multiindex_object.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/multi.py
Labels: Performance, MultiIndex

#48607 BUG: MultiIndex.symmetric_difference not keeping ea dtype
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_setops.py
Labels: MultiIndex, NA - MaskedArrays

#48592 CLN: MultiIndex.drop_duplicates
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_duplicates.py
Labels: MultiIndex, Clean

#48604 ENH: MultiIndex.intersection now keeping EA dtypes
  asv_bench/benchmarks/index_object.py
  asv_bench/benchmarks/multiindex_object.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_setops.py
Labels: MultiIndex, NA - MaskedArrays

#48590 TYP: reshape.merge
  pandas/core/reshape/merge.py
Labels: Reshaping, Typing

#48551 ENH: added finalize to binary operators on DataFrame, GH28283
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/frame.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/generic/test_finalize.py
Labels: Numeric Operations, metadata

#48504 PERF: merge on sorted MultiIndex
  asv_bench/benchmarks/join_merge.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/indexes/base.py
Labels: Performance, Reshaping, MultiIndex

#48403 ENH: Add use_nullable_dtypes in csv internals
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/test_upcast.py
Labels: IO CSV, NA - MaskedArrays

#48138 ENH: Support mask in groupby cumprod
  doc/source/whatsnew/v1.6.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_libgroupby.py
Labels: Groupby, NA - MaskedArrays

#48050 ENH: allow user to infer SAS file encoding; add correct encoding names
  doc/source/whatsnew/v1.6.0.rst
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_constants.py
  pandas/tests/io/sas/test_sas7bdat.py
Labels: IO SAS

#48609 PERF: DatetimeIndex constructor from list
  asv_bench/benchmarks/ctors.py
  doc/source/whatsnew/v1.6.0.rst
  pandas/core/arrays/datetimelike.py
Labels: Timeseries, Performance
