Repository pandas-dev/pandas, pull requests merged in 2022-05, with the labels that each got.

#46917 REF: stronger typing in _box_func
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/nanops.py
  pandas/tests/arrays/timedeltas/test_reductions.py
  pandas/tests/test_nanops.py
Labels: Refactor, Non-Nano

#46912 CI: More targeted pyarrow version testing
  .github/workflows/posix.yml
Labels: CI, Arrow

#46774 ENH: Create ArrowDtype
  pandas/core/arrays/arrow/dtype.py
Labels: Arrow

#46926 CLN: tzconversion
  pandas/_libs/tslibs/tzconversion.pxd
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Timezones, Clean

#46925 Backport PR #46912 on branch 1.4.x (CI: More targeted pyarrow version testing)
  .github/workflows/posix.yml
Labels: CI, Arrow

#46930 DataFrame.replace with dict doesn't work when value=None
  pandas/core/shared_docs.py
Labels: Docs

#46921 STYL: a few cleanups in pyi files
  pandas/_libs/hashtable.pyi
  pandas/_libs/tslibs/conversion.pyi
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/conftest.py
  pyproject.toml
Labels: Typing

#46932 ENH: support mask in libalgos.rank
  pandas/_libs/algos.pyi
  pandas/_libs/algos.pyx
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_rank.py
Labels: Algos, NA - MaskedArrays

#46730 BUG: to_json incorrectly localizes tz-naive datetimes to UTC
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/src/ujson/python/date_conversions.c
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/tslibs/src/datetime/np_datetime.c
  pandas/_libs/tslibs/src/datetime/np_datetime.h
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.c
  pandas/_libs/tslibs/src/datetime/np_datetime_strings.h
  pandas/core/internals/blocks.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_json_table_schema_ext_dtype.py
  pandas/tests/io/json/test_pandas.py
Labels: Bug, IO JSON

#46931 DOC: added index, dropna description for HDF methods #45030
  pandas/core/generic.py
  pandas/io/pytables.py
Labels: Docs, IO HDF5

#46906 DEPR: numeric_only default in DataFrame methods with None/True
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/resample/test_resample_api.py
Labels: Deprecate

#46902 ENH: fields.get_start_end_field support non-nano
  asv_bench/benchmarks/tslibs/fields.py
  pandas/_libs/tslibs/fields.pyi
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/tslibs/test_fields.py
  setup.py
Labels: Non-Nano

#46949 CI/DOC: Fix to_hdf docstring validation
  pandas/core/generic.py
Labels: Docs

#46953 CLN: Remove special case for rank in groupby.ops
  pandas/_libs/groupby.pyx
  pandas/core/groupby/ops.py
Labels: Groupby, Clean

#46265 BUG: fix rolling with centering and axis=1 (#46135)
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_win_type.py
Labels: Window

#46901 ENH: allow non-nano in DatetimeArray, TimedeltaArray._simple_new
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/tslibs/test_api.py
  pandas/tests/tslibs/test_np_datetime.py
Labels: Non-Nano

#46928 TYP: resolve ignored mypy errors in core/describe.py
  pandas/core/describe.py
  pandas/io/formats/format.py
Labels: Typing

#46518 TYP: Index.join
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexes/base.py
Labels: Deprecate, Typing

#46943 PERF: Remove unnecessary(?) asof join functions
  pandas/_libs/join.pyx
  pandas/core/reshape/merge.py
Labels: Performance, Reshaping

#46886 REF: handle 2D in tslibs.vectorized
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/vectorized.pyi
  pandas/_libs/tslibs/vectorized.pyx
Labels: Refactor, Timeseries

#46957 DOC: fix cookbook groupby & transform example
  doc/source/user_guide/cookbook.rst
Labels: Docs

#46959 ENH: Timestamp.month_name, day_name support non-nano
  asv_bench/benchmarks/tslibs/fields.py
  pandas/_libs/tslibs/fields.pyi
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/tslibs/test_fields.py
Labels: Enhancement, Non-Nano

#46914 TYP: fix type annotation in _has_externally_shared_axis
  pandas/plotting/_matplotlib/tools.py
Labels: Typing

#46698 TYP: Make temporary variables in pandas/__init__.py private
  pandas/__init__.py
Labels: Typing

#46638 TYP: tighten return type in function any
  pandas/core/frame.py
  pandas/core/series.py
Labels: Typing

#44787 ENH: add support for reading .tar archives
  doc/source/whatsnew/v1.5.0.rst
  pandas/_testing/_io.py
  pandas/_typing.py
  pandas/conftest.py
  pandas/core/shared_docs.py
  pandas/io/common.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/parser/test_compression.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_stata.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/io/xml/test_xml.py
Labels: Enhancement, IO Data

#46963 Fix link to be *true* raw data
  doc/source/getting_started/intro_tutorials/includes/titanic.rst
Labels: Docs

#46960 CI: Move Windows build from Azure to GHA
  .github/actions/build_pandas/action.yml
  .github/workflows/posix.yml
  .github/workflows/windows.yml
  azure-pipelines.yml
  ci/azure/windows.yml
Labels: CI, Windows

#46967 CLN: mmap used by only read_csv
  pandas/io/common.py
  pandas/tests/io/test_common.py
Labels: IO CSV

#46966 TYP: overload asarray_tuplesafe signature
  pandas/core/common.py
  pandas/core/indexes/base.py
Labels: Typing

#46969 TYP: enable reportOverlappingOverload
  .github/workflows/code-checks.yml
  .pre-commit-config.yaml
  pandas/_libs/interval.pyi
  pyproject.toml
Labels: Typing

#46282 BUG: MaskedArray._quantile match non-nullable behavior
  pandas/core/array_algos/quantile.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/series/methods/test_quantile.py
Labels: Algos, NA - MaskedArrays, Stale

#46973 follow-up to 44787, use pandas compat for platform specifics in added test
  pandas/tests/io/test_compression.py
Labels: Testing

#46971 Backport PR #46960 on branch 1.4.x (CI: Move Windows build from Azure to GHA)
  .github/actions/build_pandas/action.yml
  .github/workflows/posix.yml
  .github/workflows/windows.yml
  azure-pipelines.yml
  ci/azure/windows.yml
Labels: CI, Windows

#46980 TST: avoid chained assignment in tests outside of specific tests on chaining
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/test_loc.py
Labels: Testing

#46991 CI/TST: Fix test for pyarrow 8.0 release
  pandas/compat/pyarrow.py
  pandas/tests/io/test_parquet.py
Labels: Testing, Arrow

#46990 ENH: non-nano Timestamp.timestamp, to_period
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Enhancement, Non-Nano

#46992 Backport PR #46991 on branch 1.4.x (CI/TST: Fix test for pyarrow 8.0 release)
  pandas/compat/pyarrow.py
  pandas/tests/io/test_parquet.py
Labels: Testing, Arrow

#46981 CI: Move MacOS build from Azure to GHA
  .github/workflows/macos-windows.yml
  azure-pipelines.yml
  ci/azure/posix.yml
  ci/setup_env.sh
Labels: CI, OS X

#46717 EHN: add same value count for skew & kurt
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_rolling_skew_kurt.py
Labels: Window

#47019 REF: simplify tzconversion
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/tzconversion.pxd
  pandas/_libs/tslibs/tzconversion.pyi
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/tests/tslibs/test_conversion.py
Labels: Refactor, Timezones

#47020 CI: Move 32 bit Linux build to GHA
  .github/workflows/32-bit-linux.yml
  .github/workflows/python-dev.yml
  README.md
  azure-pipelines.yml
  doc/source/development/contributing_codebase.rst
  pandas/conftest.py
  pandas/tests/io/conftest.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
Labels: CI

#47012 DOC: pyarrow >= 8.0.0 supports timedelta
  doc/source/user_guide/io.rst
Labels: Docs

#47021 MAINT: Fix some typos.
  LICENSES/ULTRAJSON_LICENSE
  asv_bench/benchmarks/sparse.py
  doc/source/user_guide/io.rst
  doc/source/user_guide/style.ipynb
Labels: Docs

#47007 Backport PR #46981 on branch 1.4.x (CI: Move MacOS build from Azure to GHA)
  .github/workflows/macos-windows.yml
  azure-pipelines.yml
  ci/azure/posix.yml
  ci/setup_env.sh
Labels: CI, OS X

#47015 CI: Ensure no-use-pep517 with no-build-isolation with new pip version
  ci/setup_env.sh
Labels: Build, CI

#47029 Backport PR #47020 on branch 1.4.x (CI: Move 32 bit Linux build to GHA)
  .github/workflows/32-bit-linux.yml
  .github/workflows/python-dev.yml
  README.md
  azure-pipelines.yml
  doc/source/development/contributing_codebase.rst
  pandas/conftest.py
  pandas/tests/io/conftest.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
Labels: CI

#47031 Backport PR #47015 on branch 1.4.x (CI: Ensure no-use-pep517 with no-build-isolation with new pip version)
  ci/setup_env.sh
Labels: Build, CI

#46905 TYP/CI: bump mypy&pyright
  .github/workflows/code-checks.yml
  .pre-commit-config.yaml
  doc/source/whatsnew/v1.5.0.rst
  environment.yml
  pandas/_config/localization.py
  pandas/_libs/tslibs/timestamps.pyi
  pandas/core/arrays/masked.py
  pandas/io/parsers/base_parser.py
  requirements-dev.txt
Labels: Typing

#47016 Unpin xarray
  environment.yml
  pandas/core/generic.py
  requirements-dev.txt
Labels: Dependencies

#47033 DOC: Fix a typo in documentation for qyear
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Frequency

#46394 CI: Use conda-forge PyPy
  .github/workflows/posix.yml
  ci/deps/actions-pypy-38.yaml
Labels: CI

#47040 Backport PR #46394 on branch 1.4.x (CI: Use conda-forge PyPy)
  .github/workflows/posix.yml
  ci/deps/actions-pypy-38.yaml
Labels: CI

#47038 REF: share parts of DTI and PI
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/period.py
Labels: Refactor, Timeseries, Period

#47036 REF: write indexing checks in terms of should_fallback_to_positional
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/core/indexing.py
Labels: Refactor, Indexing

#47044 ENH: DatetimeArray fields support non-nano
  pandas/_libs/tslibs/fields.pyi
  pandas/_libs/tslibs/fields.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/arrays/test_datetimes.py
Labels: Enhancement, Non-Nano

#47025 DEPR: groupby numeric_only default
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/generic/test_frame.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_allowlist.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_index_as_string.py
  pandas/tests/groupby/test_pipe.py
  pandas/tests/groupby/test_quantile.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/test_pivot.py
Labels: Groupby, Deprecate, Nuisance Columns

#47026 DOC: Clarify decay argument validation in ewm when times is provided
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/window/ewm.py
  pandas/tests/window/conftest.py
  pandas/tests/window/test_ewm.py
Labels: Enhancement, Docs, Window

#47059 REGR: Styler `buf` and `encoding` in `to_latex` and `to_html`
  doc/source/whatsnew/v1.4.3.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: Bug, IO HTML

#47049 CI/TST: Lower recurison limit for test_json:test_series_constructor_scalar_with_index on Windows
  pandas/tests/extension/json/test_json.py
Labels: Windows, Unreliable Test

#47048 DEPS: Bump optional dependencies
  ci/deps/actions-38-minimum_versions.yaml
  doc/source/whatsnew/v1.5.0.rst
  pandas/compat/_optional.py
  pandas/tests/io/data/excel/high_surrogate.xlsx
  pandas/tests/io/excel/__init__.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/excel/test_xlrd.py
  pandas/tests/io/formats/style/test_highlight.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Dependencies

#47050 CLN/TST: Remove tm.makeUnicodeIndex
  asv_bench/benchmarks/strings.py
  pandas/_testing/__init__.py
  pandas/_testing/_random.py
  pandas/conftest.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/series/test_api.py
  pandas/tests/tseries/frequencies/test_inference.py
Labels: Testing, Clean

#46903 BUG: DatetimeIndex.resolution with nanosecond reso
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/vectorized.pyx
  pandas/core/indexes/datetimes.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/series/methods/test_asof.py
  pandas/tests/tslibs/test_resolution.py
Labels: Indexing, Timezones, Deprecate

#46994 ENH: do not sort resulting columns when sort=False
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping

#47057 BUG: groupby.transform/agg with engine='numba' and a MultiIndex
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
Labels: Groupby, numba

#47062 Backport PR #47057 on branch 1.4.x (BUG: groupby.transform/agg with engine='numba' and a MultiIndex)
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
Labels: Groupby, MultiIndex

#47065 DOC: Fix deprecation warnings in docs for groupby nuisance columns
  doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
  doc/source/user_guide/10min.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/reshaping.rst
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.18.1.rst
  doc/source/whatsnew/v0.19.0.rst
Labels: Docs, Groupby, Deprecate, Nuisance Columns

#47068 CLN: Move test_parallel to gil.py
  asv_bench/benchmarks/gil.py
  pandas/_testing/__init__.py
Labels: Clean, Benchmark

#47083 DOC: Ignore certain doctest warnings
  pandas/conftest.py
  pyproject.toml
Labels: Docs, Warnings

#47080 DOC: Fix assorted doc warnings
  doc/source/conf.py
  pandas/core/arrays/sparse/array.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
Labels: Docs

#47078 REGR: Raise NotImplementedError for agg with axis=1 and multiple funcs
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/window/test_api.py
Labels: Bug, Groupby, Regression, Resample, Apply, Window

#47018 REF: merge datetime_to_datetime64 into array_to_datetime
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyi
  pandas/_libs/tslibs/conversion.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Refactor, Timeseries

#47072 Backport PR #47059 on branch 1.4.x (REGR: Styler buf and encoding in to_latex and to_html)
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_style.py
Labels: IO HTML

#47047 ENH: move DataError from core/base.py to error/__init__.py per GH27656
  doc/source/reference/testing.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/apply.py
  pandas/core/base.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/core/window/rolling.py
  pandas/errors/__init__.py
  pandas/tests/test_errors.py
  pandas/tests/window/test_dtypes.py
Labels: Error Reporting

#46162 Bug fix - GroupBy.describe produces inconsistent results for empty datasets
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_function.py
Labels: Groupby, Reshaping

#47064 TYP: resolve mypy ignores in core/groupby/ops.py
  pandas/core/groupby/ops.py
Labels: Typing

#46919 TYP: fix MultiIndex._names type
  pandas/core/frame.py
  pandas/core/indexes/multi.py
Labels: Typing

#47077 REF: Manager.fast_xs to return SingleBlockManager instead of array
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Internals

#47086 Backport PR #47078 on branch 1.4.x (REGR: Raise NotImplementedError for agg with axis=1 and multiple funcs)
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/window/test_api.py
Labels: Bug, Groupby, Regression, Resample, Apply, Window

#47076 ENH: liboffsets support non-nano
  asv_bench/benchmarks/arithmetic.py
  asv_bench/benchmarks/tslibs/normalize.py
  asv_bench/benchmarks/tslibs/offsets.py
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/vectorized.pyi
  pandas/_libs/tslibs/vectorized.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/tools/datetimes.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/tseries/offsets/test_offsets.py
  setup.py
Labels: Non-Nano

#47075 CI: mypy&pyright in manual pre-commit stage
  .github/workflows/code-checks.yml
  .pre-commit-config.yaml
  ci/code_checks.sh
  doc/source/development/contributing_codebase.rst
  environment.yml
  requirements-dev.txt
Labels: CI, Typing

#45333 DEPR: df.iloc[:, foo] = bar attempt to set inplace
  doc/source/user_guide/10min.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/indexing.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/frame/indexing/test_coercion.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/methods/test_dropna.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/methods/test_shift.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/test_stata.py
Labels: Indexing, Deprecate, API - Consistency

#47104 BUG Fix: Cannot read pickle generate_legacy_storage_files version 1.4.2 under environment pandas version 1.5.0 (incompatibilites issue)
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/io/data/legacy_pickle/1.4.2/1.4.2_x86_64_linux_3.9.7.pickle
Labels: IO Pickle, Non-Nano

#47119 Changes as requested in #47058
  pandas/core/generic.py
Labels: Docs

#47070 TST: add copy/view test for setting columns with an array/series
  pandas/conftest.py
  pandas/tests/copy_view/test_setitem.py
Labels: Testing, Indexing, Copy / view semantics

#47045 TYP: Mypy workaround for NoDefault
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/_testing/asserters.py
  pandas/_typing.py
  pandas/core/arrays/interval.py
  pandas/core/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/reshape/tile.py
  pandas/core/series.py
Labels: Typing

#46942 TYP: narrow type bounds on extract_array
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/construction.py
  pandas/core/internals/construction.py
  pandas/io/formats/format.py
  pandas/io/pytables.py
Labels: Typing

#46636 REGR: Replace changes the dtype of other columns
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_replace.py
Labels: Regression, replace

#47010 TYP: resolve mypy ingores in core/indexing.py
  pandas/core/indexing.py
Labels: Typing

#46786 TYP: CallableDynamicDoc
  pandas/_config/config.py
  pandas/_libs/indexing.pyi
  pandas/_libs/json.pyi
  pandas/_libs/reduction.pyi
  pandas/core/indexing.py
  pandas/io/sas/_sas.pyi
Labels: Typing

#47123 Backport PR #46636 on branch 1.4.x (REGR: Replace changes the dtype of other columns)
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_replace.py
Labels: Regression, replace

#47089 ENH: move SpecificationError to error/__init__.py
  doc/source/reference/testing.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/apply.py
  pandas/core/base.py
  pandas/core/groupby/generic.py
  pandas/errors/__init__.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/test_errors.py
  pandas/tests/window/test_api.py
Labels: Enhancement, Error Reporting

#47082 BUG: Fix `set_sticky` background
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_html.py
Labels: Styler

#47126 infer_freq handle non-nano
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/fields.pyi
  pandas/_libs/tslibs/fields.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tests/tslibs/test_api.py
  pandas/tseries/frequencies.py
Labels: Enhancement, Non-Nano

#47131 Fix typo in tz_convert docs
  pandas/core/generic.py
Labels: Docs, Timezones

#47122 sync "inplace" document strings anywhere possible
  pandas/core/frame.py
Labels: Docs

#47135 CLN: ensure clean up styler tests
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#47133 Remove ctime.pyx
  pandas/_libs/tslibs/ctime.pyx
  pandas/tests/tslibs/test_api.py
  pandas/tests/tslibs/test_ctime.py
  setup.py
Labels: Timezones, Clean

#47093 DOC/CI: Use more explicit data setup in user guides
  doc/data/fx_prices
  doc/data/mindex_ex.csv
  doc/data/test.xls
  doc/source/user_guide/io.rst
  doc/source/user_guide/scale.rst
  doc/source/whatsnew/v0.9.1.rst
  pandas/tests/util/test_show_versions.py
Labels: Docs, CI

#47107 BUG: Resampler attempts to aggregate the `on` column
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Bug, Resample, Reduction Operations

#47139 REGR: index_col False and header=None inferring index names in some cases
  doc/source/whatsnew/v1.4.3.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/test_python_parser_only.py
Labels: Regression, IO CSV

#47141 Backport PR #47135 on branch 1.4.x (CLN: ensure clean up styler tests)
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#47142 Backport PR #47139 on branch 1.4.x (REGR: index_col False and header=None inferring index names in some cases)
  doc/source/whatsnew/v1.4.3.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/test_python_parser_only.py
Labels: Regression, IO CSV

#47144 Backport PR #47093 on branch 1.4.x (DOC/CI: Use more explicit data setup in user guides)
  doc/data/fx_prices
  doc/data/mindex_ex.csv
  doc/data/test.xls
  doc/source/user_guide/io.rst
  doc/source/user_guide/scale.rst
  doc/source/whatsnew/v0.9.1.rst
  pandas/tests/util/test_show_versions.py
Labels: Docs, CI

#47145 Add note about different series lengths to Series.corr and Series.cov docs
  pandas/core/series.py
Labels: Docs

#47109 make series axis parameter docs consistent
  pandas/core/arrays/datetimes.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/ops/docstrings.py
  pandas/core/series.py
  pandas/core/shared_docs.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Docs

#47150 DEPS: Bump Cython
  ci/deps/actions-310.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-38.yaml
  ci/deps/circle-38-arm64.yaml
  doc/source/whatsnew/v1.4.3.rst
  environment.yml
  requirements-dev.txt
  setup.py
Labels: CI, Dependencies

#47151 ENH: Move SettingWithCopyError to error/__init__.py per GH27656
  doc/source/reference/testing.rst
  doc/source/user_guide/indexing.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/common.py
  pandas/core/generic.py
  pandas/errors/__init__.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/test_errors.py
Labels: Enhancement, Error Reporting

#47152 Backport PR #47150 on branch 1.4.x (DEPS: Bump Cython)
  ci/deps/actions-310-numpydev.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-38.yaml
  ci/deps/circle-38-arm64.yaml
  doc/source/whatsnew/v1.4.3.rst
  environment.yml
  requirements-dev.txt
  setup.py
Labels: CI, Dependencies

#47051 BUG: `DataFrame.shift` shows different behavior for `axis=1` when `freq` is specified
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_shift.py
Labels: Timeseries, Regression

#47158 Backport PR #47051 on branch 1.4.x (BUG: `DataFrame.shift` shows different behavior for `axis=1` when `freq` is specified)
  doc/source/whatsnew/v1.4.3.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_shift.py
Labels: Timeseries, Regression

#47140 TYP: Upgrade mypy to 0.960
  doc/source/whatsnew/v1.5.0.rst
  environment.yml
  requirements-dev.txt
Labels: Typing

#47159 TST: Re-enable test after Cython upgrade
  pandas/tests/io/parser/common/test_common_basic.py
Labels: Testing

#47161 Backport PR #47159 on branch 1.4.x (TST: Re-enable test after Cython upgrade)
  pandas/tests/io/parser/common/test_common_basic.py
Labels: Testing

#47091 Bug Fix: pd.DataFrame.sum with min_count changes dtype if result contains NaNs
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/nanops.py
  pandas/tests/frame/test_reductions.py
Labels: Bug, Dtype Conversions, Reduction Operations

#47066 TYP: resolve mypy ignores in core/apply.py
  pandas/core/apply.py
Labels: Apply, Typing

#47153 CLN: Share code between _BytesTarFile and _BytesZipFile
  pandas/io/common.py
  pandas/tests/io/test_compression.py
Labels: Refactor, IO Data, Clean

#47175 CLN: Simplify mmap code
  pandas/io/common.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/tests/io/test_common.py
Labels: Refactor, IO CSV

#47165 BUG: do not suppress errors when closing file handles
  doc/source/whatsnew/v1.4.3.rst
  pandas/io/common.py
  pandas/tests/io/test_common.py
Labels: IO Data, Error Reporting

#47170 Test Case: pd.DataFrame.prob with min_count changes dtype if result contains NaNs
  pandas/tests/frame/test_reductions.py
Labels: Testing

#46979 API/TST: add tests for new copy/view behaviour
  pandas/tests/copy_view/__init__.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/copy_view/util.py
Labels: API Design, Copy / view semantics

#47183 [CLN] call __finalize__ in quantile
  pandas/core/frame.py
  pandas/tests/generic/test_finalize.py
Labels: Clean, metadata
