Repository pandas-dev/pandas, pull requests merged in 2022-07, with the labels that each got.

#47555 REF: share some constructor code
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
Labels: Refactor

#47553 REF: Reduce duplicative methods between XML parser classes
  pandas/io/xml.py
Labels: Refactor, IO XML

#47568 [DOC] improving the ExcelWriter docstring
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#47572 Use license_files instead of license_file
  setup.cfg
Labels: Build

#47574 REF: simplify DTA.__init__
  pandas/core/arrays/datetimes.py
  pandas/tests/arrays/datetimes/test_constructors.py
Labels: Refactor, Timeseries

#47573 CLN: Move monotonic check to safe_sort_index
  pandas/core/indexes/api.py
Labels: Clean, Index

#46759 PERF: Some faster date/time string formatting
  asv_bench/benchmarks/io/sql.py
  asv_bench/benchmarks/tslibs/strftime.py
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/io/excel/_odswriter.py
  pandas/io/formats/format.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Performance

#47342 BUG: Series.setitem losing precision when enlarging
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Indexing, Dtype Conversions

#47565 "Backport PR #47508 on branch 1.4.x REGR: concat materializing index even if sort is not necessary )"
  doc/source/whatsnew/v1.4.4.rst
  pandas/core/indexes/api.py
  pandas/tests/reshape/concat/test_index.py
Labels: Reshaping

#47513 "Backport PR #47387 on branch 1.4.x (TST,WARN: read_csv raises warning at wrong stacklevel, but _assert_raised_with_correct_stacklevel doesn't fail )"
  doc/source/whatsnew/v1.4.4.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
Labels: Warnings

#47588 CLN: concat union_indexes now respecting sort keyword
  pandas/core/frame.py
Labels: Clean

#47581 BUG: DataFrame.loc not aligning rhs df for single block case
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/frame.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Bug, Indexing

#47575 Adding testcase for quartile performed on a timestamp column group by ( closes #33168 )
  pandas/tests/groupby/test_quantile.py
Labels: Testing, Groupby, Timezones

#47562 TYP: fix a few errors found by pandas-stub
  pandas/_testing/asserters.py
  pandas/core/generic.py
  pandas/core/indexes/multi.py
  pandas/plotting/_matplotlib/groupby.py
Labels: Typing

#47558 TYP: misc return type annotations
  pandas/__init__.py
  pandas/_config/config.py
  pandas/_testing/__init__.py
  pandas/_testing/_io.py
  pandas/_testing/_random.py
  pandas/_testing/asserters.py
  pandas/_testing/contexts.py
  pandas/compat/__init__.py
  pandas/compat/pickle_compat.py
  pandas/conftest.py
  pandas/io/common.py
  pandas/tests/api/test_api.py
  pandas/tests/util/test_assert_attr_equal.py
  pyright_reportGeneralTypeIssues.json
Labels: Testing, Typing

#47515 ENH/TST: Add BaseGroupbyTests tests for ArrowExtensionArray
  pandas/core/dtypes/missing.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Groupby, Arrow

#47586 BUG: concat losing columns dtypes for join=outer
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexes/api.py
  pandas/tests/reshape/concat/test_index.py
Labels: Bug, Reshaping, Index

#47518 PERF: use c-division in nancorr
  pandas/_libs/algos.pyx
Labels: Performance

#47474 BUG: to_sql with method=callable not returning int raising TypeError
  doc/source/whatsnew/v1.4.4.rst
  pandas/core/generic.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL

#47496 BUG: read_excel not forward filling index columns when no names are given
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/data/excel/multiindex_no_index_names.xlsx
  pandas/tests/io/excel/test_openpyxl.py
Labels: IO Excel

#47590 Backport PR #47474 on branch 1.4.x (BUG: to_sql with method=callable not returning int raising TypeError)
  doc/source/whatsnew/v1.4.4.rst
  pandas/core/generic.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL

#47561 DEPR: numeic_only in Series and SeriesGroupBy consistency
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/series.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/test_function.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/series/test_api.py
Labels: Resample, Deprecate, Series, Nuisance Columns

#47222 BUG Fix: pd.apply returns a dataframe when empty dataframe instead of a series
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/apply.py
  pandas/tests/apply/test_frame_apply.py
Labels: Bug, Apply

#47591 ENH: Move CSSWarning to error/__init__.py per GH27656
  doc/source/reference/testing.rst
  pandas/errors/__init__.py
  pandas/io/formats/css.py
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_to_excel.py
  pandas/tests/test_errors.py
Labels: Warnings

#47583 REF: share DTA/TDA.__init__
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
Labels: Refactor, ExtensionArray

#47595 CI: flake8-pyi
  .pre-commit-config.yaml
  pandas/_libs/index.pyi
  pandas/_libs/interval.pyi
  pandas/_libs/lib.pyi
  pandas/_libs/sparse.pyi
  pandas/_libs/tslibs/conversion.pyi
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/writers.pyi
  setup.cfg
Labels: Typing

#47552 ENH/TST: Add BaseMethodsTests tests for ArrowExtensionArray
  pandas/core/base.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
Labels: Testing, Arrow

#47579 ENH: DTI/DTA.astype support non-nano
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/dtypes.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/astype.py
  pandas/core/dtypes/common.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/tslibs/test_api.py
Labels: Non-Nano

#47559 TST: Test aggregate with list values #25581
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Testing, Groupby, Algos

#47367 Revert inclusive default change of IntervalDtype
  doc/source/reference/arrays.rst
  pandas/_libs/interval.pyi
  pandas/_libs/interval.pyx
  pandas/_libs/intervaltree.pxi.in
  pandas/core/arrays/arrow/_arrow_utils.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/interval.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/indexes/interval/test_constructors.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval_range.py
  pandas/tests/plotting/test_misc.py
Labels: Interval

#47609 DOC: fix shared compression_options and decompression_options
  pandas/core/generic.py
  pandas/core/shared_docs.py
  pandas/io/parsers/readers.py
  pandas/io/sas/sasreader.py
  pandas/io/stata.py
Labels: Docs, IO Data

#47587 TYP: return values in core/*.py
  pandas/core/algorithms.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/core/common.py
  pandas/core/config_init.py
  pandas/core/flags.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/missing.py
  pandas/core/nanops.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/series.py
  pandas/io/formats/format.py
Labels: Typing

#47617 DOC: Fixed pandas capitalization
  RELEASE.md
Labels: Docs

#47616 TST: Added test for strides in column major Dataframes stored in HDFS…
  pandas/tests/io/pytables/test_store.py
Labels: Testing, IO HDF5

#47619 BUG: Return Float64 for read_parquet(use_nullable_dtypes=True)
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: IO Parquet, NA - MaskedArrays

#47621 WARN: Don't show FutureWarning when enlarging df with iloc
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Indexing, Warnings

#47601 ENH/TST: Add TestBaseReshaping tests for ArrowExtensionArray
  pandas/tests/extension/test_arrow.py
Labels: Testing, Reshaping, Arrow

#47630 BUG: using read_xml with iterparse and names will ignore duplicate values
  pandas/io/xml.py
  pandas/tests/io/xml/test_xml.py
Labels: Bug, IO XML

#47631 DOC: avoid overriding Python built-in functions
  doc/source/user_guide/groupby.rst
Labels: Docs

#47638 TST: adding test for multiindex nunique raising not implemnted error
  pandas/tests/indexing/multiindex/test_multiindex.py
Labels: Testing, MultiIndex

#47637 DEPR: Remove deprecation from private class IntervalTree
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_interval_tree.py
Labels: Deprecate, Interval

#47641 POC/ENH: Timedelta min/max/resolution support non-nano
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Timedelta, Non-Nano

#47644 Fixed mypy errors in frequencies.py
  pandas/tseries/frequencies.py
Labels: Typing

#47636 DEPR: Deprecate set_closed and add set_incluive
  doc/redirects.csv
  doc/source/reference/arrays.rst
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Deprecate, Interval

#47626 "DOC #45443 edited the documentation of where/mask functions"
  pandas/core/generic.py
Labels: Docs

#47523 CI: Bump Mac/Windows build timeout to 120 minutes
  .github/workflows/macos-windows.yml
Labels: CI

#47623 BUG: boolean indexer with NA raising when reindex is necessary
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Indexing, Missing-data, NA - MaskedArrays

#47570 BUG: Fixed `tm.set_locale` context manager, it could error and leak when category LC_ALL was used
  pandas/_config/localization.py
  pandas/tests/config/test_localization.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_time.py
Labels: Testing, Localization

#47557 ENH: RangeIndex._shallow_copy can return RangeIndex
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexes/range.py
  pandas/tests/indexes/ranges/test_setops.py
  pandas/tests/reshape/concat/test_index.py
Labels: Index

#47646 TYP: Improve typing interval inclusive
  pandas/_libs/interval.pyi
  pandas/_typing.py
  pandas/core/arrays/arrow/_arrow_utils.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/dtypes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/interval.py
  pandas/io/formats/style.py
  pandas/util/_validators.py
Labels: Interval, Typing

#46491 Bug46381 - Add `storage_option` parameter to to_excel method in Styler
  pandas/core/generic.py
  pandas/io/formats/style.py
  pandas/tests/io/excel/test_style.py
Labels: IO Excel, Styler

#46937 TYP: enable reportUnusedImport
  pandas/__init__.py
  pandas/_config/__init__.py
  pandas/_testing/__init__.py
  pandas/api/__init__.py
  pandas/conftest.py
  pandas/core/api.py
  pandas/core/arrays/arrow/__init__.py
  pandas/core/arrays/sparse/__init__.py
  pandas/core/dtypes/api.py
  pandas/core/dtypes/common.py
  pandas/core/index.py
  pandas/core/internals/__init__.py
  pandas/core/ops/__init__.py
  pandas/core/reshape/api.py
  pandas/core/tools/datetimes.py
  pandas/core/window/__init__.py
  pandas/core/window/rolling.py
  pandas/errors/__init__.py
  pandas/io/api.py
  pandas/io/parquet.py
  pandas/io/sas/__init__.py
  pandas/tests/tseries/offsets/conftest.py
  pandas/tseries/api.py
  pandas/tseries/frequencies.py
  pandas/tseries/holiday.py
  pandas/tseries/offsets.py
  pandas/util/__init__.py
  pandas/util/_decorators.py
  pyproject.toml
Labels: Typing

#47633 BUG: Series.str.zfill() behaves differently than str.zfill() from standard library
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_strings.py
Labels: Strings

#47655 CLN: Rename private variables to inclusive
  pandas/_libs/interval.pyi
  pandas/_libs/interval.pyx
  pandas/core/arrays/arrow/_arrow_utils.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/interval.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/interval/test_constructors.py
Labels: Interval, Clean

#47654 TYP: fix some of the __hash__ methods
  pandas/core/arrays/arrow/_arrow_utils.py
  pandas/core/arrays/base.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/frozen.py
Labels: Typing

#47650 WEB: Update NumFOCUS committee members
  web/pandas/config.yml
Labels: Admin, Web

#47475 REGR: maybe_convert_objects ignoring uints
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/series/test_constructors.py
Labels: Bug, Dtype Conversions, Regression

#47404 SAS7BDAT parser: Faster string parsing
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/sas/sas.pyx
Labels: Performance, IO SAS

#47661 DOC: Fixed CoC broken link
  README.md
Labels: Docs

#47662 Enh move pytable errors and warnings
  doc/source/reference/testing.rst
  pandas/errors/__init__.py
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/test_errors.py
Labels: Warnings

#47664 TYP: make _engine_type consistently a property
  .pre-commit-config.yaml
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pyright_reportGeneralTypeIssues.json
Labels: Typing

#47660 WEB: Add governance page to the website
  web/pandas/about/governance.md
  web/pandas/about/team.md
  web/pandas/community/blog/extension-arrays.md
  web/pandas/community/blog/pandas-1.0.md
  web/pandas/config.yml
Labels: Admin, Web

#47652 ci: add GitHub token permissions for workflows
  .github/workflows/32-bit-linux.yml
  .github/workflows/assign.yml
  .github/workflows/asv-bot.yml
  .github/workflows/autoupdate-pre-commit-config.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/macos-windows.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  .github/workflows/stale-pr.yml
  .github/workflows/ubuntu.yml
Labels: CI

#47665 Code review from #46759 : moved strftime benchmark file outside of tslibs dir
  asv_bench/benchmarks/strftime.py
Labels: Timeseries, Benchmark

#47605 BUG: df.groupby().resample()[[cols]] without key columns raise KeyError
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Groupby, Resample

#47668 ENH: TDA.__mul__ support non-nano
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Numeric Operations, Timedelta, Non-Nano

#47675 ENH: TDA+datetime_scalar support non-nano
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/tests/arrays/test_timedeltas.py
Labels: Timeseries, Numeric Operations, Timedelta

#47679 WEB: Updating links of the governance page
  web/pandas/about/governance.md
Labels: Admin, Web

#47676 TYP: make na_value consistently a property
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/numeric.py
Labels: Typing

#47682 CLN: non-nano follow-ups
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/vectorized.pyi
  pandas/core/indexes/base.py
Labels: Non-Nano

#47684 DOC: Clarify that FrozenList is hashable
  pandas/core/indexes/frozen.py
Labels: Docs

#47685 TST: avoid sort when concat int-index Dataframes with sort=False
  pandas/tests/reshape/concat/test_sort.py
Labels: Testing, Reshaping

#47670 CI: Fix npdev build post Cython annotation change
  pandas/_libs/arrays.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/tests/io/parser/test_quoting.py
Labels: CI, Compat

#47709 Backport PR #47670 on branch 1.4.x (CI: Fix npdev build post Cython annotation change)
  pandas/_libs/arrays.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/tests/io/parser/test_quoting.py
Labels: CI, Compat

#47674 ENH: Move database error to error/__init__.py per GH27656
  doc/source/reference/testing.rst
  pandas/errors/__init__.py
  pandas/io/sql.py
  pandas/tests/test_errors.py
Labels: Error Reporting

#47717 TST: add test for groupby with dropna=False on multi-index
  pandas/tests/groupby/test_groupby_dropna.py
Labels: Testing, Groupby

#47714 BUG: df.fillna ignores axis when df is single block
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Missing-data

#47602 BUG: Make xticks from _quarterly_finder() line up better
  doc/source/whatsnew/v1.5.0.rst
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/plotting/test_converter.py
Labels: Visualization

#47710 GH: Add CITATION.cff
  CITATION.cff
  web/pandas/about/citing.md
Labels: Admin

#47696 GH: Convert feature request template to GH form
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: Admin

#47692 DOC: Centeralized testing guidance for contributions
  doc/source/development/contributing_codebase.rst
  doc/source/development/index.rst
  doc/source/development/test_writing.rst
Labels: Docs

#47645 ENH/TST: Add TestBaseArithmeticOps tests for ArrowExtensionArray #47601
  pandas/compat/__init__.py
  pandas/core/arrays/arrow/array.py
  pandas/core/strings/object_array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/strings/test_api.py
Labels: Testing, Arrow

#47643 ENH: add result_names argument to DataFrame.compare #44354
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/core/shared_docs.py
  pandas/tests/frame/methods/test_compare.py
Labels: Enhancement, Reshaping

#47715 TST: Test for the Enum triggering TypeError (#22551 issue)
  pandas/tests/frame/test_arithmetic.py
Labels: Testing

#47724 BUG: numeric_only with axis=1 in DataFrame.corrwith and DataFrameGroupBy.cummin/max
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_function.py
Labels: Bug, Groupby, Nuisance Columns

#47749 BUG: Correct numeric_only default for resample var and std
  pandas/core/resample.py
  pandas/tests/resample/test_resample_api.py
Labels: Bug, Numeric Operations, Resample, Nuisance Columns

#47712 DOC: fix typos in "See also" documentation section
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#47752 BUG: Fix pc.power_checked min version
  pandas/core/arrays/arrow/array.py
Labels: Testing, Arrow

#47758 TYP: reflect ensure_* function removals
  pandas/_libs/algos.pyi
Labels: Typing

#47756 TYP: Update timestamps.pyi
  pandas/_libs/tslibs/timestamps.pyi
Labels: Typing

#47766 add ignore for new mypy error 'type-var'
  pandas/core/resample.py
Labels: Typing

#47778 Specify that both ``by`` and ``level`` should not be specified in ``groupby`` - GH40378
  doc/source/user_guide/groupby.rst
Labels: Docs, Groupby

#47775 Cln tests interval wrt inclusive
  pandas/tests/arrays/test_array.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/interval/test_constructors.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/indexes/interval/test_pickle.py
  pandas/tests/indexes/interval/test_setops.py
  pandas/tests/series/test_constructors.py
Labels: Testing, Interval, Clean

#47770 REF: de-duplicate get_conversion_factor
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Refactor, Timeseries

#47768 TYP: Appender also works with properties
  pandas/util/_decorators.py
Labels: Typing

#47767 PERF: operations with zoneinfo tzinfos
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Performance, Timezones

#47764 TYP: a few mismatches found by stubtest
  pandas/_libs/algos.pyi
  pandas/_libs/groupby.pyi
  pandas/_libs/internals.pyi
  pandas/_libs/join.pyi
  pandas/_libs/missing.pyi
  pandas/_libs/parsers.pyi
  pandas/_libs/tslibs/ccalendar.pyi
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/timezones.pyi
Labels: Typing

#47754 BUG: Set y-axis label, limits and ticks for a secondary y-axis (#47753)
  doc/source/whatsnew/v1.5.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Visualization

#47736 TST: add test for last() on dataframe grouped by on boolean column (#46409)
  pandas/tests/frame/methods/test_dtypes.py
Labels: Testing

#47727 DOC: update min package versions in install.rst to align with v.1.5.0 requirements
  doc/source/getting_started/install.rst
Labels: Docs

#47716 opt out of bottleneck for nanmean
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/nanops.py
  pandas/tests/test_nanops.py
Labels: Dependencies, Reduction Operations

#47729 TYP: freq and na_value
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/frame.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals/array_manager.py
Labels: Typing

#47763 BUG: fix regression in Series[string] setitem setting a scalar with a mask
  doc/source/whatsnew/v1.4.4.rst
  pandas/core/arrays/string_.py
  pandas/tests/arrays/string_/test_string.py
Labels: Regression, Strings

#47747 FIX: PeriodIndex json roundtrip
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/json/_table_schema.py
  pandas/tests/io/json/test_json_table_schema.py
Labels: IO JSON, Period

#47755 TST: Add additional test for future warning when call Series.str.cat(Series.str)
  pandas/tests/strings/test_cat.py
Labels: Strings

#47757 BUG: wide_to_long fails when stubname misses and i contains string type column
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/reshape/melt.py
  pandas/tests/reshape/test_melt.py
Labels: Reshaping

#47783 BUG: PeriodIndex + TimedeltaArray-with-NaT
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/period.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/tslibs/test_np_datetime.py
Labels: Timedelta, Period

#47792 DOC: Fix versionadded for callable in on_bad_lines
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#47532 WEB: Update to `jupyterlite==0.1.0b10`
  environment.yml
  requirements-dev.txt
Labels: Docs, Web

#47807 REF: re-use convert_reso
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/tslibs/test_timedeltas.py
Labels: Refactor, Non-Nano

#47804 TYP: Column.null_count is a Python int
  pandas/core/exchange/column.py
  pandas/tests/exchange/test_spec_conformance.py
Labels: Typing, Interchange

#46850 Update join docs for other param
  pandas/core/frame.py
  pandas/tests/frame/methods/test_join.py
Labels: Docs, Reshaping

#47585 BUG: Series map ignoring na_action for dict or series mapper
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/base.py
  pandas/tests/apply/test_series_apply.py
Labels: Bug, Missing-data

#47720 ENH: Timestamp.min/max/resolution support non-nano
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Non-Nano

#47711 ENH/TST: Add BaseUnaryOpsTests tests for ArrowExtensionArray
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#47805 ENH/TST: Add isin, _hasna for ArrowExtensionArray
  pandas/core/arrays/arrow/array.py
Labels: Testing, Arrow

#47730 ENH/TST: Add Reduction tests for ArrowExtensionArray
  pandas/core/arrays/arrow/array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#47810 BUG: fix SparseArray.unique IndexError and _first_fill_value_loc algo
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_array.py
Labels: Bug, Sparse

#47732 DOC: Updating some capitalization in doc/source/user_guide #32550
  doc/source/user_guide/sparse.rst
  doc/source/user_guide/timeseries.rst
  doc/source/user_guide/visualization.rst
  doc/source/user_guide/window.rst
Labels: Docs

#47803 TST/CI: xfail test_round_sanity for 32 bit
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
Labels: CI, Unreliable Test

#47824 Manual Backport PR #47803 on branch 1.4.x (TST/CI: xfail test_round_sanity for 32 bit)
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
Labels: Unreliable Test, 32bit

#47678 WEB: Update sponsors in website
  web/pandas/config.yml
  web/pandas/static/img/partners/anaconda.svg
  web/pandas/static/img/partners/bodo.svg
  web/pandas/static/img/partners/dfine.svg
  web/pandas/static/img/partners/nvidia.svg
  web/pandas/static/img/partners/quansight_labs.svg
  web/pandas/static/img/partners/r_studio.svg
  web/pandas/static/img/partners/ursa_labs.svg
  web/pandas/static/img/partners/voltron_data.svg
Labels: Admin, Web

#47847 DOC: Add spaces before `:` to cancel bold
  pandas/core/computation/eval.py
Labels: Docs, expressions

#47831 TYP: pandas/io annotations from pandas-stubs
  pandas/errors/__init__.py
  pandas/io/excel/_base.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/formats/style.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/parquet.py
  pandas/io/pytables.py
  pandas/io/sas/sas_constants.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/util/_validators.py
Labels: IO Data, Typing

#47827 TYP: pandas/plotting annotations from pandas-stubs
  .pre-commit-config.yaml
  pandas/core/arrays/arrow/array.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/misc.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/plotting/_matplotlib/tools.py
  pandas/plotting/_misc.py
Labels: Typing

#47826 REF: de-duplicate PeriodArray arithmetic code
  pandas/core/arrays/period.py
  pandas/tests/arithmetic/test_period.py
Labels: Refactor, Numeric Operations, Period

#47821 Fixed metadata propagation in Dataframe.idxmax and Dataframe.idxmin #…
  pandas/core/frame.py
  pandas/tests/generic/test_finalize.py
Labels: Bug, metadata

#47816 TST: Addition test for get_indexer for interval index
  pandas/tests/indexes/interval/test_indexing.py
Labels: Testing, Interval

#47858 DOC: correct links of Plotly
  doc/source/ecosystem.rst
Labels: Docs

#47603 Add test for unique aggregation returning different dtypes
  pandas/tests/apply/test_frame_apply.py
Labels: Testing, Dtype Conversions, Algos

#47850 TYP/CLN: small cleanups from flake-pyi
  .pre-commit-config.yaml
  pandas/_libs/algos.pyi
  pandas/_libs/interval.pyi
  pandas/_libs/join.pyi
  pandas/_libs/json.pyi
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/writers.pyi
  pandas/_typing.py
  pandas/core/arrays/datetimelike.py
  pandas/core/frame.py
  pandas/core/nanops.py
  pandas/core/reshape/encoding.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/timedeltas.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/info.py
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/parsers/readers.py
  pandas/io/stata.py
Labels: Typing

#47779 PERF: efficient argmax/argmin for SparseArray
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_reductions.py
Labels: Performance, Sparse, ExtensionArray

#47875 DOC: Minor fixes in the IO user guide
  doc/source/user_guide/io.rst
Labels: Docs, IO Data

#47876 DOC: fix broken link in getting started tutorials
  doc/source/getting_started/intro_tutorials/10_text_data.rst
Labels: Docs

#47869 DOC: Update link from VirtusLab to pandas-dev repo
  doc/source/ecosystem.rst
Labels: Docs

#47865 DOC: Adds Hamilton as a development tool
  web/pandas/community/ecosystem.md
Labels: Docs

#47801 TST: Test series construct of dtype timedelta64 #35465
  pandas/tests/series/test_constructors.py
Labels: Testing, Timedelta

#47877 DOC: Additions/updates to documentation-GH46359
  pandas/core/ops/docstrings.py
Labels: Docs

#47853 CLN/DOC: Remove sphinx referencing the wiki
  doc/source/conf.py
  web/pandas/about/roadmap.md
Labels: Docs, Clean

#47811 ENH/TST: Add argsort/min/max for ArrowExtensionArray
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_setops.py
Labels: Testing, Arrow

#47744 ENH/TST: Add quantile & mode tests for ArrowExtensionArray
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#47870 DOC: Add sphinx-toggleprompt and sphinx-copybutton
  doc/source/conf.py
  environment.yml
  requirements-dev.txt
Labels: Docs

#47881 BUG: fix Dataframe.join with categorical index leads to unexpected reordering
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexes/base.py
  pandas/tests/reshape/merge/test_join.py
Labels: Reshaping, Categorical

#47889 CI: Pin cython on 32bit build
  .github/workflows/32-bit-linux.yml
Labels: CI, 32bit

#47851 DEPR: args and kwargs in rolling, expanding, and ewm ops
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/window/common.py
  pandas/core/window/doc.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_api.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_win_type.py
Labels: Numeric Operations, Deprecate, Window

#47892 CLN: Rename "add" to "sum" in groupby
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/resample/test_datetime_index.py
Labels: Groupby, Clean

#47900 BUG: preserve _id in MultiIndex.copy(deep=False)
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_copy.py
Labels: MultiIndex

#47885 DOC: Add numpydoc SS06 validation
  ci/code_checks.sh
  pandas/_config/config.py
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexers/objects.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexes/timedeltas.py
  pandas/core/resample.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/pivot.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/errors/__init__.py
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/plotting/_misc.py
  pandas/tests/scalar/test_nat.py
  scripts/validate_docstrings.py
Labels: Docs

#47888 REF: Rename exchange -> interchange
  doc/source/reference/general_functions.rst
  pandas/api/__init__.py
  pandas/api/exchange/__init__.py
  pandas/api/interchange/__init__.py
  pandas/core/frame.py
  pandas/core/interchange/__init__.py
  pandas/core/interchange/buffer.py
  pandas/core/interchange/column.py
  pandas/core/interchange/dataframe.py
  pandas/core/interchange/dataframe_protocol.py
  pandas/core/interchange/from_dataframe.py
  pandas/core/interchange/utils.py
  pandas/tests/api/test_api.py
  pandas/tests/interchange/__init__.py
  pandas/tests/interchange/conftest.py
  pandas/tests/interchange/test_impl.py
  pandas/tests/interchange/test_spec_conformance.py
  pandas/tests/interchange/test_utils.py
Labels: Interchange

#47890 CI: Add CodeQL Github Action
  .github/workflows/codeql.yml
Labels: CI
