Repository pandas-dev/pandas, pull requests merged in 2022-01, with the labels that each got.

#45137 ENH: to_sql returns rowcount
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/generic.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Enhancement, IO SQL

#44819 API: hide NumericIndex from public top-level namespace in favor of pd.Index
  doc/source/reference/indexing.rst
  doc/source/user_guide/advanced.rst
  doc/source/whatsnew/v0.16.2.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/__init__.py
  pandas/_testing/__init__.py
  pandas/core/indexes/category.py
  pandas/core/indexes/numeric.py
  pandas/tests/api/test_api.py
  pandas/tests/base/test_unique.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/multi/test_names.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numpy_compat.py
Labels: Index, Blocker for rc

#45132 REF: Deduplicate to_xml code
  pandas/core/frame.py
  pandas/io/formats/xml.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Refactor, IO XML

#45147 CLN: assorted, suppress test warnings
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/algorithms.py
  pandas/core/arraylike.py
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/io/formats/test_printing.py
Labels: Clean

#45152 TST: Use pytest or decorator instead of checking ImportError
  pandas/tests/computation/test_compat.py
  pandas/tests/frame/test_reductions.py
Labels: Testing

#45159 DOC: update references to deprecated methods
  pandas/io/formats/style.py
Labels: Docs

#45163 TST: Parameterize
  pandas/tests/computation/test_eval.py
Labels: Testing

#45157 BUG: `Styler.apply_index` fails with LaTeX conversion with hidden Multi levels
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_to_latex.py
Labels: Styler

#45169 ASV: Add merge on categorical benchmarks
  asv_bench/benchmarks/join_merge.py
Labels: Reshaping, Benchmark

#45154 TST: tests for setitem-like casting issues
  pandas/tests/series/indexing/test_setitem.py
Labels: Testing, Indexing, Dtype Conversions

#45150 BUG: fix GH45032 iloc(axis=1).__setitem__ axis argument
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_iloc.py
Labels: Bug, Indexing

#45164 TST: Clean pg8000 test
  .pre-commit-config.yaml
  pandas/tests/io/test_sql.py
Labels: Testing

#45167 TST: tests for nullable issues
  pandas/tests/arrays/categorical/test_astype.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/indexing/test_loc.py
Labels: Testing, Indexing, Dtype Conversions, Categorical

#44282 BUG: Add fix for hashing timestamps with folds
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Timezones

#45133 TYP: type read_xml and deprecate passing positional arguments
  doc/source/whatsnew/v1.4.0.rst
  pandas/_typing.py
  pandas/io/xml.py
  pandas/tests/io/xml/test_xml.py
Labels: Typing, IO XML

#45179 Pin numpy to get ci back to green
  environment.yml
  pandas/compat/numpy/__init__.py
  pandas/tests/frame/test_ufunc.py
  requirements-dev.txt
Labels: CI

#45134 BUG: allow use of both default+input resolvers in df.eval, GH34966
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_query_eval.py
Labels: Bug, expressions

#45166 REF: separate numpy-specific part of can_hold_element
  pandas/core/dtypes/cast.py
Labels: Refactor, Dtype Conversions

#45175 BUG: MultiIndex dtypes incorrect if level names not unique
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_get_set.py
Labels: MultiIndex

#45180 BUG: encoding_errors=None with read_csv c-engine
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/parsers.pyx
  pandas/tests/io/test_common.py
Labels: IO CSV

#45184 CLN: assorted follow-ups
  pandas/core/array_algos/putmask.py
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/io/sas/sas7bdat.py
  pandas/io/stata.py
  pandas/tests/arrays/categorical/test_astype.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/extension/test_floating.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_astype.py
Labels: Clean

#45183 TST: parameterize and split
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Testing

#45191 CI: fix mypy complaints
  pandas/core/ops/array_ops.py
  pandas/io/stata.py
Labels: Typing

#45170 PERF: expanding/rolling.min/max with engine='numba'
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/window/aggregations.pyx
  pandas/core/_numba/kernels/__init__.py
  pandas/core/_numba/kernels/min_max_.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_numba.py
Labels: Performance, Window

#45103 CI: Ensure all minimum optional dependencies are tested
  .github/workflows/posix.yml
  ci/deps/actions-38-db-min.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38-locale.yaml
  ci/deps/actions-38-locale_slow.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/compat/_optional.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/series/methods/test_reindex.py
Labels: CI, Dependencies

#42494 Improved docstring and return type hints for `to_datetime`
  pandas/core/tools/datetimes.py
Labels: Docs, Timezones

#45181 BUG: Index.get_loc always raise InvalidIndexError on listlike
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/numeric/test_indexing.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_indexing.py
Labels: Indexing, Error Reporting

#45189 DOC: Improve reference/arrays.rst
  doc/source/reference/arrays.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#45196 DOC: add contributors to 1.4 release notes
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#45197 DOC: Increased minimum version for Python
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#45199 CI: activate azure pipelines/github actions on 1.4.x
  .github/workflows/code-checks.yml
  .github/workflows/datamanger.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  azure-pipelines.yml
Labels: CI

#45195 BLD: updated pydata-sphinx-theme to master in environment.yml
  environment.yml
  requirements-dev.txt
Labels: Dependencies

#45201 Backport PR #45199 on branch 1.4.x (CI: activate azure pipelines/github actions on 1.4.x)
  .github/workflows/code-checks.yml
  .github/workflows/datamanger.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  azure-pipelines.yml
Labels: CI

#45202 Backport PR #45195 on branch 1.4.x (BLD: updated pydata-sphinx-theme to master in environment.yml)
  environment.yml
  requirements-dev.txt
Labels: Dependencies

#44894 DOC: `MultiIndex.get_level_values` mentions implicit type casting if level contains null.
  pandas/core/indexes/multi.py
Labels: Docs, MultiIndex

#45138 ENH: add `cline` to `Styler.to_latex`
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/formats/templates/latex_longtable.tpl
  pandas/io/formats/templates/latex_table.tpl
  pandas/tests/io/formats/style/test_to_latex.py
Labels: IO LaTeX, Styler

#45207 TST: Split/parameterize test_to_csv
  pandas/tests/frame/methods/test_to_csv.py
Labels: Testing

#45205 DOC: fix typo in 06_calculate_statistics
  doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
Labels: Docs

#45173 STYLE add vulture hook
  .pre-commit-config.yaml
  pandas/tests/frame/test_constructors.py
  scripts/run_vulture.py
Labels: Code Style

#45213 Backport PR #45205 on branch 1.4.x (DOC: fix typo in 06_calculate_statistics)
  doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
Labels: Docs

#45210 Backport PR #44894 on branch 1.4.x (DOC: `MultiIndex.get_level_values` mentions implicit type casting if level contains null.)
  pandas/core/indexes/multi.py
Labels: Docs, MultiIndex

#45198 DOC: start v1.5.0 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#45220 fix issue link in what's new 1.4.0
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#45211 Backport PR #45138 on branch 1.4.x (ENH: add `cline` to `Styler.to_latex`)
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/formats/templates/latex_longtable.tpl
  pandas/io/formats/templates/latex_table.tpl
  pandas/tests/io/formats/style/test_to_latex.py
Labels: IO LaTeX, Styler

#45225 Backport PR #45220 on branch 1.4.x (fix issue link in what's new 1.4.0)
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#45204 CI: Use broader condition to maybe catch ResourceWarning from Matplotlib
  pandas/_testing/_warnings.py
Labels: CI

#45208 DOC: improve IO & General Functions API reference
  doc/source/reference/general_functions.rst
  doc/source/reference/io.rst
  pandas/core/algorithms.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/io/stata.py
  pandas/util/_tester.py
Labels: Docs

#45233 Backport PR #45208 on branch 1.4.x (DOC: improve IO & General Functions API reference)
  doc/source/reference/general_functions.rst
  doc/source/reference/io.rst
  pandas/core/algorithms.py
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/io/stata.py
  pandas/util/_tester.py
Labels: Docs

#45229 CLN: remove generic `import pandas as pd` in `test_style.py`
  pandas/tests/io/formats/style/test_style.py
Labels: Clean

#45239 TST: pytest --strict-config
  pyproject.toml
Labels: Testing

#45247 PERF: find_stack_level
  pandas/util/_exceptions.py
Labels: Performance

#45146 ENH: Allow callable for on_bad_lines in read_csv when engine="python"
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_unsupported.py
Labels: Enhancement, IO CSV

#45232 BUG: Series.__setitem__ positional raising ValueError
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/series.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Indexing

#45185 TST: Create test for #30122 about display.precision
  pandas/tests/io/formats/test_format.py
Labels: Testing

#45214 REGR: Index(pd.array(foo), dtype=object)
  pandas/core/indexes/base.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_index_new.py
Labels: Regression, Index, Constructors

#45242 CLN/PERF: avoid double-checks
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
Labels: Indexing, Performance

#45228 DOC: comprehensive example of `Styler.to_latex` features
  doc/source/_static/style/latex_stocks.png
  doc/source/_static/style/latex_stocks_html.png
  pandas/io/formats/style.py
Labels: Docs, IO LaTeX

#45254 REF/TYP: Block._slice and related
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/series.py
Labels: Refactor, Internals

#45237 DOC: Improve doc summaries in series.rst
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/sparse/array.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/series.py
  pandas/core/shared_docs.py
Labels: Docs

#45209 TST/REF: port coercion tests to SetitemCastingEquivalents
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Testing, Dtype Conversions

#45212 CLN: suppress warnings
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/lib.pyx
  pandas/core/arrays/masked.py
  pandas/core/dtypes/cast.py
  pandas/core/indexing.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_ufunc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/test_downstream.py
  pandas/util/_test_decorators.py
Labels: Clean

#45194 REF: catch more specific exceptions in Series.__setitem__
  pandas/core/series.py
Labels: Refactor, Indexing

#45216 REF: consolidate _validate_fill_logic in np_can_hold_element
  pandas/core/dtypes/cast.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
Labels: Refactor, Dtype Conversions

#45203 DOC: fix doctests for depr `closed` arg
  pandas/core/indexes/datetimes.py
Labels: Testing, Docs

#45261 Added note in docs for giving the developer the option of choosing be…
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs, Timedelta

#44502 ENH: `Styler.to_string`
  doc/source/reference/style.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/formats/templates/string.tpl
  pandas/tests/io/formats/style/test_to_string.py
Labels: Enhancement, IO Data, Styler

#45234 REF: dtypes.astype
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/astype.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/concat.py
  pandas/core/indexes/numeric.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/io/parsers/base_parser.py
  pandas/tests/dtypes/test_common.py
Labels: Refactor, Dtype Conversions

#45264 Backport PR #45146 on branch 1.4.x (ENH: Allow callable for on_bad_lines in read_csv when engine="python")
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.4.0.rst
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_unsupported.py
Labels: Enhancement, IO CSV

#45265 Backport PR #45214 on branch 1.4.x (REGR: Index(pd.array(foo), dtype=object))
  pandas/core/indexes/base.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_index_new.py
Labels: Regression, Index, Constructors

#45266 Backport PR #45242 on branch 1.4.x (CLN/PERF: avoid double-checks)
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
Labels: Indexing, Performance

#45267 Backport PR #45228 on branch 1.4.x (DOC: comprehensive example of `Styler.to_latex` features)
  doc/source/_static/style/latex_stocks.png
  doc/source/_static/style/latex_stocks_html.png
  pandas/io/formats/style.py
Labels: Docs, IO LaTeX

#45268 Backport PR #45237 on branch 1.4.x (DOC: Improve doc summaries in series.rst)
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/sparse/array.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/series.py
  pandas/core/shared_docs.py
Labels: Docs

#45269 Backport PR #45212 on branch 1.4.x (CLN: suppress warnings)
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/lib.pyx
  pandas/core/arrays/masked.py
  pandas/core/dtypes/cast.py
  pandas/core/indexing.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_ufunc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/test_downstream.py
  pandas/util/_test_decorators.py
Labels: Clean

#45270 Backport PR #45203 on branch 1.4.x (DOC: fix doctests for depr `closed` arg)
  pandas/core/indexes/datetimes.py
Labels: Testing, Docs

#45271 Backport PR #45261 on branch 1.4.x (Added note in docs for giving the developer the option of choosing be…)
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs, Timedelta

#45125 BUG: Operations with SparseArray return SA with wrong indices
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/extension/test_sparse.py
Labels: Bug, Sparse

#45227 BUG: raise on wrong keyword arguments in Timedelta
  doc/source/whatsnew/v1.4.0.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/tslibs/test_timedeltas.py
Labels: Bug, Timedelta

#45256 ENH: Index[complex]
  pandas/_libs/index.pyi
  pandas/_libs/index_class_helper.pxi.in
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/base/test_misc.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/methods/test_value_counts.py
Labels: Dtype Conversions, Index

#45279 Revert "ENH: Index[complex]"
  pandas/_libs/index.pyi
  pandas/_libs/index_class_helper.pxi.in
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/base/test_misc.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/methods/test_value_counts.py
Labels: Dtype Conversions, Index, Constructors

#45275 Backport PR #45125 on branch 1.4.x (BUG: Operations with SparseArray return SA with wrong indices)
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/extension/test_sparse.py
Labels: Bug, Sparse

#45139 TYP: Add type definition for generators in excel.py
  pandas/io/formats/excel.py
Labels: Typing

#45274 Fix groupby any/all on an empty series/frame
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_any_all.py
Labels: Bug, Groupby

#45295 Backport PR #45227 on branch 1.4.x (BUG: raise on wrong keyword arguments in Timedelta)
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/tslibs/test_timedeltas.py
Labels: Timedelta

#45276 TST: Parameterize & split
  pandas/tests/computation/test_eval.py
  pandas/tests/libs/test_hashtable.py
  pandas/tests/libs/test_lib.py
  pandas/tests/reductions/test_reductions.py
Labels: Testing

#45278 TST: Split / parameterize reshaping tests
  pandas/tests/reshape/test_melt.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_union_categoricals.py
  pandas/tests/reshape/test_util.py
Labels: Testing

#45142 BUG: Series(floatlike, dtype=intlike) inconsistent with non-ndarray data
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/tests/series/test_constructors.py
Labels: Bug, Constructors

#45255 BUG/PERF: MaskedArray.searchsorted(np.nan)
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/masked.py
  pandas/tests/arrays/masked_shared.py
Labels: Performance, NA - MaskedArrays

#45241 BUG: frame.iloc[i] with a single EA column
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_iloc.py
Labels: Bug, Indexing

#45290 TST: implement xfailed test for #18415
  pandas/tests/frame/indexing/test_coercion.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Testing

#45282 TST: Split / parameterize resample PT 2
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
Labels: Testing

#45281 TST: Parameterize / split resample tests
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
Labels: Testing

#45280 BUG: pd.to_datetime([np.str_ objects]) GH#32264
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/tools/test_to_datetime.py
Labels: Timeseries

#45273 BUG: can_hold_element size checks on ints/floats
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_can_hold_element.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Dtype Conversions

#45246 TYP: Add types for excel writer classes
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
Labels: IO Excel, Typing

#45293 REF: fewer simple_new calls in DTA._generate_range GH#24562
  pandas/core/arrays/datetimes.py
Labels: Refactor, Timeseries, Performance

#45292 Bump stale GHA
  .github/workflows/stale-pr.yml
Labels: CI

#45297 Backport PR #45274 on branch 1.4.x (Fix groupby any/all on an empty series/frame)
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_any_all.py
Labels: Bug, Groupby

#45323 CI: Fix concurrency group for min versions posix builds
  .github/workflows/posix.yml
Labels: CI

#45327 DOC: fix a typo
  doc/source/user_guide/style.ipynb
Labels: Docs

#45302 DEPR: line_terminator->lineterminator GH#9569
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/src/parser/tokenizer.c
  pandas/core/generic.py
  pandas/io/formats/csvs.py
  pandas/io/formats/format.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/io/xml/test_to_xml.py
Labels: IO CSV, Deprecate

#45304 REF: implement find_result_type
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Refactor, Dtype Conversions

#45251 DOC CLN: use ``color`` shared doc string
  pandas/io/formats/style.py
Labels: Docs, Visualization

#45087 BUG: Timestamp.to_pydatetime losing 'fold'
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/scalar/timestamp/test_timezones.py
Labels: Bug, Timezones

#45308 BUG: Timestamp(2020,1, 1, tzinfo=foo) GH#31929
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: Bug, Timezones

#45330 Backport PR #45087 on branch 1.4.x (BUG: Timestamp.to_pydatetime losing 'fold')
  doc/source/whatsnew/v1.4.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/scalar/timestamp/test_timezones.py
Labels: Bug, Timezones

#45336 CI/DOC: replace master -> main branch
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/documentation_improvement.yaml
  .github/ISSUE_TEMPLATE/performance_issue.yaml
  .github/workflows/asv-bot.yml
  .github/workflows/code-checks.yml
  .github/workflows/comment_bot.yml
  .github/workflows/datamanger.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  Dockerfile
  Makefile
  README.md
  azure-pipelines.yml
  codecov.yml
  doc/source/conf.py
  doc/source/development/contributing.rst
  doc/source/development/contributing_codebase.rst
  doc/source/development/contributing_docstring.rst
  doc/source/development/contributing_documentation.rst
  doc/source/development/contributing_environment.rst
  doc/source/development/extending.rst
  doc/source/getting_started/comparison/comparison_with_sas.rst
  doc/source/getting_started/comparison/comparison_with_spreadsheets.rst
  doc/source/getting_started/comparison/comparison_with_stata.rst
  doc/source/getting_started/intro_tutorials/07_reshape_table_layout.rst
  doc/source/getting_started/intro_tutorials/08_combine_dataframes.rst
  doc/source/getting_started/intro_tutorials/09_timeseries.rst
  doc/source/getting_started/intro_tutorials/includes/air_quality_no2.rst
  doc/source/getting_started/intro_tutorials/includes/titanic.rst
  doc/source/user_guide/options.rst
  doc/source/user_guide/style.ipynb
  doc/source/user_guide/visualization.rst
  doc/source/user_guide/window.rst
  doc/source/whatsnew/v0.19.2.rst
  doc/source/whatsnew/v0.20.0.rst
  pandas/plotting/_misc.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_parquet.py
Labels: Compat

#45334 DEPR: un-deprecate errors kwd reverts #44294
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/series/methods/test_fillna.py
Labels: Indexing, Deprecate

#45325 TST: Split/parameterize indexing tests
  pandas/conftest.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_scalar.py
Labels: Testing

#45294 BUG: DataFrame[dt64].quantile(axis=1) when empty returning f8
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_quantile.py
Labels: Bug, Reshaping, Dtype Conversions

#45354 TST: xfail test_arrowparquet_options for windows
  pandas/tests/io/test_fsspec.py
Labels: Testing

#45365 Backport PR #45354 on branch 1.4.x (TST: xfail test_arrowparquet_options for windows)
  pandas/tests/io/test_fsspec.py
Labels: Testing

#44889 BUG: ArrayManager not respecting copy keyword
  pandas/core/internals/construction.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/indexing/multiindex/test_setitem.py
Labels: ArrayManager

#45355 CI: Ensure GHA uses major versions of actions
  .github/workflows/asv-bot.yml
  .github/workflows/code-checks.yml
  .github/workflows/comment_bot.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
Labels: CI

#45343 Backport PR #45334 on branch 1.4.x (DEPR: un-deprecate errors kwd reverts #44294)
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/series/methods/test_fillna.py
Labels: Indexing, Deprecate

#45306 Backport PR #45244 on branch 1.4.x (TYP: Ignore numpy related issues)
  environment.yml
  pandas/core/algorithms.py
  pandas/core/arraylike.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/array.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/internals/ops.py
  pandas/core/missing.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/core/window/rolling.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/stata.py
  pandas/tests/extension/date/array.py
  requirements-dev.txt
Labels: Typing

#45360 BUG: No error raised in to_stata() for -np.inf #45350
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Bug, IO Stata

#45321 DEPR: Series/DataFrame/HDFStore.iteritems()
  doc/source/user_guide/scale.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/sparse/accessor.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/io/pytables.py
  pandas/tests/frame/test_api.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_iteration.py
Labels: IO HDF5, Deprecate

#45257 CI: Simplify GHA dependency files
  .github/workflows/posix.yml
  ci/deps/actions-38-locale.yaml
  ci/deps/actions-38-locale_slow.yaml
  ci/deps/actions-38-slow.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39-slow.yaml
  ci/deps/actions-39.yaml
  pandas/tests/arrays/floating/test_construction.py
  pandas/tests/arrays/period/test_arrow_compat.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_parquet.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_time.py
Labels: CI

#45324 DEPR: inconsistent series[i:j] slicing with Int64Index GH#45162
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/numeric.py
  pandas/core/indexing.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/series/indexing/test_get.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_item.py
  pandas/tests/window/test_apply.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_rolling_functions.py
  pandas/tests/window/test_rolling_quantile.py
  pandas/tests/window/test_rolling_skew_kurt.py
Labels: Indexing, Deprecate

#45301 BUG: hash_array TypeError instead of AttributeError on Index GH#42003
  pandas/core/util/hashing.py
  pandas/tests/util/test_hashing.py
Labels: Bug

#45375 DOC: Improve gotchas.rst
  doc/source/user_guide/gotchas.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/formats/info.py
Labels: Docs

#45376 DOC: Improve sparse.rst
  doc/source/reference/arrays.rst
  doc/source/user_guide/sparse.rst
Labels: Docs

#45362 BUG: CategoricalIndex.union with nans
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/dtypes/cast.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_setops.py
Labels: Categorical, setops

#45359 BUG: categorical-with-nas to float64 instead of object
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/dtypes/concat.py
  pandas/core/indexes/category.py
  pandas/tests/reshape/concat/test_append_common.py
Labels: Categorical

#45272 BUG: DataFrame.astype preserve subclasses GH#40810
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
  pandas/tests/frame/test_subclass.py
Labels: Bug, Subclassing

#45287 BUG: frame[x].loc[y] inconsistent with frame.at[x, y] GH#22372
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/managers.py
  pandas/tests/indexing/test_at.py
  pandas/tests/internals/test_internals.py
Labels: Bug, Indexing

#45285 BUG: setitem into complex64 overflow
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Indexing, Complex

#45377 REGR: DataFrame.reset_index with empty RangeIndex
  pandas/core/indexes/base.py
  pandas/tests/frame/methods/test_reset_index.py
Labels: Regression

#45371 PERF: avoid SQL MetaData reflection in init #45260
  pandas/io/sql.py
Labels: Performance, IO SQL

#45393 DOC: whatsnew note for groupby.apply bugfix
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#45363 BUG: correctly instantiate subclassed DataFrame/Series in groupby apply
  pandas/core/groupby/ops.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/groupby/test_groupby_subclass.py
Labels: Bug, Groupby, Regression

#45381 ENH: support 'out' keyword in Categorical.__array_ufunc__
  pandas/core/arrays/categorical.py
  pandas/core/arrays/numpy_.py
  pandas/tests/arrays/test_numpy.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/indexes/test_numpy_compat.py
Labels: ufuncs

#45380 REF: de-duplicate methods across nullable EA subclasses
  pandas/core/arrays/boolean.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numeric.py
Labels: Refactor, NA - MaskedArrays

#45353 REF: use standard coerce pattern in Block.shift
  pandas/core/internals/blocks.py
Labels: Refactor

#45385 DOC: Improve scale.rst
  doc/source/user_guide/scale.rst
  pandas/_testing/__init__.py
Labels: Docs

#45348 REF: Share Block.setitem
  pandas/core/internals/blocks.py
Labels: Refactor

#45299 BUG: .asof casting bool results to float64 GH#16063
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_asof.py
Labels: Bug, Dtype Conversions

#45309 BUG: Float64Index.astype('u8') returns Int64Index
  doc/source/whatsnew/v1.5.0.rst
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/core/arrays/interval.py
  pandas/core/dtypes/astype.py
  pandas/core/indexes/numeric.py
  pandas/tests/base/test_misc.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/numeric/test_astype.py
  pandas/tests/series/methods/test_astype.py
Labels: Bug, Index, Astype

#45391 Fix Stale Action commenting on issues
  .github/workflows/stale-pr.yml
Labels: CI

#45145 BUG: Fix for xlabel/ylabel in barh plot
  doc/source/whatsnew/v1.5.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_series.py
Labels: Bug, Visualization

#45389 REG/REF: close file handles engine-independently in read_csv
  doc/source/whatsnew/v1.4.0.rst
  pandas/_typing.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_unsupported.py
Labels: IO CSV

#45394 Backport PR #45377 on branch 1.4.x (REGR: DataFrame.reset_index with empty RangeIndex)
  pandas/core/indexes/base.py
  pandas/tests/frame/methods/test_reset_index.py
Labels: Regression

#45395 Backport PR #45371 on branch 1.4.x (PERF: avoid SQL MetaData reflection in init #45260)
  pandas/io/sql.py
Labels: Performance, IO SQL

#45378 REF: implement LocationIndexer._tupleize_axis_indexer
  pandas/core/indexing.py
Labels: Refactor, Indexing

#45396 Backport PR #45393 on branch 1.4.x (DOC: whatsnew note for groupby.apply bugfix)
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#45397 Backport PR #45363 on branch 1.4.x (BUG: correctly instantiate subclassed DataFrame/Series in groupby apply)
  pandas/core/groupby/ops.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/groupby/test_groupby_subclass.py
Labels: Bug, Groupby, Regression

#44839 REGR: allow reindexing datetimelike with upcast / raise deprecation warning
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/array_algos/take.py
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/series/methods/test_reindex.py
Labels: Indexing, Deprecate

#45398 Backport PR #45389 on branch 1.4.x (REG/REF: close file handles engine-independently in read_csv)
  doc/source/whatsnew/v1.4.0.rst
  pandas/_typing.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_unsupported.py
Labels: IO CSV

#45400 CLN: consolidate arg no longer needed
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/core/internals/managers.py
Labels: Clean

#45401 CLN: reuse common_dtype_categorical_compat
  pandas/core/dtypes/concat.py
Labels: Dtype Conversions, Categorical
