Repository pandas-dev/pandas, pull requests merged in 2022-02, with the labels that each got.

#45672 REF: implement LossySetitemError
  pandas/core/arrays/interval.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/series.py
Labels: Dtype Conversions, Internals

#45673 BUG: consistent downcast on fillna no-ops
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Missing-data

#45742 REF: use try/except pattern in Block.setitem, EABackedBlock.setitem
  pandas/core/arrays/datetimelike.py
  pandas/core/internals/blocks.py
Labels: Refactor, ExtensionArray

#45192 REF/PERF: dont use hashtable in IndexEngine.__contains__
  pandas/_libs/index.pyx
  pandas/_libs/index_class_helper.pxi.in
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
Labels: Indexing, Performance

#45687 ENH: Allow safe access to `.book` in ExcelWriter
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
  pandas/tests/io/excel/test_odswriter.py
  pandas/tests/io/excel/test_openpyxl.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/excel/test_xlsxwriter.py
  pandas/tests/io/excel/test_xlwt.py
Labels: Enhancement, IO Excel

#45512 Test to datetime null to NaT
  pandas/tests/tools/test_to_datetime.py
Labels: Testing, Missing-data

#45747 BUG: update caught exception
  pandas/core/internals/blocks.py
Labels: Indexing, Error Reporting

#45754 Backport PR #45679: BUG: Do not error on other dbapi2 connections
  doc/source/whatsnew/v1.4.1.rst
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL

#45755 Backport PR #45581 on branch 1.4.x (CI: Fix actions-310 testing 3.9 instead of 3.10)
  ci/deps/actions-310.yaml
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_user_agent.py
Labels: CI

#45746 DEPR: Series[td64].fillna(incompat) cast instead of raise
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/series/methods/test_fillna.py
Labels: Missing-data, Deprecate

#45756 DOC: minor fix to 1.4.1 release notes
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45757 DOC: move pydata-sphinx-theme to the conda packages section
  environment.yml
  requirements-dev.txt
Labels: Docs

#45758 DOC: minor tidy of 1.4.1 release notes
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45759 Backport PR #45756 on branch 1.4.x (DOC: minor fix to 1.4.1 release notes)
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45760 Backport PR #45757 on branch 1.4.x (DOC: move pydata-sphinx-theme to the conda packages section)
  environment.yml
  requirements-dev.txt
Labels: Docs

#45764 Backport PR #45758 on branch 1.4.x (DOC: minor tidy of 1.4.1 release notes)
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45744 Backport PR #45706: BUG: Frame.iat item_cache invalidation bug
  doc/source/whatsnew/v1.4.1.rst
  pandas/conftest.py
  pandas/core/frame.py
  pandas/core/internals/base.py
  pandas/tests/indexing/test_iat.py
Labels: Indexing

#45750 BUG: Series.mask with small int dtypes raising
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/array_algos/putmask.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Indexing

#45748 DOC: fix incorrect pie chart documentation
  doc/source/user_guide/visualization.rst
Labels: Docs, Visualization

#45767 CLN: Index methods incorrectly assuming object dtype
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
Labels: Clean, Index

#45768 BUG: Series[Period][mask] = 'foo' raising inconsistent with non-mask indexing
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/arrays/test_period.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Bug, Indexing, Dtype Conversions, Period, Interval

#45771 TST: Skip pyarrow hanging in MacOS CI
  pandas/tests/io/parser/test_unsupported.py
Labels: Testing

#45781 Backport PR #45771 on branch 1.4.x (TST: Skip pyarrow hanging in MacOS CI)
  pandas/tests/io/parser/test_unsupported.py
Labels: Testing

#45763 Group by aggregate functions test case
  pandas/tests/groupby/test_categorical.py
Labels: Testing

#45782 REF: extract_ordinals support 2D
  pandas/_libs/tslibs/period.pyx
  pandas/tests/tslibs/test_period_asfreq.py
Labels: Refactor, Period

#45788 REF: array_to_timedelta64 handle 2D
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/tslibs/test_timedeltas.py
Labels: Refactor, Timedelta

#45784 Regression: Series.loc.setitem raising with all false indexer and series on rhs
  doc/source/whatsnew/v1.4.1.rst
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Indexing, Regression

#45749 BUG: RecursionError when attempting to replace np.nan values (#45725)
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Missing-data, replace

#45791 BUG: DataFrame.interpolate failing to return a copy
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Dtype Conversions

#45792 REF: use np_can_hold_element pattern in Block.shift
  pandas/core/internals/blocks.py
Labels: Refactor, Dtype Conversions

#45695 TST: Nan must not be converted to string using .loc
  pandas/tests/indexing/test_loc.py
Labels: Testing

#45786 TST: Skip flaky, crashing test in Windows
  pandas/tests/test_sorting.py
Labels: Testing, Windows

#45805 Backport PR #45786 on branch 1.4.x (TST: Skip flaky, crashing test in Windows)
  pandas/tests/test_sorting.py
Labels: Testing, Windows

#45812 TST: Create is_ci_environment helper
  pandas/compat/__init__.py
  pandas/tests/io/conftest.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/test_user_agent.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/test_sorting.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
Labels: Testing

#45796 BUG: Series[Interval].fillna(mismatched) coerce instead of raise
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_coercion.py
Labels: Bug, Dtype Conversions

#45820 PERF: groupby.transform skip fast path when only a single group exists
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Performance

#45823 Backport PR #45812 on branch 1.4.x (TST: Create is_ci_environment helper)
  pandas/compat/__init__.py
  pandas/tests/io/conftest.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/test_user_agent.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/test_sorting.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
Labels: Testing

#45808 bug: fix pd.NA in highlighters
  doc/source/whatsnew/v1.4.1.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_highlight.py
Labels: Bug, Styler

#45826 TST: Fixturize / parameterize test_sas7bdat
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/series/indexing/test_xs.py
Labels: Testing

#45794 BUG: Error writing an empty DataFrame to an ods file
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/excel/_odswriter.py
  pandas/tests/io/excel/test_writers.py
Labels: Bug, IO Excel

#45770 REF/TYP: collect Block methods
  pandas/core/internals/blocks.py
Labels: Internals, Typing

#45828 Backport PR #45808 on branch 1.4.x (bug: fix pd.NA in highlighters)
  doc/source/whatsnew/v1.4.1.rst
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_highlight.py
Labels: Bug, Styler

#45829 CLN: test_eval.py
  pandas/tests/computation/test_eval.py
Labels: Testing

#45822 Test case for concat inconsistent multiIndex
  pandas/tests/reshape/concat/test_index.py
Labels: Testing, Reshaping, MultiIndex

#45061 ENH: Index[bool]
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/index.pyi
  pandas/_libs/index.pyx
  pandas/conftest.py
  pandas/core/algorithms.py
  pandas/core/indexes/base.py
  pandas/core/tools/datetimes.py
  pandas/core/util/hashing.py
  pandas/tests/base/test_value_counts.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/reshape/concat/test_append_common.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_drop.py
  pandas/tests/series/methods/test_value_counts.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/test_algos.py
Labels: Enhancement, Index

#45300 BUG: Categorical.view not accepting integer dtypes GH#25464
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/indexes/categorical/test_category.py
Labels: Bug, Categorical

#45797 Test series replace different numpy int
  pandas/tests/series/methods/test_replace.py
Labels: Testing, Dtype Conversions

#45832 TST: Don't use autouse fixture in test_eval
  pandas/tests/computation/test_eval.py
Labels: Testing

#45831 TST: Don't use autouse fixture in test_stata
  pandas/tests/io/test_stata.py
Labels: Testing

#45834 REF: render trimming moved to private method
  pandas/io/formats/style_render.py
Labels: Refactor, Styler

#45840 REF: standardize patterns in Block Methods
  pandas/core/internals/blocks.py
Labels: Refactor, Internals

#45625 BUG: SeriesGroupBy.value_counts - index name missing in categorical columns
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_value_counts.py
Labels: Bug, Groupby, Algos, Categorical, Series

#45843 TST: Remove unused fixtures in tests
  pandas/conftest.py
  pandas/tests/apply/test_str.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_shift.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_parquet.py
Labels: Testing

#45841 DOC: Update import statement (GH21749)
  pandas/core/algorithms.py
Labels: Docs

#45795 DEP: Protect some ExcelWriter attributes
  doc/source/reference/io.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/excel/_xlwt.py
  pandas/io/formats/excel.py
  pandas/tests/io/excel/test_openpyxl.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/excel/test_xlwt.py
Labels: IO Excel, Deprecate

#45641 Switch deps to Conda
  .pre-commit-config.yaml
  environment.yml
  pandas/io/formats/excel.py
  pandas/io/json/_json.py
  pandas/io/pytables.py
  requirements-dev.txt
  scripts/tests/test_sync_flake8_versions.py
  setup.cfg
Labels: Code Style, Dependencies

#45586 BUG: fix skiprows callable infinite loop
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/test_skiprows.py
Labels: Bug, IO CSV, IO Excel

#45015 Typ parts of python parser
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
Labels: Typing

#45853 Fixing documentation format in read_csv
  pandas/io/parsers/readers.py
Labels: Docs

#45851 Backport PR #45641 on branch 1.4.x (Switch deps to Conda)
  .pre-commit-config.yaml
  environment.yml
  pandas/io/formats/excel.py
  pandas/io/json/_json.py
  pandas/io/pytables.py
  requirements-dev.txt
  scripts/tests/test_sync_flake8_versions.py
  setup.cfg
Labels: Code Style, Dependencies

#45842 TST: Use fixtures instead of setup_method
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/base/test_constructors.py
  pandas/tests/indexes/test_frozen.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_timeseries_window.py
Labels: Testing

#45856 CI: Align GHA and Windows Azure dependencies
  azure-pipelines.yml
  ci/azure/windows.yml
  ci/deps/azure-windows-310.yaml
  ci/deps/azure-windows-38.yaml
  ci/deps/azure-windows-39.yaml
Labels: CI

#45861 Backport PR #45856 on branch 1.4.x (CI: Align GHA and Windows Azure dependencies)
  azure-pipelines.yml
  ci/azure/windows.yml
  ci/deps/azure-windows-310.yaml
  ci/deps/azure-windows-38.yaml
  ci/deps/azure-windows-39.yaml
Labels: CI

#45859 Backport PR #45784 on branch 1.4.x (Regression: Series.loc.setitem raising with all false indexer and series on rhs)
  doc/source/whatsnew/v1.4.1.rst
  pandas/core/indexing.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Indexing, Regression

#45862 TST: Parameterize tests
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/sparse/test_indexing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/indexes/period/test_tools.py
  pandas/tests/io/parser/test_textreader.py
Labels: Testing

#45866 TST: Clean test_pickle
  pandas/tests/io/test_pickle.py
Labels: Testing

#45871 Pin scipy docs to 1.7.1 until 1.8 is available
  doc/source/conf.py
Labels: Docs

#45879 Backport PR #45872 on branch 1.4.x (CI/TST: add is_ci_environment to test_close_file_handle_on_invalid_usecols skip)
  pandas/tests/io/parser/test_unsupported.py
Labels: Testing, CI

#45873 Backport PR #45453 on branch 1.4.x (REF: move np_can_hold_element to mgr method)
  pandas/core/internals/base.py
  pandas/core/series.py
Labels: Refactor, Dtype Conversions

#45877 DOC: follow-up #45616, move release note from bugfix to regression section
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs, Dtype Conversions

#45878 DOC: restore SciPy intersphinx
  doc/source/conf.py
Labels: Docs

#45882 Backport PR #45877 on branch 1.4.x (DOC: follow-up #45616, move release note from bugfix to regression section)
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs, Dtype Conversions

#45883 Backport PR #45878 on branch 1.4.x (DOC: restore SciPy intersphinx)
  doc/source/conf.py
Labels: Docs

#45785 Regression: Loc raising when indexing mi with one level
  doc/source/whatsnew/v1.4.1.rst
  pandas/core/indexes/multi.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, Regression, MultiIndex

#45870 TST: add test Index.where infers dtype instead of converting string to float (#32413)
  pandas/tests/indexes/numeric/test_indexing.py
Labels: Testing

#45854 PERF: faster constructors from ea scalars
  asv_bench/benchmarks/frame_ctor.py
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/dtypes/cast.py
Labels: Performance, ExtensionArray, Constructors

#45852 PERF: use fast version of 1d-only checks
  pandas/core/frame.py
  pandas/core/groupby/ops.py
  pandas/core/internals/concat.py
Labels: Performance

#45880 DOC: examples for Styler.pipe
  doc/source/_static/style/df_pipe_applydata.png
  doc/source/_static/style/df_pipe_applymap.png
  doc/source/_static/style/df_pipe_hl.png
  doc/source/_static/style/df_pipe_hl2.png
  pandas/io/formats/style.py
Labels: Docs, Styler

#45844 BUG: Series[float32].__setitem__(int_cant_hold_in_int32) not coercing
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_fillna.py
Labels: Indexing, Dtype Conversions

#45817 REF: avoid ravel/reshape in astype_nansafe, ndarray_to_mgr
  pandas/core/construction.py
  pandas/core/dtypes/astype.py
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Refactor, Internals

#45849 REF: share NumericArray._arith_method with BooleanArray
  pandas/core/arrays/boolean.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numeric.py
  pandas/tests/arrays/boolean/test_arithmetic.py
  pandas/tests/arrays/masked/test_arithmetic.py
Labels: ExtensionArray

#45868 CI: Always run clipboard tests on GHA Linux
  .github/workflows/posix.yml
  ci/run_tests.sh
  pandas/tests/io/test_clipboard.py
Labels: CI

#45838 PERF: Merge empty frame
  asv_bench/benchmarks/join_merge.py
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Performance, Reshaping

#45887 Backport PR #45868 on branch 1.4.x (CI: Always run clipboard tests on GHA Linux)
  .github/workflows/posix.yml
  ci/run_tests.sh
  pandas/tests/io/test_clipboard.py
Labels: CI

#45886 CI: Debug ASV timeout
  environment.yml
  requirements-dev.txt
Labels: CI, Benchmark

#45891 Backport PR #45886 on branch 1.4.x (CI: Debug ASV timeout)
  environment.yml
  requirements-dev.txt
Labels: CI, Benchmark

#45895 Backport PR #45785 on branch 1.4.x (Regression: Loc raising when indexing mi with one level)
  doc/source/whatsnew/v1.4.1.rst
  pandas/core/indexes/multi.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, MultiIndex

#45893 DOC: 1.4.1 release notes (__setitem__/__getitem__ special methods are not a valid links/ref)
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45901 Backport PR #45893 on branch 1.4.x (DOC: 1.4.1 release notes (__setitem__/__getitem__ special methods are not a valid links/ref))
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45896 DOC: Imbalanced backticks.
  pandas/core/common.py
Labels: Docs

#45899 TST: Test change axis in boxplot
  pandas/tests/plotting/test_boxplot_method.py
Labels: Testing, Visualization

#45910 TST/CI: Set hypothesis deadline to None to avoid flaky failures
  pandas/conftest.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Testing, CI

#45923 DOC: add Python 3.10 to doc
  doc/source/getting_started/install.rst
Labels: Docs, Python 3.10

#45845 ENH: Index[complex]
  doc/source/whatsnew/v1.5.0.rst
  pandas/_libs/index.pyi
  pandas/_libs/index_class_helper.pxi.in
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/core/indexes/numeric.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/base/test_misc.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/methods/test_value_counts.py
Labels: Complex

#45918 Backport PR #45909 on branch 1.4.x (BUG: DateOffset(n) not defaulting to days)
  doc/source/whatsnew/v1.4.1.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Regression, Frequency

#45919 Backport PR #45910 on branch 1.4.x (TST/CI: Set hypothesis deadline to None to avoid flaky failures)
  pandas/conftest.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Testing, CI

#45927 Backport PR #45923 on branch 1.4.x (DOC: add Python 3.10 to doc)
  doc/source/getting_started/install.rst
Labels: Docs, Python 3.10

#45920 DOC: fix URLs, formatting and typos
  pandas/core/generic.py
  pandas/plotting/_core.py
  web/pandas/about/index.md
  web/pandas/community/ecosystem.md
Labels: Docs

#45312 BUG/ENH: Translate CSS border properties for `Styler.to_excel`
  doc/source/user_guide/style.ipynb
  doc/source/whatsnew/v1.5.0.rst
  pandas/io/formats/css.py
  pandas/io/formats/excel.py
  pandas/tests/io/excel/test_style.py
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_to_excel.py
Labels: IO Excel, Styler

#45906 TST: Use more pytest idioms in test_reductions, test_generic
  pandas/tests/frame/test_reductions.py
  pandas/tests/generic/test_generic.py
Labels: Testing

#45922 Backport PR #45853 on branch 1.4.x (Fixing documentation format in read_csv)
  pandas/io/parsers/readers.py
Labels: Docs

#45924 Backport PR #45633 on branch 1.4.x (DOC: Fix typo in nth docstring)
  pandas/core/groupby/groupby.py
Labels: Docs

#45911 REF: dispatch Block.fillna to putmask/where
  pandas/core/internals/blocks.py
Labels: Refactor, Internals

#45930 Backport PR #45920 on branch 1.4.x (DOC: fix URLs, formatting and typos)
  pandas/core/generic.py
  pandas/plotting/_core.py
  web/pandas/about/index.md
  web/pandas/community/ecosystem.md
Labels: Docs

#45925 BUG: rolling(axis=1).apply() raising ValueError
  doc/source/whatsnew/v1.4.1.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_apply.py
Labels: Window

#45936 DOC: 1.4.1 release date
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45939 Backport PR #45925 on branch 1.4.x (BUG: rolling(axis=1).apply() raising ValueError)
  doc/source/whatsnew/v1.4.1.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_apply.py
Labels: Window

#45940 DOC: minor tidy of 1.5 release notes
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs

#45587 DOC: append deprecation
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs, Blocker

#45941 Backport PR #45936 on branch 1.4.x (DOC: 1.4.1 release date)
  doc/source/whatsnew/v1.4.1.rst
Labels: Docs

#45942 Backport PR #45587 on branch 1.4.x (DOC: append deprecation)
  doc/source/whatsnew/v1.4.0.rst
  pandas/core/frame.py
  pandas/core/series.py
Labels: Docs

#45888 TST: add test for DataFrame with duplicate indices concat
  pandas/tests/reshape/concat/test_concat.py
Labels: Testing, Reshaping

#45837 BUG: DataFrame[dt64].where downcasting
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/boolean.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/dtypes/cast/test_downcast.py
  pandas/tests/frame/indexing/test_where.py
Labels: Missing-data, Dtype Conversions

#45938 DOC: Start v1.4.2 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.4.1.rst
  doc/source/whatsnew/v1.4.2.rst
Labels: Docs

#45900 Testcase Subtracting two series with unordered index and all-nan index produces unexpected result
  pandas/tests/indexing/multiindex/test_multiindex.py
Labels: Testing

#45947 DEPR: warn parameter in infer_freq
  doc/source/whatsnew/v1.5.0.rst
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tseries/frequencies.py
Labels: Frequency, Deprecate

#45960 Backport PR #45938 on branch 1.4.x (DOC: Start v1.4.2 release notes)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v1.4.1.rst
  doc/source/whatsnew/v1.4.2.rst
Labels: Docs

#45946 CI: Debug min build timing out
  .github/workflows/datamanger.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  azure-pipelines.yml
  ci/azure/posix.yml
  pandas/compat/pyarrow.py
  pandas/tests/base/test_unique.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_keys.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_retain_attributes.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/pytables/test_time_series.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/test_algos.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
  pyproject.toml
  test_fast.bat
  test_fast.sh
Labels: CI

#45950 CI: Set max job limit for test runs
  ci/azure/posix.yml
Labels: CI

#45974 Manual Backport PR #45946 on branch 1.4.x (CI: Debug min build timing out)
  .github/workflows/datamanger.yml
  .github/workflows/posix.yml
  .github/workflows/python-dev.yml
  azure-pipelines.yml
  ci/azure/posix.yml
  pandas/compat/pyarrow.py
  pandas/tests/base/test_unique.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_keys.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_retain_attributes.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/pytables/test_time_series.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/test_algos.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_online.py
  pyproject.toml
  test_fast.bat
  test_fast.sh
Labels: CI, Dependencies

#45976 TST: Inline once used variables & parameterize
  pandas/tests/apply/test_str.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/test_html.py
  pandas/tests/series/test_ufunc.py
  pandas/tests/test_multilevel.py
  pandas/tests/test_nanops.py
Labels: Testing

#45574 DEPR: datetimelike.astype(int_other_than_i8) return requested dtype
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/arrays/period/test_astype.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/indexes/datetimes/methods/test_astype.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/period/methods/test_astype.py
  pandas/tests/indexes/timedeltas/methods/test_astype.py
Labels: Timeseries, Deprecate

#45975 TST: Use pytest idioms in test_libsparse
  pandas/tests/arrays/sparse/test_libsparse.py
Labels: Testing

#45984 TST: Simplify test_register_writer
  pandas/tests/io/excel/test_writers.py
Labels: Testing, IO Excel, Clean

#45989 DOCS: Add comment about index_col and forward filling missing values
  doc/source/user_guide/io.rst
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#45897 BUG: Error reporting str.startswith and str.endswith
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_strings.py
Labels: Error Reporting, Strings

#45951 REF: share MaskedArray methods
  pandas/core/arrays/boolean.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numeric.py
Labels: Refactor

#45956 REF: avoid special-casing in SelectN
  pandas/core/algorithms.py
  pandas/core/arrays/masked.py
  pandas/core/dtypes/dtypes.py
Labels: Refactor

#45988 TST: Use fixture instead of setup_method in tests/array/categorical
  pandas/tests/arrays/categorical/common.py
  pandas/tests/arrays/categorical/conftest.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/sparse/test_constructors.py
  pandas/tests/arrays/sparse/test_unary.py
Labels: Testing

#45949 TST: Check network URL statuses in tests
  pandas/_testing/_io.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/xml/test_xml.py
Labels: Testing, IO Network

#45987 BUG: groupby.size and groupby.transform('size') incorrect for axis=1
  doc/source/whatsnew/v1.5.0.rst
  pandas/conftest.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_size.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Bug, Groupby

#45980 Backport PR #45950 on branch 1.4.x (CI: Set max job limit for test runs)
  ci/azure/posix.yml
Labels: CI

#45564 BUG: align not adding levels only on one side if intersection is equal
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_align.py
  pandas/tests/series/test_arithmetic.py
Labels: MultiIndex

#45992 TST: Clean tests/plotting
  pandas/plotting/_matplotlib/compat.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/plotting/common.py
  pandas/tests/plotting/conftest.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/frame/test_frame_groupby.py
  pandas/tests/plotting/frame/test_frame_subplots.py
  pandas/tests/plotting/frame/test_hist_box_by.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
Labels: Testing, Visualization

#45864 ENH: port time.pxd from cython
  pandas/_libs/tslibs/ctime.pyx
  pandas/tests/tslibs/test_api.py
  pandas/tests/tslibs/test_ctime.py
  setup.py
Labels: Non-Nano

#45928 DOC: How to use storage_option param here to integrate with GCP bucket?
  pandas/core/shared_docs.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odfreader.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_pyxlsb.py
  pandas/io/excel/_xlrd.py
  pandas/io/formats/xml.py
  pandas/io/xml.py
Labels: Docs, IO Data

#45996 TST: Use uuid instead of random chars for temp files
  pandas/_testing/contexts.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/pytables/conftest.py
  pandas/tests/io/test_pickle.py
Labels: Testing

#45995 CI: Add single_cpu build
  .github/workflows/posix.yml
  pandas/tests/io/parser/conftest.py
Labels: CI

#45993 Backport PR #45949 on branch 1.4.x (TST: Check network URL statuses in tests)
  pandas/_testing/_io.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/xml/test_xml.py
Labels: Testing, IO Network

#46005 Backport PR #45995 on branch 1.4.x (CI: Add single_cpu build)
  .github/workflows/posix.yml
  pandas/tests/io/parser/conftest.py
Labels: CI

#46016 CI: Unpin Cython on PyPy testing
  .github/workflows/posix.yml
Labels: CI, Dependencies

#45954 BUG: Fix implementation of temp_setattr
  pandas/core/common.py
  pandas/tests/test_common.py
Labels: Bug, Groupby

#46007 BUG: to_csv not respecting float_format for Float64
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/io/formats/test_to_csv.py
Labels: Bug, Output-Formatting, IO CSV

#45985 BUG: index.getitem raising ValueError with boolean indexer and NA
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/base_class/test_indexing.py
Labels: Indexing, Index

#46006 BUG: PeriodArray subtraction returning wrong results
  doc/source/whatsnew/v1.5.0.rst
  pandas/core/arrays/period.py
  pandas/tests/extension/test_period.py
Labels: Bug, Numeric Operations, Period

#45997 REF: Share NumericArray/NumericDtype methods
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numeric.py
  pandas/core/arrays/string_.py
  pandas/core/groupby/ops.py
  pandas/io/stata.py
  pandas/tests/frame/methods/test_astype.py
Labels: Refactor, NA - MaskedArrays

#45982 Test case dataframe.groupby incorrect with multiindex and None value
  pandas/tests/groupby/test_indexing.py
Labels: Testing, Groupby, MultiIndex

#46022 DOC: add note for ExtensionArray authors on relation between argmax/min and _values_for_argsort
  pandas/core/arrays/base.py
Labels: Docs, ExtensionArray

#46020 Backport PR #45983 on branch 1.4.x (REGR: drop raising with ea index and duplicates)
  doc/source/whatsnew/v1.4.2.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/series/methods/test_drop.py
Labels: Regression, ExtensionArray, Index

#46024 CI: Fix line sep issue in to_csv test
  pandas/tests/io/formats/test_to_csv.py
Labels: Output-Formatting, IO CSV, CI
