Repository pandas-dev/pandas, pull requests merged in 2022-11, with the labels that each got.

#49427 enable pylint wildcard-import
  pyproject.toml
Labels: Code Style

#49425 enable pylint unused-wildcard-import
  pyproject.toml
Labels: Code Style

#49437 CI: maybe fix docs build
  doc/source/whatsnew/v0.13.0.rst
Labels: Docs

#49422 CLN: test_expressions.py
  pandas/tests/test_expressions.py
Labels: Testing, Clean, expressions

#49424 TST: Remove unnecessary pytest fixture scopes
  pandas/tests/arithmetic/conftest.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/interval/test_interval_range.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/io/test_html.py
  pandas/tests/series/test_arithmetic.py
Labels: Testing, Clean

#49430 DEPR: Remove df.info(null_counts=)
  doc/source/user_guide/options.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/io/formats/info.py
  pandas/tests/io/formats/test_format.py
Labels: Deprecate

#49418 issue 48855 enable pylint unnecessary-pass
  pandas/core/computation/engines.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/multi.py
  pandas/core/interchange/dataframe_protocol.py
  pandas/io/excel/_base.py
  pandas/io/json/_json.py
  pandas/io/pytables.py
  pandas/io/stata.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/base/test_constructors.py
  pandas/tests/indexes/interval/test_constructors.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/util/test_deprecate.py
  pyproject.toml
  scripts/tests/test_validate_docstrings.py
Labels: Code Style

#49444 Backport PR #49437 on branch 1.5.x (CI: maybe fix docs build)
  doc/source/whatsnew/v0.13.0.rst
Labels: Docs

#49415 DEPR: non-keyword args, errors arg
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/io/html.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/io/test_html.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/strings/test_split_partition.py
Labels: Deprecate

#49377 BUG: Fix passing `Colormap` instance to plot methods with mpl >= 3.6
  doc/source/whatsnew/v1.5.2.rst
  pandas/io/formats/style.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/io/formats/style/test_matplotlib.py
Labels: Visualization, Regression

#49324 DEPR: SparseArray.astype
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/tests/arrays/sparse/test_astype.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/methods/test_append.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/test_ufunc.py
Labels: Deprecate, Astype

#48996 BUG: CoW - correctly track references for chained operations
  doc/source/whatsnew/v1.5.2.rst
  pandas/_libs/internals.pyx
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_internals.py
  pandas/tests/copy_view/test_methods.py
Labels: Bug, Copy / view semantics

#49429 DEPR: Enforce disallowed merging scenarios
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/frame/methods/test_join.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Deprecate

#49392 DEPR: internals
  ci/deps/actions-38-minimum_versions.yaml
  doc/source/whatsnew/v2.0.0.rst
  pandas/compat/_optional.py
  pandas/core/internals/__init__.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/__init__.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/test_downstream.py
Labels: Internals, Deprecate

#49381 DEPR: Timestamp(dt64obj, tz=tz)
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: Deprecate

#49446 API: Series([pydate, pydatetime])
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/series/test_constructors.py
Labels: Timeseries, Series, Constructors, datetime.date

#49451 Backport PR #48996 on branch 1.5.x (BUG: CoW - correctly track references for chained operations)
  doc/source/whatsnew/v1.5.2.rst
  pandas/_libs/internals.pyx
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_internals.py
  pandas/tests/copy_view/test_methods.py
Labels: Bug, Copy / view semantics

#49376 CLN: Remove xlrd < 2.0 code
  pandas/io/excel/_base.py
  pandas/io/excel/_xlrd.py
  pandas/tests/io/excel/__init__.py
  pandas/tests/io/excel/test_xlrd.py
Labels: IO Excel, Clean

#49401 DEPR: Enforce deprecation of silent dropping of nuisance columns in agg_list_like
  asv_bench/benchmarks/groupby.py
  doc/source/user_guide/basics.rst
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/apply.py
  pandas/core/groupby/generic.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/resample/test_resample_api.py
Labels: Deprecate, Apply, DataFrame

#49361 DEPR: DTA(float_data, dtype=dt64tz)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/datetimes.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/series/methods/test_astype.py
Labels: Deprecate

#49393 Make the conversion from dtype to subclass just a little faster
  pandas/core/indexes/base.py
Labels: Performance, Index

#49447 enable pylint: literal-comparison
  pyproject.toml
Labels: Code Style

#49460 (🎁) add python 3.11 to sdist.yml
  .github/workflows/sdist.yml
Labels: Build, CI

#49471 Backport PR #49460 on branch 1.5.x ((🎁) add python 3.11 to sdist.yml)
  .github/workflows/sdist.yml
Labels: Build, CI

#49461 DEPR: Remove check_less_precise in asserters
  doc/source/whatsnew/v2.0.0.rst
  pandas/_testing/asserters.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/util/test_assert_almost_equal.py
Labels: Deprecate

#49118 BUG: Return type discrepancy in USFederalHolidayCalendar
  doc/source/whatsnew/v2.0.0.rst
  pandas/tests/tseries/holiday/test_federal.py
  pandas/tests/tseries/holiday/test_holiday.py
  pandas/tseries/holiday.py
Labels: Frequency

#49426 CLN: assorted; silence test warnings
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/dtypes/astype.py
  pandas/core/dtypes/cast.py
  pandas/core/groupby/base.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/io/sas/sas.pyx
  pandas/tests/apply/test_str.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/pytables/test_subclass.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Clean

#49472 DEPR: enforce passing non boolean sort in concat
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_sort.py
Labels: Deprecate

#49470 STYLE Suppressing two instances of pylint W0703 broad-except.
  pandas/_testing/_io.py
  pandas/core/dtypes/cast.py
Labels: Code Style

#49464 STYLE: fix pylint no-else-continue warnings
  doc/source/conf.py
  pandas/core/indexes/multi.py
  pandas/core/reshape/merge.py
  pandas/io/formats/style_render.py
  pandas/io/json/_normalize.py
  pandas/tests/io/parser/common/test_common_basic.py
  pyproject.toml
Labels: Code Style

#49463 DEPR: Disallow kwargs in ExcelWriter
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_odswriter.py
  pandas/tests/io/excel/test_openpyxl.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/excel/test_xlsxwriter.py
Labels: Deprecate

#49458 DEPR: Index(ndarray[object]) inferring numeric dtype
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/ranges/test_constructors.py
Labels: Deprecate

#49455 DEPR: DatetimeIndex setops with mismatched tzs
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/api.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimes.py
  pandas/tests/indexes/datetimes/test_timezones.py
Labels: Deprecate

#49438 BUG: pivot_table with margins=T raises when results in empty df
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping

#49459 DEPR: inplace argument in set_axis
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_set_axis.py
  pandas/tests/generic/test_duplicate_labels.py
Labels: Deprecate

#49416 API: make some Timestamp args keyword-only
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: API Design, Timestamp

#49412 DEPR: indexing
  ci/deps/actions-38-minimum_versions.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/compat/_optional.py
  pandas/core/common.py
  pandas/core/indexers/__init__.py
  pandas/core/indexers/utils.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/series.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_indexing.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_indexing.py
Labels: Deprecate

#49476 CI maybe fix arm test
  pandas/core/arrays/datetimes.py
Labels: CI, ARM

#49379 issue 48855 enable pylint C-type "disallowed-name " warning
  asv_bench/benchmarks/attrs_caching.py
  pandas/io/formats/style.py
  pandas/plotting/_core.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/base/test_constructors.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/io/test_sql.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/reshape/concat/test_empty.py
  pandas/tests/reshape/concat/test_series.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/util/test_deprecate_nonkeyword_arguments.py
  pandas/tests/window/test_apply.py
  pandas/tests/window/test_groupby.py
  pyproject.toml
  scripts/tests/test_validate_docstrings.py
Labels: Code Style

#49488 CI: Remove GHA running on 1.4.x branch
  .github/workflows/32-bit-linux.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/macos-windows.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  .github/workflows/ubuntu.yml
Labels: CI

#49485 DEPR: Index.reindex with non-unique Index
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/tests/indexes/categorical/test_reindex.py
  pandas/tests/resample/test_datetime_index.py
Labels: Deprecate

#49495 Backport PR #49488 on branch 1.5.x (CI: Remove GHA running on 1.4.x branch)
  .github/workflows/32-bit-linux.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/macos-windows.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  .github/workflows/ubuntu.yml
Labels: CI

#48849 DEP: Enforce deprecations of read_csv keywords
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: IO CSV, Deprecate

#49378 API/BUG: Fix is_string_dtype and make more strict
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_string.py
Labels: Dtype Conversions, Strings

#49457 DEPR: Index methods, to_time, Categorical constructor
  asv_bench/benchmarks/index_cached_properties.py
  doc/redirects.csv
  doc/source/reference/indexing.rst
  doc/source/reference/series.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/base.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/multi.py
  pandas/core/tools/datetimes.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/categorical/test_constructors.py
  pandas/tests/indexes/datetimes/methods/test_to_frame.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tools/test_to_time.py
Labels: Deprecate

#49483 DEPR: HDFStore.iteritems, read_csv(use_cols) behavior
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/parsers.pyx
  pandas/io/excel/_base.py
  pandas/io/parsers/python_parser.py
  pandas/io/pytables.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
  pandas/tests/io/pytables/test_store.py
Labels: Deprecate

#49486 DEPR: Change str.replace(regex) from True to False & single behavior
  doc/source/user_guide/text.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_find_replace.py
Labels: Deprecate

#49480 enable pylint: consider-using-sys-exit
  pandas/tests/io/generate_legacy_storage_files.py
  pyproject.toml
Labels: Code Style

#49445 STYLE: enable pylint warnings for `cell-var-from-loop`
  pandas/core/strings/object_array.py
  pandas/io/pytables.py
  pandas/tests/io/parser/test_c_parser_only.py
  pyproject.toml
Labels: Code Style

#49474 TST: avoid chained assignment in tests outside of specific tests on chaining
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/series/methods/test_rank.py
Labels: Testing

#49454 DEPR: __setitem__ on dt64tz with mixed timezones
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslib.pyi
  pandas/_libs/tslib.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/indexes/datetimes/methods/test_insert.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_fillna.py
Labels: Deprecate

#49419 BUG: Unclear error message when merging tables and passing invalid option to validate
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/frame/methods/test_join.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Error Reporting

#49290 API: Series.astype(td64_unsupported) raise
  doc/source/user_guide/timedeltas.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/astype.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/indexes/timedeltas/methods/test_astype.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
  pandas/tests/indexing/test_loc.py
Labels: Dtype Conversions, Astype, Non-Nano

#49504 CI: fix flake8 warning
  pandas/core/indexes/category.py
Labels: CI

#49502 STYLE enable pylint: comparison-of-constants
  pandas/tests/io/parser/test_dialect.py
  pyproject.toml
Labels: Code Style

#49512 CI: Fix ASV post str.replace(regex) change
  asv_bench/benchmarks/inference.py
Labels: CI, Benchmark

#49428 UPGRADE: Autoupdate pre-commit config
  .pre-commit-config.yaml
  pandas/_libs/algos.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/internals.pyx
  pandas/_libs/join.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/testing.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/_libs/tslibs/vectorized.pyx
  pandas/_libs/window/aggregations.pyx
  pandas/errors/__init__.py
  pandas/io/clipboard/__init__.py
  pandas/io/sas/byteswap.pyx
  pandas/io/sas/sas.pyx
Labels: Code Style

#49515 STYLE: fix pylint consider-using-f-string issues
  asv_bench/benchmarks/io/hdf.py
  doc/scripts/eval_performance.py
  pandas/_version.py
  pandas/core/arraylike.py
  pandas/core/generic.py
  pandas/tests/config/test_config.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/io/excel/test_openpyxl.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/test_to_latex.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_html.py
  pyproject.toml
  versioneer.py
Labels: Code Style

#49517 STYLE/PERF: use f-strings instead of ''.join on static elements
  pandas/core/apply.py
  pandas/core/window/doc.py
  pandas/io/formats/css.py
Labels: Code Style

#49462 DEPR: Enforce melt(value_name) behavior
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/reshape/melt.py
  pandas/tests/reshape/test_melt.py
Labels: Deprecate

#49365 DEPR: Remove deprecated Timestamp.freq
  asv_bench/benchmarks/tslibs/timestamp.py
  doc/redirects.csv
  doc/source/reference/arrays.rst
  doc/source/whatsnew/v0.24.0.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/vectorized.pyi
  pandas/_libs/tslibs/vectorized.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_first_valid_index.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/datetimes/test_misc.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/test_pickle.py
  pandas/tests/reshape/concat/test_datetimes.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timestamp/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/scalar/timestamp/test_rendering.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_getitem.py
Labels: Deprecate

#49525 API: to_timedelta([bad_type]) TypeError instead of ValueError
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/indexes/base.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/datetimes/methods/test_astype.py
  pandas/tests/indexes/object/test_astype.py
  pandas/tests/indexes/timedeltas/test_constructors.py
Labels: Error Reporting, Timedelta

#49507 DEPR: enforce non-positional, keyword deprecations
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/series/methods/test_drop.py
  pandas/tests/series/methods/test_fillna.py
Labels: Deprecate

#49481 DEPR: lookup, append
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/join_merge.py
  doc/redirects.csv
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/user_guide/indexing.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/indexing/test_lookup.py
  pandas/tests/frame/methods/test_append.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/methods/test_append.py
Labels: Deprecate

#49478 CLN use default_index more
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/generic.py
  pandas/core/reshape/encoding.py
  pandas/core/reshape/merge.py
Labels: Index

#49533 STYLE pylint: 48855-duplicate-value
  pandas/tests/io/parser/test_parse_dates.py
  pyproject.toml
  scripts/validate_rst_title_capitalization.py
Labels: Code Style

#49511 DEPR: enforce indexing deprecations
  doc/source/whatsnew/v0.11.0.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/series.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_xs.py
Labels: Deprecate

#49537 CI fixup pylint ci failure
  pandas/core/dtypes/concat.py
Labels: CI

#49513 CLN: CategoricalIndex.reindex
  pandas/core/indexes/category.py
Labels: Categorical, Clean

#49546 DOC: replaced Gitter link with Slack link in README.
  README.md
Labels: Docs, good first issue, Community

#49366 ENH: Implement io.nullable_backend config for read_csv(engine="pyarrow")
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: Enhancement, IO CSV, Arrow

#49542 TYP: Series.groupby
  pandas/core/series.py
Labels: Typing

#49544 CI: Fix wheel builder uploading
  .github/workflows/wheels.yml
  ci/test_wheels.py
Labels: Build

#49547 CLN: Remove unused code in Factorizer classes
  pandas/_libs/hashtable.pyx
  pandas/tests/test_algos.py
Labels: Algos, Clean

#49559 CLN: MultiIndex._values remove special casing for Timestamp.freq
  pandas/core/indexes/multi.py
Labels: MultiIndex, Clean

#49518 STYLE/PERF: replace string concatenations with f-strings in core
  pandas/core/arrays/categorical.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/string_arrow.py
  pandas/core/computation/expr.py
  pandas/core/computation/parsing.py
  pandas/core/computation/scope.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/category.py
  pandas/core/indexes/interval.py
  pandas/core/interchange/column.py
  pandas/core/nanops.py
  pandas/core/ops/docstrings.py
Labels: Code Style

#49562 Fix pylint use-a-generator warning
  pandas/io/formats/css.py
  pyproject.toml
Labels: Code Style

#49402 DEPR: Enforce deprecation of na_sentinel
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/algorithms.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/core/indexes/range.py
  pandas/core/reshape/merge.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_extension.py
  pandas/tests/test_algos.py
  pandas/tests/test_sorting.py
Labels: Missing-data, Algos, Deprecate

#49564 STYLE: fix pylint consider-using-min-builtin warnings
  pandas/io/sas/sas7bdat.py
  pandas/plotting/_matplotlib/converter.py
  pyproject.toml
Labels: Code Style

#49550 CLN: Deduplicate code in duplicated
  pandas/_libs/hashtable_func_helper.pxi.in
Labels: Clean

#49442 BUG: MultiIndex.get_indexer not matching nan values
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/index.pyx
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexing/multiindex/test_multiindex.py
Labels: Indexing, Missing-data, MultiIndex

#49487 DEPR: maybe_promote with pydate
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/cast/test_promote.py
  pandas/tests/frame/methods/test_reindex.py
Labels: Deprecate

#49373 BUG: groupby with CategoricalIndex doesn't include unobserved categories
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/categorical.py
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
Labels: Groupby, Categorical

#49549 ENH: Support mask in Int64Factorizer
  pandas/_libs/hashtable.pyi
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/tests/test_algos.py
Labels: Reshaping, NA - MaskedArrays

#49548 REF: remove unreachable maybe_cast_to_datetime cases
  pandas/_libs/lib.pyi
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
Labels: Refactor

#49529 DOC: correctly format bullets in parameter descriptions for `fillna` methods
  pandas/core/arrays/base.py
  pandas/core/generic.py
Labels: Docs

#49503 DEPR: Index.__and__, __or__, __xor__
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/numeric/test_setops.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexes/timedeltas/test_setops.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_logical_ops.py
Labels: Deprecate, Index

#49025 pylint: disable invalid-repr-returned in Series.__repr__
  pandas/core/series.py
  pyproject.toml
Labels: Code Style

#49261 ENH: Add pre-commit check for setup.cfg options.extras_require
  ci/deps/actions-38-minimum_versions.yaml
  pandas/compat/_optional.py
  scripts/validate_min_versions_in_sync.py
  setup.cfg
Labels: Code Style

#49466 Fix memory leak with ujson module
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/src/ujson/python/objToJSON.c
  pandas/_libs/src/ujson/python/ujson.c
Labels: Performance, IO JSON

#49552 DEPR: enforce a bunch
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/sparse/array.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/tests/arrays/sparse/test_constructors.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/tools/test_to_timedelta.py
  pyproject.toml
Labels: Deprecate

#49530 DEPR: enforce Series.__setitem__ behavior with Float64Index and non-present int key
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/series.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Indexing, Deprecate

#49492 DEPR: DatetimeIndex indexing with mismatched tzawareness
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexing/test_datetime.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/methods/test_truncate.py
Labels: Deprecate

#49570 DEPR: Disallow Series.between(inclusive=bool)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_between.py
Labels: Deprecate

#49490 DEP: Enforce respecting group_keys in groupby.apply
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/resample/test_resample_api.py
Labels: Groupby, Deprecate, Apply

#49577 PERF: MultiIndex.isin
  asv_bench/benchmarks/multiindex_object.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/multi.py
Labels: Performance, MultiIndex

#49566 API: Index([NaT, None]) match Series([NaT, None])
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/indexes/test_index_new.py
Labels: Missing-data, Index, Constructors

#49540 BUG: NumericIndex.astype(complex) should return Index[complex]
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/common.py
Labels: Dtype Conversions, Index

#49588 REF: simplify maybe_convert_objects
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
Labels: Refactor

#49589 DEPR: Enforce deprecations
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_between_time.py
  pandas/tests/io/formats/test_to_markdown.py
  pandas/tests/series/methods/test_to_frame.py
Labels: Deprecate

#49596 PERF: df.groupby(categorical)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/categorical.py
Labels: Groupby, Performance, Categorical

#49591 REF: tighter typing in constructor functions
  pandas/core/construction.py
  pandas/core/frame.py
  pandas/core/internals/construction.py
Labels: Refactor

#49590 CLN: assorted
  asv_bench/benchmarks/tslibs/tslib.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_shift.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/indexes/datetimes/methods/test_snap.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/test_downstream.py
Labels: Clean

#49594 API: Index(object_dtype_bool_ndarray) retain object dtype
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_index_new.py
Labels: Dtype Conversions

#49574 BUG: Series(index=[]) should have dtype=object
  pandas/core/series.py
  pandas/tests/series/test_constructors.py
Labels: Series, Constructors

#49575 CLN: collect fastpath in Series.__init__
  pandas/core/series.py
Labels: Clean, Series, Constructors

#49558 BUG/PERF: MultiIndex.value_counts returning flat index
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/algorithms.py
  pandas/tests/base/test_value_counts.py
Labels: Performance, MultiIndex

#49509 CI: Change flaky to_excel test to use xlsxwriter
  pandas/tests/io/test_common.py
Labels: IO Excel, Unreliable Test

#49601 STYLE Enable Pylint statement import-self
  pyproject.toml
Labels: Code Style

#48877 TST: MultiIndex.get_indexer with na/missing
  doc/source/whatsnew/v2.0.0.rst
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_isin.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexing/multiindex/test_multiindex.py
Labels: Bug, Missing-data, MultiIndex

#49592 DEPR: Enforce DataFrame(list_with_categorical) deprecation
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/internals/construction.py
  pandas/tests/frame/test_constructors.py
Labels: Deprecate

#49551 DEPR: Enforce deprecation of numeric_only=None in DataFrame aggregations
  doc/source/whatsnew/v1.2.0.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_function.py
Labels: Deprecate, DataFrame, Reduction Operations

#49608 REF: remove infer_datetimelike_array
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/io/parsers/base_parser.py
  pandas/tests/dtypes/test_inference.py
Labels: Refactor

#49607 DEPR: Enforce deprecations in indexes/datetimes.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/datetimes.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_datetime.py
Labels: Deprecate

#49621 TST/CI: Follow up fix test_write_fspath_all
  pandas/tests/io/test_common.py
Labels: Testing, Unreliable Test

#49423 CLN: test_nanops.py
  pandas/tests/test_nanops.py
Labels: Testing, Clean

#49615 REGR: Better warning in pivot_table when dropping nuisance columns
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/util/test_rewrite_warning.py
  pandas/util/_exceptions.py
Labels: Reshaping, Warnings, Nuisance Columns

#49284 REGR: MultiIndex.join does not work for ea dtypes
  doc/source/whatsnew/v1.5.2.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_join.py
Labels: Regression, Index, NA - MaskedArrays

#49613 BUG: groupby with sort=False still sorts an ordered categorical
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/categorical.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/shared_docs.py
  pandas/tests/groupby/test_categorical.py
Labels: Bug, Groupby, Categorical

#49610 BUG: date_range with freq="C" (business days) return value changed on 1.5.0
  doc/source/whatsnew/v1.5.2.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/datetimes/test_date_range.py
Labels: Regression, Frequency

#48819 API: make Timestamp/Timedelta _as_unit public as_unit
  doc/source/reference/arrays.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/window/ewm.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/scalar/timestamp/test_timezones.py
  pandas/tests/scalar/timestamp/test_unary_ops.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Timedelta, Non-Nano, Timestamp

#49605 DEPR: Enforce Series(float_with_nan, dtype=inty)
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/construction.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/series/test_constructors.py
  pandas/tests/test_downstream.py
Labels: Deprecate

#49625 Backport PR #49610 on branch 1.5.x (BUG: date_range with freq="C" (business days) return value changed on 1.5.0)
  doc/source/whatsnew/v1.5.2.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/datetimes/test_date_range.py
Labels: Regression, Frequency

#49628 DEPR: Disallow missing nested label when indexing MultiIndex level
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/io/formats/style/test_style.py
Labels: Deprecate

#49262 BUG: groupby.nth should be a filter
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/base.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_nth.py
Labels: Bug, Groupby

#49614 CI: Updating website sync to new server
  .github/workflows/docbuild-and-upload.yml
Labels: Docs, CI, Web

#49639 for #49638 updated the doc
  doc/source/development/contributing.rst
Labels: Docs

#49627 Backport PR #49284 on branch 1.5.x (REGR: MultiIndex.join does not work for ea dtypes)
  doc/source/whatsnew/v1.5.2.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/multi/test_join.py
Labels: Reshaping, Regression

#49634 Backport PR #49614 on branch 1.5.x (CI: Updating website sync to new server)
  .github/workflows/docbuild-and-upload.yml
Labels: Docs, CI, Web

#49556 for gh-49508 changing Doc for DataFrame.astype
  pandas/core/generic.py
Labels: Docs

#49611 DEPR: Remove df.reduction(level)
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/stat_ops.py
  doc/source/whatsnew/v0.15.2.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_count_with_level_deprecated.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/groupby/test_allowlist.py
  pandas/tests/groupby/test_api_consistency.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/series/methods/test_count.py
  pandas/tests/series/test_reductions.py
  pandas/tests/test_multilevel.py
Labels: Deprecate

#49622 DEPR: Enforce default of numeric_only=False in DataFrame methods
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/frame/test_reductions.py
Labels: Deprecate, DataFrame, Nuisance Columns

#49645 STYLE: fix pylint reimported warnings
  pandas/_testing/__init__.py
  pandas/_testing/contexts.py
  pandas/core/generic.py
  pandas/io/sql.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/json/test_normalize.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/concat/test_datetimes.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/tseries/offsets/test_custom_business_month.py
  pyproject.toml
Labels: Code Style

#49666 STYLE: enable pylint useless-option-value
  pyproject.toml
Labels: Code Style

#49669 STYLE: fix pylints redefined-outer-name warnings
  pandas/core/dtypes/inference.py
  pandas/core/frame.py
Labels: Code Style

#49674 STYLE: fix pylint unnecessary-comprehension warnings
  asv_bench/benchmarks/reshape.py
  doc/source/conf.py
  doc/sphinxext/announce.py
  pandas/core/computation/expr.py
  pandas/io/xml.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexes/categorical/test_map.py
  pandas/tests/io/test_sql.py
  pandas/tests/series/methods/test_replace.py
  pyproject.toml
Labels: Code Style

#49675 STYLE: Fixed redefined-outer-name linting issue
  pandas/core/indexes/datetimes.py
  pandas/io/formats/xml.py
  pandas/io/json/_table_schema.py
Labels: Code Style

#49662 STYLE: fix pylint redefined-outer-name warnings (#49656)
  pandas/core/arrays/datetimelike.py
  pandas/core/base.py
  pandas/core/computation/pytables.py
Labels: Code Style

#49681 DOC: Update interpolation docstring
  pandas/core/generic.py
Labels: Docs, Numeric Operations

#49587 TYP:Replace union of subclasses with base class.
  pandas/io/sql.py
Labels: IO SQL, Typing

#49671 STYLE enable pylint's redefined-outer-name
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/base.py
Labels: Code Style

#49676 REGR: Remove groupby's __getattribute__ for nth
  doc/source/whatsnew/v1.5.2.rst
  pandas/core/groupby/groupby.py
  pandas/core/groupby/indexing.py
Labels: Groupby, Performance, Regression

#49224 ADM/WEB: Update CoC committee members
  web/pandas/config.yml
Labels: Admin, Web

#48940 STYLE: Fix Pylint Style Checks For used-before-assignment
  pandas/_version.py
  pandas/core/arrays/sparse/array.py
  pandas/core/dtypes/common.py
  pandas/core/groupby/indexing.py
  pandas/core/tools/datetimes.py
  pandas/io/formats/style.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/pytables/test_store.py
  pyproject.toml
  versioneer.py
Labels: Code Style

#49395 BUG: Fixing DataFrame.Update crashes when NaT present
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_update.py
Labels: DataFrame

#49557 ENH/CoW: use lazy copy in set_index method
  pandas/core/frame.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#49708 for issue #49656 STYLE enable pylint's redefined-outer-name
  pandas/core/generic.py
Labels: Code Style

#49720 Suppress spurious warning
  pandas/core/frame.py
  pandas/tests/frame/methods/test_update.py
Labels: Warnings

#49689 ENH: Add copy-on-write to `DataFrame.drop`
  pandas/core/generic.py
  pandas/core/internals/array_manager.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#49705 Backport PR #49676 on branch 1.5.x (REGR: Remove groupby's __getattribute__ for nth)
  doc/source/whatsnew/v1.5.2.rst
  pandas/core/groupby/groupby.py
  pandas/core/groupby/indexing.py
Labels: Groupby, Performance, Regression
