Repository pandas-dev/pandas, pull requests merged in 2023-01, with the labels that each got.

#50493 CLN avoid some upcasting when its not the purpose of the test
  pandas/tests/frame/methods/test_equals.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/series/methods/test_replace.py
Labels: Clean

#50415 ENH: add lazy copy (CoW) mechanism to rename_axis
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50305 CLN: clean IntervalArray._simple_new
  pandas/_typing.py
  pandas/core/arrays/interval.py
Labels: Interval

#50468 used regular expression in `format_is_iso()`
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/strptime.pyx
Labels: Timeseries, Performance

#50478 ENH: Add lazy copy to swaplevel
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50490 ENH: Add lazy copy for tz_convert and tz_localize
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50491 ENH: Add lazy copy for sort_index
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50472 ENH: Add lazy copy for series.reorder_levels
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50311 DOC: Add to the io documentation of `on_bad_lines` to alert users of silently skipped lines.
  doc/source/user_guide/io.rst
Labels: Docs, IO CSV

#50529 WARN improve some warnings introduced in PDEP4
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/tslibs/test_parsing.py
Labels: Warnings

#50219 ENH: handle nonexistent shift for ZoneInfo
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/series/methods/test_tz_localize.py
Labels: Timezones

#50049 DOC: Improve groupby().ngroup() explanation for missing groups
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#50470 DOC: Add Copy on write whatsnew
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs, Copy / view semantics

#50489 TST: Test cow for set_flags
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50494 DOC: Fix some doctest errors
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/shared_docs.py
  pandas/core/window/doc.py
Labels: Docs

#50532 REF: move _validate_frequency to more accurate subclass
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/indexes/datetimelike.py
Labels: Refactor, Frequency

#48888 BUG: histogram weights aren't dropped if NaN values in data
  doc/source/whatsnew/v2.0.0.rst
  pandas/plotting/_matplotlib/hist.py
  pandas/tests/plotting/test_hist_method.py
Labels: Visualization

#50533 BUG: to_datetime incorrect OverflowError
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Timeseries

#50524 PERF: ArrowExtensionArray comparison methods
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/arrow/array.py
Labels: Performance, Arrow

#50521 Update doc for pd.MultiIndex.droplevel to reflect inplace behaviour
  pandas/core/indexes/base.py
Labels: Docs, MultiIndex

#50507 BUG: DataFrameGroupBy.value_counts fails with a TimeGrouper
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_frame_value_counts.py
  pandas/tests/groupby/test_value_counts.py
Labels: Groupby, Algos

#50375 ENH: Preserve ea dtype in groupby.std
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Groupby, NA - MaskedArrays

#50175 BUG: isetitem coercing df columns to object
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_isetitem.py
Labels: Indexing, DataFrame, NA - MaskedArrays

#50085 BUG: unwrap setitem indexer for ArrowExtensionArray
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/tests/extension/base/setitem.py
Labels: Bug, Indexing, Arrow

#50540 CLN explicit casts to float to avoid implicit casts
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_asfreq.py
  pandas/tests/frame/methods/test_asof.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/test_value_counts.py
Labels: Clean

#50477 ENH: Add lazy copy for truncate
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/methods/test_truncate.py
Labels: Copy / view semantics

#50546 Backport PR #50470 on branch 1.5.x (DOC: Add Copy on write whatsnew)
  doc/source/whatsnew/v1.5.0.rst
Labels: Docs, Copy / view semantics

#50544 CI fix typing with latest ipython
  pandas/io/formats/printing.py
Labels: CI, Typing

#50551 Backport PR #50485 on branch 1.5.x (CI/WEB: Adding cache for maintainers' github info)
  .github/workflows/docbuild-and-upload.yml
  web/pandas_web.py
Labels: CI, Web

#50460 TST: Verify mask's return keeps dtype
  pandas/tests/frame/indexing/test_mask.py
Labels: Indexing

#50545 BUG: Follow-up with Timestamp(nanoseconds) keyword only
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Bug, Timestamp

#50474 DOC: Add pyarrow type equivalency table
  doc/source/reference/arrays.rst
Labels: Docs, Arrow

#50530 BUG: Fix creating DatetimeIndex with BusinessHour Frequency
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_business_hour.py
Labels: Timeseries, Frequency

#50440 BUG: Fix issue where df.groupby.resample.size returns wide DF instead of MultiIndex Series.
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Groupby

#50559 REF: refactor describe.py into the methods folder
  pandas/core/generic.py
  pandas/core/methods/describe.py
Labels: Refactor

#50516 CLN/TST: test_series_align_multiindex_containing_nan
  pandas/tests/indexing/multiindex/test_multiindex.py
Labels: Testing, Clean

#50500 ENH: Add use_nullable_dtypes to read_xml
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/ops.pyx
  pandas/io/xml.py
  pandas/tests/io/xml/test_xml.py
Labels: Enhancement, IO XML

#50555 Backport PR #50544 on branch 1.5.x (CI fix typing with latest ipython)
  pandas/io/formats/printing.py
Labels: CI, Typing

#50562 CI Ipython ci fixup again
  pandas/io/formats/printing.py
Labels: CI

#50566 CI: Make some builds contents read only
  .github/workflows/codeql.yml
  .github/workflows/wheels.yml
Labels: Build, CI

#50552 ENH: test CoW for drop_level
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50568 Backport PR #50562 on branch 1.5.x (CI Ipython ci fixup again)
  pandas/io/formats/printing.py
Labels: CI

#50519 Revert "STYLE use pandas-dev-flaker (#40906)
  .pre-commit-config.yaml
  asv_bench/benchmarks/pandas_vb_common.py
  doc/scripts/eval_performance.py
  doc/source/development/contributing_codebase.rst
  doc/source/whatsnew/v1.4.0.rst
  environment.yml
  pandas/__init__.py
  pandas/_libs/lib.pyx
  pandas/_testing/__init__.py
  pandas/compat/__init__.py
  pandas/compat/compressors.py
  pandas/core/arrays/string_arrow.py
  pandas/core/generic.py
  pandas/core/interchange/dataframe.py
  pandas/core/internals/managers.py
  pandas/core/strings/base.py
  pandas/core/strings/object_array.py
  pandas/core/window/ewm.py
  pandas/io/common.py
  pandas/io/json/_json.py
  pandas/io/xml.py
  pandas/tests/api/test_api.py
  pandas/tests/arrays/boolean/test_function.py
  pandas/tests/io/formats/style/test_style.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_pickle.py
  requirements-dev.txt
  scripts/check_for_inconsistent_pandas_namespace.py
  scripts/sync_flake8_versions.py
  scripts/tests/test_inconsistent_namespace_check.py
  scripts/tests/test_sync_flake8_versions.py
  scripts/tests/test_validate_unwanted_patterns.py
  scripts/validate_unwanted_patterns.py
  setup.cfg
Labels: Code Style

#50329 BUG: idxmin & idxmax axis = 1 str reducer for transform
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Bug, Groupby, Apply

#50574 CLN: MultiIndex._union
  pandas/core/indexes/multi.py
  pandas/tests/frame/methods/test_combine_first.py
Labels: MultiIndex

#50447 PERF: ArrowExtensionArray.searchsorted
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
Labels: Performance, Arrow

#50506 BUG: to_numpy not respecting na_value before converting to array
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/base.py
  pandas/tests/series/methods/test_to_numpy.py
Labels: Missing-data, NA - MaskedArrays

#50503 ENH: Add pandas nullable support to read_orc
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/_util.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/tests/io/test_orc.py
Labels: Enhancement, IO Data

#50576 DEPR: Remove silent dropping of nuisance columns in window ops
  asv_bench/benchmarks/rolling.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_api.py
  pandas/tests/window/test_dtypes.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_numba.py
Labels: Deprecate, Window

#50572 BUG: is_numeric_dtype(ArrowDtype[numeric]) not returning True
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/io/json/test_json_table_schema_ext_dtype.py
Labels: Bug, Arrow

#50590 TST: Test squeeze with CoW
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50596 CI: Fix pre-commit
  scripts/validate_unwanted_patterns.py
Labels: CI

#50591 CI: Temporary pin sqlalchemy
  ci/deps/actions-310.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-38-arm64.yaml
  environment.yml
  requirements-dev.txt
Labels: CI

#50602 Backport PR #50591 on branch 1.5.x (CI: Temporary pin sqlalchemy)
  ci/deps/actions-310.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-38-arm64.yaml
  environment.yml
  requirements-dev.txt
Labels: CI

#50592 ENH: Add fast array equal function for indexers
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/tests/libs/test_lib.py
Labels: Copy / view semantics

#50567 ENH: Add lazy copy to pipe
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50502 ENH: Add use_nullable_dtypes to read_clipboard
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/clipboards.py
  pandas/io/parsers/readers.py
  pandas/tests/io/test_clipboard.py
Labels: Enhancement, IO Data

#50604 DOC: add example to Interval.mid docstring
  pandas/_libs/interval.pyx
Labels: Docs, Interval

#50599 DOC: Fix doc for DataFrame.plot subplots argument
  pandas/plotting/_core.py
Labels: Docs, Visualization

#50586 BUG: parsing mixed-offset Timestamps with errors='ignore' and no format raises
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslib.pyx
  pandas/tests/tools/test_to_datetime.py
Labels: Bug, Timeseries

#49706 Bug: Fix Inconsistent Behavior for Series.searchsorted
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/base.py
  pandas/tests/series/methods/test_searchsorted.py
Labels: Error Reporting, Series, Stale

#50605 CLN More float warnings
  pandas/tests/series/methods/test_asof.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/tools/test_to_datetime.py
Labels: Clean

#50589 TST: Copy on Write for filter
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50116 Standard library imports style check
  pandas/tests/apply/test_series_apply.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_to_records.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/formats/test_printing.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_index.py
  pandas/tests/reshape/test_get_dummies.py
  pandas/tests/series/test_arithmetic.py
Labels: Code Style

#50565 BUG: Fix more interchange Column.size method
  pandas/core/interchange/column.py
  pandas/core/interchange/dataframe_protocol.py
  pandas/core/interchange/from_dataframe.py
Labels: Interchange

#50475 BUG: loc.setitem coercing rhs df dtypes
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, Dtype Conversions

#50610 Backport PR #50565 on branch 1.5.x (BUG: Fix more interchange Column.size method)
  pandas/core/interchange/dataframe_protocol.py
  pandas/core/interchange/from_dataframe.py
Labels: Interchange

#50608 DEPR: Remove pandas.io.json.json_normalize in favor of pd.json_normalize
  doc/source/whatsnew/v2.0.0.rst
  pandas/__init__.py
  pandas/io/json/__init__.py
  pandas/io/json/_normalize.py
  pandas/tests/io/json/test_normalize.py
  scripts/validate_unwanted_patterns.py
Labels: Deprecate

#50613 PERF: BooleanArray._from_sequence_of_strings
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/boolean.py
  pandas/tests/extension/test_arrow.py
Labels: Performance

#50620 PERF: IntervalArray.from_tuples
  asv_bench/benchmarks/array.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/interval.py
Labels: Performance, Interval

#50612 DEPR: Enforce disallowing 2 positional args in DataFrame.reindex
  doc/source/whatsnew/v2.0.0.rst
  pandas/tests/frame/methods/test_reindex.py
  pandas/util/_validators.py
Labels: Deprecate

#50623 PERF: groupby.any/all with object dtype
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/groupby.py
Labels: Groupby, Performance

#50619 DOC: improve Timestamp properties docstrings
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs, Timestamp

#50609 DOC: update docstrings of Interval's attributes
  pandas/_libs/interval.pyx
Labels: Docs, Interval

#50509 DOC: Add ignore_functions option to validate_docstrings.py
  ci/code_checks.sh
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs, CI, Code Style

#50637 DOC: Fix column alignment in df.mul docstring
  pandas/core/ops/docstrings.py
Labels: Docs

#50148 PERF: Split blocks in blk.delete
  asv_bench/benchmarks/indexing.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/internals/test_internals.py
Labels: Performance, Internals

#50629 REF: avoid catching and re-raising in datetime parsing
  pandas/_libs/tslibs/conversion.pyx
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/scalar/timestamp/test_constructors.py
Labels: Refactor, datetime.date

#50640 DOC: fix code in groupby documentation
  doc/source/user_guide/groupby.rst
  pandas/core/arrays/datetimes.py
Labels: Docs

#50631 CLN: Consolidate groupby.value_counts tests
  pandas/tests/groupby/test_frame_value_counts.py
  pandas/tests/groupby/test_value_counts.py
Labels: Testing, Groupby, Algos, Clean

#50642 ENH/BUG: preserve non-nano in NaT subtraction
  pandas/core/arrays/datetimelike.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Non-Nano

#50635 BUG: groupby with empty object, categorical grouper, and dropna=False fails
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby, Missing-data, Categorical

#50622 ENH: guess ISO8601 formats without separators
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tslibs/test_parsing.py
Labels: Enhancement, Timeseries

#50606 REGR: Fix regression in to_numpy
  pandas/core/base.py
  pandas/tests/series/methods/test_to_numpy.py
Labels: Bug, Regression

#50594 DOC: Add missing attributes and methods to MultiIndex API documentation
  doc/source/reference/indexing.rst
  pandas/core/indexes/multi.py
Labels: Docs, MultiIndex

#50571 TYP: Better numeric test types
  pandas/_testing/__init__.py
  pandas/conftest.py
Labels: Testing, Typing

#50549 REF: handle 2D in array_to_datetime
  pandas/_libs/tslib.pyx
  pandas/core/arrays/datetimes.py
Labels: Refactor, datetime.date

#50526 DOC: Add groupby-specific docstrings for take
  pandas/core/groupby/generic.py
Labels: Docs, Groupby

#50471 DOC: Add note about copy on write improvements
  doc/source/whatsnew/v2.0.0.rst
Labels: Docs, Copy / view semantics

#49642 DOC: Gitpod documentation
  doc/source/development/contributing.rst
  doc/source/development/contributing_codebase.rst
  doc/source/development/contributing_documentation.rst
  doc/source/development/contributing_environment.rst
  doc/source/development/contributing_gitpod.rst
  doc/source/development/gitpod-imgs/gitpod-dashboard-stop.png
  doc/source/development/gitpod-imgs/gitpod-edit-permissions-gh.png
  doc/source/development/gitpod-imgs/gitpod-edit-permissions-repo.png
  doc/source/development/gitpod-imgs/gitpod-workspace.png
  doc/source/development/gitpod-imgs/pandas-github.png
  doc/source/development/gitpod-imgs/pandas-gitpod-branches.png
  doc/source/development/gitpod-imgs/rst-rendering.png
  doc/source/development/gitpod-imgs/vscode-rst.png
  doc/source/development/gitpod-imgs/vscode-statusbar.png
  scripts/validate_rst_title_capitalization.py
Labels: Docs

#50369 ENH/API: preserve non-nano in to_datetime
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/core/reshape/tile.py
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Non-Nano

#50370 Rename duplicate column names in read_json(orient='split')
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/common.py
  pandas/io/json/_json.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON

#50505 ENH: Add use_nullable_dtypes to to_numeric
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/lib.pyx
  pandas/core/tools/numeric.py
  pandas/tests/tools/test_to_numeric.py
Labels: NA - MaskedArrays

#50616 ENH: DTI/TDI as_unit
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/datetimelike.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/indexes/datetimes/methods/test_snap.py
  pandas/tests/series/test_constructors.py
Labels: Enhancement, Timestamp

#50195 API: ensure IntervalIndex.left/right are 64bit if numeric, part II
  pandas/core/arrays/interval.py
  pandas/core/dtypes/cast.py
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval.py
Labels: Interval

#50648 DEPR: Remove DeprecationWarnings
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/tests/base/test_misc.py
  pandas/tests/indexes/test_base.py
  pandas/tests/test_downstream.py
Labels: Deprecate

#50647 Fix docstring for layout parameter of boxplot
  pandas/plotting/_core.py
Labels: Docs

#50160 DEV/STYLE: use ruff for linting
  .pre-commit-config.yaml
  doc/source/development/contributing_codebase.rst
  environment.yml
  pandas/core/computation/pytables.py
  pandas/core/generic.py
  pandas/core/reshape/merge.py
  pandas/io/formats/latex.py
  pandas/io/formats/style.py
  pandas/io/parsers/python_parser.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/period/test_indexing.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/test_html.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/util/_doctools.py
  pyproject.toml
  requirements-dev.txt
  scripts/no_bool_in_generic.py
  scripts/sync_flake8_versions.py
  scripts/tests/test_sync_flake8_versions.py
  setup.cfg
Labels: Code Style

#50662 improved description of mamba section
  doc/source/development/contributing_environment.rst
Labels: Docs

#50659 DOC: Fix some RT02 issues in docstrings
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
Labels: Docs

#50663 DOC: Improve wording for DataFrame.rename summary
  pandas/core/frame.py
Labels: Docs, Sprints

#50661 DOC: add default encoding to read_csv
  pandas/io/parsers/readers.py
Labels: Docs, Sprints

#50548 BUG/PERF: SeriesGroupBy.value_counts sorting bug and categorical performance
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_value_counts.py
Labels: Bug, Groupby, Performance, Algos

#50665 Add test for checking inconsistencies for large series using Series.rmod
  pandas/tests/series/test_arithmetic.py
Labels: Numeric Operations, Sprints

#50575 ENH: Add lazy copy to to_timestamp and to_period
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/copy_view/util.py
Labels: Copy / view semantics

#50675 CLN: fix and move using_copy_on_write() helper out of internals
  pandas/_config/__init__.py
  pandas/core/generic.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  scripts/validate_unwanted_patterns.py
Labels: Clean

#49715 API: dtlike.astype(inty)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/core/dtypes/astype.py
  pandas/tests/arrays/period/test_astype.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/indexes/datetimes/methods/test_astype.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/period/methods/test_astype.py
  pandas/tests/indexes/timedeltas/methods/test_astype.py
  pandas/tests/series/test_constructors.py
Labels: Dtype Conversions, Timedelta, Period, Astype, Timestamp

#50679 Update eval_performance.py
  doc/scripts/eval_performance.py
Labels: Docs

#50680 DOC: Add note in 1.5.3 about SQLAlchemy warnings
  doc/source/whatsnew/v1.5.3.rst
Labels: Docs, IO SQL

#50683 BUG: is_any_int_dtype not recognizing arrow integers
  pandas/core/dtypes/common.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#50664 TST: ro_replace changing dtype of series
  pandas/tests/series/methods/test_replace.py
Labels: replace, Sprints

#50700 Backport PR #49386 on branch 1.5.x (DOC: add name parameter to the IntervalIndex for #48911)
  pandas/core/arrays/interval.py
  pandas/core/indexes/interval.py
Labels: Docs

#50698 CI capture error in numpy dev, fix python-dev build
  .github/workflows/python-dev.yml
  pandas/tests/frame/test_unary.py
Labels: CI

#50676 DEPR: ADD FutureWarning for pandas.io.execute
  doc/source/whatsnew/v2.0.0.rst
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL, Deprecate

#50705 Backport PR #50698 on branch 1.5.x (CI capture error in numpy dev, fix python-dev build)
  .github/workflows/python-dev.yml
  pandas/tests/frame/test_unary.py
Labels: CI

#50677 TEST: added test case for issue 41800
  pandas/tests/series/methods/test_combine_first.py
Labels: Testing

#50706 Revert "CI temporarily pin numpy"
  asv_bench/asv.conf.json
  ci/deps/actions-310-numpydev.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-38.yaml
  ci/deps/circle-38-arm64.yaml
  environment.yml
  pandas/util/_test_decorators.py
  requirements-dev.txt
Labels: Dependencies

#50697 add multi index with categories test
  pandas/tests/indexes/multi/test_setops.py
Labels: Testing

#50685 BUG: Series.quantile emitting RuntimeWarning for all NA case
  doc/source/whatsnew/v1.5.3.rst
  pandas/core/array_algos/quantile.py
  pandas/core/arrays/masked.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/series/methods/test_quantile.py
Labels: Bug, quantile, NA - MaskedArrays

#50686 TST: Fix test_constructor_signed_int_overflow_deprecation w/ multiple warnings
  pandas/tests/series/test_constructors.py
Labels: Testing

#50651 Improve error message if attempting to construct multidimensional series
  pandas/core/construction.py
  pandas/tests/series/test_constructors.py
Labels: Error Reporting, Series

#50644 CLN: assorted
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/parsing.pyi
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/apply.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/dtypes/cast.py
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/numeric.py
  pandas/core/indexing.py
  pandas/io/parsers/base_parser.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/tslibs/test_parsing.py
Labels: Clean

#50653 ENH: Added explicit arguments in DataFrameGroupBy.describe by replacing **…
  pandas/core/groupby/groupby.py
Labels: Groupby

#50692 TST: CoW with df.isetitem()
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50573 ENH: Add lazy copy for swapaxes no op
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50611 BUG/ENH: infer_freq with non-nano
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tseries/frequencies.py
Labels: Enhancement, Frequency

#50614 CLN/BUG: Allow assert_produces_warning to raise during an exception
  pandas/_libs/tslibs/offsets.pyx
  pandas/_testing/_warnings.py
  pandas/core/arrays/datetimes.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/interval/test_base.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/test_stata.py
  pandas/tests/reshape/concat/test_append_common.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/methods/test_convert_dtypes.py
  pandas/tests/series/test_constructors.py
  pandas/tests/test_algos.py
  pandas/tests/util/test_assert_produces_warning.py
Labels: Clean, Warnings

#50674 CLN: Remove 3rd party warning filters
  pandas/io/parquet.py
  pandas/tests/frame/test_unary.py
  pandas/tests/io/__init__.py
  pandas/tests/io/excel/__init__.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/pytables/__init__.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/pytables/test_subclass.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/test_downstream.py
  pandas/tests/util/test_show_versions.py
  pandas/tests/window/__init__.py
  pandas/util/_test_decorators.py
  pyproject.toml
Labels: Testing, Warnings

#50476 ENH: Add lazy copy for take and between_time
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50630 BUG: Fix bug in putmask for CoW
  doc/source/whatsnew/v1.5.3.rst
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50718 Backport PR #50685 on branch 1.5.x (BUG: Series.quantile emitting RuntimeWarning for all NA case)
  doc/source/whatsnew/v1.5.3.rst
  pandas/core/array_algos/quantile.py
  pandas/core/arrays/masked.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/series/methods/test_quantile.py
Labels: Bug, quantile, NA - MaskedArrays

#50726 Backport PR #50685 on branch 1.5.x (BUG: Fix bug in putmask for CoW)
  doc/source/whatsnew/v1.5.3.rst
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50128 Backport PR #49771 on branch 1.5.x (PERF: Use fastpath for accessing option value in internals)
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_internals.py
Labels: Performance

#49450 API / CoW: always return new objects for column access (don't use item_cache)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/series.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/methods/test_sort_values.py
Labels: Copy / view semantics

#50728 CI fix failing python-dev job
  .github/workflows/python-dev.yml
Labels: CI

#50731 Backport PR #50728 on branch 1.5.x (CI fix failing python-dev job)
  .github/workflows/python-dev.yml
Labels: CI

#50729 TST: mark copy_view test_switch_options test as single_cpu
  pandas/tests/copy_view/test_internals.py
Labels: Testing

#50643 ENH: Add lazy copy for sort_values
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/methods/test_sort_values.py
Labels: Copy / view semantics

#50719 BUG: .max() gives wrong answer for non-nanosecond datetimeindex
  pandas/core/nanops.py
  pandas/tests/arrays/datetimes/test_reductions.py
  pandas/tests/test_nanops.py
Labels: Bug, Non-Nano

#50429 ENH: Use lazy copy for dropna
  pandas/core/frame.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#50668 BUG: Timestamp parsing creating invalid object
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
Labels: Timestamp

#49524 API / CoW: constructing Series from Series creates lazy copy (with default copy=False)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/series.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_indexing.py
Labels: Copy / view semantics

#50722 REF: stricter typing, better naming in parsing.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/parsing.pyi
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/core/indexes/datetimelike.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tslibs/test_parsing.py
Labels: Timeseries, Typing

#50707 DOC: added installation instructions for nightly build
  .github/ISSUE_TEMPLATE/bug_report.yaml
  doc/source/getting_started/install.rst
Labels: Docs

#50396 BUG/COMPAT: fix assert_* functions for nested arrays with latest numpy
  doc/source/whatsnew/v1.5.3.rst
  pandas/core/dtypes/missing.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/util/test_assert_almost_equal.py
Labels: Testing, Compat

#50723 TST: Cleanup more warning filtering
  pandas/conftest.py
  pandas/core/nanops.py
  pandas/tests/arrays/floating/test_function.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/io/excel/test_xlsxwriter.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_retain_attributes.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_sql.py
  pandas/tests/window/test_win_type.py
Labels: Testing, Warnings

#50297 Use ea interface to calculate accumulator functions for datetimelike
  pandas/core/array_algos/datetimelike_accumulations.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/timedeltas.py
  pandas/core/nanops.py
  pandas/tests/arrays/datetimes/test_cumulative.py
  pandas/tests/arrays/timedeltas/test_cumulative.py
  pandas/tests/series/test_cumulative.py
Labels: Timeseries, Timedelta

#50669 ENH: fix a bunch of pyarrow duration xfails
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Timedelta, Arrow

#50739 Backport PR #50396 on branch 1.5.x (BUG/COMPAT: fix assert_* functions for nested arrays with latest numpy)
  doc/source/whatsnew/v1.5.3.rst
  pandas/core/dtypes/missing.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/util/test_assert_almost_equal.py
Labels: Testing, Compat

#50176 DEPR: deprecate Index.is_boolean
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/indexes/base.py
  pandas/tests/base/common.py
  pandas/tests/indexes/common.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/test_loc.py
Labels: Deprecate, Index
