Repository pandas-dev/pandas, pull requests merged in 2023-03, with the labels that each got.

#51699 Backport PR #51659 on branch 2.0.x (ENH: Improve replace lazy copy for categoricals)
  pandas/core/internals/blocks.py
  pandas/tests/copy_view/test_replace.py
Labels: replace, Copy / view semantics

#51669 ENH: Add CoW mechanism to replace_regex
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_replace.py
Labels: replace, Copy / view semantics

#51713 Backport PR #51669 on branch 2.0.x (ENH: Add CoW mechanism to replace_regex)
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_replace.py
Labels: replace, Copy / view semantics

#51714 Backport PR #50778 on branch 2.0.x (PERF: Use generator expression for Blocks.replace_list)
  asv_bench/benchmarks/series_methods.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/series/methods/test_replace.py
Labels: Performance

#51701 ERR: Add explicit error message for isetitem for DataFrame
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_isetitem.py
Labels: Indexing, Error Reporting

#51454 DOC: Add user guide section about copy on write
  doc/source/development/copy_on_write.rst
  doc/source/user_guide/copy_on_write.rst
  doc/source/user_guide/index.rst
  doc/source/whatsnew/v2.0.0.rst
Labels: Docs, Copy / view semantics

#51319 ENH: EA._hash_pandas_object
  ci/code_checks.sh
  doc/source/reference/extensions.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/util/hashing.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/json/test_json.py
Labels: ExtensionArray, hashing

#51498 PERF: Implement round on the block level
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
Labels: Performance

#51640 COMPAT: Update code for latest Cython 3 beta
  .github/workflows/ubuntu.yml
  pandas/_libs/algos.pyx
  pandas/_libs/join.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/sparse_op_helper.pxi.in
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/window/aggregations.pyx
  pandas/core/reshape/merge.py
Labels: Compat

#51728 Backport PR #51640 on branch 2.0.x (COMPAT: Update code for latest Cython 3 beta)
  .github/workflows/ubuntu.yml
  pandas/_libs/algos.pyx
  pandas/_libs/join.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/sparse_op_helper.pxi.in
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/window/aggregations.pyx
  pandas/core/reshape/merge.py
Labels: Compat

#51729 Backport PR #51498: PERF: Implement round on the block level
  asv_bench/benchmarks/frame_methods.py
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
Labels: Performance

#51592 PERF: maybe_promote
  pandas/core/dtypes/cast.py
Labels: Performance, Dtype Conversions

#49694 PDEP-5: NoRowIndex
  web/pandas/pdeps/0005-no-default-index-mode.md
  web/pandas_web.py
Labels: PDEP

#51724 DOC: updated docstrings for EX02 validation and updated code_checks
  ci/code_checks.sh
  pandas/core/dtypes/common.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
Labels: Docs

#51687 STYLE start enabling TCH
  pandas/_config/config.py
  pandas/_testing/__init__.py
  pandas/_testing/_io.py
  pandas/_testing/_random.py
  pandas/_testing/compat.py
  pandas/_testing/contexts.py
  pandas/compat/__init__.py
  pandas/compat/_optional.py
  pandas/compat/numpy/function.py
  pandas/core/_numba/executor.py
  pandas/core/_numba/kernels/shared.py
  pandas/core/computation/expressions.py
  pandas/core/computation/pytables.py
  pandas/core/indexing.py
  pandas/core/interchange/utils.py
  pandas/core/sample.py
  pyproject.toml
  typings/numba.pyi
Labels: Code Style

#51735 Backport PR #51592 on branch 2.0.x (PERF: maybe_promote)
  pandas/core/dtypes/cast.py
Labels: Performance, Dtype Conversions

#51743 REF: remove usage of `np.product` and `np.cumproduct`
  pandas/core/reshape/util.py
  pandas/tests/groupby/test_libgroupby.py
Labels: Refactor

#51746 DOC: Fix item docstring
  pandas/core/base.py
Labels: Docs

#51719 Backport PR #51454 on branch 2.0.x (DOC: Add user guide section about copy on write)
  doc/source/development/copy_on_write.rst
  doc/source/user_guide/copy_on_write.rst
  doc/source/user_guide/index.rst
  doc/source/whatsnew/v2.0.0.rst
Labels: Docs, Copy / view semantics

#51742 Revert "CLN: Remove read_orc dtype checking (#51604)"
  pandas/io/orc.py
Labels: CI, Arrow

#51703 DEPR: pinning name in SeriesGroupBy.agg
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Deprecate

#51705 TST: add test for apply/reconstruct_func
  pandas/tests/apply/test_frame_apply_relabeling.py
Labels: Groupby, Apply, Needs Tests

#51732 CoW: Add property for references to series class
  pandas/core/internals/construction.py
  pandas/core/series.py
Labels: Copy / view semantics

#51759 CI: fixup pre-commit failure
  doc/source/whatsnew/v2.1.0.rst
Labels: CI

#51755 Backport PR #51732 on branch 2.0.x (CoW: Add property for references to series class)
  pandas/core/internals/construction.py
  pandas/core/series.py
Labels: Copy / view semantics

#51723 CI: Add bot to track deprecation prs
  .github/workflows/deprecation-tracking-bot.yml
Labels: CI

#51697 DEP: Deprecate passing a DataFrame to from_records
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/core/internals/construction.py
  pandas/tests/frame/constructors/test_from_records.py
Labels: Deprecate, DataFrame

#51674 BUG: ArrowDtype().type raising for fixed size pa binary
  pandas/core/arrays/arrow/dtype.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#51611 BUG: Weighted rolling aggregations min_periods=0
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_win_type.py
Labels: Bug, Window

#51395 DEPR: DataFrame.groupby(axis=1)
  doc/source/user_guide/categorical.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/reshaping.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/tests/apply/test_str.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/test_allowlist.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_indexing.py
  pandas/tests/groupby/test_missing.py
  pandas/tests/groupby/test_nth.py
  pandas/tests/groupby/test_quantile.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/test_rank.py
  pandas/tests/groupby/test_size.py
  pandas/tests/groupby/test_value_counts.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/test_multilevel.py
Labels: Groupby, Deprecate

#51779 STYLE: Enable ruff TCH on pandas/core/indexers and more
  pandas/core/groupby/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/indexing.py
  pandas/core/groupby/numba_.py
  pandas/core/indexers/utils.py
  pandas/core/indexes/api.py
  pandas/core/indexes/category.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/extension.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/period.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pandas/core/internals/api.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/base.py
  pandas/core/internals/concat.py
  pandas/core/internals/construction.py
  pandas/core/internals/managers.py
  pandas/core/internals/ops.py
  pandas/core/methods/selectn.py
  pandas/core/methods/to_dict.py
  pyproject.toml
Labels: Code Style

#51776 Backport PR #51674 on branch 2.0.x (BUG: ArrowDtype().type raising for fixed size pa binary)
  pandas/core/arrays/arrow/dtype.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#51780 CI: Fix np dev build failure
  pandas/tests/apply/test_frame_apply_relabeling.py
Labels: CI

#51785 Backport PR #51780 on branch 2.0.x (CI: Fix np dev build failure)
  pandas/tests/apply/test_frame_apply_relabeling.py
Labels: CI

#51798 STYLE: Enable ruff TCH for pandas/core/common.py
  pandas/core/common.py
  pyproject.toml
Labels: Code Style

#51802 PERF: enabling TCH for pandas/core/resample.py
  pandas/core/resample.py
  pyproject.toml
Labels: Code Style

#51781 STYLE: Enable ruff TCH on some files
  pandas/core/array_algos/masked_accumulations.py
  pandas/core/array_algos/masked_reductions.py
  pandas/core/array_algos/putmask.py
  pandas/core/array_algos/quantile.py
  pandas/core/array_algos/replace.py
  pandas/core/array_algos/take.py
  pandas/core/array_algos/transforms.py
  pandas/core/dtypes/astype.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/concat.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/series.py
  pyproject.toml
Labels: Code Style

#50398 ENH: add math mode to formatter escape="latex-math"
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/config_init.py
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_format.py
Labels: Enhancement, IO LaTeX, Styler

#51790 BUG: PeriodDtype constructor allowing invalid construction, incorrect exception class
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Period

#51787 ENH: Let to_feather accept index and non string column names
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/feather_format.py
  pandas/tests/io/test_feather.py
Labels: IO Parquet

#51774 WEB: Add robots.txt to disallow docs preview
  web/pandas/robots.txt
Labels: Web

#51730 PERF: ArrowExtensionArray._from_sequence_of_strings(dtype=pa.bool_())
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Performance, Arrow

#51806 DOC Fix EX01 issues in docstrings
  ci/code_checks.sh
  pandas/core/generic.py
Labels: Docs

#51800 BUG: ArrowDtype.numpy_dtype returning ns units for non-nano timestamp and duration types
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/dtype.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Arrow, Non-Nano

#51770 STYLE enable TCH on pandas/core/io
  pyproject.toml
Labels: Code Style

#51761 TST: Test to verify behavior of groupby.std with no numeric columns and numeric_only=True
  pandas/tests/groupby/test_groupby.py
Labels: Testing, Groupby

#51688 BUG: ArrowExtensionArray logical ops raising KeyError
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Arrow

#51812 STYLE: Enable ruff TCH on some files
  pandas/core/reshape/concat.py
  pandas/core/reshape/encoding.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/reshape/tile.py
  pandas/core/reshape/util.py
  pandas/core/strings/base.py
  pandas/core/strings/object_array.py
  pandas/core/tools/numeric.py
  pandas/core/tools/timedeltas.py
  pandas/core/tools/times.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/numba_.py
  pandas/core/window/rolling.py
  pandas/io/__init__.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_pyxlsb.py
  pandas/io/excel/_xlrd.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/feather_format.py
  pandas/io/formats/__init__.py
  pandas/io/formats/csvs.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/info.py
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/formats/xml.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/json/_normalize.py
  pandas/io/json/_table_schema.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/io/pickle.py
  pandas/io/pytables.py
  pandas/io/sas/_sas.pyi
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_xport.py
  pandas/io/sas/sasreader.py
  pandas/io/spss.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/io/xml.py
  pyproject.toml
Labels: Code Style

#51665 WEB: Added stying for pre element within the codeblock divs
  web/pandas/static/css/codehilite.css
Labels: Web

#51762 DOC: Add explanation how to convert arrow table to pandas df
  doc/source/user_guide/pyarrow.rst
Labels: Docs, Arrow

#51565 BUG: transpose inferring dtype for dt in object column
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_transpose.py
  pandas/tests/groupby/test_quantile.py
Labels: Reshaping, Dtype Conversions

#51822 Backport PR #51762 on branch 2.0.x (DOC: Add explanation how to convert arrow table to pandas df)
  doc/source/user_guide/pyarrow.rst
Labels: Docs, Arrow

#51810 Backport PR #51688 on branch 2.0.x (BUG: ArrowExtensionArray logical ops raising KeyError)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Arrow

#51773 PERF: fastpaths in tzconversion
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/_libs/tslibs/vectorized.pyx
Labels: Performance, Timezones

#51775 CLN: assorted
  doc/source/whatsnew/v2.0.0.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/arrays.pyx
  pandas/_libs/parsers.pyi
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/src/datetime/np_datetime.c
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/_testing/asserters.py
  pandas/conftest.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/groupby/generic.py
  pandas/core/indexing.py
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
  pandas/core/ops/methods.py
  pandas/core/ops/missing.py
  pandas/io/json/_table_schema.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/sparse/test_libsparse.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexing/multiindex/test_indexing_slow.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_upcast.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/tseries/offsets/test_offsets.py
  scripts/validate_unwanted_patterns.py
Labels: Clean

#51793 PERF: PeriodArray._format_native_types
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
  pandas/tests/indexes/period/test_formats.py
Labels: Performance, Period

#51694 Adds Hamilton to match ecosystem.md
  doc/source/ecosystem.rst
Labels: Docs

#51672 ENH: Support na_position for sort_index and sortlevel
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/sorting.py
  pandas/tests/frame/methods/test_sort_index.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexes/test_base.py
Labels: MultiIndex

#51838 CLN: Remove pep8speaks
  .pep8speaks.yml
Labels: CI, Clean

#51836 PERF: ArrowExtensionArray._from_sequence
  pandas/core/arrays/arrow/array.py
Labels: Performance, Arrow

#51766 CLN: Use type_mapper instead of manual conversion
  pandas/io/feather_format.py
  pandas/io/json/_json.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/test_parquet.py
Labels: Clean, Arrow

#51741 BUG: indexing empty pyarrow backed object returning corrupt object
  doc/source/whatsnew/v2.0.0.rst
  pandas/_testing/__init__.py
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Indexing, Arrow

#51738 PERF: accessing sliced indexes with populated indexing engines
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/index.pyx
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/range.py
Labels: Indexing, Performance

#51843 STYLE Remove flake8-rst
  .pre-commit-config.yaml
Labels: Code Style

#51833 PERF: avoid non-cython in testing.pyx
  pandas/_libs/testing.pyx
  pandas/tests/util/test_assert_almost_equal.py
Labels: Testing

#51847 Remove flake8-rst usage
  setup.cfg
Labels: Code Style

#51792 PERF: cache sortings in groupby.ops
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Groupby, Performance

#51813 REF: define arithmetic methods non-dynamically
  pandas/core/arrays/categorical.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/sparse/array.py
  pandas/core/computation/expressions.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/ops/__init__.py
  pandas/core/ops/array_ops.py
  pandas/core/ops/docstrings.py
  pandas/core/ops/methods.py
  pandas/core/series.py
  pandas/tests/frame/test_arithmetic.py
Labels: Refactor

#51704 DOC: Improve groupby in the User Guide
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.7.0.rst
Labels: Docs, Groupby

#51689 BUG: mask/where raising for mixed dtype frame and no other
  pandas/core/generic.py
  pandas/tests/frame/indexing/test_mask.py
  pandas/tests/frame/indexing/test_where.py
Labels: Indexing, Regression

#51651 ENH: Add na_position support to midx.sort_values
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_sorting.py
Labels: Missing-data, MultiIndex

#51464 CoW: Ignore copy=True when copy_on_write is enabled
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/managers.py
  pandas/core/reshape/concat.py
  pandas/core/series.py
  pandas/tests/copy_view/test_functions.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_set_axis.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_dataframe.py
  pandas/tests/reshape/concat/test_index.py
  pandas/tests/series/methods/test_align.py
Labels: Copy / view semantics

#51849 Backport PR #51464 on branch 2.0.x (CoW: Ignore copy=True when copy_on_write is enabled)
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/managers.py
  pandas/core/reshape/concat.py
  pandas/core/series.py
  pandas/tests/copy_view/test_functions.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_set_axis.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_dataframe.py
  pandas/tests/reshape/concat/test_index.py
  pandas/tests/series/methods/test_align.py
Labels: Copy / view semantics

#51848 Backport PR #51689 on branch 2.0.x (BUG: mask/where raising for mixed dtype frame and no other)
  pandas/core/generic.py
  pandas/tests/frame/indexing/test_mask.py
  pandas/tests/frame/indexing/test_where.py
Labels: Indexing, Regression

#51851 TST/CLN: `test_query_eval.py`
  pandas/tests/frame/test_query_eval.py
Labels: Testing, Clean, expressions

#51835 STYLE: enable ruff TCH on some file
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/groupby.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/extension/array_with_attr/array.py
  pandas/tests/extension/date/array.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/list/array.py
  pandas/tests/frame/common.py
  pandas/tests/tseries/offsets/test_custom_business_month.py
  pandas/tseries/__init__.py
  pandas/tseries/frequencies.py
  pyproject.toml
Labels: Code Style

#51857 Backport PR #51704 on branch 2.0.x (DOC: Improve groupby in the User Guide)
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.7.0.rst
Labels: Docs

#50936 DOC: Fix dark mode styles
  doc/source/_static/css/getting_started.css
Labels: Docs

#51643 API: ArrowExtensionArray._cmp_method to return pyarrow.bool_ type
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
Labels: Arrow

#51691 BUG: DataFrame.stack losing EA dtypes with multi-columns and mixed dtypes
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping, ExtensionArray

#51827 Enabled ruff TCH on some files
  pandas/core/ops/array_ops.py
  pandas/core/ops/common.py
  pandas/core/ops/dispatch.py
  pandas/core/sorting.py
  pyproject.toml
Labels: Code Style

#51864 Backport PR #50936 on branch 2.0.x (DOC: Fix dark mode styles)
  doc/source/_static/css/getting_started.css
Labels: Docs

#51869 ENH: Add to_pydatetime for ArrowExtensionArray
  pandas/core/arrays/arrow/array.py
  pandas/core/indexes/accessors.py
  pandas/tests/extension/test_arrow.py
Labels: Timeseries, Arrow

#51870 Backport PR #51869 on branch 2.0.x (ENH: Add to_pydatetime for ArrowExtensionArray)
  pandas/core/arrays/arrow/array.py
  pandas/core/indexes/accessors.py
  pandas/tests/extension/test_arrow.py
Labels: Timeseries, Arrow

#50987 REF: ArrowEA _data->_pa_array
  pandas/_testing/__init__.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/core/indexes/accessors.py
  pandas/tests/copy_view/test_astype.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/io/excel/test_readers.py
Labels: Refactor, Arrow

#51825 DOC: sort has no effect on filters
  pandas/core/shared_docs.py
Labels: Docs, Groupby

#51816 add concat function dtype test
  pandas/tests/reshape/concat/test_datetimes.py
Labels: Testing

#51877 CI/DEPS: Use np.prod in tests for np deprecation
  pandas/tests/resample/test_datetime_index.py
Labels: Testing, Dependencies

#51854 ENH: Add misc pyarrow types to ArrowDtype.type
  pandas/core/arrays/arrow/dtype.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#51884 Backport PR #51877 on branch 2.0.x (CI/DEPS: Use np.prod in tests for np deprecation)
  pandas/tests/resample/test_datetime_index.py
Labels: Testing, Dependencies

#51890 DOC: change 8610 -> 8601 in Timestamp.isoformat() docstring
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#51887 Backport PR #51854 on branch 2.0.x (ENH: Add misc pyarrow types to ArrowDtype.type)
  pandas/core/arrays/arrow/dtype.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#51886 CI: Pin moto image to specific version
  .github/workflows/ubuntu.yml
Labels: CI, IO Network

#51889 DOC: Fix dangling hyphens.
  doc/source/ecosystem.rst
  doc/source/user_guide/integer_na.rst
Labels: Docs

#51893 Backport PR #51886 on branch 2.0.x (CI: Pin moto image to specific version)
  .github/workflows/ubuntu.yml
Labels: CI, IO Network

#51897 DEPS: Address np.cumproduct deprecation
  pandas/core/reshape/util.py
  pandas/tests/groupby/test_libgroupby.py
Labels: Dependencies

#51888 fixed "pandas/util/*" = ["TCH"]
  pandas/util/_print_versions.py
  pandas/util/_test_decorators.py
  pyproject.toml
Labels: Code Style

#51786 STYLE enable ruff TCH on pandas/core/arrays
  pandas/core/arrays/_ranges.py
  pandas/core/arrays/arrow/dtype.py
  pandas/core/arrays/arrow/extension_types.py
  pandas/core/arrays/base.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/numeric.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/sparse/dtype.py
  pandas/core/arrays/sparse/scipy_sparse.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/arrays/timedeltas.py
  pyproject.toml
Labels: Code Style

#51906 DOC: typo fix contributing_environment
  doc/source/development/contributing_environment.rst
Labels: Docs

#51902 Re-enable parallel builds in CI
  .circleci/setup_env.sh
  .github/workflows/32-bit-linux.yml
  .github/workflows/python-dev.yml
Labels: Build

#51867 TYP: fix NDFrame.align
  pandas/_typing.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
Labels: Typing

#51911 CI: parallel build follow up
  .github/actions/build_pandas/action.yml
  .github/actions/setup-conda/action.yml
Labels: CI

#51894 CI/STYLE: Add auto-fix to ruff
  .pre-commit-config.yaml
  pyproject.toml
Labels: Code Style

#51918 Replace deprecated BadZipfile with BadZipFile
  pandas/tests/io/parser/test_compression.py
Labels: Compat

#51809 REF: Add ExtensionArray.map
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/algorithms.py
  pandas/core/apply.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
Labels: ExtensionArray

#51907 Update integer_na.rst with multiple improvements.
  doc/source/user_guide/integer_na.rst
Labels: Docs

#51082 API / CoW: return read-only numpy arrays in .values/to_numpy()
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/io/parsers/base_parser.py
  pandas/tests/copy_view/test_array.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_insert.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_copy.py
  pandas/tests/frame/methods/test_join.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/methods/test_transpose.py
  pandas/tests/frame/methods/test_values.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/test_ufunc.py
  pandas/tests/window/test_pairwise.py
  pandas/util/_test_decorators.py
Labels: Copy / view semantics

#51753 Add test to check numeric precision GH33234
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Testing

#51853 Remove use_nullable_dtypes and add dtype_backend keyword
  doc/source/user_guide/io.rst
  doc/source/user_guide/pyarrow.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/_libs/parsers.pyi
  pandas/_libs/parsers.pyx
  pandas/_typing.py
  pandas/conftest.py
  pandas/core/arrays/numeric.py
  pandas/core/config_init.py
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/internals/construction.py
  pandas/core/series.py
  pandas/core/tools/numeric.py
  pandas/io/clipboards.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/readers.py
  pandas/io/spss.py
  pandas/io/sql.py
  pandas/io/xml.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_upcast.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_spss.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/tools/test_to_numeric.py
Labels: NA - MaskedArrays, Arrow

#51832 BUG / CoW: Series.view not respecting CoW
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Series, Copy / view semantics

#51480 TYP: Use Self instead of class-bound TypeVar in pyi files (remove Y019)
  environment.yml
  pandas/_libs/sparse.pyi
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_typing.py
  requirements-dev.txt
  setup.cfg
Labels: Typing

#51896 BUG: disallow resample with non-Tick on TimedeltaIndex
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/timedeltas.py
  pandas/core/resample.py
  pandas/tests/indexes/timedeltas/test_freq_attr.py
  pandas/tests/resample/test_base.py
Labels: Frequency, Resample

#51931 BLD: Try strip-all instead of strip-debug
  pyproject.toml
Labels: Build

#51937 Backport PR #51832 on branch 2.0.x (BUG / CoW: Series.view not respecting CoW)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Series, Copy / view semantics

#51933 Backport PR #51082 on branch 2.0.x (API / CoW: return read-only numpy arrays in .values/to_numpy())
  pandas/core/base.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/io/parsers/base_parser.py
  pandas/tests/copy_view/test_array.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_insert.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_copy.py
  pandas/tests/frame/methods/test_join.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/methods/test_transpose.py
  pandas/tests/frame/methods/test_values.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/test_ufunc.py
  pandas/tests/window/test_pairwise.py
  pandas/util/_test_decorators.py
Labels: Copy / view semantics

#51938 Backport PR #51931 on branch 2.0.x (BLD: Try strip-all instead of strip-debug)
  pyproject.toml
Labels: Build

#51949 CI: Remove workflows on 1.5.x branch
  .github/workflows/32-bit-linux.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/macos-windows.yml
  .github/workflows/package-checks.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  .github/workflows/ubuntu.yml
Labels: CI

#51943 BUG: Count creates result with read_only array
  pandas/core/frame.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#51917 Series.astype(np.integer) doesn't show numpy warning
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
Labels: Warnings

#51956 Backport PR #51949 on branch 2.0.x (CI: Remove workflows on 1.5.x branch)
  .github/workflows/32-bit-linux.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/macos-windows.yml
  .github/workflows/package-checks.yml
  .github/workflows/python-dev.yml
  .github/workflows/sdist.yml
  .github/workflows/ubuntu.yml
Labels: CI

#51912 TYP: misc return types
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/core/strings/accessor.py
  pandas/io/formats/css.py
  pandas/io/pytables.py
  pandas/io/sql.py
Labels: Typing

#51873 PERF: Improve performance of MultiIndex._verify_integrity
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexes/multi.py
Labels: Performance, MultiIndex

#51828 ERR: Raise ValueError when non-default index is given for orc format
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/orc.py
  pandas/tests/io/test_orc.py
Labels: IO Parquet, Arrow

#51957 Backport PR #51943 on branch 2.0.x (BUG: Count creates result with read_only array)
  pandas/core/frame.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#51958 Backport PR #51917 on branch 2.0.x (Series.astype(np.integer) doesn't show numpy warning)
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
Labels: Warnings

#51942 TST: Avoid datetime.now in tests for DST dependence
  pandas/tests/dtypes/cast/test_promote.py
Labels: Testing, Timezones, Unreliable Test

#51871 ERR: Check that dtype_backend is valid
  pandas/core/generic.py
  pandas/core/internals/construction.py
  pandas/core/tools/numeric.py
  pandas/io/clipboards.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/readers.py
  pandas/io/spss.py
  pandas/io/sql.py
  pandas/io/xml.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_spss.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/tools/test_to_numeric.py
  pandas/util/_validators.py
Labels: NA - MaskedArrays, Arrow

#51945 BUG: swapaxes creating result with read_only array
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#51944 BUG: CoW not tracking references when indexing midx with slice
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/tests/copy_view/test_indexing.py
Labels: Copy / view semantics

#51962 Backport PR #51945 on branch 2.0.x (BUG: swapaxes creating result with read_only array)
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#51963 Backport PR #51944 on branch 2.0.x (BUG: CoW not tracking references when indexing midx with slice)
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/tests/copy_view/test_indexing.py
Labels: Copy / view semantics

#51934 REF: move ExtensionIndex.map to be part of DatetimeLikeArrayMixin.map
  pandas/core/arrays/datetimelike.py
  pandas/core/base.py
  pandas/core/indexes/extension.py
Labels: Refactor

#48347 ENH: __pandas_priority__
  doc/source/development/extending.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/base.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/ops/common.py
  pandas/core/series.py
  pandas/tests/test_downstream.py
Labels: Enhancement

#51609 ENH: use native filesystem (if available) for read_parquet with pyarrow engine
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_parquet.py
Labels: IO Parquet, Arrow

#51497 TYP: Use Self instead of class-bound TypeVar II (pandas/core/arrays/)
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numeric.py
  pandas/core/arrays/sparse/array.py
Labels: Typing

#51974 BUG: astype_view check raising on minimum versions build
  pandas/core/dtypes/astype.py
  pandas/tests/copy_view/test_astype.py
Labels: Dtype Conversions

#51983 Backport PR #51974 on branch 2.0.x (BUG: astype_view check raising on minimum versions build)
  pandas/core/dtypes/astype.py
  pandas/tests/copy_view/test_astype.py
Labels: Dtype Conversions

#51247 PERF: Construction of a DatetimeIndex from a list of Timestamp with timezone
  .github/workflows/package-checks.yml
  ci/deps/actions-310-numpydev.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-38-downstream_compat.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-38.yaml
  ci/test_wheels_windows.bat
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.0.0.rst
  environment.yml
  pyproject.toml
  requirements-dev.txt
  scripts/validate_min_versions_in_sync.py
Labels: Build

#51926 CoW: change ChainedAssignmentError exception to a warning
  doc/source/user_guide/copy_on_write.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/_testing/contexts.py
  pandas/core/frame.py
  pandas/core/indexing.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/tests/io/test_spss.py
Labels: Copy / view semantics

#51982 integer array creation test GH#31104
  pandas/tests/arrays/integer/test_construction.py
Labels: Testing

#51985 BUG: Add numpy_nullable support to arrow csv parser
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: IO CSV, Arrow

#51969 REF/TYP: avoid need for NDFrameTb
  pandas/_typing.py
  pandas/core/generic.py
  pandas/tests/frame/methods/test_align.py
Labels: Refactor, Typing

#51932 DOC: add examples to offsets CustomBusinessDay, Business/MonthBegin
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs, Frequency

#51986 Backport PR #51926 on branch 2.0.x (CoW: change ChainedAssignmentError exception to a warning)
  doc/source/user_guide/copy_on_write.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/_testing/contexts.py
  pandas/core/frame.py
  pandas/core/indexing.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/tests/io/test_spss.py
Labels: Copy / view semantics

#51971 BLD: Try g0 on macos?
  pyproject.toml
Labels: Build

#51976 BUG: read_csv for arrow with mismatching dtypes does not work
  pandas/io/parsers/c_parser_wrapper.py
  pandas/tests/io/parser/test_concatenate_chunks.py
Labels: IO CSV

#51989 Backport PR #51985 on branch 2.0.x (BUG: Add numpy_nullable support to arrow csv parser)
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: IO CSV, Arrow

#51993 Backport PR #51971 on branch 2.0.x (BLD: Try g0 on macos?)
  pyproject.toml
Labels: Build

#51995 Backport PR #51976 on branch 2.0.x (BUG: read_csv for arrow with mismatching dtypes does not work)
  pandas/io/parsers/c_parser_wrapper.py
  pandas/tests/io/parser/test_concatenate_chunks.py
Labels: IO CSV

#51967 Series.plot doesn't allow color=None
  doc/source/whatsnew/v2.1.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/test_series.py
Labels: Visualization
