Repository pandas-dev/pandas, pull requests merged in 2023-08, with the labels that each got.

#54331 REF: share IntegerArray/FloatingArray extension tests
  pandas/tests/extension/masked_shared.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_floating.py
  pandas/tests/extension/test_integer.py
  pandas/tests/extension/test_masked_numeric.py
Labels: Refactor, Testing, NA - MaskedArrays

#54334 REF/TST: handle boolean dtypes in base extension tests
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
Labels: Refactor, Testing, NA - MaskedArrays

#51722 PERF: GroupBy.quantile
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/groupby/groupby.py
Labels: Groupby, Performance, quantile

#54330 STY: Enable ruff ambiguous unicode character
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/indexes/datetimes.py
  pandas/core/reshape/merge.py
  pandas/core/tools/datetimes.py
  pandas/io/excel/_base.py
  pandas/io/formats/html.py
  pandas/io/formats/style.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_stata.py
  pandas/tests/series/methods/test_to_csv.py
  pandas/tests/strings/test_strings.py
  pandas/tseries/holiday.py
  pyproject.toml
  web/pandas/about/governance.md
  web/pandas/community/coc.md
Labels: Code Style

#54292 Contributor Docs: update gitpod docs and small fix
  doc/source/development/contributing_gitpod.rst
Labels: Docs, Sprints

#54350 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  doc/source/reference/arrays.rst
  pandas/_libs/tslibs/nattype.pyx
Labels: Docs

#54348 restructured drop method return value defination
  pandas/core/frame.py
Labels: Docs

#54343 REF: dont patch assert_frame_equal
  pandas/tests/extension/json/test_json.py
Labels: Testing, ExtensionArray

#54345 REF: don patch assert_series_equal, assert_equal
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_numpy.py
Labels: Testing

#54339 DOC: Move performance improvements in whatsnew
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs, Clean

#54306 BUG: Fix Series.groupby raising OutOfBoundsDatetime with DatetimeIndex and month name
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby

#54351 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#54353 Added Test for multi-index groupby partial indexing equivalence
  pandas/tests/groupby/test_grouping.py
Labels: Testing

#54340 REF: de-duplicate extension tests
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/extension/test_string.py
Labels: Testing, ExtensionArray

#54354 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#54355 REF/TST: remove overriding tm.assert_foo pattern
  .pre-commit-config.yaml
  pandas/tests/arrays/integer/test_comparison.py
  pandas/tests/arrays/masked_shared.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/accumulate.py
  pandas/tests/extension/base/base.py
  pandas/tests/extension/base/casting.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/io.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_masked_numeric.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/extension/test_string.py
Labels: Testing, ExtensionArray

#54361 REF: avoid monkeypatch in arrow tests
  pandas/tests/extension/test_arrow.py
Labels: Refactor, Testing, Arrow

#54360 Added pivot table test for explicit datetime types Issue#43574
  pandas/tests/reshape/test_pivot.py
Labels: Testing, Reshaping

#54263 BUG: pivot_table mean of integer input casted back to int
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/reshape/pivot.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/reshape/test_pivot.py
Labels: Bug, Groupby, Reshaping, Dtype Conversions, API - Consistency

#54370 CI: fix cython lint errors
  pandas/_libs/sparse.pyx
  pandas/_libs/tslibs/offsets.pyx
Labels: CI

#53212 ENH: explicit filters parameter in pd.read_parquet
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: Docs, IO Parquet

#54366 REF: implement BaseOpsUtil._cast_pointwise_result
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_masked_numeric.py
Labels: Testing, ExtensionArray

#54364 CLN: Remove None check in attrs property lookup
  pandas/core/generic.py
Labels: metadata

#54362 CI/TST: Cleanups
  .circleci/setup_env.sh
  .github/workflows/unit-tests.yml
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/io/parser/test_upcast.py
  pandas/tests/io/test_gcs.py
  pandas/tests/test_downstream.py
Labels: Testing, CI

#53921 ENH: Add new implementation of DataFrame.stack
  doc/source/getting_started/comparison/comparison_with_r.rst
  doc/source/user_guide/10min.rst
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/reshaping.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_function.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/series/methods/test_reset_index.py
  pandas/tests/series/methods/test_unstack.py
Labels: Enhancement, Reshaping

#54367 REF: remove test_accumulate_series_raises
  pandas/tests/extension/base/accumulate.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_masked_numeric.py
  pandas/tests/extension/test_sparse.py
Labels: Testing, ExtensionArray

#54384 DOC: Fixing EX01 - Added example
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#54374 DOC: Changed from_custom_template example
  pandas/io/formats/style.py
Labels: Docs

#54377 TST: Use more pytest.importorskip
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_ufunc.py
  pandas/tests/generic/test_to_xarray.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/test_numba.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_numba.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/formats/style/test_matplotlib.py
  pandas/tests/io/formats/test_to_excel.py
  pandas/tests/io/formats/test_to_string.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_upcast.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_s3.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/series/test_api.py
  pandas/tests/test_downstream.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/window/test_online.py
  pandas/util/_test_decorators.py
Labels: Testing

#54375 COMPAT: Change khcomplex64/128_t typedefs
  pandas/_libs/include/pandas/vendored/klib/khash_python.h
  pandas/tests/io/formats/test_printing.py
Labels: Compat

#54368 TST: Remove tm.rands/rands_array
  asv_bench/benchmarks/array.py
  asv_bench/benchmarks/series_methods.py
  asv_bench/benchmarks/strings.py
  pandas/_testing/__init__.py
  pandas/_testing/_io.py
  pandas/_testing/_random.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_repr_info.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_rank.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/util/test_hashing.py
  pandas/tests/util/test_util.py
Labels: Testing, Clean

#54298 BUG: to_timedelta with ArrowDtype(pa.duration)
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/tools/timedeltas.py
  pandas/tests/tools/test_to_timedelta.py
Labels: Timedelta, Arrow

#54346 Parquet metadata persistence of DataFrame.attrs
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: IO Parquet, metadata

#54372 BUG: pd.array([]) should return masked array
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/construction.py
  pandas/tests/arrays/test_array.py
Labels: ExtensionArray

#54393 REF: de-duplicate check_reduce_frame
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_masked_numeric.py
  pandas/tests/extension/test_numpy.py
Labels: Testing, ExtensionArray

#54365 REF: dont pass exception to check_opname
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_masked_numeric.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
Labels: Refactor, Testing

#54388 bug fix 54251
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/dtypes/common.py
  pandas/tests/dtypes/test_common.py
Labels: Dtype Conversions

#53722 API / CoW: shallow copy of DataFrame/Series (.copy(deep=False)) also returns shallow copy of the index/columns
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_npfuncs.py
  pandas/tests/reshape/concat/test_index.py
  pandas/tests/series/methods/test_align.py
  pandas/tests/series/test_constructors.py
  pandas/tests/test_multilevel.py
Labels: API Design, Copy / view semantics

#54404 CI: remove test cases which would have globbed pandas.tests
  scripts/tests/test_check_test_naming.py
Labels: CI

#54379 CLN: VariableOffsetWindowIndexer
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexers/objects.py
  pandas/tests/window/test_base_indexer.py
Labels: Clean, Window

#54387 TST: Use importorskip over skip_if_no_scipy
  pandas/conftest.py
  pandas/tests/arrays/sparse/test_accessor.py
  pandas/tests/arrays/sparse/test_constructors.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/frame/test_frame_legend.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/series/methods/test_cov_corr.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/test_algos.py
  pandas/tests/test_nanops.py
  pandas/tests/window/test_rolling_skew_kurt.py
  pandas/tests/window/test_win_type.py
Labels: Testing

#54395 CLN/DOC: DataFrame.count remove references to "level"
  asv_bench/benchmarks/frame_methods.py
  pandas/core/frame.py
Labels: Docs, Clean

#54335 DEPS: Bump cython 3.0
  asv_bench/asv.conf.json
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  doc/source/whatsnew/v2.1.0.rst
  environment.yml
  pandas/_libs/arrays.pyi
  pandas/_libs/groupby.pyi
  pandas/_libs/hashtable.pyi
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/lib.pyi
  pandas/_libs/ops.pyi
  pandas/_libs/sparse.pyi
  pandas/_libs/tslibs/conversion.pyi
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/tslibs/tzconversion.pyi
  pandas/_libs/tslibs/vectorized.pyi
  pandas/_libs/window/aggregations.pyi
  pandas/core/arrays/datetimelike.py
  pyproject.toml
  requirements-dev.txt
  scripts/run_stubtest.py
  setup.py
Labels: Compat, Dependencies

#54300 BUG: from_dummies always returning object data
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/reshape/encoding.py
  pandas/tests/reshape/test_from_dummies.py
Labels: Dtype Conversions, Strings

#54398 TYP: Enable pyright's reportInconsistentConstructor
  .pre-commit-config.yaml
  pandas/_typing.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/indexes/accessors.py
  pandas/io/excel/_base.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pyproject.toml
  pyright_reportGeneralTypeIssues.json
Labels: Typing

#54414 REF: de-duplicate test_combine_add
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_period.py
Labels: Testing, ExtensionArray

#54413 REF: de-duplicate test_divmod_series_array
  pandas/tests/extension/conftest.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_period.py
Labels: Testing, ExtensionArray

#54411 CI: Build sdist again on macOS
  .github/workflows/wheels.yml
Labels: Build

#54407 Fix #54391: Use memcpy() for unaligned loads
  pandas/_libs/byteswap.pyx
Labels: Internals, ARM

#53338 DEPR: int slicing always positional
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexes/base.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/test_floats.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Indexing, Deprecate

#54410 REF: de-duplicate test_direct_arith_with_ndframe_returns_not_implemented
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/core/arrays/datetimelike.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/test_period.py
Labels: Testing, ExtensionArray

#54394 REF: simplify extension reduction tests
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_masked_numeric.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_string.py
Labels: Testing, ExtensionArray

#54418 DOC: Simplify scale.rst
  doc/source/user_guide/scale.rst
Labels: Docs

#54419 DOC: Simplify enhancingperf.rst
  doc/source/user_guide/enhancingperf.rst
Labels: Docs

#54415 DOC: Simplify gotchas.rst
  doc/source/user_guide/gotchas.rst
Labels: Docs

#54412 REF: de-duplicate test_add_series_with_extension_array
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_period.py
Labels: Testing, ExtensionArray

#54153 DOC: Example missing in pandas.DataFrame.to_html #44945
  pandas/core/frame.py
Labels: Sprints

#54426 Update conftest.py
  pandas/conftest.py
Labels: Testing

#54424 REF: de-duplicate _compare_other
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_masked_numeric.py
  pandas/tests/extension/test_string.py
Labels: Testing, ExtensionArray

#54429 REF: move misplaced tests
  pandas/tests/arrays/categorical/test_astype.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/extension/test_string.py
Labels: Testing

#54390 TST: Use pytest or assert_produces_warnings instead of catch_warnings
  doc/source/development/contributing_codebase.rst
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/computation/test_eval.py
  pandas/tests/config/test_config.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/multi/test_drop.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_complex.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_subplots.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/series/accessors/test_cat_accessor.py
  pandas/tests/test_expressions.py
  pandas/tests/test_nanops.py
  pandas/tests/util/test_deprecate_nonkeyword_arguments.py
  pandas/tests/window/test_apply.py
  pandas/tests/window/test_pairwise.py
Labels: Testing, Warnings

#54422 REF: share BooleanArray tests with MaskedArray
  pandas/tests/extension/test_boolean.py
  pandas/tests/extension/test_masked.py
  pandas/tests/groupby/test_function.py
Labels: Testing, ExtensionArray

#54436 REF: update to use extension test patterns
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_interval.py
Labels: Testing, ExtensionArray

#54434 REF: simplify fixtures
  pandas/tests/extension/conftest.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_masked.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/extension/test_string.py
Labels: Testing

#54421 ENH: Dtype._is_immutable
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/internals/managers.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/test_sparse.py
Labels: ExtensionArray

#54437 CI: Try to fix the tar issue on macOS
  .github/workflows/wheels.yml
  pandas/tests/io/test_stata.py
Labels: Build, OS X

#54440 REF: move misplaced tests
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/test_common.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Testing, ExtensionArray

#54438 REF: use updated patterns in pyarrow TestReduce
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#54383 ENH: add consortium standard entrypoint
  .github/workflows/package-checks.yml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-39-minimum_versions.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.1.0.rst
  environment.yml
  pandas/compat/_optional.py
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/test_downstream.py
  pyproject.toml
  requirements-dev.txt
Labels: Build, Interchange

#54432 REF: implement TestExtension
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/accumulate.py
  pandas/tests/extension/base/casting.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/index.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/base/io.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/base/printing.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/test_interval.py
Labels: Testing, ExtensionArray

#54455 REF: update decimal tests to TestExtension
  pandas/tests/extension/decimal/test_decimal.py
Labels: Testing, ExtensionArray

#54456 DOC: Simplify 10min.rst
  doc/source/user_guide/10min.rst
Labels: Docs

#54448 DOC Update Documentation in "missing_data" 54028
  doc/source/user_guide/missing_data.rst
Labels: Docs

#54451 BUG: Fixes #54617 Dataframe to html for empty array with complex dtypes
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_to_html.py
Labels: IO HTML, Complex

#54443 ENH: Implement more efficient merge for arrow strings
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/reshape/merge.py
Labels: Reshaping, Arrow

#54446 test_map: use data_missing to exercise na_action
  pandas/tests/extension/base/methods.py
Labels: Testing, ExtensionArray

#54427 DOC: add missing parameters to offsets classes: Second, Minute, Hour and Day
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs, Frequency

#54476 Add whatsnew for arrow
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#54397 DEPR: Positional arguments in to_sql except name
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.14.0.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: IO SQL, Deprecate

#54482 CLN: Cython 3 cleanups
  pandas/_libs/algos.pyx
  pandas/_libs/arrays.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/internals.pyx
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/parsers.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Clean

#54484 Update whatsnew
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#54472 CI/TST: Run tests in development mode with EncodingWarnings
  ci/run_tests.sh
  pandas/_testing/contexts.py
  pandas/io/common.py
  pandas/tests/arrays/categorical/test_warnings.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/test_base.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/test_sql.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Testing

#54477 BUG: interval_range with float step
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexes/interval.py
  pandas/tests/indexes/interval/test_interval_range.py
Labels: Interval

#54487 CI: Another shot at fixing macOS wheel builds
  .github/workflows/wheels.yml
Labels: Build

#54463 TST: More explicit test patterns
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_api.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/test_indexing.py
  pandas/tests/indexes/test_numpy_compat.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/reshape/concat/test_append_common.py
  pandas/tests/reshape/concat/test_empty.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_clip.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/test_expressions.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/window/test_ewm.py
Labels: Testing

#54431 ENH: Implement arrow string option for various I/O methods
  pandas/_config/__init__.py
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/io/_util.py
  pandas/io/feather_format.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/pytables.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
Labels: IO Data, Arrow

#53731 ENH: Add separate numba kernels for groupby aggregations
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/_numba/executor.py
  pandas/core/_numba/kernels/__init__.py
  pandas/core/_numba/kernels/mean_.py
  pandas/core/_numba/kernels/min_max_.py
  pandas/core/_numba/kernels/sum_.py
  pandas/core/_numba/kernels/var_.py
  pandas/core/groupby/groupby.py
  pandas/core/window/rolling.py
  pyright_reportGeneralTypeIssues.json
Labels: Groupby, numba

#54489 CI: Set back the schedule
  .github/workflows/wheels.yml
Labels: Build

#54465 DOC: Simplify reshaping.rst
  doc/source/getting_started/intro_tutorials/07_reshape_table_layout.rst
  doc/source/user_guide/reshaping.rst
Labels: Docs

#54483 Remove GIL from ``take_2d_axis_0``
  pandas/_libs/algos_take_helper.pxi.in
Labels: Internals

#54488 DOC: Prepare release notes for 2.1.0rc0 and remove 2.0.4 release notes
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.0.4.rst
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#54313 API / CoW: Add ChainedAssignmentError for inplace ops
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/tests/copy_view/test_clip.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Copy / view semantics

#54116 CoW: Copy less in replace implementation with listlikes
  pandas/core/internals/blocks.py
  pandas/tests/copy_view/test_replace.py
Labels: Copy / view semantics

#54111 CoW: Avoid tracking references in delete if not necessary
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_core_functionalities.py
Labels: Copy / view semantics

#51435 ENH: Avoid copying whole block for single block case
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/indexing/test_loc.py
Labels: Copy / view semantics

#54499 Unit test for groupby.rolling.corr
  pandas/tests/groupby/test_groupby.py
Labels: Testing, Groupby, Window

#54504 Move Unit Tests for groupby.rolling.corr
  pandas/tests/groupby/test_groupby.py
  pandas/tests/window/test_groupby.py
Labels: Testing

#54498 Speed up string inference in maybe_convert_objects
  pandas/_libs/lib.pyx
Labels: Strings

#54512 Backport PR #54498 on branch 2.1.x (Speed up string inference in maybe_convert_objects)
  pandas/_libs/lib.pyx
Labels: Strings

#54513 Backport PR #54504 on branch 2.1.x (Move Unit Tests for groupby.rolling.corr)
  pandas/tests/groupby/test_groupby.py
  pandas/tests/window/test_groupby.py
Labels: Testing

#54514 Backport PR #54509 on branch 2.1.x (PERF: Dataframe reductions with EA dtypes)
  pandas/core/frame.py
Labels: Performance, ExtensionArray, Reduction Operations

#54517 Run CI on 2.1.x
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/package-checks.yml
  .github/workflows/unit-tests.yml
Labels: CI

#54515 ENH: ArrowExtensionArray(duration) workarounds for pyarrow versions >= 11.0
  pandas/core/arrays/arrow/array.py
Labels: Upstream issue, Arrow

#54522 Backport PR #54517 on branch 2.1.x (Run CI on 2.1.x)
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/package-checks.yml
  .github/workflows/unit-tests.yml
Labels: CI

#54520 DOC: Add whatsnew file for 2.2.0
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs, Release

#54524 Backport PR #54515 on branch 2.1.x (ENH: ArrowExtensionArray(duration) workarounds for pyarrow versions >= 11.0)
  pandas/core/arrays/arrow/array.py
Labels: Upstream issue, Arrow

#54341 PERF: axis=1 reductions with EA dtypes
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/tests/frame/test_reductions.py
Labels: Performance, ExtensionArray, Reduction Operations

#54528 Backport PR #54341 on branch 2.1.x (PERF: axis=1 reductions with EA dtypes)
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/tests/frame/test_reductions.py
Labels: Performance, ExtensionArray, Reduction Operations

#54536 REF: Move checks to object into a variable
  pandas/tests/strings/__init__.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_strings.py
Labels: Refactor, Strings

#54534 REF: Move methods that can be shared with new string dtype
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
Labels: Arrow

#54538 Backport PR #54536 on branch 2.1.x (REF: Move checks to object into a variable)
  pandas/tests/strings/__init__.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_strings.py
Labels: Refactor, Strings

#54539 Backport PR #54534 on branch 2.1.x (REF: Move methods that can be shared with new string dtype)
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
Labels: Arrow

#54548 ruff 0.0.284
  .pre-commit-config.yaml
  pandas/core/arrays/base.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/category.py
  pandas/core/indexes/frozen.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/numeric.py
  pandas/io/common.py
  pandas/io/parsers/readers.py
  pandas/io/pytables.py
  pandas/io/sas/sasreader.py
  pandas/io/stata.py
  pandas/tests/frame/methods/test_to_dict.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/series/indexing/test_setitem.py
  pyproject.toml
Labels: Code Style

#54537 REF: Refactor using_pyarrow check for string tests
  pandas/tests/strings/test_find_replace.py
Labels: Refactor, Strings

#54526 DOC: Series.count remove mention of "level"
  pandas/core/series.py
Labels: Docs

#54525 BLD: Fix version script
  .circleci/config.yml
  generate_version.py
  scripts/validate_unwanted_patterns.py
Labels: Build

#54493 DOC: updated required dependencies list
  doc/source/getting_started/install.rst
Labels: Docs

#54490 DOC: Simplify missing_data.rst
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v0.21.0.rst
  doc/source/whatsnew/v0.4.x.rst
Labels: Docs

#53984 WEB/DOC: use Plausible for analytics (using Scientific Python server)
  doc/source/conf.py
  web/pandas/_templates/layout.html
Labels: Web, Stale

#54559 Backport PR #54537 on branch 2.1.x (REF: Refactor using_pyarrow check for string tests)
  pandas/tests/strings/test_find_replace.py
Labels: Refactor, Strings

#54560 Backport PR #54525 on branch 2.1.x (BLD: Fix version script)
  .circleci/config.yml
  generate_version.py
  scripts/validate_unwanted_patterns.py
Labels: Build

#54558 Backport PR #54541 on branch 2.1.x (Bump pypa/cibuildwheel from 2.14.1 to 2.15.0)
  .github/workflows/wheels.yml
Labels: Build, CI, Dependencies

#54562 Backport PR #54493 on branch 2.1.x (DOC: updated required dependencies list)
  doc/source/getting_started/install.rst
Labels: Docs

#54573 TST: use single-class pattern for Arrow, Masked tests
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
Labels: Testing, NA - MaskedArrays, Arrow

#54557 REF: remove special-casing for IntervalDtype in Index._raise_if_missing
  pandas/core/indexes/base.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/interval/test_interval_new.py
Labels: Refactor, Interval

#54511 REF: implement Dtype.index_class
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/base.py
Labels: Refactor, ExtensionArray

#54570 TST: use single-class pattern for Categorical tests
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/test_categorical.py
Labels: Testing, Categorical

#54568 REF: remove unnecessary Block specialization
  pandas/_libs/internals.pyi
  pandas/_libs/internals.pyx
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
Labels: Internals

#54545 DOC: whatsnew 2.1.0 refinements
  doc/source/reference/series.rst
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#54588 Backport PR #54545 on branch 2.1.x (DOC: whatsnew 2.1.0 refinements)
  doc/source/reference/series.rst
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#54535 REF: Replace "pyarrow" string storage checks with variable
  pandas/conftest.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/extension/test_string.py
Labels: Refactor

#54594 Backport PR #54535 on branch 2.1.x (REF: Replace "pyarrow" string storage checks with variable)
  pandas/conftest.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/extension/test_string.py
Labels: Refactor

#54581 REF: ujson cleanups
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/json/__init__.py
  pandas/tests/io/json/test_pandas.py
Labels: Refactor, IO JSON

#54576 TST: annotations, fix test_invert
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_masked.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_string.py
Labels: Testing, ExtensionArray

#54574 ENH: add cummax/cummin/cumprod support for arrow dtypes
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Enhancement, Arrow

#54603 Backport PR #54574 on branch 2.1.x (ENH: add cummax/cummin/cumprod support for arrow dtypes)
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Enhancement, Arrow

#54599 DEPR: Nonkeyword arguments in to_pickle
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/io/test_pickle.py
Labels: Deprecate, IO Pickle

#54491 DEPR: Positional arguments in to_hdf except path_or_buf
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.11.0.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v0.17.0.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/pytables/test_complex.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_pytables_missing.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_retain_attributes.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/pytables/test_subclass.py
Labels: IO HDF5

#54601 DEPR: Nonkeyword arguments in to_latex
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/io/formats/test_to_latex.py
Labels: Deprecate

#54597 DEPR: deprecated nonkeyword arguments for to_string
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/tests/io/formats/test_to_string.py
Labels: Deprecate

#54587 CI: Enable MacOS Python Dev tests
  .github/workflows/unit-tests.yml
Labels: CI

#54615 DOC: Update build instructions in the README
  README.md
Labels: Docs

#54619 Backport PR #54615 on branch 2.1.x (DOC: Update build instructions in the README)
  README.md
Labels: Docs

#54614 Backport PR #54587 on branch 2.1.x (CI: Enable MacOS Python Dev tests)
  .github/workflows/unit-tests.yml
Labels: CI

#54549 Fixed unexpected np.nan value with reindex on pd.series with pd.Inter…
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexing/interval/test_interval.py
Labels: Missing-data, Interval

#54617 DOC: Convert docstring to numpydoc.
  pandas/core/common.py
Labels: Docs

#54613 DEPR: deprecated nonkeyword arguments in to_json
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Deprecate

#54605 DEPR: deprecated nonkeyword arguments in to_markdown
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/io/formats/test_to_markdown.py
Labels: Deprecate

#54457 Clean up autosummary usage
  doc/_templates/autosummary/class.rst
  doc/source/conf.py
  doc/source/reference/series.rst
Labels: Docs

#54618 DOC: Add information on fetching tags for contributors building pandas.
  doc/source/development/contributing_codebase.rst
  doc/source/development/contributing_environment.rst
Labels: Docs
