Repository pandas-dev/pandas, pull requests merged in 2023-11, with the labels that each got.

#55788 DOC: Index docstring to clarify dtype
  pandas/core/indexes/base.py
Labels: Docs, Index

#55726 fix segfault with tz_localize_to_utc
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Timezones

#55778 ENH/POC: infer resolution in array_strptime
  pandas/_libs/tslibs/strptime.pxd
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/tslibs/test_strptime.py
Labels: Non-Nano

#55796 Backport PR #55726 on branch 2.1.x (fix segfault with tz_localize_to_utc)
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Timezones

#55798 CLN: __repr__ tests
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_insert.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/frame/test_repr.py
  pandas/tests/indexes/base_class/test_formats.py
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/datetimes/test_formats.py
  pandas/tests/indexes/datetimes/test_ops.py
  pandas/tests/indexes/interval/test_formats.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/period/test_formats.py
  pandas/tests/indexes/ranges/test_range.py
  pandas/tests/indexes/timedeltas/test_formats.py
  pandas/tests/indexes/timedeltas/test_join.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_printing.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/reshape/test_crosstab.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_repr.py
Labels: Testing, Output-Formatting

#51463 PDEP-7: Consistent copy/view semantics in pandas with Copy-on-Write
  web/pandas/pdeps/0007-copy-on-write.md
Labels: Copy / view semantics, PDEP

#55780 BUG: to_datetime with mixed-string-and-numeric
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslib.pyx
  pandas/core/arrays/datetimelike.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/tools/test_to_datetime.py
Labels: Timeseries

#55734 DEPR: errors='ignore'
  doc/source/user_guide/basics.rst
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v0.17.0.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/melt.py
  pandas/core/tools/datetimes.py
  pandas/core/tools/numeric.py
  pandas/core/tools/timedeltas.py
  pandas/core/tools/times.py
  pandas/io/parsers/base_parser.py
  pandas/io/sql.py
  pandas/tests/test_algos.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_numeric.py
  pandas/tests/tools/test_to_time.py
  pandas/tests/tools/test_to_timedelta.py
Labels: Deprecate

#55804 CI: parametrize and xfail
  pandas/tests/indexes/datetimes/test_constructors.py
Labels: CI

#55806 TST: parametrize over unit
  pandas/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/base/test_conversion.py
  pandas/tests/base/test_value_counts.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/test_algos.py
Labels: Testing, Non-Nano

#55777 List accessor
  doc/source/reference/series.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/__init__.py
  pandas/core/arrays/arrow/accessors.py
  pandas/core/series.py
  pandas/tests/series/accessors/test_list_accessor.py
  pandas/tests/series/accessors/test_struct_accessor.py
Labels: Nested Data, Arrow

#55762 DOC: Fixes DataFrame.replace documentation
  pandas/core/shared_docs.py
Labels: Docs

#55805 ENH/BUG: infer reso in array_strptime
  pandas/_libs/tslibs/strptime.pxd
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/tslibs/test_strptime.py
Labels: Non-Nano

#55814 DOC: Add "nullable float" link in "dtypes" table of User Guide
  doc/source/user_guide/basics.rst
Labels: Docs

#55813 BUG: DatetimeIndex with dayfirst/yearfirst and tz
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslib.pyi
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_constructors.py
Labels: Bug, Timezones

#55818 TST: parametrize over dt64 unit
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/indexes/datetimes/methods/test_delete.py
  pandas/tests/indexes/datetimes/methods/test_insert.py
  pandas/tests/indexes/datetimes/methods/test_repeat.py
  pandas/tests/indexes/datetimes/methods/test_round.py
  pandas/tests/indexes/datetimes/methods/test_tz_localize.py
  pandas/tests/indexes/datetimes/test_formats.py
  pandas/tests/reshape/concat/test_datetimes.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_combine_first.py
  pandas/tests/series/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_dropna.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tseries/offsets/test_business_hour.py
Labels: Testing, Non-Nano

#55821 BUG: Index.isin raising for arrow strings and null set
  doc/source/whatsnew/v2.1.3.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/indexes/test_base.py
Labels: Arrow

#55822 ENH: infer resolution in array_to_datetime_with_tz
  pandas/_libs/tslib.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Timezones, Non-Nano

#55831 DOC: replace deprecated freqs in user_guide Period
  doc/source/user_guide/timeseries.rst
Labels: Docs

#55823 TST: Fix shares_memory for arrow string dtype
  pandas/_testing/__init__.py
  pandas/tests/util/test_shares_memory.py
Labels: Testing, Strings, Arrow

#55812 BUG: `assert_extension_array_equal` using the wrong dtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_extension_array_equal.py
Labels: Testing, Non-Nano

#55795 Add missing dependencies for: _khash_primitive_helper
  pandas/_libs/meson.build
Labels: Build

#55816 PERF: IndexEngine.get_indexer_non_unique
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/index.pyx
Labels: Performance, Index

#55837 REF: make plotting less stateful
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Visualization, Clean

#55839 REF/PERF: MultiIndex.get_indexer with method
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/index.pyi
  pandas/_libs/index.pyx
  pandas/core/indexes/base.py
Labels: Refactor, Performance, MultiIndex

#55817 COMPAT: Numpy int64 Windows default for Numpy 2.0
  pandas/compat/numpy/__init__.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_reductions.py
Labels: Windows, Compat

#55851 Backport PR #55817 on branch 2.1.x (COMPAT: Numpy int64 Windows default for Numpy 2.0)
  pandas/compat/numpy/__init__.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_reductions.py
Labels: Windows, Compat

#55819 Backport PR #55761 on branch 2.1.x (BUG: DatetimeIndex.diff raising TypeError)
  doc/source/whatsnew/v2.1.3.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_datetimelike.py
Labels: Bug, Index

#55829 TYP: plotting
  pandas/plotting/_matplotlib/core.py
Labels: Visualization, Typing

#55736 PERF: Use fused types for map_infer_mask
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/dtypes.pxd
  pandas/_libs/lib.pyx
  pandas/core/arrays/string_.py
Labels: Performance, Dtype Conversions

#55830 TST: Parameterize & make tests more performant
  pandas/tests/apply/conftest.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/io/generate_legacy_storage_files.py
  pandas/tests/io/parser/test_textreader.py
  pandas/tests/io/test_pickle.py
  pandas/tests/reshape/concat/test_dataframe.py
Labels: Testing

#55850 REF: make plotting less stateful (2)
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Refactor, Visualization

#55853 DEPS: Use ipython run_cell instead of run_code; remove pytest-asyncio
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  ci/meta.yaml
  environment.yml
  pandas/tests/arrays/categorical/test_warnings.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/test_base.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/util/_test_decorators.py
  pyproject.toml
  requirements-dev.txt
  scripts/tests/data/deps_expected_random.yaml
  scripts/tests/data/deps_minimum.toml
  scripts/tests/data/deps_unmodified_random.yaml
  tooling/debug/Dockerfile.pandas-debug
Labels: Testing, Dependencies

#55754 fixed bug where pd.NA was being cast to NaN during formatting
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Bug, Missing-data, Output-Formatting

#55862 DOC: fix spelling of deque
  doc/source/whatsnew/v1.0.0.rst
Labels: Docs

#55227 BUG: Interchange object data buffer has the wrong dtype / from_dataframe incorrect
  pandas/core/interchange/from_dataframe.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#55860 TST: avoid usage of unnecessary xfail in test_datetime64
  pandas/tests/arithmetic/test_datetime64.py
Labels: Testing

#55857 Added str to index_col attribute in the read_excel function description
  pandas/io/excel/_base.py
Labels: IO Excel, Typing

#55861 TST: clean-up various tests avoiding CoW issues
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_nonunique_indexes.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Testing

#55858 Backport PR #55853: DEPS: Use ipython run_cell instead of run_code; remove pytest-asyncio
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  ci/meta.yaml
  environment.yml
  pandas/tests/arrays/categorical/test_warnings.py
  pandas/tests/frame/test_api.py
  pandas/tests/indexes/test_base.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/util/_test_decorators.py
  pyproject.toml
  requirements-dev.txt
  scripts/tests/data/deps_expected_random.yaml
  scripts/tests/data/deps_minimum.toml
  scripts/tests/data/deps_unmodified_random.yaml
Labels: Dependencies

#55844 ENH: Raise TypeError for offsets which are not supported as period frequency
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
Labels: Frequency, Period

#53769 DEPR: deprecate returning a tuple from a callable in iloc indexing
  doc/source/user_guide/indexing.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, Deprecate

#55855 TST: Make read_csv tests pyarrow 13 compatable on 2.1.x
  pandas/tests/interchange/test_impl.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: Testing, IO CSV, Arrow

#55841 BUG: Fix rounding of percentile 99.999% to 100%
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Algos

#55870 REF: misplaced tests, parametrize, simplify
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/arrays/interval/test_formats.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/arrays/interval/test_overlaps.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/groupby/methods/test_nth.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/libs/test_libalgos.py
  pandas/tests/series/test_formats.py
  pandas/tests/test_algos.py
  pandas/tests/tools/test_to_datetime.py
Labels: Testing

#55246 Create broken-linkcheck.yml
  .github/workflows/broken-linkcheck.yml
  doc/source/conf.py
Labels: Docs, CI

#55872 REF: make plotting less stateful (4)
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/timeseries.py
Labels: Refactor, Visualization

#55811 PERF: avoid unnecessary method call in get_indexer_non_unique() on MultiIndex
  pandas/core/indexes/base.py
Labels: MultiIndex, Clean

#55863 Backport PR #55227 on branch 2.1.x (BUG: Interchange object data buffer has the wrong dtype / from_dataframe incorrect )
  pandas/core/interchange/from_dataframe.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#55871 TST: Simplify tests, remove unnecessary minversions
  pandas/tests/arrays/masked/test_arrow_compat.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/io/conftest.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/test_downstream.py
Labels: Testing

#55878 REF: make BarPlot attributes cache_readonlys
  pandas/plotting/_matplotlib/core.py
Labels: Refactor, Visualization

#55877 TYP: plotting, make weights kwd explicit
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Visualization, Typing

#55591 DEPR: fix stacklevel for DataFrame(mgr) deprecation
  doc/source/user_guide/10min.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/pyarrow.rst
  doc/source/user_guide/scale.rst
  doc/source/whatsnew/v2.0.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/arrays/interval/test_interval.py
  pandas/tests/arrays/masked/test_arrow_compat.py
  pandas/tests/arrays/period/test_arrow_compat.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
  pandas/tests/io/test_orc.py
  pandas/tests/test_downstream.py
Labels: Internals, Warnings

#55764 REGR: fix return class in _constructor_from_mgr for simple subclasses
  doc/source/whatsnew/v2.1.3.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/test_subclass.py
Labels: Regression, Subclassing

#55792 DEPR offsets: rename ‘Y’ to ‘YE'
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/period/test_arrow_compat.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/methods/test_asfreq.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_to_timestamp.py
  pandas/tests/frame/test_repr.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/indexes/datetimes/methods/test_resolution.py
  pandas/tests/indexes/datetimes/methods/test_round.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timedelta/methods/test_round.py
  pandas/tests/series/test_formats.py
  pandas/tests/tseries/frequencies/test_freq_code.py
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tslibs/test_conversion.py
  pandas/tseries/frequencies.py
Labels: Frequency, Deprecate

#55886 REF: make plotting less stateful (6)
  pandas/plotting/_matplotlib/core.py
Labels: Refactor, Visualization

#55887 TYP: plotting
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/groupby.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/timeseries.py
Labels: Visualization, Typing

#55807 ENH: Allow passing `read_only`, `data_only` and `keep_links` arguments to openpyxl using `engine_kwargs`
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/excel/_openpyxl.py
  pandas/tests/io/excel/test_openpyxl.py
Labels: IO Excel

#55793 BUG: mixed-type mixed-timezone/awareness
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/strptime.pxd
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/indexes/test_index_new.py
  pandas/tests/tools/test_to_datetime.py
Labels: Timezones

#55896 Backport PR #55427 on branch 2.1.x (DOC: Remove outdated docs about NumPy's broadcasting)
  doc/source/user_guide/basics.rst
Labels: Docs

#55889 REF: Mess with data less outside of MPLPlot.__init__
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Refactor, Visualization

#55892 Backport PR #55764 on branch 2.1.x (REGR: fix return class in _constructor_from_mgr for simple subclasses)
  doc/source/whatsnew/v2.1.3.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/frame/test_subclass.py
Labels: Regression, Subclassing

#55894 Parquet/Feather IO: disable PyExtensionType autoload
  doc/source/whatsnew/v2.1.3.rst
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/core/arrays/arrow/extension_types.py
  pandas/io/feather_format.py
Labels: IO Parquet

#55900 Backport PR #55894 on 2.1.x: Parquet/Feather IO: disable PyExtensionType autoload
  doc/source/whatsnew/v2.1.3.rst
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/core/arrays/arrow/extension_types.py
  pandas/io/feather_format.py
Labels: IO Parquet

#55911 DOC: convert outdated example of NumPy's broadcasting to literal code block
  doc/source/whatsnew/v0.17.0.rst
Labels: Docs

#55907 DOC: Add release date for 2.1.3
  doc/source/whatsnew/v2.1.3.rst
Labels: Docs

#55913 Backport PR #55907 on branch 2.1.x (DOC: Add release date for 2.1.3)
  doc/source/whatsnew/v2.1.3.rst
Labels: Docs

#55838 CoW warning mode: add warning for single block setitem
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/internals/managers.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/copy_view/index/test_datetimeindex.py
  pandas/tests/copy_view/index/test_index.py
  pandas/tests/copy_view/index/test_periodindex.py
  pandas/tests/copy_view/index/test_timedeltaindex.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/copy_view/test_setitem.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_pop.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/frame/test_api.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/period/test_partial_slicing.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/multiindex/test_slice.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iat.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/methods/test_copy.py
  pandas/tests/series/methods/test_cov_corr.py
  pandas/tests/series/methods/test_get_numeric_data.py
Labels: Copy / view semantics

#55912 Backport PR #55911 on branch 2.1.x (DOC: convert outdated example of NumPy's broadcasting to literal code block)
  doc/source/whatsnew/v0.17.0.rst
Labels: Docs

#55915 Fix Cython 3.0 regression with time_loc_dups
  pandas/_libs/index.pyx
Labels: Performance, Internals

#55917 REF: less state in scatterplot
  pandas/plotting/_matplotlib/core.py
Labels: Refactor, Visualization

#55906 REF: avoid altering self.data in get_xticks
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Refactor, Visualization

#55888 REF: Ensure MPLPlot.data is a DataFrame after __init__
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Refactor, Visualization

#55902 BLD: Bump our C standard to 11
  meson.build
Labels: Build

#55918 TST: de-xfail some pyarrow tests
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/common/test_decimal.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/common/test_ints.py
  pandas/tests/io/parser/common/test_iterator.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/common/test_verbose.py
  pandas/tests/io/parser/dtypes/test_categorical.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: Testing, IO CSV, Arrow

#55921 ASV: avoid "H" and "S" freq deprecations
  asv_bench/benchmarks/algorithms.py
  asv_bench/benchmarks/arithmetic.py
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/gil.py
  asv_bench/benchmarks/groupby.py
  asv_bench/benchmarks/indexing.py
  asv_bench/benchmarks/inference.py
  asv_bench/benchmarks/io/csv.py
  asv_bench/benchmarks/io/excel.py
  asv_bench/benchmarks/io/hdf.py
  asv_bench/benchmarks/io/json.py
  asv_bench/benchmarks/io/pickle.py
  asv_bench/benchmarks/io/stata.py
  asv_bench/benchmarks/join_merge.py
  asv_bench/benchmarks/period.py
  asv_bench/benchmarks/series_methods.py
  asv_bench/benchmarks/strftime.py
  asv_bench/benchmarks/timeseries.py
Labels: Benchmark

#55924 DOC: add whatsnew for 2.1.4
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.1.4.rst
Labels: Docs

#55931 PERF: Cython 3.0 regression with frame constructor
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
Labels: Performance, DataFrame, Constructors

#55937 Backport PR #55924 on branch 2.1.x (DOC: add whatsnew for 2.1.4)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.1.4.rst
Labels: Docs

#55920 Fix off-by-one in aggregations
  pandas/core/indexers/objects.py
Labels: Window, Segfault

#55926 TST: Group by callable test
  pandas/tests/groupby/test_grouping.py
Labels: Testing

#55904 REF: avoid statefulness in 'color' args
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
Labels: Refactor, Visualization

#55941 Cython 3.0 faster maybe_convert_objects
  pandas/_libs/lib.pyx
Labels: Internals

#55890 ENH: warn when silently ignoring log keywords in PiePlot
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Refactor, Visualization

#55942 Backport PR #55920 on branch 2.1.x (Fix off-by-one in aggregations)
  pandas/core/indexers/objects.py
Labels: Window, Segfault

#55950 REF: simplify objects_to_datetime64ns
  pandas/core/arrays/datetimes.py
  pandas/core/tools/datetimes.py
Labels: Refactor, Timeseries

#55923 ASV: clean/simplify setup methods
  asv_bench/benchmarks/algorithms.py
  asv_bench/benchmarks/array.py
  asv_bench/benchmarks/categoricals.py
  asv_bench/benchmarks/frame_methods.py
  asv_bench/benchmarks/gil.py
  asv_bench/benchmarks/groupby.py
  asv_bench/benchmarks/index_object.py
  asv_bench/benchmarks/indexing_engines.py
  asv_bench/benchmarks/series_methods.py
Labels: Benchmark

#55927 Fixes #55884- Added else for invalid fill_method
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_ordered.py
Labels: Reshaping, Error Reporting

#55938 ASV: DataFrame.__setitem__ performance with object dtype
  asv_bench/benchmarks/indexing.py
Labels: Benchmark

#55952 DOC: Updates typo in to_timedelta docs
  pandas/core/tools/timedeltas.py
Labels: Docs, Timedelta

#55939 ASV: add FrameMixedDtypesOps
  asv_bench/benchmarks/stat_ops.py
Labels: Benchmark

#55868 DEPR: read_gbq, DataFrame.to_gbq
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  doc/source/conf.py
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/io/gbq.py
  pandas/tests/io/test_gbq.py
  pandas/tests/test_downstream.py
  scripts/tests/data/deps_expected_random.yaml
  scripts/tests/data/deps_minimum.toml
  scripts/tests/data/deps_unmodified_random.yaml
Labels: IO Google, Deprecate

#55943 TST: Skip pyarrow csv tests that raise ParseErrors
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/common/test_data_list.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/common/test_float.py
  pandas/tests/io/parser/common/test_index.py
  pandas/tests/io/parser/common/test_inf.py
  pandas/tests/io/parser/common/test_ints.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/io/parser/dtypes/test_categorical.py
  pandas/tests/io/parser/dtypes/test_empty.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_index_col.py
  pandas/tests/io/parser/test_mangle_dupes.py
  pandas/tests/io/parser/test_na_values.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_quoting.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/io/parser/usecols/test_parse_dates.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
Labels: Testing, Arrow

#55949 PERF: assert_frame_equal and assert_series_equal for frames/series with a MultiIndex
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/testing.pyx
  pandas/_testing/asserters.py
  pandas/tests/frame/methods/test_value_counts.py
Labels: Testing, Performance

#55940 ENH: Improve error message when constructing period with invalid freq
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/period/test_period.py
Labels: Frequency, Deprecate

#55957 TST: split and parametrize
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/io/test_stata.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Testing

#55958 BUG: astype, asfreq with non-nano
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/period.py
  pandas/core/resample.py
  pandas/tests/indexes/period/methods/test_astype.py
  pandas/tests/resample/test_datetime_index.py
Labels: Non-Nano

#55959 TST: parametrize tests over dt64 unit
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/series/methods/test_map.py
  pandas/tests/series/methods/test_quantile.py
  pandas/tests/series/methods/test_tz_localize.py
  pandas/tests/series/methods/test_value_counts.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/test_algos.py
  pandas/tests/tseries/holiday/test_calendar.py
  pandas/tests/tseries/holiday/test_holiday.py
  pandas/tests/tseries/offsets/test_business_hour.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_timeseries_window.py
Labels: Testing, Non-Nano

#55953 BUG: disallow how keyword in shared-ax plotting
  doc/source/whatsnew/v2.2.0.rst
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/plotting/test_datetimelike.py
Labels: Visualization

#55961 BUG: PeriodIndex.__new__ with keyword mismatch
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/period.py
  pandas/tests/indexes/period/test_constructors.py
Labels: Error Reporting, Period

#55966 TST: collect date_range tests, parametrize over unit
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/tseries/offsets/test_business_hour.py
  pandas/tests/tseries/offsets/test_custom_business_month.py
  pandas/tests/tseries/offsets/test_month.py
Labels: Testing, Non-Nano

#55151 Remove undefined behavior from npy_datetimestruct_to_datetime
  asv_bench/benchmarks/tslibs/period.py
  pandas/_libs/src/vendored/numpy/datetime/np_datetime.c
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timestamps.pxd
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/methods/test_replace.py
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Refactor, Internals

#55741 POC/ENH: infer resolution in array_to_datetime
  pandas/_libs/tslib.pyx
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Non-Nano

#55253 TYP: towards matplotlib 3.8
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/plotting/_matplotlib/style.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/io/test_sql.py
  pandas/tests/plotting/common.py
  pyright_reportGeneralTypeIssues.json
  requirements-dev.txt
Labels: Visualization, Typing

#55963 DEPR: PeriodIndex ordinal, fields keywords
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/period.py
  pandas/core/indexes/period.py
  pandas/io/pytables.py
  pandas/tests/indexes/period/methods/test_to_timestamp.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/test_old_base.py
Labels: Period, Deprecate

#55979 BUG: dt64 astype silent overflows
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/tests/arrays/test_datetimes.py
Labels: Astype, Non-Nano

#55974 TST: parametrize over dt64 unit
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/groupby/methods/test_nth.py
  pandas/tests/groupby/methods/test_quantile.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexes/datetimes/methods/test_delete.py
  pandas/tests/indexes/datetimes/methods/test_repeat.py
  pandas/tests/indexes/datetimes/methods/test_tz_localize.py
  pandas/tests/indexes/datetimes/methods/test_unique.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/tseries/offsets/test_business_hour.py
  pandas/tests/tseries/offsets/test_month.py
  pandas/tests/window/test_ewm.py
Labels: Testing, Non-Nano

#55719 DEPR: groupby.fillna
  doc/source/whatsnew/v2.2.0.rst
  pandas/conftest.py
  pandas/core/groupby/generic.py
  pandas/tests/apply/test_str.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_missing.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Missing-data, Deprecate, Transformations

#55967 TST: Move groupby tests out of test_function
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/methods/test_describe.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_cumulative.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_reductions.py
Labels: Testing, Groupby, Clean

#55994 CI fix ci whatsnew items
  doc/source/whatsnew/v2.2.0.rst
Labels: CI

#55995 REF: use numpy cimports
  pandas/_libs/interval.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/util.pxd
Labels: Clean

#55993 TST update and simplify consortium api test
  pandas/tests/test_downstream.py
Labels: Testing, Interchange

#55986 CLN: remove unused unit argument
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pxd
  pandas/_libs/tslibs/conversion.pyx
Labels: Clean

#55985 CLN: remove unnecessary bits from dtypes.pyx
  pandas/_libs/tslibs/ccalendar.pxd
  pandas/_libs/tslibs/ccalendar.pyx
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/tseries/frequencies/test_freq_code.py
Labels: Clean

#55984 Remove address violation with safe_sort
  pandas/core/algorithms.py
  pandas/tests/test_sorting.py
Labels: Bug

#55987 REF: de-duplicate freq pinning/validation
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
Labels: Refactor, Frequency

#55983 ENH: dont hard-code nanoseconds in overflow exception message
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
Labels: Error Reporting, Non-Nano

#55962 TST: parametrize and improve test performance
  pandas/tests/frame/test_iteration.py
  pandas/tests/indexes/datetimes/test_indexing.py
  pandas/tests/indexing/multiindex/test_multiindex.py
  pandas/tests/io/test_stata.py
  pandas/tests/resample/test_resample_api.py
Labels: Testing

#55395 BUG: avoid DeprecationWarning when the Series has index as list of Series
  doc/source/whatsnew/v2.1.4.rst
  pandas/_libs/lib.pyx
  pandas/tests/series/test_constructors.py
Labels: Warnings

#55981 BUG: resolution inference with NaT ints/floats/strings
  pandas/_libs/lib.pyx
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Missing-data, Non-Nano

#55179 DEP: Use Cython 3.0
  asv_bench/asv.conf.json
  environment.yml
  pandas/_libs/arrays.pyi
  pandas/_libs/groupby.pyi
  pandas/_libs/hashtable.pyi
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/lib.pyi
  pandas/_libs/ops.pyi
  pandas/_libs/sparse.pyi
  pandas/_libs/tslibs/conversion.pyi
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/strptime.pyi
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_libs/tslibs/tzconversion.pyi
  pandas/_libs/tslibs/vectorized.pyi
  pandas/_libs/window/aggregations.pyi
  pandas/core/arrays/datetimelike.py
  pyproject.toml
  requirements-dev.txt
  scripts/run_stubtest.py
  setup.py
Labels: Dependencies

#56011 REF: use conditional-nogil in libgroupby
  pandas/_libs/groupby.pyx
Labels: Internals

#56009 PERF: assert_produces_warning
  pandas/_testing/_warnings.py
Labels: Testing, Performance

#56006 CLN: remove cython<3 reversed-op pattern
  pandas/_libs/interval.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Internals

#55978 DEPR: rename BQ to BQE for offsets
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/methods/test_asfreq.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/frequencies.py
Labels: Frequency, Deprecate

#56015 CI/TST: Skip pyarrow csv tests where parsing fails
  .github/workflows/unit-tests.yml
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
Labels: Testing, IO CSV, CI, Arrow

#54846 DEPR: remove use of `nan_as_null` from callers of `__dataframe__`
  pandas/core/frame.py
  pandas/core/interchange/dataframe.py
Labels: Interchange

#56023 [Docstring] Update a link to SQLAlchemy documentation to be compatible with 2.0
  pandas/io/sql.py
Labels: Docs

#55977 Use NumPy macros for overflow detection
  pandas/_libs/src/vendored/numpy/datetime/np_datetime.c
Labels: Build, Internals

#55341 ENH: Implement convert_dtypes on block level
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/frame/methods/test_convert_dtypes.py
Labels: Dtype Conversions

#56004 BUG: DatetimeIndex with non-nano dtype and mixed numeric inputs
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslib.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/series/methods/test_astype.py
Labels: Non-Nano

#56002 CLN: use cimports for type checks
  pandas/_libs/lib.pyx
  pandas/_libs/tslibs/util.pxd
Labels: Clean

#55742 BUG: fix nanmedian for CoW without bottleneck
  pandas/core/nanops.py
Labels: Bug, Copy / view semantics, Reduction Operations

#56020 CoW warning mode: setting values into single column of DataFrame
  pandas/core/computation/eval.py
  pandas/core/frame.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/computation/test_eval.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_core_functionalities.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/frame/methods/test_update.py
  pandas/tests/groupby/methods/test_nth.py
  pandas/tests/groupby/methods/test_quantile.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_iat.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_stata.py
Labels: Copy / view semantics

#56026 STY: Fix whatsnew ordering
  doc/source/whatsnew/v2.2.0.rst
Labels: Code Style

#56000 Fix apply na overflow
  pandas/core/methods/selectn.py
Labels: Bug

#56025 REF: use conditional-nogil in libalgos
  pandas/_libs/algos.pyx
Labels: Internals

#55745 CoW - don't try to update underlying values of Series/column inplace for inplace operator
  pandas/core/generic.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#56028 REF: cython3 cleanups
  pandas/_libs/algos.pyx
  pandas/_libs/arrays.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/internals.pyx
  pandas/_libs/lib.pyx
  pandas/_libs/parsers.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/util.pxd
Labels: Internals

#56027 TST: Simplify and clarify test skipping
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/computation/test_eval.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_string.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/plotting/frame/test_frame_legend.py
  pandas/tests/plotting/test_backend.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/strings/test_extract.py
  pandas/tests/util/test_safe_import.py
  pandas/tests/window/test_rolling_functions.py
  pandas/util/_test_decorators.py
Labels: Testing

#56018 remove ctypedef class from lib.pyx
  pandas/_libs/lib.pyx
Labels: Internals

#56016 BUG: GroupBy.value_counts sorting order
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/methods/test_value_counts.py
Labels: Bug, Groupby, Algos

#55971 PERF: assert_frame_equal / assert_series_equal
  doc/source/whatsnew/v2.2.0.rst
  pandas/_testing/asserters.py
  pandas/core/dtypes/missing.py
  pandas/tests/dtypes/test_missing.py
Labels: Testing, Performance

#56031 DOC: Fix GH# in whatsnew not for DataFrameGroupBy.value_counts bugfix
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/groupby/groupby.py
Labels: Docs

#56030 ASV: Add benchmarks for groupby with multiple categories
  asv_bench/benchmarks/groupby.py
Labels: Enhancement, Groupby, Categorical, Benchmark

#56029 Avoid warning in DateOffset addition
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Numeric Operations, Frequency, Warnings

#56038 DEPR: is_period, is_interval
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/lib.pyx
  pandas/core/dtypes/cast.py
  pandas/core/indexes/interval.py
  pandas/tests/dtypes/test_inference.py
Labels: Period, Deprecate, Interval

#56035 TST: de-xfail pyarrow parser tests
  pandas/tests/io/parser/test_comment.py
  pandas/tests/io/parser/test_converters.py
Labels: Testing, IO CSV, Arrow

#56040 TST: de-xfail pyarrow dialect tests
  pandas/tests/io/parser/test_dialect.py
Labels: IO CSV, Arrow

#56049 REGR: sort_index with ascending as list of boolean
  pandas/core/sorting.py
  pandas/tests/series/methods/test_sort_index.py
Labels: Regression, MultiIndex
