Repository pandas-dev/pandas, pull requests merged in 2023-06, with the labels that each got.

#53474 TST: fix import in test_hash_pandas_object extension test
  pandas/tests/extension/base/methods.py
Labels: Testing

#53484 DEV: Create CODEOWNERS
  .github/CODEOWNERS
Labels: Admin

#53482 BUG: dtype from nankurt and nanskew when returning 0
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/nanops.py
  pandas/tests/reductions/test_stat_reductions.py
Labels: Reduction Operations

#53479 TYP: algos.isin
  pandas/core/algorithms.py
  pandas/core/tools/datetimes.py
  pandas/io/parsers/base_parser.py
Labels: Typing

#53478 Removed unused argument from groupby cython impl
  pandas/_libs/groupby.pyx
Labels: Groupby, Clean

#53477 DOC: point out that only period frequencies are valid for to_period
  pandas/core/arrays/datetimes.py
Labels: Docs, Period

#52986 DEPR: accepting non-standard sequences in core.algorithms functions
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/algorithms.py
  pandas/core/arrays/categorical.py
  pandas/core/indexes/multi.py
  pandas/core/reshape/tile.py
  pandas/core/tools/datetimes.py
  pandas/tests/indexes/period/methods/test_factorize.py
  pandas/tests/libs/test_hashtable.py
  pandas/tests/reshape/test_cut.py
  pandas/tests/test_algos.py
Labels: Deprecate

#53419 DEPR: Series.first() and DataFrame.first()
  doc/source/whatsnew/v2.1.0.rst
  pandas/conftest.py
  pandas/core/generic.py
  pandas/tests/frame/methods/test_first_and_last.py
  pandas/tests/generic/test_finalize.py
Labels: Frequency, Deprecate

#53442 DOC: PDEP6 page format update
  web/pandas/pdeps/0006-ban-upcasting.md
Labels: Web

#53471 Backport PR #53231 on branch 2.0.x (PERF: fix merging on datetimelike columns to not use object-dtype factorizer)
  asv_bench/benchmarks/join_merge.py
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/reshape/merge.py
Labels: Timeseries, Performance, Reshaping

#53489 BLD: Fix compiling pandas with a venv located in the src dir
  pandas/meson.build
Labels: Build

#53087 CI: Build wheel from sdist
  .github/workflows/wheels.yml
  MANIFEST.in
  ci/fix_wheels.py
  ci/test_wheels.py
  ci/test_wheels_windows.bat
  pandas/util/_tester.py
  pyproject.toml
Labels: Build, CI

#53298 ENH: Add sort keyword to unstack
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/core/reshape/reshape.py
  pandas/core/series.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Enhancement, Reshaping

#53499 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/core/strings/accessor.py
Labels: Docs

#52830 COMPAT: Use actual isinstance check for pyarrow.Array instead of hasattr(.. 'type') duck typing
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/arrays/string_.py
Labels: Arrow

#53392 DOC: Adjust build command for building with meson
  doc/source/development/contributing_environment.rst
Labels: Docs

#53502 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
  pandas/core/strings/accessor.py
Labels: Docs

#53486 ENH: Groupby agg support multiple funcs numba
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/apply.py
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_numba.py
Labels: Enhancement, Groupby, numba

#53443 ENH: xz compression_args df.to_pickle(path, compression={'method':'xz','pr…
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/shared_docs.py
  pandas/io/common.py
  pandas/tests/io/test_compression.py
Labels: IO Data

#53510 STY: Enable Ruff specific checks
  pandas/_config/config.py
  pandas/_libs/__init__.py
  pandas/api/types/__init__.py
  pandas/core/dtypes/dtypes.py
  pyproject.toml
Labels: Code Style

#53506 Cython Groupby unused argument removal
  pandas/_libs/groupby.pyx
  pandas/core/groupby/groupby.py
Labels: Groupby, Clean, Transformations

#53526 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
  pandas/core/arrays/sparse/accessor.py
  pandas/core/arrays/sparse/array.py
  pandas/core/flags.py
  pandas/core/indexes/datetimes.py
Labels: Docs

#53522 docs: Fix alignment in "merge_ordered" docstring
  pandas/core/reshape/merge.py
Labels: Docs

#53519 BUG: groupby.nth after selection
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_nth.py
Labels: Bug, Groupby, Filters

#53513 BUG: merge_asof raising ValueError for read-only ndarrays
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/join.pyi
  pandas/_libs/join.pyx
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Bug, Reshaping

#53536 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/arrays/sparse/accessor.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/plotting/_core.py
Labels: Docs

#53508 CI: Bump builds to 3.11, update numpy nightly wheels location
  .circleci/config.yml
  .github/workflows/unit-tests.yml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/circle-310-arm64.yaml
  pandas/core/sorting.py
  pandas/core/window/rolling.py
Labels: CI

#53517 FIX `groupby` with column selection not returning tuple when grouping by list of a single element
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby

#53544 TST: Remove inheritance from pandas/tests/indexes
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/datetimes/test_datetimelike.py
  pandas/tests/indexes/interval/test_base.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/period/test_period.py
  pandas/tests/indexes/ranges/test_range.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_datetimelike.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/indexes/timedeltas/test_timedelta.py
Labels: Testing, Index

#53532 BUG: Series.str.split(expand=True) for ArrowDtype(pa.string())
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/strings/accessor.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Strings, Arrow

#53543 TST: Clean up finalize tests
  pandas/tests/generic/test_finalize.py
Labels: Testing, metadata

#53538 BUG: Fix metadata propagation in squeeze and describe
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/tests/generic/test_finalize.py
Labels: metadata

#53325 DEPR: make Series.agg aggregate when possible
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/apply.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_frame_transform.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/apply/test_series_transform.py
Labels: Deprecate, Apply

#53435 DOC: Update release process
  doc/source/development/maintaining.rst
Labels: Docs, Release

#53540 DOC: Fixing EX01 - Added more examples
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs

#53552 TST: Add test for timedelta of fraction GH#9048
  pandas/tests/tools/test_to_timedelta.py
Labels: Testing

#53551 TST: Add test for complex categories GH#16399
  pandas/tests/dtypes/test_dtypes.py
Labels: Testing

#53549 Backport PR #53532 on branch 2.0.x (BUG: Series.str.split(expand=True) for ArrowDtype(pa.string()))
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/strings/accessor.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Strings, Arrow

#53555 Backport PR #53435 on branch 2.0.x (DOC: Update release process)
  doc/source/development/maintaining.rst
Labels: Docs, Release

#53554 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs

#53496 DEPR: fillna method kwd
  ci/code_checks.sh
  doc/source/getting_started/comparison/includes/missing.rst
  doc/source/user_guide/basics.rst
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v0.10.0.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/conftest.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_pct_change.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/generic/test_finalize.py
  pandas/tests/groupby/test_missing.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/series/methods/test_align.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/series/methods/test_pct_change.py
  pandas/tests/series/methods/test_reindex.py
  pandas/tests/window/moments/test_moments_consistency_ewm.py
  pandas/tests/window/test_ewm.py
Labels: Deprecate, Transformations

#53556 ENH: Numba groupby support multiple labels
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
Labels: numba

#53541 CI: Bump builds to 3.11, update numpy nightly wheels location (#53508)
  .circleci/config.yml
  .github/workflows/unit-tests.yml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/circle-310-arm64.yaml
  pandas/core/window/rolling.py
Labels: CI

#53559 Update 02_read_write.rst
  doc/source/getting_started/intro_tutorials/02_read_write.rst
Labels: Docs

#53561 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs

#53548 CI/DEPS: Add xfail(strict=False) to related unstable sorting changes in Numpy 1.25
  pandas/core/sorting.py
  pandas/tests/frame/methods/test_nlargest.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/groupby/test_value_counts.py
Labels: Compat

#53566 Backport PR #53548: CI/DEPS: Add xfail(strict=False) to related unstable sorting changes in Numpy 1.25
  pandas/tests/frame/methods/test_nlargest.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/groupby/test_value_counts.py
Labels: Compat

#53564 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs

#53142 CLN: Cleanup after CoW setitem PRs
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
Labels: Copy / view semantics, Stale

#53573 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs

#53567 TST: Use more pytest fixtures
  pandas/tests/arrays/sparse/test_indexing.py
  pandas/tests/arrays/sparse/test_libsparse.py
  pandas/tests/indexing/multiindex/test_indexing_slow.py
  pandas/tests/io/conftest.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/parser/test_compression.py
  pandas/tests/io/parser/test_network.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_stata.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Testing

#53550 TST: Use fixtures instead of TestPlotBase
  pandas/tests/plotting/common.py
  pandas/tests/plotting/conftest.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/frame/test_frame_groupby.py
  pandas/tests/plotting/frame/test_frame_legend.py
  pandas/tests/plotting/frame/test_frame_subplots.py
  pandas/tests/plotting/frame/test_hist_box_by.py
  pandas/tests/plotting/test_backend.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_common.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_groupby.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
Labels: Testing, Visualization

#53530 DOC: create a table for period aliases
  doc/source/user_guide/timeseries.rst
  pandas/core/arrays/datetimes.py
Labels: Docs, Period

#53575 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/plotting/_core.py
Labels: Docs

#53520 DEPR `fill_method` and `limit` keywords in `pct_change`
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/frame/methods/test_pct_change.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/series/methods/test_pct_change.py
Labels: Missing-data, Deprecate, Transformations

#53563 TST: Use monkeypatch instead of custom func for env variables
  pandas/_testing/__init__.py
  pandas/_testing/contexts.py
  pandas/tests/io/conftest.py
  pandas/tests/io/test_s3.py
Labels: Testing

#53578 CI: Ensure nightly wheels are uploaded instead of just sdist
  ci/upload_wheels.sh
Labels: Build, CI

#53598 Corrected minor typos in the paragraph below 'Formatting the Display'
  doc/source/user_guide/style.ipynb
Labels: Docs

#53593 CI: Fix the deprecation bot
  .github/workflows/deprecation-tracking-bot.yml
Labels: CI

#53611 DOC: pd.Period and pd.period_range should document that they accept datetime, date and pd.Timestamp
  pandas/_libs/tslibs/period.pyx
  pandas/core/indexes/period.py
Labels: Docs, Period

#53605 DOC: Fixed inconsistencies in pandas.DataFrame.pivot_table docstring parameter descriptions
  pandas/core/frame.py
Labels: Docs, Reshaping

#53594 ENH: Implement PandasArray, DTA, TDA interpolate
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/numpy_.py
  pandas/core/internals/blocks.py
Labels: Missing-data

#53585 PERF: Series.str.split(expand=True) for pyarrow-backed strings
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/strings/accessor.py
Labels: Performance, Strings, Arrow

#53572 DOC: Multi-conditional examples added to .loc docstring
  pandas/core/indexing.py
Labels: Docs

#53493 DEPR: pd.value_counts
  doc/source/user_guide/basics.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/algorithms.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/string_.py
  pandas/core/base.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/test_algos.py
Labels: Deprecate

#53579 ENH: Groupby.transform support string input with engine=numba
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/transform/test_numba.py
Labels: Groupby, numba

#53607 DEPR: NDFrame.interpolate with ffill/bfill methods
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Missing-data

#53620 BUG: clean_fill_method failing to raise
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/core/resample.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Missing-data

#51799 PDEP-9: Allow third-party projects to register pandas connectors with a standard API
  web/pandas/pdeps/0009-io-extensions.md
Labels: PDEP

#53591 TST: Add test for apply cast types GH#9506
  pandas/tests/apply/test_series_apply.py
Labels: Testing

#53637 BUG: DataFrame.stack with sort=True and unsorted MultiIndex levels
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping

#53646 ENH: Series.str.join for ArrowDtype(pa.string())
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#53638 DEPR: interpolate with object dtype
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Missing-data, API Design, Deprecate

#53635 BUG: interpolate with complex dtype
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Missing-data

#53628 DOC: Added links to GitHub tutorials/resources for Forking Workflow in contributing.rst
  doc/source/development/contributing.rst
Labels: Docs

#53610 TST: Refactor slow test
  pandas/tests/test_algos.py
Labels: Testing

#53650 Backport PR #53495 on branch 2.0.x (BUG: RangeIndex.union(sort=True) with another RangeIndex)
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/range.py
  pandas/tests/indexes/test_setops.py
Labels: Index, setops

#53602 ENH: Series.explode to support pyarrow-backed list types
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/series.py
  pandas/tests/series/methods/test_explode.py
Labels: Reshaping, Arrow

#53657 CI: Build pandas even if doctests fail
  .github/workflows/code-checks.yml
Labels: CI

#53623 BUG: groupby sum turning `inf+inf` and `(-inf)+(-inf)` into `nan`
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/test_libgroupby.py
Labels: Bug, Groupby, Reduction Operations

#53492 DEPR: method, limit in NDFrame.replace
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/conftest.py
  pandas/core/generic.py
  pandas/core/shared_docs.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/series/methods/test_replace.py
Labels: Deprecate, replace

#53655 PERF: Series.str.get_dummies for ArrowDtype(pa.string())
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/arrow/array.py
Labels: Performance, Strings, Arrow

#53625 TYP: core.missing
  pandas/core/arrays/sparse/array.py
  pandas/core/missing.py
Labels: Missing-data, Typing

#53670 CI: Attempt to fix wheel builds
  .github/workflows/wheels.yml
Labels: Build, CI

#53647 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/datetimes.py
  pandas/core/groupby/generic.py
Labels: Docs

#53677 CI/TST: Mark test_to_read_gcs as single_cpu
  pandas/tests/io/test_gcs.py
Labels: CI, Unreliable Test

#53672 BUG/CoW: is_range_indexer can't handle very large arrays
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/libs/test_lib.py
Labels: Indexing, Copy / view semantics

#53444 ENH: Allow numba aggregations to return non-float64 results
  asv_bench/benchmarks/groupby.py
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/_numba/executor.py
  pandas/core/_numba/kernels/mean_.py
  pandas/core/_numba/kernels/min_max_.py
  pandas/core/_numba/kernels/sum_.py
  pandas/core/_numba/kernels/var_.py
  pandas/core/groupby/groupby.py
  pandas/core/window/rolling.py
  pandas/io/formats/info.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_numba.py
Labels: Groupby, Dtype Conversions, Window, numba

#53691 Backport PR #53672 on branch 2.0.x (BUG/CoW: is_range_indexer can't handle very large arrays)
  doc/source/whatsnew/v2.0.3.rst
  pandas/_libs/lib.pyx
  pandas/tests/libs/test_lib.py
Labels: Indexing, Copy / view semantics

#53690 DOC: Move Whatsnew for CoW fix
  doc/source/whatsnew/v2.0.3.rst
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#53693 CI: Pin pandas-gbq above 0.15 to get rid of warnings on 2.0.x
  ci/deps/circle-310-arm64.yaml
Labels: CI, Dependencies

#53715 CI: Adjust tests for release of numpy 1.25
  pandas/compat/numpy/__init__.py
  pandas/tests/apply/test_frame_apply_relabeling.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/methods/test_compare.py
  pandas/tests/frame/test_unary.py
  pandas/tests/series/methods/test_describe.py
  pandas/tests/series/methods/test_equals.py
Labels: CI

#53571 DEPR: deprecate obj argument in GroupBy.get_group
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Deprecate

#53716 Backport PR #53715: CI: Adjust tests for release of numpy 1.25
  pandas/compat/numpy/__init__.py
  pandas/tests/apply/test_frame_apply_relabeling.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/frame/methods/test_compare.py
  pandas/tests/frame/test_unary.py
  pandas/tests/series/methods/test_describe.py
  pandas/tests/series/methods/test_equals.py
Labels: CI

#53475 Use _values_for_factorize by default for hashing ExtensionArrays
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/arrays/base.py
  pandas/tests/extension/json/test_json.py
Labels: ExtensionArray

#53726 CI: ignore experimental warnings from numba
  doc/source/user_guide/window.rst
Labels: Docs, CI

#53727 CI: fix `pytest scripts`
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  ci/meta.yaml
  environment.yml
  pandas/compat/_optional.py
  pyproject.toml
  requirements-dev.txt
  scripts/tests/conftest.py
  scripts/tests/data/deps_expected_random.yaml
  scripts/tests/data/deps_minimum.toml
  scripts/tests/data/deps_unmodified_random.yaml
Labels: Testing

#53703 BUG: IntervalIndex.get_indexer raising for read only array
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/intervaltree.pxi.in
  pandas/tests/indexes/interval/test_indexing.py
Labels: Interval

#52947 CoW: Add lazy copy mechanism to DataFrame constructor for dict of Index
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/indexes/base.py
  pandas/core/internals/construction.py
  pandas/tests/copy_view/index/test_index.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/indexes/test_common.py
Labels: Copy / view semantics, Stale

#53730 CI: fix numba typing
  pandas/core/_numba/kernels/mean_.py
  pandas/core/_numba/kernels/var_.py
Labels: CI, Typing

#53557 DEPR: deprecate unit parameters ’T’, 't', 'L', and 'l'
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/core/tools/timedeltas.py
  pandas/tests/indexes/timedeltas/test_timedelta_range.py
  pandas/tests/resample/test_timedelta.py
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Deprecate

#53732 Backport PR #53727 on branch 2.0.x (CI: fix pytest scripts)
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-38-minimum_versions.yaml
  ci/deps/actions-38.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-38.yaml
  ci/deps/circle-310-arm64.yaml
  ci/meta.yaml
  ci/test_wheels_windows.bat
  environment.yml
  pandas/compat/_optional.py
  pyproject.toml
  requirements-dev.txt
  scripts/tests/conftest.py
Labels: Testing

#53704 CoW: Return read-only array in Index.values
  doc/source/whatsnew/v2.1.0.rst
  pandas/conftest.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/tests/copy_view/index/test_datetimeindex.py
  pandas/tests/copy_view/index/test_index.py
  pandas/tests/copy_view/test_setitem.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/io/test_parquet.py
Labels: Index, Copy / view semantics

#53679 TST: Use more pytest fixtures
  pandas/tests/interchange/conftest.py
  pandas/tests/interchange/test_impl.py
  pandas/tests/interchange/test_spec_conformance.py
  pandas/tests/io/excel/test_xlrd.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/parser/usecols/test_parse_dates.py
  pandas/tests/io/parser/usecols/test_strings.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_sql.py
  pandas/tests/reductions/test_reductions.py
Labels: Testing

#53702 BUG: concat coercing arrow to object with null type
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/extension/test_arrow.py
Labels: Reshaping, Arrow

#53683 TST: Add test for duplcated columns and usecols GH#11823
  pandas/tests/io/parser/test_mangle_dupes.py
Labels: Testing

#53682 BUG: series with complex nan
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/series/test_constructors.py
Labels: Complex, Constructors

#53678 BUG: astype('category') on dataframe backed by non-writeable arrays raises ValueError
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/tests/extension/test_categorical.py
Labels: Bug, Dtype Conversions, Categorical

#53661 TST: xfail `test_rolling_var_numerical_issues` on Mac
  pandas/tests/window/test_rolling.py
Labels: Build, Window, ARM

#53421 BUG: Adds missing raises for numpy.timedelta64[M/Y] in pandas.Timedelta
  doc/source/user_guide/timedeltas.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/libs/test_lib.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/tslibs/test_timedeltas.py
Labels: Error Reporting, Non-Nano

#53409 DEPR: Deprecate literal json string input to read_json
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.5.0.rst
  doc/source/whatsnew/v2.1.0.rst
  pandas/io/json/_json.py
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_deprecated_kwargs.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_json_table_schema_ext_dtype.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_readlines.py
Labels: IO JSON, Deprecate

#53264 DOC: Add to_sql example of conflict with `method` parameter
  pandas/core/generic.py
  pandas/tests/io/test_sql.py
Labels: Docs, IO SQL

#53505 BUG: reindex with expansion and non-nanosecond dtype
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/dtypes/cast.py
  pandas/tests/series/methods/test_reindex.py
Labels: Missing-data, Non-Nano

#53651 BUG: convert_dtype(dtype_backend=nullable_numpy) with ArrowDtype
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_convert_dtypes.py
Labels: Dtype Conversions, Arrow

#53748 Backport PR #53505 on branch 2.0.x (BUG: reindex with expansion and non-nanosecond dtype)
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/dtypes/cast.py
  pandas/tests/series/methods/test_reindex.py
Labels: Missing-data, Non-Nano

#53652 BUG: Indexing a timestamp ArrowDtype Index
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/indexes/base.py
  pandas/tests/indexing/test_datetime.py
Labels: Indexing, Arrow

#53752 TYP: reshape.merge
  pandas/core/groupby/generic.py
  pandas/core/reshape/merge.py
Labels: Reshaping, Typing

#53750 TST: Use more pytest fixtures
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/reshape/concat/test_append_common.py
  pandas/tests/series/methods/test_argsort.py
  pandas/tests/series/methods/test_convert_dtypes.py
  pandas/tests/series/test_ufunc.py
  pandas/tests/test_take.py
  pandas/tests/tseries/offsets/test_custom_business_month.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/util/test_validate_args.py
  pandas/tests/util/test_validate_args_and_kwargs.py
  pandas/tests/util/test_validate_kwargs.py
Labels: Testing

#53654 BUG: DataFrame construction with dictionary ArrowDtype columns
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/indexes/base.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/numeric/test_indexing.py
Labels: Constructors, Arrow

#53751 DOC: point out that only period aliases are valid for the method asfreq in period.pyx
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Frequency, Period

#53741 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#53765 DOC: operator wrapper names do not match math operators
  pandas/core/ops/docstrings.py
Labels: Docs

#53725 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/scalar/timestamp/test_timestamp.py
Labels: Docs

#53710 DEPR: Deprecate DataFrame.last and Series.last
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_first_and_last.py
  pandas/tests/generic/test_finalize.py
Labels: Deprecate

#53747 BUG / CoW: Series.transform not respecting CoW
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#53760 Revert "BUG: DataFrame.stack with sort=True and unsorted MultiIndex levels"
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping

#53755 Backport PR #53652: BUG: Indexing a timestamp ArrowDtype Index
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/indexes/base.py
  pandas/tests/indexing/test_datetime.py
Labels: Indexing, Arrow

#53749 Backport PR #53651 on branch 2.0.x (BUG: convert_dtype(dtype_backend=nullable_numpy) with ArrowDtype)
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_convert_dtypes.py
Labels: Dtype Conversions, Arrow

#53766 TST: refactor data path for xml tests
  pandas/conftest.py
  pandas/io/xml.py
  pandas/tests/io/xml/conftest.py
  pandas/tests/io/xml/test_xml.py
Labels: Testing, Clean

#53660 TST: Reduce memory pressure of plotting tests
  pandas/tests/plotting/conftest.py
Labels: Testing, Visualization

#53768 DOC note pytest bump
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.1.0.rst
Labels: Docs

#53774 COMPAT: Remove np.compat
  pandas/tests/libs/test_hashtable.py
Labels: Compat

#53775 Added suggested new line to fix doc code example
  pandas/core/frame.py
Labels: Docs

#53758 Backport PR #53654: BUG: DataFrame construction with dictionary ArrowDtype columns
  doc/source/whatsnew/v2.0.3.rst
  pandas/core/indexes/base.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/numeric/test_indexing.py
Labels: Arrow

#53776 Backport PR #53774 on branch 2.0.x (COMPAT: Remove np.compat)
  pandas/tests/libs/test_hashtable.py
Labels: Compat

#53754 TST: Make test_complibs deterministic
  pandas/tests/io/pytables/test_file_handling.py
Labels: CI, Unreliable Test

#53784 TST: Refactor some slow tests
  pandas/tests/frame/methods/test_duplicated.py
  pandas/tests/groupby/test_nunique.py
  pandas/tests/io/formats/test_info.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_hist_method.py
Labels: Testing

#53780 TYP: reshape.merge
  pandas/core/reshape/merge.py
Labels: Reshaping, Typing

#53790 TST/CLN: use fixture for data path in all xml tests
  pandas/tests/io/xml/conftest.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/io/xml/test_xml_dtypes.py
Labels: Testing, Clean

#53789 REF: remove unused merge args
  pandas/core/reshape/merge.py
Labels: Reshaping, Clean

#53792 BUG: combine_first ignoring others columns if other is empty
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_combine_first.py
Labels: Bug, Reshaping

#53772 PERF: concat in no-reindexing case
  pandas/core/internals/concat.py
Labels: Performance, Reshaping

#53764 BUG: bad display for complex series with nan
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_printing.py
Labels: Output-Formatting, Complex

#53742 CLN: assorted
  pandas/_libs/groupby.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/sparse/array.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/missing.py
  pandas/core/strings/accessor.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/resample/test_base.py
  pandas/tests/series/indexing/test_take.py
  pandas/tests/series/methods/test_reindex.py
  pandas/tests/test_algos.py
Labels: Clean

#53796 DOC: Fixing EX01 - Added examples
  ci/code_checks.sh
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/categorical.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/dtypes.py
Labels: Docs

#53814 Update governance.md
  web/pandas/about/governance.md
Labels: Web

#53681 BUG: inconsistent behavior of DateOffset #47953
  doc/source/whatsnew/v2.1.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Frequency

#53815 CLN: PDEP6 precusor
  pandas/tests/copy_view/test_interp_fillna.py
Labels: Clean

#53735 DOC: Add code-formatting and cross-reference links to `read_csv` docstring
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#53800 TST: Refactor more slow tests
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/base_class/test_indexing.py
  pandas/tests/indexing/multiindex/test_indexing_slow.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
Labels: Testing
