Repository pandas-dev/pandas, pull requests merged in 2023-12, with the labels that each got.

#55856 DEPR: unit keyword in TimedeltaIndex
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/timedeltas.py
  pandas/core/tools/timedeltas.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/indexes/test_datetimelike.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/resample/test_timedelta.py
  pandas/tests/scalar/timedelta/test_constructors.py
Labels: Timedelta, Deprecate

#56276 Remove NpyDateTimeToEpoch
  pandas/_libs/include/pandas/datetime/date_conversions.h
  pandas/_libs/include/pandas/datetime/pd_datetime.h
  pandas/_libs/src/datetime/date_conversions.c
  pandas/_libs/src/datetime/pd_datetime.c
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
Labels: Internals

#56275 Remove inline_helper.h header file
  pandas/_libs/include/pandas/inline_helper.h
  pandas/_libs/include/pandas/parser/tokenizer.h
  pandas/_libs/include/pandas/skiplist.h
  pandas/_libs/include/pandas/vendored/klib/khash.h
  pandas/_libs/include/pandas/vendored/klib/khash_python.h
  pandas/_libs/src/parser/tokenizer.c
Labels: Internals

#56274 Clean up tokenizer / parser files
  pandas/_libs/include/pandas/parser/io.h
  pandas/_libs/include/pandas/parser/pd_parser.h
  pandas/_libs/include/pandas/parser/tokenizer.h
  pandas/_libs/parsers.pyx
  pandas/_libs/src/parser/io.c
  pandas/_libs/src/parser/pd_parser.c
  pandas/_libs/src/parser/tokenizer.c
Labels: Internals

#56264 TST/CLN: Remove makeTime methods
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/tests/frame/conftest.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_first_and_last.py
  pandas/tests/frame/methods/test_truncate.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/generic/test_generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexing/test_partial.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_errors.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_select.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_sql.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/series/methods/test_unstack.py
  pandas/tests/series/test_constructors.py
  pandas/tests/util/test_hashing.py
Labels: Testing, Clean

#55058 Convert to compatible NumPy dtype for MaskedArray to_numpy
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/parsers.pyx
  pandas/core/arrays/masked.py
  pandas/core/methods/to_dict.py
  pandas/io/formats/format.py
  pandas/io/parsers/base_parser.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/arrays/floating/test_to_numpy.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/base/test_conversion.py
  pandas/tests/copy_view/test_array.py
  pandas/tests/extension/test_masked.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/test_repr.py
Labels: NA - MaskedArrays

#56162 DOC: Add note about CoW change to copy keyword docs
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs, Copy / view semantics

#56293 CLN/TST: Remove makeTimeSeries
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/methods/test_describe.py
  pandas/tests/io/formats/test_to_string.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_keys.py
  pandas/tests/io/pytables/test_put.py
  pandas/tests/io/pytables/test_round_trip.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_pickle.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_series.py
  pandas/tests/series/methods/test_cov_corr.py
  pandas/tests/series/methods/test_diff.py
  pandas/tests/series/methods/test_map.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_formats.py
  pandas/tests/window/test_pairwise.py
Labels: Testing, Clean

#56168 CoW: Warn for cases that go through putmask
  pandas/core/generic.py
  pandas/core/internals/base.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
  pandas/tests/copy_view/test_clip.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/copy_view/test_replace.py
  pandas/tests/frame/methods/test_replace.py
Labels: Copy / view semantics

#56170 CoW: Fix warnings for eval
  pandas/core/computation/eval.py
  pandas/core/generic.py
  pandas/tests/computation/test_eval.py
Labels: expressions, Copy / view semantics

#56243 ENH: Raise TypeError when converting DatetimeIndex to PeriodIndex with invalid period frequency
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/period.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
Labels: Frequency

#56214 CoW: Add warning for slicing a Series with a MultiIndex
  pandas/core/series.py
  pandas/tests/copy_view/test_indexing.py
Labels: Copy / view semantics

#56237 DEPR: Default of observed=False in DataFrame.pivot_table
  doc/source/user_guide/categorical.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping, Categorical, Deprecate

#56307 DOC: Tidy docstring
  pandas/core/base.py
Labels: Docs

#56295 Assort IWYU Cleanups
  pandas/_libs/include/pandas/parser/tokenizer.h
  pandas/_libs/include/pandas/vendored/ujson/python/version.h
  pandas/_libs/src/parser/pd_parser.c
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/vendored/numpy/datetime/np_datetime.c
  pandas/_libs/src/vendored/numpy/datetime/np_datetime_strings.c
  pandas/_libs/src/vendored/ujson/lib/ultrajsondec.c
  pandas/_libs/src/vendored/ujson/lib/ultrajsonenc.c
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/_libs/src/vendored/ujson/python/ujson.c
Labels: Clean

#56284 Allow c files in src/include for gitignore
  .gitignore
Labels: Code Style

#56261 TST: dt64 units
  pandas/core/dtypes/missing.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/indexes/interval/test_formats.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
Labels: Testing, Non-Nano

#56325 BUG: avoid DeprecationWarning when the Series has index as list of Series (#55395)
  doc/source/whatsnew/v2.1.4.rst
  pandas/_libs/lib.pyx
  pandas/tests/series/test_constructors.py
Labels: Warnings

#56308 REGR: Fix reading old pickles from pandas 1.3.5
  doc/source/whatsnew/v2.1.4.rst
  pandas/compat/pickle_compat.py
  pandas/tests/io/data/legacy_pickle/1.3.5/1.3.5_x86_64_darwin_3.10.13.pickle
  pandas/tests/io/generate_legacy_storage_files.py
Labels: IO Pickle

#56328 Address violation fix
  pandas/core/methods/selectn.py
Labels: Bug

#56300 DOC: Adjust whatsnew
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs

#56250 BUG: Read CSV on python engine fails when skiprows and chunk size are specified (#55677, #56323)
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_skiprows.py
Labels: IO CSV

#56335 Backport PR #56308 on branch 2.1.x (REGR: Fix reading old pickles from pandas 1.3.5)
  doc/source/whatsnew/v2.1.4.rst
  pandas/compat/pickle_compat.py
  pandas/tests/io/data/legacy_pickle/1.3.5/1.3.5_x86_64_darwin_3.10.13.pickle
  pandas/tests/io/generate_legacy_storage_files.py
Labels: IO Pickle

#56288 CoW: Add warning for fillna
  pandas/core/internals/base.py
  pandas/core/internals/blocks.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Warnings, Copy / view semantics

#56338 TST: Remove groupby/test_function.py
  pandas/tests/groupby/methods/test_nth.py
  pandas/tests/groupby/test_all_methods.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_numeric_only.py
  pandas/tests/groupby/test_reductions.py
Labels: Testing, Groupby, Clean

#56331 TST/ CLN: Remove makeCustomIndex/DataFrame
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.12.0.rst
  pandas/_testing/__init__.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/methods/test_select_dtypes.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/indexes/datetimes/test_join.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/period/test_join.py
  pandas/tests/indexes/timedeltas/test_join.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_html.py
  pandas/tests/reshape/concat/test_invalid.py
Labels: Testing, Clean

#56127 ENH: non-nano datetime64s for read_sas
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/conversion.pyi
  pandas/_libs/tslibs/conversion.pyx
  pandas/io/sas/sas7bdat.py
  pandas/tests/io/sas/test_sas7bdat.py
Labels: IO SAS, Non-Nano

#56332 BUG: str.split for ArrowDtype with pat=None
  doc/source/whatsnew/v2.1.4.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#56334 ENH: Implement str.extract for ArrowDtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#56294 BUG: Series(strings, dtype=ArrowDtype[timestamp]) raising
  doc/source/whatsnew/v2.1.4.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Dtype Conversions, Arrow

#56348 Backport PR #56332: BUG: str.split for ArrowDtype with pat=None
  doc/source/whatsnew/v2.1.4.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#56349 Backport PR #56294: BUG: Series(strings, dtype=ArrowDtype[timestamp]) raising
  doc/source/whatsnew/v2.1.4.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#56277 Add Werror to CI
  .circleci/setup_env.sh
  .github/actions/build_pandas/action.yml
  .github/workflows/unit-tests.yml
  pandas/_libs/include/pandas/datetime/date_conversions.h
  pandas/_libs/include/pandas/datetime/pd_datetime.h
  pandas/_libs/src/datetime/date_conversions.c
  pandas/_libs/src/datetime/pd_datetime.c
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/tests/io/json/test_pandas.py
Labels: CI

#56350 BUG: astype(errors=ignore) for EAs
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/extension/test_arrow.py
Labels: Dtype Conversions, ExtensionArray

#56344 TST/CLN: Remove seldomly use items in _testing/__init__.py
  pandas/_testing/__init__.py
  pandas/tests/arrays/categorical/test_subclass.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/io/json/test_normalize.py
  pandas/tests/series/test_ufunc.py
Labels: Testing

#56352 BUG read_csv(quotechar=, engine='pyarrow')
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/test_quoting.py
Labels: IO CSV, Arrow

#56355 remove unused code from JSONtoObj
  pandas/_libs/src/vendored/ujson/python/JSONtoObj.c
  pandas/tests/io/json/test_ujson.py
Labels: IO JSON, Clean

#56368 BUG: Series.__mul__ for pyarrow strings
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_arrow.py
Labels: Numeric Operations, Strings, Arrow

#56372 CLN/TYP: "how" parameter in merge ops
  pandas/core/reshape/merge.py
Labels: Clean, Typing

#56281 BUG: Fix `Timestamp('now')` and `Timestamp.now` unit inconsistency
  doc/source/whatsnew/v2.1.4.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
Labels: Non-Nano

#56374 TYP: require_matching_freq
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
Labels: Frequency, Typing

#56123 BUG: ne comparison returns False for NA and other value
  doc/source/whatsnew/v2.1.4.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arrays/string_/test_string.py
Labels: Strings, Arrow

#56381 CoW: Warn for transform inplace modification
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/copy_view/test_methods.py
Labels: Copy / view semantics

#56393 DOC: Add release date for 2.1.4
  doc/source/whatsnew/v2.1.4.rst
Labels: Docs

#56395 Backport PR #56393 on branch 2.1.x (DOC: Add release date for 2.1.4)
  doc/source/whatsnew/v2.1.4.rst
Labels: Docs

#56391 CoW: Avoid warning in case of expansion
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Copy / view semantics

#56400 TST: clean CoW chained assignment warning iloc test case
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
Labels: Copy / view semantics

#56407 DOC: Fix typo in resample.py, "as_freq"
  pandas/core/resample.py
Labels: Docs

#56416 CLN: generate_range
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
Labels: Clean, Typing

#56157 BUG: Index.str.cat casting result always to object
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_api.py
  pandas/tests/strings/test_cat.py
Labels: Dtype Conversions, Strings

#56191 Adjust tests in extension folder for new string option
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_numpy.py
Labels: Testing, Strings, Arrow

#55257 DEPR: Index.insert dtype-inference
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexing.py
  pandas/core/internals/managers.py
  pandas/tests/indexes/test_old_base.py
Labels: Deprecate

#56420 CLN: Remove unnecessary copy keyword
  pandas/_testing/asserters.py
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/internals/managers.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/internals/test_internals.py
Labels: Clean

#56371 BUG: resample with ArrowDtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/groupby/grouper.py
  pandas/core/resample.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_timedelta.py
Labels: Resample, Arrow

#56106 BUG: reindex not matching categoricals and new string dtypes
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexing/test_categorical.py
Labels: Strings, Categorical, Arrow

#56327 Compiled pandas with -Wextra
  meson.build
  pandas/_libs/include/pandas/datetime/pd_datetime.h
  pandas/_libs/include/pandas/portable.h
  pandas/_libs/include/pandas/vendored/numpy/datetime/np_datetime_strings.h
  pandas/_libs/src/datetime/pd_datetime.c
  pandas/_libs/src/parser/pd_parser.c
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/vendored/numpy/datetime/np_datetime.c
  pandas/_libs/src/vendored/numpy/datetime/np_datetime_strings.c
  pandas/_libs/src/vendored/ujson/lib/ultrajsonenc.c
  pandas/_libs/src/vendored/ujson/python/JSONtoObj.c
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/_libs/src/vendored/ujson/python/ujson.c
Labels: Build

#56408 STY: Fix doctest and docstring formatting errors
  ci/code_checks.sh
  doc/make.py
  pandas/core/arrays/sparse/accessor.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/shared_docs.py
  pandas/core/window/rolling.py
  pandas/io/sql.py
  pandas/plotting/_core.py
  pandas/plotting/_misc.py
  scripts/validate_docstrings.py
Labels: Code Style

#56384 TST: Added a test for groupby.prod
  pandas/tests/groupby/test_reductions.py
Labels: Bug, Groupby, Needs Tests, Reduction Operations

#56385 DEPR: Series[categorical].replace special-casing
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_replace.py
  pandas/tests/copy_view/test_replace.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/series/methods/test_replace.py
Labels: Categorical, Deprecate, replace

#56424 TST: misplaced tests
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/test_feather.py
  pandas/tests/tslibs/test_parsing.py
Labels: Testing

#56423 TYP: EA.isin
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/string_arrow.py
Labels: ExtensionArray, Typing

#56427 DEPR: casting in datetimelike isin
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/lib.pyx
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/base.py
  pandas/tests/test_algos.py
Labels: Deprecate

#56373 PERF: datetimelike addition
  asv_bench/benchmarks/arithmetic.py
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/core/algorithms.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/tests/test_algos.py
  pandas/tests/tslibs/test_api.py
Labels: Performance, Numeric Operations

#56413 BUG: fillna with mixed-resolution dt64/td64
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/datetimelike.py
  pandas/tests/series/methods/test_fillna.py
Labels: Missing-data, Non-Nano

#56421 DEPR: type argument in Index.view
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/numeric/test_numeric.py
  pandas/tests/indexes/ranges/test_range.py
  pandas/tests/indexes/test_datetimelike.py
  pandas/tests/indexes/test_old_base.py
Labels: Deprecate, Index

#56426 BUG: outer join on equal indexes not sorting
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/computation/align.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/reshape/merge.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/test_arithmetic.py
Labels: Bug, Reshaping

#56365 BUG: `concat` should keep series names unless `ignore_index=True`
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Reshaping

#55409 Fix new string dtype tests for frame folder
  pandas/tests/frame/constructors/test_from_dict.py
  pandas/tests/frame/constructors/test_from_records.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_set_value.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/frame/methods/test_drop_duplicates.py
  pandas/tests/frame/methods/test_dtypes.py
  pandas/tests/frame/methods/test_duplicated.py
  pandas/tests/frame/methods/test_equals.py
  pandas/tests/frame/methods/test_explode.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_get_numeric_data.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_is_homogeneous_dtype.py
  pandas/tests/frame/methods/test_nlargest.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_select_dtypes.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/frame/methods/test_update.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_logical_ops.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/frame/test_repr.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/frame/test_unary.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_numeric_only.py
  pandas/tests/groupby/test_raises.py
Labels: Strings, Arrow

#56047 BUG: read_csv not respecting object dtype when option is set
  doc/source/whatsnew/v2.1.4.rst
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: IO CSV

#56074 Adjust Index specific tests for string option
  pandas/conftest.py
  pandas/tests/indexes/base_class/test_formats.py
  pandas/tests/indexes/base_class/test_reshape.py
  pandas/tests/indexes/base_class/test_setops.py
  pandas/tests/indexes/categorical/test_astype.py
  pandas/tests/indexes/categorical/test_category.py
  pandas/tests/indexes/categorical/test_formats.py
  pandas/tests/indexes/categorical/test_reindex.py
  pandas/tests/indexes/datetimes/methods/test_map.py
  pandas/tests/indexes/interval/test_formats.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/multi/test_get_set.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/object/test_astype.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/period/methods/test_astype.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexes/timedeltas/methods/test_astype.py
Labels: Strings, Index, Arrow

#56102 DEPR: Disallow dtype inference when setting Index into DataFrame
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Deprecate

#56428 CI: Fix mypy
  pandas/core/arrays/datetimelike.py
Labels: CI, Typing

#56188 Adjust tests in array folder for new string option
  pandas/core/algorithms.py
  pandas/tests/arrays/boolean/test_arithmetic.py
  pandas/tests/arrays/categorical/test_astype.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/categorical/test_repr.py
  pandas/tests/arrays/floating/test_arithmetic.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/integer/test_reduction.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/arrays/test_array.py
Labels: Testing, Strings, Arrow

#56291 ENH: Make get_dummies return ea booleans for ea inputs
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/encoding.py
  pandas/tests/reshape/test_get_dummies.py
Labels: ExtensionArray

#56440 WEB: Add timeout for ci
  web/pandas_web.py
Labels: CI, Web

#56418 CoW: Update test with read-only array
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
Labels: Testing, Copy / view semantics

#56453 DOC: Improve ``io/excel/_base.py``
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#56446 Adjust concat tests for string option
  pandas/tests/reshape/concat/test_append_common.py
  pandas/tests/reshape/concat/test_categorical.py
  pandas/tests/reshape/concat/test_empty.py
  pandas/tests/reshape/concat/test_index.py
Labels: Reshaping, Strings

#56444 BUG: merge_asof raising incorrect error for strings
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Reshaping, Strings

#56443 BUG: DataFrame.join with left or right empty not respecting sort=True
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/frame/methods/test_combine_first.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/series/test_logical_ops.py
Labels: Bug, Reshaping

#56439 REF: get_supported_reso->get_supported_dtype
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/np_datetime.pyi
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/timedeltas.py
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/ops/array_ops.py
  pandas/core/tools/datetimes.py
  pandas/tests/tslibs/test_api.py
Labels: Refactor

#56457 DOC: Improve ``quantile`` docstring
  pandas/core/series.py
Labels: Docs

#56458 DOC: Improve ``df.equals()`` docstring
  pandas/core/generic.py
Labels: Docs

#56369 Update nlargest nsmallest doc
  pandas/core/frame.py
Labels: Docs

#56436 REF: pass dtype to _from_sequence
  pandas/_libs/parsers.pyx
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/numeric.py
  pandas/core/arrays/period.py
  pandas/core/construction.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/internals/construction.py
  pandas/core/strings/object_array.py
  pandas/io/parsers/base_parser.py
  pandas/tests/arithmetic/test_period.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/datetimes/test_constructors.py
  pandas/tests/arrays/datetimes/test_cumulative.py
  pandas/tests/arrays/datetimes/test_reductions.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/arrays/timedeltas/test_cumulative.py
  pandas/tests/arrays/timedeltas/test_reductions.py
  pandas/tests/extension/array_with_attr/array.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/test_downstream.py
Labels: Refactor

#56464 DOC: replace deprecated freqs 'T', 'S', 'A' in docs and comments
  pandas/_libs/tslibs/period.pyx
  pandas/core/arrays/period.py
  pandas/tests/io/json/test_json_table_schema.py
Labels: Docs

#56469 DOC: fix a typo in Resampler.interpolate
  pandas/core/resample.py
Labels: Docs

#56465 DOC: Minor improvements groupby user guide
  doc/source/user_guide/groupby.rst
Labels: Docs, Groupby

#56417 ENH: unify warning message in to_offset()
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/methods/test_asfreq.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/resample/test_datetime_index.py
Labels: Frequency

#56207 WEB: Better management of releases
  .github/workflows/docbuild-and-upload.yml
  web/pandas_web.py
  web/tests/test_pandas_web.py
Labels: Web

#56431 CLN: assorted
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/dtypes.pyi
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/tools/datetimes.py
  pandas/io/sas/sas7bdat.py
  pandas/io/stata.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/numpy_/test_numpy.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/io/parser/common/test_data_list.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/test_stata.py
  pandas/tests/tools/test_to_datetime.py
Labels: Clean

#56489 DEPR: raise ValueError if invalid period freq pass to asfreq
  pandas/core/resample.py
  pandas/tests/resample/test_period_index.py
Labels: Deprecate

#56504 CI: Rename to .condarc
  .github/actions/setup-conda/action.yml
  ci/.condarc
Labels: CI

#56501 updated sphinx-lint version to 0.9.1
  .pre-commit-config.yaml
Labels: Code Style

#56494 TST: de-special-case test_EA_types
  pandas/tests/extension/base/io.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_sparse.py
Labels: Testing, ExtensionArray

#56298 DOC: Start migration guide for Copy-on-Write
  doc/source/user_guide/copy_on_write.rst
Labels: Docs, Copy / view semantics

#56490 BUG: time strings cast to ArrowDtype with pa.time64 type
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Dtype Conversions, Arrow

#56488 BUG: merge_asof(tolerance=Timedelta) with ArrowDtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
Labels: Timeseries, Reshaping, Arrow

#56459 BUG: Return numpy types from ArrowExtensionArray.to_numpy for temporal types when possible
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/sparse/accessor.py
  pandas/io/formats/format.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/io/formats/test_format.py
Labels: Timedelta, Arrow, Timestamp

#56510 TST: use one-class pattern in json extension tests
  pandas/tests/extension/json/test_json.py
Labels: Testing, ExtensionArray, Nested Data

#56506 CLN: pass dtype to from_sequence explicitly
  pandas/core/arrays/interval.py
  pandas/core/arrays/string_arrow.py
  pandas/core/reshape/merge.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/datetimes/test_cumulative.py
  pandas/tests/arrays/integer/test_construction.py
  pandas/tests/arrays/test_array.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/list/array.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/tools/test_to_timedelta.py
Labels: Clean

#56392 CoW: Avoid warnings in stata code
  pandas/io/stata.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_stata.py
Labels: Copy / view semantics

#56523 PERF: merge on monotonic keys
  asv_bench/benchmarks/join_merge.py
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/groupby/generic.py
  pandas/core/indexes/base.py
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
Labels: Performance, Reshaping

#56522 REGR: groupby with Decimal and NA values
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/algorithms.py
  pandas/tests/groupby/test_groupby.py
Labels: Bug, Groupby, Regression, Sorting

#56438 DEPS: Bump some code style check dependencies
  doc/source/conf.py
  environment.yml
  requirements-dev.txt
Labels: Dependencies

#56544 DOC: Remove 1.2 versionadded and changed
  pandas/_testing/asserters.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/string_arrow.py
  pandas/core/construction.py
  pandas/core/flags.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/core/window/rolling.py
  pandas/errors/__init__.py
  pandas/io/common.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/style.py
  pandas/io/json/_json.py
  pandas/io/parquet.py
  pandas/io/parsers/readers.py
  pandas/io/pickle.py
  pandas/io/sas/sasreader.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/plotting/_core.py
Labels: Docs

#56534 TST: Adjust excel tests for new string option
  pandas/conftest.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
Labels: IO Excel, Strings

#56508 PERF: Improve performance when hashing a nullable extension array
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/base.py
  pandas/core/arrays/masked.py
Labels: Performance, hashing, NA - MaskedArrays

#56540 REF: avoid special-casing in agg_series
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
Labels: Refactor

#56539 TYP: _json.py
  pandas/io/json/_json.py
Labels: IO JSON, Typing

#56535 Adjust format tests for new string option
  pandas/tests/io/formats/style/test_to_latex.py
  pandas/tests/io/formats/style/test_to_string.py
  pandas/tests/io/formats/test_format.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/formats/test_to_string.py
Labels: Strings

#56529 Adjust pivot tests for new string option
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_union_categoricals.py
Labels: Strings

#56527 Adjust dummies tests for new string option
  pandas/tests/reshape/test_from_dummies.py
  pandas/tests/reshape/test_get_dummies.py
Labels: Strings

#56525 CoW: Remove some no longer necessary todos
  pandas/core/internals/managers.py
Labels: Copy / view semantics

#56513 TST: use one-class pattern for SparseArray
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/test_sparse.py
Labels: Sparse

#56509 TST: use single-class pattern in test_string.py
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
Labels: Refactor, Testing

#56470 DOC: Add example with ``numpy_nullable`` to ``pd.read_xml()``
  pandas/io/xml.py
Labels: Docs, IO XML

#56441 BUG: merge not raising for String and numeric merges
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
Labels: Reshaping, Strings

#55968 DEPR: resample with PeriodIndex
  doc/source/whatsnew/v0.21.0.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
Labels: Period, Resample, Deprecate

#56487 BUG: Fix sort_index(axis=1, ignore_index=True)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_sort_index.py
Labels: Bug, DataFrame, Sorting

#56521 DEPR: groupby.grouper
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/resample.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/methods/test_groupby_shift_diff.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/test_sorting.py
Labels: Groupby, Deprecate

#56565 Revert "DOC: Change core paths to api.typing in URLs (#55626)"
  doc/source/reference/groupby.rst
  doc/source/reference/resampling.rst
  doc/source/reference/window.rst
Labels: Docs

#56531 ENH: Add limit_area to ffill/bfill
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/groupby/test_api.py
  pandas/tests/series/methods/test_fillna.py
Labels: Enhancement, Missing-data, DataFrame, Series

#56493 TYP: Update mypy and pyright
  .pre-commit-config.yaml
  doc/source/whatsnew/v2.2.0.rst
  environment.yml
  pandas/_config/config.py
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_testing/_hypothesis.py
  pandas/_typing.py
  pandas/conftest.py
  pandas/core/_numba/kernels/var_.py
  pandas/core/apply.py
  pandas/core/arrays/_ranges.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/internals/base.py
  pandas/core/methods/describe.py
  pandas/core/nanops.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/util.py
  pandas/io/excel/_calamine.py
  pandas/io/formats/format.py
  pandas/io/parquet.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/core.py
  pyproject.toml
  pyright_reportGeneralTypeIssues.json
  requirements-dev.txt
Labels: Code Style, Typing

#56561 DOC: Add example using ``dtype_backend="numpy_nullable"`` to ``read_json``
  pandas/io/json/_json.py
Labels: Docs, IO JSON

#56556 DEPR: verbose kwd in read_csv, read_table
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_verbose.py
  pandas/tests/io/parser/test_unsupported.py
Labels: IO CSV, Deprecate

#56568 TYP: simple return types from ruff
  .pre-commit-config.yaml
  doc/make.py
  doc/scripts/eval_performance.py
  doc/source/conf.py
  generate_pxi.py
  generate_version.py
  scripts/tests/conftest.py
  scripts/tests/test_no_bool_in_generic.py
  scripts/tests/test_sort_whatsnew_note.py
  scripts/tests/test_use_io_common_urlopen.py
  scripts/tests/test_use_pd_array_in_core.py
  scripts/tests/test_validate_docstrings.py
  scripts/tests/test_validate_exception_location.py
  scripts/tests/test_validate_min_versions_in_sync.py
  scripts/tests/test_validate_unwanted_patterns.py
  scripts/validate_docstrings.py
  scripts/validate_exception_location.py
  setup.py
  web/tests/test_pandas_web.py
Labels: Typing

#56552 TST: Remove arraymanager pytest mark
  pandas/conftest.py
  pyproject.toml
  scripts/tests/data/deps_minimum.toml
Labels: Testing, ArrayManager

#56571 CI: Fix pre-commit failure
  doc/source/whatsnew/v2.2.0.rst
Labels: CI, Code Style

#56558 DEPR: Tick.delta
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/tseries/offsets/test_ticks.py
Labels: Frequency, Deprecate

#56569 DEPR: keep_date_col, nested parse_dates in read_csv
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/usecols/test_parse_dates.py
Labels: IO CSV, Deprecate

#56538 Support multiplication of pd.ArrowDtype(pa.string()) and integral value where integral value is a series
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#56321 BUG: Fixed bug when creating new column with missing values when setting a single string value
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_set_value.py
Labels: Strings, Arrow

#56585 BUG: convert_dtypes raising when preserving object dtype
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_convert_dtypes.py
Labels: Dtype Conversions

#56584 CI: Disable linkecheck
  .github/workflows/broken-linkcheck.yml
Labels: CI

#56557 DEPR: delim_whitespace kwd in read_csv
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_comment.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
Labels: IO CSV, Deprecate

#56043 DEPR: DatetimeArray/TimedeltaArray.__init__
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/dtypes/dtypes.py
  pandas/core/indexes/datetimelike.py
  pandas/core/internals/managers.py
  pandas/core/ops/array_ops.py
  pandas/tests/arrays/datetimes/test_constructors.py
  pandas/tests/arrays/test_array.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/arrays/timedeltas/test_constructors.py
  pandas/tests/arrays/timedeltas/test_reductions.py
  pandas/tests/base/test_conversion.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/test_downstream.py
  pandas/tests/test_nanops.py
  pandas/tests/tools/test_to_datetime.py
Labels: Deprecate

#55102 enable ASAN/UBSAN in pandas CI
  .github/actions/build_pandas/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/unit-tests.yml
  ci/deps/actions-311-sanitizers.yaml
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_cumulative.py
  pandas/tests/io/parser/common/test_float.py
  pandas/tests/scalar/timedelta/methods/test_round.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/scalar/timestamp/methods/test_tz_localize.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
  pyproject.toml
  scripts/tests/data/deps_minimum.toml
Labels: Build

#56577 DOC: Fix doc redirects
  doc/redirects.csv
Labels: Docs

#56520 CoW: Set a bunch of Series copy statements to False
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/io/sas/sas7bdat.py
  pandas/io/stata.py
Labels: Copy / view semantics

#56582 BUG: stack changes NA values in the index
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping

#56580 support tuple in startswith/endswith for arrow strings
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#56570 Add test groupby complex numbers
  pandas/tests/groupby/test_groupby.py
Labels: Testing

#56567 BUG: ArrowExtensionArray.to_numpy from timestamp to int
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Dtype Conversions, Arrow

#56220 Switch arrow type for string array to large string
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/io/sql.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/xml/test_xml.py
Labels: Strings, Arrow

#56545 DOC: Add whatsnew illustrating upcoming changes
  doc/source/user_guide/copy_on_write.rst
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs

#56290 Convert ArrowExtensionArray to proper NumPy dtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/_utils.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/series/test_npfuncs.py
Labels: Arrow

#56244 DEPR: Deprecate dtype inference on pandas objects
  doc/source/whatsnew/v2.2.0.rst
  pandas/_testing/__init__.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/core/strings/accessor.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/base_class/test_constructors.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/methods/test_between.py
  pandas/tests/series/methods/test_equals.py
  pandas/tests/series/test_constructors.py
  pandas/tests/strings/test_cat.py
  pandas/tests/tseries/frequencies/test_inference.py
Labels: Deprecate

#56245 BUG: __eq__ raising for new arrow string dtype for incompatible objects
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/series/test_logical_ops.py
Labels: Numeric Operations, Strings

#56403 DOC: add deprecation of chained assignment to 2.2 whatsnew
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs, Copy / view semantics
