Repository pandas-dev/pandas, pull requests merged in 2023-09, with the labels that each got.

#54881 REGR: read_csv raising when dtypes is specified with usecols
  doc/source/whatsnew/v2.1.1.rst
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
Labels: Regression, IO CSV

#54832 ENH: allow EADtype to specify _supports_2d
  pandas/core/dtypes/base.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/tests/extension/base/__init__.py
  pandas/tests/extension/base/dim2.py
Labels: ExtensionArray

#53656 DEPR: downcasting in NDFrame.where, mask, clip
  doc/source/whatsnew/v2.2.0.rst
  pandas/conftest.py
  pandas/core/config_init.py
  pandas/core/internals/blocks.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_clip.py
  pandas/tests/series/indexing/test_where.py
  pandas/tests/series/methods/test_clip.py
Labels: Deprecate

#54925 Backport PR #54880 on branch 2.1.x (REGR: comparing datetime vs None raises)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/series/indexing/test_datetime.py
Labels: Regression

#54882 REGR: get_group raising with axis=1
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Regression

#54884 REGR: value_counts raises with bins
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Regression, Algos

#54895 REGR: Merge raising when left merging on arrow string index
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Reshaping, Regression

#54824 #50990 Increase to_dict('list') performance
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/methods/to_dict.py
  pandas/tests/frame/methods/test_to_dict.py
Labels: Performance

#54843 BUG: ArrowExtensionArray.to_numpy avoid object dtype when na_value provided
  pandas/core/arrays/arrow/array.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_arrow.py
Labels: Bug, Arrow

#54924 DOC: add missing periods in JSON section
  doc/source/user_guide/io.rst
Labels: Docs

#54919 REF: cast x and bins to Index early in cut, qcut
  pandas/core/reshape/tile.py
Labels: Refactor, cut

#54932 Backport PR #54884 on branch 2.1.x (REGR: value_counts raises with bins)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/algorithms.py
  pandas/tests/test_algos.py
Labels: Regression, Algos

#54933 Backport PR #54895 on branch 2.1.x (REGR: Merge raising when left merging on arrow string index)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Reshaping, Regression

#54935 DOC: fixes Sphinx parallel build error on `doc/source/whatsnew/v0.24.0.rst`
  doc/source/whatsnew/v0.24.0.rst
Labels: Docs

#54913 REGR: drop_duplicates raising for arrow strings
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_drop_duplicates.py
Labels: Regression, Algos

#54958 BLD: Fix race condition
  pandas/_libs/meson.build
Labels: Build

#54955 Backport PR #54913 on branch 2.1.x (REGR: drop_duplicates raising for arrow strings)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_drop_duplicates.py
Labels: Regression, Algos

#54956 Backport PR #54882 on branch 2.1.x (REGR: get_group raising with axis=1)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, Regression

#54954 REGR: read_csv splitting on comma with delim_whitespace
  doc/source/whatsnew/v2.1.1.rst
  pandas/_libs/src/parser/tokenizer.c
  pandas/tests/io/parser/test_header.py
Labels: Regression, IO CSV

#54945 REGR: MultiIndex.append raising for overlapping IntervalIndex levels
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/categorical.py
  pandas/tests/indexes/multi/test_reshape.py
Labels: Reshaping, Regression, MultiIndex, Interval

#54826 Infer large_string type as pyarrow_numpy strings
  pandas/core/arrays/string_arrow.py
  pandas/io/_util.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/io/test_parquet.py
Labels: Strings, Arrow

#54967 Backport PR #54954 on branch 2.1.x (REGR: read_csv splitting on comma with delim_whitespace)
  doc/source/whatsnew/v2.1.1.rst
  pandas/_libs/src/parser/tokenizer.c
  pandas/tests/io/parser/test_header.py
Labels: Regression, IO CSV

#54969 Backport PR #54826 on branch 2.1.x (Infer large_string type as pyarrow_numpy strings)
  pandas/core/arrays/string_arrow.py
  pandas/io/_util.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/io/test_parquet.py
Labels: Strings, Arrow

#54968 Backport PR #54945 on branch 2.1.x (REGR: MultiIndex.append raising for overlapping IntervalIndex levels)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/categorical.py
  pandas/tests/indexes/multi/test_reshape.py
Labels: Reshaping, Regression, MultiIndex, Interval

#54965 Backport PR #54958 on branch 2.1.x (BLD: Fix race condition)
  pandas/_libs/meson.build
Labels: Build

#54962 BUG: DataFrame.stack with future_stack=True failing when columns are tuples
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping

#54951 BUG: Categorical.isin raising for overlapping intervals
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/indexes/categorical/test_category.py
Labels: Bug, Categorical, Interval

#54971 Backport PR #54962 on branch 2.1.x (BUG: DataFrame.stack with future_stack=True failing when columns are tuples)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/reshape/reshape.py
  pandas/tests/frame/test_stack_unstack.py
Labels: Bug, Reshaping

#54928 new pandas cheat sheet fomats
  doc/cheatsheet/README.md
  doc/cheatsheet/README.txt
Labels: Docs

#54999 TYP: Add typing.overload signatures to DataFrame/Series.interpolate
  pandas/core/generic.py
Labels: Typing

#55000 BUG: ArrowDtype raising for fixed size list
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#54993 Backport PR #54985 on branch 2.1.x (REGR: rountripping datetime through sqlite doesn't work)
  doc/source/whatsnew/v2.1.1.rst
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Regression, IO SQL

#54988 DOC: expanded pandas.DataFrame.to_sql docstring
  pandas/core/generic.py
Labels: Docs

#54957 ENH: Use more arrow compute functions for string[pyarrow] dtype
  pandas/core/arrays/string_arrow.py
Labels: Strings, Arrow

#54927 REGR: interpolate raising if fill_value is given
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/generic.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Bug, Missing-data

#54914 REGR: concat raising for 2 different ea dtypes
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Reshaping, Regression

#55013 CI: Ignore hypothesis differing executors
  pandas/conftest.py
Labels: Testing, CI

#55019 Backport PR #55013 on branch 2.1.x (CI: Ignore hypothesis differing executors)
  pandas/conftest.py
Labels: Testing, CI

#54974 Include pyarrow_numpy string in efficient merge implementation
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Performance, Reshaping

#54982 REG: filter not respecting the order of labels
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_filter.py
Labels: Indexing, Regression

#55016 Backport PR #55000 on branch 2.1.x (BUG: ArrowDtype raising for fixed size list)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#55017 Backport PR #54927 on branch 2.1.x (REGR: interpolate raising if fill_value is given)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/generic.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Bug, Missing-data

#55018 Backport PR #54914 on branch 2.1.x (REGR: concat raising for 2 different ea dtypes)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Reshaping, Regression

#55021 Backport PR #54974 on branch 2.1.x (Include pyarrow_numpy string in efficient merge implementation)
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Performance, Reshaping

#55022 Backport PR #54982 on branch 2.1.x (REG: filter not respecting the order of labels)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_filter.py
Labels: Indexing, Regression

#54972 Enable Arrow implementation for removeprefix
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
Labels: Strings, Arrow

#54976 TYP: fix a few types
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/excel/_base.py
  pandas/io/formats/excel.py
  pandas/io/json/_json.py
  pandas/io/parsers/readers.py
Labels: Typing

#54966 TST: add test case of ngroup with NaN value
  pandas/tests/groupby/test_groupby.py
Labels: Testing

#54947 TST: Use (unused) window parameter of test_freq_window_not_implemented
  pandas/tests/window/test_rolling.py
Labels: Testing

#55034 DOC: Add missing word to `IndexOpsMixin.array` docstring
  pandas/core/base.py
Labels: Docs

#55033 TST: Use more explicit object names
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/indexes/ranges/test_range.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/io/formats/test_info.py
  pandas/tests/io/formats/test_series_info.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/test_cut.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_qcut.py
  pandas/tests/test_algos.py
Labels: Testing

#54983 BUG: pct_change showing unnecessary FutureWarning
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_pct_change.py
  pandas/tests/series/methods/test_pct_change.py
Labels: Warnings

#54960 ENH: Implement more string accessors through PyArrow
  pandas/core/arrays/string_arrow.py
Labels: Strings, Arrow

#55040 Backport PR #54983 on branch 2.1.x (BUG: pct_change showing unnecessary FutureWarning)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_pct_change.py
  pandas/tests/series/methods/test_pct_change.py
Labels: Warnings

#54950 DEPR: DataFrameGroupBy.apply operating on the group keys
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.14.0.rst
  doc/source/whatsnew/v0.18.1.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_function.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/test_value_counts.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/window/test_groupby.py
  scripts/validate_unwanted_patterns.py
Labels: Groupby, Deprecate, Apply

#55051 Fix pickle roundtrip for new arrow string dtype
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/string_/test_string_arrow.py
Labels: Strings, Arrow

#55050 Fix docstring of Index.join in base.py
  pandas/core/indexes/base.py
Labels: Docs

#55010 BLD: Build wheels for Python 3.12
  .circleci/config.yml
  .github/workflows/wheels.yml
  pyproject.toml
Labels: Build, Python 3.12

#54936 Convert test_sql to pytest idiom
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#55042 REGR: DataFrameGroupBy.agg with duplicate column names and a dict
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Groupby, Regression, Apply

#55053 Backport PR #55052 on branch 2.1.x (Improve error message for StringDtype with invalid storage)
  pandas/core/arrays/string_.py
  pandas/tests/arrays/string_/test_string_arrow.py
Labels: Strings, Arrow

#55054 Backport PR #55051 on branch 2.1.x (Fix pickle roundtrip for new arrow string dtype)
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/string_/test_string_arrow.py
Labels: Strings, Arrow

#55056 Backport PR #55042 on branch 2.1.x (REGR: DataFrameGroupBy.agg with duplicate column names and a dict)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Groupby, Regression, Apply

#55055 Backport PR #55010 on branch 2.1.x (BLD: Build wheels for Python 3.12)
  .circleci/config.yml
  .github/workflows/wheels.yml
  pyproject.toml
Labels: Build, Python 3.12

#54949 BLD: improvements to meson.build files
  generate_version.py
  meson.build
  pandas/_libs/meson.build
  pandas/_libs/tslibs/meson.build
  pandas/meson.build
Labels: Build

#55039 Add TODO note to BlockManager.fast_xs for EA dtypes
  pandas/core/internals/managers.py
Labels: ExtensionArray

#55065 Backport PR #54949 on branch 2.1.x (BLD: improvements to meson.build files)
  generate_version.py
  meson.build
  pandas/_libs/meson.build
  pandas/_libs/tslibs/meson.build
  pandas/meson.build
Labels: Build

#54937 ENH: use shutil.which() instead of external which(1)
  pandas/io/clipboard/__init__.py
Labels: IO Data

#55071 BUG: read_csv(on_bad_lines='warn') did not raise a Python warning
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/parsers.pyx
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_textreader.py
Labels: IO CSV, Warnings

#55048 COMPAT: bump pyarrow min version for div on duration
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#55073 Backport PR #55048 on branch 2.1.x (COMPAT: bump pyarrow min version for div on duration)
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#55084 PERF: concat(axis=1) with unaligned indexes
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/api.py
Labels: Performance, Reshaping

#55078 TYP: Misc type corrections
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timestamps.pyi
  pandas/_typing.py
  pandas/core/reshape/pivot.py
  pandas/io/parsers/readers.py
Labels: Typing

#55057 DOC: fix an example which raises an Error in whatsnew/v0.10.0.rst
  doc/source/whatsnew/v0.10.0.rst
Labels: Docs

#54666 ENH: numba engine in df.apply
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/_numba/executor.py
  pandas/core/apply.py
  pandas/core/frame.py
  pandas/tests/apply/test_frame_apply.py
Labels: Apply, numba

#55082 Updated future warning msg in transform() for Series.groupby
  pandas/core/apply.py
Labels: Error Reporting

#55094 TST: Make test_hash_equality_invariance xfail more generic
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Unreliable Test

#55097 Backport PR #55082 on branch 2.1.x (Updated future warning msg in transform() for Series.groupby)
  pandas/core/apply.py
Labels: Error Reporting

#55100 Backport PR #55094 on branch 2.1.x (TST: Make test_hash_equality_invariance xfail more generic)
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Unreliable Test

#54998 ENH: add calamine excel reader (close #50395)
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  doc/source/getting_started/install.rst
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v2.2.0.rst
  environment.yml
  pandas/compat/_optional.py
  pandas/core/config_init.py
  pandas/io/excel/_base.py
  pandas/io/excel/_calamine.py
  pandas/tests/io/excel/test_readers.py
  pyproject.toml
  requirements-dev.txt
  scripts/tests/data/deps_expected_random.yaml
  scripts/tests/data/deps_minimum.toml
  scripts/tests/data/deps_unmodified_random.yaml
Labels: Enhancement, IO Excel

#55108 PERF: Index.difference
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/datetimes/test_setops.py
  pandas/tests/indexes/timedeltas/test_setops.py
Labels: Performance, Index, setops

#55093 DOC: Remove deprecated attributes in DatetimeIndex
  pandas/core/indexes/datetimes.py
Labels: Docs

#55072 BUG: dt.tz with ArrowDtype returned string
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Timezones, Arrow

#55089 BUG: This fixes #55009 (`raw=True` caused `apply` method of `DataFrame` to ignore passed arguments)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/apply.py
  pandas/tests/apply/test_frame_apply.py
Labels: Apply

#55124 Backport PR #55072 on branch 2.1.x (BUG: dt.tz with ArrowDtype returned string)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Timezones, Arrow

#54996 BUG: boolean/string value in OdsWriter (#54994)
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/excel/_odswriter.py
  pandas/tests/io/excel/test_odswriter.py
  pandas/tests/io/excel/test_readers.py
Labels: Bug, IO Excel

#55129 Use pandasSQL transactions in sql test suite to avoid engine deadlocks
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#55101 DEPS: remove duplicated dependency in requirement-dev.txt
  environment.yml
  requirements-dev.txt
Labels: Dependencies

#55112 Assorted UBSAN cleanups
  pandas/_libs/src/vendored/ujson/lib/ultrajsonenc.c
  pandas/_libs/tslibs/np_datetime.pyx
Labels: Internals

#55008 CoW: Clear dead references every time we add a new one
  pandas/_libs/internals.pyx
Labels: Copy / view semantics

#55131 PERF: groupby aggregations on pyarrow timestamp and duration types
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
Labels: Timeseries, Groupby, Performance, Arrow

#54784 CI: Unpin Cython
  .github/workflows/unit-tests.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  meson.build
  pyproject.toml
  requirements-dev.txt
Labels: CI, Dependencies

#55159 DOCS: temporary pin pydata-sphinx-theme to 0.13
  environment.yml
  requirements-dev.txt
Labels: Docs

#55154 Backport PR #54784 on branch 2.1.x (CI: Unpin Cython)
  .github/workflows/unit-tests.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  meson.build
  pyproject.toml
  requirements-dev.txt
Labels: CI, Dependencies

#55161 Backport PR #55159 on branch 2.1.x (DOCS: temporary pin pydata-sphinx-theme to 0.13)
  environment.yml
  requirements-dev.txt
Labels: Docs

#55162 DOC: fix see also links in pandas.DataFrame.agg docstring
  pandas/core/frame.py
Labels: Docs, Sprints

#55165 DOC: remove duplicated sentence in return secion of pandas.DataFrame.agg /asof docstrings
  pandas/core/generic.py
  pandas/core/shared_docs.py
Labels: Docs, Sprints

#54977 ENH: add Series.struct accessor for ArrowDtype[struct]
  doc/source/reference/series.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/__init__.py
  pandas/core/arrays/arrow/accessors.py
  pandas/core/series.py
  pandas/tests/series/accessors/test_struct_accessor.py
Labels: Enhancement, Arrow, Accessors

#55180 MAINT: Cleanup expired ndarray methods
  doc/source/user_guide/gotchas.rst
  pandas/io/stata.py
Labels: Compat

#55172 DOC: complete parameter descriptions for DataFrame.insert's docstring
  pandas/core/frame.py
Labels: Docs, Sprints

#55155 CLN: de-duplicate code in _matplotlib.converter
  pandas/_libs/tslibs/dtypes.pyx
  pandas/plotting/_matplotlib/converter.py
  pandas/tests/plotting/test_converter.py
Labels: Visualization

#55149 docs: add explanation about `freq` units in `Timedelta.round()`
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Timedelta

#55113 BUG: Index.difference not always returning a unique set of values
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_setops.py
Labels: Bug, setops

#55035 BUG: Interval with Timestamp with tz shows tz
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/interval.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/indexes/interval.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/indexes/interval/test_formats.py
  pandas/tests/io/excel/test_writers.py
Labels: Output-Formatting, Timezones, Interval

#54940 BUG df.plot.box handles matplotlib Axes with sharey=True
  doc/source/whatsnew/v2.2.0.rst
  pandas/plotting/_matplotlib/boxplot.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Visualization

#54710 DEPR: downcasting in replace
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/series/methods/test_replace.py
Labels: Deprecate

#54261 DEPR: fillna downcasting from object dtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/io/formats/xml.py
  pandas/io/json/_json.py
  pandas/io/stata.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/extension/test_masked.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_logical_ops.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/test_function.py
  pandas/tests/series/methods/test_reindex.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_logical_ops.py
Labels: Dtype Conversions, Deprecate

#55184 Backport PR #55180 on branch 2.1.x (MAINT: Cleanup expired ndarray methods)
  doc/source/user_guide/gotchas.rst
  pandas/io/stata.py
Labels: Compat

#55186 STY: Fix precommit failure
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Code Style

#55177 DOC: added deprecation message in docs for DataFrame.rolling
  pandas/core/window/rolling.py
Labels: Docs, Window

#54834 ENH: add `ExtensionArray._explode` method; adjust pyarrow extension for use of new interface
  doc/source/reference/extensions.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/series.py
  pandas/tests/series/methods/test_explode.py
Labels: ExtensionArray

#55185 CI: Fix no BLAS error in 32 bit build
  .github/workflows/unit-tests.yml
Labels: CI, 32bit

#55191 Backport PR #55185 on branch 2.1.x (CI: Fix no BLAS error in 32 bit build)
  .github/workflows/unit-tests.yml
Labels: CI, 32bit

#55074 Replace classes with pytest in test_sql
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL

#55193 TST: Test GroupBy.__getitem__ with a column from grouper
  pandas/tests/groupby/test_grouping.py
Labels: Groupby, Needs Tests

#55175 DEPS: Bump to 1.26 proper for Python 3.12
  pyproject.toml
Labels: Dependencies, Python 3.12

#55190 TYP: Allow None in Period.strftime
  pandas/_libs/tslibs/period.pyi
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Period, Typing

#55201 BUG: RecursionError in loc.setitem
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_loc.py
Labels: Indexing

#54265 Modified doc/make.py to run sphinx-build -b linkcheck
  doc/make.py
Labels: Docs

#55198 Fix NameError in 'Evaluation order matters'
  doc/source/user_guide/indexing.rst
Labels: Docs

#55203 Backport PR #55175 on branch 2.1.x (DEPS: Bump to 1.26 proper for Python 3.12)
  pyproject.toml
Labels: Dependencies, Python 3.12

#55189 Revert "DEPR: Deprecate returning a DataFrame in SeriesApply.apply_standard
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.10.0.rst
  doc/source/whatsnew/v2.1.0.rst
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/apply.py
  pandas/core/series.py
  pandas/tests/apply/test_series_apply.py
Labels: Apply

#54952 REGR: Arrow backed objects not propagating exceptions
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Error Reporting, Arrow

#55044 DEPR: ArrayManager
  doc/source/whatsnew/v2.2.0.rst
  pandas/__init__.py
  pandas/conftest.py
  pandas/core/config_init.py
  pandas/core/frame.py
  pandas/core/series.py
  pandas/io/parquet.py
  pandas/tests/extension/conftest.py
  pandas/tests/internals/test_managers.py
  pandas/tests/io/test_parquet.py
  pandas/util/_test_decorators.py
  scripts/validate_unwanted_patterns.py
Labels: Deprecate, ArrayManager

#55210 CI: Pin matplotlib < 3.8
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  requirements-dev.txt
Labels: CI

#55211 DOC: Add release date for 2.1.1
  doc/source/whatsnew/v2.1.1.rst
Labels: Docs

#55216 Backport PR #55210 on branch 2.1.x (CI: Pin matplotlib < 3.8)
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  requirements-dev.txt
Labels: CI

#55209 Backport PR #54952 on branch 2.1.x (REGR: Arrow backed objects not propagating exceptions)
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Error Reporting, Arrow

#55207 DOC: Add whatsnew for 2.1.2
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.1.0.rst
  doc/source/whatsnew/v2.1.1.rst
  doc/source/whatsnew/v2.1.2.rst
Labels: Docs

#55217 Backport PR #55050 on branch 2.1.x (Fix docstring of Index.join in base.py)
  pandas/core/indexes/base.py
Labels: Docs

#55205 Backport PR #55189 on branch 2.1.x (Revert "DEPR: Deprecate returning a DataFrame in SeriesApply.apply_standard)
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v0.10.0.rst
  doc/source/whatsnew/v2.1.0.rst
  doc/source/whatsnew/v2.1.1.rst
  pandas/core/apply.py
  pandas/core/series.py
  pandas/tests/apply/test_series_apply.py
Labels: Apply

#55220 Backport PR #55008 on branch 2.1.x (CoW: Clear dead references every time we add a new one)
  pandas/_libs/internals.pyx
Labels: Copy / view semantics

#55221 Backport PR #55207 on branch 2.1.x (DOC: Add whatsnew for 2.1.2)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.1.0.rst
  doc/source/whatsnew/v2.1.1.rst
  doc/source/whatsnew/v2.1.2.rst
Labels: Docs

#55219 BUG: manage raw ods file without cell cache
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/excel/_odfreader.py
  pandas/tests/io/data/excel/test_unempty_cells.ods
  pandas/tests/io/excel/test_odf.py
Labels: IO Excel

#55206 BUILD: Fix duplicate files warning
  pandas/_libs/meson.build
  pandas/_libs/tslibs/meson.build
  pandas/_libs/window/meson.build
  pandas/meson.build
Labels: Build

#54964 BUG: IntervalIndex.get_indexer incorrectly matching ints to datetimes
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexes/base.py
  pandas/core/reshape/tile.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/reshape/test_cut.py
Labels: Interval

#55222 Backport PR #55206 on branch 2.1.x (BUILD: Fix duplicate files warning)
  pandas/_libs/meson.build
  pandas/_libs/tslibs/meson.build
  pandas/_libs/window/meson.build
  pandas/meson.build
Labels: Build

#55183 Faster ensure_string_array
  pandas/_libs/lib.pyx
Labels: Performance, Strings

#55233 Typo: 'whenlines' -> 'when lines'
  pandas/io/json/_json.py
  pandas/tests/io/json/test_readlines.py
Labels: Error Reporting

#54460 Fixes grouped rank bug with nullable types.
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/arrays/masked.py
  pandas/tests/groupby/test_rank.py
Labels: Bug, Groupby, NA - MaskedArrays, Transformations

#55241 PERF: Add type-hints in tzconversion.pyx
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/tzconversion.pyx
Labels: Performance, Timezones

#55240 DOC: point out that explicitly passing axis=None is deprecated for sum, prod, var, std, sem
  pandas/core/generic.py
Labels: Docs

#54653 DOC: fix build failure with sphinx 7 and SOURCE_DATE_EPOCH
  doc/source/conf.py
Labels: Docs, Stale

#55249 BUG: incompatible dtype when creating string column with loc
  doc/source/whatsnew/v2.1.2.rst
  pandas/core/dtypes/missing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_set_value.py
Labels: Indexing

#54643 ENH: Add on_bad_lines for pyarrow
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_unsupported.py
Labels: IO CSV, Arrow

#55251 Backport PR #55249 on branch 2.1.x (BUG: incompatible dtype when creating string column with loc)
  doc/source/whatsnew/v2.1.2.rst
  pandas/core/dtypes/missing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_set_value.py
Labels: Indexing

#55236 DOC: Fix doc for first_valid_index
  pandas/core/generic.py
Labels: Docs

#55262 CLN: Remove temp_setattr from groupby.transform
  pandas/core/groupby/groupby.py
Labels: Groupby, Clean

#55277 Updated `pre-commit` hooks versions.
  .pre-commit-config.yaml
  pyproject.toml
Labels: Code Style

#55273 ASV: add GroupBy.sum benchmark with timedelta and integer types
  asv_bench/benchmarks/groupby.py
Labels: Benchmark
