Repository pandas-dev/pandas, pull requests merged in 2024-01, with the labels that each got.

#56286 DOC: Explicit how 'cond' is updated on 'where'
  pandas/core/generic.py
Labels: Stale

#56167 [ENH]: Expand types allowed in Series.struct.field
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/accessors.py
  pandas/tests/series/accessors/test_struct_accessor.py
Labels: Nested Data, Arrow

#56698 Backport PR #56167 on branch 2.2.x ([ENH]: Expand types allowed in Series.struct.field)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/accessors.py
  pandas/tests/series/accessors/test_struct_accessor.py
Labels: Nested Data, Arrow

#56689 TYP: mostly Hashtable and ArrowExtensionArray
  pandas/_libs/hashtable.pyi
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_typing.py
  pandas/compat/pickle_compat.py
  pandas/core/accessor.py
  pandas/core/algorithms.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/arrow/extension_types.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/accessor.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/array_manager.py
  pandas/core/internals/managers.py
  pandas/core/strings/object_array.py
  pandas/core/tools/datetimes.py
Labels: Typing

#56685 add test for concating tzaware series with empty series. Issue: #34174
  pandas/tests/dtypes/test_concat.py
Labels: Testing

#56691 Bug pyarrow implementation of str.fullmatch matches partial string. issue #56652
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/strings/test_find_replace.py
Labels: Strings, Arrow

#56708 TST/CLN: Use more shared fixtures
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/series/methods/test_view.py
  pandas/tests/test_expressions.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/util/test_assert_frame_equal.py
Labels: Testing, Clean

#56709 TST/CLN: Reuse more existing fixtures
  pandas/tests/arrays/test_timedeltas.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Testing, Clean

#56699 DOC: Corrected typo in warning on coerce
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/internals/blocks.py
Labels: Docs

#56715 Backport PR #56691 on branch 2.2.x (Bug pyarrow implementation of str.fullmatch matches partial string. issue #56652)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/strings/test_find_replace.py
Labels: Strings, Arrow

#56616 BUG: Add limit_area to EA ffill/bfill
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/methods/test_fillna.py
  scripts/validate_unwanted_patterns.py
Labels: Bug, Missing-data, ExtensionArray

#56719 Backport PR #56699 on branch 2.2.x (DOC: Corrected typo in warning on coerce)
  doc/source/whatsnew/v2.1.0.rst
  pandas/core/internals/blocks.py
Labels: Docs

#56672 BUG: dictionary type astype categorical using dictionary as categories
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/extension/test_arrow.py
Labels: Categorical, Arrow

#56720 Backport PR #56616 on branch 2.2.x (BUG: Add limit_area to EA ffill/bfill)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/internals/blocks.py
  pandas/core/missing.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/methods/test_fillna.py
  scripts/validate_unwanted_patterns.py
Labels: Bug, Missing-data, ExtensionArray

#56721 DOC: Fixup read_csv docstring
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#56725 Backport PR #56721 on branch 2.2.x (DOC: Fixup read_csv docstring)
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#56723 Backport PR #56672 on branch 2.2.x (BUG: dictionary type astype categorical using dictionary as categories)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/extension/test_arrow.py
Labels: Categorical, Arrow

#56543 DOC: Update docstring for read_excel
  doc/source/user_guide/io.rst
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#56730 Backport PR #56543 on branch 2.2.x (DOC: Update docstring for read_excel)
  doc/source/user_guide/io.rst
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#56726 TST/CLN: Reuse more fixtures
  pandas/tests/base/test_misc.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/scalar/timestamp/test_formats.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_compare.py
  pandas/tests/series/methods/test_cov_corr.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/test_algos.py
  pandas/tests/util/test_assert_extension_array_equal.py
  pandas/tests/util/test_assert_series_equal.py
  pandas/tests/window/test_rolling_functions.py
Labels: Testing, Clean

#56677 Fix integral truediv and floordiv for pyarrow types with large divisor and avoid floating points for floordiv
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#56744 Backport PR #56677 on branch 2.2.x (Fix integral truediv and floordiv for pyarrow types with large divisor and avoid floating points for floordiv)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#56746 TST: Scope pytest.raises closer to failing line
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/methods/test_compare.py
  pandas/tests/frame/methods/test_sample.py
  pandas/tests/frame/methods/test_tz_convert.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexing/test_na_indexing.py
  pandas/tests/indexing/test_scalar.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/excel/test_openpyxl.py
  pandas/tests/io/parser/dtypes/test_empty.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_stata.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_hist_method.py
  pandas/tests/reshape/test_util.py
  pandas/tests/series/methods/test_between.py
  pandas/tests/series/methods/test_compare.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/window/test_base_indexer.py
Labels: Testing, Clean

#56671 STY: Enable ruff pytest checks
  .pre-commit-config.yaml
  pandas/conftest.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/arrays/masked/test_function.py
  pandas/tests/arrays/sparse/test_arithmetics.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/arrays/test_array.py
  pandas/tests/copy_view/test_internals.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/extension/base/dim2.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_explode.py
  pandas/tests/frame/methods/test_filter.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/conftest.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/indexes/datetimelike_/test_sort_values.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_to_latex.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/usecols/test_strings.py
  pandas/tests/io/pytables/test_compat.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_sql.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/scalar/test_nat.py
  pandas/tests/series/methods/test_size.py
  pandas/tests/strings/test_extract.py
  pandas/tests/test_nanops.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tseries/frequencies/test_inference.py
  pandas/tests/tslibs/test_to_offset.py
  pyproject.toml
  scripts/tests/test_validate_unwanted_patterns.py
  scripts/validate_unwanted_patterns.py
  web/tests/test_pandas_web.py
Labels: Code Style

#56737 TST/CLN: Test parametrizations
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/arrays/categorical/test_indexing.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/sparse/test_dtype.py
  pandas/tests/arrays/sparse/test_reductions.py
  pandas/tests/base/test_conversion.py
  pandas/tests/computation/test_eval.py
  pandas/tests/copy_view/index/test_datetimeindex.py
  pandas/tests/copy_view/index/test_periodindex.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/frame/indexing/test_get.py
  pandas/tests/frame/methods/test_drop.py
  pandas/tests/frame/methods/test_filter.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/frame/test_unary.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/test_bin_groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Testing, Clean

#56688 Added validation check for integer value for series.df
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/algorithms.py
  pandas/core/series.py
  pandas/tests/series/methods/test_diff.py
Labels: Error Reporting, Series, Transformations

#56761 BUG: fix subclass metadata preservation in groupby column selection
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/tests/groupby/test_groupby_subclass.py
Labels: Bug, Groupby, Regression, Subclassing

#56770 Backport PR #56761 on branch 2.2.x (BUG: fix subclass metadata preservation in groupby column selection)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/frame.py
  pandas/tests/groupby/test_groupby_subclass.py
Labels: Bug, Groupby, Regression, Subclassing

#56751 CI: Allow no argument in code_checks
  ci/code_checks.sh
Labels: Bug, CI

#56769 BUG: replace matching Floats with bools for ea dtypes
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/missing.py
  pandas/tests/series/methods/test_replace.py
Labels: replace, NA - MaskedArrays

#56780 Backport PR #56769 on branch 2.2.x (BUG: replace matching Floats with bools for ea dtypes)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/missing.py
  pandas/tests/series/methods/test_replace.py
Labels: replace, NA - MaskedArrays

#56767 BUG: Series.round raising for nullable bool dtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/masked.py
  pandas/core/series.py
  pandas/tests/series/methods/test_round.py
Labels: NA - MaskedArrays

#56771 BUG: to_stata not handling ea dtypes correctly
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata, NA - MaskedArrays, Arrow

#56680 DEPR: utcnow, utcfromtimestamp
  doc/source/whatsnew/v2.3.0.rst
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/groupby/methods/test_groupby_shift_diff.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/tools/test_to_datetime.py
Labels: Deprecate

#56766 BUG: IntervalIndex.from_tuples raising with masked subtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/interval.py
  pandas/tests/indexes/interval/test_constructors.py
Labels: Interval, NA - MaskedArrays

#56724 TST: Don't ignore tolerance for integer series
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Testing

#56782 Backport PR #56767 on branch 2.2.x (BUG: Series.round raising for nullable bool dtype)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/masked.py
  pandas/core/series.py
  pandas/tests/series/methods/test_round.py
Labels: NA - MaskedArrays

#56783 Backport PR #56771 on branch 2.2.x (BUG: to_stata not handling ea dtypes correctly)
  doc/source/whatsnew/v2.2.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata, NA - MaskedArrays, Arrow

#56785 Backport PR #56766 on branch 2.2.x (BUG: IntervalIndex.from_tuples raising with masked subtype)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/interval.py
  pandas/tests/indexes/interval/test_constructors.py
Labels: Interval, NA - MaskedArrays

#56786 Backport PR #56724 on branch 2.2.x (TST: Don't ignore tolerance for integer series)
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Testing

#56402 TST/CoW: expand test for chained inplace methods
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
Labels: Copy / view semantics

#56749 TST/CLN: Remove unnecessary copies in tests
  pandas/tests/io/test_stata.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_series.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/series/indexing/test_datetime.py
  pandas/tests/series/methods/test_cov_corr.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/series/methods/test_nlargest.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/series/methods/test_sort_values.py
  pandas/tests/series/methods/test_to_csv.py
  pandas/tests/series/methods/test_unstack.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/test_algos.py
  pandas/tests/test_expressions.py
  pandas/tests/test_sorting.py
  pandas/tests/tools/test_to_numeric.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_pairwise.py
  pandas/tests/window/test_win_type.py
Labels: Testing, Clean

#56442 BUG: merge not sorting for new string dtype
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_multi.py
Labels: Reshaping, Strings, Arrow

#56790 Backport PR #56402 on branch 2.2.x (TST/CoW: expand test for chained inplace methods)
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
Labels: Copy / view semantics

#56772 Support large strings in interchange protocol
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/dtypes/dtypes.py
  pandas/core/interchange/column.py
  pandas/core/interchange/utils.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#56795 Backport PR #56772 on branch 2.2.x (Support large strings in interchange protocol)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/dtypes/dtypes.py
  pandas/core/interchange/column.py
  pandas/core/interchange/utils.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#56059 ENH: Add case_when method
  doc/source/reference/series.rst
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_case_when.py
Labels: Series

#56789 DOC: add to to_offset the missing parameter is_period and examples
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#56803 CI: Add fixture back in
  pandas/tests/reshape/merge/test_multi.py
Labels: Testing

#56757 ENH: Implement interpolation for arrow and masked dtypes
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/core/missing.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Enhancement, Missing-data, NA - MaskedArrays, Arrow

#56807 'Backport PR #56146: BUG raise pdep6 warning for loc full setter'
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_update.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/indexing/test_indexing.py
Labels: PDEP6-related

#56812 BLD: Pin numpy on 2.2.x
  pyproject.toml
Labels: Build, Blocker

#56813 Backport PR #56594 on branch 2.2.x (DEPR: the method is_anchored() for offsets)
  doc/source/whatsnew/v2.2.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/interval/test_interval_range.py
  pandas/tests/tseries/offsets/test_business_quarter.py
  pandas/tests/tseries/offsets/test_fiscal.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_quarter.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/tests/tseries/offsets/test_week.py
Labels: Frequency, Deprecate

#56808 Removed describe, loc and iloc methods from code_checks.sh
  ci/code_checks.sh
Labels: Docs

#56481 Revert "DEPR: make_block (#56422)"
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/internals/api.py
  pandas/tests/internals/test_api.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/parser/common/test_chunksize.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: Internals, Compat, Blocker

#56788 Bug: Interchange protocol implementation does not allow for empty string columns
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#56802 BUG: Change the prompt on non list record path errors (PR: #56405)
  pandas/io/json/_normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: Error Reporting, IO JSON

#56806 PERF: Index.take to check for full range indices
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
Labels: Performance, Index

#56738 TST/CLN: Test parametrizations 2
  pandas/tests/indexes/base_class/test_setops.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/interval/test_interval.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_isin.py
  pandas/tests/indexes/multi/test_join.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/numeric/test_indexing.py
  pandas/tests/indexes/numeric/test_setops.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/test_indexing.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/formats/style/test_highlight.py
  pandas/tests/io/formats/style/test_matplotlib.py
  pandas/tests/io/formats/style/test_to_latex.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/formats/test_to_latex.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_json_table_schema_ext_dtype.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
  pandas/tests/io/parser/common/test_index.py
  pandas/tests/io/parser/common/test_ints.py
  pandas/tests/io/parser/test_encoding.py
  pandas/tests/io/parser/test_na_values.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
  pandas/tests/io/pytables/test_categorical.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/xml/test_to_xml.py
Labels: Testing, Clean

#56745 TST/CLN: Tests parametrizations 3
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/concat/test_series.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/merge/test_merge_ordered.py
  pandas/tests/reshape/test_from_dummies.py
  pandas/tests/reshape/test_get_dummies.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/reshape/test_qcut.py
  pandas/tests/scalar/period/test_arithmetic.py
  pandas/tests/scalar/timedelta/methods/test_round.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/scalar/timestamp/methods/test_round.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/indexing/test_getitem.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/indexing/test_where.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_diff.py
  pandas/tests/series/methods/test_drop.py
  pandas/tests/series/methods/test_drop_duplicates.py
  pandas/tests/series/methods/test_duplicated.py
  pandas/tests/series/methods/test_explode.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/series/methods/test_info.py
  pandas/tests/series/methods/test_isin.py
  pandas/tests/series/methods/test_replace.py
  pandas/tests/series/methods/test_update.py
  pandas/tests/series/methods/test_value_counts.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_constructors.py
  pandas/tests/series/test_cumulative.py
  pandas/tests/series/test_logical_ops.py
Labels: Testing, Clean

#56816 Backport PR #56788 on branch 2.2.x (Bug: Interchange protocol implementation does not allow for empty string columns)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#56814 Backport PR #56481 on branch 2.2.x (Revert "DEPR: make_block (#56422)")
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/internals/api.py
  pandas/tests/internals/test_api.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/parser/common/test_chunksize.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: Internals, Compat, Blocker

#55327 COMPAT: Fix warning with numba >= 0.58.0
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/util/numba_.py
  pandas/tests/window/test_numba.py
Labels: Compat, numba

#56819 Backport PR #56818 on branch 2.2.x (CI: Fix failing builds)
  pandas/tests/io/parser/common/test_chunksize.py
  pandas/tests/io/parser/common/test_read_errors.py
Labels: CI, Warnings

#56820 Backport PR #55327 on branch 2.2.x (COMPAT: Fix warning with numba >= 0.58.0)
  doc/source/whatsnew/v2.2.0.rst
  pandas/core/util/numba_.py
  pandas/tests/window/test_numba.py
Labels: Compat, numba

#56831 BUG fix for date_range 56134
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_date_range.py
Labels: Timeseries

#56830 DOC: fix EX03 errors in docstrings -pandas.DataFrame for idxmax, idxmin, pivot
  pandas/core/frame.py
  pandas/core/shared_docs.py
Labels: Docs

#56833 Fix typo in docstring example
  pandas/core/resample.py
Labels: Docs

#56822 TST: Additions/updates to tests
  pandas/tests/io/formats/style/test_style.py
Labels: Testing, Styler

#56817 PERF: Join non unique
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/indexes/base.py
Labels: Performance, Reshaping

#56787 TST/CLN: Test parametrizations 4
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_split_partition.py
  pandas/tests/test_errors.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_numeric.py
  pandas/tests/tools/test_to_timedelta.py
  pandas/tests/tslibs/test_array_to_datetime.py
  pandas/tests/tslibs/test_conversion.py
  pandas/tests/tslibs/test_liboffsets.py
  pandas/tests/util/test_assert_almost_equal.py
  pandas/tests/util/test_assert_categorical_equal.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/util/test_hashing.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_rolling.py
Labels: Testing, Clean

#56828 Remove pandas.core.groupby.DataFrameGroupBy for describe, idxmax, idxmin, value_counts from ci/code_checks.sh
  ci/code_checks.sh
Labels: Docs

#56524 DOC: Added docstrings to fixtures defined in XML I/O, util and pandas modules
  pandas/conftest.py
  pandas/tests/io/xml/conftest.py
  pandas/tests/util/conftest.py
Labels: Testing, Docs

#56841 PERF: use the libjoin fast paths in a few more cases
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/indexes/base.py
Labels: Performance, Reshaping

#56834 DOC: Fix EX03 flake8 errors in docstrings
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
  pandas/plotting/_core.py
Labels: Docs

#56861 DOC: ex03 - no fix required
  ci/code_checks.sh
Labels: Docs

#56859 TST: Move tests out of test_groupby
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_reductions.py
Labels: Testing, Groupby, Clean

#56849 REGR: freq "m" (as alias of deprecated "M") raises an error
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Regression, Frequency

#56862 Backport PR #56849 on branch 2.2.x (REGR: freq "m" (as alias of deprecated "M") raises an error)
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Regression, Frequency

#56843 DOC: fix EX03 errors in docstrings - pandas.Series.to_latex, pandas.read_pickle, pandas.DataFrame.to_latex, pandas.core.resample.Resampler.pipe
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/io/formats/style.py
  pandas/io/pickle.py
Labels: Docs

#56871 DOC: Remove manual doctesting from validate_docstrings
  ci/code_checks.sh
  scripts/tests/test_validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs

#56873 CI: unxfail adbc-driver-postgresql test
  pandas/tests/io/test_sql.py
Labels: IO SQL, Arrow

#56875 Backport PR #56873 on branch 2.2.x (CI: unxfail adbc-driver-postgresql test)
  pandas/tests/io/test_sql.py
Labels: IO SQL, Arrow

#56827 CI: Improve error message format in validate_docstrings.py
  scripts/validate_docstrings.py
Labels: Docs, CI

#56867 DOC: fix EX03 in `pandas.errors`
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#56868 DOC: fix EX03 errors in docstrings - pandas.core.resample.Resampler.interpolate, pandas.pivot, pandas.merge_asof, pandas.wide_to_long
  ci/code_checks.sh
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
Labels: Docs

#56881 DOC: fix EX03 errors in docstrings - pandas.io.formats.style.Styler: format_index, relabel_index, hide, set_td_classes
  ci/code_checks.sh
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
Labels: Docs

#56884 DOC: fix EX03 in pandas.ExcelWriter
  ci/code_checks.sh
  pandas/io/excel/_base.py
Labels: Docs

#56870 DOC: fix EX03 errors in docstrings - pandas.Index.rename, pandas.Index.isin, pandas.IndexSlice
  ci/code_checks.sh
  pandas/core/indexes/base.py
  pandas/core/indexing.py
Labels: Docs

#56760 TYP: Persist typing information for pipe args and kwargs
  pandas/_typing.py
  pandas/core/common.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/io/formats/style.py
Labels: Typing

#56886 DOC: Additions/updates to documentation : grammar changes to documentation
  doc/source/development/contributing.rst
Labels: Docs

#56889 TST: extension tests use its own fixtures
  pandas/tests/extension/base/accumulate.py
  pandas/tests/extension/base/dtype.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/extension/test_masked.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_period.py
  pandas/tests/extension/test_sparse.py
Labels: Testing, ExtensionArray

#56879 DOC: fix EX03 errors in docstrings - pandas.Timestamp - ceil, floor, round
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#56880 DOC: fix EX03 errors in docstrings - pandas.io.json.build_table_schema, pandas.read_stata, pandas.plotting.scatter_matrix, pandas.Index.droplevel , pandas.Grouper
  ci/code_checks.sh
  pandas/core/groupby/grouper.py
  pandas/core/indexes/base.py
  pandas/io/json/_table_schema.py
  pandas/io/stata.py
  pandas/plotting/_misc.py
Labels: Docs

#56878 DOC: fixed Ex03 errors in docstrings:
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#56762 DOC: Avoid requesting data from s3 buckets from our docs
  doc/source/user_guide/io.rst
Labels: Docs

#56891 DOC: Add deprecated markers for downcast keyword
  pandas/core/generic.py
Labels: Docs

#56893 Backport PR #56891 on branch 2.2.x (DOC: Add deprecated markers for downcast keyword)
  pandas/core/generic.py
Labels: Docs

#56898 DOC: Docstring EX03 fixes for pandas.DataFrame methods
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#56901 DOC: fix EX03 errors in docstrings - pandas.io.formats.style.Styler: set_tooltips, set_uuid, pipe, highlight_between
  ci/code_checks.sh
  pandas/io/formats/style.py
Labels: Docs

#56855 DOC: fix EX03 errors in docstrings
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
Labels: Docs

#56900 DOC: EX03 fixes on dataframe.plot methods: hexbin, line
  ci/code_checks.sh
  pandas/plotting/_core.py
Labels: Docs

#56909 DOC: fix imprecision in the type description of `pd.concat` parameter
  pandas/core/reshape/concat.py
Labels: Docs

#56895 STY: enable PLR5501
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/window/test_rolling.py
  pandas/util/_validators.py
  pyproject.toml
Labels: Code Style, Clean

#56894 STY: Remove black-specific rule
  pyproject.toml
Labels: Code Style

#56904 DOC: fix EX03 errors in docstrings - pandas.io.formats.style.Styler: highlight_quantile, background_gradient, text_gradient
  ci/code_checks.sh
  pandas/io/formats/style.py
Labels: Docs

#56906 DEPR: freq ''2BQ-SEP" for to_period should raise an error
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/period/test_constructors.py
Labels: Frequency, Period

#56915 read_csv: adding "round_trip" to the "float_precision" accepted literal types
  pandas/io/parsers/readers.py
Labels: IO CSV, Typing

#56916 Backport PR #56906 on branch 2.2.x (DEPR: freq ''2BQ-SEP" for to_period should raise an error)
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/period/test_constructors.py
Labels: Frequency, Period

#56914 Autofix ruf010
  .pre-commit-config.yaml
  doc/scripts/eval_performance.py
  pandas/_config/config.py
  pandas/_testing/_warnings.py
  pandas/_testing/asserters.py
  pandas/_version.py
  pandas/conftest.py
  pandas/core/accessor.py
  pandas/core/array_algos/replace.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/masked.py
  pandas/core/computation/align.py
  pandas/core/computation/expressions.py
  pandas/core/computation/ops.py
  pandas/core/computation/pytables.py
  pandas/core/dtypes/cast.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/dtypes.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/base.py
  pandas/core/indexes/frozen.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/range.py
  pandas/core/internals/concat.py
  pandas/core/methods/selectn.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/tile.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/io/formats/css.py
  pandas/io/formats/excel.py
  pandas/io/formats/style.py
  pandas/io/html.py
  pandas/io/json/_normalize.py
  pandas/io/parsers/readers.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sasreader.py
  pandas/plotting/_core.py
  pandas/tests/arrays/masked/test_indexing.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/frame/test_repr.py
  pandas/tests/indexes/test_base.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/test_html.py
  pandas/tests/strings/test_api.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/util/_decorators.py
  pyproject.toml
  scripts/validate_unwanted_patterns.py
Labels: Code Style

#56892 TYP: Update pyright
  .pre-commit-config.yaml
  pandas/_config/config.py
  pandas/_config/localization.py
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/computation/eval.py
  pandas/core/dtypes/missing.py
  pandas/core/frame.py
  pandas/core/indexes/range.py
  pandas/core/ops/common.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/strings/object_array.py
  pandas/core/tools/timedeltas.py
  pandas/plotting/_matplotlib/hist.py
  pandas/util/_validators.py
  pyright_reportGeneralTypeIssues.json
Labels: Typing

#56910 DEPR: lowercase freqs 'ye', 'qe', etc. raise a ValueError
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Frequency, Deprecate

#56924 Backport PR #56910 on branch 2.2.x (DEPR: lowercase freqs 'ye', 'qe', etc. raise a ValueError)
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/indexes/datetimes/test_partial_slicing.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Frequency, Deprecate

#56930 DOC: update install instruction with correct Python version support (including 3.12)
  doc/source/getting_started/install.rst
Labels: Docs

#56931 Backport PR #56930 on branch 2.2.x (DOC: update install instruction with correct Python version support (including 3.12))
  doc/source/getting_started/install.rst
Labels: Docs

#56925 DOC: indicate that origin argument can be a string that is timestamp …
  pandas/core/generic.py
Labels: Docs

#56919 PERF: DataFrame.join with how=left|right and sort=True
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/indexes/base.py
Labels: Performance, Reshaping

#56546 DOC: Add docs for read_sql to avoid sql injection
  pandas/io/sql.py
Labels: Docs, IO SQL

#56445 Adjust merge tests for new string option
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/merge/test_multi.py
Labels: Strings

#56824 DOC: 2.2.0 whatsnew cleanups
  doc/source/whatsnew/v2.1.4.rst
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs

#56933 Backport PR #56824 on branch 2.2.x (DOC: 2.2.0 whatsnew cleanups)
  doc/source/whatsnew/v2.1.4.rst
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs

#56905 DOC: Ex03 errors docstrings
  ci/code_checks.sh
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
Labels: Docs

#56938 Backport PR #56445: Adjust merge tests for new string option
  pandas/tests/reshape/merge/test_join.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/merge/test_multi.py
Labels: Strings

#56926 BUG: fix `groupby.quantile` inconsistency when interpolation='nearest'
  doc/source/whatsnew/v2.3.0.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/methods/test_quantile.py
Labels: Groupby, quantile

#56943 DOC: Remove references to AxesSubPlot #56876
  pandas/plotting/_core.py
Labels: Docs, Visualization

#56937 DOC: Remove inconsistency with timestamp data in describe() method docs
  pandas/core/generic.py
Labels: Docs

#56838 CLN: Drop Numpy 1.22 per NEP29
  ci/deps/actions-39-minimum_versions.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v2.3.0.rst
  pandas/compat/numpy/__init__.py
  pandas/tests/interchange/test_impl.py
  pyproject.toml
Labels: Clean, Dependencies

#56587 ENH: support the Arrow PyCapsule Interface on pandas.DataFrame (export)
  pandas/compat/_optional.py
  pandas/core/frame.py
  pandas/tests/frame/test_arrow_interface.py
  pandas/tests/test_optional_dependency.py
Labels: Arrow

#56944 Backport PR #56587 on branch 2.2.x (ENH: support the Arrow PyCapsule Interface on pandas.DataFrame (export))
  pandas/compat/_optional.py
  pandas/core/frame.py
  pandas/tests/frame/test_arrow_interface.py
  pandas/tests/test_optional_dependency.py
Labels: Arrow

#56947 DOC: Set date for 2.2
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs

#56950 Backport PR #56947 on branch 2.2.x (DOC: Set date for 2.2)
  doc/source/whatsnew/v2.2.0.rst
Labels: Docs

#56949 CI: avoid FutureWarnings in to_xarray tests
  pandas/tests/generic/test_to_xarray.py
Labels: Testing, CI

#56922 REGR: DatetimeTZDtype __from_arrow__ interprets UTC values as wall time
  pandas/core/dtypes/dtypes.py
  pandas/tests/arrays/datetimes/test_constructors.py
Labels: Regression, Arrow

#56896 DEPS: Add warning if pyarrow is not installed
  .github/workflows/unit-tests.yml
  pandas/__init__.py
  pandas/compat/pyarrow.py
  pandas/tests/test_common.py
Labels: Dependencies, Warnings

#56952 DEPR: Make FutureWarning into DeprecationWarning for groupby.apply
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/window/test_groupby.py
Labels: Groupby, Deprecate, Apply

#56961 Backport PR #56949 on branch 2.2.x (CI: avoid FutureWarnings in to_xarray tests)
  pandas/tests/generic/test_to_xarray.py
Labels: Testing, CI

#56953 DOC: fixed Ex03 errors in docstrings: pandas.io.formats.style.Styler.to_latex and pandas.read_parquet
  ci/code_checks.sh
  pandas/io/formats/style.py
  pandas/io/parquet.py
Labels: Docs

#56962 Backport PR #56922 on branch 2.2.x (REGR: DatetimeTZDtype __from_arrow__ interprets UTC values as wall time)
  pandas/core/dtypes/dtypes.py
  pandas/tests/arrays/datetimes/test_constructors.py
Labels: Regression, Arrow

#56963 Backport PR #56896 on branch 2.2.x (DEPS: Add warning if pyarrow is not installed)
  .github/workflows/unit-tests.yml
  pandas/__init__.py
  pandas/compat/pyarrow.py
  pandas/tests/test_common.py
Labels: Dependencies, Warnings

#56967 CI: Adjust pyarrow depr warning to account for different newlines on …
  pandas/tests/test_common.py
Labels: Build

#56969 Backport PR #56967 on branch 2.2.x (CI: Adjust pyarrow depr warning to account for different newlines on …)
  pandas/tests/test_common.py
Labels: Build

#56980 WEB: Add version 2.2 to the dropdown
  web/pandas/versions.json
Labels: Web

#56986 WEB: Fix typo in dropdown page
  web/pandas/versions.json
Labels: Web

#56983 Backport PR #56980 on branch 2.2.x (WEB: Add version 2.2 to the dropdown)
  web/pandas/versions.json
Labels: Web

#56987 Backport PR #56986 on branch 2.2.x (WEB: Fix typo in dropdown page)
  web/pandas/versions.json
Labels: Web

#56989 DOC: fix EX03 errors in docstrings - pandas.errors: SettingWithCopyWarning, SpecificationError, UndefinedVariableError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#56823 DOC: Change 2.3.0 to 3.0.0
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#56982 DOC: Add release notes for 2.2.1
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.2.1.rst
Labels: Docs

#56971 CI/DOC: Enforce PR02 in CI
  ci/code_checks.sh
Labels: Docs, CI

#56941 STY: Enable B904
  asv_bench/benchmarks/algos/isin.py
  asv_bench/benchmarks/array.py
  asv_bench/benchmarks/strings.py
  pandas/compat/_optional.py
  pandas/core/array_algos/datetimelike_accumulations.py
  pandas/core/array_algos/masked_accumulations.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/period.py
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/interchange/column.py
  pandas/core/reshape/encoding.py
  pandas/core/sorting.py
  pandas/core/tools/datetimes.py
  pandas/io/formats/style_render.py
  pandas/io/formats/xml.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/xml.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/test_common.py
  pyproject.toml
  web/pandas_web.py
Labels: Code Style
