Repository pandas-dev/pandas, pull requests merged in 2024-08, with the labels that each got.

#59376 String dtype: restrict options.mode.string_storage to python|pyarrow (remove pyarrow_numpy)
  pandas/conftest.py
  pandas/core/config_init.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/io/conftest.py
Labels: Strings

#59373 fix: show correct error message when invalid period alias is passed to to_timestamp
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/indexes/period/methods/test_to_timestamp.py
Labels: Error Reporting, Frequency

#59318 DOC: Typo in docs for na_values parameter in pandas.read_csv function #59314
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#59357 CI: Use Miniforge over Mambaforge
  .circleci/config.yml
Labels: Build, CI

#59416 DOC: Remove outdated performance metrics from 'Accelerated operations…
  doc/source/user_guide/basics.rst
Labels: Docs

#59394 DOC: Fix RT03 for pandas.Series.str.find
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Series, Accessors

#59396 DOC: Fix pandas.Series.str.get RT03,SA01
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Series, Accessors

#59423 CI: Install libegl explicitly for pytest-qt on ubuntu
  .circleci/config.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/unit-tests.yml
Labels: CI

#59424 Backport PR #59423: CI: Install libegl explicitly for pytest-qt on ubuntu
  .circleci/config.yml
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/unit-tests.yml
Labels: CI

#59400 DOC: fix SA01 for pandas.MultiIndex.get_level_values
  ci/code_checks.sh
  pandas/core/indexes/multi.py
Labels: Docs, MultiIndex

#59406 DOC: Add 'See Also' for pandas.api.types.is_sparse
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59404 DOC: Add 'See Also' for pandas.api.types.is_any_real_numeric_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59377 DOC: Add 'See Also' and 'Parameters' for pandas.api.indexers.VariableOffsetWindowIndexer
  ci/code_checks.sh
  pandas/core/indexers/objects.py
Labels: Docs

#57958 BUG: Fix `is_unique` regression for slices of `Index`es
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/index.pyx
  pandas/tests/indexes/test_base.py
Labels: Index

#59401 CI: Update to cibuildwheel 2.20.0
  .circleci/config.yml
  .github/workflows/wheels.yml
Labels: Build, CI

#59425 DOC: Improve DataFrameGroupBy.std ddof doc
  pandas/core/groupby/groupby.py
Labels: Docs

#59414 API/TST: expand tests for string any/all reduction + fix pyarrow-based implementation
  pandas/core/arrays/string_arrow.py
  pandas/tests/reductions/test_reductions.py
Labels: API Design, Strings, Reduction Operations

#59427 BUG Fix for Add numeric_only to function signature of DataFrameGroupBy.cumprod and `DataFrameGroupBy.cumsum
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_api.py
Labels: Groupby

#58451 String dtype: implement object-dtype based StringArray variant with NumPy semantics
  pandas/_libs/lib.pyx
  pandas/_testing/asserters.py
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/conftest.py
  pandas/core/arrays/string_.py
  pandas/core/construction.py
  pandas/core/dtypes/cast.py
  pandas/core/internals/construction.py
  pandas/io/_util.py
  pandas/io/pytables.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/series/test_constructors.py
  pandas/tests/strings/test_find_replace.py
Labels: Strings

#59439 removed link to numpy's resources tutorial
  doc/source/development/contributing.rst
Labels: Docs

#59441 COMPAT: Fix numpy 2.1 timedelta * DateOffset
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Numeric Operations, Timedelta, Frequency, Compat

#59444 Backport PR #59441 on branch 2.2.x (COMPAT: Fix numpy 2.1 timedelta * DateOffset)
  pandas/core/arrays/timedeltas.py
  pandas/tests/arithmetic/test_timedelta64.py
Labels: Numeric Operations, Timedelta, Frequency, Compat

#59443 REF (string dtype): de-duplicate _str_map methods
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
Labels: Strings

#59434 DOC: Update the usage of rtol and atol arguments
  pandas/_testing/asserters.py
Labels: Docs

#59446 DOC: Add SA01 for pandas.api.types.is_timedelta64_ns_dtype, pandas.api.types.is_period_dtype and pandas.api.types.is_numeric_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59449 Fix link to JSON TAB standard in pdeps
  web/pandas/pdeps/0012-compact-and-reversible-JSON-interface.md
Labels: Docs

#59448 String dtype: fix alignment sorting in case of python storage
  pandas/core/indexes/base.py
  pandas/tests/series/methods/test_align.py
Labels: Strings

#59450 DOC: fix ES01,PR07 for pandas.MultiIndex.get_loc_level
  ci/code_checks.sh
  pandas/core/indexes/multi.py
Labels: Docs

#59442 ENH: Raise TypeError instead of RecursionError when multiplying DateOffsets
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Error Reporting, Numeric Operations, Frequency

#59437 TST (string dtype): add test build with future strings enabled without pyarrow
  .github/actions/setup-conda/action.yml
  .github/workflows/unit-tests.yml
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/apply/test_numba.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arrays/boolean/test_arithmetic.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/arrays/categorical/test_constructors.py
  pandas/tests/arrays/integer/test_reduction.py
  pandas/tests/base/test_conversion.py
  pandas/tests/copy_view/test_astype.py
  pandas/tests/copy_view/test_functions.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/copy_view/test_replace.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/test_categorical.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_info.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/frame/methods/test_value_counts.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/frame/test_logical_ops.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/frame/test_unary.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/io/formats/style/test_bar.py
  pandas/tests/io/parser/conftest.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/series/test_reductions.py
  pandas/tests/window/test_rolling.py
Labels: CI, Strings

#59451 REF (string dtype): de-duplicate _str_map (2)
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings

#59397 DOC: Fix pandas.Series.str.index RT03
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Series, Accessors

#59409 BUG: Handle floating point boundaries in `qcut`
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/array_algos/quantile.py
  pandas/core/reshape/tile.py
  pandas/tests/reshape/test_qcut.py
Labels: cut

#59464 REF (string): de-duplicate str_map_nan_semantics
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings

#59398 ENH: pd.concat with keys and ignore_index=True should raise
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Enhancement, Reshaping, Error Reporting

#59071 DOC: More doc fix for dtype_backend
  pandas/core/dtypes/cast.py
  pandas/core/generic.py
  pandas/core/tools/numeric.py
  pandas/io/clipboards.py
  pandas/io/excel/_base.py
  pandas/io/feather_format.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/orc.py
  pandas/io/parquet.py
  pandas/io/parsers/readers.py
  pandas/io/spss.py
  pandas/io/sql.py
  pandas/io/xml.py
Labels: Docs, IO Data

#59474 DOC: Enforce Numpy Docstring Validation for pandas.Series.str methods
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Strings

#59479 BUG (string dtype): convert dictionary input to materialized string array in ArrowStringArray constructor
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/string_/test_string_arrow.py
Labels: Strings

#59486 Correct typo
  doc/source/development/contributing_docstring.rst
Labels: Docs

#59482 use x.com and twitter's new X logo
  web/pandas/_templates/layout.html
Labels: Web

#59470 String dtype: fix convert_dtypes() to convert NaN-string to NA-string
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/series/methods/test_convert_dtypes.py
Labels: Strings

#59467 DOC: Clarify nrows behavior in read_csv
  pandas/io/parsers/readers.py
Labels: Docs

#59490 STY: Add Yields section to option_context
  pandas/_config/config.py
Labels: Code Style

#59489 BUG: Fix out-of-bounds access in safe_sort with an empty array and non-empty codes
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/algorithms.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/test_sorting.py
Labels: Reshaping

#59484 DOC: Fix docstrings for Timestamp: tz_localize, tzname, utcfromtimestamp
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59089 DEPS: Make pytz an optional dependency
  .circleci/config.yml
  .github/workflows/unit-tests.yml
  ci/deps/actions-310-minimum_versions.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-311-arm64.yaml
  ci/meta.yaml
  doc/source/getting_started/install.rst
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v3.0.0.rst
  environment.yml
  pandas/__init__.py
  pandas/_libs/tslibs/conversion.pyx
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/_libs/tslibs/timezones.pyx
  pandas/_libs/tslibs/tzconversion.pyx
  pandas/compat/__init__.py
  pandas/compat/_optional.py
  pandas/compat/pyarrow.py
  pandas/conftest.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/dtypes/dtypes.py
  pandas/core/generic.py
  pandas/core/indexes/datetimes.py
  pandas/io/json/_table_schema.py
  pandas/tests/indexes/datetimes/methods/test_tz_localize.py
  pandas/tests/indexes/datetimes/test_constructors.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_timezones.py
  pandas/tests/io/test_parquet.py
  pandas/tests/scalar/timestamp/methods/test_round.py
  pandas/tests/scalar/timestamp/methods/test_tz_localize.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/methods/test_tz_localize.py
  pandas/tests/test_downstream.py
  pandas/tests/tseries/offsets/test_dst.py
  pandas/tests/tseries/offsets/test_offsets_properties.py
  pandas/tests/tslibs/test_tzconversion.py
  pandas/util/_print_versions.py
  pyproject.toml
  requirements-dev.txt
Labels: Timezones, Dependencies

#59491 DOC: add pandas-gbq and related db-dtypes packages to ecosystem
  web/pandas/community/ecosystem.md
Labels: Docs

#59496 DOC: Fix docstrings for Timestamp: unit, utcoffset, utctimetuple
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59485 DOC: fix PR02 for pandas.tseries.offsets.*
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#59463 REF: remove unused variable and checks
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/timedeltas.py
Labels: Refactor

#59505 BUG (string): ArrowEA comparisons with mismatched types
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/series/test_logical_ops.py
Labels: Numeric Operations, Arrow

#59392 ENH: Allow Iterable[Hashable] in drop_duplicates
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_drop_duplicates.py
Labels: Enhancement, duplicated

#59506 DOC: Docstrings for pandas.Series.str functions
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Strings

#59481 TST (string dtype): clean up construction of expected string arrays
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/xml/test_xml.py
Labels: Strings

#59509 TST (string dtype): fix IO dtype_backend tests for storage of str dtype of columns' Index
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/test_html.py
  pandas/tests/io/xml/test_xml.py
Labels: Strings

#59507 docs: Fix ES01, SA01 code check of `pandas.api.types.is_bool_dtype`
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59514 REF (string): Move StringArrayNumpySemantics methods to base class
  pandas/core/arrays/string_.py
Labels: Refactor, Strings

#59521 DOC: fix PR07,SA01 for pandas.MultiIndex.sortlevel
  ci/code_checks.sh
  pandas/core/indexes/multi.py
Labels: Docs

#59520 DOC: fix ES01,SA01 for pandas.MultiIndex.names
  ci/code_checks.sh
  pandas/core/indexes/multi.py
Labels: Docs

#59517 Fix docstrings for pandas.Period.month
  ci/code_checks.sh
  pandas/_libs/tslibs/period.pyx
Labels: Docs, Period

#59475 DOC: Enforce Numpy Docstring Validation for freqstr, nanos, and rule_code methods
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs, Timezones

#59515 REF (string): remove _str_na_value
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/strings/object_array.py
Labels: Refactor, Strings

#59501 REF (string): move ArrowStringArrayNumpySemantics methods to base class
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings

#59519 TST: Added test for date_range for bug GH#57456
  pandas/tests/indexes/datetimes/test_date_range.py
Labels: Needs Tests, datetime.date

#59525 Fix docstrings for pandas.Period.year SA01
  ci/code_checks.sh
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#59526 API (string): return str dtype for .dt methods, DatetimeIndex methods
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/extension.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/series/accessors/test_dt_accessor.py
Labels: Datetime, Strings

#59545 CI: Fix ci for numpy 2 failures
  pandas/plotting/_matplotlib/core.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Compat

#59550 Backport PR #59545 on branch 2.2.x (CI: Fix ci for numpy 2 failures)
  pandas/plotting/_matplotlib/core.py
  pandas/tests/io/test_parquet.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Compat

#56001 Fix get_datetimestruct_days overflow
  pandas/_libs/src/vendored/numpy/datetime/np_datetime.c
Labels: Internals

#59393 TST: Test non-nanosecond datetimes in PyArrow Parquet dataframes
  pandas/tests/io/test_parquet.py
Labels: Testing

#59539 DOC: Fixed bug number in what's new v3.0.0
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#59540 DOC: Fix Numpy Docstring validation errors in pandas.api.extensions.ExtensionArray
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#59533 Fix docstring timestamps#59458
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59296 BUG: `query` on columns with characters like # in its name
  .pre-commit-config.yaml
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/computation/parsing.py
  pandas/core/frame.py
  pandas/tests/frame/test_query_eval.py
Labels: Bug, expressions

#59553 CI: Uninstall nomkl & 32 bit Interval tests
  .github/actions/build_pandas/action.yml
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/interval/test_interval_new.py
Labels: Testing, CI, Compat, Interval, 32bit

#59569 DOC: Fix docstrings for Timestamp: strptime, timetz, to_datetime64, to_julian_date
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59573 PERF: avoid calling `DataFrame.dtypes` in loop
  pandas/core/generic.py
Labels: Performance

#59552 Series replace error
  pandas/core/generic.py
  pandas/tests/series/methods/test_replace.py
Labels: Error Reporting, Series

#59566 DOC: Clarify date_format usage in read_csv documentation specifically…
  pandas/io/parsers/readers.py
Labels: Docs

#59471 BUG: Handle nonexistent end dates when resampling
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_datetime_index.py
Labels: Bug, Timezones, Resample

#59478 String dtype: fix pyarrow-based IO + update tests
  pandas/io/_util.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_gcs.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
Labels: Strings, IO Parquet

#59574 BUG: Fix Ability to set both color and style in pandas plotting
  doc/source/whatsnew/v3.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame_color.py
Labels: Visualization

#59435 ENH: Add merge type validation on `pandas.merge`
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/merge.py
  pandas/tests/frame/methods/test_join.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Reshaping, Error Reporting

#59551 REF (string): avoid copy in StringArray factorize
  pandas/_libs/arrays.pyx
  pandas/_libs/hashtable.pyx
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/string_.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/window/test_rolling.py
Labels: Refactor, Strings

#59583 Use shorthand notation for pip config-settings
  .circleci/config.yml
  .github/actions/build_pandas/action.yml
  .github/workflows/unit-tests.yml
  .gitpod.yml
  README.md
  doc/source/development/contributing_environment.rst
  doc/source/development/debugging_extensions.rst
  doc/source/development/maintaining.rst
  pandas/__init__.py
Labels: Build

#59589 Clarify documentation for asfreq
  pandas/core/generic.py
Labels: Docs

#59602 DOCS: fix docstring validation errors for pandas.Series
  ci/code_checks.sh
  pandas/core/arrays/arrow/accessors.py
  pandas/core/arrays/sparse/array.py
  pandas/core/generic.py
  pandas/core/ops/docstrings.py
  pandas/core/series.py
Labels: Docs

#59591 Add example same correlation in pandas.Series.corr documentation
  pandas/core/series.py
Labels: Docs, cov/corr

#59590 DOC: Enforce Numpy Docstring Validation (Issue #59458)
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs, Timestamp

#59596 DOCS: fix docstring validation errors for pandas.Series
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Strings

#59558 MAINT: update vendored version util from packaging
  pandas/util/version/__init__.py
Labels: Dependencies

#59407 DOC: Enforce Numpy Docstring Validation | pandas.api.extensions.ExtensionArray
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#59597 DOCS: fix docstring validation errors for pandas.Series.str
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Strings

#59605 DOC: Fix Numpy Docstring errors in pandas.api.extensions.ExtensionArray
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#59599 DOC: add See Also section to groupby.DataFrameGroupBy.prod
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#59587 ENH: support Arrow PyCapsule Interface on Series for export
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/series.py
  pandas/tests/series/test_arrow_interface.py
Labels: Arrow

#59618 REF: Minimize operations in recode_for_groupby
  pandas/core/groupby/categorical.py
Labels: Refactor, Groupby, Categorical

#59546 BUG: allow None as name in multi-index during join
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/reshape/merge/test_join.py
Labels: Bug, Reshaping, MultiIndex

#59608 PERF: Performance Improvement on `DataFrame.to_csv()` when `index=False`
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/csvs.py
Labels: Performance, IO CSV

#59607 DOC: fix docstring validation errors for pandas.io.formats.style.Styler
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/io/formats/style.py
Labels: Docs

#59594 BUG: Fix for pandas.to_datetime reports incorrect index when failing
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/frame/test_block_internals.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tslibs/test_array_to_datetime.py
Labels: Bug, Datetime

#59610 String dtype: avoid surfacing pyarrow exception in binary operations
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/tests/arithmetic/test_object.py
  pandas/tests/arrays/boolean/test_arithmetic.py
  pandas/tests/arrays/floating/test_arithmetic.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/extension/base/ops.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/frame/test_logical_ops.py
  pandas/tests/frame/test_unary.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_logical_ops.py
Labels: Error Reporting, Strings, Arrow

#59622 DOC: Enforce Numpy Docstring Validation (Issue #59458)
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59621 DOC: fix docstring validation errors for pandas.Series
  ci/code_checks.sh
  pandas/core/generic.py
Labels: Docs

#56434 ENH: Enhancement for spss kwargs
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/spss.py
  pandas/tests/io/test_spss.py
Labels: IO Data, Stale

#59625 DOC: Add whatsnew for 2.3.0
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.3.0.rst
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#59628 BUG (string): str.replace with negative n
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_arrow.py
Labels: Strings

#59630 PERF: avoid unnecessary copy
  pandas/core/arrays/string_.py
Labels: Performance, Strings

#59633 DOC: fix docstring validation errors for pandas.Series
  ci/code_checks.sh
  pandas/core/arrays/sparse/accessor.py
Labels: Docs

#59638 DOC: fix docstring validation errors for pandas.PeriodIndex
  ci/code_checks.sh
  pandas/core/arrays/period.py
  pandas/core/indexes/period.py
Labels: Docs

#59634 DOC: fix docstring validation errors for pandas.core.window
  ci/code_checks.sh
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Docs

#59626 REF (string): rename result converter methods
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
Labels: Strings

#59598 PERF: Improve efficiency of `BlockValuesRefs`
  pandas/_libs/internals.pyx
Labels: Enhancement, Performance, Copy / view semantics

#59611 Doc/59592/fix docstring validation errors
  ci/code_checks.sh
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/multi.py
Labels: Docs

#59643 PERF: Improve efficiency of `BlockValuesRefs._clear_dead_references(...)`
  pandas/_libs/internals.pyx
Labels: Performance, Copy / view semantics

#59642 TST (string) fix xfailed groupby tests (3)
  pandas/tests/groupby/methods/test_describe.py
  pandas/tests/groupby/methods/test_nth.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Testing, Strings

#59644 Docstring timestamps#59458
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59568 REF (string): de-duplicate str_endswith, startswith
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings

#59651 Fixed Typos #59640
  pandas/tests/io/parser/test_network.py
  pandas/tests/plotting/test_hist_method.py
  web/pandas/index.html
Labels: Clean

#59658 DOC: fix RT03,SA01,ES01 for pandas.MultiIndex.reorder_levels
  ci/code_checks.sh
  pandas/core/indexes/multi.py
Labels: Docs

#59661 DOC: fix SA01,ES01 for pandas.Period.freqstr
  ci/code_checks.sh
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#59660 DOC: fix SA01,ES01 for pandas.NaT
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
Labels: Docs

#59663 DOC: Remove unnecessary parentheses in `:func:` & `:meth:` role
  doc/source/user_guide/visualization.rst
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v0.15.1.rst
  doc/source/whatsnew/v0.21.0.rst
  doc/source/whatsnew/v0.21.1.rst
  doc/source/whatsnew/v0.23.0.rst
  doc/source/whatsnew/v0.23.1.rst
  doc/source/whatsnew/v0.24.0.rst
  doc/source/whatsnew/v0.24.2.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v1.1.0.rst
  doc/source/whatsnew/v1.2.1.rst
  doc/source/whatsnew/v1.3.0.rst
  doc/source/whatsnew/v1.4.0.rst
Labels: Docs

#59619 REF: Use range over arange for iterators
  pandas/core/generic.py
  pandas/core/indexing.py
Labels: Refactor

#59669 fix typo
  doc/source/user_guide/io.rst
Labels: Docs

#59615 DEPR (string): non-bool na for obj.str.contains
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/string_arrow.py
  pandas/core/strings/object_array.py
  pandas/tests/strings/test_find_replace.py
Labels: Strings, Deprecate

#59648 TST: Add SparseArray _arith_method test to fail on incorrect comparison operator
  pandas/tests/arrays/sparse/test_arithmetics.py
Labels: Testing, Sparse

#59673 DOC: fix PR01,SA01 for pandas.Period.strftime
  ci/code_checks.sh
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#59674 DOC: fix SA01 for pandas.PeriodDtype
  ci/code_checks.sh
  pandas/core/dtypes/dtypes.py
Labels: Docs

#59675 DOC: fix PR07 for pandas.RangeIndex
  ci/code_checks.sh
  pandas/core/indexes/range.py
Labels: Docs

#59679 DOC: fix PR01,SA01,ES01 for pandas.errors.AbstractMethodError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs
