Repository pandas-dev/pandas, pull requests merged in 2024-06, with the labels that each got.

#58877 DOC: fix PR07,SA01 for pandas.util.hash_array
  ci/code_checks.sh
  pandas/core/util/hashing.py
Labels: Docs

#58878 DOC: fix PR02 for pandas.tseries.offsets.YearEnd
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#58879 DOC: fix SA01 for pandas.timedelta_range
  ci/code_checks.sh
  pandas/core/indexes/timedeltas.py
Labels: Docs

#58881 DOC: fix SA01 for pandas.test
  ci/code_checks.sh
  pandas/util/_tester.py
Labels: Docs

#58882 DOC: fix SA01 for pandas.set_option
  ci/code_checks.sh
  pandas/_config/config.py
Labels: Docs

#58883 DOC: fix SA01 for pandas.read_sas
  ci/code_checks.sh
  pandas/io/sas/sasreader.py
Labels: Docs

#58884 DOC: fix SA01 for pandas.read_feather
  ci/code_checks.sh
  pandas/io/feather_format.py
Labels: Docs

#58885 DOC: fix SA01 for pandas.plotting.plot_params
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#58887 DOC: fix PR07 for pandas.unique
  ci/code_checks.sh
  pandas/core/algorithms.py
Labels: Docs

#58888 DOC: fix PR07,SA01 for pandas.testing.assert_series_equal
  ci/code_checks.sh
  pandas/_testing/asserters.py
Labels: Docs

#58889 DOC: fix SA01 for pandas.show_versions
  ci/code_checks.sh
  pandas/util/_print_versions.py
Labels: Docs

#58890 DOC: fix SA01 for pandas.reset_option
  ci/code_checks.sh
  pandas/_config/config.py
Labels: Docs

#58891 DOC: fix SA01 for pandas.read_orc
  ci/code_checks.sh
  pandas/io/orc.py
Labels: Docs

#58894 DOC: fix PR07,RT03,SA01 for pandas.plotting.parallel_coordinates
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#58895 DOC: fix RT03,SA01 for pandas.plotting.autocorrelation_plot
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#58897 DOC: fix SA01 for pandas.option_context
  ci/code_checks.sh
  pandas/_config/config.py
Labels: Docs

#58902 Removed duplicated description of cumsum and cumprod methods
  doc/source/user_guide/missing_data.rst
Labels: Docs

#58886 BUG: Check `min_periods` before applying the function
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/window/numba_.py
  pandas/tests/window/test_numba.py
Labels: Bug, Apply, Window, numba

#58555 ENH: Restore support for reading Stata 104 format dta files, and add support for 103
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/data/stata/stata-compat-103.dta
  pandas/tests/io/data/stata/stata-compat-104.dta
  pandas/tests/io/data/stata/stata-compat-be-103.dta
  pandas/tests/io/data/stata/stata-compat-be-104.dta
  pandas/tests/io/data/stata/stata4_103.dta
  pandas/tests/io/data/stata/stata4_104.dta
  pandas/tests/io/test_stata.py
Labels: IO Stata

#58758 CLN: Stopped object inference in constructors for pandas objects
  doc/source/whatsnew/v3.0.0.rst
  pandas/_testing/__init__.py
  pandas/core/construction.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/internals/construction.py
  pandas/core/series.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/base_class/test_constructors.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/methods/test_equals.py
  pandas/tests/series/test_constructors.py
  pandas/tests/tseries/frequencies/test_inference.py
Labels: Dtype Conversions, Clean

#58804 REF: Remove BlockManager.arrays in favor of BlockManager.blocks usage
  pandas/_testing/__init__.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/internals/managers.py
  pandas/tests/apply/test_str.py
  pandas/tests/extension/base/casting.py
  pandas/tests/extension/base/constructors.py
  pandas/tests/extension/base/getitem.py
  pandas/tests/extension/base/reshaping.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_shift.py
  pandas/tests/frame/methods/test_values.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/indexing/test_setitem.py
Labels: Internals, Clean

#58732 Dep groupby corrwith
  doc/source/whatsnew/v3.0.0.rst
  pandas/conftest.py
  pandas/core/groupby/generic.py
  pandas/tests/groupby/test_all_methods.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_numeric_only.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Deprecate

#57754 DEPR: make_block
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/internals/api.py
  pandas/io/feather_format.py
  pandas/io/parquet.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/internals/test_api.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/test_parquet.py
Labels: Internals, Deprecate

#58919 Proofreading/editing Getting Started for readability. Attempt 2, this time without extra files.
  doc/source/getting_started/index.rst
Labels: Docs

#58917 DOC: fix RT03,SA01 for pandas.bdate_range
  ci/code_checks.sh
  pandas/core/indexes/datetimes.py
Labels: Docs

#58914 DOC: fix SA01 for pandas.describe_option
  ci/code_checks.sh
  pandas/_config/config.py
Labels: Docs

#58896 DOC: fix PR07 for pandas.pivot_table
  ci/code_checks.sh
  pandas/core/reshape/pivot.py
Labels: Docs

#58908 CI: Update CircleCI configs
  .circleci/config.yml
  .circleci/setup_env.sh
  ci/deps/circle-311-arm64.yaml
Labels: CI, ARM

#58905 CLN: Plotting tests
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/plotting/test_misc.py
  pandas/tests/plotting/test_series.py
  pandas/tests/plotting/test_style.py
Labels: Testing, Visualization

#58910 CLN: Plotting tests 2
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/plotting/test_converter.py
  pandas/tests/plotting/test_hist_method.py
Labels: Testing, Visualization

#58452 Update compute_dict_like to get all columns
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Groupby, Apply

#58921 CLN: Matplotlib imports in style
  pandas/io/formats/style.py
Labels: Visualization, Clean, Styler

#58923 CLN: Remove downcast keyword in MultiIndex.fillna
  pandas/core/indexes/multi.py
Labels: MultiIndex, Clean

#58864 BUG/df.agg-with-df-with-missing-values-results-in-IndexError
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/apply.py
  pandas/tests/groupby/aggregate/test_aggregate.py
Labels: Bug, Apply

#58934 DOC: fix SA01 for pandas.read_spss
  ci/code_checks.sh
  pandas/io/spss.py
Labels: Docs

#58935 DOC: fix PR07 for pandas.pivot
  ci/code_checks.sh
  pandas/core/reshape/pivot.py
Labels: Docs

#58936 DOC: fix PR07 for pandas.merge_ordered
  ci/code_checks.sh
  pandas/core/reshape/merge.py
Labels: Docs

#58947 DOC: correct examples for Resample a time series for clarity
  doc/source/getting_started/intro_tutorials/09_timeseries.rst
  doc/source/user_guide/timeseries.rst
Labels: Docs

#58805 REF: Make _slice_take_blocks_ax0 a generator
  pandas/core/internals/managers.py
Labels: Internals, Clean

#58163 DOC: Add notes to nullable types documentation about pd.NA column type
  doc/source/user_guide/boolean.rst
  doc/source/user_guide/integer_na.rst
Labels: Docs, Missing-data, NA - MaskedArrays

#58893 ENH: Add **kwargs to pivot_table to allow the specification of aggfunc keyword arguments #57884
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Enhancement, Reshaping

#58953 DOC: minor grammar fix "en -> and"
  pandas/core/series.py
Labels: Docs

#57986 CLN: enforce deprecation of frequencies deprecated for offsets
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/frame/methods/test_asfreq.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/datetimes/test_datetime.py
  pandas/tests/indexes/period/methods/test_asfreq.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Frequency, Clean

#58937 REF/CLN: Standardized matplotlib imports
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/__init__.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/misc.py
  pandas/plotting/_matplotlib/style.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/io/formats/style/test_matplotlib.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_color.py
  pandas/tests/plotting/frame/test_frame_legend.py
  pandas/tests/plotting/test_converter.py
Labels: Visualization, Clean

#58957 DOC: fix PR07,SA01 for pandas.qcut
  ci/code_checks.sh
  pandas/core/reshape/tile.py
Labels: Docs

#58961 Fix link wording in "10 Minutes to Pandas"
  doc/source/user_guide/10min.rst
Labels: Docs

#57494 BUG: DateTimeIndex.is_year_start unexpected behavior when constructed with freq 'MS' date_range (#57377)
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/fields.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
Labels: Frequency

#58691 TST: add tests for DatetimeIndex.is_year_start/is_quarter_start on "BMS" frequency
  pandas/tests/indexes/datetimes/test_scalar_compat.py
Labels: Testing, Frequency

#58640 BUG: Unable to open Stata 118 or 119 format files saved in big-endian…
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/data/stata/stata12_118.dta
  pandas/tests/io/data/stata/stata12_119.dta
  pandas/tests/io/data/stata/stata12_be_117.dta
  pandas/tests/io/data/stata/stata12_be_118.dta
  pandas/tests/io/data/stata/stata12_be_119.dta
  pandas/tests/io/data/stata/stata14_119.dta
  pandas/tests/io/data/stata/stata14_be_118.dta
  pandas/tests/io/data/stata/stata14_be_119.dta
  pandas/tests/io/data/stata/stata16_119.dta
  pandas/tests/io/data/stata/stata16_be_118.dta
  pandas/tests/io/data/stata/stata16_be_119.dta
  pandas/tests/io/test_stata.py
Labels: IO Stata

#58951 DOC: added see also to docstrings in mean and median
  ci/code_checks.sh
  pandas/core/generic.py
Labels: Docs

#58968 DOC: Update typo in missing_data.rst
  doc/source/user_guide/missing_data.rst
Labels: Docs

#58970 BUG: byteorder option in to_stata is not honoured when writing strL data
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata

#58976 DOC: fix SA01 for pandas.MultiIndex.nlevels
  ci/code_checks.sh
  pandas/core/indexes/multi.py
Labels: Docs

#58979 DOC: fix PR07 for pandas.merge
  ci/code_checks.sh
  pandas/core/reshape/merge.py
Labels: Docs

#58767 ENH add *args support for numba apply
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/_numba/executor.py
  pandas/core/apply.py
  pandas/core/util/numba_.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/window/test_numba.py
Labels: Enhancement, Apply, numba

#58975 DOC: add examples to clarify the behavior of `is_year_start` for business offsets
  pandas/core/arrays/datetimes.py
Labels: Docs

#58793 Fix : #58748 BUG: eval fails for ExtensionArray
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/computation/ops.py
  pandas/tests/frame/test_query_eval.py
Labels: Bug, ExtensionArray, expressions

#58992 PERF: cache plotting date locators for DatetimeIndex plotting
  pandas/plotting/_matplotlib/converter.py
Labels: Visualization, Performance

#59002 Backport PR #58992 on branch 2.2.x (PERF: cache plotting date locators for DatetimeIndex plotting)
  pandas/plotting/_matplotlib/converter.py
Labels: Visualization, Performance

#59011 WEB: Correctly link to PR
  web/pandas/pdeps/0001-purpose-and-guidelines.md
Labels: Web

#58984 BUG: Fix issue with negative labels in `group_cumsum`
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/groupby.pyx
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Reduction Operations

#58958 PERF: Only copy in plotting when needed
  pandas/plotting/_core.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Visualization, Performance

#58960 PERF: Use shallow copies/defer copies in io
  pandas/io/json/_json.py
  pandas/io/json/_table_schema.py
  pandas/io/sql.py
Labels: IO Data, Performance

#58972 PERF: Use reshape instead of ravel/flatten
  pandas/core/arrays/arrow/array.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/reshape/reshape.py
Labels: Performance, Code Style

#59013 CI: remove xfail in test_to_xarray_index_types
  pandas/tests/generic/test_to_xarray.py
Labels: Testing

#59015 Backport PR #59013 on branch 2.2.x (CI: remove xfail in test_to_xarray_index_types )
  pandas/tests/generic/test_to_xarray.py
Labels: Testing

#59017 Change link from NEP 29 to SPEC 0 for Numpy Guidelines
  doc/source/development/policies.rst
Labels: Docs

#59033 DOC: update the documentation for Timestamp: add to parameters the missing unit 'W' and an example
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59025 PREF: Fix regression from #58984
  pandas/_libs/groupby.pyx
Labels: Groupby, Performance

#59030 DOC: fix SA01 for pandas.Timedelta.as_unit
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59029 DOC: fix SA01 for pandas.NamedAgg
  ci/code_checks.sh
  pandas/core/groupby/generic.py
Labels: Docs

#59034 CLN: BaseGrouper
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/tests/test_sorting.py
Labels: Groupby, Clean

#59044 DOC: fix PR07,RT03 for pandas.merge_asof
  ci/code_checks.sh
  pandas/core/reshape/merge.py
Labels: Docs

#59040 DOC: fix typos in User Guide
  doc/source/user_guide/basics.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/missing_data.rst
  doc/source/user_guide/options.rst
  doc/source/user_guide/timeseries.rst
Labels: Docs

#58052 BUG: fixed Series.dt methods in ArrowDtype class that were returning incorrect values #57355
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Timedelta, Arrow

#59035 REF: Use `default_index` or preserve original Index type for empty-like results
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/indexes/api.py
  pandas/core/internals/managers.py
  pandas/core/methods/selectn.py
  pandas/core/reshape/reshape.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/generic/test_generic.py
  pandas/tests/indexes/test_base.py
  pandas/tests/series/methods/test_get_numeric_data.py
Labels: Refactor, Index

#59018 Fix wrong save of datetime64[s] in HDFStore
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_round_trip.py
Labels: IO HDF5, Non-Nano

#59047 DOC: Fix diction: "e.g." -> "i.e."
  pandas/io/html.py
Labels: Docs

#59061 DOC: Typo in missing_data.rst
  doc/source/user_guide/missing_data.rst
Labels: Docs

#59068 DOC: fix SA01 for pandas.Timedelta.days
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59067 DOC: add SA01 for pandas.Series.ge
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#59056 DOC: Correct typo in pandas.pivot_table doc
  pandas/core/reshape/pivot.py
Labels: Docs

#59051 DEPR: deprecate units 'w', 'd', 'MS', 'US', 'NS' for Timedelta in favor of 'W', 'D', 'ms', 'us', 'ns'
  doc/source/user_guide/timedeltas.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/dtypes.pxd
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/accessors.py
  pandas/core/tools/timedeltas.py
  pandas/tests/frame/indexing/test_mask.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/indexes/timedeltas/methods/test_shift.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/indexes/timedeltas/test_delete.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexes/timedeltas/test_setops.py
  pandas/tests/indexing/test_categorical.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/scalar/timedelta/test_formats.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_isin.py
  pandas/tests/series/methods/test_nlargest.py
  pandas/tests/tools/test_to_timedelta.py
  pandas/tests/window/test_rolling.py
Labels: Timedelta, Deprecate

#59021 DOC: Change `to_numeric`'s `dtype_backend` default doc
  pandas/core/tools/numeric.py
Labels: Docs

#59070 DOC: fix SA01 for pandas.Timestamp.floor
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59080 BUG: Fix read_csv raising TypeError when iterator and nrows are specified without chunksize
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_iterator.py
Labels: IO CSV

#59037 BUG: DatetimeIndex.union with non-nano
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/datetimelike.py
  pandas/tests/indexes/datetimes/test_setops.py
Labels: setops, Non-Nano

#58967 DEPR: Change version to 4.0 in deprecate decorators
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/io/formats/test_to_markdown.py
  pandas/tests/io/formats/test_to_string.py
Labels: Clean

#59046 TST: Fix some test builds for numpy 2.0
  ci/deps/actions-311-pyarrownightly.yaml
  pandas/compat/__init__.py
  pandas/compat/numpy/__init__.py
  pandas/compat/pyarrow.py
  pandas/core/dtypes/cast.py
  pandas/tests/indexes/datetimelike_/test_indexing.py
  pandas/tests/io/test_parquet.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/tools/test_to_datetime.py
Labels: Testing, CI, Compat

#59086 Backport PR #59046: TST: Fix some test builds for numpy 2.0
  ci/deps/actions-311-pyarrownightly.yaml
  pandas/compat/__init__.py
  pandas/compat/numpy/__init__.py
  pandas/compat/pyarrow.py
  pandas/core/dtypes/cast.py
  pandas/tests/indexes/datetimelike_/test_indexing.py
  pandas/tests/io/test_parquet.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/tools/test_to_datetime.py
Labels: Compat

#59085 CI: Clean GHA files
  .github/actions/build_pandas/action.yml
  .github/actions/run-tests/action.yml
  .github/workflows/unit-tests.yml
Labels: CI

#59065 ENH: Fix Python 3.13 test failures & enable CI
  .github/workflows/unit-tests.yml
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/groupby/test_groupby.py
  pandas/tests/io/parser/test_dialect.py
  pandas/tests/io/test_common.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
Labels: CI

#59073 DOC: document default behaviour of `sample` methods when `random_state = None`
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
Labels: Docs

#59097 DOC: fix SA01, ES01 for pandas.Timestamp.tz
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59094 BUG: Fix sparse doctests for SciPy 1.14.0
  pandas/core/arrays/sparse/accessor.py
Labels: Docs

#59081 ENH: Add option to only merge column header cells in `ExcelFormatter`.
  doc/source/whatsnew/v3.0.0.rst
  pandas/_typing.py
  pandas/io/formats/excel.py
  pandas/io/formats/style.py
  pandas/tests/io/excel/test_writers.py
Labels: IO Excel

#59090 DOC: Fix typo in `StylerRenderer.format` docstring
  pandas/io/formats/style_render.py
Labels: Docs

#59104 Backport PR #59094 on branch 2.2.x (BUG: Fix sparse doctests for SciPy 1.14.0)
  pandas/core/arrays/sparse/accessor.py
Labels: Docs

#59103 RT03 fix in pandas.Series.pop docstring.
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#59102 Added a test for the groupby MultiIndex with codes
  pandas/tests/groupby/test_groupby.py
Labels: Testing, Groupby, MultiIndex

#59101 TST: .loc dtype change bug
  pandas/tests/dtypes/test_dtypes.py
Labels: Testing

#59069 Fix insertion of None value in MultiIndex
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/test_multilevel.py
Labels: Missing-data, MultiIndex

#58959 PERF: Use shallow copies/remove unnecessary copies in reshaping
  pandas/core/reshape/melt.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
Labels: Reshaping, Copy / view semantics

#58994 BUG: True cannot be cast to bool in read_excel
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/boolean.py
  pandas/io/parsers/base_parser.py
  pandas/tests/io/data/excel/test_boolean_types.xlsx
  pandas/tests/io/data/excel/test_none_type.xlsx
  pandas/tests/io/excel/test_readers.py
Labels: IO Excel

#58270 CLN: enforce deprecation of the Series[categorical].replace special-casing
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/core/internals/blocks.py
  pandas/tests/arrays/categorical/test_replace.py
  pandas/tests/copy_view/test_replace.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Categorical, Clean, replace

#59083 DEPR: replace for Timedelta deprecated unit 'd' with 'D' in benchmarks
  asv_bench/benchmarks/tslibs/timedelta.py
Labels: Benchmark

#58232 CLN: enforce the deprecation of the `Series.argsort` NA behavior
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/series.py
  pandas/tests/extension/base/methods.py
  pandas/tests/series/methods/test_argsort.py
Labels: Clean

#59058 CI: Set up CI for the free-threaded build of 3.13
  .github/workflows/unit-tests.yml
Labels: CI

#59109 CI: Keep GIL disabled in free-threading CI
  .github/workflows/unit-tests.yml
Labels: CI

#59113 DOC: fix Raises TypeError if any kind of string dtype is passed in
  pandas/core/frame.py
Labels: Docs

#59064 BUG: `DataFrame.sparse.from_spmatrix` hard codes an invalid ``fill_value`` for certain subtypes
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/sparse/accessor.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/missing.py
  pandas/tests/arrays/sparse/test_accessor.py
  pandas/tests/dtypes/test_missing.py
  pandas/tests/indexing/test_loc.py
Labels: Sparse

#59117 CI: Modify the trailing-whitespace hook to preserve markdown hard linebreaks
  .pre-commit-config.yaml
Labels: Code Style

#59075 BUG: Add type check for encoding_errors in pd.read_csv
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/test_common.py
Labels: Error Reporting, IO CSV

#59108 DOC: Update warning message in pandas.eval function
  pandas/core/computation/eval.py
Labels: Docs

#59127 DOC: json_normalize breaking changes in pandas 3.0.0
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#59119 CLN: unify a ValueError message for removed units T, L, U, N and remove these entries from UnitChoices
  pandas/_libs/tslibs/dtypes.pyx
  pandas/_libs/tslibs/timedeltas.pyi
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/tests/tslibs/test_resolution.py
Labels: Clean

#59123 BUG: chokes on pd.DatetimeTZDtype if there are no rows.
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/reshape.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping, ExtensionArray
