Repository pandas-dev/pandas, pull requests merged in 2024-12, with the labels that each got.

#60444 Fix indices docstrings, DataFrameGroupBy, SeriesGroupBy, Resampler
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby, Resample

#60452 DOC: fix ES01 for pandas.set_option
  pandas/_config/config.py
Labels: Docs

#60449 DOC: fix SA01,ES01 for pandas.io.stata.StataWriter.write_file
  ci/code_checks.sh
  pandas/io/stata.py
Labels: Docs

#60447 DOC: fix SA01,ES01 for pandas.arrays.IntegerArray
  ci/code_checks.sh
  pandas/core/arrays/integer.py
Labels: Docs

#60446 DOC: Added missing links to optional dependencies in getting_started/install.html
  doc/source/getting_started/install.rst
Labels: Docs

#60442 DOC: fix SA01,ES01 for pandas.errors.IntCastingNaNError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#60441 DOC: fix SA01,ES01 for pandas.infer_freq
  ci/code_checks.sh
  pandas/tseries/frequencies.py
Labels: Docs

#60463 BUG: Fix keyerror bug when indexing multiindex columns with NaT values
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/test_multilevel.py
Labels: Indexing, Missing-data

#60465 BUG: Maintain column order in table method rolling
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/window/rolling.py
  pandas/tests/window/test_numba.py
Labels: Bug, Apply, Window

#60464 BUG: Fix pd.read_html handling of rowspan in table header
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/html.py
  pandas/tests/io/test_html.py
Labels: Bug, IO HTML

#60476 BUG: Fix stata bug post pre-commit update
  pandas/io/stata.py
Labels: IO Stata

#60461 PERF: improve construct_1d_object_array_from_listlike
  pandas/core/dtypes/cast.py
Labels: Performance, Constructors

#60481 DOC: Fix some docstring validations in pd.Series
  ci/code_checks.sh
  pandas/core/arrays/datetimelike.py
Labels: Docs

#60474 DOC: DataFrameGroupBy.idxmin() returns DataFrame, documentation says Serie
  pandas/core/groupby/generic.py
Labels: Docs, Groupby

#60483 Backport PR #60461 on branch 2.3.x (PERF: improve construct_1d_object_array_from_listlike)
  pandas/core/dtypes/cast.py
Labels: Performance, Constructors

#60457 DOC: Examples added for float_format in to_csv documentation
  pandas/core/generic.py
Labels: Docs

#60459 BUG: ValueError when printing a DataFrame with DataFrame in its attrs
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting, metadata

#60468 FIX : Missing 'pickleshare' package when running 'sphinx-build' command
  environment.yml
  requirements-dev.txt
Labels: Build, Docs

#60475 DOC: Fix docstrings errors SEM and GET_GROUP
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#60507 doc: update dsintro.rst to remove a warring
  doc/source/user_guide/dsintro.rst
Labels: Docs

#60505 BUG: Fix bug in GroupBy that ignores group_keys arg for empty datafra…
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/generic.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/test_all_methods.py
  pandas/tests/groupby/test_grouping.py
Labels: Groupby, Apply

#60516 DOC: Fix hyperlinks to NumPy methods in DataFrame.shape / DataFrame.ndim
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#60525 Update frame.rst
  doc/source/reference/frame.rst
Labels: Docs

#60518 updated v to conv_val in that function
  pandas/core/computation/pytables.py
Labels: IO HDF5, Clean

#60527 BUG: Fix `ListAccessor` methods to preserve original name
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/accessors.py
  pandas/tests/series/accessors/test_list_accessor.py
Labels: Series, Arrow

#60526 DOC: Update variables a and b to names consistent with comment documentation
  pandas/core/computation/expressions.py
Labels: Clean, expressions

#60523 DOC: Fix docstrings for errors
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#60510 BUG: Fix float32 precision issues in pd.to_datetime
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Dtype Conversions

#60509 DOC: fix docstrings validation for pandas.core.groupby.DataFrameGroupBy.boxplot
  ci/code_checks.sh
  pandas/plotting/_core.py
Labels: Docs

#60541 FIX: ruff checks in expressions/pytables
  pandas/core/computation/expressions.py
  pandas/core/computation/pytables.py
Labels: Code Style

#60544 CI/TST: Use tm.external_error_raised for test_from_arrow_respecting_given_dtype_unsafe
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#60545 Backport PR #60544 on branch 2.3.x (CI/TST: Use tm.external_error_raised for test_from_arrow_respecting_given_dtype_unsafe)
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#60546 CI: Ignore prompting in test-arm when apt-get installing
  .circleci/config.yml
Labels: CI, ARM

#60547 CI: Ignore prompting in test-arm when apt-get installing
  .circleci/config.yml
Labels: CI, ARM

#60553 TST: filter possible RuntimeWarning in tests
  pandas/tests/extension/test_interval.py
  pandas/tests/frame/methods/test_to_numpy.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/interval/test_formats.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/reshape/test_cut.py
Labels: Warnings

#60555 Backport PR #60553: TST: filter possible RuntimeWarning in tests
  pandas/tests/extension/test_interval.py
  pandas/tests/frame/methods/test_to_numpy.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/interval/test_astype.py
  pandas/tests/indexes/interval/test_formats.py
  pandas/tests/indexes/interval/test_indexing.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/reshape/test_cut.py
Labels: Testing, Warnings

#60549 ENH: Support NamedAggs in kwargs in Rolling/Expanding/EWM agg method
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_groupby.py
Labels: Groupby, Window

#60565 CLN: Remove deprecations of groupby.fillna in tests
  pandas/tests/groupby/__init__.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_numeric_only.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Testing, Groupby, Deprecate, Clean

#60577 BUG: Fixed type annotations for read_sql_* functions.
  pandas/io/sql.py
Labels: IO SQL, Typing

#60574 BUG: fix ValueError when printing a Series with DataFrame in its attrs
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/format.py
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting, metadata

#60572 DOC: fix PR07,SA01,ES01 for pandas.plotting.scatter_matrix
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#60571 DOC: fix PR07,RT03,SA01,ES01 for pandas.io.json.build_table_schema
  ci/code_checks.sh
  pandas/io/json/_table_schema.py
Labels: Docs

#60570 DOC: fix PR01,SA01 for pandas.errors.UndefinedVariableError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#60512 DOC: Add hyperlink to ndarray.size in DataFrame.size docstring (#60368)
  pandas/core/generic.py
Labels: Docs

#60582 CI: Install nightly numpy on free threading build to avoid numpy 2.2.0 segfaults
  .github/workflows/unit-tests.yml
Labels: CI, Dependencies

#60543 DOC: fix deprecation message for `is_period_dtype`
  pandas/core/dtypes/common.py
Labels: Docs

#60183 String dtype (2.3.x): avoid downcasting object to string in fillna/where/interpolate
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/internals/blocks.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/series/methods/test_replace.py
Labels: Strings, Downcasting

#60566 DEPR: Enforce deprecation of include_groups in groupby.apply
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/window/test_groupby.py
Labels: Groupby, Deprecate, Apply

#60584 TST: Address matplotlib 3.10 deprecation of vert=
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Testing, Visualization

#60586 Backport PR #60584 on branch 2.3.x (TST: Address matplotlib 3.10 deprecation of vert=)
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/tools.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/test_boxplot_method.py
Labels: Testing, Visualization

#60588 DOC: Fix "kwargs" description for .assign()
  pandas/core/frame.py
Labels: Docs

#59125 PDEP-17: Backwards compatibility and deprecation policy
  web/pandas/pdeps/0017-backwards-compatibility-and-deprecation-policy.md
Labels: PDEP

#60598 DOC: Change Twitter to X in pandas maintenance
  doc/source/development/maintaining.rst
Labels: Docs

#60614 TST(string dtype): Resolve to_latex xfail
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_to_latex.py
Labels: Strings, IO LaTeX

#60615 TST(string dtype): Resolve some HDF5 xfails
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_subclass.py
  pandas/tests/io/test_common.py
Labels: IO HDF5, Strings

#60450 TST: Test .loc #25548 for matched and unmatched indices of Series
  pandas/tests/indexing/test_loc.py
Labels: Testing

#60619 TST/CLN: Remove groupby tests with mutation
  pandas/tests/groupby/test_apply_mutate.py
Labels: Testing, Groupby, Clean

#60620 TST/CLN: Improve some groupby.apply tests
  pandas/tests/groupby/test_apply.py
Labels: Testing, Groupby, Clean

#60617 Backport PR #60614 on branch 2.3.x (TST(string dtype): Resolve to_latex xfail)
  pandas/io/formats/style.py
  pandas/tests/io/formats/style/test_to_latex.py
Labels: Strings, IO LaTeX

#60623 DOC: Remove Blank cell in `doc/source/user_guide/visualization.rst`
  doc/source/user_guide/visualization.rst
Labels: Docs

#60626 Backport PR #60615: TST(string dtype): Resolve some HDF5 xfails
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_file_handling.py
  pandas/tests/io/pytables/test_subclass.py
  pandas/tests/io/test_common.py
Labels: IO HDF5, Strings

#60628 DOC: Make warning on query/eval consistent
  pandas/core/computation/eval.py
  pandas/core/frame.py
Labels: Docs, expressions

#60631 TST: Remove test_apply_mutate.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
Labels: Testing, Groupby, Apply
