Repository pandas-dev/pandas, pull requests merged in 2024-10, with the labels that each got.

#59782 BUG: groupby().any() returns true for groups with timedelta all NaT
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/ops.py
  pandas/tests/groupby/test_grouping.py
Labels: Bug, Groupby, Missing-data, Timedelta, Reduction Operations

#59939 CI: Run jobs on 2.3.x branch
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/package-checks.yml
  .github/workflows/unit-tests.yml
Labels: CI

#59940 Backport PR #59939 on branch 2.3.x (CI: Run jobs on 2.3.x branch)
  .github/workflows/code-checks.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/package-checks.yml
  .github/workflows/unit-tests.yml
Labels: CI

#59936 Backport PR #59912 on branch 2.3.x (CI: Pin micromamba to 1.x)
  .github/actions/setup-conda/action.yml
Labels: CI

#59911 DOC: Fix docstring of pandas.Series.compare list indent formatting
  pandas/core/shared_docs.py
Labels: Docs, Sprints

#59907 BUG: pd.eval with engine="numexpr" fails with float division
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/computation/align.py
  pandas/tests/computation/test_eval.py
Labels: expressions

#59930 BUG: fix html float display
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting

#59964 BUG: fix nbsp for html formatting
  pandas/io/formats/html.py
  pandas/tests/io/formats/test_format.py
Labels: Output-Formatting

#59966 BUG: fix treatment of NaNs when .apply() function is used on categorical columns.
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/apply.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_series_apply.py
Labels: Categorical, Apply

#59967 BUG: Fix SparseFrameAccessor.to_dense return type
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/sparse/accessor.py
  pandas/tests/arrays/sparse/test_accessor.py
Labels: Sparse, Subclassing

#59720 BUG: CSS strings truncated at ":"
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_style.py
Labels: Styler

#59958 DOC: fix RT03,SA01 for pandas.period_range
  ci/code_checks.sh
  pandas/core/indexes/period.py
Labels: Docs

#59962 DOC: fix SA01, ES01 for pandas.io.stata.StataReader.data_label
  ci/code_checks.sh
  pandas/io/stata.py
Labels: Docs

#59974 BUG: fix to_numeric raises TypeError for Timedelta and Timestamp scalar
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/tools/numeric.py
  pandas/tests/tools/test_to_numeric.py
Labels: Bug, Dtype Conversions, Timedelta, Timestamp

#59975 DOC: fix SA01, ES01 for pandas.testing.assert_extension_array_equal
  ci/code_checks.sh
  pandas/_testing/asserters.py
Labels: Docs

#59745 API: value_counts to consistently maintain order of input
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/tests/frame/methods/test_value_counts.py
  pandas/tests/groupby/methods/test_value_counts.py
Labels: Algos, API - Consistency

#59980 DOC: fix PR07,SA01,ES01 for pandas.Series.sparse.from_coo
  ci/code_checks.sh
  pandas/core/arrays/sparse/accessor.py
Labels: Docs

#59981 DOC: fix PR01,SA01,ES01 for pandas.api.types.is_float
  ci/code_checks.sh
  pandas/_libs/lib.pyx
Labels: Docs

#59982 DOC: fix SA01 for pandas.arrays.DatetimeArray
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs

#59983 DOC: fix SA01 for pandas.errors.SpecificationError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#59984 DOC: fix SA01 for pandas.errors.InvalidVersion
  ci/code_checks.sh
  pandas/util/version/__init__.py
Labels: Docs

#59986 DOC: Fix typos in plotting.table
  pandas/plotting/_misc.py
Labels: Docs

#59991 DOC: fix RT03,SA01,ES01 for pandas.io.stata.StataReader.value_labels
  ci/code_checks.sh
  pandas/io/stata.py
Labels: Docs

#59990 DOC: fix RT03,SA01,ES01 for pandas.plotting.lag_plot
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#59995 Typing: Added missing methods to `NaTType` stub
  pandas/_libs/tslibs/nattype.pyi
Labels: Missing-data, Typing

#59999 REGR: groupby.value_counts with all NA values
  pandas/core/groupby/ops.py
  pandas/tests/groupby/methods/test_value_counts.py
Labels: Bug, Groupby, Regression, Algos

#60000 Doc: Update docstring for `dummy_na` parameter
  pandas/core/reshape/encoding.py
Labels: Docs

#60002 Typing: More precise NaT stub
  pandas/_libs/tslibs/nattype.pyi
Labels: Missing-data, Typing

#60001 Fix Styler docstring
  pandas/io/formats/style.py
Labels: Docs, Styler

#60008 DOC: fix RT03,SA01,ES01 for pandas.io.stata.StataReader.variable_labels
  ci/code_checks.sh
  pandas/io/stata.py
Labels: Docs

#60011 DOC: fix SA01,ES01 for pandas.errors.CategoricalConversionWarning
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#59616 String dtype: propagate NaNs as False in predicate methods (eg .str.startswith)
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/strings/accessor.py
  pandas/core/strings/base.py
  pandas/core/strings/object_array.py
  pandas/tests/strings/test_api.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_string_array.py
  pandas/tests/strings/test_strings.py
Labels: API Design, Strings

#59686 TST (string dtype): resolve all infer_string TODO/xfails in pandas/tests/arrays
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/categorical/test_analytics.py
  pandas/tests/arrays/integer/test_reduction.py
Labels: Strings

#60015 Backport PR #59816 on branch 2.3.x (Bump pypa/cibuildwheel from 2.20.0 to 2.21.0)
  .github/workflows/wheels.yml
Labels: Build, CI, Dependencies

#60006 STY: Bump pyright, pyupgrade and mypy for new PEP-696 syntax
  .pre-commit-config.yaml
  environment.yml
  pandas/_config/config.py
  pandas/_config/localization.py
  pandas/_testing/_warnings.py
  pandas/_testing/contexts.py
  pandas/compat/pickle_compat.py
  pandas/core/apply.py
  pandas/core/arraylike.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/datetimes.py
  pandas/core/common.py
  pandas/core/computation/expr.py
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/interval.py
  pandas/core/indexes/multi.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/methods/to_dict.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/core/tools/datetimes.py
  pandas/core/window/rolling.py
  pandas/io/excel/_odswriter.py
  pandas/io/excel/_openpyxl.py
  pandas/io/excel/_xlsxwriter.py
  pandas/io/formats/css.py
  pandas/io/formats/format.py
  pandas/io/parsers/python_parser.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sql.py
  pandas/plotting/_matplotlib/converter.py
  pandas/plotting/_matplotlib/tools.py
  pandas/plotting/_misc.py
  pandas/tests/frame/test_ufunc.py
  pandas/tests/indexes/test_base.py
  pandas/util/_exceptions.py
  requirements-dev.txt
Labels: Code Style, Typing

#60021 DOC: Fix title capitalization in documentation files (#32550)
  doc/source/whatsnew/v0.12.0.rst
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#60036 DOC: fix SA01 for pandas.core.resample.Resampler.ohlc
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby, Resample

#60109 CI/TST: Update pyreadstat tests and pin xarray on CI
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/circle-311-arm64.yaml
  environment.yml
  pandas/tests/io/test_spss.py
  requirements-dev.txt
Labels: CI, Dependencies

#60033 DOC: fix RT03,SA01,ES01 for pandas.core.resample.Resampler.__iter__
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby, Resample

#60110 Backport PR #60109 on branch 2.3.x (CI/TST: Update pyreadstat tests and pin xarray on CI)
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  pandas/tests/io/test_spss.py
  requirements-dev.txt
Labels: CI, Dependencies

#60076 CLN: fix pre-commit stage names
  .pre-commit-config.yaml
Labels: CI, Code Style

#59900 ENH: Improve error mesage verbosity in string accessor
  pandas/core/strings/accessor.py
  pandas/tests/series/accessors/test_str_accessor.py
Labels: Enhancement, Error Reporting, Strings

#60031 DOC: fix SA01 for pandas.errors.OptionError
  ci/code_checks.sh
  pandas/_config/config.py
Labels: Docs

#60030 DOC: fix SA01 for pandas.errors.CSSWarning
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#60034 DOC: fix PR01,SA01,ES01 for pandas.api.types.is_integer
  ci/code_checks.sh
  pandas/_libs/lib.pyx
Labels: Docs

#60037 DOC: fix SA01,ES01 for pandas.core.resample.Resampler.sum
  ci/code_checks.sh
  pandas/core/resample.py
Labels: Docs

#60060 DOC: fix SA01,ES01 for pandas.tseries.offsets.SemiMonthBegin
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#60072 DOC: fix SA01 for pandas.errors.UnsupportedFunctionCall
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#60032 DOC: fix RT03,SA01,ES01 for pandas.json_normalize
  ci/code_checks.sh
  pandas/io/json/_normalize.py
Labels: Docs

#59751 DEPR: Update groupby.apply DeprecationWarning to FutureWarning
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/groupby/groupby.py
  pandas/core/resample.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_counting.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_groupby_subclass.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_resampler_grouper.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/window/test_groupby.py
Labels: Groupby, Apply, Warnings

#60029 Add information about code coverage to docs
  doc/source/development/contributing_codebase.rst
Labels: Docs

#60051 docs: add marimo to ecosystem.md
  web/pandas/community/ecosystem.md
Labels: Docs

#60058 DOC: Add Timedelta accepting float value
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs, Timedelta

#60089 BLD: relax meson/meson-python requirements
  pyproject.toml
Labels: Build, Python 3.13

#60125 Backport PR #60089 on branch 2.3.x (BLD: relax meson/meson-python requirements)
  pyproject.toml
Labels: Build, Python 3.13

#60117 TST (string dtype): duplicate pandas/tests/indexes/object tests specifically for string dtypes
  pandas/tests/indexes/object/test_astype.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/string/__init__.py
  pandas/tests/indexes/string/test_astype.py
  pandas/tests/indexes/string/test_indexing.py
Labels: Testing, Strings

#58694 DEPR: Change stacklevel to 2 in DataFrame(mgr) deprecation
  pandas/core/frame.py
Labels: Clean, Warnings

#60047 DOC: fix docstring of timedaltas.ceil
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#60135 DOC: fix RT03,SA01,ES01 for pandas.set_eng_float_format
  ci/code_checks.sh
  pandas/io/formats/format.py
Labels: Docs

#60142 DOC: fix PR07,SA01 for pandas.api.types.is_iterator
  ci/code_checks.sh
  pandas/_libs/lib.pyx
Labels: Docs

#60141 DOC: fix broken link on team webpage
  web/pandas/about/team.md
Labels: Web

#60130 BUG/TST (string dtype): fix and update tests for Stata IO
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Strings

#60103 DOC: to_latex braces in headers must be escaped (#60063)
  pandas/core/generic.py
Labels: Docs, IO LaTeX

#60121 PERF: faster _coerce_to_data_and_mask() for astype("Float64")
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/numeric.py
Labels: Performance, NA - MaskedArrays

#59972 DOC: Fix title capitalization in documentation files (#32550)
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/gotchas.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/integer_na.rst
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v1.0.2.rst
Labels: Docs

#60147 Backport PR #60035 on branch 2.3.x (Bump pypa/cibuildwheel from 2.21.0 to 2.21.3)
  .github/workflows/wheels.yml
Labels: Build, CI, Dependencies

#60143 CI/TST: fix parquet tz test returning pytz fixed offset (pyarrow 18)
  pandas/tests/io/test_parquet.py
Labels: CI, Compat

#60112 TST: Retyping of categorical column with NaN
  pandas/tests/dtypes/test_dtypes.py
Labels: Testing

#60144 CI: remove usage of legacy NPY_PROMOTION_STATE
  .github/workflows/unit-tests.yml
  ci/deps/actions-311-pyarrownightly.yaml
Labels: CI

#59875 TST: update frame method quantile tests
  pandas/tests/frame/methods/test_quantile.py
Labels: Strings

#59853 String dtype: implement sum reduction
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/array_algos/masked_reductions.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/series/test_reductions.py
Labels: Strings, Reduction Operations

#60133 TST (string dtype): update tests/reductions tests
  pandas/tests/reductions/test_reductions.py
Labels: Strings

#60150 CI: remove uninstall of nomkl
  .github/actions/build_pandas/action.yml
Labels: CI

#60158 Backport PR #60133 on branch 2.3.x (TST (string dtype): update tests/reductions tests)
  pandas/tests/reductions/test_reductions.py
Labels: Strings

#60156 BUG: Remove incorrect check on value label length
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Bug, IO Stata

#60152 String dtype: deprecate the pyarrow_numpy storage option
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/string_.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_string.py
Labels: Strings, Deprecate

#60118 BUG: preserve (object) dtype in factorize
  pandas/core/base.py
  pandas/tests/test_algos.py
Labels: Dtype Conversions, Algos

#60160 Backport PR #60150 on branch 2.3.x (CI: remove uninstall of nomkl)
  .github/actions/build_pandas/action.yml
Labels: CI

#58995 ENH: numba apply supports positional arguments passed as **kwargs
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/apply.py
  pandas/core/groupby/groupby.py
  pandas/core/util/numba_.py
  pandas/core/window/rolling.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/transform/test_numba.py
  pandas/tests/window/test_numba.py
Labels: Enhancement, Groupby, Apply, numba

#59910 CI: fix wrong syntax in CI env yml files (mamba 2.0 compat)
  .github/actions/setup-conda/action.yml
  ci/deps/actions-310-minimum_versions.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-311-arm64.yaml
  environment.yml
  scripts/generate_pip_deps_from_conda.py
Labels: CI
