Repository pandas-dev/pandas, pull requests merged in 2024-09, with the labels that each got.

#59672 REF: Use numpy methods instead of np.array
  pandas/core/array_algos/quantile.py
  pandas/core/arrays/_ranges.py
  pandas/core/dtypes/dtypes.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/multi.py
  pandas/core/tools/datetimes.py
  pandas/core/window/rolling.py
Labels: Refactor

#59678 TST (string dtype): fix and clean up arrow roundtrip tests
  pandas/tests/arrays/masked/test_arrow_compat.py
  pandas/tests/arrays/string_/test_string.py
Labels: Strings

#59624 API (string): str.center with pyarrow-backed string dtype
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/strings/test_case_justify.py
Labels: Strings

#59578 PERF: Only clear cached .levels when setting MultiIndex.names
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/multi.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
Labels: Performance, MultiIndex

#59403 DOC: Add 'See Also'and return value description for pandas.api.interchang.from_dataframe
  ci/code_checks.sh
  pandas/core/interchange/from_dataframe.py
Labels: Docs, Interchange

#59239 ENH: DataFrame.plot.scatter argument `c` now accepts a column of strings, where rows with the same string are colored identically
  doc/source/whatsnew/v3.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/frame/test_frame_color.py
Labels: Visualization

#59460 Fix obj arguments in assertions
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_frame_equal.py
  pandas/tests/util/test_assert_interval_array_equal.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Enhancement, Testing

#59701 Fix docstring timestamps (Issue #59458)
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#59705 REF (string): de-duplicate str_isfoo methods
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings

#59702 TST (string): copy/view tests
  pandas/core/dtypes/dtypes.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_functions.py
  pandas/tests/copy_view/test_internals.py
  pandas/tests/dtypes/test_dtypes.py
Labels: Testing, Strings

#59699 Changed to GroupBy
  pandas/core/groupby/groupby.py
Labels: Docs

#59703 TST (string): more targeted xfails in test_string.py
  pandas/tests/extension/test_string.py
Labels: Testing, Strings

#59707 Fix part of docstring timedelta index#59698
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59647 PERF: CategoricalDtype.update_dtype
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/dtypes/dtypes.py
Labels: Performance, Categorical

#59708 TST: Update BooleanArray _logical_method test to fail on incorrect length comparison operator
  pandas/tests/arrays/boolean/test_logical.py
Labels: Testing

#59709 REF (string): de-duplicate _str_contains
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings

#59713 DOC: Fix some docstring validation errors #59698
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/timedeltas.py
Labels: Docs

#59562 BUG (string): ArrowStringArray.find corner cases
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_arrow.py
Labels: Strings

#59730 DOC: fix SA01 for pandas.Period.to_timestamp
  ci/code_checks.sh
  pandas/_libs/tslibs/period.pyx
Labels: Docs

#59733 DOC: fix SA01,ES01 for pandas.Timedelta.view
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59682 String dtype: implement _get_common_dtype
  pandas/core/arrays/string_.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/string_/test_concat.py
Labels: Strings

#59735 DOC: move `idxmin` and `idxmax` docs from core/shared_docs.py to core/frame.py
  pandas/core/frame.py
  pandas/core/shared_docs.py
Labels: Docs

#59723 Resolves #59670 by documenting that DataFrame.from_records()'s columns filters (includes) data.
  pandas/core/frame.py
Labels: Docs

#59549 Missing source link
  pandas/core/frame.py
Labels: Docs

#59629 BUG: Fix inconsistent pivot table subaggregation when index is None
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/pivot.py
  pandas/tests/reshape/test_pivot.py
Labels: Bug, Reshaping

#59544 TST/BUG (string dtype): Fix and adjust indexes string tests
  pandas/core/construction.py
  pandas/core/indexes/base.py
  pandas/tests/indexes/base_class/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_old_base.py
Labels: Strings

#59541 TST (string dtype): Adjust indexing string tests
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_indexing.py
  pandas/tests/indexing/test_loc.py
Labels: Strings

#59762 TST (string dtype): adjust pandas/tests/reshape tests
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/merge/test_merge_asof.py
  pandas/tests/reshape/test_get_dummies.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/reshape/test_pivot.py
Labels: Strings

#59747 TST: Update IntervalArray min/max test to fail on changed default skipna
  pandas/tests/arrays/interval/test_interval.py
Labels: Testing

#59742 DOCS: fix docstring validation errors for groupby.DataFrameGroupBy.filter, groupby.SeriesGroupBy.filter
  ci/code_checks.sh
  pandas/core/groupby/generic.py
Labels: Docs

#59729 DOC: fix SA01,ES01 for pandas.RangeIndex.stop
  ci/code_checks.sh
  pandas/core/indexes/range.py
Labels: Docs

#59728 DOC: fix SA01,ES01 for pandas.RangeIndex.start
  ci/code_checks.sh
  pandas/core/indexes/range.py
Labels: Docs

#59683 fix: use fastpath for PyCapsule export when starting from pyarrow-backed Series, respect requested_schema
  pandas/core/series.py
  pandas/tests/series/test_arrow_interface.py
Labels: Arrow

#59756 BUG (string dtype): fix inplace mutation with copy=False in ensure_string_array
  pandas/_libs/lib.pyx
  pandas/tests/copy_view/test_astype.py
  pandas/tests/libs/test_lib.py
Labels: Bug, Strings

#59758 TST (string dtype): remove usage of 'string[pyarrow_numpy]' alias
  pandas/conftest.py
  pandas/tests/apply/test_numba.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/base/test_misc.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/groupby/methods/test_size.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/indexes/base_class/test_constructors.py
  pandas/tests/indexes/base_class/test_reshape.py
  pandas/tests/indexes/object/test_indexing.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/interchange/test_impl.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_orc.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_sql.py
  pandas/tests/reshape/test_get_dummies.py
  pandas/tests/reshape/test_melt.py
  pandas/tests/series/test_logical_ops.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/util/test_shares_memory.py
Labels: Strings

#59577 ENH: Add dtype argument to StringMethods get_dummies()
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/string_arrow.py
  pandas/core/strings/accessor.py
  pandas/core/strings/base.py
  pandas/core/strings/object_array.py
  pandas/tests/strings/test_get_dummies.py
Labels: Enhancement, Strings

#59724 BUG (string): Series.str.slice with negative step
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/strings/test_strings.py
Labels: Strings

#59760 String dtype: remove fallback Perfomance warnings for string methods
  pandas/core/arrays/arrow/_arrow_utils.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_string_array.py
Labels: Strings

#59749 DOC: Add docstring for Extensionarray interpolate
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#59555 REF (string): de-duplicate ArrowStringArray methods
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
Labels: Refactor, Strings, Arrow

#59755 Fix/na_values_GH59303
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/test_na_values.py
Labels: IO CSV

#59778 BUG: avoid triggering numpy deprecation warning in assert functions for nested array with empty array/list
  pandas/_libs/lib.pyx
  pandas/tests/dtypes/test_missing.py
  pandas/tests/series/methods/test_equals.py
  pandas/tests/util/test_assert_almost_equal.py
Labels: Bug, Testing

#59784 Backport PR #58218: Revert "CI: Pin blosc to fix pytables"
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  scripts/generate_pip_deps_from_conda.py
  scripts/validate_min_versions_in_sync.py
Labels: Build, CI

#59748 DOC: Update GroupBy docstrings with See Also requirements
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Docs, Groupby

#59768 BUG/API (string dtype): return float dtype for series[str].rank()
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/frame/methods/test_rank.py
  pandas/tests/series/methods/test_rank.py
Labels: Strings, Arrow, Transformations

#59759 String dtype: fix isin() values handling for python storage
  pandas/conftest.py
  pandas/core/arrays/string_.py
  pandas/tests/arrays/string_/test_string.py
Labels: Strings

#59787 DOC: fix SA01 for pandas.NA
  ci/code_checks.sh
  pandas/_libs/missing.pyx
Labels: Docs

#59799 DOC: fix SA01,ES01 for pandas.Timedelta.components
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59798 Update ExtensionArray.interpolate to remove outdated method of pad
  pandas/core/arrays/base.py
Labels: Docs

#59796 DOC: fix SA01,ES01 for pandas.PeriodDtype.freq
  ci/code_checks.sh
  pandas/core/dtypes/dtypes.py
Labels: Docs

#59800 DOC: fix SA01,ES01 for pandas.Timedelta.total_seconds
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59802 DOC: fix SA01 for pandas.api.types.is_array_like
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59803 DOC: fix SA01 for pandas.api.types.is_integer_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59804 DOC: fix SA01 for pandas.arrays.FloatingArray
  ci/code_checks.sh
  pandas/core/arrays/floating.py
Labels: Docs

#59807 BUG (CoW): fix reference tracking in replace_list with None
  pandas/core/internals/blocks.py
  pandas/tests/copy_view/test_replace.py
Labels: Bug, replace, Copy / view semantics

#59811 DOC: add whatsnew for v2.2.3
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.2.3.rst
Labels: Docs

#59805 DOC: fix SA01 for pandas.errors.MergeError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#59812 Backport PR #59811 on branch 2.2.x (DOC: add whatsnew for v2.2.3)
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.2.3.rst
Labels: Docs

#59810 String dtype: allow string dtype in query/eval with default numexpr engine
  pandas/core/computation/eval.py
  pandas/core/computation/expr.py
  pandas/tests/frame/test_query_eval.py
Labels: Strings, expressions

#59818 BUG: Remove np._get_promotion_state usage
  pandas/tests/series/indexing/test_setitem.py
Labels: CI, Compat

#59813 CI: Debug failing ARM builds
  pandas/tests/extension/test_sparse.py
  pandas/tests/series/test_ufunc.py
  pyproject.toml
Labels: Build

#59828 Backport PR #59813 on branch 2.2.x (CI: Debug failing ARM builds)
  pandas/tests/extension/test_sparse.py
  pandas/tests/series/test_ufunc.py
  pyproject.toml
Labels: Build

#59535 Backport #59144 on 2.2.x / 2.3.x (remove ops div class to solve #2137)
  pandas/_testing/__init__.py
  pandas/conftest.py
  pandas/core/computation/expr.py
  pandas/core/computation/ops.py
  pandas/tests/computation/test_eval.py
Labels: Bug, expressions

#59834 DOC: fix SA01,ES01 for pandas.tseries.offsets.WeekOfMonth
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#59785 Assorted backports for 2.2.x
  .circleci/config.yml
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39.yaml
  ci/deps/actions-pypy-39.yaml
  ci/deps/circle-310-arm64.yaml
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/_libs/tslibs/offsets.pyx
  pandas/io/gbq.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/indexes/interval/test_interval_tree.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexing/interval/test_interval.py
  pandas/tests/indexing/interval/test_interval_new.py
  pandas/tests/io/parser/test_dialect.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/plotting/test_datetimelike.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/series/indexing/test_setitem.py
  pyproject.toml
Labels: Build, CI, Python 3.13

#59830 DOC: Adding ArcticDB to the ecosystem.md page
  web/pandas/community/ecosystem.md
Labels: Docs, Web

#59836 BLD: Fix bad Cython annotation
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
Labels: Build, Compat, Python 3.13

#59837 Backport PR #59836 on branch 2.2.x (BLD: Fix bad Cython annotation)
  pandas/_libs/tslibs/np_datetime.pxd
  pandas/_libs/tslibs/np_datetime.pyx
Labels: Build, Compat, Python 3.13

#59819 BLD/RLS: build wheels with released numpy/cython for Python 3.13
  .github/workflows/wheels.yml
  MANIFEST.in
  pyproject.toml
  scripts/cibw_before_build.sh
  scripts/cibw_before_test.sh
Labels: Build, CI

#59835 Backport PR #59136 on branch 2.2.x (Upload 3.13 & free-threaded nightly wheels)
  .circleci/config.yml
  .gitattributes
  .github/workflows/wheels.yml
  MANIFEST.in
  pyproject.toml
  scripts/cibw_before_build.sh
Labels: Build

#59840 BLD: Final release prep for 2.2.3
  doc/source/conf.py
  doc/source/whatsnew/v2.2.2.rst
  doc/source/whatsnew/v2.2.3.rst
  doc/source/whatsnew/v3.0.0.rst
  pyproject.toml
  scripts/cibw_before_build.sh
Labels: Build

#59842 Backport PR #59840: BLD: Final release prep for 2.2.3
  doc/source/conf.py
  doc/source/whatsnew/v2.2.2.rst
  doc/source/whatsnew/v2.2.3.rst
  pyproject.toml
  scripts/cibw_before_build.sh
Labels: Build

#59847 BLD: Build wheels for Python 3.13 on aarch64 as well
  .circleci/config.yml
Labels: Build

#59848 Backport PR #59847: BLD: Build wheels for Python 3.13 on aarch64 as well
  .circleci/config.yml
Labels: Build

#59870 DOC: fix RT03 for pandas.core.groupby.DataFrameGroupBy.hist
  ci/code_checks.sh
  pandas/core/groupby/generic.py
Labels: Docs, Groupby, Visualization

#59284 BUG: Fix precision loss in read_json
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/json/_json.py
  pandas/tests/io/json/test_pandas.py
Labels: Bug, Dtype Conversions, IO JSON

#59862 DOC: fix SA01 for pandas.api.types.is_int64_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59861 DOC: fix SA01, ES01 for pandas.api.types.is_float_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59859 DOC: fix SA01, ES01 for pandas.Series.sparse.sp_values
  ci/code_checks.sh
  pandas/core/arrays/sparse/array.py
Labels: Docs

#59858 DOC: fix SA01 for pandas.Series.sparse.fill_value
  ci/code_checks.sh
  pandas/core/arrays/sparse/array.py
Labels: Docs

#59856 DOC: fix SA01, ES01 for pandas.tseries.offsets.SemiMonthEnd
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#59685 String dtype: map builtin str alias to StringDtype
  pandas/_libs/lib.pyx
  pandas/_testing/__init__.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/dtypes/common.py
  pandas/core/indexes/base.py
  pandas/core/indexes/interval.py
  pandas/tests/arrays/floating/test_astype.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/arrays/sparse/test_astype.py
  pandas/tests/arrays/sparse/test_dtype.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/extension/base/casting.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_select_dtypes.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/indexes/datetimes/methods/test_astype.py
  pandas/tests/indexes/object/test_astype.py
  pandas/tests/indexes/period/methods/test_astype.py
  pandas/tests/indexes/timedeltas/methods/test_astype.py
  pandas/tests/interchange/test_impl.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/parser/test_na_values.py
  pandas/tests/io/parser/test_python_parser_only.py
  pandas/tests/series/methods/test_astype.py
  pandas/tests/series/methods/test_map.py
  pandas/tests/series/test_constructors.py
  pandas/tests/strings/test_get_dummies.py
  pandas/tests/test_algos.py
Labels: Strings

#59863 DOC: fix SA01 for pandas.api.types.is_interval_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59864 DOC: fix SA01 for pandas.api.types.is_list_like
  ci/code_checks.sh
  pandas/_libs/lib.pyx
Labels: Docs

#59852 typo
  pandas/io/pytables.py
Labels: Docs

#59866 DOC: fix SA01 for pandas.arrays.BooleanArray
  ci/code_checks.sh
  pandas/core/arrays/boolean.py
Labels: Docs

#59865 DOC: fix SA01, ES01 for pandas.api.types.is_object_dtype
  ci/code_checks.sh
  pandas/core/dtypes/common.py
Labels: Docs

#59868 DOC: fix RT03 for pandas.date_range
  ci/code_checks.sh
  pandas/core/indexes/datetimes.py
Labels: Docs

#59857 DOC: fix SA01, ES01 for pandas.RangeIndex.step
  ci/code_checks.sh
  pandas/core/indexes/range.py
Labels: Docs

#59860 DOC: fix SA01, ES01 for pandas.Timedelta.to_timedelta64
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59872 DOC: fix SA01, ES01 for pandas.errors.EmptyDataError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#59855 DOC: Fix inconsistent and incomplete documentation of `pandas.eval`
  pandas/core/computation/eval.py
  pandas/core/frame.py
Labels: Docs, expressions

#59854 String dtype: allow string dtype for non-raw apply with numba engine
  pandas/core/_numba/extensions.py
  pandas/core/apply.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_numba.py
Labels: Strings, Apply, numba

#59843 ENH: Add kwargs to Series.map
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_map.py
Labels: Enhancement

#59773 REF: pass dtype explicitly to _from_sequence inside pd.array
  pandas/core/construction.py
  pandas/tests/extension/base/methods.py
Labels: Refactor, ExtensionArray

#59822 DOC: Emphasize team managed pandas in installation docs
  doc/source/development/maintaining.rst
  doc/source/getting_started/index.rst
  doc/source/getting_started/install.rst
  web/pandas/getting_started.md
  web/pandas/static/img/install/anaconda_prompt.png
  web/pandas/static/img/install/jupyterlab_home.png
  web/pandas/static/img/install/pandas_import_and_version.png
Labels: Docs

#59893 CI/TST: Check for tzset in set_timezone
  pandas/_testing/contexts.py
  pandas/tests/tslibs/test_parsing.py
Labels: Testing, CI, Timezones, ARM

#59912 CI: Pin micromamba to 1.x
  .github/actions/setup-conda/action.yml
Labels: CI

#59896 DOC: fix SA01, ES01 for pandas.Series.sparse.npoints
  ci/code_checks.sh
  pandas/core/arrays/sparse/array.py
Labels: Docs

#59869 DOC: fix RT03, ES01 for pandas.core.groupby.DataFrameGroupBy.agg and pandas.core.groupby.DataFrameGroupBy.aggregate
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  scripts/validate_unwanted_patterns.py
Labels: Docs

#59898 DOC: fix RT03, ES01 for pandas.core.groupby.SeriesGroupBy.agg and pandas.core.groupby.SeriesGroupBy.aggregate
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  scripts/validate_unwanted_patterns.py
Labels: Docs

#59920 DOC: fix docstrings for multiple api.types methods
  ci/code_checks.sh
  pandas/core/dtypes/inference.py
Labels: Docs

#59918 DOC: the table name should be `air_quality_parameters` rather than `air_quality_parameters_name`
  doc/source/getting_started/intro_tutorials/08_combine_dataframes.rst
Labels: Docs

#59850 DOC: Separate out examples - pandas.str.is methods
  pandas/core/strings/accessor.py
Labels: Docs, Strings

#59914 DOC: fix pandas.TimedeltaIndex.to_pytimedelta RT03,SA01
  ci/code_checks.sh
  pandas/core/arrays/timedeltas.py
Labels: Docs

#59924 DOC: fix SA01, ES01 for pandas.errors.ClosedFileError
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#59925 DOC: fix SA01, ES01 for pandas.errors.OutOfBoundsDatetime
  ci/code_checks.sh
  pandas/_libs/tslibs/np_datetime.pyx
Labels: Docs

#59719 Fix docstring Timedelta.to_timedelta64 SA01, Timedelta.total_seconds SA01, Timedelta.view SA01
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#59906 BLD: Fix armv7 build
  pandas/_libs/src/vendored/ujson/python/JSONtoObj.c
Labels: Build, ARM

#59793 Fix doc
  doc/source/user_guide/dsintro.rst
Labels: Docs, Series, Constructors
