Repository pandas-dev/pandas, pull requests merged in 2024-04, with the labels that each got.

#58100 MNT: fix compatibility with beautifulsoup4 4.13.0b2
  pandas/io/html.py
Labels: IO HTML, Dependencies

#58097 DOC: Fix docstring errors for pandas.DataFrame.unstack, pandas.DataFrame.value_counts and pandas.DataFrame.tz_localize
  ci/code_checks.sh
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs

#58096 Remove 'Not implemented for Series' from _num_doc in generic.py
  pandas/core/generic.py
Labels: Docs

#58090 CI: Remove deprecated methods from code_checks.sh
  ci/code_checks.sh
Labels: Code Style

#58091 DOC: Changed ndim to 1, modified doc as suggested. #57088
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#58087 BLD: Build wheels using numpy 2.0rc1
  .circleci/config.yml
  .github/workflows/wheels.yml
  pyproject.toml
Labels: Build

#58076 DOC: docstring fix for pandas.DataFrame.where method
  ci/code_checks.sh
  pandas/core/generic.py
Labels: Docs

#58019 CLN/PERF: Simplify argmin/argmax
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/sparse/array.py
  pandas/core/base.py
  pandas/core/indexes/base.py
  pandas/core/nanops.py
  pandas/tests/extension/base/methods.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/reductions/test_reductions.py
Labels: Missing-data, Performance, Clean, Reduction Operations

#58016 PERF: Allow np.integer Series/Index to convert to RangeIndex
  pandas/core/indexes/base.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/io/test_stata.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Performance, Index

#57875 ENH: add warning when export to tar, zip in append mode
  pandas/io/common.py
  pandas/tests/frame/methods/test_to_csv.py
Labels: IO Data, Warnings

#53576 PDEP-1 Revision (Decision Making)
  web/pandas/pdeps/0001-purpose-and-guidelines.md
Labels: Stale, PDEP

#57487 CoW: Track references in unstack if there is no copy
  pandas/core/reshape/reshape.py
  pandas/tests/reshape/test_pivot.py
Labels: Reshaping, Copy / view semantics

#57862 DOC: RT03 fix for various DataFrameGroupBy and SeriesGroupBy methods
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
Labels: Docs

#57874 DOC: add note to how pandas deduplicate header when read from file
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#58040 DEPR: replace without passing value
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/core/shared_docs.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: Clean

#58101 DOC: fix docstring for DataFrame.to_period, pandas.DataFrame.to_timestamp, pandas.DataFrame.tz_convert #58065
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs

#58080 Backport PR #58075 on branch 2.2.x (DOC: whatsnew note for #57553)
  doc/source/whatsnew/v2.2.2.rst
Labels: Docs

#58107 BUG: Remove "Mean of empty slice" warning in nanmedian
  pandas/core/nanops.py
Labels: Warnings

#58017 Docs: Add note about exception for integer slices with float indices
  doc/source/user_guide/indexing.rst
Labels: Docs

#58095 DOC: read_sql_query docstring contraine wrong examples #58094
  pandas/io/sql.py
Labels: Docs

#58114 Add note for name field in groupby
  doc/source/user_guide/groupby.rst
Labels: Docs

#58126 BLD: Build wheels with numpy 2.0rc1
  pyproject.toml
Labels: Build

#58127 Backport PR #58126: BLD: Build wheels with numpy 2.0rc1
  pyproject.toml
Labels: Build

#57867 DOC: Add examples for creating an index accessor
  pandas/core/accessor.py
Labels: Docs

#58118 PERF: Series(dict) returns RangeIndex when possible
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/series/test_constructors.py
Labels: Index, Series

#58138 BLD: Fix nightlies not building
  .github/workflows/wheels.yml
Labels: Build

#58137 Backport PR #58100 on branch 2.2.x (MNT: fix compatibility with beautifulsoup4 4.13.0b2)
  pandas/io/html.py
Labels: IO HTML, Dependencies

#58119 PERF: concat([Series, DataFrame], axis=0) returns RangeIndex columns when possible
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Reshaping, Index

#58135 DOC: Add return value for Index.slice_locs when label not found #32680
  pandas/core/indexes/base.py
Labels: Docs

#58140 Backport PR #58138 on branch 2.2.x (BLD: Fix nightlies not building)
  .github/workflows/wheels.yml
Labels: Build

#58006 CLN: remove unnecessary check `needs_i8_conversion` if Index subclass does not support `any` or `all`
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/datetimelike.py
  pandas/core/indexes/base.py
  pandas/core/nanops.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/arrays/categorical/test_operators.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/extension/base/groupby.py
  pandas/tests/extension/base/reduce.py
  pandas/tests/extension/test_datetime.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reductions/test_stat_reductions.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/series/test_ufunc.py
Labels: Index, Reduction Operations

#58148 BUG: Fix Index.sort_values with natsort_key raises
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/sorting.py
  pandas/tests/indexes/test_common.py
Labels: Index, Sorting

#58158 DEPR: PandasArray alias
  doc/redirects.csv
  doc/source/whatsnew/v3.0.0.rst
  pandas/arrays/__init__.py
  pandas/tests/api/test_api.py
Labels: Clean

#57999 DEPR: Enforce datetimelike deprecations
  asv_bench/benchmarks/categoricals.py
  asv_bench/benchmarks/timeseries.py
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/interval/test_interval_range.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/indexes/timedeltas/test_constructors.py
Labels: Clean

#58157 DEPR: Categorical fastpath
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/arrays/categorical/test_constructors.py
Labels: Clean

#58167 DEPR: enforce Sparse deprecations
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/sparse/array.py
  pandas/core/dtypes/dtypes.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/arrays/sparse/test_constructors.py
  pandas/tests/arrays/sparse/test_dtype.py
Labels: Clean

#58168 No longer produce test.tar/test.zip after running test suite
  pandas/tests/frame/methods/test_to_csv.py
Labels: Testing

#58171 REF: de-duplicate tzinfo-awareness mismatch checks
  pandas/_libs/tslib.pyx
  pandas/_libs/tslibs/strptime.pxd
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/tools/test_to_datetime.py
Labels: Timezones, Clean

#58161 STY: Add flake8-slots and flake8-raise rules
  .pre-commit-config.yaml
  pandas/core/api.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/interchange/buffer.py
  pandas/io/stata.py
  pandas/tests/config/test_localization.py
  pandas/tests/frame/indexing/test_setitem.py
  pyproject.toml
Labels: Code Style

#58057 BUG: Allow using numpy in `DataFrame.eval` and `DataFrame.query` via @-notation
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/computation/ops.py
  pandas/tests/frame/test_query_eval.py
Labels: expressions

#57182 Migrate pylint to ruff
  .github/workflows/code-checks.yml
  .pre-commit-config.yaml
  pandas/_libs/tslibs/__init__.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/base.py
  pandas/core/dtypes/common.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/multi.py
  pandas/core/internals/__init__.py
  pandas/core/series.py
  pandas/io/formats/style.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/plotting/_matplotlib/core.py
  pandas/plotting/_matplotlib/hist.py
  pandas/tests/config/test_config.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/indexes/datetimes/test_iter.py
  pandas/tests/io/formats/style/test_html.py
  pandas/tests/io/test_html.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/scalar/timedelta/test_arithmetic.py
  pandas/tests/scalar/timestamp/test_comparisons.py
  pandas/tests/util/test_deprecate_nonkeyword_arguments.py
  pyproject.toml
  scripts/tests/data/deps_minimum.toml
Labels: Code Style

#58187 Backport PR #58181 on branch 2.2.x (CI: correct error msg in test_view_index)
  pandas/tests/indexes/test_base.py
Labels: Build

#58166 TST: Use temp_file fixture over ensure_clean
  pandas/tests/io/test_stata.py
  pandas/tests/series/methods/test_to_csv.py
Labels: Testing

#58192 TST: Match dta format used for Stata test files with that implied by their filenames
  pandas/tests/io/data/stata/stata10_115.dta
  pandas/tests/io/data/stata/stata4_114.dta
  pandas/tests/io/data/stata/stata9_115.dta
Labels: Testing, IO Stata

#58175 TST: Remove deprecation check from test_pyarrow_engine
  pandas/tests/io/parser/test_unsupported.py
Labels: Testing, IO CSV

#58155 ENH: Add support for reading value labels from 108-format and prior Stata dta files
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/data/stata/stata4_105.dta
  pandas/tests/io/data/stata/stata4_108.dta
  pandas/tests/io/data/stata/stata4_111.dta
  pandas/tests/io/test_stata.py
Labels: IO Stata

#58122 DEPR: keyword-only arguments for DataFrame/Series statistical methods
  doc/source/user_guide/basics.rst
  doc/source/user_guide/indexing.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/series.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_str.py
  pandas/tests/frame/methods/test_asof.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/series/test_api.py
  pandas/tests/test_multilevel.py
  scripts/tests/test_validate_docstrings.py
Labels: Deprecate

#57965 BUG: Fix na_values dict not working on index column (#57547)
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/python_parser.py
  pandas/tests/io/parser/test_na_values.py
Labels: IO CSV

#58198 Remove unused tslib function
  pandas/_libs/tslib.pyx
Labels: Internals, Clean

#58199 Fix ASV with virtualenv
  asv_bench/asv.conf.json
Labels: Benchmark

#58200 CLN: Make iterators lazier
  pandas/core/apply.py
  pandas/core/frame.py
  pandas/core/groupby/ops.py
  pandas/core/indexing.py
  pandas/core/sorting.py
Labels: Clean

#58195 TST: Add tests for reading Stata dta files saved in big-endian format
  pandas/tests/io/data/stata/stata-compat-be-105.dta
  pandas/tests/io/data/stata/stata-compat-be-108.dta
  pandas/tests/io/data/stata/stata-compat-be-111.dta
  pandas/tests/io/data/stata/stata-compat-be-113.dta
  pandas/tests/io/data/stata/stata-compat-be-114.dta
  pandas/tests/io/data/stata/stata-compat-be-118.dta
  pandas/tests/io/test_stata.py
Labels: Testing, IO Stata

#58105 Backport PR #58087 on branch 2.2.x (BLD: Build wheels using numpy 2.0rc1)
  .circleci/config.yml
  .github/workflows/wheels.yml
  pyproject.toml
Labels: Build

#58201 CLN: Remove unused code
  pandas/core/groupby/grouper.py
Labels: Groupby, Clean

#58203 DOC: Add release date/contributors for 2.2.2
  doc/source/whatsnew/v2.2.1.rst
  doc/source/whatsnew/v2.2.2.rst
Labels: Docs

#58202 DOC/TST: Document numpy 2.0 support and add tests for string array
  doc/source/whatsnew/v2.2.2.rst
  pandas/tests/frame/test_constructors.py
  pandas/tests/series/test_constructors.py
Labels: Testing, Docs, Compat

#58206 Backport PR #58203 on branch 2.2.x (DOC: Add release date/contributors for 2.2.2)
  doc/source/whatsnew/v2.2.1.rst
  doc/source/whatsnew/v2.2.2.rst
Labels: Docs

#58208 Backport PR #58202: DOC/TST: Document numpy 2.0 support and add tests…
  doc/source/whatsnew/v2.2.2.rst
  pandas/tests/frame/test_constructors.py
  pandas/tests/series/test_constructors.py
Labels: Testing, Compat

#58209 CI: Pin blosc to fix pytables
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  scripts/generate_pip_deps_from_conda.py
  scripts/validate_min_versions_in_sync.py
Labels: CI

#58211 Backport PR #58209: CI: Pin blosc to fix pytables
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  scripts/generate_pip_deps_from_conda.py
  scripts/validate_min_versions_in_sync.py
Labels: CI

#58218 Revert "CI: Pin blosc to fix pytables"
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  environment.yml
  scripts/generate_pip_deps_from_conda.py
  scripts/validate_min_versions_in_sync.py
Labels: CI

#57788 API: Revert 57042 - MultiIndex.names|codes|levels returns tuples
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/index.pyi
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/frozen.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/strings/accessor.py
  pandas/core/window/rolling.py
  pandas/tests/frame/methods/test_rename_axis.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_series.py
  pandas/tests/groupby/methods/test_quantile.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/indexes/multi/test_astype.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/multi/test_copy.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/multi/test_formats.py
  pandas/tests/indexes/multi/test_get_set.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/multi/test_names.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_frozen.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_sql.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/reshape/test_crosstab.py
  pandas/tests/series/methods/test_rename_axis.py
  pandas/tests/test_common.py
  pandas/tests/util/test_assert_index_equal.py
  pandas/tests/window/test_rolling.py
Labels: MultiIndex

#58223 DOC: Fix docstring error for pandas.DataFrame.axes
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58227 REF: Use PyUnicode_AsUTF8AndSize instead of get_c_string_buf_and_size
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/_libs/tslibs/np_datetime.pyx
  pandas/_libs/tslibs/parsing.pyx
  pandas/_libs/tslibs/util.pxd
Labels: Internals, Clean

#58213 DOC: update DatetimeTZDtype unit limitation
  pandas/core/dtypes/dtypes.py
Labels: Docs

#58241 DEPR: object casting in Series logical ops in non-bool cases
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/series.py
  pandas/tests/series/test_logical_ops.py
Labels: Clean

#58242 DEPR: logical ops with dtype-less sequences
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/ops/array_ops.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/series/test_logical_ops.py
Labels: Clean

#57222 ENH: Add all warnings check to the assert_produces_warnings, and separate messages for each warning.
  pandas/_testing/_warnings.py
  pandas/_testing/contexts.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/usecols/test_parse_dates.py
  pandas/tests/util/test_assert_produces_warning.py
Labels: Testing, Warnings

#58235 DOC: Enforce Numpy Docstring Validation for pandas.ExcelFile, pandas.ExcelFile.parse and pandas.ExcelWriter
  ci/code_checks.sh
  pandas/io/excel/_base.py
Labels: Docs, IO Excel

#58261 DOC: Reference Excel reader installation in the read and write tabular data tutorial
  doc/source/getting_started/install.rst
  doc/source/getting_started/intro_tutorials/02_read_write.rst
Labels: Docs, IO Excel

#58226 BUG: Timestamp ignoring explicit tz=None
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/timestamps.pyx
  pandas/tests/indexing/test_at.py
  pandas/tests/scalar/timestamp/test_constructors.py
  pandas/tests/scalar/timestamp/test_formats.py
Labels: Timezones, Timestamp

#58188 TST: catch exception for div/truediv operations between Timedelta and pd.NA
  pandas/tests/scalar/timedelta/test_timedelta.py
Labels: Testing

#58085 ENH: Enable fillna(value=None)
  doc/source/user_guide/missing_data.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/array.py
  pandas/core/generic.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/extension/base/missing.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Enhancement, Missing-data

#58197 Add low-level create_dataframe_from_blocks helper function
  pandas/api/internals.py
  pandas/core/internals/api.py
  pandas/tests/api/test_api.py
  pandas/tests/internals/test_api.py
  scripts/validate_unwanted_patterns.py
Labels: API Design, Internals

#58265 DOC: Move whatsnew 3.0 elements
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#58268 CI/TST: Unxfail test_slice_locs_negative_step Pyarrow test
  pandas/tests/indexes/object/test_indexing.py
Labels: Testing, CI, Arrow

#58266 DOC: Enforce Numpy Docstring Validation for pandas.Float32Dtype and pandas.Float64Dtype
  ci/code_checks.sh
  pandas/core/arrays/floating.py
Labels: Docs

#58237 API: Expose api.typing.FrozenList for typing
  doc/source/whatsnew/v3.0.0.rst
  pandas/api/typing/__init__.py
  pandas/tests/api/test_api.py
Labels: Typing

#58269 Backport PR #58268 on branch 2.2.x (CI/TST: Unxfail test_slice_locs_negative_step Pyarrow test)
  pandas/tests/indexes/object/test_indexing.py
Labels: Testing, CI, Arrow

#58228 ASV: benchmark for DataFrame.Update
  asv_bench/benchmarks/frame_methods.py
Labels: Benchmark

#58256 DOC: replace deprecated frequency alias
  pandas/core/arrays/datetimelike.py
Labels: Docs

#58043 BUG: DataFrame slice selection treated as hashable in Python 3.12 #57500
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, MultiIndex

#58204 GH: PDEP vote issue template
  .github/ISSUE_TEMPLATE/pdep_vote.yaml
  web/pandas/pdeps/0001-purpose-and-guidelines.md
Labels: Admin

#58267 REF: Clean up some iterator usages
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/construction.py
  pandas/core/tools/datetimes.py
Labels: Clean

#58275 Avoid unnecessary re-opening of HDF5 files (Closes: #58248)
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/pytables.py
Labels: Performance, IO HDF5

#58293 CI: Pin docutils to < 0.21
  environment.yml
  requirements-dev.txt
Labels: Docs, CI

#58271 REF: Use more cython memoryviews
  pandas/_libs/algos.pyx
  pandas/_libs/groupby.pyx
  pandas/_libs/hashing.pyx
Labels: Refactor, Internals

#58295 Backport PR #58293 on branch 2.2.x (CI: Pin docutils to < 0.21)
  environment.yml
  requirements-dev.txt
Labels: Docs, CI

#58115 DOC: Remove deprecated methods from code_checks.sh
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Code Style

#58294 DOC: Remove deprecated methods from code_checks.sh
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs

#58310 Fix merge error logging order
  pandas/core/reshape/merge.py
Labels: Error Reporting

#58301 BUG: Setting values on DataFrame with multi-index .loc(axis=0) access adds columns
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
Labels: Indexing

#58298 DOC: Remove deprecated methods w/ SA01 errors from code_checks.sh
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs

#58250 ENH: DtypeWarning message enhancement
  doc/source/whatsnew/v3.0.0.rst
  pandas/errors/__init__.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/tests/io/parser/common/test_chunksize.py
  pandas/tests/io/parser/test_concatenate_chunks.py
Labels: IO CSV, Warnings

#58245 DOC: Add documentation on parquet categorical data handling
  pandas/core/frame.py
Labels: Docs, IO Parquet

#57987 DEPR: 'epoch' date format in to_json
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_gcs.py
Labels: IO JSON, Deprecate

#58322 BUG: `df.plot` with a `PeriodIndex` causes a shift to the right when the frequency multiplier is greater than one
  doc/source/whatsnew/v3.0.0.rst
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/plotting/frame/test_frame.py
Labels: Bug, Visualization

#58125 CLN: enforce deprecation of the `kind` keyword on df.resample/ser.resample
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/core/resample.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: Resample, Clean

#58326 DOC: Fix SA01 errors for DatetimeIndex.month and DatetimeIndex.year
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs

#58314 DEPR: concat ignoring all-NA entries
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/internals/concat.py
  pandas/tests/reshape/concat/test_append.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_datetimes.py
  pandas/tests/reshape/merge/test_merge.py
Labels: Clean

#58296 CLN: Use generators where list results are re-iterated over
  pandas/core/groupby/groupby.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/core/internals/concat.py
  pandas/io/formats/info.py
  pandas/io/sql.py
Labels: Clean

#58331 DOC: removing SA01 errors for DateTimeIndex: hour, minute, and second.
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs

#58323 DOC: Update DataFrame.sparse methods' docstring to pass docstring validation
  ci/code_checks.sh
  pandas/core/arrays/sparse/accessor.py
Labels: Docs

#58339 TYP: register_*_accessor decorators
  .pre-commit-config.yaml
  doc/source/whatsnew/v3.0.0.rst
  environment.yml
  pandas/_typing.py
  pandas/core/accessor.py
  requirements-dev.txt
Labels: Typing

#58305 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.append
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58333 DOC: fixing SA01 errors for index.size, shape, and ndim.
  ci/code_checks.sh
  pandas/core/base.py
  pandas/core/indexes/base.py
Labels: Docs

#58341 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.get
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58342 DOC: fixing SA01 error for DatetimeIndex: second, nanosecond, and microsecond
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs

#58349 TYP: export SASReader in pandas.api.typing
  doc/source/whatsnew/v3.0.0.rst
  pandas/api/typing/__init__.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sas/sas_xport.py
  pandas/io/sas/sasreader.py
  pandas/tests/api/test_api.py
Labels: Typing

#58357 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.groups
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58343 DOC: Fix SA01 errors for Index.hasnans, Index.map, Index.nbytes
  ci/code_checks.sh
  pandas/core/base.py
  pandas/core/indexes/base.py
Labels: Docs

#58353 DOC: Enforce Numpy Docstring Validation for DatetimeIndex
  ci/code_checks.sh
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
Labels: Docs

#58368 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.info
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58364 DOC: Fix SA01 Docstring Errors for DataFrame
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#58356 More idiomatic example code in BaseIndexer
  pandas/core/indexers/objects.py
Labels: Docs

#58355 DOC: fixing SA01 errors for Index: name, dtype, and equals
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58352 DOC: Fix SA01 errors for pandas.Index.astype
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58330 CLN: Use more memoryviews
  pandas/_libs/lib.pyx
  pandas/_libs/reshape.pyx
Labels: Clean

#58319 CLN: Use generators when objects are re-iterated over in core/internals
  pandas/core/frame.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_internals.py
Labels: Internals, Clean

#58334 Allow `tan` to be used in `df.eval`.
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/computation/ops.py
Labels: expressions

#58371 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.keys
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58359 Doc: Fixing SA01 error for DataFrame: pop and columns
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58374 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.select
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58377 DOC: Fixing SA01 issues for DatetimeIndex: date and tz
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs

#58370 REF: Defer creating Index._engine until needed
  pandas/core/frame.py
  pandas/core/indexes/base.py
Labels: Refactor, Index

#58358 Add mailing list link
  doc/source/development/community.rst
Labels: Docs, Admin

#56419 BUG: setitem with mixed-resolution dt64s
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/datetimes.py
  pandas/core/internals/blocks.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_clip.py
  pandas/tests/series/methods/test_fillna.py
Labels: Indexing, Non-Nano

#58384 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.put
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58381 TST: No longer produce test_stata.dta file after running test suite
  pandas/tests/io/test_stata.py
Labels: Testing, IO Stata

#58379 #58324
  doc/source/user_guide/style.ipynb
Labels: Docs

#58386 DOC: Enforce Numpy Docstring Validation for pandas.HDFStore.walk
  ci/code_checks.sh
  pandas/io/pytables.py
Labels: Docs

#58360 ENH: Implement cummax and cummin in _accumulate() for ordered Categorical arrays
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/categorical.py
  pandas/tests/series/test_cumulative.py
Labels: Categorical, Reduction Operations

#58387 DOC: Enforce Numpy Docstring Validation for pandas.DatetimeTZDtype.unit
  ci/code_checks.sh
  pandas/core/dtypes/dtypes.py
Labels: Docs

#58390 CLN: Enforce empty bool indexer deprecation
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_base.py
Labels: Clean

#58189 BUG: Let check_exact_index default to True for integers
  doc/source/whatsnew/v3.0.0.rst
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Testing

#58393 Extend eval test of standard functions to cover python engine.
  pandas/tests/computation/test_eval.py
Labels: Testing, expressions

#58385 PERF: MultiIndex.memory_usage shouldn't trigger the index engine
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/base.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/test_old_base.py
Labels: Performance, Index

#58399 DOC: Enforce Numpy Docstring Validation for pandas.Index.unique
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58396 TST: Added match argument for most uses of tm.assert_produces_warning
  doc/source/development/contributing_codebase.rst
  pandas/tests/arrays/sparse/test_constructors.py
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/computation/test_eval.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_generic.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/methods/test_to_dict.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/indexes/base_class/test_setops.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_index_new.py
  pandas/tests/indexes/test_setops.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/formats/test_css.py
  pandas/tests/io/formats/test_to_excel.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_compression.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/test_stata.py
  pandas/tests/plotting/frame/test_frame.py
  pandas/tests/plotting/frame/test_frame_subplots.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/scalar/timestamp/methods/test_to_pydatetime.py
  pandas/tests/scalar/timestamp/test_timestamp.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/test_expressions.py
  pandas/tests/test_optional_dependency.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_rolling_quantile.py
Labels: Testing, Warnings

#58335 BUG: Ignore warning for duplicate columns in `to_dict` when orient='tight'
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/methods/to_dict.py
  pandas/tests/frame/methods/test_to_dict.py
Labels: Output-Formatting, Warnings

#58389 CI: Fix npdev failures
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/extension/base/missing.py
  pandas/tests/indexes/test_base.py
Labels: CI, Compat

#58408 Backport PR #58389 on branch 2.2.x (CI: Fix npdev failures)
  pandas/tests/arrays/test_datetimelike.py
  pandas/tests/extension/base/missing.py
  pandas/tests/indexes/test_base.py
Labels: CI, Compat

#58407 DEPR: to_datetime string behavior with unit
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslib.pyi
  pandas/_libs/tslib.pyx
  pandas/core/tools/datetimes.py
  pandas/tests/tools/test_to_datetime.py
Labels: Clean

#58406 DOC: fix SA01 error for DatetimeIndex: day_of_year, is_leap_year, inferred_freq
  ci/code_checks.sh
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
Labels: Docs

#58398 DOC: Enforce Numpy Docstring Validation for pandas.Index.to_list
  ci/code_checks.sh
  pandas/core/base.py
Labels: Docs

#56515 Fix/time series interpolation is wrong 21351
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/missing.py
  pandas/core/resample.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Missing-data, Error Reporting

#56484 REF: use maybe_convert_objects in pd.array
  pandas/_libs/lib.pyx
  pandas/core/construction.py
  pandas/tests/arrays/test_array.py
  pandas/tests/dtypes/test_inference.py
Labels: Stale

#58400 DOC: Enforce Numpy Docstring Validation for pandas.Index.item
  ci/code_checks.sh
  pandas/core/base.py
Labels: Docs

#58417 DOC: Enforce Numpy Docstring Validation for pandas.Index.fillna
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58416 DOC: Enforce Numpy Docstring Validation for pandas.DatetimeIndex.tzconvert
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs
