Repository pandas-dev/pandas, pull requests merged in 2024-05, with the labels that each got.

#58506 DOC: Enforce Numpy Docstring Validation for pandas.Index.get_indexer
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58508 DOC: Enforce Numpy Docstring Validation for pandas.Index.get_indexer_non_unique
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58510 DOC: Enforce Numpy Docstring Validation for pandas.Index.putmask
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58512 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.prod
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58514 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.skew
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58507 DOC: Enforce Numpy Docstring Validation for pandas.Index.get_indexer_for
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58515 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.sparse
  ci/code_checks.sh
  pandas/core/arrays/sparse/accessor.py
Labels: Docs

#58511 DOC: Enforce Numpy Docstring Validation for pandas.Int
  ci/code_checks.sh
  pandas/core/arrays/integer.py
Labels: Docs

#58497 REF: Read excel parse refactor
  pandas/io/excel/_base.py
Labels: Refactor, IO Excel

#58369 BUG: as_index=False can return a MultiIndex in groupby.apply
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_groupby.py
Labels: Groupby, MultiIndex, Apply

#58513 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.sem
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58509 DOC: Enforce Numpy Docstring Validation for pandas.Index.get_loc
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58521 DOC: Enforce Numpy Docstring Validation for pandas.IntervalDtype
  ci/code_checks.sh
  pandas/core/dtypes/dtypes.py
Labels: Docs

#58526 DOC: Enforce Numpy Docstring Validation for pandas.Series.backfill
  ci/code_checks.sh
Labels: Docs

#58518 DOC: remove concat dict sortedness statement
  pandas/core/reshape/concat.py
Labels: Docs

#58527 DOC: Enforce Numpy Docstring Validation for pandas.Series.cat.codes
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
Labels: Docs

#58535 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp.days_in_month
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58522 DOC: Enforce Numpy Docstring Validation for pandas.IntervalDtype.subtype
  ci/code_checks.sh
  pandas/core/dtypes/dtypes.py
Labels: Docs

#58532 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp.day_name
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58534 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp.day_of_year
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58540 DOC: Fix Docstring Errors for pandas.api.extensions.ExtensionArray
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#58542 Fix SA01 errors for Series.dtype, Series.is_unique, Series.shape
  ci/code_checks.sh
  pandas/core/base.py
  pandas/core/series.py
Labels: Docs

#58533 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp.day_of_week
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58249 BUG: Implement fillna(..., limit=x) for EAs
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/base.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/array.py
  pandas/core/internals/blocks.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_interval.py
  pandas/tests/extension/test_numpy.py
  pandas/tests/extension/test_sparse.py
Labels: Bug, Missing-data, ExtensionArray

#58467 CLN: enforce the deprecation of exposing blocks in core.internals
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/internals/__init__.py
  pandas/io/pytables.py
  pandas/tests/internals/test_api.py
  pandas/tests/io/test_parquet.py
Labels: Internals, Clean

#58413 DEPS: Unpin docutils
  doc/source/user_guide/basics.rst
  doc/source/user_guide/gotchas.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/indexing.rst
  doc/source/user_guide/io.rst
  doc/source/user_guide/text.rst
  environment.yml
  requirements-dev.txt
Labels: Docs, Dependencies

#58556 DOC: Fix SA01 Errors
  ci/code_checks.sh
  pandas/core/base.py
Labels: Docs

#58558 DOC: Improve convert_dtypes's docstring
  pandas/core/generic.py
Labels: Docs

#58572 DOC: Enforce Numpy Docstring Validation for pandas.Interval.mid
  ci/code_checks.sh
  pandas/_libs/interval.pyx
Labels: Docs

#58573 DOC: Enforce Numpy Docstring Validation for pandas.Series.max
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58575 DOC: Enforce Numpy Docstring Validation for pandas.Series.median
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58571 DOC: Enforce Numpy Docstring Validation for pandas.Interval.right pandas.Interval.left pandas.Interval.closed
  ci/code_checks.sh
  pandas/_libs/interval.pyx
Labels: Docs

#58568 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.var
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58563 DOC: Enforce Numpy Docstring Validation for pandas.Index.names
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58550 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58567 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.to_markdown
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58574 DOC: Enforce Numpy Docstring Validation for pandas.Series.mean
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58580 DOC: Enforce Numpy Docstring Validation for pandas.Series.mul
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58565 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.sum
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58562 DOC: Enforce Numpy Docstring Validation for pandas.Index.str and pandas.Series.str
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs

#58590 BUG: Use large_string in string array consistently
  pandas/core/arrays/string_arrow.py
Labels: Strings, Arrow

#58589 DOC: Minor fix to docstring formatting for `head()` and `tail()`
  pandas/core/generic.py
Labels: Docs

#58587 DOC: Fix minor grammatical typo in `core/series.py` docstring.
  pandas/core/series.py
Labels: Docs

#58588 DOC: shift() of boolean series gives drawdown by an order of magnitude with default filling np.NaN comparing with filling by bool like False
  pandas/core/generic.py
Labels: Docs

#58560 DOC: Enforce Numpy Docstring Validation for pandas.Index.join
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58564 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.std
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58595 BUG: Improve error message when casting array of objects to int
  pandas/core/dtypes/cast.py
  pandas/tests/indexes/numeric/test_numeric.py
Labels: Error Reporting

#58566 DOC: Enforce Numpy Docstring Validation for pandas.DataFrame.swaplevel
  ci/code_checks.sh
  pandas/core/frame.py
Labels: Docs

#58561 DOC: Enforce Numpy Docstring Validation for pandas.Index.ravel
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58579 TST: Add test for duplicate `by` columns in `groupby.agg` using `pd.namedAgg` and `asIndex=False`
  pandas/tests/groupby/test_groupby.py
Labels: Testing

#58597 Backport PR #58590 on branch 2.2.x (BUG: Use large_string in string array consistently)
  pandas/core/arrays/string_arrow.py
Labels: Strings, Arrow

#58599 CLN: Some unit tests
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_str.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/base/test_conversion.py
  pandas/tests/base/test_value_counts.py
  pandas/tests/computation/test_eval.py
  pandas/tests/frame/test_ufunc.py
  pandas/tests/test_multilevel.py
  pandas/tests/window/test_expanding.py
Labels: Testing, Clean

#58606 DOC: Enforce Numpy Docstring Validation for pandas.Series.min
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58608 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.closed and pandas.arrays.IntervalArray.closed
  ci/code_checks.sh
  pandas/core/arrays/interval.py
Labels: Docs

#58610 DOC: Enforce Numpy Docstring Validation for pandas.tseries copy methods
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#58614 DOC: Enforce Numpy Docstring Validation for pandas.api.extensions.register_extension_dtype
  ci/code_checks.sh
  pandas/core/dtypes/base.py
Labels: Docs

#58617 TST: Reduce some testing data sizes
  pandas/conftest.py
  pandas/tests/frame/conftest.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/methods/test_at_time.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_to_csv.py
  pandas/tests/frame/methods/test_truncate.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
Labels: Testing, Clean

#58616 BUG: Fix arrow extension array assignment by repeated key
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/base/setitem.py
Labels: Indexing, Arrow

#58615 DOC: Enforce Numpy Docstring Validation for pandas.api.extensions.register_extension_dtype
  ci/code_checks.sh
  pandas/core/indexers/objects.py
Labels: Docs

#58619 Enforce Numpy Docstring Validation for pandas.Series.mod
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58618 Enforce Numpy Docstring Validation for pandas.IntervalIndex.contains and pandas.arrays.IntervalArray.contains
  ci/code_checks.sh
  pandas/core/arrays/interval.py
Labels: Docs

#58620 CLN: Remove deprecated read_csv(infer_datetime_format=)
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/test_parse_dates.py
Labels: Clean

#58624 CLN: Remove deprecated read_*(date_parser=)
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/excel/_base.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/test_read_fwf.py
Labels: IO CSV, Clean

#58625 CLN: Change Categorical.map(na_action=) default to None
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/sparse/array.py
  pandas/core/frame.py
  pandas/tests/arrays/categorical/test_map.py
Labels: Categorical, Clean

#58609 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp.as_unit and pandas.Timedelta.as_unit
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58627 DOC: Enforce Numpy Docstring Validation for pandas.Series.mode
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58629 DOC: Enforce Numpy Docstring Validation for pandas.Timestamp.utcnow
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58633 DOC: Enforce Numpy Docstring Validation for pandas.tseries.offsets.Week.name
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#58634 DOC: Enforce Numpy Docstring Validation for pandas.tseries.offsets.Week.name
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#58637 DOC: Enforce Numpy Docstring Validation for pandas.Series.dt.daysinmonth and pandas.Series.dt.days_in_month
  ci/code_checks.sh
  pandas/core/arrays/datetimes.py
Labels: Docs

#58635 TST: Skip test_rolling_var_numerical_issues on riscv64 platforms
  pandas/compat/__init__.py
  pandas/tests/window/test_rolling.py
Labels: Testing

#58626 CLN: callable to Series.iloc returning a tuple
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexing.py
  pandas/tests/frame/indexing/test_indexing.py
Labels: Indexing, Clean

#57896 BLD, TST: Build and test Pyodide wheels for `pandas` in CI
  .github/workflows/unit-tests.yml
  pandas/compat/__init__.py
  pandas/compat/_constants.py
  pandas/tests/apply/test_str.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/indexes/datetimes/methods/test_normalize.py
  pandas/tests/indexes/datetimes/methods/test_resolution.py
  pandas/tests/io/parser/common/test_file_buffer_url.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/io/test_common.py
  pandas/tests/io/xml/test_xml.py
  pandas/tests/scalar/timestamp/methods/test_replace.py
  pandas/tests/scalar/timestamp/methods/test_timestamp_method.py
  pandas/tests/scalar/timestamp/test_formats.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_timedelta.py
  pandas/tests/tseries/offsets/test_common.py
  pandas/tests/tslibs/test_parsing.py
  pandas/util/_test_decorators.py
Labels: Testing

#58642 DOC: Improve docstrings for Index.empty, Index.view and Index.names
  pandas/core/base.py
  pandas/core/indexes/base.py
Labels: Docs

#58630 TST: Add test for regression in `groupby` with tuples yielding MultiIndex
  pandas/tests/groupby/test_grouping.py
Labels: Testing

#58037 DEPR: remove deprecated internals names
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/internals/api.py
  pandas/core/internals/blocks.py
Labels: Clean

#58084 BUG/PERF: groupby.transform with unobserved categories
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Bug, Groupby, Performance, Categorical, Apply

#58044 ENH: Add support for reading 110-format Stata dta files
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/data/stata/stata-compat-110.dta
  pandas/tests/io/data/stata/stata-compat-be-110.dta
  pandas/tests/io/data/stata/stata4_110.dta
  pandas/tests/io/test_stata.py
Labels: IO Stata

#58653 DOC: Fix typo in indexing.rst
  doc/source/user_guide/indexing.rst
Labels: Docs

#58652 DOC: Enforce Numpy Docstring Validation for pandas.api.indexers.FixedForwardWindowIndexer
  ci/code_checks.sh
  pandas/core/indexers/objects.py
Labels: Docs

#58649 DOC: Enforce Numpy Docstring Validation for pandas.Interval
  ci/code_checks.sh
  pandas/_libs/interval.pyx
Labels: Docs

#58650 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.right
  ci/code_checks.sh
  pandas/core/indexes/interval.py
Labels: Docs

#58656 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.get_loc
  ci/code_checks.sh
  pandas/core/indexes/interval.py
Labels: Docs

#58657 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.mid
  ci/code_checks.sh
  pandas/core/indexes/interval.py
Labels: Docs

#58658 CI/TST: Don't xfail test_api_read_sql_duplicate_columns for pyarrow=16 and sqlite
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL, CI

#58659 DOC: Remove deprecated delim_whitespace from user guide
  doc/source/user_guide/io.rst
Labels: Docs

#58660 Backport PR #58658 on branch 2.2.x (CI/TST: Don't xfail test_api_read_sql_duplicate_columns for pyarrow=16 and sqlite)
  pandas/tests/io/test_sql.py
Labels: Testing, IO SQL, CI

#58661 DOC: Add examples for pd.read_csv
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#58662 DOC: Clarify allowed values for on_bad_lines in read_csv
  pandas/io/parsers/readers.py
Labels: Docs

#58483 CLN: Simplify map_infer_mask
  asv_bench/benchmarks/series_methods.py
  pandas/_libs/dtypes.pxd
  pandas/_libs/lib.pyx
  pandas/core/arrays/string_arrow.py
Labels: Clean

#58622 CLN: Enforce read_csv(keep_date_col, parse_dates) deprecations
  asv_bench/benchmarks/io/csv.py
  asv_bench/benchmarks/io/parsers.py
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/parsing.pyi
  pandas/_libs/tslibs/parsing.pyx
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/parser/usecols/test_parse_dates.py
  pandas/tests/io/test_html.py
  pandas/tests/io/xml/test_xml_dtypes.py
Labels: IO CSV, Clean

#58666 Clarify on_bad_lines PyArrow in read_csv
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#58549 BUG: `DatetimeIndex.is_year_start` and `DatetimeIndex.is_quarter_start` always return False on double-digit frequencies
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/fields.pyi
  pandas/_libs/tslibs/fields.pyx
  pandas/_libs/tslibs/timestamps.pyx
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_scalar_compat.py
Labels: Bug, Frequency

#58494 BUG: Improve error message when `tansfrom()` with incorrect axis
  pandas/core/apply.py
  pandas/tests/apply/test_invalid_arg.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_other.py
  pandas/tests/resample/test_resample_api.py
Labels: Error Reporting, Apply

#58670 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.is_non_overlapping_monotonic and pandas.arrays.IntervalArray.is_non_overlapping_monotonic
  ci/code_checks.sh
  pandas/core/arrays/interval.py
Labels: Docs

#58671 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.length
  ci/code_checks.sh
  pandas/core/indexes/interval.py
Labels: Docs

#58672 DOC: Enforce Numpy Docstring Validation for pandas.IntervalIndex.to_tuples and pandas.arrays.IntervalArray.to_tuples
  ci/code_checks.sh
  pandas/core/arrays/interval.py
Labels: Docs

#58675 DOC: Fix Docstring Validation for pandas.Series.cat
  ci/code_checks.sh
  pandas/core/arrays/categorical.py
Labels: Docs

#58676 DOC: Add SA01 for pandas.Timestamp.asm8
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58677 DOC: Enforce Numpy Docstring Validation - Timestamp.strftime and Timestamp.isoformat
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58674 DOC: Enforce Numpy Docstring Validation Timestamp.week
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58665 BUG: DatetimeIndex.is_year_start breaks on custom business days frequencies bigger then `1C`
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/fields.pyx
  pandas/tests/indexes/datetimes/test_scalar_compat.py
Labels: Bug, Frequency

#58686 A typo in user guide doc
  doc/source/user_guide/merging.rst
Labels: Docs

#58682 DOC: add PR07 for pandas.Index
  ci/code_checks.sh
  pandas/core/indexes/base.py
Labels: Docs

#58683 DOC: add RT03,SA01 for pandas.IntervalIndex.set_closed and pandas.arrays.IntervalArray.set_closed
  ci/code_checks.sh
  pandas/core/arrays/interval.py
Labels: Docs

#58688 DOC: Fix SA01 for pandas.SparseDtype
  ci/code_checks.sh
  pandas/core/dtypes/dtypes.py
Labels: Docs

#58687 DOC: Add GL08 for pandas.intervalIndex.left
  ci/code_checks.sh
  pandas/core/indexes/interval.py
Labels: Docs

#58698 DOC: Fix Docstring Validation for pandas.Series.case_when
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58699 DOC: Fix Docstring Validation for pandas.Series.str.translate
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs

#58702 DOC: Fix PR02 for pandas.tseries.offsets.BYearBegin and pandas.tseries.offsets.YearBegin
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#58704 DOC: add RT03,SA01 for pandas.api.extensions.ExtensionArray.copy
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#58705 DOC: add SA01 for pandas.api.extensions.ExtensionArray.shape
  ci/code_checks.sh
  pandas/core/arrays/base.py
Labels: Docs

#58708 Sentence restructured in compare methods's doc
  doc/source/user_guide/merging.rst
Labels: Docs

#58706 DOC: Grammar improvements in getting started tutorials
  doc/source/getting_started/intro_tutorials/01_table_oriented.rst
  doc/source/getting_started/intro_tutorials/02_read_write.rst
  doc/source/getting_started/intro_tutorials/03_subset_data.rst
  doc/source/getting_started/intro_tutorials/04_plotting.rst
  doc/source/getting_started/intro_tutorials/05_add_columns.rst
  doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
  doc/source/getting_started/intro_tutorials/08_combine_dataframes.rst
  doc/source/getting_started/intro_tutorials/09_timeseries.rst
  doc/source/getting_started/intro_tutorials/10_text_data.rst
Labels: Docs

#58692 TST: Test searchsorted for monotonic decreasing index
  pandas/tests/indexes/test_common.py
Labels: Docs

#58646 CLN: int slice on Index[float] as positional
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/base.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/test_floats.py
Labels: Indexing, Clean

#58693 TST: Fix CI failures (don't xfail postgresql / don't xfail for pyarrow=16)
  pandas/tests/io/parser/test_multi_thread.py
  pandas/tests/io/test_sql.py
Labels: Testing

#58680 DOC: Update Python version support
  doc/source/development/policies.rst
  doc/source/getting_started/install.rst
Labels: Docs

#58709 Backport PR #58693 on branch 2.2.x (TST: Fix CI failures (don't xfail postgresql / don't xfail for pyarrow=16))
  pandas/tests/io/parser/test_multi_thread.py
  pandas/tests/io/test_sql.py
Labels: Testing

#58717 DOC: Fix typo in indexing.rst
  doc/source/user_guide/indexing.rst
Labels: Docs

#58703 DOC: fix PR02 for pandas.tseries.offsets.MonthEnd methods
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#58701 DOC: Fix SA01 ES01 for pandas.Timestamp.to_pydatetime
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58700 DOC: Fix SA01 ES01 for pandas.Timestamp.round
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58718 DOC: Fix PR07 for pandas.Series.div and pandas.Series.truediv
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58719 CI: xfail test_to_xarray_index_types due to new 2024.5 release
  pandas/tests/generic/test_to_xarray.py
Labels: CI, Dependencies

#58720 Backport PR #58719 on branch 2.2.x (CI: xfail test_to_xarray_index_types due to new 2024.5 release)
  pandas/tests/generic/test_to_xarray.py
Labels: CI, Dependencies

#58728 DOC: Added clarification for the input to pandas.core.series.Series
  pandas/core/series.py
Labels: Docs

#58726 BUG: Fixed ChainedAssignmentError link to documentation will break? #58716
  pandas/errors/cow.py
Labels: Docs

#58725 DOC: Fix Docstring validation for pandas.Series.floordiv and others
  ci/code_checks.sh
  pandas/core/ops/docstrings.py
Labels: Docs

#58655 CLN: Stopped dtype inference in sanitize_array with Index[object]
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/construction.py
  pandas/core/frame.py
  pandas/tests/frame/indexing/test_setitem.py
Labels: Dtype Conversions, Clean

#58668 CLN: Remove deprecated read_csv(delim_whitespace=)
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/errors/__init__.py
  pandas/io/clipboards.py
  pandas/io/parsers/readers.py
  pandas/tests/io/parser/common/test_common_basic.py
  pandas/tests/io/parser/common/test_read_errors.py
  pandas/tests/io/parser/test_c_parser_only.py
  pandas/tests/io/parser/test_comment.py
  pandas/tests/io/parser/test_header.py
  pandas/tests/io/parser/test_read_fwf.py
  pandas/tests/io/parser/test_skiprows.py
  pandas/tests/io/parser/test_unsupported.py
  pandas/tests/io/parser/usecols/test_usecols_basic.py
Labels: IO CSV, Clean

#58724 DEPR: Deprecate method argument of reindex_like
  doc/source/whatsnew/v3.0.0.rst
  pandas/conftest.py
  pandas/core/generic.py
  pandas/io/formats/style.py
  pandas/tests/frame/methods/test_reindex_like.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/series/methods/test_reindex_like.py
Labels: Deprecate

#58689 STY: Enable all sphinx-lint rules
  .pre-commit-config.yaml
  doc/source/development/maintaining.rst
  doc/source/whatsnew/v0.15.0.rst
  doc/source/whatsnew/v0.15.2.rst
  doc/source/whatsnew/v0.24.0.rst
  doc/source/whatsnew/v0.25.0.rst
  doc/source/whatsnew/v1.1.4.rst
Labels: Code Style

#58735 DOC: add PR01,RT03,SA01 to pandas.Series.var docstring
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58736 DOC: fix SA01 error for pandas.Series.swaplevel
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58710 CI: Clear CI caches daily instead of weekly
  .github/workflows/cache-cleanup-daily.yml
Labels: CI

#58733 PERF: Eliminate circular references in accessor attributes
  LICENSES/XARRAY_LICENSE
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/accessor.py
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/strings/test_api.py
  pandas/tests/test_register_accessor.py
Labels: Performance, Accessors

#58740 DOC: fix formatting of date_format special options
  pandas/io/parsers/readers.py
Labels: Docs

#58742 DOC: Whatsnew for DataFrameGroupBy.__len__ with NA values bugfix
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs, Groupby, Missing-data

#58741 CLN: Misc copy-on-write cleanups
  pandas/_config/__init__.py
  pandas/_testing/contexts.py
  pandas/core/arrays/arrow/array.py
  pandas/core/indexing.py
  pandas/tests/copy_view/test_astype.py
  pandas/tests/indexes/base_class/test_constructors.py
  pandas/tests/indexing/test_chaining_and_caching.py
Labels: Clean, Copy / view semantics

#58739 CLN: Require ExtensionArray._reduce(keepdims=)
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/base.py
  pandas/core/frame.py
Labels: Clean, ExtensionArray

#58745 DOC: Sort whatsnew 3.0 entries
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs, Code Style

#58754 FIX: Keep CachedAccessor alias for downstream libraries
  pandas/core/accessor.py
Labels: Compat

#58645 CLN: Stopped casting values in Series/Index.isin for datelike dtypes
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/datetimelike.py
  pandas/tests/test_algos.py
Labels: Clean

#58753 DOC: Add SA01 ES01 for pandas.Timestamp.is_leap_year
  ci/code_checks.sh
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58752 DOC: Add SA01 ES01 for pandas.Timestamp.dst
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58755 DOC: Add SA01 for pandas.Series.le
  ci/code_checks.sh
  pandas/core/series.py
Labels: Docs

#58757 DOC: add SA01 ES01 for pandas.Timestamp.tz_convert and pandas.Timestamp.astimezone
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs

#58756 DOC: add SA01 for pandas.tseries.api.guess_datetime_format
  ci/code_checks.sh
  pandas/_libs/tslibs/parsing.pyx
Labels: Docs

#58763 DOC: add SA01 for pandas.Timestamp.isocalendar
  ci/code_checks.sh
  pandas/_libs/tslibs/nattype.pyx
  pandas/_libs/tslibs/timestamps.pyx
Labels: Docs
