Repository pandas-dev/pandas, pull requests merged in 2024-02, with the labels that each got.

#56633 CoW: Enable CoW by default and remove warning build
  .github/workflows/unit-tests.yml
  asv_bench/benchmarks/algos/isin.py
  asv_bench/benchmarks/strings.py
  pandas/_config/__init__.py
  pandas/conftest.py
  pandas/core/generic.py
  pandas/core/indexes/multi.py
  pandas/tests/copy_view/test_internals.py
  pandas/tests/extension/conftest.py
  pandas/tests/frame/methods/test_copy.py
  pandas/tests/series/test_ufunc.py
  pandas/tests/test_downstream.py
  pandas/util/_test_decorators.py
Labels: Copy / view semantics

#57190 CI: Pinning doc previewer action to current release
  .github/workflows/comment-commands.yml
Labels: Docs, CI

#57194 fix typo
  pandas/core/window/rolling.py
Labels: Docs

#57186 DEPR: Enforce deprecation of groupby(..., axis=1)
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/window.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/resample.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/core/series.py
  pandas/core/shared_docs.py
  pandas/core/window/ewm.py
  pandas/core/window/expanding.py
  pandas/core/window/numba_.py
  pandas/core/window/online.py
  pandas/core/window/rolling.py
  pandas/plotting/_matplotlib/boxplot.py
  pandas/tests/apply/test_str.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/methods/test_describe.py
  pandas/tests/groupby/methods/test_nth.py
  pandas/tests/groupby/methods/test_quantile.py
  pandas/tests/groupby/methods/test_size.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_filters.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_indexing.py
  pandas/tests/groupby/test_numba.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/plotting/test_boxplot_method.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/test_multilevel.py
  pandas/tests/window/test_api.py
  pandas/tests/window/test_apply.py
  pandas/tests/window/test_ewm.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_numba.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_timeseries_window.py
  pandas/tests/window/test_win_type.py
Labels: Groupby, Deprecate

#57173 BUG: pandas int extension dtypes has no attribute byteorder
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/interchange/column.py
  pandas/tests/interchange/test_impl.py
Labels: NA - MaskedArrays, Interchange

#57145 DOC: fix PR02 errors in docstrings - pandas.core.groupby.SeriesGroupBy.idxmax, pandas.core.groupby.SeriesGroupBy.idxmin
  ci/code_checks.sh
  pandas/core/groupby/generic.py
Labels: Docs

#57103 ENH: Add check for character limmit
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/io/excel/_base.py
  pandas/tests/io/excel/test_writers.py
Labels: Enhancement, IO Excel, Warnings

#57163 CI: Add macOS M1 CI
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39.yaml
  pyproject.toml
Labels: Build, CI, OS X

#57174 BUG: Interchange protocol implementation allows non-string column names
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/interchange/column.py
  pandas/core/interchange/dataframe.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#57202 Backport PR #57163 on branch 2.2.x (CI: Add macOS M1 CI)
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39.yaml
  pyproject.toml
Labels: Build, CI, OS X

#57203 Backport PR #57174 on branch 2.2.x (BUG: Interchange protocol implementation allows non-string column names)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/interchange/column.py
  pandas/core/interchange/dataframe.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#57210 DOC: fix PR02 errors in docstrings - pandas.core.groupby.SeriesGroupBy.transform and pandas.core.groupby.DataFrameGroupBy.transform
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Clean

#57211 DOC: fix PR02 errors in docstrings - pandas.core.window.rolling.Rolling.quantile, pandas.core.window.expanding.Expanding.quantile
  ci/code_checks.sh
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Docs, Clean

#57096 CLN: Move capitalize_first_letter to where it's used
  pandas/core/dtypes/dtypes.py
  pandas/util/__init__.py
Labels: Clean

#57200 STY: Enable some passing rules
  pandas/_libs/tslibs/vectorized.pyi
  pandas/core/indexers/objects.py
  pandas/io/formats/style_render.py
  pandas/io/json/_normalize.py
  pandas/tests/arrays/masked/test_arithmetic.py
  pandas/tests/copy_view/index/test_index.py
  pandas/tests/frame/test_query_eval.py
  pandas/tests/io/test_feather.py
  pandas/tests/plotting/common.py
  pandas/tests/reshape/test_pivot.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_rolling.py
  pyproject.toml
Labels: Code Style

#57199 TST/CLN: Assorted
  pandas/tests/config/test_localization.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/indexes/datetimes/test_constructors.py
Labels: Testing, Clean

#57201 CLN: pyproject.toml
  pyproject.toml
  scripts/tests/data/deps_minimum.toml
Labels: Clean

#57208 REF: Remove internals.base
  pandas/core/frame.py
  pandas/core/internals/__init__.py
  pandas/core/internals/base.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_api.py
Labels: Refactor, Internals

#57060 check ExtensionType in is_datetime64_any_dtype for array-likes
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/dtypes/common.py
  pandas/tests/extension/test_arrow.py
Labels: ExtensionArray

#55642 ENH: read_stata return non-nano
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata, Non-Nano

#56792 Series.str.find fix for pd.ArrowDtype(pa.string())
  pandas/core/arrays/arrow/array.py
  pandas/tests/extension/test_arrow.py
Labels: Strings, Arrow

#57207 DEPR: Enforce deprecation of groupby(...).grouper
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/tests/groupby/test_grouping.py
Labels: Groupby

#57218 BUG: Fixing broken link in getting_started.md
  web/pandas/getting_started.md
Labels: Web

#57221 TST: Reduce parameterization of test_str_find_e2e
  pandas/tests/extension/test_arrow.py
Labels: Testing

#57227 Update style.ipynb http -> https
  doc/source/user_guide/style.ipynb
Labels: Docs

#57228 TYP: misc IO return types
  pandas/_typing.py
  pandas/io/excel/_openpyxl.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/info.py
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/io/html.py
  pandas/io/json/_normalize.py
  pandas/io/parquet.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/parsers/readers.py
  pandas/io/sas/sas7bdat.py
  pandas/io/sql.py
  pandas/io/stata.py
Labels: Typing

#57225 BUG: Raise if an aggregation function other than mean is used with ewm and times
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/window/ewm.py
  pandas/tests/window/test_ewm.py
Labels: Window

#57230 DOC: fix PR02 errors in docstring for pandas.io.formats.style.Styler.to_excel
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/io/formats/style.py
Labels: Docs, IO Excel

#57234 Remove Copy-on-Write warning mode
  pandas/_config/__init__.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/errors/cow.py
Labels: Copy / view semantics

#57237 Remove Copy-on-Write warning mode from tests
  pandas/conftest.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/computation/test_eval.py
  pandas/tests/copy_view/index/test_index.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
  pandas/tests/copy_view/test_clip.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_core_functionalities.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/copy_view/test_replace.py
  pandas/tests/copy_view/test_setitem.py
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_pop.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/frame/methods/test_update.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/groupby/test_apply_mutate.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/indexes/period/test_partial_slicing.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iat.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/methods/test_copy.py
  pandas/tests/series/methods/test_get_numeric_data.py
  pandas/tests/series/methods/test_rename.py
  pandas/tests/series/test_constructors.py
Labels: Copy / view semantics

#57238 Remove Copy-on-Write builds
  .github/workflows/unit-tests.yml
Labels: CI, Copy / view semantics

#57232 REGR: to_json converting nullable ints to floats
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/io/json/test_pandas.py
Labels: Regression, IO JSON

#57240 Backport PR #57232 on branch 2.2.x (REGR: to_json converting nullable ints to floats)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/io/json/test_pandas.py
Labels: Regression, IO JSON

#57242 DOC: Fix typo in merging.rst
  doc/source/user_guide/merging.rst
Labels: Docs

#57246 DEPR: Remove first and last from DataFrame
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_first_and_last.py
  pandas/tests/generic/test_finalize.py
Labels: Deprecate, DataFrame

#56614 DEPR: Remove SettingWithCopyWarning
  doc/source/reference/testing.rst
  doc/source/user_guide/advanced.rst
  doc/source/user_guide/indexing.rst
  doc/source/whatsnew/v0.13.0.rst
  doc/source/whatsnew/v0.13.1.rst
  doc/source/whatsnew/v1.5.0.rst
  pandas/_config/__init__.py
  pandas/core/apply.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexes/accessors.py
  pandas/core/indexing.py
  pandas/core/interchange/from_dataframe.py
  pandas/core/internals/managers.py
  pandas/core/series.py
  pandas/errors/__init__.py
  pandas/io/json/_json.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
  pandas/tests/copy_view/test_clip.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_asof.py
  pandas/tests/frame/methods/test_sample.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexes/multi/test_get_set.py
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/series/accessors/test_dt_accessor.py
  pandas/tests/series/methods/test_sort_values.py
  pandas/tests/test_downstream.py
  pandas/tests/test_errors.py
Labels: Copy / view semantics

#57236 DOC: Clarifying brackets vs. parentheses
  doc/source/getting_started/intro_tutorials/02_read_write.rst
  doc/source/getting_started/intro_tutorials/03_subset_data.rst
  doc/source/getting_started/intro_tutorials/05_add_columns.rst
  doc/source/getting_started/intro_tutorials/06_calculate_statistics.rst
Labels: Docs

#57249 Update type hint in io/formats/format.py
  pandas/io/formats/format.py
Labels: Typing

#57223 DOC: Replace pandas logo with a conditional image for light and dark …
  README.md
Labels: Docs

#57212 BUG: ensure_string_array might modify read-only array inplace
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/copy_view/test_astype.py
Labels: Bug, Strings

#57247 Fix errors in docstring for `pandas.PeriodIndex`
  ci/code_checks.sh
  pandas/core/indexes/period.py
Labels: Docs, Period

#57239 DOC: fix PR02 errors in docstring for pandas.Series.rename_axis
  ci/code_checks.sh
  pandas/core/generic.py
  pandas/core/series.py
Labels: Docs

#57253 CoW: Enforce some deprecations on the block level
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/series.py
Labels: Copy / view semantics

#57255 CoW: Remove copy-on-write conditions from frame tests
  pandas/tests/frame/indexing/test_getitem.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/frame/indexing/test_insert.py
  pandas/tests/frame/indexing/test_setitem.py
  pandas/tests/frame/indexing/test_xs.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/frame/methods/test_cov_corr.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/methods/test_rename.py
  pandas/tests/frame/methods/test_set_axis.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/methods/test_to_dict_of_blocks.py
  pandas/tests/frame/methods/test_to_numpy.py
  pandas/tests/frame/methods/test_transpose.py
  pandas/tests/frame/methods/test_update.py
  pandas/tests/frame/methods/test_values.py
  pandas/tests/frame/test_api.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_constructors.py
Labels: Copy / view semantics

#57261 DOC: fix PR02 errors in docstrings of Index subclasses
  ci/code_checks.sh
  pandas/core/indexes/extension.py
Labels: Docs

#57235 DOC: Updated docstring for set_option
  ci/code_checks.sh
  pandas/_config/config.py
Labels: Docs

#57184 Use ruff to detect banned import
  .pre-commit-config.yaml
  pandas/io/common.py
  pyproject.toml
  scripts/tests/test_use_io_common_urlopen.py
  scripts/use_io_common_urlopen.py
Labels: Code Style

#57226 WEB: Using Bootstrap icon instead of font awesome icons
  web/pandas/_templates/layout.html
  web/pandas/index.html
Labels: Web

#57256 TYP: misc Index return types
  pandas/_typing.py
  pandas/core/generic.py
  pandas/core/indexes/accessors.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/datetimes.py
  pandas/core/indexes/multi.py
  pandas/core/indexes/range.py
  pandas/core/indexes/timedeltas.py
  pyproject.toml
Labels: Typing

#57265 COMPAT: Numpy 2.0 casting compat
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/test_constructors.py
Labels: Compat

#57271 Backport PR #57265 on branch 2.2.x (COMPAT: Numpy 2.0 casting compat)
  pandas/core/dtypes/cast.py
  pandas/core/internals/blocks.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/test_constructors.py
Labels: Compat

#57270 CoW: Remove cow branches from more tests
  pandas/tests/indexing/multiindex/test_chaining_and_caching.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  pandas/tests/indexing/test_iat.py
  pandas/tests/indexing/test_iloc.py
  pandas/tests/indexing/test_loc.py
  pandas/tests/series/indexing/test_indexing.py
  pandas/tests/series/indexing/test_setitem.py
  pandas/tests/series/methods/test_align.py
  pandas/tests/series/methods/test_copy.py
  pandas/tests/series/methods/test_get_numeric_data.py
  pandas/tests/series/methods/test_rename.py
  pandas/tests/series/methods/test_sort_values.py
  pandas/tests/series/methods/test_update.py
  pandas/tests/series/test_constructors.py
Labels: Copy / view semantics

#57243 DOC: fix PR02 errors in docstring for pandas.core.groupby.DataFrameGroupBy.corrwith
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/core/groupby/generic.py
Labels: Docs, Groupby

#57241 DEPR: Remove sql.execute, *args/**kwargs in resample, unrecognized timezones
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/parsing.pyx
  pandas/core/resample.py
  pandas/io/sql.py
  pandas/tests/io/test_sql.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/tools/test_to_datetime.py
Labels: Clean

#57278 Remove codecov CI output
  .github/actions/run-tests/action.yml
Labels: CI

#57279 CLN: Make first argument in IO writers keyword only; remove gbq
  asv_bench/benchmarks/io/hdf.py
  doc/redirects.csv
  doc/source/conf.py
  doc/source/getting_started/install.rst
  doc/source/reference/frame.rst
  doc/source/reference/io.rst
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/__init__.py
  pandas/_typing.py
  pandas/compat/_optional.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/io/api.py
  pandas/io/gbq.py
  pandas/tests/api/test_api.py
  pandas/tests/frame/methods/test_to_dict.py
  pandas/tests/io/excel/test_writers.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/formats/test_to_html.py
  pandas/tests/io/formats/test_to_latex.py
  pandas/tests/io/formats/test_to_markdown.py
  pandas/tests/io/formats/test_to_string.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_clipboard.py
  pandas/tests/io/test_gbq.py
  pandas/tests/io/test_parquet.py
  pandas/tests/io/test_pickle.py
  pandas/tests/io/test_sql.py
  pyproject.toml
  scripts/validate_min_versions_in_sync.py
Labels: IO Data

#57042 API: MultiIndex.names|codes|levels returns tuples
  doc/source/user_guide/groupby.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/index.pyi
  pandas/core/groupby/groupby.py
  pandas/core/indexes/base.py
  pandas/core/indexes/frozen.py
  pandas/core/indexes/multi.py
  pandas/core/resample.py
  pandas/core/reshape/melt.py
  pandas/core/reshape/merge.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/core/strings/accessor.py
  pandas/core/window/rolling.py
  pandas/tests/frame/methods/test_rename_axis.py
  pandas/tests/frame/methods/test_set_index.py
  pandas/tests/frame/methods/test_sort_values.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_series.py
  pandas/tests/groupby/methods/test_quantile.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/indexes/multi/test_astype.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/indexes/multi/test_copy.py
  pandas/tests/indexes/multi/test_duplicates.py
  pandas/tests/indexes/multi/test_formats.py
  pandas/tests/indexes/multi/test_get_set.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/indexes/multi/test_names.py
  pandas/tests/indexes/multi/test_reindex.py
  pandas/tests/indexes/multi/test_reshape.py
  pandas/tests/indexes/multi/test_setops.py
  pandas/tests/indexes/multi/test_sorting.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_common.py
  pandas/tests/indexes/test_frozen.py
  pandas/tests/indexing/multiindex/test_partial.py
  pandas/tests/io/json/test_json_table_schema.py
  pandas/tests/io/pytables/test_store.py
  pandas/tests/io/test_sql.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/merge/test_multi.py
  pandas/tests/reshape/test_crosstab.py
  pandas/tests/series/methods/test_rename_axis.py
  pandas/tests/test_common.py
  pandas/tests/util/test_assert_index_equal.py
  pandas/tests/window/test_rolling.py
Labels: MultiIndex

#57285 TYP: misc return types
  pandas/_typing.py
  pandas/core/_numba/extensions.py
  pandas/core/arrays/_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/dtypes/dtypes.py
  pandas/core/dtypes/generic.py
  pandas/core/groupby/generic.py
  pandas/core/indexing.py
  pandas/core/interchange/from_dataframe.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/core/ops/array_ops.py
  pandas/core/ops/mask_ops.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/tile.py
  pandas/core/strings/base.py
  pandas/core/tools/datetimes.py
Labels: Typing

#55738 REF: Compute complete result_index upfront in groupby
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/groupby/grouper.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/reshape/pivot.py
  pandas/tests/groupby/methods/test_value_counts.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_grouping.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/test_timegrouper.py
  pandas/tests/reshape/test_pivot.py
Labels: Bug, Refactor, Groupby, Categorical

#56945 ENH: raise ValueError if invalid period freq pass to asfreq when the index of df is a PeriodIndex
  doc/source/whatsnew/v2.2.1.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/period.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/period/methods/test_asfreq.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
Labels: Frequency

#57292 Backport PR #56945 on branch 2.2.x (ENH: raise ValueError if invalid period freq pass to asfreq when the index of df is a PeriodIndex)
  doc/source/whatsnew/v2.2.1.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/core/arrays/period.py
  pandas/plotting/_matplotlib/timeseries.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/indexes/datetimes/methods/test_to_period.py
  pandas/tests/indexes/period/methods/test_asfreq.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/scalar/period/test_asfreq.py
  pandas/tests/scalar/period/test_period.py
Labels: Frequency

#57233 REGR: Fix to_numpy conversion for arrow ea with float dtype given
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/_utils.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/arrays/floating/test_to_numpy.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/series/methods/test_to_numpy.py
Labels: Arrow

#57294 Backport PR #57233 on branch 2.2.x (REGR: Fix to_numpy conversion for arrow ea with float dtype given)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/_utils.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/arrays/floating/test_to_numpy.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/series/methods/test_to_numpy.py
Labels: Arrow

#57289 DOC: fix typo: "two solution"
  doc/source/user_guide/copy_on_write.rst
Labels: Docs

#57266 DOC: fix pr02 errors in docstrings - plot.bar, plot.barh, plot.line, plot.pie
  ci/code_checks.sh
  pandas/plotting/_core.py
Labels: Docs, Visualization

#57231 DEPR: Remove Index type checking attributes
  doc/source/reference/index.rst
  doc/source/reference/indexing.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/base.py
  pandas/io/formats/format.py
  pandas/plotting/_core.py
  pandas/plotting/_matplotlib/core.py
  pandas/tests/indexes/test_old_base.py
Labels: Index

#57288 DOC: fix PR02 errors in docstring for pandas.core.groupby.SeriesGroupBy.apply
  ci/code_checks.sh
  pandas/core/groupby/generic.py
  pandas/core/groupby/groupby.py
  scripts/validate_unwanted_patterns.py
Labels: Docs

#57306 TST: adds a test to check signedness preservation after sum
  pandas/tests/reductions/test_reductions.py
Labels: Testing

#57319 CLN: Remove Series.view/ravel, fastpath
  doc/redirects.csv
  doc/source/reference/series.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/series.py
  pandas/tests/copy_view/test_array.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_methods.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/series/methods/test_view.py
  pandas/tests/series/test_api.py
Labels: Clean, Series

#57304 DOC: fix PR02 errors in docstring for pandas.core.groupby.DataFrameGroupBy.hist
  ci/code_checks.sh
  pandas/core/groupby/generic.py
Labels: Docs

#57297 BUG: sort_index(1, ignore_index=True, ascending=False)
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_sort_index.py
Labels: Bug

#57309 DOC: fix reference to api.typing.NaTType (from api.types.NaTType)
  doc/source/user_guide/missing_data.rst
Labels: Docs

#57295 BUG: Updated _pprint_seq to use enumerate instead of next
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/printing.py
  pandas/tests/io/formats/test_to_string.py
Labels: Bug, Output-Formatting

#57272 PERF: reindex default fill_value dtype
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_reindex.py
Labels: Missing-data, Dtype Conversions

#57252 PERF: RangeIndex.append with the same index
  asv_bench/benchmarks/index_object.py
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexes/range.py
Labels: Performance, Index

#57308 CLN: Remove .bool(), __init__, __float__ from DataFrame/Series
  .pre-commit-config.yaml
  doc/redirects.csv
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/user_guide/basics.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/conftest.py
  pandas/core/generic.py
  pandas/core/series.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_generic.py
  pandas/tests/generic/test_series.py
  pandas/tests/series/test_api.py
  scripts/no_bool_in_generic.py
  scripts/tests/test_no_bool_in_generic.py
Labels: Clean

#57254 CoW: Enforce some deprecations on the datafame level
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/grouper.py
  pandas/core/series.py
Labels: Copy / view semantics

#57121 REGR: Fix to_numpy for masked array with non-numeric dtype
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/masked.py
  pandas/tests/arrays/masked/test_function.py
Labels: NA - MaskedArrays

#57250 REGR/DOC: pd.concat should special case DatetimeIndex to sort even when sort=False
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/indexes/api.py
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_datetimes.py
Labels: Docs, Reshaping, Regression

#57269 CoW: Finish deprecation enforcal on block level
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/internals/test_internals.py
Labels: Copy / view semantics

#57296 CLN: Remove pandas.value_counts, Index.format, is_interval, is_period
  asv_bench/benchmarks/strftime.py
  doc/redirects.csv
  doc/source/reference/arrays.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/__init__.py
  pandas/_libs/lib.pyi
  pandas/_libs/lib.pyx
  pandas/core/algorithms.py
  pandas/core/api.py
  pandas/core/dtypes/api.py
  pandas/core/dtypes/common.py
  pandas/core/dtypes/inference.py
  pandas/core/indexes/base.py
  pandas/core/indexes/datetimelike.py
  pandas/core/indexes/multi.py
  pandas/tests/api/test_api.py
  pandas/tests/api/test_types.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/indexes/base_class/test_formats.py
  pandas/tests/indexes/categorical/test_formats.py
  pandas/tests/indexes/datetimes/test_formats.py
  pandas/tests/indexes/multi/test_formats.py
  pandas/tests/indexes/period/test_formats.py
  pandas/tests/indexes/ranges/test_range.py
  pandas/tests/indexes/test_base.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/series/test_formats.py
  pandas/tests/test_algos.py
Labels: Clean

#57325 Backport PR #57121 on branch 2.2.x (REGR: Fix to_numpy for masked array with non-numeric dtype)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/masked.py
  pandas/tests/arrays/masked/test_function.py
Labels: NA - MaskedArrays

#57326 Backport PR #57250 on branch 2.2.x (REGR/DOC: pd.concat should special case DatetimeIndex to sort even when sort=False)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/indexes/api.py
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_datetimes.py
Labels: Docs, Reshaping, Regression

#57327 CoW: Remove copy-keywords as far as possible
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/groupby/groupby.py
  pandas/core/indexing.py
  pandas/core/internals/blocks.py
  pandas/core/internals/concat.py
  pandas/core/internals/managers.py
  pandas/core/reshape/merge.py
  pandas/core/series.py
Labels: Copy / view semantics

#57322 REGR: Fix astype conversion of ea int to td/dt with missing values
  pandas/core/arrays/_utils.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/series/methods/test_to_numpy.py
Labels: Dtype Conversions, NA - MaskedArrays

#57331 Backport PR #57322 on branch 2.2.x (REGR: Fix astype conversion of ea int to td/dt with missing values)
  pandas/core/arrays/_utils.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/series/methods/test_to_numpy.py
Labels: Dtype Conversions, NA - MaskedArrays

#57329 REGR: CategoricalIndex.difference with null values
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/indexes/base.py
  pandas/tests/indexes/categorical/test_setops.py
Labels: Regression, Categorical, setops

#57330 CLN: Enforce change in default value of observed
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/core/reshape/pivot.py
  pandas/core/series.py
  pandas/core/shared_docs.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/reshape/test_pivot.py
Labels: Groupby, Categorical, Clean

#57332 CLN: Enforce deprecation of Series.agg using Series.apply
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/apply.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_series_apply.py
Labels: Clean, Apply

#57307 CLN: Remove literal string/bytes support in IO readers
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v0.12.0.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/excel/_base.py
  pandas/io/formats/xml.py
  pandas/io/html.py
  pandas/io/json/_json.py
  pandas/io/xml.py
  pandas/tests/io/excel/test_readers.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_html.py
  pandas/tests/io/xml/test_to_xml.py
  pandas/tests/io/xml/test_xml.py
Labels: IO Data, Clean

#57164 WEB: Adding Effective pandas 2 book to home page
  web/pandas/getting_started.md
  web/pandas/index.html
  web/pandas/static/img/books/effective_pandas_2.gif
  web/pandas/static/img/books/pydata_book.gif
Labels: Web

#57333 REGR: merge with 3rd party EA's can sometimes raise ValueError
  doc/source/whatsnew/v2.2.1.rst
  pandas/_libs/index.pyx
  pandas/tests/indexes/test_base.py
Labels: Reshaping, Regression

#57337 Backport PR #57333 on branch 2.2.x (REGR: merge with 3rd party EA's can sometimes raise ValueError)
  doc/source/whatsnew/v2.2.1.rst
  pandas/_libs/index.pyx
  pandas/tests/indexes/test_base.py
Labels: Reshaping, Regression

#57323 REGR: Fix regression when grouping over a Series
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
Labels: Regression, Copy / view semantics

#57339 Backport PR #57323 on branch 2.2.x (REGR: Fix regression when grouping over a Series)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/internals/managers.py
  pandas/tests/copy_view/test_methods.py
Labels: Regression, Copy / view semantics

#57345 Remove DataFrame.applymap and Styler.applymap
  doc/redirects.csv
  doc/source/reference/frame.rst
  doc/source/user_guide/10min.rst
  doc/source/whatsnew/v0.20.0.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/errors/__init__.py
  pandas/io/formats/style.py
  pandas/tests/frame/methods/test_map.py
  pandas/tests/io/formats/style/test_style.py
Labels: DataFrame, Styler

#57353 DOC: Add missing doc `Index.array` and `Index.to_numpy`
  doc/source/reference/indexing.rst
Labels: Docs

#57371 Remove close from StataReader
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: IO Stata

#57370 Remove use_nullable_dtypes from read_parquet
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/parquet.py
  pandas/tests/io/test_parquet.py
Labels: IO Parquet

#57368 CoW: Remove more using_copy_on_write fixtures
  pandas/tests/copy_view/index/test_datetimeindex.py
  pandas/tests/copy_view/index/test_index.py
  pandas/tests/copy_view/index/test_periodindex.py
  pandas/tests/copy_view/index/test_timedeltaindex.py
  pandas/tests/copy_view/test_array.py
  pandas/tests/copy_view/test_astype.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
  pandas/tests/copy_view/test_clip.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/copy_view/test_core_functionalities.py
  pandas/tests/copy_view/test_indexing.py
  pandas/tests/copy_view/test_internals.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/copy_view/test_replace.py
  pandas/tests/copy_view/test_setitem.py
Labels: Copy / view semantics

#57367 CoW: Remove Copy-on-Write fixtures from more tests
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/computation/test_eval.py
  pandas/tests/extension/base/setitem.py
  pandas/tests/extension/conftest.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/extension/test_sparse.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/reshape/concat/test_concat.py
  pandas/tests/reshape/concat/test_dataframe.py
  pandas/tests/reshape/concat/test_index.py
Labels: Copy / view semantics

#57364 CoW: Remove item_cache benchmarks
  asv_bench/benchmarks/frame_methods.py
Labels: Benchmark, Copy / view semantics

#57348 Remove fillna from Resampler
  doc/redirects.csv
  doc/source/reference/resampling.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/resample.py
  pandas/tests/resample/test_resample_api.py
Labels: Resample

#57369 Remove convert_dtype from Series.apply
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/algorithms.py
  pandas/core/apply.py
  pandas/core/base.py
  pandas/core/series.py
  pandas/tests/apply/test_series_apply.py
Labels: Clean

#57341 REGR: assert_series_equal defaulting to check_exact=True for Index
  doc/source/whatsnew/v2.2.1.rst
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Testing, Regression

#57340 REGR: shift raising for axis=1 and empty df
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_shift.py
Labels: DataFrame

#57334 DOC: fix PR02 errors in docstring for pandas.core.groupby.DataFrameGroupBy.rolling and pandas.core.groupby.SeriesGroupBy.rolling
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/test_groupby.py
Labels: Docs, Code Style

#57352 CI/DOC: Enforce SA05 in CI
  ci/code_checks.sh
Labels: Code Style

#57379 Fix numpy-dev CI warnings
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
Labels: CI, IO JSON, Compat

#57380 Backport PR #57341 on branch 2.2.x (REGR: assert_series_equal defaulting to check_exact=True for Index)
  doc/source/whatsnew/v2.2.1.rst
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_series_equal.py
Labels: Testing, Regression

#57381 Backport PR #57340 on branch 2.2.x (REGR: shift raising for axis=1 and empty df)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_shift.py
Labels: DataFrame

#56758 TST: assert that informative error is raised when offset not supported as a period frequency is passed to DataFrame.asfreq
  pandas/tests/frame/methods/test_asfreq.py
Labels: Needs Tests

#57383 Backport PR #57379 on branch 2.2.x (Fix numpy-dev CI warnings)
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
Labels: CI, IO JSON, Compat

#56175 ENH: Allow dictionaries to be passed to pandas.Series.str.replace
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/strings/accessor.py
  pandas/tests/strings/test_find_replace.py
Labels: Enhancement, API Design, Strings

#56739 TYP: mostly DataFrame return overloads
  pandas/core/base.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/reshape/encoding.py
  pandas/core/series.py
Labels: DataFrame, Typing

#57389 TST: Ensure Matplotlib is always cleaned up
  pandas/conftest.py
  pandas/tests/io/formats/style/test_matplotlib.py
  pandas/tests/plotting/conftest.py
  pandas/tests/test_downstream.py
Labels: Testing

#57321 DOC: fix PR02 errors in docstring for pandas.Series.str.wrap
  ci/code_checks.sh
  pandas/core/strings/accessor.py
Labels: Docs, Code Style

#57283 Translate more banned import config to ruff
  .pre-commit-config.yaml
  doc/make.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
  pyproject.toml
  web/tests/test_pandas_web.py
Labels: Code Style

#57394 TST: Fix test_str_encode on big endian machines
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#57393 TST: Fix IntervalIndex constructor tests on big-endian systems
  pandas/tests/indexes/interval/test_constructors.py
Labels: Testing, Interval

#57344 Remove limit, fill_axis, broadcast_axis and method parameters from align
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_align.py
  pandas/tests/series/methods/test_align.py
Labels: Clean

#57342 Remove support for DataFrames from df.from_records
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/copy_view/test_constructors.py
  pandas/tests/frame/constructors/test_from_records.py
Labels: Clean

#57328 Enforce silent downcasting deprecation
  doc/source/reference/frame.rst
  doc/source/reference/series.rst
  doc/source/user_guide/basics.rst
  doc/source/whatsnew/v2.2.0.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/core/internals/blocks.py
  pandas/core/internals/managers.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/copy_view/test_interp_fillna.py
  pandas/tests/frame/indexing/test_where.py
  pandas/tests/frame/methods/test_clip.py
  pandas/tests/frame/methods/test_fillna.py
  pandas/tests/frame/methods/test_interpolate.py
  pandas/tests/frame/methods/test_quantile.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/frame/test_logical_ops.py
  pandas/tests/groupby/test_api.py
  pandas/tests/groupby/transform/test_transform.py
  pandas/tests/indexing/test_coercion.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/series/indexing/test_where.py
  pandas/tests/series/methods/test_clip.py
  pandas/tests/series/methods/test_fillna.py
  pandas/tests/series/methods/test_interpolate.py
  pandas/tests/series/methods/test_reindex.py
  pandas/tests/series/methods/test_replace.py
  pandas/tests/series/test_api.py
  pandas/tests/series/test_arithmetic.py
Labels: Clean

#57343 Remove support for slices in take
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/indexing/test_take.py
Labels: Indexing

#57404 DOC: fix SA05 errors in docstring for pandas.DataFrame - agg, aggregate, boxplot
  ci/code_checks.sh
  pandas/core/frame.py
  pandas/plotting/_core.py
Labels: Docs

#57406 CLN: Misc pre-COW stuff
  pandas/_testing/__init__.py
  pandas/_testing/contexts.py
  pandas/core/internals/blocks.py
  pandas/errors/cow.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
  pandas/tests/copy_view/test_core_functionalities.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexing/multiindex/test_setitem.py
  pandas/tests/indexing/test_chaining_and_caching.py
  scripts/validate_unwanted_patterns.py
Labels: Clean, Copy / view semantics

#57405 CLN: Enforce nonkeyword deprecations
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/indexes/range.py
  pandas/core/series.py
Labels: Clean

#57387 CLN: Python 2 pickle/hdf support
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/pickle.py
  pandas/io/pytables.py
  pandas/tests/io/data/legacy_hdf/datetimetz_object.h5
  pandas/tests/io/data/legacy_hdf/gh26443.h5
  pandas/tests/io/data/legacy_hdf/legacy_table_fixed_datetime_py2.h5
  pandas/tests/io/data/legacy_hdf/legacy_table_fixed_py2.h5
  pandas/tests/io/data/legacy_hdf/legacy_table_py2.h5
  pandas/tests/io/data/legacy_hdf/periodindex_0.20.1_x86_64_darwin_2.7.13.h5
  pandas/tests/io/data/legacy_msgpack/0.20.3/0.20.3_x86_64_darwin_3.5.2.msgpack
  pandas/tests/io/data/pickle/test_mi_py27.pkl
  pandas/tests/io/data/pickle/test_py27.pkl
  pandas/tests/io/pytables/test_read.py
  pandas/tests/io/pytables/test_timezones.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_pickle.py
Labels: IO HDF5, IO Pickle

#57388 BUG: map(na_action=ignore) not respected for Arrow & masked types
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
Labels: NA - MaskedArrays, Arrow

#57413 Backport PR #57388 on branch 2.2.x (BUG: map(na_action=ignore) not respected for Arrow & masked types)
  doc/source/whatsnew/v2.2.1.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/masked.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
Labels: NA - MaskedArrays, Arrow

#57410 Remove downcast from Index.fillna
  pandas/core/indexes/base.py
  pandas/tests/indexes/test_old_base.py
Labels: Clean

#57408 DOC: fix SA05 errors in docstrings for pandas.PeriodIndex.asfreq, arr…
  ci/code_checks.sh
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/indexes/period.py
Labels: Docs

#57356 CI/DOC: Enforce RT03 in CI
  ci/code_checks.sh
Labels: Code Style

#57302 DEPR: Enforce deprecation of previous implementation of DataFrame.stack
  doc/source/getting_started/comparison/comparison_with_r.rst
  doc/source/user_guide/10min.rst
  doc/source/user_guide/cookbook.rst
  doc/source/user_guide/groupby.rst
  doc/source/user_guide/reshaping.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/core/groupby/generic.py
  pandas/core/resample.py
  pandas/core/reshape/pivot.py
  pandas/core/reshape/reshape.py
  pandas/tests/extension/json/test_json.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/frame/test_subclass.py
  pandas/tests/groupby/aggregate/test_cython.py
  pandas/tests/groupby/methods/test_describe.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/indexes/multi/test_indexing.py
  pandas/tests/indexes/multi/test_integrity.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/pytables/test_append.py
  pandas/tests/series/methods/test_reset_index.py
  pandas/tests/series/methods/test_unstack.py
Labels: Reshaping, Deprecate

#57415 DOC: Resolve SA05 errors for all ExponentialMovingWindow, Expanding, Rolling, and Window
  ci/code_checks.sh
  pandas/core/window/doc.py
Labels: Docs, Clean

#57357 CI/DOC: Enforce PR07 in CI
  ci/code_checks.sh
Labels: Docs, CI

#57414 DOC: fix SA05 errors in docstring for pandas.core.groupby.DataFrameGroupBy - first, last
  ci/code_checks.sh
  pandas/core/groupby/groupby.py
Labels: Docs, Clean

#57385 CLN: ._data, PeriodIndex arguments
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-39-minimum_versions.yaml
  ci/deps/actions-39.yaml
  ci/deps/circle-310-arm64.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v3.0.0.rst
  environment.yml
  pandas/compat/_optional.py
  pandas/core/arrays/string_arrow.py
  pandas/core/generic.py
  pandas/core/indexes/period.py
  pandas/tests/frame/test_api.py
  pandas/tests/generic/test_generic.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/test_old_base.py
  pandas/tests/series/test_api.py
  pyproject.toml
  requirements-dev.txt
Labels: Clean

#57358 CI/DOC: Enforce PR01 in CI
  ci/code_checks.sh
Labels: Docs, CI

#56519 TYP: make dtype required in _from_sequence_of_strings
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/boolean.py
  pandas/core/arrays/numeric.py
  pandas/core/arrays/period.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/tests/arrays/boolean/test_construction.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/test_arrow.py
Labels: ExtensionArray

#57422 ENH: Preserve Series index on `json_normalize`
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/json/_normalize.py
  pandas/tests/io/json/test_normalize.py
Labels: IO JSON

#57426 DOC: fix SA05 errors in docstrings for pandas.core.resample.Resampler…
  ci/code_checks.sh
Labels: Code Style

#57384 DOC: add an example to `PeriodIndex.to_timestamp` to clarify the behavior in case len(index)<3
  pandas/core/arrays/period.py
Labels: Docs

#57434 DOC: fix SA05 errors in docstrings for `pandas.plotting.bootstrap_plot` and `pandas.plotting.radviz`
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#57359 CI/DOC: Enforce ES01 in CI
  ci/code_checks.sh
Labels: Docs, CI

#56981 ENH: Adds ability to store tooltips as title attribute through pandas styler
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/style.py
  pandas/io/formats/style_render.py
  pandas/tests/io/formats/style/test_tooltip.py
Labels: Enhancement, Styler

#54302 ENH: Change DataFrame.to_excel to output unformatted excel file
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/excel.py
  pandas/tests/io/excel/test_style.py
Labels: Styler

#57360 CI/DOC: Enforce GL08 in CI
  ci/code_checks.sh
Labels: Docs, CI

#57450 DOC: Set verbose parameter as deprecated in docstring
  pandas/io/parsers/readers.py
Labels: Docs, IO CSV

#57446 DOC: fix SA05 errors in docstrings for pandas.core.window Expanding and Rolling, and SeriesGroupBy
  ci/code_checks.sh
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
Labels: Code Style
