Repository pandas-dev/pandas, pull requests merged in 2025-05, with the labels that each got.

#61394 DOC: add `api.types.is_dtype_equal` into document
  doc/source/reference/arrays.rst
  pandas/core/dtypes/common.py
Labels: Docs, Dtype Conversions

#61400 BUG: Fix naive timestamps inheriting timezone from previous timestamps in to_datetime with ISO8601 format
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/strptime.pyx
  pandas/tests/tools/test_to_datetime.py
Labels: Timezones

#61393 Subplot title count fix + fix for issue introduced in earlier PR
  doc/source/whatsnew/v3.0.0.rst
  pandas/plotting/_matplotlib/core.py
  pandas/tests/plotting/test_misc.py
Labels: Visualization

#61411 DOC: removed none from docstring
  pandas/core/generic.py
Labels: Docs, Algos

#61421 DOC: Updated titanic.rst survived description
  doc/source/getting_started/intro_tutorials/includes/titanic.rst
Labels: Docs

#61148 String dtype: more informative repr (keeping brief __str__)
  pandas/core/arrays/string_.py
  pandas/core/generic.py
  pandas/io/formats/format.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/io/formats/test_to_string.py
Labels: Output-Formatting, Strings

#61429 DOC: Updates to documentation - io.rst
  doc/source/user_guide/io.rst
Labels: Docs

#61423 CI: Fix test failures in 32-bit environment
  .github/workflows/unit-tests.yml
Labels: CI, Dependencies, 32bit

#61437 Backport PR #61423: CI: Fix test failures in 32-bit environment
  .github/workflows/unit-tests.yml
Labels: CI, Dependencies

#61383 ENH: Implement pandas.read_iceberg
  ci/deps/actions-310-minimum_versions.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-313.yaml
  doc/source/getting_started/install.rst
  doc/source/reference/io.rst
  doc/source/user_guide/io.rst
  doc/source/whatsnew/v3.0.0.rst
  environment.yml
  pandas/__init__.py
  pandas/compat/_optional.py
  pandas/io/api.py
  pandas/io/iceberg.py
  pandas/tests/api/test_api.py
  pandas/tests/io/test_iceberg.py
  pyproject.toml
  requirements-dev.txt
Labels: IO Data

#61263 BUG: Impossible creation of array with dtype=string
  pandas/_libs/lib.pyx
  pandas/tests/libs/test_lib.py
Labels: Bug, Strings

#61410 CI: Upgrade to ubuntu-24.04, install Python free threading from conda-forge
  .github/actions/build_pandas/action.yml
  .github/workflows/code-checks.yml
  .github/workflows/codeql.yml
  .github/workflows/comment-commands.yml
  .github/workflows/deprecation-tracking-bot.yml
  .github/workflows/docbuild-and-upload.yml
  .github/workflows/package-checks.yml
  .github/workflows/stale-pr.yml
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-313-freethreading.yaml
Labels: CI

#61384 BLD: Try using shared memory utilities in Cython to reduce wheel sizes
  meson.build
  pandas/_libs/meson.build
  pandas/_libs/tslibs/meson.build
  pandas/_libs/window/meson.build
  pyproject.toml
Labels: Build

#61446 CI: clean up wheel build workarounds now that Cython 3.1.0 is out
  .gitattributes
  .github/workflows/wheels.yml
  MANIFEST.in
  pyproject.toml
  scripts/cibw_before_build.sh
  scripts/cibw_before_build_windows.sh
Labels: Build

#61448 DOC: Skip parallel_coordinaes, andrews_curves doctests
  pandas/plotting/_misc.py
Labels: Docs

#61449 DOC: fix typo in merging.rst
  doc/source/user_guide/merging.rst
Labels: Docs

#61195 DOC: User Guide Page on user-defined functions
  doc/source/user_guide/index.rst
  doc/source/user_guide/user_defined_functions.rst
Labels: Docs, Apply

#61138 API (string dtype): implement hierarchy (NA > NaN, pyarrow > python) for consistent comparisons between different string dtypes
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/ops/invalid.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/extension/test_string.py
Labels: Numeric Operations, Strings, API - Consistency

#61451 BUG: Fix DataFrame constructor misclassification of array-like with 'name' attribute (#61443)
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_constructors.py
Labels: Bug, Constructors

#61459 DOC: change `pandas.DataFrame.unstack`'s `fill_value` param to scalar
  pandas/core/frame.py
Labels: Docs

#61453 TYP: Update typing for 3.10
  .pre-commit-config.yaml
  pandas/_libs/arrays.pyi
  pandas/_libs/hashtable.pyi
  pandas/_libs/internals.pyi
  pandas/_libs/json.pyi
  pandas/_libs/lib.pyi
  pandas/_libs/ops.pyi
  pandas/_libs/parsers.pyi
  pandas/_libs/properties.pyi
  pandas/_libs/sparse.pyi
  pandas/_libs/testing.pyi
  pandas/_libs/tslibs/nattype.pyi
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/timezones.pyi
  pandas/_libs/tslibs/tzconversion.pyi
  pandas/_libs/window/aggregations.pyi
  pandas/_libs/window/aggregations.pyx
  pandas/_testing/contexts.py
  pandas/_typing.py
  pandas/core/interchange/from_dataframe.py
  pandas/core/internals/__init__.py
  scripts/run_stubtest.py
Labels: Typing

#61320 PERF: Restore old performances with .isin() on columns typed as np.ui…
  pandas/core/algorithms.py
Labels: Performance, Regression, isin

#61413 CLN: Expose arguments in DataFrame.query
  pandas/core/frame.py
Labels: Clean, expressions

#61225 BUG: Fix #57608: queries on categorical string columns in HDFStore.select() return unexpected results.
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/computation/pytables.py
  pandas/tests/io/pytables/test_store.py
Labels: IO HDF5

#61455 fix(doc): #61432 typing
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/reshape/pivot.py
Labels: Docs, Reshaping

#61399 BUG: round on object columns no longer raises a TypeError
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_round.py
Labels: Bug, Regression, Numeric Operations

#60806 DOC: Expand on different Getitem uses
  doc/source/user_guide/10min.rst
Labels: Docs

#61472 Backport PR #61399: BUG: round on object columns no longer raises a TypeError
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/series.py
  pandas/tests/series/methods/test_round.py
Labels: Error Reporting

#61463 Wheels for win_arm64
  .github/workflows/wheels.yml
Labels: Build

#61480 DOC: Fix formatting in indexing.rst
  doc/source/user_guide/indexing.rst
Labels: Docs

#60898 Bug cov nat
  pandas/core/frame.py
  pandas/core/internals/managers.py
  pandas/tests/frame/methods/test_to_numpy.py
  pandas/tests/frame/test_reductions.py
Labels: Datetime, Missing-data

#61470 DOC: Restructure and expand UDF page
  doc/source/user_guide/user_defined_functions.rst
Labels: Docs, Apply

#61500 DOC: use Hashable instead of label
  pandas/core/frame.py
  pandas/core/indexes/base.py
  pandas/core/reshape/merge.py
Labels: Docs

#61488 Backport PR #60739 on branch 2.3.x (ENH: pandas.api.interchange.from_dataframe now uses the Arrow PyCapsule Interface if available, only falling back to the Dataframe Interchange Protocol if that fails)
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/interchange/from_dataframe.py
  pandas/tests/interchange/test_impl.py
Labels: Interchange

#61506 CLN Replace direct import of closing with qualified contextlib usage
  pandas/tests/io/test_sql.py
Labels: Testing

#61467 ENH: Support third-party execution engines in Series.map
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/series.py
  pandas/tests/apply/conftest.py
  pandas/tests/apply/test_frame_apply.py
  pandas/tests/apply/test_series_apply.py
  pandas/tests/series/methods/test_map.py
Labels: Apply

#61514 BUGFIX: escape `quotechar` when `escapechar` is not None (even if quoting=csv.QUOTE_NONE)
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/formats/csvs.py
  pandas/tests/frame/methods/test_to_csv.py
Labels: IO CSV

#61484 BUG: Raise clear error for duplicate id_vars in melt (GH61475)
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/melt.py
  pandas/tests/reshape/test_melt.py
Labels: Reshaping, Error Reporting

#61520 Backport PR #61518 on branch 2.3.x (TST: Use external_error_raised for numpy-raised test_error_invalid_values)
  pandas/tests/arrays/integer/test_arithmetic.py
Labels: Testing
