Repository pandas-dev/pandas, pull requests merged in 2025-01, with the labels that each got.

#60636 TST(string dtype): Resolve xfail with apply returning an ndarray
  pandas/tests/frame/methods/test_dtypes.py
Labels: Testing, Strings, Apply

#60635 TST(string dtype): Resolve xfail for corrwith
  pandas/tests/frame/methods/test_cov_corr.py
Labels: Testing, Strings, cov/corr

#60634 TST(string dtype): Remove xfail for combine_first
  pandas/tests/frame/methods/test_combine_first.py
Labels: Testing, Strings

#60612 DOC: Adding a Persian version of Pandas Cheat Sheet
  doc/cheatsheet/Pandas_Cheat_Sheet_FA.pdf
  doc/cheatsheet/Pandas_Cheat_Sheet_FA.pptx
  doc/cheatsheet/README.md
Labels: Docs

#60643 Backport PR #60636 on branch 2.3.x (TST(string dtype): Resolve xfail with apply returning an ndarray)
  pandas/tests/frame/methods/test_dtypes.py
Labels: Testing, Strings, Apply

#60608 DOC: Add Hugging Face Hub access
  web/pandas/community/ecosystem.md
Labels: Docs

#60501 DOC: Clarify loc and iloc functionality in user_guide/indexing.html
  doc/source/user_guide/indexing.rst
Labels: Docs

#60513 DOC: fix SA01 for pandas.arrays.NumpyExtensionArray
  ci/code_checks.sh
  pandas/core/arrays/numpy_.py
Labels: Docs

#60502 DOC: Fix some core.resample.Resampler docstrings
  ci/code_checks.sh
  pandas/core/resample.py
Labels: Docs, Resample

#60454 String dtype: coerce missing values in indexers for string dtype Index
  pandas/_libs/index.pyx
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexes/string/test_indexing.py
  pandas/tests/reshape/test_pivot.py
Labels: Indexing, Missing-data, Strings

#60637 BUG/TST (string dtype): raise proper TypeError in interpolate
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/numpy_.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/frame/methods/test_interpolate.py
Labels: Testing, Missing-data, Strings

#60649 Backport PR #60454 on branch 2.3.x (String dtype: coerce missing values in indexers for string dtype Index)
  pandas/_libs/index.pyx
  pandas/tests/frame/indexing/test_indexing.py
  pandas/tests/indexes/string/test_indexing.py
  pandas/tests/reshape/test_pivot.py
Labels: Indexing, Missing-data, Strings

#60650 DOC: fix SA01,ES01 for pandas.errors.ValueLabelTypeMismatch
  ci/code_checks.sh
  pandas/errors/__init__.py
Labels: Docs

#60679 Update macos12 runner to macos13
  .github/workflows/wheels.yml
Labels: CI

#60680 Backport PR #60679 on branch 2.3.x (Update macos12 runner to macos13)
  .github/workflows/wheels.yml
Labels: CI

#60674 Clean up compiler warnings
  pandas/_libs/byteswap.pyx
  pandas/_libs/include/pandas/vendored/klib/khash_python.h
  pandas/_libs/tslibs/conversion.pyx
Labels: Build, Internals

#60682 Add meson-format to pre-commit
  .pre-commit-config.yaml
  meson.build
  pandas/_libs/meson.build
  pandas/_libs/tslibs/meson.build
  pandas/_libs/window/meson.build
  pandas/meson.build
Labels: Code Style

#60683 TST(string dtype): Resolve xfails in test_to_csv
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_to_csv.py
Labels: Testing, IO CSV, Strings

#60687 Backport PR #60683: TST(string dtype): Resolve xfails in test_to_csv
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_reset_index.py
  pandas/tests/frame/methods/test_to_csv.py
Labels: Testing, Strings

#60689 PERF: Fix ASV CSV benchmarks
  asv_bench/benchmarks/io/csv.py
Labels: Performance, IO CSV

#60691 BUG: Fix ValueError in DataFrame/Series regex replace for all-NA values
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/array_algos/replace.py
  pandas/tests/frame/methods/test_replace.py
  pandas/tests/series/methods/test_replace.py
Labels: replace

#60659 TST(string dtype): Resolve replace xfails
  pandas/tests/frame/methods/test_replace.py
Labels: Testing, Strings, replace

#60433 ENH: Support kurtosis (kurt) in DataFrameGroupBy and SeriesGroupBy
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/groupby/base.py
  pandas/core/groupby/generic.py
  pandas/core/groupby/ops.py
  pandas/tests/groupby/methods/test_kurt.py
  pandas/tests/groupby/test_api.py
  pandas/tests/groupby/test_apply.py
  pandas/tests/groupby/test_categorical.py
  pandas/tests/groupby/test_groupby.py
  pandas/tests/groupby/test_numeric_only.py
  pandas/tests/groupby/test_raises.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Groupby, Reduction Operations

#60703 TST(string dtype): Resolve xfails in stack_unstack
  pandas/tests/frame/test_stack_unstack.py
Labels: Testing, Reshaping, Strings

#60704 DOC: Fix IPython prompts in io.rst
  doc/source/user_guide/io.rst
Labels: Docs

#60701 TST(str dtype): Resolve xfail in test_value_counts.py
  pandas/tests/frame/methods/test_value_counts.py
Labels: Testing, Algos, Strings

#60700 TST(string dtype): Resolve xfail in test_find_replace.py
  pandas/tests/strings/test_find_replace.py
Labels: Testing, Strings

#60706 Backport PR #60703 on branch 2.3.x (TST(string dtype): Resolve xfails in stack_unstack)
  pandas/tests/frame/test_stack_unstack.py
Labels: Testing, Reshaping, Strings

#60707 Backport PR #60701 on branch 2.3.x (TST(str dtype): Resolve xfail in test_value_counts.py)
  pandas/tests/frame/methods/test_value_counts.py
Labels: Testing, Algos, Strings

#60708 Backport PR #60700 on branch 2.3.x (TST(string dtype): Resolve xfail in test_find_replace.py)
  pandas/tests/strings/test_find_replace.py
Labels: Testing, Strings

#60395 DEPR: Raise `FutureWarning` about raising an error in __array__ when copy=False cannot be honored
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/interval.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/period.py
  pandas/core/arrays/sparse/array.py
  pandas/core/generic.py
  pandas/core/indexes/multi.py
  pandas/tests/arrays/sparse/test_array.py
  pandas/tests/base/test_conversion.py
  pandas/tests/copy_view/test_array.py
  pandas/tests/extension/base/interface.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/indexes/multi/test_conversion.py
  pandas/tests/io/test_fsspec.py
Labels: Compat, Deprecate

#60661 String dtype: disallow specifying the 'str' dtype with storage in [..] in string alias
  pandas/core/dtypes/dtypes.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/strings/test_get_dummies.py
Labels: Strings, API - Consistency

#60712 TST(string dtype): Resolve xfail when grouping by nan column
  pandas/tests/groupby/test_groupby.py
Labels: Testing, Groupby, Strings

#60697 ENH: Support pipe() method in Rolling and Expanding
  doc/source/reference/window.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/window/doc.py
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_api.py
Labels: Window

#60717 Remove sizeof(char) uses
  pandas/_libs/src/parser/tokenizer.c
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/_libs/tslibs/period.pyx
Labels: Internals

#60702 ENH: Enable .mode to sort with NA values
  pandas/core/algorithms.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/reductions/test_reductions.py
Labels: Enhancement, Algos, Needs Discussion

#60633 ENH: Implement cum* methods for PyArrow strings
  doc/source/whatsnew/v2.3.0.rst
  pandas/conftest.py
  pandas/core/arrays/arrow/array.py
  pandas/tests/apply/test_str.py
  pandas/tests/extension/base/accumulate.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_string.py
  pandas/tests/series/test_cumulative.py
Labels: Enhancement, Strings, Arrow, Transformations

#60696 ENH: Expose NoDefault in pandas.api.extensions
  doc/source/whatsnew/v3.0.0.rst
  pandas/api/typing/__init__.py
  pandas/tests/api/test_api.py
Labels: Typing

#60698 ENH: Format `decimal.Decimal` as full precision strings in `.to_json(...)`
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/tests/io/json/test_json_table_schema_ext_dtype.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/json/test_ujson.py
Labels: IO JSON

#60719 [backport 2.3.x] TST(string dtype): Resolve xfail when grouping by nan column (#60712)
  pandas/tests/groupby/test_groupby.py
Labels: Strings

#60538 BUG: Fix DataFrame binary arithmatic operation handling of unaligned …
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_arithmetic.py
Labels: Numeric Operations, MultiIndex

#60720 DOC: fix PR01,SA01,ES01 for pandas.RangeIndex.from_range
  ci/code_checks.sh
  pandas/core/indexes/range.py
Labels: Docs

#60721 Use const char* for JSON key name
  pandas/_libs/include/pandas/vendored/ujson/lib/ultrajson.h
  pandas/_libs/src/vendored/ujson/lib/ultrajsonenc.c
  pandas/_libs/src/vendored/ujson/python/objToJSON.c
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
Labels: Internals, IO JSON

#60724 DOC: fix PR07,SA01 for pandas.arrays.ArrowExtensionArray
  ci/code_checks.sh
  pandas/core/arrays/arrow/array.py
Labels: Docs

#60725 DOC: Update doc for newly added groupby method kurt
  doc/source/reference/groupby.rst
Labels: Docs

#60579 ENH: Add first and last aggregations to Rolling and Expanding
  doc/source/reference/window.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/window/aggregations.pyi
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_cython_aggregations.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_rolling.py
  pandas/tests/window/test_rolling_functions.py
  pandas/tests/window/test_timeseries_window.py
Labels: Enhancement, Window, Stale

#60726 REGR: from_records not initializing subclasses properly
  doc/source/whatsnew/v2.3.0.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/test_subclass.py
Labels: Constructors

#60746 DOC: fix ES01 for pandas.read_feather
  pandas/io/feather_format.py
Labels: Docs

#60731 DOC: Fix typo "numpy.ndarray.putmask"
  pandas/core/indexes/base.py
Labels: Docs

#60741 ENH: Support skipna parameter in GroupBy mean and sum
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/groupby.pyi
  pandas/_libs/groupby.pyx
  pandas/core/_numba/kernels/mean_.py
  pandas/core/_numba/kernels/sum_.py
  pandas/core/groupby/groupby.py
  pandas/tests/groupby/aggregate/test_numba.py
  pandas/tests/groupby/test_api.py
  pandas/tests/groupby/test_reductions.py
Labels: Groupby

#60734 DOC: Add line clarifying sorting using sort_values()
  pandas/core/frame.py
  pandas/core/generic.py
Labels: Docs

#60722 CI: Test Github Actions Arm64 Runners
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
Labels: Build

#60749 Fix group_sum NaN comparison warnings
  pandas/_libs/groupby.pyx
Labels: Groupby

#60751 CI: Rename ubuntu unit test jobs
  .github/workflows/unit-tests.yml
Labels: CI

#60716 Update PyArrow conversion and arrow/parquet tests for pyarrow 19.0
  .github/workflows/unit-tests.yml
  ci/deps/actions-311-pyarrownightly.yaml
  pandas/compat/__init__.py
  pandas/compat/pyarrow.py
  pandas/io/_util.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/io/test_common.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_parquet.py
Labels: Compat, IO Parquet, Arrow

#60710 API(str dtype): Raise on StringDtype for unary op +
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/frame/test_unary.py
Labels: Numeric Operations, Strings, API - Consistency

#60757 DOC: fix PR07,SA01 for pandas.arrays.TimedeltaArray
  ci/code_checks.sh
  pandas/core/arrays/timedeltas.py
Labels: Docs

#60759 DOC: fix RT03,SA01 for pandas.plotting.andrews_curves
  ci/code_checks.sh
  pandas/plotting/_misc.py
Labels: Docs

#60718 DOC: Whatsnew for sorting mode result
  doc/source/whatsnew/v2.3.0.rst
Labels: Docs

#60756 Miscellaneous updates for Pyodide 0.27: bump WASM CI and revise Arrow compatibility note
  .github/workflows/unit-tests.yml
  .gitignore
  pandas/tests/series/indexing/test_setitem.py
  web/pandas/pdeps/0010-required-pyarrow-dependency.md
Labels: Testing, CI

#60760 Backport PR #60718 on branch 2.3.x (DOC: Whatsnew for sorting mode result)
  doc/source/whatsnew/v2.3.0.rst
Labels: Docs

#60738 DOC: add SPSS comparison guide structure
  doc/source/getting_started/comparison/comparison_with_spss.rst
  doc/source/getting_started/comparison/index.rst
Labels: Docs

#60763 [backport 2.3.x] API(str dtype): Raise on StringDtype for unary op + (#60710)
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/frame/test_unary.py
Labels: Strings

#60736 BUG: Fixed TypeError for Series.isin() when large series and values contains NA (#60678)
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/algorithms.py
  pandas/tests/series/methods/test_isin.py
Labels: Missing-data, Algos

#59786 ENH: Series.str.get_dummies() raise on string type (follow up to PR #59577)
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/core/strings/accessor.py
  pandas/core/strings/object_array.py
  pandas/tests/strings/test_get_dummies.py
Labels: Strings

#60663 ENH: Enable pytables to round-trip with StringDtype
  doc/source/whatsnew/v2.3.0.rst
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_put.py
Labels: IO HDF5

#60764 TST (string dtype): follow-up fix for pyarrow 19.0 update
  pandas/tests/io/test_parquet.py
Labels: Testing, Strings, IO Parquet

#60771 [backport 2.3.x] ENH: Enable pytables to round-trip with StringDtype (#60663)
  doc/source/whatsnew/v2.3.0.rst
  pandas/io/pytables.py
  pandas/tests/io/pytables/test_put.py
Labels: Strings

#60776 DOC: fix SA01 for pandas.tseries.offsets.LastWeekOfMonth
  ci/code_checks.sh
  pandas/_libs/tslibs/offsets.pyx
Labels: Docs

#60765 TST(string dtype): Fix xfails in test_block_internals.py
  pandas/tests/frame/conftest.py
  pandas/tests/frame/constructors/test_from_dict.py
  pandas/tests/frame/test_block_internals.py
Labels: Strings

#60711 TST(string dtype): Resolve xfail in groupby.test_size
  pandas/tests/groupby/methods/test_size.py
Labels: Testing, Groupby, Strings

#60784 TST(string_dtype): Fix minor issue with CSV parser and column dtype
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/common/test_index.py
Labels: Testing, Strings

#60785 Backport PR #60784 on branch 2.3.x (TST(string_dtype): Fix minor issue with CSV parser and column dtype)
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/common/test_index.py
Labels: Testing, Strings

#60787 DOC: Update a link in tutorials.rst
  doc/source/getting_started/tutorials.rst
Labels: Docs

#60761 CI: Remove CircleCI in favor of GHA ARM builds
  .circleci/config.yml
  .gitattributes
  ci/deps/circle-311-arm64.yaml
  pandas/tests/io/conftest.py
Labels: CI

#60436 BUG: fix construction of Series / Index from dict keys when "str" dtype is specified explicitly
  pandas/core/construction.py
  pandas/tests/base/test_constructors.py
  pandas/tests/io/test_fsspec.py
Labels: Strings, Constructors

#60792 [2.3.x] DEPS: Drop Python 3.9
  .github/workflows/package-checks.yml
  .github/workflows/unit-tests.yml
  .github/workflows/wheels.yml
  ci/deps/actions-310-minimum_versions.yaml
  ci/deps/actions-39.yaml
  doc/source/whatsnew/v2.3.0.rst
Labels: CI, Dependencies

#59937 Backport PR #59906 on branch 2.3.x (BLD: Fix armv7 build)
  pandas/_libs/src/vendored/ujson/python/JSONtoObj.c
Labels: Build, Stale, ARM

#60791 BUG: fix combine_first reorders columns
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/methods/test_combine_first.py
Labels: Reshaping

#60799 TST: Add test for exceptional behavior when calling `view()` on `BaseStringArray`
  pandas/tests/arrays/string_/test_string.py
Labels: Testing

#60796 BUG: is_*_array returns true on empty object dtype
  pandas/_libs/lib.pyx
  pandas/tests/dtypes/test_inference.py
  pandas/tests/io/test_feather.py
Labels: Bug, Internals

#60805 DOC: fix PR01,RT03,SA01 for pandas.core.resample.Resampler.transform
  ci/code_checks.sh
  pandas/core/resample.py
Labels: Docs

#60808 Backport PR #60796 on branch 2.3.x (BUG: is_*_array returns true on empty object dtype)
  pandas/_libs/lib.pyx
  pandas/tests/dtypes/test_inference.py
Labels: Bug, Internals

#60811 TST(string_dtype): Refine scope of string xfail in test_http_headers
  pandas/tests/io/test_http_headers.py
Labels: Testing, Strings

#60709 ENH(string dtype): Make str.decode return str dtype
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/strings/accessor.py
  pandas/io/pytables.py
  pandas/io/sas/sas7bdat.py
  pandas/tests/io/sas/test_sas7bdat.py
  pandas/tests/strings/test_strings.py
Labels: Enhancement, Strings

#60818 BUG(string): from_dummies, dropna
  pandas/tests/frame/methods/test_dropna.py
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/reshape/test_from_dummies.py
Labels: Strings
