Repository pandas-dev/pandas, pull requests merged in 2025-06, with the labels that each got.

#61471 DOC: Improve lookup documentation
  doc/source/user_guide/indexing.rst
Labels: Docs, Indexing

#61553 DOC: Move PyCapsule whatsnew note from v3.0.0 to v2.3.0
  doc/source/whatsnew/v2.3.0.rst
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#61549 TST: Add error message for test_groupby_raises_category_on_category for quantile
  pandas/tests/groupby/test_raises.py
Labels: Testing

#61556 Backport PR #61549 on branch 2.3.x (TST: Add error message for test_groupby_raises_category_on_category for quantile)
  pandas/tests/groupby/test_raises.py
Labels: Testing

#61558 Backport PR #61519: BUILD: Bump Cython to 3.1
  asv_bench/asv.conf.json
  ci/deps/actions-310-minimum_versions.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311-numpydev.yaml
  ci/deps/actions-311-pyarrownightly.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-pypy-39.yaml
  environment.yml
  pyproject.toml
  requirements-dev.txt
Labels: Build, Dependencies

#61560 DOC: Set date for v2.3.0.rst whatsnew
  doc/source/whatsnew/v2.3.0.rst
Labels: Docs

#61572 BUG: Fix JSON typo that breaks javascript in the docs
  web/pandas/versions.json
Labels: Bug, Docs

#61555 DOC: Fix typo in to_html and to_string docs
  pandas/io/formats/format.py
Labels: Docs

#61567 BUILD: Add wheels for musllinux_aarch64
  .github/workflows/wheels.yml
Labels: Build

#61592 CI: Update Python version to 3.11 in environment.yml
  environment.yml
Labels: CI, Dependencies

#61591 WEB: Moving maintainers to inactive status
  web/pandas/config.yml
Labels: Admin, Web

#61593 WEB: Restore website width and improve table of contents style
  web/pandas/static/css/pandas.css
Labels: Web

#61601 WEB: remove "String data type" from "Roadmap points pending a PDEP" section.
  web/pandas/about/roadmap.md
Labels: Web

#61586 Update whatsnew for issue #53115
  doc/source/whatsnew/v3.0.0.rst
Labels: Docs

#61630 DOC: Title Capitalization and Grammar Fix
  README.md
Labels: Docs

#61648 TST: update xfail xarray version check in to_xarray test
  pandas/tests/generic/test_to_xarray.py
Labels: Testing

#61594 CI: Fix slow mamba solver issue by limiting boto3 versions
  ci/deps/actions-310-minimum_versions.yaml
  ci/deps/actions-310.yaml
  ci/deps/actions-311-downstream_compat.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-313.yaml
Labels: CI, Dependencies

#61600 DOC/ENH: Holiday exclusion argument
  doc/source/whatsnew/v3.0.0.rst
  pandas/tests/tseries/holiday/test_holiday.py
  pandas/tseries/holiday.py
Labels: Frequency

#61604 WEB: Replace os.path with pathlib.Path in pandas_web.py
  web/pandas_web.py
Labels: Web

#61577 TST: Remove match= in test_setitem_invalid to avoid PytestWarning
  pandas/tests/extension/base/setitem.py
Labels: Testing

#61655 WEB: Add table of contents to the Ecosystem
  web/pandas/community/ecosystem.md
  web/pandas/config.yml
  web/pandas_web.py
Labels: Web

#61666 ENH: Support for Orthodox Easter
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_easter.py
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Frequency

#61615 BUG: Fix RecursionError when apply native container types as a func
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/lib.pyx
  pandas/tests/dtypes/test_inference.py
Labels: Dtype Conversions

#61664 Fix some incorrect indents in development documentation
  doc/source/development/community.rst
  doc/source/development/contributing.rst
  doc/source/development/contributing_codebase.rst
  doc/source/development/contributing_gitpod.rst
  doc/source/development/debugging_extensions.rst
  doc/source/development/developer.rst
  doc/source/development/maintaining.rst
Labels: Docs

#61658 DOC/ENH: Holiday days_of_week value error
  doc/source/whatsnew/v3.0.0.rst
  pandas/tests/tseries/holiday/test_holiday.py
  pandas/tseries/holiday.py
Labels: Frequency

#61654 DOC: Add release notes template for 2.3.1
  doc/source/whatsnew/index.rst
  doc/source/whatsnew/v2.3.1.rst
Labels: Docs

#61686 fix for building docs on Windows
  doc/source/conf.py
  doc/source/user_guide/enhancingperf.rst
Labels: Docs, Windows

#61704 DOC: update Slack invite link in community dos
  doc/source/development/community.rst
Labels: Docs, Community

#61697 TST: Increase test coverage for pandas.io.formats.excel.py
  pandas/io/formats/excel.py
  pandas/tests/io/formats/test_to_excel.py
Labels: Testing, IO Excel

#61744 CI: if no docstring, create error GL08 and don't validate - fix for numpydoc 1.9
  scripts/validate_docstrings.py
Labels: CI, Code Style

#61698 DOC: move relevant whatsnew changes from 2.3.0 to 2.3.1 file
  doc/source/whatsnew/v2.3.0.rst
  doc/source/whatsnew/v2.3.1.rst
Labels: Docs

#61635 Description of pandas_datetime_exec function.
  pandas/_libs/src/datetime/pd_datetime.c
Labels: Docs

#61629 BUG: to_stata erroring when encoded text and normal text have mismatched length
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/stata.py
  pandas/tests/io/test_stata.py
Labels: Bug, IO Stata

#61597 ENH: improve optional import error message
  pandas/compat/_optional.py
  pandas/tests/io/test_fsspec.py
  pandas/tests/io/test_parquet.py
  pandas/tests/test_optional_dependency.py
  pandas/tests/util/test_numba.py
Labels: Error Reporting

#60357 BUG: Copy attrs on pd.merge()
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/core/reshape/concat.py
  pandas/core/reshape/merge.py
  pandas/tests/frame/test_api.py
  pandas/tests/generic/test_duplicate_labels.py
  pandas/tests/generic/test_frame.py
  pandas/tests/generic/test_series.py
Labels: Reshaping, metadata

#61054 BUG: Fix return type of loc/iloc
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/multiindex/test_loc.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing, Dtype Conversions
