Repository pandas-dev/pandas, pull requests merged in 2025-03, with the labels that each got.

#60052 BUG: Fix incosistent behavior of 2d-indexed loc-set to Series #59933
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/indexing.py
  pandas/tests/indexing/test_loc.py
Labels: Bug, Indexing

#61022 BUG: Fix bug in to_datetime that occasionally throws FloatingPointErr…
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/conversion.pyx
  pandas/tests/tools/test_to_datetime.py
Labels: Datetime, Missing-data

#61034 DOC: Correct typos in Working with text data
  doc/source/user_guide/text.rst
Labels: Docs

#60946 ENH: Add HalfYear offsets
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_business_halfyear.py
  pandas/tests/tseries/offsets/test_halfyear.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tseries/offsets.py
Labels: Frequency

#61039 CI: Bump GHA uses versions
  .github/actions/run-tests/action.yml
  .github/actions/setup-conda/action.yml
Labels: CI

#61042 CI/TST: Fix xfail in test_columns_dtypes_not_invalid for pyarrow nightly
  pandas/compat/pyarrow.py
  pandas/tests/io/test_parquet.py
Labels: Testing, CI

#60820 test_datetimes.py: fix literal string
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/arrays/test_datetimes.py
Labels: Error Reporting, Clean

#60758 ENH: Add JupyterLite-powered shell for the website (reprise of #47428)
  .github/workflows/docbuild-and-upload.yml
  environment.yml
  requirements-dev.txt
  web/interactive_terminal/README.md
  web/interactive_terminal/jupyter-lite.json
  web/interactive_terminal/jupyter_lite_config.json
  web/pandas/getting_started.md
  web/pandas/index.html
  web/pandas/try.md
Labels: Enhancement, Web

#61044 Backport PR #61042: CI/TST: Fix xfail in test_columns_dtypes_not_invalid for pyarrow nightly
  pandas/compat/pyarrow.py
  pandas/tests/io/test_parquet.py
Labels: Testing, CI

#61053 DOC Fix Styler.to_latex to be in Writer column
  doc/source/user_guide/io.rst
Labels: Docs

#60990 DOC: Updated set_index doc with a warning
  pandas/core/frame.py
Labels: Docs

#61059 DOC: Correct a typo in ecosystem.md
  web/pandas/community/ecosystem.md
Labels: Docs

#61041 BUG: Recognize chained fsspec URLs
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/common.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_common.py
Labels: IO Network

#61066 DOC: Fix syntax highlighting in overview
  doc/source/getting_started/overview.rst
Labels: Docs

#61065 DOC: Add inference type information to Dataframe Apply
  pandas/core/frame.py
Labels: Docs

#61063 DOC: Add link description
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#61062 BUG: Fix na_position type in IndexEngine
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/hashtable.pxd
  pandas/_libs/hashtable_class_helper.pxi.in
  pandas/tests/libs/test_hashtable.py
Labels: Index

#60983 BUG: Fix concat DataFrame and Series with ignore_index=True
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/reshape/concat.py
  pandas/tests/reshape/concat/test_concat.py
Labels: Bug, Reshaping

#61080 BUG: Fix OverflowError in lib.maybe_indices_to_slice()
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/lib.pyx
Labels: Internals

#60944 BUG: Fix MultiIndex from_tuples on tuples with NaNs
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/algorithms.py
  pandas/core/indexes/multi.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/series/test_constructors.py
Labels: Bug, MultiIndex

#61087 ENH: Add Rolling.nunique()
  asv_bench/benchmarks/rolling.py
  doc/source/reference/window.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/window/aggregations.pyi
  pandas/_libs/window/aggregations.pyx
  pandas/core/window/expanding.py
  pandas/core/window/rolling.py
  pandas/tests/window/test_cython_aggregations.py
  pandas/tests/window/test_expanding.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_rolling.py
Labels: Enhancement, Window

#61082 DOC: Add doc for half year offsets
  ci/code_checks.sh
  doc/source/reference/offset_frequency.rst
  doc/source/user_guide/timeseries.rst
  scripts/validate_rst_title_capitalization.py
Labels: Docs

#61098 CI/TST: Address TestArrowArray::test_reduce_series_numeric supporting skew
  pandas/compat/__init__.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#61069 DOC: Update warning in `Index.values` docstring to clarify index modification which causes segmentation fault
  pandas/core/indexes/base.py
Labels: Docs

#61105 BUG: DataFrame.explode doesn't work for pyarrow.large_list type
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/arrow/array.py
  pandas/tests/series/methods/test_explode.py
Labels: Arrow

#61085 DEPS: Update NumpyExtensionArray repr for NEP51
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/numpy_.py
  pandas/tests/arrays/numpy_/test_numpy.py
Labels: Output-Formatting, ExtensionArray

#61107 Backport PR #61085 on branch 2.3.x (DEPS: Update NumpyExtensionArray repr for NEP51)
  doc/source/whatsnew/v2.3.0.rst
  pandas/core/arrays/numpy_.py
  pandas/tests/arrays/numpy_/test_numpy.py
Labels: Output-Formatting, ExtensionArray

#61112 TST: Add test for retaining dtype of datetime columns in DataFrame.to_hdf
  pandas/tests/io/pytables/test_retain_attributes.py
Labels: Testing

#61103 Enh arrow json extension
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/dtypes/dtypes.py
  pandas/tests/extension/test_arrow.py
Labels: Arrow

#61111 DOC: Update infer_dtype docstring
  pandas/_libs/lib.pyx
Labels: Docs

#61102 Backport PR #61098: CI/TST: Address TestArrowArray::test_reduce_series_numeric supporting skew
  pandas/compat/__init__.py
  pandas/tests/extension/test_arrow.py
Labels: Testing, Arrow

#61130 DOC: Add skrub to ecosystem.md
  web/pandas/community/ecosystem.md
Labels: Web

#61119 DOC: Added docstrings to min/max/reso for Timedelta
  ci/code_checks.sh
  pandas/_libs/tslibs/timedeltas.pyx
Labels: Docs

#61131 BUG: Fix inconsistency of converting empty categorical with dtype_backend='pyarrow'
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/dtypes/cast.py
  pandas/tests/frame/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_convert_dtypes.py
Labels: Dtype Conversions, Categorical

#60997 BUG: fix read_json ignoring the dtype with the pyarrow engine
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/json/_json.py
  pandas/tests/io/json/test_pandas.py
Labels: IO JSON, Arrow

#61146 Fix #61123 with simple doc change
  pandas/io/excel/_base.py
Labels: Docs

#61150 DOC: Add missing period
  doc/source/development/contributing_codebase.rst
Labels: Docs

#61158 Fix bug in `Series.describe` where the median is included any time the `percentiles` argument is not None
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/core/methods/describe.py
  pandas/io/formats/format.py
  pandas/tests/frame/methods/test_describe.py
  pandas/tests/groupby/methods/test_describe.py
Labels: Series

#61121 WEB: Update sponsors and fix logos style
  web/pandas/config.yml
  web/pandas/index.html
  web/pandas/static/img/partners/czi.svg
  web/pandas/static/img/partners/intel.svg
  web/pandas/static/img/partners/two_sigma.svg
  web/pandas/static/img/partners/voltron_data.svg
Labels: Web

#61167 DOC: Add punctuation to basics.rst in User Guide
  doc/source/user_guide/basics.rst
Labels: Docs

#61163 WEB: Remove self (Marco Gorelli) from "active maintainers" list
  .github/CODEOWNERS
  ci/meta.yaml
  web/pandas/config.yml
  web/pandas/static/img/partners/quansight_labs.svg
Labels: Web

#61154 BUG: Clip corr edge cases between -1.0 and 1.0
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/algos.pyx
  pandas/tests/frame/methods/test_cov_corr.py
Labels: cov/corr

#61190 Update guidance on CFLAGS
  doc/source/development/debugging_extensions.rst
Labels: Docs

#61183 REGR: Interpolate with method=index
  pandas/core/missing.py
  pandas/core/resample.py
  pandas/tests/resample/test_base.py
  pandas/tests/resample/test_time_grouper.py
  pandas/tests/series/methods/test_interpolate.py
Labels: Bug, Missing-data, Regression
