Repository pandas-dev/pandas, pull requests merged in 2025-10, with the labels that each got.

#62493 BUG: honor ambiguous/nonexistent for tz-aware endpoints in date_range
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/datetimes.py
  pandas/tests/indexes/datetimes/test_date_range.py
Labels: Timezones

#62546 TST: Replace ensure_clean utility with temp_file pytest fixture (2 files)
  pandas/tests/io/json/test_compression.py
  pandas/tests/io/json/test_pandas.py
Labels: Testing

#62553 TST: remove expected warnings for new `numexpr` version
  pandas/tests/frame/test_arithmetic.py
  pandas/tests/series/test_arithmetic.py
  pandas/tests/test_expressions.py
Labels: Testing

#62503 TST: Avoid time.sleep in tests
  pandas/tests/io/excel/test_style.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_compression.py
Labels: Testing

#61941 BUG: Fix TypeError in assert_index_equal when comparing CategoricalIndex with check_categorical=True and exact=False
  doc/source/whatsnew/v3.0.0.rst
  pandas/_testing/asserters.py
  pandas/tests/util/test_assert_index_equal.py
Labels: Testing

#62393 ENH: adds columnwise fillna support
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_fillna.py
Labels: Missing-data

#62469 STY: ZIP strict for pandas/io
  pandas/io/excel/_xlrd.py
  pandas/io/formats/css.py
  pandas/io/formats/excel.py
  pandas/io/formats/format.py
  pandas/io/formats/html.py
  pandas/io/formats/info.py
  pandas/io/formats/printing.py
  pandas/io/formats/style_render.py
  pandas/io/json/_normalize.py
  pandas/io/json/_table_schema.py
  pandas/io/parsers/base_parser.py
  pandas/io/parsers/c_parser_wrapper.py
  pandas/io/parsers/python_parser.py
  pandas/io/pytables.py
  pandas/io/sas/sas_xport.py
  pandas/io/sql.py
  pandas/io/stata.py
  pandas/io/xml.py
  pyproject.toml
Labels: Code Style

#62577 Zip Strict for pandas/core level files #62469
  pandas/core/apply.py
  pandas/core/arraylike.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/indexing.py
  pandas/core/series.py
  pandas/core/sorting.py
  pyproject.toml
Labels: Code Style

#62575 STY: Add `strict=True` in `zip()` in pandas\core\array_algos\quantile.py
  pandas/core/array_algos/quantile.py
Labels: Code Style

#62591 STY: Enforce Ruff rule B905 for pandas/_config
  pandas/_config/config.py
Labels: Code Style

#62588 STY: Add `strict` parameter with appropriate value in `zip()` in pandas/tests/series/methods/
  pandas/tests/series/methods/test_convert_dtypes.py
  pandas/tests/series/methods/test_rename.py
  pandas/tests/series/methods/test_replace.py
  pandas/tests/series/methods/test_reset_index.py
  pandas/tests/series/methods/test_sort_index.py
Labels: Code Style

#62587 STY: Add `strict=True` in `zip()` in pandas\tests\io\test_orc.py
  pandas/tests/io/test_orc.py
Labels: Code Style

#62573 DOC: clarify that check_array_indexer accepts int and slice
  pandas/core/indexers/utils.py
Labels: Docs

#62539 ENH: improve error message when specifying a previously-deprecated frequen…
  pandas/_libs/tslibs/offsets.pyx
  pandas/tests/tseries/offsets/test_offsets.py
Labels: Error Reporting, Frequency

#62016 DOC: Add example for multi-column joins using `merge`
  doc/source/getting_started/comparison/comparison_with_sql.rst
Labels: Docs

#61871 BUG FIX: None of the included dtypes present in df will raise ValueError with clear error message.
  pandas/core/methods/describe.py
  pandas/tests/frame/methods/test_describe.py
Labels: Error Reporting

#62593 DOC: Replace appender decorators with docstrings for IntervalArray #62437
  pandas/core/arrays/interval.py
Labels: Docs

#62584 DOC: inline docstring for pandas.plotting functions
  pandas/plotting/_core.py
Labels: Docs

#62542 BUG: make `read_csv` be able to read large floating numbers into float
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/parsers.pyx
  pandas/tests/io/parser/common/test_float.py
Labels: IO CSV

#62612 TST: Replace ensure_clean with temp_file in test_errors.py
  pandas/tests/io/pytables/test_errors.py
Labels: Testing

#62605 Zip strict strings
  pandas/core/strings/accessor.py
  pyproject.toml
Labels: Code Style

#62613 TST: Replace ensure_clean with temp_file in test_pytables_missing.py
  pandas/tests/io/pytables/test_pytables_missing.py
Labels: Testing

#62615 TST: Replace ensure_clean with temp_file in test_multi_thread.py
  doc/source/whatsnew/v3.0.0.rst
  pandas/tests/io/parser/test_multi_thread.py
Labels: Testing

#62585 CI: remove "take" for assigning issues to user
  .github/workflows/comment-commands.yml
  doc/source/development/contributing.rst
Labels: Admin
