Repository pandas-dev/pandas, pull requests merged in 2025-08, with the labels that each got.

#62025 BUG: Change default of observed in Series.groupby
  pandas/core/series.py
Labels: Bug, Groupby, Categorical

#62032 EHN: return early when the result is None
  pandas/core/common.py
Labels: Index

#62021 TST: nan->NA in non-construction tests
  pandas/tests/arrays/categorical/test_astype.py
  pandas/tests/arrays/floating/conftest.py
  pandas/tests/arrays/floating/test_arithmetic.py
  pandas/tests/arrays/floating/test_construction.py
  pandas/tests/arrays/floating/test_function.py
  pandas/tests/arrays/integer/conftest.py
  pandas/tests/arrays/integer/test_arithmetic.py
  pandas/tests/arrays/integer/test_construction.py
  pandas/tests/arrays/integer/test_dtypes.py
  pandas/tests/arrays/integer/test_function.py
  pandas/tests/arrays/test_array.py
  pandas/tests/base/test_conversion.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
  pandas/tests/frame/methods/test_diff.py
  pandas/tests/frame/methods/test_get_numeric_data.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/groupby/methods/test_kurt.py
  pandas/tests/groupby/test_cumulative.py
  pandas/tests/groupby/test_groupby_dropna.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/indexes/multi/test_constructors.py
  pandas/tests/io/formats/test_to_csv.py
  pandas/tests/io/json/test_pandas.py
  pandas/tests/io/test_feather.py
  pandas/tests/io/test_html.py
  pandas/tests/io/test_sql.py
  pandas/tests/io/test_stata.py
  pandas/tests/io/xml/test_xml_dtypes.py
  pandas/tests/reductions/test_reductions.py
  pandas/tests/reshape/merge/test_merge.py
  pandas/tests/series/methods/test_case_when.py
  pandas/tests/series/methods/test_rank.py
  pandas/tests/series/methods/test_reindex.py
  pandas/tests/series/test_constructors.py
  pandas/tests/strings/test_find_replace.py
  pandas/tests/strings/test_strings.py
  pandas/tests/test_algos.py
  pandas/tests/test_sorting.py
  pandas/tests/tools/test_to_datetime.py
  pandas/tests/tools/test_to_numeric.py
Labels: Testing, Missing-data

#62019 REF: make copy keyword in recode_for_categories keyword only
  pandas/_libs/index.pyx
  pandas/core/arrays/categorical.py
  pandas/core/dtypes/concat.py
  pandas/core/groupby/categorical.py
  pandas/core/indexes/multi.py
  pandas/tests/arrays/categorical/test_api.py
  pandas/tests/arrays/categorical/test_dtypes.py
  pandas/tests/arrays/categorical/test_missing.py
Labels: Categorical

#62049 REF: simplify mask_missing
  pandas/core/dtypes/common.py
  pandas/core/missing.py
Labels: Refactor

#62060 API: make construct_array_type non-classmethod
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/arrays/boolean.py
  pandas/core/arrays/floating.py
  pandas/core/arrays/integer.py
  pandas/core/arrays/numeric.py
  pandas/core/arrays/string_.py
  pandas/core/dtypes/base.py
  pandas/core/dtypes/dtypes.py
  pandas/tests/arrays/test_array.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/extension/array_with_attr/array.py
  pandas/tests/extension/date/array.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/list/array.py
  pandas/tests/frame/methods/test_astype.py
Labels: ExtensionArray

#61969 BUG: Fix Series.reindex losing values when reindexing to MultiIndex
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/generic.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/series/methods/test_reindex.py
Labels: MultiIndex, Index

#62074 BUG(CoW): also raise for chained assignment for .at / .iat
  pandas/core/indexing.py
  pandas/tests/copy_view/test_chained_assignment_deprecation.py
Labels: Copy / view semantics

#61985 API: offsets.Day is always calendar-day
  ci/code_checks.sh
  doc/source/user_guide/timedeltas.rst
  doc/source/user_guide/timeseries.rst
  doc/source/whatsnew/v3.0.0.rst
  pandas/_libs/tslibs/__init__.py
  pandas/_libs/tslibs/offsets.pyi
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/_ranges.py
  pandas/core/arrays/datetimelike.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/period.py
  pandas/core/arrays/timedeltas.py
  pandas/core/indexes/period.py
  pandas/core/resample.py
  pandas/tests/arithmetic/test_datetime64.py
  pandas/tests/arithmetic/test_numeric.py
  pandas/tests/arithmetic/test_timedelta64.py
  pandas/tests/indexes/datetimes/methods/test_tz_convert.py
  pandas/tests/indexes/datetimes/test_arithmetic.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
  pandas/tests/resample/test_resample_api.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/tseries/offsets/test_dst.py
  pandas/tests/tseries/offsets/test_offsets.py
  pandas/tests/tseries/offsets/test_ticks.py
  pandas/tests/tslibs/test_api.py
  pandas/tests/tslibs/test_to_offset.py
Labels: Frequency

#62085 BUG: Preserve column names in DataFrame.from_records when nrows=0
  doc/source/whatsnew/v3.0.0.rst
  pandas/core/frame.py
  pandas/tests/frame/constructors/test_from_records.py
Labels: DataFrame

#62065 DEPS: Bump adbc-driver-postgresql/sqlite to 1.2
  ci/deps/actions-311-minimum_versions.yaml
  ci/deps/actions-311.yaml
  ci/deps/actions-312.yaml
  ci/deps/actions-313-downstream_compat.yaml
  ci/deps/actions-313.yaml
  doc/source/getting_started/install.rst
  doc/source/whatsnew/v3.0.0.rst
  environment.yml
  pandas/compat/_optional.py
  pyproject.toml
  requirements-dev.txt
  scripts/tests/data/deps_expected_random.yaml
  scripts/tests/data/deps_minimum.toml
Labels: Dependencies

#62053 BUG: read_csv with engine=pyarrow and numpy-nullable dtype
  doc/source/whatsnew/v3.0.0.rst
  pandas/io/_util.py
  pandas/io/parsers/arrow_parser_wrapper.py
  pandas/tests/io/parser/dtypes/test_dtypes_basic.py
  pandas/tests/io/parser/test_na_values.py
Labels: IO CSV

#62101 ENH: Warn on unused arguments to resample
  pandas/core/resample.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_period_index.py
Labels: Resample, Warnings

#62090 DOC: Add to_julian_date to DatetimeIndex methods listing
  doc/source/reference/indexing.rst
  pandas/core/arrays/datetimes.py
  pandas/core/indexes/datetimes.py
Labels: Docs

#61964 BUG: fix Series.str.fullmatch() and Series.str.match() with a compiled regex failing with arrow strings
  doc/source/whatsnew/v2.3.2.rst
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/strings/accessor.py
  pandas/core/strings/object_array.py
  pandas/tests/strings/test_find_replace.py
Labels: Strings, Arrow

#61946 BUG: Fix Series.str.contains with compiled regex on Arrow string dtype
  doc/source/whatsnew/v2.3.2.rst
  pandas/core/arrays/string_arrow.py
  pandas/tests/strings/test_find_replace.py
Labels: Bug, Strings, Arrow

#62125 DOC: Improve kwargs docs for parquet engines
  pandas/io/parquet.py
Labels: Docs

#62120 WEB: fix discussion link in PDEP-6
  web/pandas/pdeps/0006-ban-upcasting.md
Labels: Web

#62105 ENH: EA._cast_pointwise_result
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/base.py
  pandas/core/arrays/categorical.py
  pandas/core/arrays/datetimes.py
  pandas/core/arrays/masked.py
  pandas/core/arrays/numpy_.py
  pandas/core/arrays/sparse/array.py
  pandas/core/arrays/string_.py
  pandas/core/dtypes/cast.py
  pandas/core/groupby/ops.py
  pandas/core/indexes/base.py
  pandas/core/series.py
  pandas/tests/extension/base/methods.py
  pandas/tests/extension/decimal/array.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/extension/json/array.py
  pandas/tests/extension/test_arrow.py
  pandas/tests/extension/test_masked.py
  pandas/tests/extension/test_string.py
  pandas/tests/groupby/aggregate/test_aggregate.py
  pandas/tests/indexes/test_any_index.py
  pandas/tests/indexes/test_base.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/resample/test_resampler_grouper.py
Labels: ExtensionArray

#62163 Backport PR #62152 on branch 2.3.x (DOC: prepare 2.3.2 whatsnew notes for release)
  doc/source/whatsnew/v2.3.1.rst
  doc/source/whatsnew/v2.3.2.rst
Labels: Docs

#62165 REF: get rid of ArrowStringArrayNumpySemantics
  pandas/core/arrays/_arrow_string_mixins.py
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/construction.py
  pandas/core/groupby/groupby.py
  pandas/core/series.py
  pandas/tests/arrays/string_/test_string.py
  pandas/tests/arrays/string_/test_string_arrow.py
  pandas/tests/base/test_conversion.py
  pandas/tests/extension/test_string.py
  pandas/tests/reductions/test_reductions.py
Labels: Refactor

#62162 CLN: Replace warnings with Pandas4Warning
  pandas/_libs/tslibs/offsets.pyx
  pandas/_libs/tslibs/period.pyx
  pandas/_libs/tslibs/timedeltas.pyx
  pandas/core/arrays/arrow/array.py
  pandas/core/arrays/string_.py
  pandas/core/arrays/string_arrow.py
  pandas/core/dtypes/common.py
  pandas/core/frame.py
  pandas/core/generic.py
  pandas/core/internals/__init__.py
  pandas/core/internals/api.py
  pandas/core/internals/blocks.py
  pandas/core/resample.py
  pandas/core/series.py
  pandas/io/stata.py
  pandas/tests/arrays/test_datetimes.py
  pandas/tests/dtypes/test_common.py
  pandas/tests/dtypes/test_dtypes.py
  pandas/tests/dtypes/test_inference.py
  pandas/tests/extension/decimal/test_decimal.py
  pandas/tests/frame/methods/test_astype.py
  pandas/tests/frame/methods/test_reindex.py
  pandas/tests/frame/test_block_internals.py
  pandas/tests/frame/test_stack_unstack.py
  pandas/tests/indexes/datetimes/methods/test_snap.py
  pandas/tests/indexes/datetimes/test_date_range.py
  pandas/tests/indexes/period/test_constructors.py
  pandas/tests/indexes/period/test_period_range.py
  pandas/tests/indexes/timedeltas/test_constructors.py
  pandas/tests/indexes/timedeltas/test_indexing.py
  pandas/tests/indexes/timedeltas/test_scalar_compat.py
  pandas/tests/indexes/timedeltas/test_setops.py
  pandas/tests/indexes/timedeltas/test_timedelta_range.py
  pandas/tests/internals/test_api.py
  pandas/tests/internals/test_internals.py
  pandas/tests/io/parser/test_parse_dates.py
  pandas/tests/io/test_stata.py
  pandas/tests/resample/test_datetime_index.py
  pandas/tests/scalar/period/test_period.py
  pandas/tests/scalar/timedelta/test_constructors.py
  pandas/tests/scalar/timedelta/test_timedelta.py
  pandas/tests/series/methods/test_map.py
  pandas/tests/strings/test_strings.py
  pandas/tests/tools/test_to_timedelta.py
  pandas/tests/tslibs/test_to_offset.py
  pandas/tests/window/test_groupby.py
  pandas/tests/window/test_rolling.py
Labels: Warnings

#62193 Backport PR #62190: TST: Adjust test_round for Numpy 2.4 behavior
  pandas/tests/copy_view/test_methods.py
Labels: Testing

#62181 CI: Fix scripts tests when running from another directory
  scripts/tests/test_validate_min_versions_in_sync.py
  scripts/tests/test_validate_unwanted_patterns.py
  scripts/validate_min_versions_in_sync.py
Labels: Testing, CI

#62179 DOC: Add change in .values to the string migration guide
  doc/source/user_guide/migration-3-strings.rst
Labels: Docs, Strings

#62199 Backport PR #62179 on branch 2.3.x (DOC: Add change in .values to the string migration guide)
  doc/source/user_guide/migration-3-strings.rst
Labels: Docs, Strings

#62201 CLN: Enforce deprecation of DataFrame.idxmin/max with EAs and axis=1
  pandas/core/frame.py
  pandas/core/groupby/groupby.py
  pandas/tests/frame/test_reductions.py
  pandas/tests/groupby/test_reductions.py
  pandas/tests/groupby/transform/test_transform.py
Labels: Clean, ExtensionArray, Reduction Operations

#62211 TYP: Typing fixes and improvements related to ``scipy.interpolate``
  pandas/core/missing.py
Labels: Typing
